### ISSUE TITLE
Crushed 

### ISSUE THREAD

**Issue by SSUHOY** [TeamNewPipe/NewPipe#10034]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

Latest

### Steps to reproduce the bug

1. Go to app
2. Start the app 
3. Click search button
4. Crushed...

### Expected behavior

Crached after a few seconds after start app

**Comment by Frivolous2** [comment]
Happens to me as well, appears to be intermittent

Galaxy A52s, Android 13, NewPipe version 0.25.1

Logs:
<details>
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ BG
* __Content Language:__ en-
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.25.1
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.RelativeLayout org.schabi.newpipe.databinding.PlaylistHeaderBinding.getRoot()' on a null object reference
	at org.schabi.newpipe.fragments.list.playlist.PlaylistFragment.handleResult(PlaylistFragment.java:279)
	at org.schabi.newpipe.fragments.list.playlist.PlaylistFragment.handleResult(PlaylistFragment.java:67)
	at org.schabi.newpipe.fragments.list.BaseListInfoFragment.lambda$startLoading$0(BaseListInfoFragment.java:148)
	at org.schabi.newpipe.fragments.list.BaseListInfoFragment.$r8$lambda$Gn1fP3-8OJnktT5gkmUmbW-egTg(BaseListInfoFragment.java:0)
	at org.schabi.newpipe.fragments.list.BaseListInfoFragment$$ExternalSyntheticLambda4.accept(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```
</details>
</details>
<hr>
