### ISSUE TITLE
No feed loading; no videos; loading forever; NewPipe not working

### ISSUE THREAD

**Issue by Dan-TBA** [TeamNewPipe/NewPipe#10090]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.1 and all other older versions lile 0.22.0 etc

### Steps to reproduce the bug

By opening NewPipe app itself.

### Expected behavior

To load videos and content obviously in search tab and in Trending tab or whatever page your on. Playlist, comments and search results should come up when i seaech for something.

### Actual behavior

Search results should come up when typed in search bar, videos should also open from links or even load, Trending should load or feeds whatever you call it. 

It takes forever to load in the trending tab or search tab, it might be a problem with the app, But I am trying to find a solution to this problem for past an hour.

Some people suggested to turn on "Fetch from dedicated feed when available" setting and set the "Feed Update Threshold" to 'Always update'. I am out of solutions too.

Yes, I tried:
1) Re-opening the app.
2) Clearing storage data and cache.
3) Un-installing and Re-installing the app.
4) Installing NewPipe on other android devices: [Samsung Galaxy Tab 4 10.1 3G Lineage OS 16.0 Android 9 Pie] and [Infinix Hot 10s ~ Stock ROM ~ Android 11].
5) Rebooting the tablet/device
6) Clearing cache in TWRP
7) Using VPN (Calyx VPN, free open source app from android foss github)
8) Disabling and Re-enabling Wi-Fi network.
9) Opening NewPipe with links or from Share option in youtube.

~ Also!~: Somehow, the feeds load halfway in both Trending page and on Search page (only video titles, no thumbnail and no descriptions or comments when opening video, only the loading icon) if do this steps: (down below)

🔷 (I turned on "Fetch from dedicated feeds when available" and set "Feeds Update Threshold" to Always Update dor this to happen, otherwise nope)

It only occurs when I:
1) Run NewPipe with VPN for like 1-2 minutes
2) Turning off VPN
3) Coming back to NewPipe and wait there for 1-2 minutes more,

THEN after all that, video titles appears only. Does not work when using normal Wi-Fi connection.

### Logs

There were multiple types of bugs involved in this problem, all the bugs refers to network error and could nor parse website meaning it has to do with the servers.

## Exception
* __User Action:__ requested stream
* __Request:__ https://youtu.be/0xSJx54N6Gk opened with popup_player
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ YouTube
* __Version:__ 0.25.1
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not store JavaScript player
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.storePlayerJs(YoutubeStreamExtractor.java:1105)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.initStsFromPlayerJsIfNeeded(YoutubeStreamExtractor.java:1173)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:817)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:78)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:73)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:121)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda11.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5375)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15917)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5375)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn.subscribeActual(SingleObserveOn.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4803)
	at org.schabi.newpipe.RouterActivity$FetcherService.handleChoice(RouterActivity.java:984)
	at org.schabi.newpipe.RouterActivity$FetcherService.onHandleIntent(RouterActivity.java:956)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.os.HandlerThread.run(HandlerThread.java:65)
Caused by: org.schabi.newpipe.extractor.exceptions.ParsingException: Embedded info did not provide YouTube player js url
	at org.schabi.newpipe.extractor.services.youtube.YoutubeJavaScriptExtractor.extractJavaScriptUrl(YoutubeJavaScriptExtractor.java:116)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeJavaScriptExtractor.extractJavaScriptCode(YoutubeJavaScriptExtractor.java:46)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeJavaScriptExtractor.extractJavaScriptCode(YoutubeJavaScriptExtractor.java:65)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.storePlayerJs(YoutubeStreamExtractor.java:1103)
	... 31 more

```
</details>
<hr>

![Screenshot_20230512-094225_NewPipe_channel-tabs](https://github.com/TeamNewPipe/NewPipe/assets/82999543/6604d1c3-5e5d-43c6-a2ce-223f9a0e5a52)

### Affected Android/Custom ROM version

Android 9 Pie/ Lineage OS 16.0

### Affected device model

Amazon Fire HD7 9th Gen 2019

**Comment by ctntt** [comment]
Calyx VPN is very slow. I wouldn't recommend using it with NewPipe. I can reproduce this when using Calyx VPN but when it is turned off everything works fine.

**Comment by Dan-TBA** [comment]
@ctntt Well it does not work for me and I really need a downloader like NewPipe to download my favourite musics man, I am having problems today.

**Comment by ctntt** [comment]
> Also consider suggesting better VPN for me to choose? <;D

I have tried using NewPipe with the free locations on Proton VPN and it worked fine for me. The only downside compared to CalyxVPN is that you need a Proton account.

**Comment by escalinci** [comment]
I've been having quite a slow experience with Newpipe recently too. Not always, but usually, youtube thumbnails take a long time to load, and videos take a long time to start. Once a video has started, though, it plays back at normal speed and doesn't seem affected by any unusual restrictions (e.g. seeking is a fast as usual).

I'm not using any sort of VPN (does Newpipe itself make use of a VPN?), and since this wasn't a crash I don't think there's any sort of log I can post here?
Device is a Samsung SM-X200, on Android 13, and Newpipe v0.25.1

**Comment by mdk97** [comment]
This is happening to me too when I'm on WiFi. 
Works fine on mobile network (LTE)

**Comment by Dan-TBA** [comment]
> I've been having quite a slow experience with Newpipe recently too. Not always, but usually, youtube thumbnails take a long time to load, and videos take a long time to start. Once a video has started, though, it plays back at normal speed and doesn't seem affected by any unusual restrictions (e.g. seeking is a fast as usual).
> 
> I'm not using any sort of VPN (does Newpipe itself make use of a VPN?), and since this wasn't a crash I don't think there's any sort of log I can post here?
> Device is a Samsung SM-X200, on Android 13, and Newpipe v0.25.1

Dude, After Android 9, android versions 10 to 13 and later are like buggy, especially with custom roms. Even android 10 to 13 of most stable rom "Lineage OS" is buggy, Or if not buggy and fast, Not stable especiqly with installing apps and stuff. For me android 9 worked flawlessly all the time in my tablet. Hope eres a custom rom out there for your Samsung phone

**Comment by Foliage-cloud** [comment]
I have this same issue. I don't use a VPN though.

**Comment by Dan-TBA** [comment]
> 
@opusforlife2's question's answer: No, no i don't use adblock service on my rooted fire tablet. I don't have mobile data or cellular network yet. And I also don't have a friend to use his/her wifi network.

I'm using a very slow tablet, so it's useless for me to use extra services like that. (And it never worked for me anyway, plus I was too lazy to find a solution for adblock service fix to make it work, so yeah.)

**Comment by nafijninja** [comment]
error
## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=gVkdO7ZyvGU
* __Content Country:__ BD
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ YouTube
* __Version:__ 0.27.5
* __OS:__ Linux Android 5.1.1 - 22
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ExtractionException: IOS player response is not valid
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.fetchIosMobileJsonPlayer(YoutubeStreamExtractor.java:974)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:830)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:77)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:118)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$bVfA-5gb6gDc8jcAgcGWG5oH0FE(ExtractorHelper.java:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda3.call(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5377)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16144)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5377)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

```
</details>
<hr>

**Comment by nafijninja** [comment]
error
## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=gVkdO7ZyvGU
* __Content Country:__ BD
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ YouTube
* __Version:__ 0.27.5
* __OS:__ Linux Android 5.1.1 - 22
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ExtractionException: IOS player response is not valid
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.fetchIosMobileJsonPlayer(YoutubeStreamExtractor.java:974)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:830)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:77)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:118)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$bVfA-5gb6gDc8jcAgcGWG5oH0FE(ExtractorHelper.java:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda3.call(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5377)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16144)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5377)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

```
</details>
<hr>
