### ISSUE TITLE
Casting not working

### ISSUE THREAD

**Issue by whois-bogeyman** [TeamNewPipe/NewPipe#10127]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.1

### Steps to reproduce the bug

Just clicked on casting icon and application crashes.

### Expected behavior

Casting 

### Actual behavior

Crashing each time 

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.25.1
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1351)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:405)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:148)
	at android.app.Dialog.show(Dialog.java:370)
	at org.schabi.newpipe.util.external_communication.KoreUtils.playWithKore(KoreUtils.java:68)
	at org.schabi.newpipe.player.ui.VideoPlayerUi.onPlayWithKodiClicked(VideoPlayerUi.java:1423)
	at org.schabi.newpipe.player.ui.VideoPlayerUi.$r8$lambda$5s0hWnw57M8ioWfqWKDNzOAvxy0(VideoPlayerUi.java:0)
	at org.schabi.newpipe.player.ui.VideoPlayerUi$$ExternalSyntheticLambda22.run(R8$$SyntheticClass:0)
	at org.schabi.newpipe.player.ui.VideoPlayerUi.lambda$makeOnClickListener$26(VideoPlayerUi.java:1336)
	at org.schabi.newpipe.player.ui.VideoPlayerUi.$r8$lambda$-liQzwojzgb3c-WB0sRgyQOP0b4(VideoPlayerUi.java:0)
	at org.schabi.newpipe.player.ui.VideoPlayerUi$$ExternalSyntheticLambda39.onClick(R8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:7558)
	at android.view.View.performClickInternal(View.java:7534)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29661)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8381)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

```
</details>
<hr>

**Comment by Zyban117** [comment]
What are you casting on?

**Comment by GolemancerVekk** [comment]
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.25.2
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1075)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:409)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:110)
	at android.app.Dialog.show(Dialog.java:340)
	at androidx.appcompat.app.AlertDialog$Builder.show(AlertDialog.java:1009)
	at org.schabi.newpipe.util.external_communication.KoreUtils.playWithKore(KoreUtils.java:69)
	at org.schabi.newpipe.player.ui.VideoPlayerUi.onPlayWithKodiClicked(VideoPlayerUi.java:1495)
	at org.schabi.newpipe.player.ui.VideoPlayerUi.$r8$lambda$Ah5-AMSNj8xTdhW85LEN89TEhsk(VideoPlayerUi.java:0)
	at org.schabi.newpipe.player.ui.VideoPlayerUi$$ExternalSyntheticLambda21.run(R8$$SyntheticClass:0)
	at org.schabi.newpipe.player.ui.VideoPlayerUi.lambda$makeOnClickListener$27(VideoPlayerUi.java:1408)
	at org.schabi.newpipe.player.ui.VideoPlayerUi.$r8$lambda$PsCE_Yd-jcDxLdmShO83lTESJIk(VideoPlayerUi.java:0)
	at org.schabi.newpipe.player.ui.VideoPlayerUi$$ExternalSyntheticLambda38.onClick(R8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:7463)
	at android.view.View.performClickInternal(View.java:7432)
	at android.view.View.access$3600(View.java:817)
	at android.view.View$PerformClick.run(View.java:28324)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:7730)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

```
</details>
<hr>

**Comment by GolemancerVekk** [comment]
I am not the original author but I've added a bug report here too.

If it helps, I'm trying to cast from a Sony Xperia 10 III to a Chromecast gen2.

**Comment by GolemancerVekk** [comment]
I've submitted #10388 .
