### ISSUE TITLE
Do not steal focus to report a guru meditation

### ISSUE THREAD

**Issue by rpdelaney** [TeamNewPipe/NewPipe#10135]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.1

### Steps to reproduce the bug

I'm not sure unfortunately. I was watching videos last night and today I have the problem described below with the background process. I'm happy to experiment if anyone can make suggestions. 

### Expected behavior

When an unhandled exception occurs, NewPipe should print a guru meditation without stealing focus or switching me out of the app I'm working on. 

### Actual behavior

Today I'm driving my car navigating with a maps app. NewPipe repeatedly takes over the screen every few minutes to print a guru meditation. I had to pull off the road and force kill the app to get it to stop. This is dangerous and annoying.

To be clear, it's not important what the error was about. Errors happen. When they happen, NewPipe should not ever steal focus. 

### Affected Android/Custom ROM version

grapheneOS.org

### Affected device model

Pixel 6

**Comment by 1537hasnain** [comment]
Brother please send Api

**Comment by rpdelaney** [comment]
I was driving and not using the app at all. Since I needed to get to my destination on time I did not bother to copy the error log. No matter what the content of the stack trace might be, NewPipe should not ever steal focus like this.

**Comment by rpdelaney** [comment]
A notification could be reasonable to cover the use case where someone needs to know that NewPipe is no longer running in the background. Ideally, DND mode would suppress that notification as well: in my case, I did not care at all what was going on with NewPipe at that time, which made the focus-stealing especially heavy-handed and frustrating.

**Comment by mitchellcairns** [comment]
It's not clear how this is replicated. The error will display when NewPipe is completely closed and hasn't been operating. First, fix the issue of the app stealing focus to display errors, second we can go through and determine what the issues actually are.

**Comment by Stypox** [comment]
> I think that's the most straightforward solution, @Stypox?

Yes, although I am not sure there is a simple way to distinguish whether the app was in foreground or not AFTER it has crashed.

**Comment by rpdelaney** [comment]
Okay, I just had it happen again. I'm able to copy the stack trace.

I want to emphasize that it is not enough to fix this particular error. The point is that taking focus is a bad thing to do when an error occurred. There will be more errors and bugs: handling them gracefully is at least as important to the user experience as anything else. Therfore I'm putting this here in case the error itself has any clues about why NewPipe is taking focus. 

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.25.1
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{f892f11 u0 org.schabi.newpipe/.player.PlayerService}
	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2009)
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1983)
	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2245)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7903)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1936)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1891)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822)
	at androidx.core.content.ContextCompat$Api26Impl$$ExternalSyntheticApiModelOutline0.m(R8$$SyntheticClass:0)
	at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:931)
	at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:703)
	at androidx.media.session.MediaButtonReceiver.onReceive(MediaButtonReceiver.java:115)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4311)
	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2157)
	... 9 more

```
</details>
<hr>

**Comment by GameOverFlowChart** [comment]
I know a way to reproduce this problem.

Step 1:
Have NewPipe in background without playing any video (not just paused)

Step 3:
Press the play button on the Bluetooth headphones (by accident or not)

Step 4:
Wait a while, it really takes some time

Step 5:
NewPipe will crash and steal the focus from which ever app was open to show guru meditation

**Comment by Wazhai** [comment]
The core of the issue is NewPipe popping up with a full screen crash report while the app isn't in the foreground. For me this usually happens **hours or even days after I last opened the app**, and often repeatedly until I go and kill NewPipe manually. Most users won't care enough or have the skills to report it properly, making the unprompted focus-stealing pop-up solely a major nuisance.

**Comment by atomizer** [comment]
> Step 3: Press the play button on the Bluetooth headphones (by accident or not)
Another annoying thing (though less annoying than the crash jumpscare) is that the button press gets stolen even if there was an eligible background media app that was used more recently. You have to open the app and resume playback manually.

**Comment by Coehill** [comment]
I'm experiencing this same issue on Android 14 (happened on Android 13 too) and have been for many months now.  I'll try to remember to attach a log to this ticket next time.  I find it difficult since it's usually when I'm driving.  I wonder if it has to do with Google Maps or Waze since it never happens with OSM or OrganicMaps for me...

**Comment by rpdelaney** [comment]
I use OSMAND and it happens frequently.  [This](https://github.com/TeamNewPipe/NewPipe/issues/10135#issuecomment-1591275276) repro seems to be accurate.

**Comment by akidee** [comment]
This is a major issue and a very bad practice, in addition to the fact that the app has some serious bugs. This lets me regularly force-stop the app and then deleting all app data.
