### ISSUE TITLE
java.lang.IllegalArgumentException: Play Queue has not been initialized.

### ISSUE THREAD

**Issue by zolagonano** [TeamNewPipe/NewPipe#10222]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.1

### Steps to reproduce the bug

It sometimes happens when playing a youtube video

## Exception
* User Action: ui error
* Request: ACRA report
* Content Country: US
* Content Language: en-
* App Language: en_US
* Service: none
* Version: 0.25.1
* OS: Linux Nokia
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalArgumentException: Play Queue has not been initialized.
 at org.schabi.newpipe.player.playback.MediaSourceManager.<init>(MediaSourceManager.java:141)
 at org.schabi.newpipe.player.playback.MediaSourceManager.<init>(MediaSourceManager.java:130)
 at org.schabi.newpipe.player.Player.reloadPlayQueueManager(Player.java:618)
 at org.schabi.newpipe.player.ui.VideoPlayerUi.onMenuItemClick(VideoPlayerUi.java:1207)
 at androidx.appcompat.widget.PopupMenu$1.onMenuItemSelected(PopupMenu.java:113)
 at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:836)
 at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:159)
 at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:987)
 at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
 at android.widget.AdapterView.performItemClick(AdapterView.java:330)
 at android.widget.AbsListView.performItemClick(AbsListView.java:1197)
 at android.widget.AbsListView$PerformClick.run(AbsListView.java:3210)
 at android.widget.AbsListView.onTouchUp(AbsListView.java:4188)
 at android.widget.AbsListView.onTouchEvent(AbsListView.java:3929)
 at androidx.appcompat.widget.DropDownListView.onTouchEvent(DropDownListView.java:225)
 at androidx.appcompat.widget.MenuPopupWindow$MenuDropDownListView.onTouchEvent(MenuPopupWindow.java:140)
 at android.view.View.dispatchTouchEvent(View.java:15056)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3168)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2810)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3174)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2824)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3174)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2824)
 at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2570)
 at android.view.View.dispatchPointerEvent(View.java:15320)
 at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6740)
 at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6521)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5973)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6030)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5996)
 at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6161)
 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6004)
 at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6218)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5977)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6030)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5996)
 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6004)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5977)
 at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9131)
 at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9082)
 at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9037)
 at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9263)
 at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
 at android.os.MessageQueue.nativePollOnce(Native Method)
 at android.os.MessageQueue.next(MessageQueue.java:335)
 at android.os.Looper.loopOnce(Looper.java:161)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7941)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 13

### Affected device model

Nokia G20

**Comment by zolagonano** [comment]
> > It sometimes happens when playing a youtube video
> 
> We'll probably need more than that. Try to find out if there are definite steps that cause this bug.

It happens quite randomly, I don't know how i can reproduce it
