### ISSUE TITLE
Release v0.25.2 (please TEST!)

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipe#10284]
## Testing for regressions

Debug APK (GH Actions): [NewPipe_v0.25.2_RC1.zip](https://github.com/TeamNewPipe/NewPipe/files/12222674/NewPipe_v0.25.2_RC1.zip)

Please report **only regressions** (i.e. new issues) here, not issues that were already present in previous releases!

## TODO
- [ ] Merge weblate

<details><summary><h2>App changelog </h2></summary>

### New
- Allow setting volume and brightness gestures on any side of the screen #9708
- Add an ExoPlayer settings page #8875 #10122
- Add support for multiple audio tracks #9937 #10230
- Add support for displaying main-tabs at the bottom of the screen #9719

### Improved
- Add whitelist to only retrieve supported YouTube itags/streams #9748
- [YouTube] Improve download speed #9948
- [PeerTube] Handle links to the instance “peertube.stream” #10141
- Fix a memory leak in the player #10232
- Disable media tunneling by default on more known unsupported devices #10122

### Fixed
- [PeerTube] Fix uploader and subchannel avatars being swapped and disable loading thumbnail message failure on content details page #10066
- Fix crash after feed update #10229
- Fix no video in player when switching to main player from playlist view #10195

### Localization
- Update translations #10074
- Add new language ߒߞߏ / N'Ko (nqo) to the language chooser  #10042
- Translate README into new languages and update a few translations #9421 #9897 #10240 #10250
- Add Uchinaguchi translation #10250

### Development
- Remove jsoup files from APK #10004
- Update to Kotlin to 1.8.20 and AndroidX Core to 1.10 and switch to AndroidX's `PendingIntentCompat` #10021
- Upgrade Gradle and AGP from 7.x to 8.x and use Java 17 #10035 #10067
- Update ACRA to 5.10.1 and Checkstyle to 10.12.1 to fix a dependency vulnerability #10200
- Update screenshots #10213
- Add support for new GitHub assets URLs in image minimizer workflow & minimize images in PR descriptions #10166 #10233 
- Add link to wiki page for APK download #10219
- Clean up `AlertDialog`s #10223
- Update LeakCanary library #10085 #10232
- Add database test for `SubscriptionManager` #8456
- Update AndroidX Room library #10235
- Use Okio 3.4.0 explicitly to fix a vulnerability #10281
</details>

<details><summary><h2>NewPipe Extractor changelog </h2></summary>
### New
- [YouTube] Add support for `CarouselHeaderRenderer` TeamNewPipe/NewPipeExtractor#1050
- Extract playlists description TeamNewPipe/NewPipeExtractor#1061

### Improved
-  [PeerTube] Don't return "No description" when there is no description for a channel or an account  TeamNewPipe/NewPipeExtractor#1055
- Add more audio media formats and `MediaFormat.getAllForMimeType(mimeType)`  TeamNewPipe/NewPipeExtractor#1074 
- [YouTube] Check whether player responses are valid for all InnerTube clients used  TeamNewPipe/NewPipeExtractor#1070
-  Add support for AV1 itags.  TeamNewPipe/NewPipeExtractor#706 

### Fixed
- [Bandcamp] Handle paywalled tracks  TeamNewPipe/NewPipeExtractor#1033
- [YouTube] Fix YouTube Music client version extraction from HTML page  TeamNewPipe/NewPipeExtractor#1051
- [PeerTube] Fix multi level comment replies  TeamNewPipe/NewPipeExtractor#1052
- [YouTube] Extract trends from A/B tested "Videos" tab and fix extraction of trends name from A/B tested new title design  TeamNewPipe/NewPipeExtractor#1045
- [YouTube] Fix parsing short relative date formats (English only)  TeamNewPipe/NewPipeExtractor#1068
- [YouTube] Support multiple declarations for throttling parameter function name array  TeamNewPipe/NewPipeExtractor#1076
- [YouTube] Workaround again 403 HTTP issues on the ANDROID InnerTube client and fix stream tests  TeamNewPipe/NewPipeExtractor#1084  

### Development
- Bump junit-bom from 5.9.2 to 5.9.3  TeamNewPipe/NewPipeExtractor#1053
- Make sure CI is not vulnerable to bash word splitting  TeamNewPipe/NewPipeExtractor#1054
- Bump jsoup from 1.15.4 to 1.16.1  TeamNewPipe/NewPipeExtractor#1058
- Fix `BandcampRadioStreamExtractorTest.testGetAudioStreams()`  TeamNewPipe/NewPipeExtractor#1072 
- Initialize services at the correct place  TeamNewPipe/NewPipeExtractor#1071 
- Add proguard rules to README  TeamNewPipe/NewPipeExtractor#1080 

</details>

**Comment by TheHCJ** [comment]
## Exception
* __User Action:__ requested channel
* __Request:__ Start loading: https://www.youtube.com/channel/UCXAWX5r69jcqPTNAhXCSA7Q
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ YouTube
* __Version:__ 0.25.2
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get banner
 at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.lambda$getBannerUrl$10(YoutubeChannelExtractor.java:285)
 at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor$$ExternalSyntheticLambda8.get(Unknown Source:0)
 at j$.util.Optional.orElseThrow(Optional.java:408)
 at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.getBannerUrl(YoutubeChannelExtractor.java:285)
 at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:83)
 at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:55)
 at org.schabi.newpipe.util.ExtractorHelper.lambda$getChannelInfo$4(ExtractorHelper.java:127)
 at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda5.call(Unknown Source:4)
 at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
 at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
 at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
 at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
 at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
 at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5377)
 at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
 at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
 at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
 at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
 at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16013)
 at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
 at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5377)
 at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
 at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
 at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
 at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
 at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
 at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
 at java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
 at java.lang.Thread.run(Thread.java:1012)

```
</details>
<hr>

**Comment by Sir-Alex-L** [comment]
Not sure if related to fix #10174

I can recreate the crash 100% but the errors say different things depending on release. 

Method to recreate: Play any video/song in background. I usually test with hour long videos, but same thing happens with playlists. Play the video for a few minutes then pause. Leave the app running for few hours, I usually leave over night. Resume playback. It'll run for a few minutes then crash. You need to stop playback entirely and restart the playlist or video for it to work again.

Error on this Release Candidate, still reporting itself as 0.25.1:
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ CA
* __Content Language:__ en-
* __App Language:__ en_CA
* __Service:__ none
* __Version:__ 0.25.1
* __OS:__ Linux Android 8.1.0 - 27
<details><summary><b>Crash log </b></summary><p>

```
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1802)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6548)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)

```
</details>
<hr>



Error on the 25.1 version:
## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_BAD_HTTP_STATUS] occurred while playing https://www.youtube.com/watch?v=NjMPOO9WV7E
* __Content Country:__ CA
* __Content Language:__ en-
* __App Language:__ en_CA
* __Service:__ YouTube
* __Version:__ 0.25.1
* __OS:__ Linux Android 8.1.0 - 27
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:422)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:796)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:609)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:124)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

```
</details>
<hr>

**Comment by layingback** [comment]
Tested 25.2 on 2 videos stuck @ 1:19, including 1 which would not respond to Force Stop workaround. Both perfect. Thx! (Firestick 4K)

**Comment by disconnect5852** [comment]
Still not works, on xiaomi mi tv. I open a video, it plays, switch to full screen= error. Then always error until i reboot the device.
Model: MITV-AYFRO
Kernel version: 5.4.210-android12-9-g041469a404b2-ab1407 #1 Thu Jun 15 21:14:30 CST 2023
Android TV OS-build: RTTO.211222.001.1407 release-keys

**Comment by TobiGr** [comment]
Did you disable media tunneling in the ExoPlayer settings?

**Comment by disconnect5852** [comment]
> Did you disable media tunneling in the ExoPlayer settings?

i see, now it works! Mostly :)

**Comment by TobiGr** [comment]
@disconnect5852 That's good to hear. Please install this [APK](https://github.com/TeamNewPipe/NewPipe/files/11565524/app-debug.zip). Go to settings > debug  and use "Show device id" and post the model id here so we can ensure that media tunneling is disabled by default for the device model. It should differ from the model name you posted above, because the Android internal model names do not contain hyphens.
