### ISSUE TITLE
Newpipe crashes after 1 minute of opening any video

### ISSUE THREAD

**Issue by swissk** [TeamNewPipe/NewPipe#10334]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.1

### Steps to reproduce the bug

1. Go to newpipe
2.  Search for a video
3. Open video

### Expected behavior

It should run the entire video without problem

### Actual behavior

It crashes after the video has run for 1 minute. 

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_BAD_HTTP_STATUS] occurred while playing https://www.youtube.com/watch?v=CqqMRt1QwHs
* __Content Country:__ CH
* __Content Language:__ de-CH
* __App Language:__ de_CH
* __Service:__ YouTube
* __Version:__ 0.25.1
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:213)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:422)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:796)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:609)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:124)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 10

### Affected device model

Huawei P20 pro

**Comment by Michel-12** [comment]
Exact same issue on LG V30 running Android 9, execpt app does not crash, video just stops playing on version 0.25.1

**Comment by maxwelgordon** [comment]
Same issue on Samsung A71. About a minute I playing then stops and produces an error briefly saying to check notification on the error. There's no notifications of the error other than the inition that will flash briefly after every video stops playing

**Comment by ikskoder** [comment]
Same issue on Redmi Note 11 (Android 13, MIUI 14). About a minute video is playing then it stops without producing any errors. NewPipe v0.25.1

**Comment by hambudge** [comment]
Same issue today on Samsung S22

**Comment by SoulReaver01** [comment]
Same issue on my s21 ultra. With all of the genius creators floating around, i'm surprised a permanent fix hasn't been found as of yet. If my memory serves me correctly, I believe the issue has been going on for almost a year now? I've also seen this issue in some other forums too. No solutions posted in other forums either. Damn YouTube. Why can't they leave their app alone so that my favorite one, NewPipe, can work flawlessly again! 
I really do LOVE this app! It's really GREAT for what it does! It's the only app I use DAILY! Seriously! I use it to listen to Creepypasta stories all night until I fall asleep, music videos during the day, and other short videos and stuff here and there! It's one of the BEST apps EVER MADE! 100% TRUE

**Comment by viplo** [comment]
Same issue of one of my device (Huawei Mediapad 5), but the only one which isn't ungooglized.
May it helps.
