### ISSUE TITLE
Random "UI error" causes a crash

### ISSUE THREAD

**Issue by ek-is-anika** [TeamNewPipe/NewPipe#10355]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2

### Steps to reproduce the bug

1. Open the app as normally
2. Start downloading videos & subtitles
3. Use the app as normally (watch other videos, search, look at the download progress)
4. At any given backswipe to go to the previous screen (especially from the downloads progress view), the app will crash, and give an "UI error" 

### Expected behavior

The app should have worked normally, no crashes, et cetera.

### Actual behavior

The app will crash at any given time, especially if you look at the downloads view, and go back to the previous view by tapping back on the system nav bar.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ ZA
* __Content Language:__ en-ZA
* __App Language:__ en_ZA
* __Service:__ none
* __Version:__ 0.25.2
* __OS:__ Linux samsung/a33xnsdxx/a33x:13/TP1A.220624.014/A336EDXU6CWF1:user/release-keys 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service org.schabi.newpipe/us.shandian.giga.service.DownloadManagerService
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4787)
	at android.os.Parcel.readParcelable(Parcel.java:4755)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3018)
	at android.os.Parcel.createException(Parcel.java:3007)
	at android.os.Parcel.readException(Parcel.java:2990)
	at android.os.Parcel.readException(Parcel.java:2932)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6991)
	at android.app.Service.startForeground(Service.java:743)
	at us.shandian.giga.service.DownloadManagerService.updateForegroundState(DownloadManagerService.java:336)
	at us.shandian.giga.service.DownloadManagerService.handleMessage(DownloadManagerService.java:268)
	at us.shandian.giga.service.DownloadManagerService.$r8$lambda$gVT-KbstFlv6SWFsotFx97l7BIY(DownloadManagerService.java:0)
	at us.shandian.giga.service.DownloadManagerService$$ExternalSyntheticLambda2.handleMessage(R8$$SyntheticClass:0)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 13, with OneUI 5.1

### Affected device model

Samsung Galaxy A33 5G (SM-A336E)

**Comment by ZybanX** [comment]
I think android is preventing the service from starting in the foreground. This could be due to a restriction imposed by the Android system or by the app itself.

**Comment by ek-is-anika** [comment]
> I think android is preventing the service from starting in the foreground. This could be due to a restriction imposed by the Android system or by the app itself.
> 
> Edit: When leaving Newpipe, Samsung kills the app when not using to improve battery life. See the reference [here](https://dontkillmyapp.com/)

Didn't think of the shitty OneUI app management, but i'll definitely adjust the battery optimization settings for newpipe.
Though at some point (before this) I'd see a system pop-up telling me that the app isn't responding at random (I could be watching a video, or monitoring the downloads view and this would happen), then I knew if I were to swipe back, or tap back, the app will crash.

**Comment by ZybanX** [comment]
> > I think android is preventing the service from starting in the foreground. This could be due to a restriction imposed by the Android system or by the app itself.
> > 
> > Edit: When leaving Newpipe, Samsung kills the app when not using to improve battery life. See the reference [here](https://dontkillmyapp.com/)
> 
> Didn't think of the shitty OneUI app power management, but i'll definitely adjust the battery optimization settings for newpipe.
> Though at some point (before this) I'd see a system pop-up telling me that the app isn't responding at random (I could be watching a video, or monitoring the downloads view and this would happen), then I knew if I were to swipe back, or tap back, the app will crash.

See the reference [here](https://dontkillmyapp.com/samsung)

**Comment by T1z3n** [comment]
Same Issue here:

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ DE
* __Content Language:__ de-DE
* __App Language:__ de_DE
* __Service:__ none
* __Version:__ 0.27.2
* __OS:__ Linux Android 14 - 34
<details><summary><b>Crash log </b></summary><p>

```
android.os.BadParcelableException: Parcelable encountered IOException writing serializable object (name = org.schabi.newpipe.extractor.channel.ChannelInfo)
	at android.os.Parcel.writeSerializable(Parcel.java:2909)
	at android.os.Parcel.writeValue(Parcel.java:2675)
	at android.os.Parcel.writeValue(Parcel.java:2474)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1338)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1846)
	at android.os.Bundle.writeToParcel(Bundle.java:1390)
	at android.os.Parcel.writeBundle(Parcel.java:1407)
	at android.os.Parcel.writeValue(Parcel.java:2591)
	at android.os.Parcel.writeValue(Parcel.java:2481)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1338)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1846)
	at android.os.Bundle.writeToParcel(Bundle.java:1390)
	at android.os.Parcel.writeBundle(Parcel.java:1407)
	at android.os.Parcel.writeValue(Parcel.java:2591)
	at android.os.Parcel.writeValue(Parcel.java:2481)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1338)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1846)
	at android.os.Bundle.writeToParcel(Bundle.java:1390)
	at android.os.Parcel.writeBundle(Parcel.java:1407)
	at android.os.Parcel.writeValue(Parcel.java:2591)
	at android.os.Parcel.writeValue(Parcel.java:2481)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1338)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1846)
	at android.os.Bundle.writeToParcel(Bundle.java:1390)
	at android.os.Parcel.writeBundle(Parcel.java:1407)
	at android.os.Parcel.writeValue(Parcel.java:2591)
	at android.os.Parcel.writeValue(Parcel.java:2481)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1338)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1846)
	at android.os.Bundle.writeToParcel(Bundle.java:1390)
	at android.os.Parcel.writeBundle(Parcel.java:1407)
	at android.os.Parcel.writeValue(Parcel.java:2591)
	at android.os.Parcel.writeValue(Parcel.java:2481)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1338)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1846)
	at android.os.Bundle.writeToParcel(Bundle.java:1390)
	at android.os.Parcel.writeBundle(Parcel.java:1407)
	at android.os.Parcel.writeValue(Parcel.java:2591)
	at android.os.Parcel.writeValue(Parcel.java:2481)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1920)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1957)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.collectBundleStates(PendingTransactionActions.java:123)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:139)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.io.NotSerializableException: org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at java.util.ArrayList.writeObject(ArrayList.java:955)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1079)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1568)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at android.os.Parcel.writeSerializable(Parcel.java:2904)
	... 52 more

```
</details>
<hr>

**Comment by ShareASmile** [comment]
Reopening due to more reports of this issue in #12753 #12524 , but they lack steps of reproduction so let us reopen it.

**Comment by ShareASmile** [comment]
@tct123 @VladaZemunac coming from your's respective issues #12753 #12524 please write your steps of reproduction with what did you do before crash occured? Even if you don't know what exactly lead to bug it would be helpful to know what you were doing"
