### ISSUE TITLE
Casting crashes every time

### ISSUE THREAD

**Issue by GolemancerVekk** [TeamNewPipe/NewPipe#10388]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2

### Steps to reproduce the bug

1. Play any YouTube video.
2. Expand the video controls.
3. Tap the cast button.

### Expected behavior

Cast the video to Chromecast gen2.

### Actual behavior

App crashes.

### Logs

Attempting to cast to a Chromecast gen2 from a Sony Xperia 10 III phone.
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.25.2
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1075)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:409)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:110)
	at android.app.Dialog.show(Dialog.java:340)
	at androidx.appcompat.app.AlertDialog$Builder.show(AlertDialog.java:1009)
	at org.schabi.newpipe.util.external_communication.KoreUtils.playWithKore(KoreUtils.java:69)
	at org.schabi.newpipe.player.ui.VideoPlayerUi.onPlayWithKodiClicked(VideoPlayerUi.java:1495)
	at org.schabi.newpipe.player.ui.VideoPlayerUi.$r8$lambda$Ah5-AMSNj8xTdhW85LEN89TEhsk(VideoPlayerUi.java:0)
	at org.schabi.newpipe.player.ui.VideoPlayerUi$$ExternalSyntheticLambda21.run(R8$$SyntheticClass:0)
	at org.schabi.newpipe.player.ui.VideoPlayerUi.lambda$makeOnClickListener$27(VideoPlayerUi.java:1408)
	at org.schabi.newpipe.player.ui.VideoPlayerUi.$r8$lambda$PsCE_Yd-jcDxLdmShO83lTESJIk(VideoPlayerUi.java:0)
	at org.schabi.newpipe.player.ui.VideoPlayerUi$$ExternalSyntheticLambda38.onClick(R8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:7463)
	at android.view.View.performClickInternal(View.java:7432)
	at android.view.View.access$3600(View.java:817)
	at android.view.View$PerformClick.run(View.java:28324)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:7730)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 11 / Sony

### Affected device model

Xperia 10 III

### Additional information

Similar issue with inactive reporter is #10127 .

**Comment by whatistime** [comment]
I have same crash issue from my Samsung S22 Ultra (up to date stock) to google home smart speakers (I have 4)

**Comment by just-grizzle** [comment]
Same here. I can't select which target device to cast to, NewPipe crashes when clicking the icon.


<details><summary>Logs</summary>
<p>
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ DE
* __Content Language:__ de-DE
* __App Language:__ de_DE
* __Service:__ none
* __Version:__ 0.26.0
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1235)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:403)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:134)
	at android.app.Dialog.show(Dialog.java:374)
	at androidx.appcompat.app.AlertDialog$Builder.show(AlertDialog.java:1009)
	at org.schabi.newpipe.util.external_communication.KoreUtils.playWithKore(KoreUtils.java:69)
	at org.schabi.newpipe.player.ui.VideoPlayerUi.onPlayWithKodiClicked(VideoPlayerUi.java:1522)
	at org.schabi.newpipe.player.ui.VideoPlayerUi.$r8$lambda$Ah5-AMSNj8xTdhW85LEN89TEhsk(VideoPlayerUi.java:0)
	at org.schabi.newpipe.player.ui.VideoPlayerUi$$ExternalSyntheticLambda21.run(R8$$SyntheticClass:0)
	at org.schabi.newpipe.player.ui.VideoPlayerUi.lambda$makeOnClickListener$27(VideoPlayerUi.java:1435)
	at org.schabi.newpipe.player.ui.VideoPlayerUi.$r8$lambda$PsCE_Yd-jcDxLdmShO83lTESJIk(VideoPlayerUi.java:0)
	at org.schabi.newpipe.player.ui.VideoPlayerUi$$ExternalSyntheticLambda38.onClick(R8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:7753)
	at android.view.View.performClickInternal(View.java:7730)
	at android.view.View.access$3700(View.java:861)
	at android.view.View$PerformClick.run(View.java:29146)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8293)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

```
</details>
<hr>
</p>
</details>

**Comment by GfEW** [comment]
I'm getting the same `Unable to add window -- token null is not valid` error when touching the cast button during pause or playback on a plain Android 9 phone **without any casting device**.

Should you prefer me to report this in a separate issue, please let me now.

**Comment by hugdubois** [comment]
Any news about that?

**Comment by zuavra** [comment]
Still crashing.

**Comment by Cris--** [comment]
And....still crashing with NewPipe v.0.28.0-1076-202511200116 nightly.
Same with Tubular or official release of NewPipe. 😓

ASOP A16
