### ISSUE TITLE
App/UI crashes on startup repeatedly

### ISSUE THREAD

**Issue by cipher-source** [TeamNewPipe/NewPipe#10463]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2

### Steps to reproduce the bug

1. Open the NewPipe Application and wait for about 2 seconds.
2. The App/UI crashes and shows the error report.
3. This process can only be repeated and no interaction stops the crash.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ PT
* __Content Language:__ pt-PT
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.25.2
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Canvas: trying to draw too large(125516160bytes) bitmap.
	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:266)
	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:94)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:549)
	at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:109)
	at android.widget.ImageView.onDraw(ImageView.java:1446)
	at com.google.android.material.imageview.ShapeableImageView.onDraw(ShapeableImageView.java:198)
	at android.view.View.draw(View.java:23266)
	at android.view.View.updateDisplayListIfDirty(View.java:22133)
	at android.view.View.draw(View.java:22997)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
	at android.view.View.draw(View.java:23269)
	at android.view.View.updateDisplayListIfDirty(View.java:22133)
	at android.view.View.draw(View.java:22997)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5204)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23269)
	at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4603)
	at android.view.View.updateDisplayListIfDirty(View.java:22133)
	at android.view.View.draw(View.java:22997)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22124)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22089)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22089)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22089)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22089)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22089)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22089)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22089)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22089)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22089)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4513)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4486)
	at android.view.View.updateDisplayListIfDirty(View.java:22089)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:689)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:695)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:793)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4785)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4496)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3683)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2367)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9293)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 13

### Affected device model

Pixel Tablet

### Additional information

- the error occurred from time to time and sometimes goes away
- rebooting the device does not help to fix the bug
- installed GrapheneOS on my device
- encountered the bug in previous versions already but it goes away from time to time
- once it is prevalent, the application is not usable for hours to the best of my knowledge
- both landscape and portrait mode result in this crash

**Comment by cipher-source** [comment]
> Does it happen on another OS?

I haven't tried it out, I only use GrapheneOs.

**Comment by inubu** [comment]
I had the same issue on **/e/ OS 1.15-s (LineageOS 19)** and **CalyxOS 4.14 (AOSP 13)**. It seems not be a problem of one particular OS. 
I think it is the thumbnail of one of the videos.

Workaround: Close NewPipe, put phone into aeroplane mode, open NewPipe, go to Settings, Content and Disable "Load thumbnails", now disable aeroplane mode.
NewPipe don't crash, after I disabled "Load thumbnails"

It only crashes on a certain thumbnail, but I have around 125 subscriptions.
I figured out, what channel it is and unsubscribed it, while in aeroplane mode. After that NewPipe don't crash anymore.
But if I just subscribe only to that one channel, there is no issue at all. Maybe someone with the same amount of subscription can trigger it. In my case it's the "Dust" channel, they publish Sci-Fi short films.

**Comment by gschwaer** [comment]
> Does it happen on another OS?

I have this issue on stock Android 13 on Pixel 6a.

Thank you @inubu for the workaround!

**Comment by inubu** [comment]
> @inubu The channel itself opens just fine for you?

Yes. I resetted NewPipe and just added "Dust" to the subscription list. No problem. It has nothing to do with a particular channel. I think it's a combination of thumbnails. 
And the issue is now gone. I can't test anymore. That's bad. 
The "What's new" Tab had that issue.
I saw how thumbnails got loaded one by one and then NewPipe crashed. But now everything is fine again. Well, that's it.

**Comment by Feuerswut** [comment]
never had that issue GrapheneOS Pixel 6.
Are you using an oficially supported version of Graphene that is recent and maintained?

**Comment by cipher-source** [comment]
> never had that issue GrapheneOS Pixel 6. Are you using an oficially supported version of Graphene that is recent and maintained?

Yes, I use the latest officially supported version of GrapheneOS.

**Comment by cipher-source** [comment]
> > @inubu The channel itself opens just fine for you?
> 
> Yes. I resetted NewPipe and just added "Dust" to the subscription list. No problem. It has nothing to do with a particular channel. I think it's a combination of thumbnails. And the issue is now gone. I can't test anymore. That's bad. The "What's new" Tab had that issue. I saw how thumbnails got loaded one by one and then NewPipe crashed. But now everything is fine again. Well, that's it.

The workaround of disconnecting the device from the internet worked for me perfectly. Thank you!
I too am subscribed to the "Dust" channel, that could be a common link between the bug occurrences.

**Comment by ghost** [comment]
Seems like the reason is the same as in #10751.

Seems like there is an image which hits limits of drawable size (~119MB O_o) of Picasso library. Or probably just a bug in Picasso itself because it is hard to believe there will 119MB image file....

Couldn't be reproducible in refactor branch because it [already moved](11238) from Picasso to Coil library
