### ISSUE TITLE
Player crashes on Downloaded Videos

### ISSUE THREAD

**Issue by firefoxlover** [TeamNewPipe/NewPipe#10467]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

Newpipe Sponsorblock 0.25.2

### Steps to reproduce the bug

After downloading a video and in the app clicking on the "Downloads" tab, trying to play a video, the app crashes always.

In the SAF i have set the download location as Downloads/Newpipe, while the videos are in Downloads.

This is due to the stupid Android limitation restricting storage access.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ DE
* __Content Language:__ de-DE
* __App Language:__ de_DE
* __Service:__ none
* __Version:__ 0.25.2
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
java.lang.SecurityException: UID 10306 does not have permission to content://com.android.externalstorage.documents/document/primary%3ADownload%2FEasiest%20Way%20To%20Find%20Product%20End%20Of%20Life%20Dates.mp4 [user 0] [prefix]; you could obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3020)
	at android.os.Parcel.createException(Parcel.java:3004)
	at android.os.Parcel.readException(Parcel.java:2980)
	at android.os.Parcel.readException(Parcel.java:2922)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2054)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1840)
	at android.app.Activity.startActivityForResult(Activity.java:5554)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:712)
	at android.app.Activity.startActivityForResult(Activity.java:5473)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:693)
	at android.app.Activity.startActivity(Activity.java:6010)
	at android.app.Activity.startActivity(Activity.java:5977)
	at org.schabi.newpipe.util.external_communication.ShareUtils.tryOpenIntentInApp(ShareUtils.java:142)
	at org.schabi.newpipe.util.external_communication.ShareUtils.openIntentInApp(ShareUtils.java:160)
	at us.shandian.giga.ui.adapter.MissionAdapter.openExternally(MissionAdapter.java:374)
	at us.shandian.giga.ui.adapter.MissionAdapter.-$$Nest$mopenExternally(MissionAdapter.java:0)
	at us.shandian.giga.ui.adapter.MissionAdapter$ViewHolderItem.lambda$new$1(MissionAdapter.java:916)
	at us.shandian.giga.ui.adapter.MissionAdapter$ViewHolderItem.$r8$lambda$CmCEgQjJdZQU71R9MLF_QHU7UWI(MissionAdapter.java:0)
	at us.shandian.giga.ui.adapter.MissionAdapter$ViewHolderItem$$ExternalSyntheticLambda1.onClick(R8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:7542)
	at android.view.View.performClickInternal(View.java:7519)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29476)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermissionUnlocked(UriGrantsManagerService.java:1251)
	at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermissionFromIntentUnlocked(UriGrantsManagerService.java:626)
	at com.android.server.uri.UriGrantsManagerService.-$$Nest$mcheckGrantUriPermissionFromIntentUnlocked(Unknown Source:0)
	at com.android.server.uri.UriGrantsManagerService$LocalService.checkGrantUriPermissionFromIntent(UriGrantsManagerService.java:1441)
	at com.android.server.wm.ActivityStarter$Request.resolveActivity(ActivityStarter.java:569)


```
</details>
<hr>

### Affected Android/Custom ROM version

GrapheneOS Android 13

### Affected device model

Google Pixel 4a

**Comment by ccpp** [comment]
Same happened here on current f-droid version, 0.27.2 (not related to sponsor block)
