### ISSUE TITLE
UI crash while trying to view yt vid

### ISSUE THREAD

**Issue by js290** [TeamNewPipe/NewPipe#10484]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2

### Steps to reproduce the bug

1. go to subscription channel
2. select video to view
3. crash

usually does not crash, and not really sure why it happened this time... works fine on subsequent attempts.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.25.2
* __OS:__ Linux Android 8.1.0 - 27
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to write to field 'android.view.ViewParent android.view.View.mParent' on a null object reference
	at android.view.ViewGroup.removeFromArray(ViewGroup.java:5057)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5254)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5216)
	at android.view.ViewGroup.removeView(ViewGroup.java:5147)
	at org.schabi.newpipe.player.ui.MainPlayerUi.removeViewFromParent(MainPlayerUi.java:227)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda30.accept(R8$$SyntheticClass:0)
	at j$.util.Optional.ifPresent(Unknown Source:4)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.removeVideoPlayerView(VideoDetailFragment.java:1237)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.hideMainPlayerOnLoadingNewStream(VideoDetailFragment.java:1144)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$runWorker$32(VideoDetailFragment.java:828)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.$r8$lambda$yO9w4bII-7LTl9F0EIApbmkEC3Q(VideoDetailFragment.java:0)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda13.accept(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```
</details>
<hr>

### Affected Android/Custom ROM version

Andoird 8.1.0

### Affected device model

Google Nexus 6P

**Comment by gsture** [comment]
I recognize this. Happens when you select a new video in portrait mode and then switch to landscape with auto totate enabled when the video is still loading. As soon as the video starts it crashes. Not always but regularly.

**Comment by js290** [comment]
> I recognize this. Happens when you select a new video in portrait mode and then switch to landscape with auto totate enabled when the video is still loading. As soon as the video starts it crashes. Not always but regularly.

This happened again, and seems to happen during screen rotation.
```
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.25.2
* __OS:__ Linux Android 7.0 - 24
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to destroy activity {org.schabi.newpipe/org.schabi.newpipe.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.IWindowSession.performDeferredDestroy(android.view.IWindow)' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4208)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4226)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4500)
	at android.app.ActivityThread.-wrap19(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1479)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.IWindowSession.performDeferredDestroy(android.view.IWindow)' on a null object reference
	at android.view.SurfaceView.updateWindow(SurfaceView.java:644)
	at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:251)
	at android.view.View.dispatchDetachedFromWindow(View.java:15452)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3219)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3219)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3219)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3219)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3219)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3219)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3219)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4756)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4730)
	at android.view.ViewGroup.removeView(ViewGroup.java:4661)
	at androidx.fragment.app.FragmentContainerView.removeView(FragmentContainerView.kt:288)
	at
```
