### ISSUE TITLE
Exoplayer fails playing videos

### ISSUE THREAD

**Issue by igor-fittgen** [TeamNewPipe/NewPipe#10488]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2

### Steps to reproduce the bug

1. Open any YouTube video
2. Click on video
3. Fails to open

### Expected behavior

Video plays

### Actual behavior

Immediately fails and gives a notification

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_DECODING_FAILED] occurred while playing https://www.youtube.com/watch?v=FXCAZXAOt4I
* __Content Country:__ DE
* __Content Language:__ en-DE
* __App Language:__ en_DE
* __Service:__ YouTube
* __Version:__ 0.25.2
* __OS:__ Linux motorola/vicky_g_sysen/vicky:12/S3SV32.45-28-1/78f81:user/release-keys 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(135, null, null, video/avc, avc1.4D401E, 372393, null, [478, 480, 30.0], [-1, -1]), format_supported=YES
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:578)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.os.HandlerThread.run(HandlerThread.java:85)
Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: c2.mtk.avc.decoder
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1639)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:803)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1007)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:502)
	... 4 more
Caused by: android.media.MediaCodec$CodecException: Error 0xe

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12

### Affected device model

moto g72

**Comment by igor-fittgen** [comment]
> > Decoder failed: c2.mtk.avc.decoder
> 
> Change the video format or audio format from settings. You likely have MP4. Switch to WebM.

Same result with "WebM" and "3GP"

**Comment by igor-fittgen** [comment]
## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_DECODING_FAILED] occurred while playing https://www.youtube.com/watch?v=FXCAZXAOt4I
* __Content Country:__ DE
* __Content Language:__ en-DE
* __App Language:__ en_DE
* __Service:__ YouTube
* __Version:__ 0.25.2
* __OS:__ Linux motorola/vicky_g_sysen/vicky:12/S3SV32.45-28-1/78f81:user/release-keys 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(244, null, null, video/x-vnd.on2.vp9, vp9, 155481, en, [478, 480, 30.0], [-1, -1]), format_supported=YES
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:578)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.os.HandlerThread.run(HandlerThread.java:85)
Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: c2.mtk.vp9.decoder
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1639)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:803)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1007)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:502)
	... 4 more
Caused by: android.media.MediaCodec$CodecException: Error 0xe

```
</details>
<hr>

**Comment by igor-fittgen** [comment]
Note that playing in background seems to still work, as does using an external player.

**Comment by igor-fittgen** [comment]
Seems that Exoplayer doesn't work anymore.
Thanks for the help so far.

**Comment by igor-fittgen** [comment]
Yesterday
Last update was 29.08. and is the current one

**Comment by igor-fittgen** [comment]
I feel
VERY
VERY
stupid right now

Thank you a LOT!
