### ISSUE TITLE
App immediately crashes/closes when opened

### ISSUE THREAD

**Issue by evdcush** [TeamNewPipe/NewPipe#10516]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2

### Steps to reproduce the bug

1. Open the app
2. It opens for about .1s
3. It immediately closes

There is no crash report or bug report.
I cannot open the application at all.
It immediately crashes/closes.

This is the second time the app state became in this irrecoverable state.

Clearing the cache, clearing the data, nothing works.
I am forced to reinstall the app, losing all user data and cache since the last time I exported my user.

### Expected behavior

Open the app.

**EITHER**

It opens, and I can use the app.

It crashes with a bug report or trace that it reports immediately after crashing.

### Actual behavior

It immediately closes, with no reported error or bug.

### Screenshots/Screen recordings

I cannot recover the app.

### Affected Android/Custom ROM version

Android 13; One UI 5.1.1

### Affected device model

Samsung Galaxy Z Fold 5 SM-F946B/DS

### Additional information

The affected device is a foldable.

**Comment by evdcush** [comment]
Since the app is in an irrecoverable state, here's my device SW info:

![Screenshot_20231027_201304_Settings](https://github.com/TeamNewPipe/NewPipe/assets/28853935/0ce5287f-0ddf-470e-8602-1dd0a706e841)

**Comment by MD77MD** [comment]
I've had the same problem for a very long time... 

from my observations, the app when opened, tries to makes a refresh (maybe for thumbnails) ... however if you  Interrupt this process by let us say hitting the search icon to make a search... the app will immediately crash.

until this bug is fixed... the workaround is to give the app 2 seconds or so to complete opening then use the app as usual

**Comment by evdcush** [comment]
> When did this start occurring? Or has it never worked on this device?

The first time this happened, same SW and NewPipe version, was 5 weeks prior, so mid September 2023.
The app does work initially, for some length of time.
Nothing about my usage prior to this bugged state is remarkable: I just open the app as usual, only now it is stuck in this state.

**Comment by evdcush** [comment]
> I've had the same problem for a very long time...
> 
> from my observations, the app when opened, tries to makes a refresh (maybe for thumbnails) ... however if you Interrupt this process by let us say hitting the search icon to make a search... the app will immediately crash.
> 
> until this bug is fixed... the workaround is to give the app 2 seconds or so to complete opening (or refreshing?) then use the app as usual

It sounds like you are experiencing a different issue.
My bug is very different. It immediately closes upon opening; you cannot wait on it, it's instantly closed. I've also tried to somehow interrupt this. Nothing works.

**Comment by evdcush** [comment]
> I'm assuming you're importing your exported database? Could you try that again, but say no when it asks to import settings in the next dialog?

I'm sorry I'm not sure I understand.
You're saying to uninstall, install again, and try what you said?

**Comment by evdcush** [comment]
Here's what it looks like:


https://github.com/TeamNewPipe/NewPipe/assets/28853935/455bf431-89db-440e-ba5e-e67d5e34fe29

**Comment by evdcush** [comment]
> Yep. Or just clear data from app settings and save yourself a step there.

Ah okay, thank you for your support.

The last time the app got in this bugged state, neither clearing the cache nor clearing the data resolved the issue. I had to reinstall.

Is there anyway to somehow recover the user data, such as subscriptions, without using the app? Such as copying a dir or db or something out of current bugged app dir and then into reinstalled dir?

**Comment by evdcush** [comment]
> > such as subscriptions
> 
> For that particularly, you should always keep the JSON backup separately.
> 

Okay, thanks!
Is it possible (granted root privileges) to copy the subscriptions JSON somehow?

### Update:

I was able to get the app to at least persist with an error.
It always shows an error, but no longer instantly closes.

The way I got this was by manually granting permissions to newpipe's trackers in AppManager.

Here's the error:

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ JP
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.25.2
* __OS:__ Linux samsung/q5qxxx/q5q:13/TP1A.220624.014/F946BXXU1AWG4:user/release-keys 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalArgumentException: Tried to schedule job for non-existent component: ComponentInfo{org.schabi.newpipe/org.acra.sender.JobSenderService}
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3027)
	at android.os.Parcel.createException(Parcel.java:3007)
	at android.os.Parcel.readException(Parcel.java:2990)
	at android.os.Parcel.readException(Parcel.java:2932)
	at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:263)
	at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:47)
	at org.acra.scheduler.DefaultSenderScheduler.scheduleReportSending(DefaultSenderScheduler.kt:52)
	at org.acra.scheduler.SchedulerStarter.scheduleReports(SchedulerStarter.kt:49)
	at org.acra.startup.StartupProcessorExecutor.processReports$lambda$6$lambda$5(StartupProcessorExecutor.kt:60)
	at org.acra.startup.StartupProcessorExecutor.$r8$lambda$LK61ILz0qM6dPNH2J6guur40K2U(StartupProcessorExecutor.kt:0)
	at org.acra.startup.StartupProcessorExecutor$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.enforceValidJobRequest(JobSchedulerService.java:3046)
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:3101)
	at android.app.job.IJobScheduler$Stub.onTransact(IJobScheduler.java:153)
	at android.os.Binder.execTransactInternal(Binder.java:1316)
	at android.os.Binder.execTransact(Binder.java:1280)


```
</details>
<hr>

**Comment by evdcush** [comment]
Okay, I was able to get NewPipe functional again.

But I had to unblock trackers.

![Screenshot_20231030_173023_App Manager](https://github.com/TeamNewPipe/NewPipe/assets/28853935/7653c98d-f180-45ae-bab5-83b29d06637e)

Why are these trackers necessary for the operation of NewPipe?

Now that this issue is resolved, please feel free to close it.

Thank you! ☺️
