### ISSUE TITLE
The app reports a Network error.

### ISSUE THREAD

**Issue by Cajogu1** [TeamNewPipe/NewPipe#10545]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2

### Steps to reproduce the bug

1. Open the app.
2. You got the bug.

### Expected behavior

To show me recommend videos

### Actual behavior

Not showing anything but network error

## Exception
* __User Action:__ requested kiosk
* __Request:__ Start loading: https://www.youtube.com/feed/trending
* __Content Country:__ DE
* __Content Language:__ en-DE
* __App Language:__ en_DE
* __Service:__ YouTube
* __Version:__ 0.25.2
* __OS:__ Linux motorola/odessa_retaile/odessa:11/RPA31.Q2-59-17-4-5/08c89:user/release-keys 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
javax.net.ssl.SSLException: Unable to parse TLS packet header
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:807)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:896)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.-$$Nest$mprocessDataFromSocket(Unknown Source:0)
	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:236)
	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:218)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at org.schabi.newpipe.DownloaderImpl.execute(DownloaderImpl.java:163)
	at org.schabi.newpipe.extractor.downloader.Downloader.get(Downloader.java:77)
	at org.schabi.newpipe.extractor.downloader.Downloader.get(Downloader.java:59)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.extractClientVersionAndKeyFromHtmlSearchResultsPage(YoutubeParsingHelper.java:604)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getClientVersion(YoutubeParsingHelper.java:688)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.prepareDesktopJsonBuilder(YoutubeParsingHelper.java:1241)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeTrendingExtractor.onFetchPage(YoutubeTrendingExtractor.java:63)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)
	at org.schabi.newpipe.extractor.kiosk.KioskInfo.getInfo(KioskInfo.java:53)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getKioskInfo$11(ExtractorHelper.java:191)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$NbG7JFGg0N9HK-3exJNRB9r_hYY(ExtractorHelper.java:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda8.call(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
	Suppressed: javax.net.ssl.SSLException: Unable to parse TLS packet header
		... 49 more
	Suppressed: javax.net.ssl.SSLHandshakeException: connection closed
		at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:356)
		at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:239)
		... 43 more
	Caused by: java.io.EOFException: connection closed
		... 44 more
	Suppressed: javax.net.ssl.SSLException: Unable to parse TLS packet header
		... 49 more
	Suppressed: javax.net.ssl.SSLHandshakeException: connection closed
		at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:356)
		at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:239)
		... 43 more
	Caused by: java.io.EOFException: connection closed
		... 44 more
	Suppressed: javax.net.ssl.SSLHandshakeException: connection closed
		at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:356)
		at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:239)
		... 43 more
	Caused by: java.io.EOFException: connection closed
		... 44 more
	Suppressed: javax.net.ssl.SSLException: Unable to parse TLS packet header
		... 49 more
	Suppressed: javax.net.ssl.SSLException: Unable to parse TLS packet header
		... 49 more
	Suppressed: javax.net.ssl.SSLException: Unable to parse TLS packet header
		... 49 more
	Suppressed: javax.net.ssl.SSLHandshakeException: connection closed
		at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:356)
		at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:239)
		... 43 more
	Caused by: java.io.EOFException: connection closed
		... 44 more
	Suppressed: javax.net.ssl.SSLHandshakeException: connection closed
		at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:356)
		at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:239)
		... 43 more
	Caused by: java.io.EOFException: connection closed
		... 44 more
	Suppressed: javax.net.ssl.SSLException: Unable to parse TLS packet header
		... 49 more
	Suppressed: javax.net.ssl.SSLException: Unable to parse TLS packet header
		... 49 more
	Suppressed: javax.net.ssl.SSLException: Unable to parse TLS packet header
		... 49 more
	Suppressed: javax.net.ssl.SSLException: Unable to parse TLS packet header
		... 49 more
	Suppressed: javax.net.ssl.SSLException: Unable to parse TLS packet header
		... 49 more
	Suppressed: javax.net.ssl.SSLException: Unable to parse TLS packet header
		... 49 more
	Suppressed: javax.net.ssl.SSLException: Unable to parse TLS packet header
		... 49 more
	Suppressed: javax.net.ssl.SSLHandshakeException: connection closed
		at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:356)
		at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:239)
		... 43 more
	Caused by: java.io.EOFException: connection closed
		... 44 more
	Suppressed: javax.net.ssl.SSLException: Unable to parse TLS packet header
		... 49 more

```
</details>
<hr>

### Affected device model

Motorola G9 plus

**Comment by Cajogu1** [comment]
Of cause. Even my phone. No effect

**Comment by Kannibalenleiche** [comment]
I have the same error, also in Germany. It does not matter if I am on cellular data or WiFi, the problem persists. First occurred a few hours ago.

**Comment by Cajogu1** [comment]
Thank god I'm not the only one. It appears to only be in Germany.

**Comment by Cajogu1** [comment]
I'll try that. Thx

**Comment by ZybanX** [comment]
I think it's YouTube server problem because it's having problem with YouTube SSL/TLS certificate or the compatibility from you and YouTube servers

**Comment by Cajogu1** [comment]
Ah. Thank you

**Comment by ZybanX** [comment]
> Ah. Thank you
> Edit: so how to fix this issue 

Well I don't know but let me see what I can do

**Comment by ZybanX** [comment]
@Cajogu1 try select your country on Newpipe by going to Settings > Content > Default Content Country and select your country, the restart Newpipe. I think that should work.

**Comment by Cajogu1** [comment]
I‘ll try that. Thanks in advance.

**Comment by Cajogu1** [comment]
I tried it. Did not work. I used a vpn and then it works. Without its dead silence

**Comment by Cajogu1** [comment]
Hope they fix it in the future. For now lets leave this thread active, so the devs at some point may find and fix it. Stay active please. 
Regards Cajogu
