### ISSUE TITLE
When I play a video on newpipe and use navigation gesture and swipe up to go back to home screen it stops the video (on evolution x a14 custom rom and kinesis kernel by clarencelol) (im using redmi note 9 pro 4g (with Snapdragon 720g and 4 gigs of ram)with atharva evo x a14 (community build) (with clarencelol's kinesis kernel) (device codename is miatoll)

### ISSUE THREAD

**Issue by parasgargexx20** [TeamNewPipe/NewPipe#10543]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2

### Steps to reproduce the bug

1. Go To App
2. Play Video 
3. Minimize using gesture navigation by swiping up

### Expected behavior

Background Playback should work in a14 with good kernel

### Actual behavior

Background playback does not work in android 14

### Screenshots/Screen recordings

https://github.com/TeamNewPipe/NewPipe/assets/102552831/ce3b4006-d54d-401a-b988-f0cf8a1e1587

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_TIMEOUT] occurred while playing https://www.youtube.com/watch?v=qxTV5fJSRjk
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.25.2
* __OS:__ Linux Android 14 - 34
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
	at com.google.android.exoplayer2.ExoPlayerImpl.setVideoOutputInternal(ExoPlayerImpl.java:2562)
	at com.google.android.exoplayer2.ExoPlayerImpl.setVideoSurface(ExoPlayerImpl.java:1293)
	at org.schabi.newpipe.player.playback.SurfaceHolderCallback.surfaceCreated(SurfaceHolderCallback.java:38)
	at android.view.SurfaceView.updateSurface(SurfaceView.java:1108)
	at android.view.SurfaceView.setWindowStopped(SurfaceView.java:346)
	at android.view.SurfaceView.surfaceCreated(SurfaceView.java:1784)
	at android.view.ViewRootImpl.notifySurfaceCreated(ViewRootImpl.java:2230)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3629)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2465)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9308)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1339)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
	at android.view.Choreographer.doCallbacks(Choreographer.java:952)
	at android.view.Choreographer.doFrame(Choreographer.java:882)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8173)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: com.google.android.exoplayer2.ExoTimeoutException: Detaching surface timed out.
	at com.google.android.exoplayer2.ExoPlayerImpl.setVideoOutputInternal(ExoPlayerImpl.java:2560)
	... 22 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 14 (Evolution X) (By Atharva) (With Custom Balanced Kernel By clarencelo named kinesisl)

### Affected device model

Redmi Note 9 Pro 4G (Snapdragon 720g 4 Gig Variant)

**Comment by parasgargexx20** [comment]
Pls inform if kernel is responsible for it (this is repo https://github.com/clarencelol/kernel_xiaomi_sm6250)

**Comment by parasgargexx20** [comment]
Yes

**Comment by parasgargexx20** [comment]
Actually It Got Fixed After I Used Ice Box Apps Freezer App And Kernel SU To Grant That App Root So It Can Freeze Google App.

**Comment by parasgargexx20** [comment]
Which is kinda weird but works
