### ISSUE TITLE
Crash when auto-rotate is on while video is playing 

### ISSUE THREAD

**Issue by abdullhakim-sami** [TeamNewPipe/NewPipe#10544]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2

### Steps to reproduce the bug

1.play a video in non-full screen display
2.turn auto-rotate in your phone
3.keep flipping the phone and the video will crash 

somehow now when i tried to do it it dosen't crash but it shows an error

 "sorry something went wrong" this problem happens to me when my phone falls while playing a video 

### Expected behavior

The video continues playing like usual

### Actual behavior

The video stops playing and the app shows a message "guru meditation" something like this

### Screenshots/Screen recordings

<img alt="Screenshot_20231106_215121_org schabi newpipe" src="https://github.com/TeamNewPipe/NewPipe/assets/136203274/d32029fa-6fd2-4390-a035-2d9f9a1fc314" width=272 />

### Logs

(Couldn't reproduce maybe i am missing an extra step) 

### Affected Android/Custom ROM version

Andriod 10 (emui 11.0.1)

### Affected device model

huwaui NEN-L22

**Comment by abdullhakim-sami** [comment]
I manged to remake the bug(I swear i wasn't trying 

I clicked a video after searching for it i flipped the screen to watch it then flipped it back cuz when it was full screen it was a broken full screen(this issue happens alot where some parts of the app i still can see while in full screen)

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ SA
* __Content Language:__ ar-
* __App Language:__ en_SA
* __Service:__ none
* __Version:__ 0.25.2
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Fragment CommentsFragment{6824761} (591d2231-9d50-46c2-86e7-89ad254c04e8) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:919)
	at androidx.fragment.app.Fragment.getResources(Fragment.java:983)
	at androidx.fragment.app.Fragment.getString(Fragment.java:1005)
	at org.schabi.newpipe.fragments.list.BaseListFragment.onSharedPreferenceChanged(BaseListFragment.java:477)
	at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:612)
	at android.app.SharedPreferencesImpl$EditorImpl.lambda$notifyListeners$0$SharedPreferencesImpl$EditorImpl(SharedPreferencesImpl.java:618)
	at android.app.-$$Lambda$SharedPreferencesImpl$EditorImpl$3CAjkhzA131V3V-sLfP2uy0FWZ0.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8403)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1087)

```
</details>
<hr>
