### ISSUE TITLE
Memory leak in nightly

### ISSUE THREAD

**Issue by Parmjot-Singh** [TeamNewPipe/NewPipe#10557]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2 nightly 92

### Steps to reproduce the bug

Watch a video, and if the video is long enough, Newpipe will crash due to running out of memory

### Expected behavior

Not crashing 

### Actual behavior

Starts skipping frames, and eventually crashes.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ NZ
* __Content Language:__ en-GB
* __App Language:__ en_NZ
* __Service:__ none
* __Version:__ 0.25.2
* __OS:__ Linux samsung/t2sxxx/t2s:13/TP1A.220624.014/G996BXXU9EWH5:user/release-keys 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 1060688 free bytes and 1035KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at android.os.ThreadLocalWorkSource.setUid(ThreadLocalWorkSource.java:68)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:313)
	at android.os.HandlerThread.run(HandlerThread.java:67)

```
</details>
<hr>

### Affected Android/Custom ROM version

OneUI 5, Android 13

### Affected device model

Samsung Galaxy S21+

**Comment by XiangRongLin** [comment]
>  if the video is long enough

can you put a number on this? like 1hour or like 1day?

**Comment by Parmjot-Singh** [comment]
Sorry for the delay as I hadn't noticed it in a while. I've noticed it only happens with videos higher than 1080p60, which may be because of the format change.
It happens on this video about 1:20 into the video.
https://www.youtube.com/watch?v=ki5xh3ax2EE

**Comment by XiangRongLin** [comment]
I can't reproduce the crash with nighlty-96 . I have a pixel 6a with only 6gb ram (should be less than yours) and didn't crash even after 3minutes on 2160p60.

**Comment by Parmjot-Singh** [comment]
@ShareASmile I don't think this is the same issue

**Comment by Parmjot-Singh** [comment]
Nevermimd, NewPipe crashed again, about 2 minutes into this video. https://www.youtube.com/watch?v=ti5G-c3wcM0

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ NZ
* __Content Language:__ en-GB
* __App Language:__ en_NZ
* __Service:__ none
* __Version:__ 0.25.2
* __OS:__ Linux samsung/t2sxxx/t2s:13/TP1A.220624.014/G996BXXU9EWH5:user/release-keys 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
java.lang.OutOfMemoryError: Failed to allocate a 64 byte allocation with 621296 free bytes and 606KB until OOM, target footprint 268435456, growth limit 268435456; giving up on allocation because <1% of heap free after GC.
	at android.media.MediaCodec.getBuffer(Native Method)
	at android.media.MediaCodec.getInputBuffer(MediaCodec.java:4031)
	at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.getInputBuffer(AsynchronousMediaCodecAdapter.java:212)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1193)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:784)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1007)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:502)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.os.HandlerThread.run(HandlerThread.java:67)

```
</details>
<hr>
