### ISSUE TITLE
Clicking Error details Get Crashed.

### ISSUE THREAD

**Issue by AF1011** [TeamNewPipe/NewPipe#10568]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2

### Steps to reproduce the bug

1. Play the Content you want to Watch & Listen
2. After several content later, the error message will be appear.

### Expected behavior

The Error short message appears after playing some selected watched video.

### Actual behavior

After clicking the error message, the application is crashed.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ KR
* __Content Language:__ ko-
* __App Language:__ in_ID
* __Service:__ none
* __Version:__ 0.25.2
* __OS:__ Linux samsung/a53xnsxx/a53x:13/TP1A.220624.014/A536EXXU7CWGJ:user/release-keys 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Failure from system
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1807)
	at android.app.Activity.startActivityForResult(Activity.java:5596)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:712)
	at android.app.Activity.startActivityForResult(Activity.java:5554)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:693)
	at android.app.Activity.startActivity(Activity.java:6052)
	at android.app.Activity.startActivity(Activity.java:6019)
	at org.schabi.newpipe.error.ErrorUtil$Companion.openActivity(ErrorUtil.kt:43)
	at org.schabi.newpipe.error.ErrorUtil$Companion.showSnackbar$lambda$0(ErrorUtil.kt:149)
	at org.schabi.newpipe.error.ErrorUtil$Companion.$r8$lambda$hbVLiP6-HtFc17h3_yyNDsmaIY8(ErrorUtil.kt:0)
	at org.schabi.newpipe.error.ErrorUtil$Companion$$ExternalSyntheticLambda0.onClick(R8$$SyntheticClass:0)
	at com.google.android.material.snackbar.Snackbar$1.onClick(Snackbar.java:349)
	at android.view.View.performClick(View.java:7892)
	at android.widget.TextView.performClick(TextView.java:16220)
	at android.view.View.performClickInternal(View.java:7869)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30891)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: android.os.TransactionTooLargeException: data parcel size 1143048 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:662)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:2790)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1801)
	... 24 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 13 /One UI 5.1

### Affected device model

Samsung Galaxy A53 (SM-A5363/DS)

**Comment by ZybanX** [comment]
I think (if I'm wrong) a possible memory leak
