### ISSUE TITLE
NewPipe crashes when putting a video in full-screen then scrubbing to the end

### ISSUE THREAD

**Issue by TheMCNerd2017** [TeamNewPipe/NewPipe#10594]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2/latest Nightly

### Steps to reproduce the bug

1. Open this video: https://www.youtube.com/watch?v=6pUIzXh2dOk
2. Play the video, then go into fullscreen
3. Bring up the progress bar by tapping once on the screen, then scrub to the end.
4. NewPipe crashes.

### Expected behavior

NewPipe lets me scrub to the end of the video and back.

### Actual behavior

NewPipe crashes upon scrubbing to the end of the video, sometimes instantly, sometimes after a few seconds of scrubbing near the end of the video.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.25.2
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalArgumentException: cannot use a recycled source in createBitmap
	at android.graphics.Bitmap.createBitmap(Bitmap.java:880)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:834)
	at org.schabi.newpipe.player.seekbarpreview.SeekbarPreviewThumbnailHolder.lambda$generateDataFrom$3(SeekbarPreviewThumbnailHolder.java:143)
	at org.schabi.newpipe.player.seekbarpreview.SeekbarPreviewThumbnailHolder.$r8$lambda$0elxBGHHcmMbO9kgf0vknFIh1sg(SeekbarPreviewThumbnailHolder.java:0)
	at org.schabi.newpipe.player.seekbarpreview.SeekbarPreviewThumbnailHolder$$ExternalSyntheticLambda4.get(R8$$SyntheticClass:0)
	at org.schabi.newpipe.player.seekbarpreview.SeekbarPreviewThumbnailHolder.getBitmapAt(SeekbarPreviewThumbnailHolder.java:214)
	at org.schabi.newpipe.player.ui.VideoPlayerUi.onProgressChanged(VideoPlayerUi.java:585)
	at org.schabi.newpipe.views.FocusAwareSeekBar$NestedListener.onProgressChanged(FocusAwareSeekBar.java:130)
	at android.widget.SeekBar.onProgressRefresh(SeekBar.java:99)
	at android.widget.ProgressBar.doRefreshProgress(ProgressBar.java:1578)
	at android.widget.ProgressBar.refreshProgress(ProgressBar.java:1690)
	at android.widget.ProgressBar.setProgressInternal(ProgressBar.java:1756)
	at android.widget.AbsSeekBar.trackTouchEvent(AbsSeekBar.java:1016)
	at android.widget.AbsSeekBar.onTouchEvent(AbsSeekBar.java:924)
	at android.view.View.dispatchTouchEvent(View.java:15050)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:500)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1912)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4307)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:70)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:458)
	at android.view.View.dispatchPointerEvent(View.java:15309)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6774)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6574)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6030)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6087)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6053)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6218)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6061)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6275)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6034)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6087)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6053)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6061)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6034)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9202)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9153)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9122)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9325)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:247)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:9282)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:9416)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:824)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```
</details>
<hr>

### Affected Android/Custom ROM version

GrapheneOS 13 (TP1A.221005.002.B2.2023110900)

### Affected device model

Pixel 4XL

### Additional information

This occurs on both the latest stable version 0.25.2 and the latest Nightly build.

**Comment by stavpup** [comment]
I have a similar issue.  I  installed F-droid to my android box, and then NewPipe. The player works fine, but when I put in of full screen, it freezes (720p). I wish there was a way to scale the video to a large enough size to be viewable on TV.

Also IMHO there is a design flow, because the full screen button is on the right of the video bar, and if you press the right arrow, it forwards the video. I found by accident that you must press the down button to get to it. So the current position is counter intuitive.  It should be placed up and on the right for example.

![tv](https://github.com/TeamNewPipe/NewPipe/assets/10577035/707c4e00-fc49-447c-b77f-390063ea98a6)
