### ISSUE TITLE
Fullscreen no work 

### ISSUE THREAD

**Issue by Kowal1234p** [TeamNewPipe/NewPipe#10609]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

25.2

### Steps to reproduce the bug

1 search video
2 click video
3 click Play
4 click fullscreen/rotate screen
5 crash

### Logs

java.lang.IllegalArgumentException: serviceId is NO_SERVICE_ID
	at org.schabi.newpipe.util.ExtractorHelper.checkServiceId(ExtractorHelper.java:74)
	at org.schabi.newpipe.util.ExtractorHelper.suggestionsFor(ExtractorHelper.java:105)
	at org.schabi.newpipe.fragments.list.search.SearchFragment.getRemoteSuggestionsObservable(SearchFragment.java:728)
	at org.schabi.newpipe.fragments.list.search.SearchFragment.lambda$initSuggestionObserver$13(SearchFragment.java:759)
	at org.schabi.newpipe.fragments.list.search.SearchFragment.$r8$lambda$pBDX-0z_WT5AfgQUUvGxZ1y-jHc(SearchFragment.java:0)
	at org.schabi.newpipe.fragments.list.search.SearchFragment$$ExternalSyntheticLambda13.apply(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableSwitchMap$SwitchMapObserver.onNext(ObservableSwitchMap.java:112)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver$DelayErrorInnerObserver.onNext(ObservableConcatMap.java:500)
	at io.reactivex.rxjava3.observers.SerializedObserver.onNext(SerializedObserver.java:114)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableDebounceTimed$DebounceTimedObserver.emit(ObservableDebounceTimed.java:156)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableDebounceTimed$DebounceEmitter.run(ObservableDebounceTimed.java:181)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
-------------------------------------

### Affected Android/Custom ROM version

Android13

### Affected device model

Realme8

**Comment by stefano-p** [comment]
Hello, I am also experiencing such issue in my Android TV v11. NewPipe just installed. As soon as I trigger a full screen mode the video stops with an error message.
