### ISSUE TITLE
[YouTube] Could not get like count (Fixed in code)

### ISSUE THREAD

**Issue by marek22k** [TeamNewPipe/NewPipe#10624]
# Mod edit: See TeamNewPipe/NewPipeExtractor#1133 and TeamNewPipe/NewPipeExtractor#1127

### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2

### Steps to reproduce the bug

For me, the message almost always appears when I start a video and when I switch the video to full screen or back again.

### Expected behavior

No error message

### Actual behavior

A error message

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=SX0XbxS2was
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.25.2
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get like count
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getLikeCount(YoutubeStreamExtractor.java:508)
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractOptionalData(StreamInfo.java:279)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:83)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:73)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:119)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(ExtractorHelper.java:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda3.call(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5377)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16013)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5377)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equalsIgnoreCase(java.lang.String)' on a null object reference
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.lambda$getLikeCount$7(YoutubeStreamExtractor.java:458)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.$r8$lambda$JNZYncC0vyG9Ez_PK6G8Ez8Psqs(YoutubeStreamExtractor.java:0)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor$$ExternalSyntheticLambda14.test(R8$$SyntheticClass:0)
	at j$.util.stream.d2.accept(SourceFile:0)
	at j$.util.stream.d2.accept(SourceFile:0)
	at j$.util.stream.d2.accept(SourceFile:0)
	at j$.util.stream.d2.accept(SourceFile:0)
	at j$.util.a.tryAdvance(SourceFile:0)
	at j$.util.stream.l2.z0(Unknown Source:6)
	at j$.util.stream.c.a0(Unknown Source:15)
	at j$.util.stream.c.Z(SourceFile:0)
	at j$.util.stream.c.t0(Unknown Source:10)
	at j$.util.stream.J.v(Unknown Source:8)
	at j$.util.stream.c.w0(SourceFile:0)
	at j$.util.stream.l2.findFirst(SourceFile:0)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getLikeCount(YoutubeStreamExtractor.java:466)
	... 30 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 13 / CalyxOS 4.15.0

### Affected device model

FP4

### Additional information

I apologize if I am creating a duplicate, but I could not find a similar issue.

**Comment by marek22k** [comment]
@opusforlife2 Why did you close the issue? The problem exists.

**Comment by marek22k** [comment]
As I said, I didn't find anything there that corresponded to my issue and was created recently. Could you name a specific issue? If not, please open this one again.

**Comment by marek22k** [comment]
> I see this says "fixed in code", can you share what version fixes it? I have the latest version available for download and the error is still persisting. Thanks.

It means that the error is known and code has been created to fix it.
The code still needs to be reviewed and a new version of NewPipe needs to be released so that the bug is finally fixed for the user.

A fork of Newpipe, PipePipe (but does not have all the features of NewPipe), has already fixed the bug in the current version.

**Comment by Ansshaoh** [comment]
> > I see this says "fixed in code", can you share what version fixes it? I have the latest version available for download and the error is still persisting. Thanks.
> 
> It means that the error is known and code has been created to fix it.
> The code still needs to be reviewed and a new version of NewPipe needs to be released so that the bug is finally fixed for the user.
> 
> A fork of Newpipe, PipePipe (but does not have all the features of NewPipe), has already fixed the bug in the current version.

Thank you very much to the author. I have encountered the same problem in Android 13. I tried to install the historical version to solve it, but without success. It would be better if it can be solved in the new version.

**Comment by fenopa** [comment]
> > I see this says "fixed in code", can you share what version fixes it? I have the latest version available for download and the error is still persisting. Thanks.
> 
> It means that the error is known and code has been created to fix it. The code still needs to be reviewed and a new version of NewPipe needs to be released so that the bug is finally fixed for the user.
> 
> A fork of Newpipe, PipePipe (but does not have all the features of NewPipe), has already fixed the bug in the current version.

why there is not even a nightly release at least?

**Comment by fenopa** [comment]
> notification for the RC

"notification for the RC" ?

**Comment by fenopa** [comment]
I already saw this issue from pinned issues. What's the meaning of "notification for the RC", what "RC"? how does that answer the lack of nightly release?

**Comment by marek22k** [comment]
Maybe RC = Release candidate = Preview version?

**Comment by InconsolableCellist** [comment]
Can we disable the "report problem" ribbon in the meantime?
