### ISSUE TITLE
App UI crashes every time I add a video to my watch later list

### ISSUE THREAD

**Issue by alexispurslane** [TeamNewPipe/NewPipe#10641]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2

### Steps to reproduce the bug

1. Long press on a video in the search screen
2. Pick add to watch later
3. Observe the app crash to your home screen

### Expected behavior

While the video *is* added to my watch later, I don't expect the app to quit while doing so

### Actual behavior

After(?) adding the video to my watch later list the app completely crashes.

### Screenshots/Screen recordings

https://github.com/TeamNewPipe/NewPipe/assets/1920151/19578978-4355-4da5-bc53-92c3bd2c45fb

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.25.2
* __OS:__ Linux Android 14 - 34
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at org.schabi.newpipe.local.dialog.PlaylistAppendDialog.lambda$onPlaylistSelected$4(PlaylistAppendDialog.java:163)
	at org.schabi.newpipe.local.dialog.PlaylistAppendDialog.$r8$lambda$zTWALft3TUabC8jelCR2F7daRCg(PlaylistAppendDialog.java:0)
	at org.schabi.newpipe.local.dialog.PlaylistAppendDialog$$ExternalSyntheticLambda4.accept(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeCallbackObserver.onSuccess(MaybeCallbackObserver.java:71)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeObserveOn$ObserveOnMaybeObserver.run(MaybeObserveOn.java:103)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8216)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

```
</details>
<hr>

### Affected Android/Custom ROM version

GrapheneOS 14

### Affected device model

Pixel 6

**Comment by matthiakl** [comment]
I can confirm the issue. It happens to me, when I add a video from my news feed to a playlist, but not every time/with every video. After restarting NewPipe, the video is already in the playlist.

## Affected Android/Custom ROM version

LineageOS for microg 

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ DE
* __Content Language:__ de-
* __App Language:__ de_DE
* __Service:__ none
* __Version:__ 0.25.2
* __OS:__ Linux Android 7.1.2 - 25
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at org.schabi.newpipe.local.dialog.PlaylistAppendDialog.lambda$onPlaylistSelected$4(PlaylistAppendDialog.java:163)
	at org.schabi.newpipe.local.dialog.PlaylistAppendDialog.$r8$lambda$zTWALft3TUabC8jelCR2F7daRCg(PlaylistAppendDialog.java:0)
	at org.schabi.newpipe.local.dialog.PlaylistAppendDialog$$ExternalSyntheticLambda4.accept(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeCallbackObserver.onSuccess(MaybeCallbackObserver.java:71)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeObserveOn$ObserveOnMaybeObserver.run(MaybeObserveOn.java:103)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

```
</details>
<hr>

**Comment by alexispurslane** [comment]
> Does it happen if the video is not being added from the feed, but from some other source, like a channel or search results?

I first discovered the behavior adding videos from search results, but I just tested adding videos from my feed and channels just now, and yeah those also crash the app

**Comment by alexispurslane** [comment]
> Does it happen with playlists other than "watch later"?

No, only watch later seems to be effected, oddly.

**Comment by alexispurslane** [comment]
> What happens if you delete this playlist and create it again? Does the bug persist?

I have a lot of stuff in my watch later at the moment and I'd prefer not to have to recreate it, maybe someone else can test this?

**Comment by matthiakl** [comment]
> Does it happen with playlists other than "watch later"?

For me it also happens for other playlists. I have now created a new one to see, whether it crashs there as well.

**Comment by alexispurslane** [comment]
@opusforlife2 oh! Alright let me try it out :D

**Comment by alexispurslane** [comment]
Oh, and now that I've restored my database and rhe old playlist, the crash is back again!

**Comment by Nes2525** [comment]
> Oh, and now that I've restored my database and rhe old playlist, the crash is back again!

How much video is in watchlater ?

**Comment by alexispurslane** [comment]
> > Oh, and now that I've restored my database and rhe old playlist, the crash is back again!
> 
> How much video is in watchlater ? If its too big it might cause memory issues.

It's only about 120 videos. But the crashes mysteriously stopped happening sometime (I'm not sure when) after restoring my database, and haven't happened since. I really don't know why.

**Comment by L12C** [comment]
I have the same issue on 0.26.1, also with my watch later playlist. The issue seems to be that it attempts to use a video that is no longer available as thumbnail for the playlist, and while most other code ignores this and uses the default thumbnail instead, PlaylistAppendDialog fails when the selected playlist's thumbnail isn't available.
While I don't know enough about the NewPipe code to fix this, as a workaround you can just manually set another video as playlist thumbnail.

**Comment by L12C** [comment]
Unfortunately I forgot to keep the old database, so I can't reproduce it.

**Comment by stephen-hill** [comment]
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.26.1
* __OS:__ Linux motorola/capri_retailen/capri:11/RRB31.Q1-3-48/5b092:user/release-keys 11 - 30

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at org.schabi.newpipe.local.dialog.PlaylistAppendDialog.lambda$onPlaylistSelected$4(PlaylistAppendDialog.java:163)
	at org.schabi.newpipe.local.dialog.PlaylistAppendDialog.$r8$lambda$zTWALft3TUabC8jelCR2F7daRCg(PlaylistAppendDialog.java:0)
	at org.schabi.newpipe.local.dialog.PlaylistAppendDialog$$ExternalSyntheticLambda4.accept(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeCallbackObserver.onSuccess(MaybeCallbackObserver.java:71)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeObserveOn$ObserveOnMaybeObserver.run(MaybeObserveOn.java:103)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:250)
	at android.app.ActivityThread.main(ActivityThread.java:7806)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

```

**Comment by kohane27** [comment]
> I have the same issue on 0.26.1, also with my watch later playlist. The issue seems to be that it attempts to use a video that is no longer available as thumbnail for the playlist, and while most other code ignores this and uses the default thumbnail instead, PlaylistAppendDialog fails when the selected playlist's thumbnail isn't available. While I don't know enough about the NewPipe code to fix this, as a workaround you can just manually set another video as playlist thumbnail.

Spot on! This is exactly the root cause. To reproduce:

1. Add a video to a playlist
2. Long press the video and `Set as playlist thumbnail`
3. Long press the video and `Delete` (so the playlist is still referring to the deleted video **that is no longer available on YouTube, i.e., the uploader deleted the video**)
4. Add any video to the playlist
5. App crash

The solution is very simple: use a new and available video as playlist thumbnail or simply create another playlist. Cheers!
