### ISSUE TITLE
Annoying UI Error

### ISSUE THREAD

**Issue by quinb96** [TeamNewPipe/NewPipe#10650]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2

### Steps to reproduce the bug

Can't reproduce it. Happens randomly. However this happens A LOT.

### Expected behavior

To simply just operate correctly and not spawn this error every 2 mins.

### Actual behavior

Error comes up ALL THE TIME.
I've looked up this error and their doesn't seem to be a clear answer on why this comes up for many people so much. I'm not seeing that the Newpipe team had ever answered why this happens. I apologize but I've had enough of this error now. Is there a known permanent fix for this?

### Logs

#10648

### Affected Android/Custom ROM version

Android 13

### Affected device model

Samsung Galaxy A13 5G

### Additional information

Same issue deacribed in #10648 but was closed without providing me any information that helps. What certain keywords do I need to be using? Can you link me to an issue that actually answers my questions? Otherwise this will just continue.

**Comment by Nes2525** [comment]
Try new version, maybe it will go away. [v0.26](https://github.com/TeamNewPipe/NewPipe/issues/10471)

**Comment by 31duderino** [comment]
And here I thought it was just me:
![Screenshot_20231212-082255](https://github.com/TeamNewPipe/NewPipe/assets/150315153/7ccb12ad-07a1-4ab3-a7d6-a4240319d64e)

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.25.2
* __OS:__ Linux Android 14 - 34
<details><summary><b>Crash log </b></summary><p>

```
android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{55aa30c u0 org.schabi.newpipe/.player.PlayerService}
	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2104)
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2075)
	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2369)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1952)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1906)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:830)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:830)
	at androidx.core.content.ContextCompat$Api26Impl$$ExternalSyntheticApiModelOutline1.m(R8$$SyntheticClass:0)
	at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:1091)
	at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:749)
	at androidx.media.session.MediaButtonReceiver.onReceive(MediaButtonReceiver.java:115)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4449)
	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2256)
	... 7 more

```
</details>
<hr>

Affected Android/Custom ROM version
Android 14

Affected device model
Pixel 7 Pro

**Comment by Nes2525** [comment]
Also make sure newpipe excluded from battery optimization.

**Comment by quinb96** [comment]
@AudricV

**Comment by quinb96** [comment]
> Try new version, maybe it will go away. [v0.26](https://github.com/TeamNewPipe/NewPipe/issues/10471)

This has been an issue with different devices for literally over a year. I'm almost certain a new version won't fix this.

**Comment by quinb96** [comment]
> And here I thought it was just me:
> <img alt="Screenshot_20231212-082255" src="https://github.com/TeamNewPipe/NewPipe/assets/150315153/7ccb12ad-07a1-4ab3-a7d6-a4240319d64e" width=276 />
> 
> ## Exception
> * __User Action:__ ui error
> * __Request:__ ACRA report
> * __Content Country:__ US
> * __Content Language:__ en-US
> * __App Language:__ en_US
> * __Service:__ none
> * __Version:__ 0.25.2
> * __OS:__ Linux Android 14 - 34
> <details><summary><b>Crash log </b></summary><p>
> 
> ```
> android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{55aa30c u0 org.schabi.newpipe/.player.PlayerService}
> 	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2104)
> 	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2075)
> 	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2369)
> 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 	at android.os.Looper.loopOnce(Looper.java:205)
> 	at android.os.Looper.loop(Looper.java:294)
> 	at android.app.ActivityThread.main(ActivityThread.java:8177)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
> Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
> 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1952)
> 	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1906)
> 	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:830)
> 	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:830)
> 	at androidx.core.content.ContextCompat$Api26Impl$$ExternalSyntheticApiModelOutline1.m(R8$$SyntheticClass:0)
> 	at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:1091)
> 	at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:749)
> 	at androidx.media.session.MediaButtonReceiver.onReceive(MediaButtonReceiver.java:115)
> 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4449)
> 	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2256)
> 	... 7 more
> 
> ```
> </details>
> <hr>
> 
> Affected Android/Custom ROM version
> Android 14
> 
> Affected device model
> Pixel 7 Pro

There's a lot of people having this issue at least from the research I've done. I'm not seeing that there was ever a permanent fix for this discovered for this. If there's a perament fix out there please link us to that fix.

**Comment by Stypox** [comment]
This was a duplicate of tens of issues (you could have just searched for them before opening a duplicate...), has already been fixed in https://github.com/TeamNewPipe/NewPipe/pull/10578 and the upcoming 0.26.0 will contain the fix (you can use the APK on top of https://github.com/TeamNewPipe/NewPipe/issues/10471). Next time follow the suggestions you are given, instead of repeatedly opening duplicate issues and saying things like "I'm almost certain that specific version won't fix this." without even trying.

**Comment by quinb96** [comment]
> This was a duplicate of tens of issues (e.g. #9030, you could have just searched for them before opening a duplicate...), has already been fixed in https://github.com/TeamNewPipe/NewPipe/pull/10578 and the upcoming 0.26.0 will contain the fix (you can use the APK on top of https://github.com/TeamNewPipe/NewPipe/issues/10471). Next time follow the suggestions you are given, instead of repeatedly opening duplicate issues and saying things like "I'm almost certain that specific version won't fix this." without even trying.

But this is probably my 3rd to 4th time saying I had extensively lookes through all that and I couldn't find it. Everyone keeps telling me that but it appears to me you guys aren't even thoroughly reading what I'm saying or not understanding. I don't know how else to express I've done extensive troubleshooting. Then asked maybe 3 times for someone to link me to issues that may solve my problem. You're the first one to do anything of the sort. I said more than once if there's a fix and I'm not seeing it then please link me. No one wanted to do that. So idk. Also for assuming that 0.26.0 wouldn't work, it may be wrong for me to assume it won't work but at the same time this has been an issue for me for idk how many versions now.

**Comment by quinb96** [comment]
> This was a duplicate of tens of issues (e.g. #9030, you could have just searched for them before opening a duplicate...), has already been fixed in https://github.com/TeamNewPipe/NewPipe/pull/10578 and the upcoming 0.26.0 will contain the fix (you can use the APK on top of https://github.com/TeamNewPipe/NewPipe/issues/10471). Next time follow the suggestions you are given, instead of repeatedly opening duplicate issues and saying things like "I'm almost certain that specific version won't fix this." without even trying.

And I keep being told there's tens of the same thing. OK and I see that. That's a clear indication of a serious bug. it appeared to me that no one was trying to fix the issue. If so, that's great but no one had the incentive to actually link me to that info. I'm not sure why you guys are expecting us to just stop reporting this. The only way I see people stop reporting this if the error was truly resolved kn 0.26.0.

**Comment by quinb96** [comment]
> > I've done extensive troubleshooting
> 
> I understand the feeling, but unfortunately that is not enough. You have to work with the maintainers of the project you're participating in, even if that sometimes means repeating steps or doing things you're sure won't work. The maintainers don't know your brain, nor can they telepathically glean all your activities regarding the bug.
> 
> But if you come out the door guns blazing, flinging your frustration around at everyone else, then it makes for a very difficult interaction no matter what project you're in.
> 
> FYI, when I told you to search using the string I provided from your crash log, it would have led you to discover exactly what Stypox showed, that there are dozens of duplicate reports about the same thing. You just happened to give up at that exact step.
> 
> Moreover, a general policy of reporting bugs in any software project is to test the latest version available, including release candidates, nightlies, beta versions, etc. If you had tested the RC, you wouldn't have had to open an issue at all.

I apologize for the frustration. It's due to this error happening every 2 mins in combination with believing that the team will not do anything about it. I sometimes won't even be touching my phone and this error would come up.. And I did search open and closed issues but I was seeing either no one actually knew what the problem was and so it just gets closed unresolved, or the phone had no more RAM. If the problem wasn't the phone being too low on RAM, no one seemed to know what the issue was then. And I'm seeing that this has been a problem for months now. Since this became an issue at least for me which has now been over a month ago, I recall a few updates being released since then and none of them are even aimed to fix this issue. So then this made me think that you guys know this is an issue and deliberately won't fix it. Then telling me to search issues after I've done that A LOT only made me more frustrated. I've almost decompiled the APK just to see if I can find the issue cause I know it's a Java error but just too lazy to do so.
