### ISSUE TITLE
Cannot download music only

### ISSUE THREAD

**Issue by Microturbine** [TeamNewPipe/NewPipe#10689]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.0

### Steps to reproduce the bug

1, Search
2, Select video
3, Press the download button
4, Select download music (any codec, any bitrate)
5, Download failed

### Expected behavior

Music can be downloaded in any codec and at any bit rate.

### Actual behavior

The notification box will say that the download failed.

## Exception
* __User Action:__ download post-processing
* __Request:__ https://www.youtube.com/watch?v=gtYydJJtQdg [ {type=audio format=WebM Opus bitrate=160} ]
* __Content Country:__ JP
* __Content Language:__ ja-JP
* __App Language:__ ja_JP
* __Service:__ YouTube
* __Version:__ 0.26.0
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>
```
java.io.IOException: Operation not permitted
	at sun.nio.ch.FileDispatcherImpl.truncate0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.truncate(FileDispatcherImpl.java:101)
	at sun.nio.ch.FileChannelImpl.truncate(FileChannelImpl.java:406)
	at us.shandian.giga.io.FileStreamSAF.setLength(FileStreamSAF.java:138)
	at us.shandian.giga.io.CircularFileWriter.finalizeFile(CircularFileWriter.java:147)
	at us.shandian.giga.postprocessing.Postprocessing.run(Postprocessing.java:177)
	at us.shandian.giga.get.DownloadMission.doPostprocessing(DownloadMission.java:700)
	at us.shandian.giga.get.DownloadMission.$r8$lambda$TfhfQRw7BXa67GG5rH8lpt1NlmQ(DownloadMission.java:0)
	at us.shandian.giga.get.DownloadMission$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)
```
</details>
<hr>

### Affected Android/Custom ROM version

MIUI Global 14.0.3

### Affected device model

Redmi Note 11 Pro 5G

**Comment by Microturbine** [comment]
I couldn't download subtitles either.I was able to download the video.

**Comment by Microturbine** [comment]
I checked under different conditions.
Save to internal storage → video, audio, and subtitles are all possible.
Save to SD card → Only video can be saved, others will have errors.
How do I save audio directly to an SD card?

**Comment by Microturbine** [comment]
These three steps are displayed.
![Screenshot_2023-12-25-00-39-53-593_com google android documentsui](https://github.com/TeamNewPipe/NewPipe/assets/53145253/971cac6d-c8e1-4410-9603-888894e56f9d)
![Screenshot_2023-12-25-00-38-33-897_org schabi newpipe](https://github.com/TeamNewPipe/NewPipe/assets/53145253/27389e00-6d48-482b-824d-9661fa88b9f5)
![Screenshot_2023-12-25-00-39-49-761_com google android documentsui](https://github.com/TeamNewPipe/NewPipe/assets/53145253/8df88c3e-6081-4aab-8576-41697cbf1a10)

**Comment by Microturbine** [comment]
I still get a notification that the download failed.
However, when I checked the file manager, [the audio file was generated](https://github.com/TeamNewPipe/NewPipe/assets/53145253/24e0167b-4520-4508-b067-f136129203b9).
I tried to play it on [YoutubeMusic](https://github.com/TeamNewPipe/NewPipe/assets/53145253/00e4c281-ef60-4d96-9b99-e76aa7e09f91),

- In the case of opus, the seek bar cannot be moved, but playback is possible.

- In the case of m4a, the seek bar can be moved and playback is possible.

Also, I think the volume level is slightly different for the different codecs. (Is it due to the difference in bit rate?)
![Screenshot_2023-12-25-01-43-22-686_com mi android globalFileexplorer](https://github.com/TeamNewPipe/NewPipe/assets/53145253/24e0167b-4520-4508-b067-f136129203b9)
![Screenshot_2023-12-25-01-42-47-172_app rvx android apps youtube music](https://github.com/TeamNewPipe/NewPipe/assets/53145253/00e4c281-ef60-4d96-9b99-e76aa7e09f91)

**Comment by Microturbine** [comment]
I tried NewPipe_v0.26.0_RC3_release.
The situation is exactly the same as before, I get an error notification, but the file was generated.
![Screenshot_2023-12-25-01-55-39-140_org schabi newpipe v0_26_0](https://github.com/TeamNewPipe/NewPipe/assets/53145253/023fc1b0-57ef-4d71-8211-b9fce61d6f11)

**Comment by Microturbine** [comment]
Thank you for your efforts in resolving the issue.
I can close the issue, right?

**Comment by Microturbine** [comment]
ok

**Comment by Microturbine** [comment]
Sorry, but I bought a new smartphone in the past few weeks and bought one without an SD card.
So I cannot check.
