### ISSUE TITLE
Bandcamp: Crashes upon pressing system back button

### ISSUE THREAD

**Issue by joesmullen** [TeamNewPipe/NewPipe#10688]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.0

### Steps to reproduce the bug

1. Enable 3-button navigation in your device's settings if you haven't already.
2. Open NewPipe and switch to Bandcamp.
3. Search for any artist and tap on their channel.
4. Go to the Albums tab and tap on any of their albums.
5. Press your device's back button (**not** the app's back button in the top left corner).

### Expected behavior

The app takes you back to the Albums section.

### Actual behavior

The app crashes and throws a NetworkOnMainThreadException.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ IE
* __Content Language:__ en-GB
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.26.0
* __OS:__ Linux Android 14 - 34
<details><summary><b>Crash log </b></summary><p>

```
android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1675)
	at com.android.org.conscrypt.Platform.blockGuardOnNetwork(Platform.java:436)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLOutputStream.writeInternal(ConscryptEngineSocket.java:704)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLOutputStream.write(ConscryptEngineSocket.java:699)
	at okio.OutputStreamSink.write(JvmOkio.kt:56)
	at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:102)
	at okio.RealBufferedSink.flush(RealBufferedSink.kt:186)
	at okhttp3.internal.http2.Http2Writer.flush(Http2Writer.kt:120)
	at okhttp3.internal.http2.Http2Connection.flush(Http2Connection.kt:408)
	at okhttp3.internal.http2.Http2Stream$FramingSink.close(Http2Stream.kt:624)
	at okio.ForwardingSink.close(ForwardingSink.kt:37)
	at okhttp3.internal.connection.Exchange$RequestBodySink.close(Exchange.kt:247)
	at okio.RealBufferedSink.close(RealBufferedSink.kt:206)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:63)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at org.schabi.newpipe.DownloaderImpl.execute(DownloaderImpl.java:163)
	at org.schabi.newpipe.extractor.downloader.Downloader.post(Downloader.java:143)
	at org.schabi.newpipe.extractor.downloader.Downloader.postWithContentType(Downloader.java:175)
	at org.schabi.newpipe.extractor.downloader.Downloader.postWithContentTypeJson(Downloader.java:217)
	at org.schabi.newpipe.extractor.downloader.Downloader.postWithContentTypeJson(Downloader.java:235)
	at org.schabi.newpipe.extractor.services.bandcamp.extractors.BandcampExtractorHelper.getArtistDetails(BandcampExtractorHelper.java:120)
	at org.schabi.newpipe.extractor.services.bandcamp.linkHandler.BandcampChannelLinkHandlerFactory.getUrl(BandcampChannelLinkHandlerFactory.java:55)
	at org.schabi.newpipe.extractor.linkhandler.ListLinkHandlerFactory.getUrl(ListLinkHandlerFactory.java:77)
	at org.schabi.newpipe.extractor.services.bandcamp.linkHandler.BandcampChannelTabLinkHandlerFactory.getUrl(BandcampChannelTabLinkHandlerFactory.java:56)
	at org.schabi.newpipe.extractor.linkhandler.ListLinkHandlerFactory.fromQuery(ListLinkHandlerFactory.java:57)
	at org.schabi.newpipe.fragments.list.channel.ChannelTabFragment.handleResult(ChannelTabFragment.java:133)
	at org.schabi.newpipe.fragments.list.channel.ChannelTabFragment.handleResult(ChannelTabFragment.java:37)
	at org.schabi.newpipe.fragments.list.BaseListInfoFragment.doInitialLoadLogic(BaseListInfoFragment.java:119)
	at org.schabi.newpipe.fragments.BaseStateFragment.onViewCreated(BaseStateFragment.java:47)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3019)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
	at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2777)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3020)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1831)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
	at androidx.fragment.app.FragmentManager.popBackStackImmediate(FragmentManager.java:812)
	at androidx.fragment.app.FragmentManager.popBackStackImmediate(FragmentManager.java:719)
	at androidx.fragment.app.FragmentManager.handleOnBackPressed(FragmentManager.java:640)
	at androidx.fragment.app.FragmentManager$1.handleOnBackPressed(FragmentManager.java:415)
	at androidx.activity.OnBackPressedDispatcher.onBackPressed(OnBackPressedDispatcher.java:192)
	at androidx.activity.ComponentActivity.onBackPressed(ComponentActivity.java:657)
	at org.schabi.newpipe.MainActivity.onBackPressed(MainActivity.java:576)
	at android.app.Activity.onKeyUp(Activity.java:4025)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2952)
	at android.app.Activity.dispatchKeyEvent(Activity.java:4376)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:126)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:86)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:144)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:601)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:60)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3106)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:392)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:7162)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7028)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6435)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6492)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6458)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6623)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6466)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6680)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6439)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6492)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6458)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6466)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6439)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6492)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6458)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6656)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:6867)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:4303)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:3740)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:3731)
	at android.view.inputmethod.InputMethodManager.-$$Nest$mfinishedInputEvent(Unknown Source:0)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:4280)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:162)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8216)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 14 / GrapheneOS 2023121200

### Affected device model

Google Pixel 7a

### Additional information

If you press the app's back button in the top left corner, it takes you back to the Albums screen as intended. The issue seems to be specifically with Android's back button.

**Comment by JavkhlanK** [comment]
Could still reproduce with 0.27.0 on Android 14:

opened an artist on bandcamp with the app, then went to an album, then pressed back and the app crashed. i was in the train, maybe my mobile data connection was lost
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.27.0
* __OS:__ Linux samsung/b0sxeea/b0s:14/UP1A.231005.007/S908BXXU9EXE1:user/release-keys 14 - 34
<details><summary><b>Crash log </b></summary><p>

```
android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1675)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:115)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49)
	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:169)
	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:131)
	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:73)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at org.schabi.newpipe.DownloaderImpl.execute(DownloaderImpl.java:163)
	at org.schabi.newpipe.extractor.downloader.Downloader.post(Downloader.java:143)
	at org.schabi.newpipe.extractor.downloader.Downloader.postWithContentType(Downloader.java:175)
	at org.schabi.newpipe.extractor.downloader.Downloader.postWithContentTypeJson(Downloader.java:217)
	at org.schabi.newpipe.extractor.downloader.Downloader.postWithContentTypeJson(Downloader.java:235)
	at org.schabi.newpipe.extractor.services.bandcamp.extractors.BandcampExtractorHelper.getArtistDetails(BandcampExtractorHelper.java:120)
	at org.schabi.newpipe.extractor.services.bandcamp.linkHandler.BandcampChannelLinkHandlerFactory.getUrl(BandcampChannelLinkHandlerFactory.java:55)
	at org.schabi.newpipe.extractor.linkhandler.ListLinkHandlerFactory.getUrl(ListLinkHandlerFactory.java:77)
	at org.schabi.newpipe.extractor.services.bandcamp.linkHandler.BandcampChannelTabLinkHandlerFactory.getUrl(BandcampChannelTabLinkHandlerFactory.java:56)
	at org.schabi.newpipe.extractor.linkhandler.ListLinkHandlerFactory.fromQuery(ListLinkHandlerFactory.java:57)
	at org.schabi.newpipe.fragments.list.channel.ChannelTabFragment.handleResult(ChannelTabFragment.java:136)
	at org.schabi.newpipe.fragments.list.channel.ChannelTabFragment.handleResult(ChannelTabFragment.java:38)
	at org.schabi.newpipe.fragments.list.BaseListInfoFragment.doInitialLoadLogic(BaseListInfoFragment.java:119)
	at org.schabi.newpipe.fragments.BaseStateFragment.onViewCreated(BaseStateFragment.java:47)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3147)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
	at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2945)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3148)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1934)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839)
	at androidx.fragment.app.FragmentManager.popBackStackImmediate(FragmentManager.java:891)
	at androidx.fragment.app.FragmentManager.popBackStackImmediate(FragmentManager.java:797)
	at androidx.fragment.app.FragmentManager.handleOnBackPressed(FragmentManager.java:717)
	at androidx.fragment.app.FragmentManager$1.handleOnBackPressed(FragmentManager.java:447)
	at androidx.activity.OnBackPressedDispatcher.onBackPressed(OnBackPressedDispatcher.kt:276)
	at androidx.activity.ComponentActivity.onBackPressed(ComponentActivity.java:678)
	at org.schabi.newpipe.MainActivity.onBackPressed(MainActivity.java:595)
	at android.app.Activity.onKeyUp(Activity.java:4157)
	at android.view.KeyEvent.dispatch(KeyEvent.java:3522)
	at android.app.Activity.dispatchKeyEvent(Activity.java:4505)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:120)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:85)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:138)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:604)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:60)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3413)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:678)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:8489)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:8349)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7682)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7739)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7705)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7908)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7713)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7965)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7686)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7739)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7705)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:7713)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:7686)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:7739)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:7705)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7941)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:8183)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:4578)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:4012)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:4003)
	at android.view.inputmethod.InputMethodManager.-$$Nest$mfinishedInputEvent(Unknown Source:0)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:4555)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:187)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```
</details>
<hr>
