### ISSUE TITLE
App crash, logs attched

### ISSUE THREAD

**Issue by heckarman** [TeamNewPipe/NewPipe#10683]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2

### Steps to reproduce the bug

IDK,
I downloaded a few videos and it started to crash randomly and now it does not open.

### Expected behavior

App shouldn't crash

### Actual behavior

App once starts to crash never opens.

### Logs

```
type: crash
osVersion: google/bluejay/bluejay:14/UQ1A.231205.015/2023121200:user/release-keys
package: org.polymorphicshade.newpipe:994
process: org.polymorphicshade.newpipe
processUptime: 356 + 214 ms
installer: com.machiav3lli.fdroid

java.lang.IllegalArgumentException: Tried to schedule job for non-existent component: ComponentInfo{org.polymorphicshade.newpipe/org.acra.sender.JobSenderService}
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3070)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:438)
	at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:87)
	at org.acra.scheduler.DefaultSenderScheduler.scheduleReportSending(DefaultSenderScheduler.kt:52)
	at org.acra.scheduler.SchedulerStarter.scheduleReports(SchedulerStarter.kt:49)
	at org.acra.startup.StartupProcessorExecutor.processReports$lambda$6$lambda$5(StartupProcessorExecutor.kt:60)
	at org.acra.startup.StartupProcessorExecutor.$r8$lambda$LK61ILz0qM6dPNH2J6guur40K2U(StartupProcessorExecutor.kt:0)
	at org.acra.startup.StartupProcessorExecutor$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.enforceValidJobRequest(JobSchedulerService.java:4295)
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:4486)
	at android.app.job.IJobScheduler$Stub.onTransact(IJobScheduler.java:227)
	at android.os.Binder.execTransactInternal(Binder.java:1361)
	at android.os.Binder.execTransact(Binder.java:1302)


```

### Affected Android/Custom ROM version

Android GrapheneOS

### Affected device model

Pixel 6A

**Comment by heckarman** [comment]
Closing this since I feel this is not an upstream issue but rather the issue with he fork itself
