### ISSUE TITLE
Instant crash when rotating screen while playing video with resolution selector menu open

### ISSUE THREAD

**Issue by skylarmt** [TeamNewPipe/NewPipe#10721]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.1

### Steps to reproduce the bug

1. Play a YouTube video while phone in portrait
2. Open the resolution menu
3. Turn phone sideways without closing menu
4. Instant crash!

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.26.1
* __OS:__ Linux Android 12 - 32
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalArgumentException: View=android.widget.PopupWindow$PopupDecorView{e0689b0 V.E...... R.....ID 0,0-515,756} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:535)
	at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:424)
	at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:145)
	at android.widget.PopupWindow.update(PopupWindow.java:2210)
	at android.widget.PopupWindow.update(PopupWindow.java:2331)
	at android.widget.PopupWindow.alignToAnchor(PopupWindow.java:2501)
	at android.widget.PopupWindow.access$000(PopupWindow.java:106)
	at android.widget.PopupWindow$1.onViewAttachedToWindow(PopupWindow.java:240)
	at android.view.View.dispatchAttachedToWindow(View.java:20823)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3497)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5290)
	at android.view.ViewGroup.addView(ViewGroup.java:5076)
	at android.view.ViewGroup.addView(ViewGroup.java:5016)
	at android.view.ViewGroup.addView(ViewGroup.java:4988)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$tryAddVideoPlayerView$41(VideoDetailFragment.java:1244)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.$r8$lambda$s-YSZ_fvw5kK3nBMjl4uKoby47w(VideoDetailFragment.java:0)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda66.accept(R8$$SyntheticClass:0)
	at j$.util.Optional.ifPresent(Unknown Source:4)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$tryAddVideoPlayerView$42(VideoDetailFragment.java:1239)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.$r8$lambda$S8n3OzU8HWJ8m_WwgX_142JT8Zo(VideoDetailFragment.java:0)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda57.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12 (LineageOS)

### Affected device model

Moto Z3 Play

**Comment by GfEW** [comment]
@opusforlife2 
I'm currently searching for relevant existing issues (open or closed) prior to possibly reporting a similar bug, and have found this one. 

As it ignores the template, I understand it has been closed. However, it also bears the label `duplicate`. 

I assume you didn't assign that label out of nowhere but actually had another issue in mind that already covers the same bug. **But wich other issue is that?**

I'd greatly appreciate if you, when closing duplicate issues, provided a brief comment with a link to the original issue.

Doing so would **save** affected users who take time to ensure unique bug reporting **the effort to search 8.5k issues (open or closed) for the approved original issue**.

Linking to the original issue is not just a nice habit to acquire, but moreover appreciates and encourages users to **spend their time on high quality reports** rather than unnecessary searches for dupes (or even getting sloppy thereby, to save the time).

Thanks a lot for considering!
