### ISSUE TITLE
Crash failure from system TransactionTooLargeException

### ISSUE THREAD

**Issue by AF1011** [TeamNewPipe/NewPipe#10748]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.1

### Steps to reproduce the bug

1. Select the video want to watch.
2. Look the Comments sections.

### Expected behavior

The comments section didn't load after the 10th Video watch.

### Actual behavior

The Application crashed after you click the Error message.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ KR
* __Content Language:__ ko-
* __App Language:__ in_ID
* __Service:__ none
* __Version:__ 0.26.1
* __OS:__ Linux Android 8.1.0 - 27
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Failure from system
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1620)
	at android.app.Activity.startActivityForResult(Activity.java:4506)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:712)
	at android.app.Activity.startActivityForResult(Activity.java:4464)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:693)
	at android.app.Activity.startActivity(Activity.java:4825)
	at android.app.Activity.startActivity(Activity.java:4793)
	at org.schabi.newpipe.error.ErrorUtil$Companion.openActivity(ErrorUtil.kt:43)
	at org.schabi.newpipe.error.ErrorUtil$Companion.showSnackbar$lambda$0(ErrorUtil.kt:149)
	at org.schabi.newpipe.error.ErrorUtil$Companion.$r8$lambda$hbVLiP6-HtFc17h3_yyNDsmaIY8(ErrorUtil.kt:0)
	at org.schabi.newpipe.error.ErrorUtil$Companion$$ExternalSyntheticLambda0.onClick(R8$$SyntheticClass:0)
	at com.google.android.material.snackbar.Snackbar.lambda$setAction$0(Snackbar.java:352)
	at com.google.android.material.snackbar.Snackbar.$r8$lambda$4rINiMZz55Dc47hSTCuz-ALWyEw(Snackbar.java:0)
	at com.google.android.material.snackbar.Snackbar$$ExternalSyntheticLambda1.onClick(R8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:6330)
	at android.view.View$PerformClick.run(View.java:24967)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6687)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
Caused by: android.os.TransactionTooLargeException: data parcel size 1241776 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:782)
	at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:4610)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1613)
	... 22 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 8.1.0

### Affected device model

LG Q6+ (M-700DSK)

**Comment by MDP43140** [comment]
I got the same error, but there is another instance where i got an error toast that shows up on the top of the screen instead of it being on the bottom of the screen, when clicking it the exact same crash happened

**Comment by Turkialh14** [comment]
**Steps to reproduce the bug**

.1 Create a large local playlist in the app

.2 Try sharing the playlist

.3 When choosing SHARE URL LIST and SHARE WITH TITLES When choosing SHARE URL LIST nothing happens and it stays frozen like this for a while then it doesn't give anything or sometimes it gets stuck and I can't move and when choosing SHARE WITH TITLES it shows me an error that it's large I assume that's because the playlist contains a lot of Korean, Chinese and Japanese videos whose letters take up more space than normal letters
