### ISSUE TITLE
Canvas error on scrolling media.ccc conferences list

### ISSUE THREAD

**Issue by ca-d** [TeamNewPipe/NewPipe#10751]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.1

### Steps to reproduce the bug

1. Go to media.ccc conferences
2. Scroll down swiftly

### Expected behavior

The list scrolls downward

### Actual behavior

The error pasted below

### Logs

scrolled through the media.ccc 'conferences' list
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ DE
* __Content Language:__ en-DE
* __App Language:__ en_DE
* __Service:__ none
* __Version:__ 0.26.1
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Canvas: trying to draw too large(125516160bytes) bitmap.
	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:266)
	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:94)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:549)
	at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:109)
	at android.widget.ImageView.onDraw(ImageView.java:1446)
	at com.google.android.material.imageview.ShapeableImageView.onDraw(ShapeableImageView.java:188)
	at android.view.View.draw(View.java:23195)
	at android.view.View.updateDisplayListIfDirty(View.java:22062)
	at android.view.View.draw(View.java:22926)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:1994)
	at android.view.View.draw(View.java:23198)
	at android.view.View.updateDisplayListIfDirty(View.java:22062)
	at android.view.View.draw(View.java:22926)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5204)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23198)
	at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4603)
	at android.view.View.updateDisplayListIfDirty(View.java:22062)
	at android.view.View.draw(View.java:22926)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22053)
	at android.view.View.draw(View.java:22926)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.kt:235)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.kt:225)
	at android.view.View.updateDisplayListIfDirty(View.java:22053)
	at android.view.View.draw(View.java:22926)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22053)
	at android.view.View.draw(View.java:22926)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1478)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22053)
	at android.view.View.draw(View.java:22926)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22053)
	at android.view.View.draw(View.java:22926)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22053)
	at android.view.View.draw(View.java:22926)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22053)
	at android.view.View.draw(View.java:22926)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.updateDisplayListIfDirty(View.java:22053)
	at android.view.View.draw(View.java:22926)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4529)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4290)
	at android.view.View.draw(View.java:23198)
	at com.android.internal.policy.DecorView.draw(DecorView.java:819)
	at android.view.View.updateDisplayListIfDirty(View.java:22062)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:688)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:786)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4579)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4290)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3517)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2286)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8948)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 13

### Affected device model

Pixel 4

**Comment by mss** [comment]
I think I run into the same bug by just loading https://media.ccc.de/v/bornhack2023-56142-sexy-ssh-hacks via the search box.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ DE
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.25.2
* __OS:__ Linux motorola/sofiar_reteu/sofiar:11/RPE31.Q4U-47-35/0edbf:user/release-keys 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Canvas: trying to draw too large(125516160bytes) bitmap.
	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:283)
	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:88)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:548)
	at com.squareup.picasso.PicassoDrawable.draw(PicassoDrawable.java:109)
	at android.widget.ImageView.onDraw(ImageView.java:1436)
	at com.google.android.material.imageview.ShapeableImageView.onDraw(ShapeableImageView.java:198)
	at android.view.View.draw(View.java:22422)
	at android.view.View.updateDisplayListIfDirty(View.java:21298)
	at android.view.View.draw(View.java:22153)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21289)
	at android.view.View.draw(View.java:22153)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22425)
	at android.view.View.updateDisplayListIfDirty(View.java:21298)
	at android.view.View.draw(View.java:22153)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21289)
	at android.view.View.draw(View.java:22153)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21289)
	at android.view.View.draw(View.java:22153)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21289)
	at android.view.View.draw(View.java:22153)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22425)
	at com.google.android.material.appbar.AppBarLayout.draw(AppBarLayout.java:419)
	at android.view.View.updateDisplayListIfDirty(View.java:21298)
	at android.view.View.draw(View.java:22153)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21289)
	at android.view.View.draw(View.java:22153)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22425)
	at android.view.View.updateDisplayListIfDirty(View.java:21298)
	at android.view.View.draw(View.java:22153)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.kt:235)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.kt:225)
	at android.view.View.updateDisplayListIfDirty(View.java:21289)
	at android.view.View.draw(View.java:22153)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21289)
	at android.view.View.draw(View.java:22153)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at androidx.drawerlayout.widget.DrawerLayout.drawChild(DrawerLayout.java:1478)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21289)
	at android.view.View.draw(View.java:22153)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21289)
	at android.view.View.draw(View.java:22153)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21289)
	at android.view.View.draw(View.java:22153)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21289)
	at android.view.View.draw(View.java:22153)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.updateDisplayListIfDirty(View.java:21289)
	at android.view.View.draw(View.java:22153)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
	at android.view.View.draw(View.java:22425)
	at com.android.internal.policy.DecorView.draw(DecorView.java:840)
	at android.view.View.updateDisplayListIfDirty(View.java:21298)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4231)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3958)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3229)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2064)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8400)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:731)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:250)
	at android.app.ActivityThread.main(ActivityThread.java:7755)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

```
</details>
<hr>

**Comment by ghost** [comment]
I can reproduce it on 0.28.0 with provided video link

Seems like there is an image which hits limits of drawable size (~119MB O_o) of Picasso library. Or probably just  a bug in Picasso itself because it is hard to believe there will 119MB image file....

Not reproducible in refactor branch because it [already moved](11238) from Picasso to Coil library

**Comment by ghost** [comment]
Solved in/by https://github.com/TeamNewPipe/NewPipe/pull/13272
