### ISSUE TITLE
[YouTube] Initial player response is not valid when trying to watch videos on some networks/IPs

### ISSUE THREAD

**Issue by proteusblack** [TeamNewPipe/NewPipe#10758]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.2

### Steps to reproduce the bug

1. Download Newpipe from F-droid and install as normal
2. Open Newpipe as normal and click on any video at all

### Expected behavior

Should play the video. 

### Actual behavior

Unfortunately, it gives a parsing error. 

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=doTGDc1SoOE
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.25.2
* __OS:__ Linux samsung/r8qsqx/r8q:13/TP1A.220624.014/G781USQUCHWH4:user/release-keys 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ExtractionException: Initial player response is not valid
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:872)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:78)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:73)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:119)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(ExtractorHelper.java:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda3.call(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5377)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16013)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5377)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```
</details>
<hr>

### Affected Android/Custom ROM version

13

### Affected device model

Samsung Galaxy S20 FE SG

**Comment by AudricV** [comment]
> - [x] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest)

You are not using the latest version. Please update to the latest version before opening a new issue.

There is nothing we can do, YouTube seems to ban (by mistake probably) logged-out access to its videos on mobile data IPs, according to several reports on Reddit and X/Twitter.

Could you please update to 0.26.1 and confirm this behavior by opening YouTube's website in a private window of a web browser connected on the IP you're using to stream NewPipe (so the web browser of your phone), and see if, when you try to watch a video on the website, after any ad, that you're getting a video with the message "This content isn't available" instead?

Then see if you can reproduce this with a Wifi connection.

**Comment by proteusblack** [comment]
Steps I now took:
- Upgraded to 0.26.1 using the custom repo
- Connected to a wifi connection
- Opened a private tab in Firefox on Android
- Opened YouTube.com and opened as video

Result: "This content is not available" message.

**Comment by ABJ4403** [comment]
Try in NewPipe, it should throw an error, click see logs, the error message should explain why its not available

Also if you use custom "filteting" dns (especially AdGuard Family, which redirects www.youtube.com to restrictmoderate.youtube.com), change it to something else (error msg might say something workspace related)

**Comment by proteusblack** [comment]
By logs, do you mean the error report? Because it just shows the same thing that it shows in the log I shared above.

**Comment by AudricV** [comment]
Is the issue gone? I do not see anymore this issue posted here and on YouTube and NewPipe subreddits and a user edited [their post](https://www.reddit.com/r/NewPipe/comments/198j9wg/newpipe_0260_and_0261_blocked_by_att_cricket_but/) saying that the issue has been fixed.
