### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by stephen-hill** [TeamNewPipe/NewPipe#10833]
### Affected version

0.26.1

### Steps to reproduce the bug

Add video to playlist

### Expected behavior

No crash

### Actual behavior

Crash

### Logs

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.26.1
* __OS:__ Linux motorola/capri_retailen/capri:11/RRB31.Q1-3-48/5b092:user/release-keys 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at org.schabi.newpipe.local.dialog.PlaylistAppendDialog.lambda$onPlaylistSelected$4(PlaylistAppendDialog.java:163)
	at org.schabi.newpipe.local.dialog.PlaylistAppendDialog.$r8$lambda$zTWALft3TUabC8jelCR2F7daRCg(PlaylistAppendDialog.java:0)
	at org.schabi.newpipe.local.dialog.PlaylistAppendDialog$$ExternalSyntheticLambda4.accept(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeCallbackObserver.onSuccess(MaybeCallbackObserver.java:71)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeObserveOn$ObserveOnMaybeObserver.run(MaybeObserveOn.java:103)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:250)
	at android.app.ActivityThread.main(ActivityThread.java:7806)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

```
</details>
<hr>

**Comment by stephen-hill** [comment]
Also, I keep sending this bug report via the email button, but I never receive a response.

Does anyone read the emails sent to crashreport@newpipe.schabi.org?

If so, it would be nice to get a response, even an automated one.

**Comment by ShareASmile** [comment]
**Don't remove the Template Please**
It is mandatory when filling an issue. 
Deleting Template invites immediate closure of the issue.

Also try to give issue a better description & search better with error keywords to find duplicates first to avoid creating duplicates while opening an issue next time, Thank you.

**Comment by stephen-hill** [comment]
@ShareASmile You said this was a duplicate. Please can you link to the active issue?
