### ISSUE TITLE
Crash upon refreshing feed while watching video from subscribed channel

### ISSUE THREAD

**Issue by jpggithub** [TeamNewPipe/NewPipe#10847]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.1

### Steps to reproduce the bug

1. Watch one or more videos on youtube within the subscribed channels
2. Refresh the list of the subscribed channels
3.  Then NewPipe crash

This bug occurs each time that I do the same process.

EDIT: There's no crash when I refresh the list of subscribed channels without watching a video.

### Expected behavior

I expect that Newpipe does not crash.

### Actual behavior

Newpipe crash when refresh the list of subscribed channels

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ FR
* __Content Language:__ fr-FR
* __App Language:__ fr_FR
* __Service:__ none
* __Version:__ 0.26.1
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalArgumentException: Cannot coerce value to an empty range: maximum 0 is less than minimum 1.
	at kotlin.ranges.RangesKt___RangesKt.coerceIn(_Ranges.kt:1413)
	at kotlin.ranges.RangesKt.coerceIn(Unknown Source:0)
	at org.schabi.newpipe.local.feed.FeedFragment.highlightNewItemsAfter(FeedFragment.kt:591)
	at org.schabi.newpipe.local.feed.FeedFragment.handleLoadedState$lambda$13(FeedFragment.kt:408)
	at org.schabi.newpipe.local.feed.FeedFragment.$r8$lambda$BLo2f7SqMRDylXOcnJDcu9Up0dM(FeedFragment.kt:0)
	at org.schabi.newpipe.local.feed.FeedFragment$$ExternalSyntheticLambda6.onUpdateComplete(R8$$SyntheticClass:0)
	at com.xwray.groupie.DiffTask.onPostExecute(DiffTask.java:61)
	at com.xwray.groupie.DiffTask.onPostExecute(DiffTask.java:18)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.access$900(AsyncTask.java:199)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 11/LineageOS 18.1

### Affected device model

Lenovo P2

**Comment by nicoursi** [comment]
Any news on this annoying bug?

**Comment by jpggithub** [comment]
Following the previous question, as I didn't see other echos of this bug, I exported my history, parameters, etc. Then I uninstalled Newpipe, reinstalled it, imported my history, parameters, etc.

I made the same test than before and Newpipe does not crash anymore so I think the bug can be closed.
