### ISSUE TITLE
Download crash ：No virtual method toArray(Ljava/util/function/IntFunction;)[Ljava/lang/Object;

### ISSUE THREAD

**Issue by NewMacPro** [TeamNewPipe/NewPipe#10868]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

V0.23.1

### Steps to reproduce the bug

Download any videos

    mission.recoveryInfo = recovery.toArray(MissionRecoveryInfo[]::new);

this line crash

ACRA caught a NoSuchMethodError for org.schabi.newpipe.debug
                                                                                                    java.lang.NoSuchMethodError: No virtual method toArray(Ljava/util/function/IntFunction;)[Ljava/lang/Object; in class Ljava/util/ArrayList; or its super classes (declaration of 'java.util.ArrayList' appears in /apex/com.android.art/javalib/core-oj.jar)
                                                                                                    	at us.shandian.giga.service.DownloadManagerService.startMission(DownloadManagerService.java:417)
                                                                                                    	at us.shandian.giga.service.DownloadManagerService.lambda$onStartCommand$0(DownloadManagerService.java:203)
                                                                                                    	at us.shandian.giga.service.DownloadManagerService.$r8$lambda$MIdSUnC6_dsRShNMzgcR8XXA0_Q(Unknown Source:0)
                                                                                                    	at us.shandian.giga.service.DownloadManagerService$$ExternalSyntheticLambda1.run(Unknown Source:4)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:210)
                                                                                                    	at android.os.Looper.loop(Looper.java:299)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8273)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)

**Comment by NewMacPro** [comment]
> > I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest)
> 
> > Affected version
> > v0.23.1
> 
> You are not on latest version.

Sorry, I didn't describe it clearly. The extractor is V0.23.1. The app is the latest version of the dev branch.v0.26.1.apk

**Comment by Stypox** [comment]
Reopening since this crash for some reason didn't bring up ACRA, so it can't be reported in the "normal" format, but the issue description contains all details anyway. This should be fixed by https://github.com/TeamNewPipe/NewPipe/pull/10912, please test :-)
