### ISSUE TITLE
Crash after change a resolution and back to history

### ISSUE THREAD

**Issue by KPniX** [TeamNewPipe/NewPipe#10861]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [x] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.1

### Steps to reproduce the bug

1. Open a history (I have pined)
2. Scroll down and open any video from history
3. Wait to loading video
4. Rolate phone to fullscreen mode
5. CHANGE A RESOLUTION
6. Rolate phone to vertical position and click back button
7. Try scroll up to top
8. App was crashed

### Expected behavior

After scroll up to top, app shouldn't crashed and display part of interface 

### Actual behavior

After scroll up to top, app crash

### Screenshots/Screen recordings

https://drive.google.com/file/d/1FQ8IvPZRoTWUFPgphZI-bwd99ESycs1N/view?usp=drive_link
INFO! This clip was recorded on older version of NewPipe (newest on F-Droid - 0.25.2), but on newest version - 0.26.1 - still have this same problem after this same steps on video/manual. If you request a clip from newest version, please write back.

### Logs

Bug report came from Unihertz T200 (Jelly Pro), but this same proble I have too on other phones and Android version:
## Exception
* _User Action:_ ui error
* _Request:_ ACRA report
* _Content Country:_ PL
* _Content Language:_ pl-
* _App Language:_ pl
* _Service:_ none
* _Version:_ 0.26.1
* _OS:_ Linux Android 8.1.0 - 27
<details><summary><b>Crash log </b></summary><p>

java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7297)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6416)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6548)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)

</details>
<hr>

### Affected Android/Custom ROM version

Android 13 (0.25.2), Android 8.1 (0.26.1)

### Affected device model

Samsung Galaxy A54 5G (0.25.2), Unihertz T200 (Jelly Pro) (0.26.1)

**Comment by ShareASmile** [comment]
Already reproduced by same steps in #10404 
Both actually are duplicates of  #4475

**Comment by KPniX** [comment]
I'm sorry, but I think this is first problem registry, becouse i have seen probably in each version this same "bug" and still - no repair
