### ISSUE TITLE
[nightly] crashes when trying to load the comments

### ISSUE THREAD

**Issue by throwaway26425** [TeamNewPipe/NewPipe#10888]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.1

### Steps to reproduce the bug

1. enable the "Show Comments" option.
2. go to random videos and try to read the comments.
3. it will crash, a LOT of times, when these comments are about to load.

### Expected behavior

it shouldn't crash.

### Actual behavior

the app just crashes.

### Screenshots/Screen recordings

<img alt="screenshot_20240315-151016" src="https://github.com/TeamNewPipe/NewPipe/assets/85243826/bea569b7-82b8-41ff-9df1-42b2ba79a0d8" width=284 />

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.26.1
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int org.schabi.newpipe.extractor.stream.Description.getType()' on a null object reference
	at org.schabi.newpipe.util.text.TextLinkifier.fromDescription(TextLinkifier.java:70)
	at org.schabi.newpipe.util.text.TextEllipsizer.linkifyContentView(TextEllipsizer.java:166)
	at org.schabi.newpipe.util.text.TextEllipsizer.setContent(TextEllipsizer.java:62)
	at org.schabi.newpipe.info_list.holder.CommentInfoItemHolder.updateFromItem(CommentInfoItemHolder.java:127)
	at org.schabi.newpipe.info_list.InfoListAdapter.onBindViewHolder(InfoListAdapter.java:337)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7747)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7847)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6646)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6917)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4348)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919)
	at android.view.View.layout(View.java:22406)
	at android.view.ViewGroup.layout(ViewGroup.java:6594)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
	at android.view.View.layout(View.java:22406)
	at android.view.ViewGroup.layout(ViewGroup.java:6594)
	at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
	at android.view.View.layout(View.java:22406)
	at android.view.ViewGroup.layout(ViewGroup.java:6594)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:149)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2381)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
	at android.view.View.layout(View.java:22406)
	at android.view.ViewGroup.layout(ViewGroup.java:6594)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:22406)
	at android.view.ViewGroup.layout(ViewGroup.java:6594)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:22406)
	at android.view.ViewGroup.layout(ViewGroup.java:6594)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
	at com.google.android.material.bottomsheet.BottomSheetBehavior.onLayoutChild(BottomSheetBehavior.java:576)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
	at android.view.View.layout(View.java:22406)
	at android.view.ViewGroup.layout(ViewGroup.java:6594)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1263)
	at android.view.View.layout(View.java:22406)
	at android.view.ViewGroup.layout(ViewGroup.java:6594)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:22406)
	at android.view.ViewGroup.layout(ViewGroup.java:6594)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:22406)
	at android.view.ViewGroup.layout(ViewGroup.java:6594)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:22406)
	at android.view.ViewGroup.layout(ViewGroup.java:6594)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:22406)
	at android.view.ViewGroup.layout(ViewGroup.java:6594)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1075)
	at android.view.View.layout(View.java:22406)
	at android.view.ViewGroup.layout(ViewGroup.java:6594)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3396)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2863)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1911)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8528)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7091)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 9

### Affected device model

Samsung Galaxy A10

### Additional information

.

**Comment by TheMCNerd2017** [comment]
I have the same issue and even reported it as well a few months ago (thinking it was rare random crash due to a YouTube A/B test) however it was closed due to the crash not occurring on the stable build. From my experience there are many actions that trigger this crash including: loading any video, viewing the description of a video, going to another video in a playlist, listening to a playlist in the background, scrolling down in the comments section.

Additionally when this crash occurs, saved playlists and potentially other data seem to revert to an older state.

**Comment by AudricV** [comment]
@opusforlife2 No, that's not the same issue, it's an app bug. even if it can be reproduced by being hit with YT A/B test: read the stacktrace. Reopening.

**Comment by throwaway26425** [comment]
@opusforlife2 I'll record a video of this, but no, it's not the same bug that you mentioned.

just wait me a few minutes.

**Comment by throwaway26425** [comment]
here:

https://github.com/TeamNewPipe/NewPipe/assets/85243826/19f1834b-8273-4cb8-8be2-a467e004dc32

it happens right before the comments even load.

this specific bug only happens in the Nightly version, not the stable version of NewPipe.

so... I guess it's a bug related to the implementation of replies?

**Comment by throwaway26425** [comment]
sorry for asking, but is that commit already merged to the nightly build?

I've just downloaded `nightly-107`, but I'm getting the very same crash :(

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.26.1
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int org.schabi.newpipe.extractor.stream.Description.getType()' on a null object reference
	at org.schabi.newpipe.util.text.TextLinkifier.fromDescription(TextLinkifier.java:70)
	at org.schabi.newpipe.util.text.TextEllipsizer.linkifyContentView(TextEllipsizer.java:166)
	at org.schabi.newpipe.util.text.TextEllipsizer.setContent(TextEllipsizer.java:62)
	at org.schabi.newpipe.info_list.holder.CommentInfoItemHolder.updateFromItem(CommentInfoItemHolder.java:127)
	at org.schabi.newpipe.info_list.InfoListAdapter.onBindViewHolder(InfoListAdapter.java:337)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7747)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7847)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6646)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6917)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4348)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919)
	at android.view.View.layout(View.java:22406)
	at android.view.ViewGroup.layout(ViewGroup.java:6594)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1083)
	at android.view.View.layout(View.java:22406)
	at android.view.ViewGroup.layout(ViewGroup.java:6594)
	at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
	at android.view.View.layout(View.java:22406)
	at android.view.ViewGroup.layout(ViewGroup.java:6594)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:149)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2381)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
	at android.view.View.layout(View.java:22406)
	at android.view.ViewGroup.layout(ViewGroup.java:6594)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:22406)
	at android.view.ViewGroup.layout(ViewGroup.java:6594)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:22406)
	at android.view.ViewGroup.layout(ViewGroup.java:6594)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
	at com.google.android.material.bottomsheet.BottomSheetBehavior.onLayoutChild(BottomSheetBehavior.java:576)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
	at android.view.View.layout(View.java:22406)
	at android.view.ViewGroup.layout(ViewGroup.java:6594)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1263)
	at android.view.View.layout(View.java:22406)
	at android.view.ViewGroup.layout(ViewGroup.java:6594)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:22406)
	at android.view.ViewGroup.layout(ViewGroup.java:6594)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:22406)
	at android.view.ViewGroup.layout(ViewGroup.java:6594)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:22406)
	at android.view.ViewGroup.layout(ViewGroup.java:6594)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:22406)
	at android.view.ViewGroup.layout(ViewGroup.java:6594)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1075)
	at android.view.View.layout(View.java:22406)
	at android.view.ViewGroup.layout(ViewGroup.java:6594)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3396)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2863)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1911)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8528)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
	at android.view.Choreographer.doFrame(Choreographer.java:696)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7091)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

```
</details>
<hr>

**Comment by throwaway242685** [comment]
sorry for asking, but idk if this is supposed to be already fixed in Nightly?

because I'm still getting the same error in the latest `nightly-110`
