### ISSUE TITLE
Full screen bug in Google TV.

### ISSUE THREAD

**Issue by 1YuvrajS** [TeamNewPipe/NewPipe#10911]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

v0.26.1

### Steps to reproduce the bug

1. I searched any video Topics.
2. I choose Video in Search results.
3. Then clicked on the Video then Video Started playing.
4. When I go to full Screen.
5. Then gives an error in any Video I wish want play in full screen.

### Screenshots/Screen recordings

![IMG_20240328_111823](https://github.com/TeamNewPipe/NewPipe/assets/93419850/7f185cde-ae1e-463c-a14c-c901853af25e)

### Affected device model

_Chromecast with Google TV (HD) Media Streaming Device_

**Comment by ermac0** [comment]
I'm getting an error when switching to full screen
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.26.1
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.schabi.newpipe.nightly/org.schabi.newpipe.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment org.schabi.newpipe.fragments.detail.DescriptionFragment: could not find Fragment constructor
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3123)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3258)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5014)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4923)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:7029)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment org.schabi.newpipe.fragments.detail.DescriptionFragment: could not find Fragment constructor
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:687)
	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:525)
	at androidx.fragment.app.FragmentState.instantiate(FragmentState.java:84)
	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:91)
	at androidx.fragment.app.FragmentManager.restoreSaveStateInternal(FragmentManager.java:2562)
	at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1988)
	at androidx.fragment.app.Fragment.onCreate(Fragment.java:1967)
	at org.schabi.newpipe.BaseFragment.onCreate(BaseFragment.java:50)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.onCreate(VideoDetailFragment.java:307)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3094)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:504)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:268)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
	at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2941)
	at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:252)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:219)
	at org.schabi.newpipe.MainActivity.onCreate(MainActivity.java:142)
	at android.app.Activity.performCreate(Activity.java:7163)
	at android.app.Activity.performCreate(Activity.java:7154)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3097)
	... 13 more
Caused by: java.lang.NoSuchMethodException: <init> []
	at java.lang.Class.getConstructor0(Class.java:2327)
	at java.lang.Class.getConstructor(Class.java:1725)
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:672)
	... 36 more

```
</details>
<hr>

**Comment by D4RKW1NT3R** [comment]
Was able to reproduce on my google TV as well
