### ISSUE TITLE
App Crash on mark video as watched

### ISSUE THREAD

**Issue by proggaliu** [TeamNewPipe/NewPipe#10939]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.1

### Steps to reproduce the bug

1. Youtube channels feed
2. Mark videos as watched
3. Pull down to update feed

### Expected behavior

Update feed and remove the watched videos

### Actual behavior

App crash

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ SE
* __Content Language:__ en-GB
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.26.1
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalArgumentException: Cannot coerce value to an empty range: maximum 12 is less than minimum 16.
	at kotlin.ranges.RangesKt___RangesKt.coerceIn(_Ranges.kt:1413)
	at kotlin.ranges.RangesKt.coerceIn(Unknown Source:0)
	at org.schabi.newpipe.local.feed.FeedFragment.highlightNewItemsAfter(FeedFragment.kt:591)
	at org.schabi.newpipe.local.feed.FeedFragment.handleLoadedState$lambda$13(FeedFragment.kt:408)
	at org.schabi.newpipe.local.feed.FeedFragment.$r8$lambda$BLo2f7SqMRDylXOcnJDcu9Up0dM(FeedFragment.kt:0)
	at org.schabi.newpipe.local.feed.FeedFragment$$ExternalSyntheticLambda6.onUpdateComplete(R8$$SyntheticClass:0)
	at com.xwray.groupie.DiffTask.onPostExecute(DiffTask.java:61)
	at com.xwray.groupie.DiffTask.onPostExecute(DiffTask.java:18)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.access$900(AsyncTask.java:199)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7881)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12

### Affected device model

Ulefone

**Comment by proggaliu** [comment]
> Try this? [#10847 (comment)](https://github.com/TeamNewPipe/NewPipe/issues/10847#issuecomment-1992701573)

Reinstall does not work. Tested on several versions. One thing to mention is that this issue only seems to occur when several videos are marked as watched. 8+ to be sure.

**Comment by proggaliu** [comment]
Seems like issue is resolved in v0.27

**Comment by jpggithub** [comment]
As I encountered this bug (see https://github.com/TeamNewPipe/NewPipe/issues/11897), do not hesitate to ask more information if needed. I would be glad if I can help.

**Comment by Dev-Aditya-More** [comment]
Hey can i try to resolve this one. assign me
