### ISSUE TITLE
opening bookmarked yt vid link fails to play

### ISSUE THREAD

**Issue by js290** [TeamNewPipe/NewPipe#10974]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.1

### Steps to reproduce the bug

1. Open messaging app
2. click on bookmarked youtube vid link
3. NewPipe 0.26.1 opens to the vid, but is not able to play

### Expected behavior

opening bookmarked links has worked previously

### Actual behavior

NewPipe opens up, loads the video seemingly at the bookmark, but is unable to play the video.

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_DECODING_FAILED] occurred while playing https://youtu.be/c876lPZ-UZU?t=4168
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.26.1
* __OS:__ Linux Android 14 - 34
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(243, null, null, video/x-vnd.on2.vp9, vp9, 368706, en, [640, 360, 25.0], [-1, -1]), format_supported=YES
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:578)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: c2.qti.vp9.decoder
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1639)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:803)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1007)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:502)
	... 4 more
Caused by: android.media.MediaCodec$CodecException: Error 0x80000000

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 14 / LineageOS 21

### Affected device model

Pixel 4

**Comment by js290** [comment]
this seems to be working correctly in `0.27.0`.

**Comment by js290** [comment]
this started happening again...
## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_DECODING_FAILED] occurred while playing https://www.youtube.com/watch?v=MyKxwnUd500
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.27.0
* __OS:__ Linux Android 14 - 34
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(243, null, null, video/x-vnd.on2.vp9, vp9, 411412, en, [640, 360, 24.0], [-1, -1]), format_supported=YES
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:578)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.os.HandlerThread.run(HandlerThread.java:68)
Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: c2.qti.vp9.decoder
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1639)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:803)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1007)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:502)
	... 4 more
Caused by: android.media.MediaCodec$CodecException: Error 0x80000000

```
</details>
<hr>

**Comment by js290** [comment]
It did take an OS update on 20240506.  I just rebooted, and still the same problem.  Maybe something changed on youtube end?

**Comment by js290** [comment]
> Possibly, but that doesn't help us debug this. Try this: use yt-dlp to download format 243 to your device. Then play it with https://f-droid.org/en/packages/com.brouken.player/ . If it is unable to play, then this is a problem with your device's decoder.
> 
> Then the only solution will be to use a lower resolution/codec combo.

```
243     webm  640x360     24    │  159.90MiB  197k https │ vp09.00.21.08  197k video only          360p, webm_dash
```
video only... plays fine with `Just Player`

**Comment by js290** [comment]
> Do other resolutions/codecs play fine? Or is the problem universal?

The problem opening a bookmarked youtube link.  It will play the video, just not from the linked bookmark.

**Comment by js290** [comment]
> Then the only solution will be to use a lower resolution/codec combo.

I just found a [yt vid](https://youtu.be/q6QyTZs__Pw?t=214) that only supports up to `240p` that NewPipe was able to open with a bookmark link.

**Comment by js290** [comment]
What is the point of opening a case with error output generated by the app itself, only for @opusforlife2 to stall it out?  Is @opusforlife2 a bot?!

**Comment by js290** [comment]
> You were asked do to a test. You haven't done it yet.

This is a joke... all the crash logs generated by NewPipe itself have been included.
