### ISSUE TITLE
opening newpipe from the app drawer causes it to crash with "ui error"

### ISSUE THREAD

**Issue by xFireFist** [TeamNewPipe/NewPipe#10982]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.1

### Steps to reproduce the bug

Opening the app from the apl drawer sometimes causes it to crash

### Expected behavior

Landing in the app home page

### Actual behavior

"Ui error" accurs upon opening

### Screenshots/Screen recordings

<img alt="Screenshot_20240417-021600" src="https://github.com/TeamNewPipe/NewPipe/assets/37742919/e97475d4-8af1-46f8-95f1-ddf1df6ac7be" width=337 />

### Logs

```
java.lang.OutOfMemoryError: Failed to allocate a 90120 byte allocation with 73856 free bytes and 71KB until OOM
	at java.io.ObjectOutputStream$HandleTable.growEntries(ObjectOutputStream.java:2418)
	at java.io.ObjectOutputStream$HandleTable.assign(ObjectOutputStream.java:2347)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1468)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1218)
	at java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1418)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1214)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1584)
	at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:454)
	at java.lang.Throwable.writeObject(Throwable.java:974)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:977)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1536)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1472)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1218)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:346)
	at java.util.ArrayList.writeObject(ArrayList.java:734)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:977)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1536)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1472)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1218)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1584)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1549)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1472)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1218)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:346)
	at java.util.LinkedList.writeObject(LinkedList.java:1132)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:977)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1536)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1472)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1218)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:346)
	at org.schabi.newpipe.util.StateSaver.tryToSave(StateSaver.java:255)
	at org.schabi.newpipe.util.StateSaver.tryToSave(StateSaver.java:167)
	at org.schabi.newpipe.fragments.list.BaseListFragment.onSaveInstanceState(BaseListFragment.java:174)
	at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:3183)
	at androidx.fragment.app.FragmentStateManager.saveBasicState(FragmentStateManager.java:680)
	at androidx.fragment.app.FragmentStateManager.saveState(FragmentStateManager.java:646)
	at androidx.fragment.app.FragmentStore.saveActiveFragments(FragmentStore.java:214)
	at androidx.fragment.app.FragmentManager.saveAllStateInternal(FragmentManager.java:2318)
	at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:3185)
	at androidx.fragment.app.FragmentStateManager.saveBasicState(FragmentStateManager.java:680)
	at androidx.fragment.app.FragmentStateManager.saveState(FragmentStateManager.java:646)
	at androidx.fragment.app.FragmentStore.saveActiveFragments(FragmentStore.java:214)
	at androidx.fragment.app.FragmentManager.saveAllStateInternal(FragmentManager.java:2318)
	at androidx.fragment.app.FragmentManager.lambda$attachController$0(FragmentManager.java:2572)
	at androidx.fragment.app.FragmentManager.$r8$lambda$XfPeDpLzKWrJr916TDyhue4S3eM(FragmentManager.java:0)
	at androidx.fragment.app.FragmentManager$$ExternalSyntheticLambda0.saveState(R8$$SyntheticClass:0)
	at androidx.savedstate.SavedStateRegistry.performSave(SavedStateRegistry.kt:247)
	at androidx.savedstate.SavedStateRegistryController.performSave(SavedStateRegistryController.kt:81)
	at androidx.activity.ComponentActivity.onSaveInstanceState(ComponentActivity.java:368)
	at android.app.Activity.performSaveInstanceState(Activity.java:1504)
	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1308)
	at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:5017)
	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4284)
	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4343)
	at android.app.ActivityThread.-wrap28(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1670)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6776)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```

### Affected Android/Custom ROM version

Android 7 api 24 samsung UI

### Affected device model

samsung a310f (A3 2016)

**Comment by xFireFist** [comment]
> > Failed to allocate a 90120 byte allocation with 73856 free bytes and 71KB until OOM
> 
> This looks like you're running low on RAM. What happens if you try this while other apps are not running?

This is a dedicated music player no other apps are running.
Usually if a podcast was last played this issue comes apps and will not go away unless the device is restarted, i checked with CPU-Z there was about 200-300mb ram free
