### ISSUE TITLE
Report (Android 6)

### ISSUE THREAD

**Issue by bw4518** [TeamNewPipe/NewPipe#10998]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.0

### Steps to reproduce the bug

1. Playing any video on YT

### Expected behavior

Video plays.

### Actual behavior

Logs following error.

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_AUDIO_TRACK_INIT_FAILED] occurred while playing https://www.youtube.com/watch?v=i5BElynqBEo
* __Content Country:__ SK
* __Content Language:__ sk-SK
* __App Language:__ sk_SK
* __Service:__ YouTube
* __Version:__ 0.27.0
* __OS:__ Linux Android 6.0.1 - 23
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(140, null, null, audio/mp4a-latm, mp4a.40.2, 130338, en, [-1, -1, -1.0], [2, 44100]), format_supported=YES
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:578)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed 0 Config(44100, 12, 44100) Format(null, null, null, audio/raw, null, -1, null, [-1, -1, -1.0], [2, 44100])
	at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:2154)
	at com.google.android.exoplayer2.audio.DefaultAudioSink.buildAudioTrack(DefaultAudioSink.java:1073)
	at com.google.android.exoplayer2.audio.DefaultAudioSink.buildAudioTrackWithRetry(DefaultAudioSink.java:1051)
	at com.google.android.exoplayer2.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:843)
	at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:929)
	at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:709)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1889)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:782)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1007)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:502)
	... 3 more
	Suppressed: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed 0 Config(44100, 12, 44100) Format(null, null, null, audio/raw, null, -1, null, [-1, -1, -1.0], [2, 44100])
		... 13 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 6.0.1 / Omni (custom rom)

### Affected device model

Samsung Galaxy Tab 2 (P5110)

### Additional information

I have tried to change the video formats, but no change.

**Comment by bw4518** [comment]
I don't know, its a 'new' device that got in my hands. I could test it, but I reported it since NewPipe should support it from  Android 5+.

**Comment by bw4518** [comment]
Yes, tested it today, the same error on 0.26.1.

**Comment by bw4518** [comment]
I did try it. Probably the same error.
```
AudioTrack init failed 0 Config(48000, 12, 48000) Format(2, null, null, audio/
raw, null, -1, en, [-1, -1, -1.0, null], [2, 48000])
```
