### ISSUE TITLE
YouTube Videos stuck on buffering.

### ISSUE THREAD

**Issue by dhaumya** [TeamNewPipe/NewPipe#11030]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.0

### Steps to reproduce the bug

1. Play a youtube video on newpipe.

### Expected behavior

The video loads and plays.

### Actual behavior

The video is stuck buffering.

### Screenshots/Screen recordings

https://github.com/TeamNewPipe/NewPipe/assets/65946378/023eaa26-6a1f-44bb-bfe2-bdaeb672ea11

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_NETWORK_CONNECTION_TIMEOUT] occurred while playing https://www.youtube.com/watch?v=NPqDIwWMtxg
* __Content Country:__ US
* __Content Language:__ en-
* __App Language:__ en
* __Service:__ YouTube
* __Version:__ 0.27.0
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketTimeoutException: SSL handshake timed out
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:389)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:796)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:609)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.chunk.InitializationChunk.load(InitializationChunk.java:99)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.net.SocketTimeoutException: SSL handshake timed out
	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:387)
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:226)
	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.makeConnection(YoutubeHttpDataSource.java:704)
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.makeConnection(YoutubeHttpDataSource.java:548)
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:383)
	... 10 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 10

### Affected device model

Lenovo Tab M10

### Additional information

1. My tab is degoogled(Google services have been disabled). 
2. The video loads perfectly fine in web browser.
3. I might been caught in the crossfire of YouTube vs adblockers.

**Comment by dhaumya** [comment]
It's loading now after I set up microG(for revanced) that might have been the issue but it was weird that it suddenly stopped working. I will test it for a few more days disabling/enabling microG and comment my observations.

**Comment by Paperwght** [comment]
## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_NETWORK_CONNECTION_TIMEOUT] occurred while playing https://www.youtube.com/watch?v=Miu_akSity4
* __Content Country:__ BR
* __Content Language:__ pt-BR
* __App Language:__ pt_BR
* __Service:__ YouTube
* __Version:__ 0.27.0
* __OS:__ Linux motorola/devon_g/devon:13/T2SN33.73-22-3/8d297-b531e:user/release-keys 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.os.HandlerThread.run(HandlerThread.java:85)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketTimeoutException: failed to connect to rr1---sn-4pgxoxunxg8pjvncg-bpbe.googlevideo.com/168.194.166.204 (port 443) from /192.168.1.249 (port 41854) after 8000ms
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:389)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:796)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:609)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.chunk.InitializationChunk.load(InitializationChunk.java:99)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.net.SocketTimeoutException: failed to connect to rr1---sn-4pgxoxunxg8pjvncg-bpbe.googlevideo.com/168.194.166.204 (port 443) from /192.168.1.249 (port 41854) after 8000ms
	at libcore.io.IoBridge.connectErrno(IoBridge.java:235)
	at libcore.io.IoBridge.connect(IoBridge.java:179)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
	at java.net.Socket.connect(Socket.java:646)
	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:182)
	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:145)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.makeConnection(YoutubeHttpDataSource.java:704)
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.makeConnection(YoutubeHttpDataSource.java:548)
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:383)
	... 10 more

```
</details>
<hr>

Same problem, though after a while buffering NewPipe stops trying and sends an error. I've also tested viewing the video on a browser and it works. I have MicroG set up and nothing changes whether I have it, uninstall it or reinstall it.

**Comment by dhaumya** [comment]
Yeah I have realised microg doesn't effect it, for me this is even affecting revanced. I have started to get the buffering again since 8hrs ago and am just using my browser to use YouTube.

**Comment by dhaumya** [comment]
Nothing changed the app is still buffering but the YouTube in browser is working.

**Comment by dhaumya** [comment]
My internet went out for 15mins and now it's working again and I was thinking that a alot of site ain't working at speed, is it possible this might be a connection issue? but the comments and related videos load. Even revanced was affected so ig this isn't a problem with piped interface. This is weird, maybe YouTube is doing A/B testing against addblockers? But every claim like YouTube slowing down and stuff against addblockets was proven false until now right?

**Comment by dhaumya** [comment]
Idk what has happened but in the last month I haven't been able to recreate the issue in any capacity so I am assuming it was a network problem.

Sorry for wasting your valuable time.

**Comment by vsl-iil** [comment]
Same issue on NewPipe 0.27.2. First observed with Tubular fork, it also happens on NewPipe. Few days ago it was still possible to load some of the videos, but now most of them fail to load:

## Exception
* User Action: play stream
* Request: Player error[type=ERROR_CODE_IO_NETWORK_CONNECTION_TIMEOUT] occurred while playing https://www.youtube.com/watch?v=RDvpAT1Gxqk
* Content Country: RU
* Content Language: ru-
* App Language: ru_RU
* Service: YouTube
* Version: 0.27.2
* OS: Linux OPPO/CPH1931RU/OP4B79L1:10/QKQ1.200209.002/1634810304:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

com.google.android.exoplayer2.ExoPlaybackException: Source error
 at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
 at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
 at android.os.Handler.dispatchMessage(Handler.java:103)
 at android.os.Looper.loop(Looper.java:241)
 at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketTimeoutException: SSL handshake timed out
 at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:389)
 at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)
 at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
 at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:796)
 at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:609)
 at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
 at com.google.android.exoplayer2.source.chunk.InitializationChunk.load(InitializationChunk.java:99)
 at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:919)
Caused by: java.net.SocketTimeoutException: SSL handshake timed out
 at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
 at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:387)
 at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:226)
 at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
 at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
 at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
 at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
 at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
 at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
 at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
 at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
 at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
 at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
 at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.makeConnection(YoutubeHttpDataSource.java:704)
 at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.makeConnection(YoutubeHttpDataSource.java:548)
 at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:383)
 ... 10 more

</details>
<hr>


I'm using a VPN (DPI bypass), but without it, the videos won't load altogether (it's not an app issue). I tried both with Wi-Fi and mobile data, but the latter usually gives off a different kind of error for the few months, so I presume it is worth a separate issue (I believe the mobile data one is related to https://github.com/TeamNewPipe/NewPipe/issues/11139). I say “usually”, because when I tried to get an error just now, video loaded fine with mobile data on. 
I will try to experiment with different Wi-Fi hotspots, but I only have so many routers. :)
Let me know if I should create a new issue, seeing as this one is a bit old.

**Comment by mrkrabs206** [comment]
But the sign in one is much more worse
