### ISSUE TITLE
App Crashing Adding the Short Video in Now Playing Playlist.

### ISSUE THREAD

**Issue by AF1011** [TeamNewPipe/NewPipe#11070]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.0

### Steps to reproduce the bug

1. Adding Non-Shorts video
2. Adding Short vidro into Now Playing lists

### Actual behavior

The app crashed, after adding short video into playlists.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ KR
* __Content Language:__ ko-
* __App Language:__ in_ID
* __Service:__ none
* __Version:__ 0.27.0
* __OS:__ Linux samsung/a53xnsxx/a53x:14/UP1A.231005.007/A536EXXU7DWK6:user/release-keys 14 - 34
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
	at android.widget.Toast.makeText(Toast.java:826)
	at org.schabi.newpipe.util.NavigationHelper.enqueueOnPlayer(NavigationHelper.java:192)
	at org.schabi.newpipe.util.NavigationHelper.enqueueOnPlayer(NavigationHelper.java:206)
	at org.schabi.newpipe.info_list.dialog.StreamDialogDefaultEntry.lambda$static$2(StreamDialogDefaultEntry.java:54)
	at org.schabi.newpipe.info_list.dialog.StreamDialogDefaultEntry.$r8$lambda$HrNW3ftQD3NQNetYZjrz1JDwzD4(StreamDialogDefaultEntry.java:0)
	at org.schabi.newpipe.info_list.dialog.StreamDialogDefaultEntry$$ExternalSyntheticLambda15.accept(R8$$SyntheticClass:0)
	at org.schabi.newpipe.util.SparseItemUtil.lambda$fetchItemInfoIfSparse$0(SparseItemUtil.java:60)
	at org.schabi.newpipe.util.SparseItemUtil.$r8$lambda$rd2kSpgtBScfiwrztd_5JrCbEyQ(SparseItemUtil.java:0)
	at org.schabi.newpipe.util.SparseItemUtil$$ExternalSyntheticLambda2.accept(R8$$SyntheticClass:0)
	at org.schabi.newpipe.util.SparseItemUtil.lambda$fetchStreamInfoAndSaveToDatabase$4(SparseItemUtil.java:121)
	at org.schabi.newpipe.util.SparseItemUtil.$r8$lambda$cfmnXoy0qdCzt8EeO-smvalxWsM(SparseItemUtil.java:0)
	at org.schabi.newpipe.util.SparseItemUtil$$ExternalSyntheticLambda0.accept(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 14 /One UI 6.0

### Affected device model

Samsung Galaxy A53 (SM-A5363/DS)

**Comment by AF1011** [comment]
This is actual links
https://www.youtube.com/watch?v=hsFs4K-KZU8 (Shorts)

https://www.youtube.com/watch?v=0fbEdyV1dMA (Non-shorts)

**Comment by AF1011** [comment]
![Screenshot_20240516_170213_NewPipe](https://github.com/TeamNewPipe/NewPipe/assets/54230948/85ab9e72-ffd0-4e85-b556-ff0219f92ee6)

Same here...

**Comment by AF1011** [comment]
> This is an image. I asked for a video.

Footage video or links?

**Comment by AF1011** [comment]
https://github.com/TeamNewPipe/NewPipe/assets/54230948/8d06ef9f-51f5-46b5-8d94-a170dbd188de

I'll wondering after crashing many times, it's seems normal...

**Comment by AF1011** [comment]
> So the bug is not happening anymore?

That happen once, if i'll cleared the cache that it's will not crashing again.
