### ISSUE TITLE
Crash when adding video to the queue after next video starts playing 

### ISSUE THREAD

**Issue by dk949** [TeamNewPipe/NewPipe#11091]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.0

### Steps to reproduce the bug

1. Start playing a video
2. Enqueue another video
3. Long press on another video to show the modal
4. Wait for the currently playing video to go to the next one in the queue whilst the modal is on screen
5. Press the enqueu button on the modal 

### Expected behavior

The video the modal was spawned from is enqueued or some message about why this can't be done. 

### Actual behavior

Crash (log attached) 

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.27.0
* __OS:__ Linux Android 14 - 34
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Fragment RelatedItemsFragment{82c241b} (edb74a84-566c-4db7-a17d-cde599994f16) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:972)
	at org.schabi.newpipe.info_list.dialog.StreamDialogDefaultEntry.lambda$static$3(StreamDialogDefaultEntry.java:53)
	at org.schabi.newpipe.info_list.dialog.StreamDialogDefaultEntry.$r8$lambda$vJPfXGxkVEGzC3RaucaklOZ4WRo(StreamDialogDefaultEntry.java:0)
	at org.schabi.newpipe.info_list.dialog.StreamDialogDefaultEntry$$ExternalSyntheticLambda5.onClick(R8$$SyntheticClass:0)
	at org.schabi.newpipe.info_list.dialog.InfoItemDialog.lambda$new$2(InfoItemDialog.java:76)
	at org.schabi.newpipe.info_list.dialog.InfoItemDialog.$r8$lambda$rolB38hFbFwRPfIy0nmFKZx8iWo(InfoItemDialog.java:0)
	at org.schabi.newpipe.info_list.dialog.InfoItemDialog$$ExternalSyntheticLambda2.onClick(R8$$SyntheticClass:0)
	at androidx.appcompat.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1068)
	at android.widget.AdapterView.performItemClick(AdapterView.java:376)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1362)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3658)
	at android.widget.AbsListView$3.run(AbsListView.java:4844)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 14

### Affected device model

Samsung galaxy s23+

**Comment by dk949** [comment]
From the related items tab, yes.

(the middle one where left is comments and right is description)

**Comment by dk949** [comment]
When selecting a video from search results or the "what's new" tab - no crash.

**Comment by dk949** [comment]
Done

**Comment by rmtilde** [comment]
Hi, can I work on this issue?
