### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by benazarenko** [TeamNewPipe/NewPipe#11134]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.0

### Steps to reproduce the bug

1. Open search
2. Type anything inside

### Expected behavior

It shows search results

### Actual behavior

Shows nothing and gives a 'Something went wrong'

## Exception
* User Action: get suggestions
* Request: taz wanted grand canyon
* Content Country: US
* Content Language: ru-RU
* App Language: ru_RU
* Service: YouTube
* Version: 0.27.0
* OS: Linux samsung/m12nsser/m12:13/TP1A.220624.014/M127FXXU6DWI3:user/release-keys 13 - 33
<details><summary><b>Crash log </b></summary><p>

org.schabi.newpipe.extractor.exceptions.ReCaptchaException: reCaptcha Challenge requested
 at org.schabi.newpipe.DownloaderImpl.execute(DownloaderImpl.java:168)
 at org.schabi.newpipe.extractor.downloader.Downloader.get(Downloader.java:77)
 at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSuggestionExtractor.suggestionList(YoutubeSuggestionExtractor.java:65)
 at org.schabi.newpipe.util.ExtractorHelper.lambda$suggestionsFor$2(ExtractorHelper.java:109)
 at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$kgV3vMftlbQH0zdv8hszrHLyMLU(ExtractorHelper.java:0)
 at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda15.call(R8$$SyntheticClass:0)
 at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
 at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
 at io.reactivex.rxjava3.internal.operators.single.SingleToObservable.subscribeActual(SingleToObservable.java:36)
 at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13262)
 at io.reactivex.rxjava3.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
 at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13262)
 at io.reactivex.rxjava3.internal.operators.observable.ObservableZip$ZipCoordinator.subscribe(ObservableZip.java:110)
 at io.reactivex.rxjava3.internal.operators.observable.ObservableZip.subscribeActual(ObservableZip.java:72)
 at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13262)
 at io.reactivex.rxjava3.internal.operators.observable.ObservableMaterialize.subscribeActual(ObservableMaterialize.java:28)
 at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13262)
 at io.reactivex.rxjava3.internal.operators.observable.ObservableSwitchMap$SwitchMapObserver.onNext(ObservableSwitchMap.java:128)
 at io.reactivex.rxjava3.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver$DelayErrorInnerObserver.onNext(ObservableConcatMap.java:500)
 at io.reactivex.rxjava3.observers.SerializedObserver.onNext(SerializedObserver.java:114)
 at io.reactivex.rxjava3.internal.operators.observable.ObservableDebounceTimed$DebounceTimedObserver.emit(ObservableDebounceTimed.java:156)
 at io.reactivex.rxjava3.internal.operators.observable.ObservableDebounceTimed$DebounceEmitter.run(ObservableDebounceTimed.java:181)
 at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
 at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
 at java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
 at java.lang.Thread.run(Thread.java:1012)

</details>
<hr>

### Affected Android/Custom ROM version

Android 13

### Affected device model

Samsung M12

### Additional information

It happens all the time, not only in search. When I open search results it gives the same error. Every time I open it. As I see it's some problem with Google Captcha.

**Comment by benazarenko** [comment]
For some reason I can't. The option is greyed out.

**Comment by benazarenko** [comment]
Cleared all app data, but nothing changed.
Reinstalled it completely, but nothing changed.

**Comment by benazarenko** [comment]
Tried it on my home wifi and it works fine. On mobile network it doesn't. Doesn't work in my office wifi too.

**Comment by benazarenko** [comment]
Yes, looks like it doesn't affect other functionality. Only search suggestions and 'Something went wrong' constantly popping from under the screen when I open app with search results.

**Comment by AudricV** [comment]
I don't think so. Anyway, this won't change anything as the logged-out access to search suggestions for the IP used by the user has been banned. Piped is for instance affected by this behavior.

The extractor `Downloader`'s app implementation interprets incorrectly any 429 HTTP response code as a captcha challenge request.

**Comment by vehosah** [comment]
> I'm guessing it's certain IP addresses that are problematic. Are you able to change it and see if others work?

Yes tried a VPN, still no results

**Comment by vehosah** [comment]
> Could you try a different network? Like mobile data instead of wifi.

No I can't try that
