### ISSUE TITLE
Particular video plays until 0:53 mark, then stops

### ISSUE THREAD

**Issue by Hippieslay** [TeamNewPipe/NewPipe#11143]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.0

### Steps to reproduce the bug

Watched this particular YouTube video: https://www.youtube.com/watch?v=kLm-4xjoFh4

Put in pop-up mode
Waited until exactly the :53 second mark
The video does not load and will not play even if you close the app
The only way to get the video to restart is to go to "Mark as watched" then reload the video, but it still only plays to the 0:53 mark.

### Expected behavior

Video should play as normal without interruption

### Actual behavior

The video stops and you cannot proceed

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.27.0
* __OS:__ Linux OnePlus/OnePlus9TMO/OnePlus9TMO:14/UKQ1.230924.001/R.17235a9-4fb2a-4fb2b:user/release-keys 14 - 34
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.exoplayer2.ext.mediasession.MediaSessionConnector.setCustomActionProviders(com.google.android.exoplayer2.ext.mediasession.MediaSessionConnector$CustomActionProvider[])' on a null object reference
	at org.schabi.newpipe.player.mediasession.MediaSessionPlayerUi.updateMediaSessionActions(MediaSessionPlayerUi.java:215)
	at org.schabi.newpipe.player.mediasession.MediaSessionPlayerUi.onMetadataChanged(MediaSessionPlayerUi.java:282)
	at org.schabi.newpipe.player.Player.lambda$updateMetadataWith$22(Player.java:1801)
	at org.schabi.newpipe.player.Player.$r8$lambda$6LL1ynLVHUrHxxol0bvWL1Rn_TU(Player.java:0)
	at org.schabi.newpipe.player.Player$$ExternalSyntheticLambda47.accept(R8$$SyntheticClass:0)
	at j$.util.AbstractList$RandomAccessSpliterator.forEachRemaining(Unknown Source:19)
	at j$.util.stream.ReferencePipeline$Head.forEachOrdered(Unknown Source:10)
	at org.schabi.newpipe.player.ui.PlayerUiList.call(PlayerUiList.java:88)
	at org.schabi.newpipe.player.Player.updateMetadataWith(Player.java:1801)
	at org.schabi.newpipe.player.Player.lambda$onEvents$13(Player.java:1293)
	at org.schabi.newpipe.player.Player.$r8$lambda$5dalatdJw7zsnq99HOZvtSHTxZo(Player.java:0)
	at org.schabi.newpipe.player.Player$$ExternalSyntheticLambda37.accept(R8$$SyntheticClass:0)
	at j$.util.Optional.ifPresent(Unknown Source:4)
	at org.schabi.newpipe.player.Player.lambda$onEvents$14(Player.java:1287)
	at org.schabi.newpipe.player.Player.$r8$lambda$67JZJPUrqqIwv2qPVBiXIeF-1Rs(Player.java:0)
	at org.schabi.newpipe.player.Player$$ExternalSyntheticLambda9.accept(R8$$SyntheticClass:0)
	at j$.util.Optional.ifPresent(Unknown Source:4)
	at org.schabi.newpipe.player.Player.onEvents(Player.java:1265)
	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$new$0(ExoPlayerImpl.java:266)
	at com.google.android.exoplayer2.ExoPlayerImpl.$r8$lambda$FaN7Odt_OJn5xWFlmhnR2OmiNMg(ExoPlayerImpl.java:0)
	at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda1.invoke(R8$$SyntheticClass:0)
	at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.release(ListenerSet.java:320)
	at com.google.android.exoplayer2.util.ListenerSet.remove(ListenerSet.java:183)
	at com.google.android.exoplayer2.ExoPlayerImpl.removeListener(ExoPlayerImpl.java:1641)
	at org.schabi.newpipe.player.Player.destroyPlayer(Player.java:573)
	at org.schabi.newpipe.player.Player.destroy(Player.java:600)
	at org.schabi.newpipe.player.PlayerService.cleanup(PlayerService.java:150)
	at org.schabi.newpipe.player.PlayerService.stopService(PlayerService.java:156)
	at org.schabi.newpipe.player.ui.PopupPlayerUi$1.end(PopupPlayerUi.java:385)
	at org.schabi.newpipe.player.ui.PopupPlayerUi$1.onAnimationEnd(PopupPlayerUi.java:379)
	at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1119)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:719)
	at android.animation.Animator$AnimatorCaller$$ExternalSyntheticLambda1.call(Unknown Source:4)
	at android.animation.Animator.callOnList(Animator.java:677)
	at android.animation.Animator.notifyListeners(Animator.java:616)
	at android.animation.Animator.notifyEndListeners(Animator.java:641)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1306)
	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1585)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:328)
	at android.animation.AnimationHandler.-$$Nest$mdoAnimationFrame(Unknown Source:0)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:86)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1550)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1561)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1117)
	at android.view.Choreographer.doFrame(Choreographer.java:992)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1535)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8825)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 14/Oxygen OS 12.0

### Affected device model

OnePlus 10

### Additional information

I tried watching other videos and there seems to be no problem as far as I can tell.

Edit: I watched some other videos and came back to this one and it seems to be working now, but I'll still submit it and you all may delete it if it's not a legitimate problem. Thank you for your work I appreciate you all.

**Comment by Hippieslay** [comment]
It appears there is a similar issue posted 4 days ago, I apologize if I have inappropriately posted this. Please forgive me.
