### ISSUE TITLE
NewPipeExtractor:v0.24.0 No static method toUnmodifiableList()Ljava/util/stream/Collector

### ISSUE THREAD

**Issue by wangchenggggdn** [TeamNewPipe/NewPipe#11270]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

v0.24.0

### Steps to reproduce the bug

![WechatIMG638](https://github.com/user-attachments/assets/23bb6165-2496-49c7-b001-1695288c72d8)

compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
 }

gradle-8.2-bin

api 'com.github.teamnewpipe:NewPipeExtractor:v0.24.0'
api 'io.reactivex.rxjava3:rxjava:3.1.8'
api 'io.reactivex.rxjava3:rxandroid:3.0.2'

### Logs

Caused by: java.lang.NoSuchMethodError: No static method toUnmodifiableList()Ljava/util/stream/Collector; in class Ljava/util/stream/Collectors; or its super classes (declaration of 'java.util.stream.Collectors' appears in /apex/com.android.art/javalib/core-oj.jar)
at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getImagesFromThumbnailsArray(YoutubeParsingHelper.java:1069)
at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getThumbnailsFromInfoItem(YoutubeParsingHelper.java:1037)

**Comment by PeOS-China** [comment]
I also encountered the same problem using version 0.27.1. How can I fix it?
`No static method toUnmodifiableList()Ljava/util/stream/Collector; in class Ljava/util/stream/Collectors; or its super classes (declaration of 'java.util.stream.Collectors' appears in /apex/com.android.art/javalib/core-oj.jar)`

**Comment by wangchenggggdn** [comment]
> I also encountered the same problem using version 0.27.1. How can I fix it? `No static method toUnmodifiableList()Ljava/util/stream/Collector; in class Ljava/util/stream/Collectors; or its super classes (declaration of 'java.util.stream.Collectors' appears in /apex/com.android.art/javalib/core-oj.jar)` Code:
> 
> ```
>         try {
>             Log.d(tag, "flow start ")
>             val it = StreamInfo.getInfo(YoutubeService(0), url)
>             Log.d(tag, "flow end ")
>             val streamItem = when (mode) {
>                 IYTDownload.RequestMode.VIDEO -> getBestVideoItem(it.videoStreams)
>                 IYTDownload.RequestMode.AUDIO -> it.audioStreams.getOrNull(0)
>             }
>             Log.d(tag, "onEach 2")
>             if (streamItem != null) {
>                 pair = Pair(streamItem.content, it.duration)
>             } else {
>                 val errMsg = "NewPipe error(onEach): can not get stream info at $url"
>                 Log.d(tag, errMsg)
>                 onError?.invoke(Throwable(errMsg), false)
>             }
>         } catch (throwable: Throwable) {
>             val err = "NewPipe error(throwable): ${throwable.message} at $url"
>             Log.d(tag, err)
>             val isRemoveErr = postNewPipeError(lessonID, err)
>             onError?.invoke(throwable, isRemoveErr)
>             Log.d("NewPipe", "requestUrlStreamData catch")
>         }
> ```
coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.0.4")

**Comment by abutun** [comment]
Same problem here with version 0.24.2

`Caused by: java.lang.NoSuchMethodError: No static method encode(Ljava/lang/String;Ljava/nio/charset/Charset;)Ljava/lang/String; in class Ljava/net/URLEncoder; or its super classes (declaration of 'java.net.URLEncoder' appears in /system/framework/core-oj.jar)
at org.schabi.newpipe.extractor.utils.Utils.encodeUrlUtf8(Utils.java:37)
at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSuggestionExtractor.suggestionList(YoutubeSuggestionExtractor.java:56)
at code.name.monkey.retromusic.stream.Extractor.suggestions$lambda$2(Extractor.kt:43)
at code.name.monkey.retromusic.stream.Extractor.$r8$lambda$snA4ZM6MPxqwWF8AjNWwNzLwiJA(Unknown Source:0)
at code.name.monkey.retromusic.stream.Extractor$$ExternalSyntheticLambda3.call(D8$$SyntheticClass:0)
at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
![Image 003](https://github.com/user-attachments/assets/69b67e8e-bcc6-45c9-a8df-dbfe1f94952d)
`
