### ISSUE TITLE
Searching for "skitanz deutschland" results in an Exception

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#1133]
Reproduce:
Use `Youtube` service with `GB` as language. Search for __"skitanz deutschland"__, then scroll to the second page.

This will result in an ExtractionException: `Empty result despite no error`

```
org.schabi.newpipe.extractor.exceptions.ExtractionException: Empty result despite no error
	at org.schabi.newpipe.extractor.search.SearchResult.getSearchResult(SearchResult.java:56)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$searchFor$0$ExtractorHelper(ExtractorHelper.java:67)
	at org.schabi.newpipe.util.ExtractorHelper$$Lambda$0.call(Unknown Source)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:45)
	at io.reactivex.Single.subscribe(Single.java:2801)
	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
	at io.reactivex.Single.subscribe(Single.java:2801)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
```

Also every currently available version of NP has this problem.

PS: Funfact of the day: [Ski dance](https://www.youtube.com/watch?v=fvk4PpFORD4) was once an [olympic discipline](https://en.wikipedia.org/wiki/Ski_ballet), but it got abandoned in the 2000 because it looked like a giant moose trying to mate.

**Comment by theScrabi** [comment]
Thx

**Comment by Stypox** [comment]
This seems to be fixed. When there are no more results available nothing happens, as expected

**Comment by Stypox** [comment]
Now that search term generates #2371
