### ISSUE TITLE
Type=ERROR_CODE_IO_BAD_HTTPS_STATUS

### ISSUE THREAD

**Issue by Eggy248** [TeamNewPipe/NewPipe#11345]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

2.7.1

### Steps to reproduce the bug

Open app, goto play or download a bookmarked video

### Expected behavior

Video opens and plays after clicking play triangle

### Actual behavior

App throws crash report

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_BAD_HTTP_STATUS] occurred while playing https://www.youtube.com/watch?v=hiA1HpG00AM
* __Content Country:__ NL
* __Content Language:__ en-NL
* __App Language:__ en_NL
* __Service:__ YouTube
* __Version:__ 0.27.1
* __OS:__ Linux OnePlus/OnePlus8Pro/OnePlus8Pro:13/RKQ1.211119.001/Q.202209070412:user/release-keys 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:422)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:796)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:609)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.chunk.InitializationChunk.load(InitializationChunk.java:99)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android OxygenOS 13.1 security update 5 June 2024

### Affected device model

Oneplus 8 pro 

### Additional information

This same behavior occurred in v0.27.0 of the app. Everything worked again after upgrading to v0.27.1 until today.

**Comment by oong819** [comment]
It crash right after tap play button or crash after a while into the video?

**Comment by NottLexa** [comment]
Occasionally happens both ways... Just had a problem, when this error was happening every time i tried to play ANY video (in normal way and audio only). Restarting app fixed the problem.

But for the last several weeks I have stumbled upon another problem, when such error has shown up on some random videos at the random moment of time. Not every video has such error, but only 25-30% of videos i tried to watch. At some certain (but occasional) moment of the video the video playback crashes and does not restart until i somehow replay video from the start. And when I reach this moment again, video playback crashes once again, with the same error... If the video is really long, this error can be avoided by skipping 10 or 15 minutes after the moment of crashing.

**Comment by NottLexa** [comment]
> It crash right after tap play button or crash after a while into the video?

Occasionally happens both ways... Just had a problem, when this error was happening every time i tried to play ANY video (in normal way and audio only). Restarting app fixed the problem.

But for the last several weeks I have stumbled upon another problem, when such error has shown up on some random videos at the random moment of time. Not every video has such error, but only 25-30% of videos i tried to watch. At some certain (but occasional) moment of the video the video playback crashes and does not restart until i somehow replay video from the start. And when I reach this moment again, video playback crashes once again, with the same error... If the video is really long, this error can be avoided by skipping 10 or 15 minutes after the moment of crashing.

**Comment by IgorArnaut** [comment]
It happens for some videos too, even though I have v0.27.1 installed.

**Comment by Ujsksowmwko** [comment]
Yes. Can't download or play anything

**Comment by 1xFF** [comment]
I think there needs to be a new pin, or perhaps renaming #11255. I was confused why 0.27.1 instant 403's were being marked duplicate with no explanation.
