### ISSUE TITLE
[YouTube] Crashes related to channels serialization (playing a video after some time, going to another app or to settings, ...)

### ISSUE THREAD

**Issue by rancidfrog** [TeamNewPipe/NewPipe#11356]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.2 

### Steps to reproduce the bug

Play any video, after a while newpipe crashes

### Expected behavior

Video playback

### Actual behavior

Newpipe crashes,
Before newpipe used to throw errors but playbagk continued, now on error newpipe crashes

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.27.2
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
android.os.BadParcelableException: Parcelable encountered IOException writing serializable object (name = org.schabi.newpipe.extractor.channel.ChannelInfo)
	at android.os.Parcel.writeSerializable(Parcel.java:2751)
	at android.os.Parcel.writeValue(Parcel.java:2517)
	at android.os.Parcel.writeValue(Parcel.java:2316)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1265)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1334)
	at android.os.Parcel.writeValue(Parcel.java:2433)
	at android.os.Parcel.writeValue(Parcel.java:2323)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1265)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1334)
	at android.os.Parcel.writeValue(Parcel.java:2433)
	at android.os.Parcel.writeValue(Parcel.java:2323)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1265)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1334)
	at android.os.Parcel.writeValue(Parcel.java:2433)
	at android.os.Parcel.writeValue(Parcel.java:2323)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1265)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1334)
	at android.os.Parcel.writeValue(Parcel.java:2433)
	at android.os.Parcel.writeValue(Parcel.java:2323)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1265)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1334)
	at android.os.Parcel.writeValue(Parcel.java:2433)
	at android.os.Parcel.writeValue(Parcel.java:2323)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1265)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1802)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1334)
	at android.os.Parcel.writeValue(Parcel.java:2433)
	at android.os.Parcel.writeValue(Parcel.java:2323)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1874)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1911)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.collectBundleStates(PendingTransactionActions.java:142)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:158)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.io.NotSerializableException: org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at java.util.ArrayList.writeObject(ArrayList.java:762)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1036)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1552)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at android.os.Parcel.writeSerializable(Parcel.java:2746)
	... 50 more

```
</details>
<hr>

### Affected Android/Custom ROM version

 Android 13 - Lineageos 20

### Affected device model

Xiaomi Mi MIX 2S

**Comment by dogtopus** [comment]
I'm seeing the same exception but only when I was trying to shuffle large playlists (e.g. https://www.youtube.com/watch?v=NC2blnl0WTE&list=PL8mG-RkN2uTx9GY3silWiMf2W2EJ9sTgx). I specifically did the following:

- Fully load the play list manually by scrolling down all the way to the bottom
- Hold the "play in background button" to enqueue everything
- In the background player UI, tap the shuffle button
- The app crashes immediately and consistently

**Comment by vshc** [comment]
I experience the same issue, with the same exception.
In my case it happened every time when NewPipe application was put into background, either by turning screen off or switching app to another.

**Comment by KanNinChun** [comment]
In my case it will crash the app when i attempt to open the playlist tab after i click play all video, it will just crash the app if you try to get to the playlist tab

**Comment by levik-opsilient** [comment]
Having the same issues on a pixel 3 Android 11

**Comment by jensli** [comment]
I have the same problem. Started after upgrading from NewPipe 0.27.1 to 0.27.2. Android 8.0.0 - 26.

**Comment by Green0wl** [comment]
same problem. as @jensli mentioned, UI crash is observed when switching from version `0.27.1` to `0.27.2`. probably, it can be somehow related to the fact that youtube updates something at itself. not sure if the bug is between versions `0.27.1` and `0.27.2`, because in version `0.27.1` videos did not start at all, although before the changes in youtube, even in version `0.27.1` everything worked correctly.

I also observe what @vshc said. this crash mostly happens when I turn off the screen or switch from one application to another. at the same time, sometimes even with long screen off times, everything continues to work correctly. i think it might be due to memory freeing in android when another application is launched. then, with long screen off times, even if everything works, it could be explained by the fact that android kept the application data in memory all the time and didn't unload it until I turned the screen back on.

**Comment by jensli** [comment]
The following are my observations and speculations about the problem. Maybe they can contribute to find the cause and fix it.

### Basic observations

The Android framework tries to serialize a `ChannelInfo` object, which it turn references a `YoutubeChannelExtractor`. `YoutubeChannelExtractor` is not serializable so the operations fails.

It seems reasonable that `YoutubeChannelExtractor` is not serializable. It seems to be a service kind of class, not a data-holder kind of class. Because of this, it is probably by mistake that `YoutubeChannelExtractor` is serialized.

The bug was probably introduced in the changes between version 2.4.1 and 2.4.2:

https://github.com/TeamNewPipe/NewPipeExtractor/compare/v0.24.1...v0.24.2

### What could be the mistake?

The following is one idea:

`ChannelInfo` contains `ListLinkHandler` objects in the field `tabs`.

The `tabs` field gets populated with a `ReadyChannelTabListLinkHandler` in `YoutubeChannelExtractor#getTabsForNonAgeRestrictedChannels` with this code:

https://github.com/TeamNewPipe/NewPipeExtractor/blob/176da72cb4c3ec4679211339b0e59f6b01bf2f52/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeChannelExtractor.java#L429

```
tabs.add(0, new ReadyChannelTabListLinkHandler(
        tabUrl,
        channelId,
        ChannelTabs.VIDEOS,
        (service, linkHandler) -> new VideosTabExtractor(
                service, linkHandler, tabRenderer, channelHeader,
                name, id, url)));
```

`channelHeader` is a field of `YoutubeChannelExtractor`. Therefor them lambda object will contain a reference to the enclosing `YoutubeChannelExtractor`.

Bingo! That is a possible chain of references from `ChannelInfo` (the object being serialized) to `YoutubeChannelExtractor` (the object that will trigger the error if it is serialized.

The whole chain looks like this:


`ChannelInfo` where the `tabs` field references...

...the object `ReadyChannelTabListLinkHandler`  where the `extractorBuilder` field references...

...a lambda implementing `ChannelTabExtractorBuilder` which has a filed for the capture `YoutubeChannelExtractor`, to be able to access `channelHeader`.


When the framework serializes `ChannelInfo` it follows thoses references and tries to serialize `YoutubeChannelExtractor` which triggers `NotSerializableException`.


### Potintial fix

Create a local variable that contains `channelHeader` to avoid having the whole `YoutubeChannelExtractor`

```
// Local variable to avoid that the lambda captures YoutubeChannelExtractor
Optional<ChannelHeader> localChannelHeader = channelHeader; 
tabs.add(0, new ReadyChannelTabListLinkHandler(
        tabUrl,
        channelId,
        ChannelTabs.VIDEOS,
        (service, linkHandler) -> new VideosTabExtractor(
                service, linkHandler, tabRenderer, localChannelHeader,
                name, id, url)));
```


### Disclaimer

I'm not at all sure about the above reasoning. I have not tried it. It is based only on reading the code at GitHub. But it just might be the cause!

**Comment by levik-opsilient** [comment]
it's interesting, but when using SoundCloud it doesn't crash, only youtube

**Comment by WagnerGMD** [comment]
Finally I had found something with the help of Scoop.
Because it's match with the first line ("User Action: ui error") but if you want a copy from the crash log you will need to explain me how to proceed from my PC ?
As reminder, I confirm my knowledge about ADB is just basic.

**Comment by levik-opsilient** [comment]
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.27.2
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = org.schabi.newpipe.extractor.channel.ChannelInfo)
	at android.os.Parcel.writeSerializable(Parcel.java:2113)
	at android.os.Parcel.writeValue(Parcel.java:1883)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:975)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1303)
	at android.os.Parcel.writeBundle(Parcel.java:1044)
	at android.os.Parcel.writeValue(Parcel.java:1801)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:975)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1303)
	at android.os.Parcel.writeBundle(Parcel.java:1044)
	at android.os.Parcel.writeValue(Parcel.java:1801)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:975)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1303)
	at android.os.Parcel.writeBundle(Parcel.java:1044)
	at android.os.Parcel.writeValue(Parcel.java:1801)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:975)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1303)
	at android.os.Parcel.writeBundle(Parcel.java:1044)
	at android.os.Parcel.writeValue(Parcel.java:1801)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:975)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1303)
	at android.os.Parcel.writeBundle(Parcel.java:1044)
	at android.os.Parcel.writeValue(Parcel.java:1801)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:975)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1303)
	at android.os.Parcel.writeBundle(Parcel.java:1044)
	at android.os.Parcel.writeValue(Parcel.java:1801)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:975)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1303)
	at android.app.IActivityTaskManager$Stub$Proxy.activityStopped(IActivityTaskManager.java:4389)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:145)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.io.NotSerializableException: org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at java.util.ArrayList.writeObject(ArrayList.java:762)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1036)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1552)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at android.os.Parcel.writeSerializable(Parcel.java:2108)
	... 43 more

```
</details>
<hr>

**Comment by WagnerGMD** [comment]
@opusforlife2 Ok I will wait apparently it could be different (unless it's another one ? I can't tell).

For the record : I had disable all the animation (inside the settings of Android 12 as developer). Perhaps it's the delay ? Because my history is bigger and apparenlty I haven't met this bug since these changes (3 at total).

**Comment by berrydzhobs** [comment]
For now it. Stopped playing videos

**Comment by T-rex2017** [comment]
At  least for me it only occurs when i try to play video from a playlist in the background and switch to another app or turn off screen , when i play it back from history or open the individual video and push to bg , there seems to be a non problem

**Comment by levik-opsilient** [comment]
Same thing, It won't crash when playing the link directly, only when
playing from a subscription.

**Comment by kirisakow** [comment]
@ShareASmile told me to reference my issue #11510 here

> ### Steps to reproduce the bug
> 
> 1. Use NewPipe to open any YouTube channel home page.
> 2. Go to the "About" tab.
> 3. Use the top right "&lt;" (share) pictogram and choose where to share.

### Consequences

This issue logs — vs — my issue logs:

![Screenshot from 2024-09-09 17-48-09](https://github.com/user-attachments/assets/18c6d2a3-01d7-4b64-b5a3-15190c123f72)

**Comment by noone74** [comment]
## Exception
* __User Action:__ play stream
* __Request:__ Loading failed for [La Séance du Drive in : "Le Droit de tuer " (1980) J.Glickenhaus / HD 1080p VF]: https://www.youtube.com/watch?v=ViqHkWdAaXM
* __Content Country:__ FR
* __Content Language:__ fr-
* __App Language:__ fr
* __Service:__ YouTube
* __Version:__ 0.27.2
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.player.mediasource.FailedMediaSource$StreamInfoLoadException: org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
	at org.schabi.newpipe.player.playback.MediaSourceManager.lambda$getLoadedMediaSource$7(MediaSourceManager.java:448)
	at org.schabi.newpipe.player.playback.MediaSourceManager.$r8$lambda$7wkrzYpwfZdms79okpk8_MCaW4U(MediaSourceManager.java:0)
	at org.schabi.newpipe.player.playback.MediaSourceManager$$ExternalSyntheticLambda5.apply(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.operators.single.SingleOnErrorReturn$OnErrorReturn.onError(SingleOnErrorReturn.java:55)
	at io.reactivex.rxjava3.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:70)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnError$DoOnError.onError(SingleDoOnError.java:63)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onError(SingleSubscribeOn.java:73)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle$ToSingleMaybeSubscriber.onError(MaybeToSingle.java:89)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onError(FlowableElementAtMaybe.java:94)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.onError(MaybeConcatArray.java:100)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle$FromSingleObserver.onError(MaybeFromSingle.java:82)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess$DoOnSuccess.onError(SingleDoOnSuccess.java:65)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:47)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5377)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:16144)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5377)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:171)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:81)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:118)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(ExtractorHelper.java:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda3.call(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	... 23 more

```
</details>
<hr>

**Comment by ethanc8** [comment]
I have not experienced this issue on the following channels, despite playing them in the background very often:
* [AtinPiano](https://youtube.com/channel/UCkPRBxO9SbNE-2h0XXKz-jg)
* [Patrik Pietschmann](https://youtube.com/channel/UCs7O9sOUQiBGBxaaAguIwig)
* [PianoDeuss](https://youtube.com/channel/UCgMvjHTX7jn4iIKNHjIUJiw)
I have encountered crashes while playing from playlists on these channels, but not when playing directly from the videos list:
* [Hsinchu City Youth Chinese Orchestra](https://youtube.com/channel/UCff1RV2vWxuzRyp7KPopVBA)
I have encountered crashes while playing directly from the videos list on these channels:
* [HeartString](https://youtube.com/channel/UCJIdkN1NrWBUy-0tVyynLPQ)

These crashes only occur upon backgrounding or putting the phone to sleep.

**Comment by yudlab** [comment]
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.27.2
* __OS:__ Linux samsung/dm3qxeea/dm3q:14/UP1A.231005.007/S918BXXU5CXE3:user/release-keys 14 - 34
<details><summary><b>Crash log </b></summary><p>

```
android.os.BadParcelableException: Parcelable encountered IOException writing serializable object (name = org.schabi.newpipe.extractor.channel.ChannelInfo)
	at android.os.Parcel.writeSerializable(Parcel.java:2809)
	at android.os.Parcel.writeValue(Parcel.java:2575)
	at android.os.Parcel.writeValue(Parcel.java:2374)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1310)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1379)
	at android.os.Parcel.writeValue(Parcel.java:2491)
	at android.os.Parcel.writeValue(Parcel.java:2381)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1310)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1379)
	at android.os.Parcel.writeValue(Parcel.java:2491)
	at android.os.Parcel.writeValue(Parcel.java:2381)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1310)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1379)
	at android.os.Parcel.writeValue(Parcel.java:2491)
	at android.os.Parcel.writeValue(Parcel.java:2381)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1310)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1379)
	at android.os.Parcel.writeValue(Parcel.java:2491)
	at android.os.Parcel.writeValue(Parcel.java:2381)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1310)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1379)
	at android.os.Parcel.writeValue(Parcel.java:2491)
	at android.os.Parcel.writeValue(Parcel.java:2381)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1310)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1843)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1379)
	at android.os.Parcel.writeValue(Parcel.java:2491)
	at android.os.Parcel.writeValue(Parcel.java:2381)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1917)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1954)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.collectBundleStates(PendingTransactionActions.java:123)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:139)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: java.io.NotSerializableException: org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at java.util.ArrayList.writeObject(ArrayList.java:955)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1079)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1568)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at android.os.Parcel.writeSerializable(Parcel.java:2804)
	... 50 more

```
</details>
<hr>

**Comment by ethanc8** [comment]
Will the fix be included in a hotfix release, or will we need to wait for a full release in order to get the fix?

**Comment by DevanWolf** [comment]
Bug is still present by #11692 in the latest nightly
