### ISSUE TITLE
Unrecoverable player error

### ISSUE THREAD

**Issue by Topper0o** [TeamNewPipe/NewPipe#11367]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.2

### Steps to reproduce the bug

1. Turn on new tube
2. Search for videos
3. Press on video
4. And on some this error happen.

### Expected behavior

Make video launch normally.

### Actual behavior

Error ecures 

### Screenshots/Screen recordings

I uploaded a log.

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_DECODER_INIT_FAILED] occurred while playing https://www.youtube.com/watch?v=EOIk0wEzwzs
* __Content Country:__ US
* __Content Language:__ en-
* __App Language:__ en
* __Service:__ YouTube
* __Version:__ 0.27.2
* __OS:__ Linux samsung/gtoeea/gto:11/RP1A.200720.012/T295XXU4CVG3:user/release-keys 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(299, null, null, video/avc, avc1.64002A, 3436641, null, [1080, 1920, 60.0], [-1, -1]), format_supported=YES
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:578)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:246)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(299, null, null, video/avc, avc1.64002A, 3436641, null, [1080, 1920, 60.0], [-1, -1])
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1021)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:537)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1453)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:917)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:954)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:769)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1007)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:502)
	... 3 more
Caused by: android.media.MediaCodec$CodecException: Error 0xfffffff4
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:2127)
	at android.media.MediaCodec.configure(MediaCodec.java:2043)
	at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter$Factory.createAdapter(SynchronousMediaCodecAdapter.java:51)
	at com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:113)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1099)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1010)
	... 10 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 11

### Affected device model

Samsung galaxy tab a

### Additional information

Happens often.

**Comment by lmsalustri** [comment]
Not an exact duplicate, but see #11329

**Comment by Topper0o** [comment]
OK I will try.

**Comment by Topper0o** [comment]
OK I tried and now the audio doesn't  match  the video and the video is really slow :(

**Comment by Topper0o** [comment]
Didn't, I noticed  it happens then I set video quality on the best possible or 1080p. 780p works fine but it will be better to have 1080p.

**Comment by Topper0o** [comment]
Yes it works

**Comment by Topper0o** [comment]
I can't select  the file in brouken player.

**Comment by Topper0o** [comment]
I can't select  the file :(

**Comment by Topper0o** [comment]
No it doesn't work it says a long error

**Comment by Topper0o** [comment]
It doesn't let me play it
