### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by cannonball95** [TeamNewPipe/NewPipe#11378]
### Checklist

- [ ] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.1

### Steps to reproduce the bug

1. Go to any video from YouTube
2. Attempt to play it

### Expected behavior

The video plays

### Actual behavior

Video doesn't play. First time it opens the media player, attempts to load, fails, pop-up message directs to check push notification while the video only shows the thumbnail with the "Play" icon. Pressing the play icon again yields the same result.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/4599a3c5-2f41-45f9-ac9b-16eb0a080ae8

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_BAD_HTTP_STATUS] occurred while playing https://www.youtube.com/watch?v=j-LP6Li4vec
* __Content Country:__ IN
* __Content Language:__ es-ES
* __App Language:__ es_ES
* __Service:__ YouTube
* __Version:__ 0.27.1
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:422)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:796)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:609)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.chunk.InitializationChunk.load(InitializationChunk.java:99)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 13

### Affected device model

Realme GT Neo2 5G

### Additional information

This same error happened in the previous version of New Pipe, apparently because YouTube placed obstacles for third party tools. This version fixed it for me, but only for some days until the issue returned. In case it's relevant, GrayJay still works, and New Pipe can still reproduce music from Bandcamp.
Thanks for your efforts.

**Comment by cannonball95** [comment]
A mistake on my side: I wasn't using the latest version, I had some issue to update regarding packets. Fixed by uninstalling and reinstalling. I'll close the issue now
