### ISSUE TITLE
Only one YouTube channel crashes NewPipe. Why ?

### ISSUE THREAD

**Issue by Machotyrant** [TeamNewPipe/NewPipe#11372]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.2

### Steps to reproduce the bug

https://www.youtube.com/channel/UC7edjYPNhTm5LYJMT7UMt0Q

I surf to this channel. I start watching. It barely lasts a minute before it crashes every single time but it doesn't crash for other channels 

### Expected behavior

I expect it to work 

### Actual behavior

Error screen copied and pasted below in logs

### Screenshots/Screen recordings

It crashes directly into the error page 

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.27.2
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = org.schabi.newpipe.extractor.channel.ChannelInfo)
	at android.os.Parcel.writeSerializable(Parcel.java:2166)
	at android.os.Parcel.writeValue(Parcel.java:1932)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1024)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeBundle(Parcel.java:1093)
	at android.os.Parcel.writeValue(Parcel.java:1850)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1024)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeBundle(Parcel.java:1093)
	at android.os.Parcel.writeValue(Parcel.java:1850)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1024)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeBundle(Parcel.java:1093)
	at android.os.Parcel.writeValue(Parcel.java:1850)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1024)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeBundle(Parcel.java:1093)
	at android.os.Parcel.writeValue(Parcel.java:1850)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1024)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeBundle(Parcel.java:1093)
	at android.os.Parcel.writeValue(Parcel.java:1850)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1024)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeBundle(Parcel.java:1093)
	at android.os.Parcel.writeValue(Parcel.java:1850)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1690)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1727)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:150)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8319)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
Caused by: java.io.NotSerializableException: org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at java.util.ArrayList.writeObject(ArrayList.java:873)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1079)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1568)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at android.os.Parcel.writeSerializable(Parcel.java:2161)
	... 42 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android :     Miui Global 14.0.3

### Affected device model

Redmi Note 9S

**Comment by lmsalustri** [comment]
Duplicate of #11356
