### ISSUE TITLE
App crashes when playing Playlist and going to Home Screen

### ISSUE THREAD

**Issue by OldGuyInTheClub** [TeamNewPipe/NewPipe#11395]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.2

### Steps to reproduce the bug

1. Go to a Channel with Playlists
2. Select a Playlist
3. Select Play All
4. Go to home screen
5. App crashes with "Sorry that should not have happened. Guru Meditation."

### Expected behavior

In prior versions I've been able to start a playlist and then switch to home screen or other apps without a problem.

### Actual behavior

Reproducible crash. "Sorry that should not have happened. Guru Meditation."

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.27.2
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = org.schabi.newpipe.extractor.channel.ChannelInfo)
at android.os.Parcel.writeSerializable(Parcel.java:2178)
at android.os.Parcel.writeValue(Parcel.java:1944)
at android.os.Parcel.writeArrayMapInternal(Parcel.java:1036)
at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
at android.os.Bundle.writeToParcel(Bundle.java:1304)
at android.os.Parcel.writeBundle(Parcel.java:1105)
at android.os.Parcel.writeValue(Parcel.java:1862)
at android.os.Parcel.writeArrayMapInternal(Parcel.java:1036)
at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
at android.os.Bundle.writeToParcel(Bundle.java:1304)
at android.os.Parcel.writeBundle(Parcel.java:1105)
at android.os.Parcel.writeValue(Parcel.java:1862)
at android.os.Parcel.writeArrayMapInternal(Parcel.java:1036)
at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
at android.os.Bundle.writeToParcel(Bundle.java:1304)
at android.os.Parcel.writeBundle(Parcel.java:1105)
at android.os.Parcel.writeValue(Parcel.java:1862)
at android.os.Parcel.writeArrayMapInternal(Parcel.java:1036)
at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
at android.os.Bundle.writeToParcel(Bundle.java:1304)
at android.os.Parcel.writeBundle(Parcel.java:1105)
at android.os.Parcel.writeValue(Parcel.java:1862)
at android.os.Parcel.writeArrayMapInternal(Parcel.java:1036)
at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
at android.os.Bundle.writeToParcel(Bundle.java:1304)
at android.os.Parcel.writeBundle(Parcel.java:1105)
at android.os.Parcel.writeValue(Parcel.java:1862)
at android.os.Parcel.writeArrayMapInternal(Parcel.java:1036)
at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
at android.os.Bundle.writeToParcel(Bundle.java:1304)
at android.os.Parcel.writeBundle(Parcel.java:1105)
at android.os.Parcel.writeValue(Parcel.java:1862)
at android.os.BaseBundle.dumpStats(BaseBundle.java:1690)
at android.os.BaseBundle.dumpStats(BaseBundle.java:1727)
at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:150)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8663)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: [java.io](http://java.io/).NotSerializableException: [org.schabi.newpipe.extractor.services](http://org.schabi.newpipe.extractor.services/).youtube.extractors.YoutubeChannelExtractor
at [java.io](http://java.io/).ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
at [java.io](http://java.io/).ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
at [java.io](http://java.io/).ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
at [java.io](http://java.io/).ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
at [java.io](http://java.io/).ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
at [java.io](http://java.io/).ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
at [java.io](http://java.io/).ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
at [java.io](http://java.io/).ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
at [java.io](http://java.io/).ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
at [java.io](http://java.io/).ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
at java.util.ArrayList.writeObject(ArrayList.java:762)
at java.lang.reflect.Method.invoke(Native Method)
at [java.io](http://java.io/).ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1036)
at [java.io](http://java.io/).ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1552)
at [java.io](http://java.io/).ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
at [java.io](http://java.io/).ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
at [java.io](http://java.io/).ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
at [java.io](http://java.io/).ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
at [java.io](http://java.io/).ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
at [java.io](http://java.io/).ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
at [java.io](http://java.io/).ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
at [java.io](http://java.io/).ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
at [java.io](http://java.io/).ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
at [java.io](http://java.io/).ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
at [java.io](http://java.io/).ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
at android.os.Parcel.writeSerializable(Parcel.java:2173)
... 42 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12 One UI 4.1

### Affected device model

Samsung Galxy S10+ SM-G975U1

### Additional information

Due Diligence:
Searched on is:issue Playlist and looked at current posts tied to v0.27.2

Very similar to https://github.com/TeamNewPipe/NewPipe/issues/11375 but this issue was closed without an answer so I did not try to add on to it.  There was also a duplicate tag applied at some point but I could not see which issue it was duplicating.

Sort of similar to https://github.com/TeamNewPipe/NewPipe/issues/11278 but in my case I don't have to go to fullscreen, return to playlist mode, or swipe to cause the crash.  

Other hits were either different problems and/or tied to older versions.

**Comment by OldGuyInTheClub** [comment]
Ok but I thought I followed the template.  To me it wasn't clear that 11356 applied since it was not tied to playlists. My setup only fails on playlists, not one-off videos.

**Comment by OldGuyInTheClub** [comment]
Ok, thanks.  I'll follow this in future.
