### ISSUE TITLE
App Crash: Videos in YouTube Playlists do not play in background with screen off.

### ISSUE THREAD

**Issue by thewtfness** [TeamNewPipe/NewPipe#11415]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.2

### Steps to reproduce the bug

1. Open NewPipe
2. Navigate to any YouTube playlist
3. Play any video in the playlist
4. Turn off the screen
5. Newpipe Crashes

### Expected behavior

The video is expected to continue playing in the background with the screen off (i.e. audio only)

### Actual behavior

Newpipe app crashes

### Affected Android/Custom ROM version

LineageOS 21

### Affected device model

OnePlus 7 guacamoleb

**Comment by TerremotoDePorta** [comment]
Happens to me as well

**Comment by thewtfness** [comment]
I have tried on other devices as well, and the issue is the same. 

This seems to have started only recently, since the YouTube changes and v 0.27.2

**Comment by levik-opsilient** [comment]
Happening to me too.
2 different phones, Android 11 and 9

Send to occur only when using YouTube, not SoundCloud.

**Comment by levik-opsilient** [comment]
```
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.27.2
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = org.schabi.newpipe.extractor.channel.ChannelInfo)
	at android.os.Parcel.writeSerializable(Parcel.java:2113)
	at android.os.Parcel.writeValue(Parcel.java:1883)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:975)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1303)
	at android.os.Parcel.writeBundle(Parcel.java:1044)
	at android.os.Parcel.writeValue(Parcel.java:1801)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:975)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1303)
	at android.os.Parcel.writeBundle(Parcel.java:1044)
	at android.os.Parcel.writeValue(Parcel.java:1801)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:975)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1303)
	at android.os.Parcel.writeBundle(Parcel.java:1044)
	at android.os.Parcel.writeValue(Parcel.java:1801)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:975)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1303)
	at android.os.Parcel.writeBundle(Parcel.java:1044)
	at android.os.Parcel.writeValue(Parcel.java:1801)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:975)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1303)
	at android.os.Parcel.writeBundle(Parcel.java:1044)
	at android.os.Parcel.writeValue(Parcel.java:1801)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:975)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1303)
	at android.os.Parcel.writeBundle(Parcel.java:1044)
	at android.os.Parcel.writeValue(Parcel.java:1801)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:975)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1303)
	at android.app.IActivityTaskManager$Stub$Proxy.activityStopped(IActivityTaskManager.java:4389)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:145)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.io.NotSerializableException: org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at java.util.ArrayList.writeObject(ArrayList.java:762)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1036)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1552)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at android.os.Parcel.writeSerializable(Parcel.java:2108)
	... 43 more

```
</details>
<hr>

```

**Comment by galure** [comment]
Same for me.
I didn't know the bug occured only on videos in my playlist, I would have never checked. And yes, after some testing, this bug only concerns channels I subscribed to. How strange.

(It's funny because I have the same bug with Freetube on Linux not working in out of focus workspaces. It's a Wayland problem but I am still gonna check if it's only on subscribed channels, you never know. It would be strange, but it's strange on NewPipe too, right?)



The logs:

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.27.2
* __OS:__ Linux Android 14 - 34
<details><summary><b>Crash log </b></summary><p>

```
android.os.BadParcelableException: Parcelable encountered IOException writing serializable object (name = org.schabi.newpipe.extractor.channel.ChannelInfo)
	at android.os.Parcel.writeSerializable(Parcel.java:2909)
	at android.os.Parcel.writeValue(Parcel.java:2675)
	at android.os.Parcel.writeValue(Parcel.java:2474)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1338)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1846)
	at android.os.Bundle.writeToParcel(Bundle.java:1390)
	at android.os.Parcel.writeBundle(Parcel.java:1407)
	at android.os.Parcel.writeValue(Parcel.java:2591)
	at android.os.Parcel.writeValue(Parcel.java:2481)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1338)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1846)
	at android.os.Bundle.writeToParcel(Bundle.java:1390)
	at android.os.Parcel.writeBundle(Parcel.java:1407)
	at android.os.Parcel.writeValue(Parcel.java:2591)
	at android.os.Parcel.writeValue(Parcel.java:2481)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1338)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1846)
	at android.os.Bundle.writeToParcel(Bundle.java:1390)
	at android.os.Parcel.writeBundle(Parcel.java:1407)
	at android.os.Parcel.writeValue(Parcel.java:2591)
	at android.os.Parcel.writeValue(Parcel.java:2481)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1338)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1846)
	at android.os.Bundle.writeToParcel(Bundle.java:1390)
	at android.os.Parcel.writeBundle(Parcel.java:1407)
	at android.os.Parcel.writeValue(Parcel.java:2591)
	at android.os.Parcel.writeValue(Parcel.java:2481)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1338)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1846)
	at android.os.Bundle.writeToParcel(Bundle.java:1390)
	at android.os.Parcel.writeBundle(Parcel.java:1407)
	at android.os.Parcel.writeValue(Parcel.java:2591)
	at android.os.Parcel.writeValue(Parcel.java:2481)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1338)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1846)
	at android.os.Bundle.writeToParcel(Bundle.java:1390)
	at android.os.Parcel.writeBundle(Parcel.java:1407)
	at android.os.Parcel.writeValue(Parcel.java:2591)
	at android.os.Parcel.writeValue(Parcel.java:2481)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1920)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1957)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.collectBundleStates(PendingTransactionActions.java:123)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:139)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.io.NotSerializableException: org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at java.util.ArrayList.writeObject(ArrayList.java:955)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1079)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1568)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at android.os.Parcel.writeSerializable(Parcel.java:2904)
	... 52 more

```
</details>
<hr>

**Comment by NottLexa** [comment]
Oh, it is also happening if you're playing the video at the background while PLAYLISTS tab is opened in the channel's window.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ RU
* __Content Language:__ ru-RU
* __App Language:__ ru_RU
* __Service:__ none
* __Version:__ 0.27.2
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
android.os.BadParcelableException: Parcelable encountered IOException writing serializable object (name = org.schabi.newpipe.extractor.channel.ChannelInfo)
	at android.os.Parcel.writeSerializable(Parcel.java:2752)
	at android.os.Parcel.writeValue(Parcel.java:2518)
	at android.os.Parcel.writeValue(Parcel.java:2317)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1266)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1806)
	at android.os.Bundle.writeToParcel(Bundle.java:1362)
	at android.os.Parcel.writeBundle(Parcel.java:1335)
	at android.os.Parcel.writeValue(Parcel.java:2434)
	at android.os.Parcel.writeValue(Parcel.java:2324)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1266)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1806)
	at android.os.Bundle.writeToParcel(Bundle.java:1362)
	at android.os.Parcel.writeBundle(Parcel.java:1335)
	at android.os.Parcel.writeValue(Parcel.java:2434)
	at android.os.Parcel.writeValue(Parcel.java:2324)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1266)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1806)
	at android.os.Bundle.writeToParcel(Bundle.java:1362)
	at android.os.Parcel.writeBundle(Parcel.java:1335)
	at android.os.Parcel.writeValue(Parcel.java:2434)
	at android.os.Parcel.writeValue(Parcel.java:2324)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1266)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1806)
	at android.os.Bundle.writeToParcel(Bundle.java:1362)
	at android.os.Parcel.writeBundle(Parcel.java:1335)
	at android.os.Parcel.writeValue(Parcel.java:2434)
	at android.os.Parcel.writeValue(Parcel.java:2324)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1266)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1806)
	at android.os.Bundle.writeToParcel(Bundle.java:1362)
	at android.os.Parcel.writeBundle(Parcel.java:1335)
	at android.os.Parcel.writeValue(Parcel.java:2434)
	at android.os.Parcel.writeValue(Parcel.java:2324)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1266)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1806)
	at android.os.Bundle.writeToParcel(Bundle.java:1362)
	at android.os.Parcel.writeBundle(Parcel.java:1335)
	at android.os.Parcel.writeValue(Parcel.java:2434)
	at android.os.Parcel.writeValue(Parcel.java:2324)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1878)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1915)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:150)
	at android.os.Handler.handleCallback(Handler.java:971)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:206)
	at android.os.Looper.loop(Looper.java:296)
	at android.app.ActivityThread.main(ActivityThread.java:9159)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1018)
Caused by: java.io.NotSerializableException: org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at java.util.ArrayList.writeObject(ArrayList.java:873)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1079)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1568)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at android.os.Parcel.writeSerializable(Parcel.java:2747)
	... 49 more

```
</details>
<hr>

**Comment by thewtfness** [comment]
> Fill the template properly.

I thought I had. Can you help me with what I have missed filling ? Thanks !

**Comment by thewtfness** [comment]
ADDITIONAL OBSERVATION: 

The issue only happens with playlists that are created in YouTube.

If I create a playlist manually within NewPipe App, those videos play fine with screen off.

**Comment by thewtfness** [comment]
I see that you have closed this request as a 'duplicate'.  Could you kindly point me to the issue which encompasses this request - so I may follow the progress on that instead. Thanks !

**Comment by thewtfness** [comment]
@opusforlife2 might you please reply to my query above?

**Comment by thewtfness** [comment]
Thanks. Could you perhaps share the link to the WIP issue here please.

**Comment by thewtfness** [comment]
I am not too familiar with using Github, hence was hoping there might be some help provided here.
Not a problem if you are not able to assist. Thanks anyway.

**Comment by thewtfness** [comment]
Thank you. I see it now.
