### ISSUE TITLE
No available space in disk

### ISSUE THREAD

**Issue by Angelk90** [TeamNewPipe/NewPipe#11445]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.2

### Steps to reproduce the bug

From youtube I made youtube videos share from youtube app to newpipe, but for every video I tried to share from the app it gave me this error.

To solve it currently I had to clear the app cache.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ KR
* __Content Language:__ it-IT
* __App Language:__ it_IT
* __Service:__ none
* __Version:__ 0.27.2
* __OS:__ Linux samsung/gtaxlltexx/gtaxllte:8.1.0/M1AJQ/T585XXU6CSL1:user/release-keys 8.1.0 - 27
<details><summary><b>Crash log </b></summary><p>

```
android.database.sqlite.SQLiteFullException: database or disk is full (code 13)
#################################################################
Error Code : 13 (SQLITE_FULL)
Caused By : No available space in disk.
	(database or disk is full (code 13))
#################################################################
	at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:751)
	at android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:437)
	at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:401)
	at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:710)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:344)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:238)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableOrReadableDatabase(FrameworkSQLiteOpenHelper.kt:232)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.innerGetDatabase(FrameworkSQLiteOpenHelper.kt:223)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getSupportDatabase(FrameworkSQLiteOpenHelper.kt:151)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.kt:104)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.kt:632)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.kt:451)
	at androidx.work.impl.model.SystemIdInfoDao_Impl.getWorkSpecIds(SystemIdInfoDao_Impl.java:163)
	at androidx.work.impl.background.systemjob.SystemJobScheduler.reconcileJobs(SystemJobScheduler.java:311)
	at androidx.work.impl.utils.ForceStopRunnable.cleanUp(ForceStopRunnable.java:278)
	at androidx.work.impl.utils.ForceStopRunnable.forceStopRunnable(ForceStopRunnable.java:242)
	at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:134)
	at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

```
</details>
<hr>

**Comment by oong819** [comment]
How many empty storage space you have?

**Comment by lawson85** [comment]
SD Maid SE is free and open source and will fix this problem. It's not really a NewPipe problem
