### ISSUE TITLE
UI Crash When Navigating to Channel from Download Prompt

### ISSUE THREAD

**Issue by dragnev-dev** [TeamNewPipe/NewPipe#11468]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.2

### Steps to reproduce the bug

1. Search for any keyword. Make sure you get videos and at least one channel as results
2. Request a download for a video
3. Before the prompt with video quality shows up, tap on a channel. The time interval for this on my device is around 2-3 secs

### Expected behavior

Download prompt and opening a channel should work

### Actual behavior

UI crash

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ DE
* __Content Language:__ en-DE
* __App Language:__ en_DE_#u-fw-mon-mu-celsius
* __Service:__ none
* __Version:__ 0.27.2
* __OS:__ Linux Android 14 - 34
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1632)
	at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1672)
	at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:341)
	at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:306)
	at androidx.fragment.app.DialogFragment.show(DialogFragment.java:507)
	at org.schabi.newpipe.info_list.dialog.StreamDialogDefaultEntry.lambda$static$16(StreamDialogDefaultEntry.java:119)
	at org.schabi.newpipe.info_list.dialog.StreamDialogDefaultEntry.$r8$lambda$E-BGm7Z2EfgISHn-yX4TCRIhxak(StreamDialogDefaultEntry.java:0)
	at org.schabi.newpipe.info_list.dialog.StreamDialogDefaultEntry$$ExternalSyntheticLambda20.accept(R8$$SyntheticClass:0)
	at org.schabi.newpipe.util.SparseItemUtil.lambda$fetchStreamInfoAndSaveToDatabase$4(SparseItemUtil.java:121)
	at org.schabi.newpipe.util.SparseItemUtil.$r8$lambda$cfmnXoy0qdCzt8EeO-smvalxWsM(SparseItemUtil.java:0)
	at org.schabi.newpipe.util.SparseItemUtil$$ExternalSyntheticLambda0.accept(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:554)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 14 / SuperiorOS fourteen

### Affected device model

Redmi Note 5 AI

### Additional information

Window Animation Scale 0.0x
Transition Animation Scale 0.0x
Animator Duration Scale 0.0x

**Comment by Debzoti** [comment]
i just updated the app and issue is gone.see for updates in your app.

**Comment by dragnev-dev** [comment]
> i just updated the app and issue is gone.see for updates in your app.

- [x] checked for updates in app
- [x] checked for updates in GitHub releases
- [x] checked for pinned issues with new versions

No updates found

**Comment by dragnev-dev** [comment]
No, I was on mobile. I'm not familiar with the GitHub UI so I mistakenly thought what would be a button to be a drop-down.

**Comment by dragnev-dev** [comment]
Added

**Comment by dragnev-dev** [comment]
> Does this happen only with channels? Or also feeds, playlists, etc.?

Ok so which scenarios also trigger the bug. The OP scenario is you long press a video, tap download, then you navigate to a channel before the prompt for the download appears on the screen. Furthermore, cases which trigger the crash after requesting a download are:

- [x] crashes when navigating to a playlist;
- [x] crashes when navigating to a different screen through the burger button side menu (feeds, settings...);
- [x] crashes when navigating to a channel through long-press on a video "Show channel details";
- [x] if you request a download on a video from trending feed (no search applied), then calling a search and navigating to search, it crashes;
- [ ] doesn't crash when navigating to a feed through the tabs in the top navigation;
- [ ] doesn't crash when requesting video long-press actions "Start playing in a popup", "Add to playlist", "Share";
- [ ] doesn't crash when navigating to a different service (SoundCloud, BandCamp...).

**Comment by elvakang** [comment]
May I have this issue assigned to me? I can try to fix it.
