### ISSUE TITLE
java.io.NotSerializableException thrown under specific conditions

### ISSUE THREAD

**Issue by jtotht** [TeamNewPipe/NewPipe#11483]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

v0.27.2

### Steps to reproduce the bug

Within ~2 seconds:

1. Started the first video of a playlist.
2. Locked the device screen.
3. Decreased the device volume a bit.
4. The app crashed.

Reproduced the above once again (with the same playlist).

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ HU
* __Content Language:__ hu-HU
* __App Language:__ hu_HU
* __Service:__ none
* __Version:__ 0.27.2
* __OS:__ Linux samsung/a41eea/a41:12/SP1A.210812.016/A415FXXU3DWD2:user/release-keys 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = org.schabi.newpipe.extractor.channel.ChannelInfo)
	at android.os.Parcel.writeSerializable(Parcel.java:2178)
	at android.os.Parcel.writeValue(Parcel.java:1944)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1036)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeBundle(Parcel.java:1105)
	at android.os.Parcel.writeValue(Parcel.java:1862)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1036)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeBundle(Parcel.java:1105)
	at android.os.Parcel.writeValue(Parcel.java:1862)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1036)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeBundle(Parcel.java:1105)
	at android.os.Parcel.writeValue(Parcel.java:1862)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1036)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeBundle(Parcel.java:1105)
	at android.os.Parcel.writeValue(Parcel.java:1862)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1036)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeBundle(Parcel.java:1105)
	at android.os.Parcel.writeValue(Parcel.java:1862)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1036)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeBundle(Parcel.java:1105)
	at android.os.Parcel.writeValue(Parcel.java:1862)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1690)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1727)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:150)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.io.NotSerializableException: org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at java.util.ArrayList.writeObject(ArrayList.java:873)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1079)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1568)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at android.os.Parcel.writeSerializable(Parcel.java:2173)
	... 42 more
```
</details>

### Affected Android/Custom ROM version

Android 12 / Samsung One UI 4.1

**Comment by jtotht** [comment]
Reproducible also by choosing to play in the background, and without changing the volume. So the key is to start playing and locking the screen shortly afterwards (the app is still processing something, and uses an unserializable object for that?).

**Comment by jtotht** [comment]
I searched for the exception name in the issues, both open and closed. There were no results. If GitHub cannot find a pinned issue based on a word appearing in it, that’s not my fault. I’m sorry for reporting a duplicate, but I’m not sorry for “template ignored”, because I didn’t ignore it.

**Comment by jtotht** [comment]
> In general, have a look at the pinned issues before searching.

Next time I’ll make sure to do so. This time, I didn’t even notice them – I simply skipped them unconsciously due to banner blindness.
