### ISSUE TITLE
StreamResetException while playing media.ccc.de

### ISSUE THREAD

**Issue by rugk** [TeamNewPipe/NewPipe#11507]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.2

### Steps to reproduce the bug

Tried to open https://media.ccc.de/v/35c3-9671-self-encrypting_deception and it fails

### Expected behavior

Not crash

### Actual behavior

Crashes, I even retried and connection is stable (mobile network, not moving) 

### Logs

Tried to open https://media.ccc.de/v/35c3-9671-self-encrypting_deception and it fails
## Exception
* __User Action:__ requested stream
* __Request:__ https://media.ccc.de/v/35c3-9671-self-encrypting_deception
* __Content Country:__ DE
* __Content Language:__ de-DE
* __App Language:__ de_DE
* __Service:__ media.ccc.de
* __Version:__ 0.27.2
* __OS:__ Linux Android 14 - 34
<details><summary><b>Crash log </b></summary><p>

```
okhttp3.internal.http2.StreamResetException: stream was reset: INTERNAL_ERROR
	at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.kt:355)
	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:281)
	at okio.RealBufferedSource.select(RealBufferedSource.kt:94)
	at okhttp3.internal.Util.readBomAsCharset(Util.kt:265)
	at okhttp3.ResponseBody.string(ResponseBody.kt:187)
	at org.schabi.newpipe.DownloaderImpl.execute(DownloaderImpl.java:175)
	at org.schabi.newpipe.extractor.downloader.Downloader.get(Downloader.java:77)
	at org.schabi.newpipe.extractor.downloader.Downloader.get(Downloader.java:32)
	at org.schabi.newpipe.extractor.services.media_ccc.extractors.MediaCCCStreamExtractor.onFetchPage(MediaCCCStreamExtractor.java:197)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:77)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:118)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(ExtractorHelper.java:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda3.call(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 14, CalyxOS 5.10.3

### Affected device model

Fairphone 4 (FP4)  

### Additional information

OS build number: AP2A.240805.005.24510030

Currently charging

**Comment by rugk** [comment]
Can confirm it currently works.
