### ISSUE TITLE
Download Crash

### ISSUE THREAD

**Issue by Tashleo** [TeamNewPipe/NewPipe#11514]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.02

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ ZA
* __Content Language:__ en-ZA
* __App Language:__ en_ZA
* __Service:__ none
* __Version:__ 0.27.2
* __OS:__ Linux HUAWEI/ELE-L09/HWELE:10/HUAWEIELE-L09/10.1.0.141C316:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.database.Cursor.moveToNext()' on a null object reference
	at android.os.Parcel.createException(Parcel.java:2096)
	at android.os.Parcel.readException(Parcel.java:2058)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
	at android.content.ContentResolver.query(ContentResolver.java:955)
	at android.content.ContentResolver.query(ContentResolver.java:891)
	at android.content.ContentResolver.query(ContentResolver.java:840)
	at org.schabi.newpipe.streams.io.StoredDirectoryHelper.findFileSAFHelper(StoredDirectoryHelper.java:367)
	at org.schabi.newpipe.streams.io.StoredDirectoryHelper.findFile(StoredDirectoryHelper.java:277)
	at org.schabi.newpipe.download.DownloadDialog.prepareSelectedDownload(DownloadDialog.java:878)
	at org.schabi.newpipe.download.DownloadDialog.lambda$initToolbar$1(DownloadDialog.java:353)
	at org.schabi.newpipe.download.DownloadDialog.$r8$lambda$eftfC3lumhpNMhhwp_4dKbyeS0U(DownloadDialog.java:0)
	at org.schabi.newpipe.download.DownloadDialog$$ExternalSyntheticLambda13.onMenuItemClick(R8$$SyntheticClass:0)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:225)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:836)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:159)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:987)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:977)
	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:156)
	at android.view.View.performClick(View.java:7317)
	at android.view.View.performClickInternal(View.java:7291)
	at android.view.View.access$3600(View.java:838)
	at android.view.View$PerformClick.run(View.java:28247)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)

```
</details>
<hr>

### Expected behavior

I want the app to download efficiently on my phone which has the updated Linux system on my Huawei P30. 

### Actual behavior

1. Tap on Download on video
2. Waiting for streaming details
3. Immediately crashes and says that something went wrong
4. Resets app after closing it

### Affected Android/Custom ROM version

Emui 12.0.0

### Affected device model

Huawei P38

**Comment by VARTIK-ARSH** [comment]
@Tashleo **I can work on it , faced same issue in my app so i can do it .**

**Comment by RCPK2023** [comment]
Im not sure if we have the same crash output however I also use Huawei, I fixed mine by
1. Open newpipe
2. Settings
3. Downloads
4. Set "Ask where to download"

In my case Im using revanced to open newpipe to download videos, seems to work fine now

**Comment by Stypox** [comment]
Some user reported this same error via email, on a Huawei P40 (codename ANA N29)

**Comment by ghost** [comment]
I am not quite sure if it is related but on Huawei MediaPad AGS2 after I press download. App freezes for a long time then I get "app doesn't response, close it?" after it just works. What is strange all the devices in the issue related to downloads are huawei
