### ISSUE TITLE
Android 7 - crash when playing videos

### ISSUE THREAD

**Issue by mwallnoefer** [TeamNewPipe/NewPipe#11558]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.26.1

### Steps to reproduce the bug

always when I play a Youtube video

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ AT
* __Content Language:__ de-AT
* __App Language:__ de_AT
* __Service:__ none
* __Version:__ 0.26.1
* __OS:__ Linux Android 7.0 - 24
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Failure from system
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1525)
	at android.app.Activity.startActivityForResult(Activity.java:4264)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:712)
	at android.app.Activity.startActivityForResult(Activity.java:4223)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:693)
	at android.app.Activity.startActivity(Activity.java:4547)
	at android.app.Activity.startActivity(Activity.java:4515)
	at org.schabi.newpipe.error.ErrorUtil$Companion.openActivity(ErrorUtil.kt:43)
	at org.schabi.newpipe.error.ErrorUtil$Companion.showSnackbar$lambda$0(ErrorUtil.kt:149)
	at org.schabi.newpipe.error.ErrorUtil$Companion.$r8$lambda$hbVLiP6-HtFc17h3_yyNDsmaIY8(ErrorUtil.kt:0)
	at org.schabi.newpipe.error.ErrorUtil$Companion$$ExternalSyntheticLambda0.onClick(R8$$SyntheticClass:0)
	at com.google.android.material.snackbar.Snackbar.lambda$setAction$0(Snackbar.java:352)
	at com.google.android.material.snackbar.Snackbar.$r8$lambda$4rINiMZz55Dc47hSTCuz-ALWyEw(Snackbar.java:0)
	at com.google.android.material.snackbar.Snackbar$$ExternalSyntheticLambda1.onClick(R8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:5675)
	at android.view.View$PerformClick.run(View.java:22651)
	at android.os.Handler.handleCallback(Handler.java:836)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:208)
	at android.app.ActivityThread.main(ActivityThread.java:6304)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
Caused by: android.os.TransactionTooLargeException: data parcel size 1224188 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:622)
	at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3242)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1518)
	... 22 more

```
</details>
<hr>

### Affected Android/Custom ROM version

7.0 - 24

### Affected device model

ASUS ZenPad 10

**Comment by mwallnoefer** [comment]
The latest release is working like a charm. I apologise, but the internal update feature didn't work: it offered me no newer release, even when doing manual checks. So I really thought that it was the latest one, sorry for the noise.
