### ISSUE TITLE
Soundcloud Could not parse json response when loading playlists

### ISSUE THREAD

**Issue by davidasunmo** [TeamNewPipe/NewPipe#11605]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.2

### Steps to reproduce the bug

1. Open Newpipe
2. Go to your favourite soundcloud playlist
3. (optional) scroll down to load more songs in the playlist

### Expected behavior

All songs in playlist load immediately upon opening the playlist

### Actual behavior

See the spinner spinning longer than usual then see the toaster saying "Something went wrong". 
Or the first batch of songs load, but you keep scrolling down to load more songs until you get the error.
Force close NewPipe and repeat to reproduce.

## Exception
* User Action: requested playlist
* Request: Loading more items: https://soundcloud.com/absurdlylongusername/sets/chill
* Content Country: GB
* Content Language: en-GB
* App Language: en_GB
* Service: SoundCloud
* Version: 0.27.2
* OS: Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse json response
 at org.schabi.newpipe.extractor.services.soundcloud.extractors.SoundcloudPlaylistExtractor.getPage(SoundcloudPlaylistExtractor.java:207)
 at org.schabi.newpipe.extractor.playlist.PlaylistInfo.getMoreItems(PlaylistInfo.java:79)
 at org.schabi.newpipe.util.ExtractorHelper.lambda$getMorePlaylistItems$11(ExtractorHelper.java:190)
 at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$noX9-ubPrK_3aZXBqr0VX801tj0(ExtractorHelper.java:0)
 at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda5.call(R8$$SyntheticClass:0)
 at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
 at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
 at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
 at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
 at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
 at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException: no track with id 1801653561 in response
 at j$.util.Objects.requireNonNull(Unknown Source:5)
 at org.schabi.newpipe.extractor.services.soundcloud.extractors.SoundcloudPlaylistExtractor.getPage(SoundcloudPlaylistExtractor.java:201)
 ... 15 more

 ```

</details>
<hr>

### Affected Android/Custom ROM version

Linux Android 9 - 28

### Affected device model

Samsung Galaxy S8

### Additional information

Problem occurs on both WiFi and mobile data.

**Comment by absurdlylongusername** [comment]
I think this has likely been fixed by https://github.com/TeamNewPipe/NewPipeExtractor/pull/1450, but the `Could not resolve id with embedded player. ClientId not extracted` part is definitely not part of it.

Now having knowledge of what this means I know this is relating to getting the client ID that we use to make requests to the API, but I've never seen this bug again after I saw it the first time.

Since the main bug is due to exception when extracting playlists, and not client ID, I will close this as completed via https://github.com/TeamNewPipe/NewPipeExtractor/pull/1450.
