### ISSUE TITLE
App/UI crash

### ISSUE THREAD

**Issue by fergreming** [TeamNewPipe/NewPipe#11616]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.2

### Steps to reproduce the bug

Play video then leave app, put phone to sleep, or play video in popup window and leave app

### Expected behavior

Video audio to play in background 

### Actual behavior

App/UI crash

### Screenshots/Screen recordings

![Screenshot_20241017-053647](https://github.com/user-attachments/assets/c1697dfa-a843-436b-833a-d6762f02416e)
![Screenshot_20241017-053700](https://github.com/user-attachments/assets/f5da2d3c-9890-45b3-a182-cbaa16f7eace)
![Screenshot_20241017-053621](https://github.com/user-attachments/assets/21997758-2ffb-4d5f-aae7-f692acf3672c)

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ CA
* __Content Language:__ en-CA
* __App Language:__ en_CA
* __Service:__ none
* __Version:__ 0.27.2
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = org.schabi.newpipe.extractor.channel.ChannelInfo)
	at android.os.Parcel.writeSerializable(Parcel.java:2165)
	at android.os.Parcel.writeValue(Parcel.java:1931)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1023)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeBundle(Parcel.java:1092)
	at android.os.Parcel.writeValue(Parcel.java:1849)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1023)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeBundle(Parcel.java:1092)
	at android.os.Parcel.writeValue(Parcel.java:1849)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1023)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeBundle(Parcel.java:1092)
	at android.os.Parcel.writeValue(Parcel.java:1849)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1023)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeBundle(Parcel.java:1092)
	at android.os.Parcel.writeValue(Parcel.java:1849)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1023)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeBundle(Parcel.java:1092)
	at android.os.Parcel.writeValue(Parcel.java:1849)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:1023)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1620)
	at android.os.Bundle.writeToParcel(Bundle.java:1304)
	at android.os.Parcel.writeBundle(Parcel.java:1092)
	at android.os.Parcel.writeValue(Parcel.java:1849)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1690)
	at android.os.BaseBundle.dumpStats(BaseBundle.java:1727)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:150)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7842)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.io.NotSerializableException: org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at java.util.ArrayList.writeObject(ArrayList.java:955)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1079)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1568)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1620)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1581)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1490)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at android.os.Parcel.writeSerializable(Parcel.java:2160)
	... 42 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12

### Affected device model

Google Pixel 3 XL

**Comment by fergreming** [comment]
How do i fix this can't find anything on the internet to help and it would
be deeply appreciated if you could help,
Because if not im using another app
