### ISSUE TITLE
High quality doesn't work 

### ISSUE THREAD

**Issue by Mapaxoide** [TeamNewPipe/NewPipe#11634]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.2

### Steps to reproduce the bug

I changed the video quality to 1080p60 and it shows a message: "an unrecoverable error occurred". I need to know if it's a bug in the app or if my phone is broken XD

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/42325d3d-b659-46f8-9cca-9b0439b6aaf6

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_DECODER_INIT_FAILED] occurred while playing https://www.youtube.com/watch?v=aWTOFYFTLUg
* __Content Country:__ ES
* __Content Language:__ es-ES
* __App Language:__ es_ES
* __Service:__ YouTube
* __Version:__ 0.27.2
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(299, null, null, video/avc, avc1.64002A, 5945625, null, [1920, 1080, 60.0], [-1, -1]), format_supported=YES
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:578)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:223)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(299, null, null, video/avc, avc1.64002A, 5945625, null, [1920, 1080, 60.0], [-1, -1])
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1021)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:537)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1453)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:917)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:954)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:769)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:1007)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:502)
	... 3 more
Caused by: android.media.MediaCodec$CodecException: Error 0xfffffff4
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:2127)
	at android.media.MediaCodec.configure(MediaCodec.java:2043)
	at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter$Factory.createAdapter(SynchronousMediaCodecAdapter.java:51)
	at com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:113)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1099)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1010)
	... 10 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 11 go 

### Affected device model

Nokia 1.4

**Comment by Mapaxoide** [comment]
> ### Checklist
> * [x]  I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
> * [x]  I made sure that there are _no existing issues_ - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
> * [x]  I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
> * [x]  I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
> * [x]  This issue contains only one bug.
> * [x]  I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).
> 
> ### Affected version
> 0.27.2
> 
> ### Steps to reproduce the bug
> I changed the video quality to 1080p60 and it shows a message: "an unrecoverable error occurred". I need to know if it's a bug in the app or if my phone is broken XD
> 
> ### Expected behavior
> _No response_
> 
> ### Actual behavior
> _No response_
> 
> ### Screenshots/Screen recordings
>  screen-20241023-003600.2.mp4 
> ### Logs
> ## Exception
> * **User Action:** play stream
> * **Request:** Player error[type=ERROR_CODE_DECODER_INIT_FAILED] occurred while playing https://www.youtube.com/watch?v=aWTOFYFTLUg
> * **Content Country:** ES
> * **Content Language:** es-ES
> * **App Language:** es_ES
> * **Service:** YouTube
> * **Version:** 0.27.2
> * **OS:** Linux Android 11 - 30
> 
> Crash log
> ### Affected Android/Custom ROM version
> Android 11 go
> 
> ### Affected device model
> Nokia 1.4
> 
> ### Additional information
> _No response_
