### ISSUE TITLE
Bug:crash

### ISSUE THREAD

**Issue by HusniMuhammad** [TeamNewPipe/NewPipe#11719]
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ IN
* __Content Language:__ en-IN
* __App Language:__ en_IN
* __Service:__ none
* __Version:__ 0.27.2
* __OS:__ Linux realme/RMX3231/RMX3231:11/RP1A.201005.001/1683856924092:user/release-keys 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7790)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6873)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7948)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>
<hr>

**Comment by HusniMuhammad** [comment]
> Use of [Template](https://github.com/TeamNewPipe/NewPipe/issues/new?assignees=&labels=bug%2Cneeds+triage&projects=&template=bug_report.yml) is mandatory when filling an issue.
> 
> You seem to have used an app to open this issue. Please use the website next time to fill out our issue template: https://github.com/TeamNewPipe/NewPipe/issues/new/choose to fill all asked required details in template. Thank you.
> 
> _Properly filled template is a must requirement for issues to be considered._

Ah ok thanks for your mandatory suggestion, I used "open source GitHub client" that don't follows  certain templates, it's a bug of that app, next time I use website
