### ISSUE TITLE
(BUG) Large user-created local playlists cannot be shared.

### ISSUE THREAD

**Issue by Turkialh14** [TeamNewPipe/NewPipe#11799]
### Checklist

- [X] I am able to reproduce the bug with the latest version given here: [CLICK THIS LINK](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.27.4

### Steps to reproduce the bug

.1 Create a large local playlist in the app

.2 Try sharing the playlist

.3 When choosing SHARE URL LIST and SHARE WITH TITLES When choosing SHARE URL LIST nothing happens and it stays frozen like this for a while then it doesn't give anything or sometimes it gets stuck and I can't move and when choosing SHARE WITH TITLES it shows me an error that it's large I assume that's because the playlist contains a lot of Korean, Chinese and Japanese videos whose letters take up more space than normal letters

### Expected behavior

The reason it gives me an error when I click on SHARE WITH TITLES is because the file is probably big and I understand that but when I click on SHARE URL LIST it doesn't give me an error so I assumed it was working in the background but no matter how long I wait it doesn't give me any file or error

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/b3cc8512-577e-4d9b-b9a1-5ca89a4accbb

### Logs

SHARE WITH TITLES error report

## Exception
* __User Action:__ ui error
* __Request:__ Sharing playlist
* __Content Country:__ AE
* __Content Language:__ ar-AE
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.27.4
* __OS:__ Linux Android 14 - 34
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Failure from system
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1880)
	at android.app.Activity.startActivityForResult(Activity.java:5760)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:780)
	at android.app.Activity.startActivityForResult(Activity.java:5718)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:761)
	at android.app.Activity.startActivity(Activity.java:6216)
	at android.app.Activity.startActivity(Activity.java:6183)
	at org.schabi.newpipe.util.external_communication.ShareUtils.openAppChooser(ShareUtils.java:217)
	at org.schabi.newpipe.util.external_communication.ShareUtils.shareText(ShareUtils.java:264)
	at org.schabi.newpipe.util.external_communication.ShareUtils.shareText(ShareUtils.java:306)
	at org.schabi.newpipe.local.playlist.LocalPlaylistFragment.lambda$sharePlaylist$6(LocalPlaylistFragment.java:411)
	at org.schabi.newpipe.local.playlist.LocalPlaylistFragment.$r8$lambda$ZwIYEfB9bPAn5G33vVlKglAEk4g(LocalPlaylistFragment.java:0)
	at org.schabi.newpipe.local.playlist.LocalPlaylistFragment$$ExternalSyntheticLambda27.accept(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:403)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:178)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: android.os.TransactionTooLargeException: data parcel size 2322964 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:662)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3041)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1873)
	... 24 more

```
</details>
<hr>

### Affected device model

Samsung Galaxy A54 5G Android 14

### Additional information

There are no duplicate videos in the playlist

 also tried it with larger playlists like 15000

**Comment by Turkialh14** [comment]
I know this is not a big problem for you right now because most users don't have such big playlists and I can do some tricks by extracting videos from db data file but if you have time have a look at it

**Comment by Turkialh14** [comment]
> Please add your steps to reproduce it as a comment in #10748

Ok, also keep in mind that SHARE URL LIST did not give me a system TransactionTooLargeException error.
