### ISSUE TITLE
application crashed, maybe because of "disc full"

### ISSUE THREAD

**Issue by levush** [TeamNewPipe/NewPipe#1326]
- [ ] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
I did not read it, crash reporter using email did not work (button was defunct)
- [ ] I checked if the issue/feature exists in the latest version.
I have the current version that f-droid ships.

{
"user_action": "ui error",
"request": "App crash, UI failure",
"content_language": "GB",
"service": "none",
"package": "org.schabi.newpipe",
"version": "0.13.1",
"os": "Linux Android 7.0 - 24",
"time": "2018-04-17 13:30",
"exceptions": [
"java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{e33aa79 position=20 id=-1, oldPos=-1, pLpos:-1 not recyclable(1)} android.support.v7.widget.RecyclerView{c86a3be VFED.V... .F....ID 0,0-1080,1536 #7f090109 app:id\/items_list}, adapter:org.schabi.newpipe.info_list.InfoListAdapter@e2bcc1f, layout:android.support.v7.widget.LinearLayoutManager@fd18b6c, context:org.schabi.newpipe.MainActivity@99930bd\n\tat android.support.v7.widget.RecyclerView$5.attachViewToParent(RecyclerView.java:842)\n\tat android.support.v7.widget.ChildHelper.attachViewToParent(ChildHelper.java:239)\n\tat android.support.v7.widget.RecyclerView.addAnimatingView(RecyclerView.java:1355)\n\tat android.support.v7.widget.RecyclerView.animateDisappearance(RecyclerView.java:4049)\n\tat android.support.v7.widget.RecyclerView$4.processDisappeared(RecyclerView.java:555)\n\tat android.support.v7.widget.ViewInfoStore.process(ViewInfoStore.java:242)\n\tat android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3882)\n\tat android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3540)\n\tat android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1767)\n\tat android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4928)\n\tat android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)\n\tat android.view.Choreographer.doCallbacks(Choreographer.java:683)\n\tat android.view.Choreographer.doFrame(Choreographer.java:616)\n\tat android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)\n\tat android.os.Handler.handleCallback(Handler.java:751)\n\tat android.os.Handler.dispatchMessage(Handler.java:95)\n\tat android.os.Looper.loop(Looper.java:154)\n\tat android.app.ActivityThread.main(ActivityThread.java:6123)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)\n"
],
"user_comment": "could be that local storage is full or near full.\n:"
}

**Comment by theScrabi** [comment]
could be that local storage is full or near full

could be.

**Comment by Stypox** [comment]
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ GB
* __Service:__ none
* __Version:__ 0.13.1
* __OS:__ Linux Android 7.0 - 24
could be that local storage is full or near full.

<details><summary><b>Crash log</b></summary><p>

```
java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{e33aa79 position=20 id=-1, oldPos=-1, pLpos:-1 not recyclable(1)} android.support.v7.widget.RecyclerView{c86a3be VFED.V... .F....ID 0,0-1080,1536 #7f090109 app:id/items_list}, adapter:org.schabi.newpipe.info_list.InfoListAdapter@e2bcc1f, layout:android.support.v7.widget.LinearLayoutManager@fd18b6c, context:org.schabi.newpipe.MainActivity@99930bd
	at android.support.v7.widget.RecyclerView$5.attachViewToParent(RecyclerView.java:842)
	at android.support.v7.widget.ChildHelper.attachViewToParent(ChildHelper.java:239)
	at android.support.v7.widget.RecyclerView.addAnimatingView(RecyclerView.java:1355)
	at android.support.v7.widget.RecyclerView.animateDisappearance(RecyclerView.java:4049)
	at android.support.v7.widget.RecyclerView$4.processDisappeared(RecyclerView.java:555)
	at android.support.v7.widget.ViewInfoStore.process(ViewInfoStore.java:242)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3882)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3540)
	at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1767)
	at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4928)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
	at android.view.Choreographer.doCallbacks(Choreographer.java:683)
	at android.view.Choreographer.doFrame(Choreographer.java:616)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

```
</p></details>
<hr>

**Comment by Stypox** [comment]
I don't think this issue can be solved in any way. From the bugreport it seems to be an internal problem (maybe caused by some wrong configuration). As theScrabi said, this could, or could not, be caused by full storage, but there is not enough information.
