### ISSUE TITLE
'getRepeatMode' Null Pointer Exception from Shared Videos

### ISSUE THREAD

**Issue by jdertl** [TeamNewPipe/NewPipe#1412]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.

There's a 60% chance for any video with a normal YouTube URL being "shared" to NewPipe to throw this exception.  Last used version was 0.12.0 beta where issue did not occur, now this occurs with almost every video in 0.13.3, and will have an equal 60% chance if attempted again, meaning the videos themselves do not cause the issue as I can simply re-share the same link and NewPipe will roll the dice.  Fresh install of less than 24 hours use.  Often requires completely exiting NewPipe for video to work through sharing.

EDIT:  Rather than being the first video after NewPipe opens, it is more often once one video is opened, then backing out, sharing another one, and THEN the exception occurs, so consecutive sharing of video URLs.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.android.exoplayer2.SimpleExoPlayer.getRepeatMode()' on a null object reference
	at org.schabi.newpipe.player.BasePlayer.getRepeatMode(BasePlayer.java:1149)
	at org.schabi.newpipe.player.BasePlayer.handleIntent(BasePlayer.java:235)
	at org.schabi.newpipe.player.VideoPlayer.handleIntent(VideoPlayer.java:256)
	at org.schabi.newpipe.player.MainVideoPlayer.onNewIntent(MainVideoPlayer.java:149)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1240)
	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1252)
	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3424)
	at android.app.ActivityThread.performNewIntents(ActivityThread.java:3436)
	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3445)
	at android.app.ActivityThread.access$1900(ActivityThread.java:221)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1871)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7224)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by jdertl** [comment]
Fixed by 13.7
