### ISSUE TITLE
Unable to Open Downloads

### ISSUE THREAD

**Issue by awgneo** [TeamNewPipe/NewPipe#1414]
Hello NewPipe,

Every time I try to access the downloads section via the main menu the app crashes with this message. I have tried uninstalling and reinstalling, clearing NewPipe's data, and deleting all media files in the storage locations.

{
   "user_action": "ui error",
   "request": "App crash, UI failure",
   "content_language": "GB",
   "service": "none",
   "package": "org.schabi.newpipe",
   "version": "0.13.3",
   "os": "Linux Android 8.1.0 - 27",
   "time": "2018-05-21 14:41",
   "exceptions": [
      "java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.ArrayList.add(java.lang.Object)' on a null object reference\n\tat us.shandian.giga.get.DownloadMission.addListener(DownloadMission.java:234)\n\tat us.shandian.giga.ui.adapter.MissionAdapter.onBindViewHolder(MissionAdapter.java:115)\n\tat us.shandian.giga.ui.adapter.MissionAdapter.onBindViewHolder(MissionAdapter.java:40)\n\tat android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)\n\tat android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)\n\tat android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)\n\tat android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)\n\tat android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)\n\tat android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)\n\tat android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)\n\tat android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)\n\tat android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)\n\tat android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)\n\tat android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)\n\tat android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)\n\tat android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)\n\tat android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)\n\tat android.view.View.layout(View.java:19659)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6075)\n\tat android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)\n\tat android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)\n\tat android.widget.LinearLayout.onLayout(LinearLayout.java:1544)\n\tat android.view.View.layout(View.java:19659)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6075)\n\tat android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)\n\tat android.widget.FrameLayout.onLayout(FrameLayout.java:261)\n\tat android.view.View.layout(View.java:19659)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6075)\n\tat android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)\n\tat android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)\n\tat android.widget.LinearLayout.onLayout(LinearLayout.java:1544)\n\tat android.view.View.layout(View.java:19659)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6075)\n\tat android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)\n\tat android.widget.FrameLayout.onLayout(FrameLayout.java:261)\n\tat android.view.View.layout(View.java:19659)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6075)\n\tat android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)\n\tat android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)\n\tat android.widget.LinearLayout.onLayout(LinearLayout.java:1544)\n\tat android.view.View.layout(View.java:19659)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6075)\n\tat android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)\n\tat android.widget.FrameLayout.onLayout(FrameLayout.java:261)\n\tat android.view.View.layout(View.java:19659)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6075)\n\tat android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)\n\tat android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)\n\tat android.widget.LinearLayout.onLayout(LinearLayout.java:1544)\n\tat android.view.View.layout(View.java:19659)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6075)\n\tat android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)\n\tat android.widget.FrameLayout.onLayout(FrameLayout.java:261)\n\tat com.android.internal.policy.DecorView.onLayout(DecorView.java:761)\n\tat android.view.View.layout(View.java:19659)\n\tat android.view.ViewGroup.layout(ViewGroup.java:6075)\n\tat android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2496)\n\tat android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2212)\n\tat android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)\n\tat android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)\n\tat android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)\n\tat android.view.Choreographer.doCallbacks(Choreographer.java:723)\n\tat android.view.Choreographer.doFrame(Choreographer.java:658)\n\tat android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)\n\tat android.os.Handler.handleCallback(Handler.java:790)\n\tat android.os.Handler.dispatchMessage(Handler.java:99)\n\tat android.os.Looper.loop(Looper.java:164)\n\tat android.app.ActivityThread.main(ActivityThread.java:6494)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)\n"
   ],
   "user_comment": ""
}

**Comment by theScrabi** [comment]
Ok ill take a look

**Comment by dakrag** [comment]
I have this problem as well. I'm on LineageOS 14.1 (Android 7.1) running as root, with Amplify, MinMinGuard, and AdAway installed if that helps. Whitelisting NewPipe in MinMinGuard did not help either.

**Comment by hmedway** [comment]
I am having this issue as well. Lineage OS 14.1, Android 7.1.2, no root.

Attempting to access the downloads page by any means, whether via the download notification or via the sidebar button results in a crash of this nature, and the cancellation of any current downloads. 

If you don't try to access the downloads page, the download seems to complete just fine!

The workaround:

@dakrag If you empty the NewPipe folders, ```/sdcard/Music/NewPipe/``` and ```/sdcard/Movies/NewPipe/```, the bug goes away, presumably until you 'fill up' those folders again.

@theScrabi It must be an over-run on how many objects the app can display at once.

<details><summary> Error log dump</summary>
<pre>{
   "user_action": "ui error",
   "request": "App crash, UI failure",
   "content_language": "GB",
   "service": "none",
   "package": "org.schabi.newpipe",
   "version": "0.13.3",
   "os": "Linux Android 7.1.2 - 25",
   "time": "2018-05-22 17:14",
   "exceptions": [
      "java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.ArrayList.add(java.lang.Object)' on a null object reference\n\t
      at us.shandian.giga.get.DownloadMission.addListener(DownloadMission.java:234)\n\t
      at us.shandian.giga.ui.adapter.MissionAdapter.onBindViewHolder(MissionAdapter.java:115)\n\t
      at us.shandian.giga.ui.adapter.MissionAdapter.onBindViewHolder(MissionAdapter.java:40)\n\t
      at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)\n\t
      at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)\n\t
      at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)\n\t
      at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)\n\t
      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)\n\t
      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)\n\t
      at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)\n\t
      at android.support.v7.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:556)\n\t
      at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)\n\t
      at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)\n\t
      at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)\n\t
      at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)\n\t
      at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)\n\t
      at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)\n\t
      at android.view.View.layout(View.java:17641)\n\t
      at android.view.ViewGroup.layout(ViewGroup.java:5575)\n\t
      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)\n\t
      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)\n\t
      at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)\n\t
      at android.view.View.layout(View.java:17641)\n\t
      at android.view.ViewGroup.layout(ViewGroup.java:5575)\n\t
      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)\n\t
      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)\n\t
      at android.view.View.layout(View.java:17641)\n\t
      at android.view.ViewGroup.layout(ViewGroup.java:5575)\n\t
      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)\n\t
      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)\n\t
      at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)\n\t
      at android.view.View.layout(View.java:17641)\n\t
      at android.view.ViewGroup.layout(ViewGroup.java:5575)\n\t
      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)\n\t
      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)\n\t
      at android.view.View.layout(View.java:17641)\n\t
      at android.view.ViewGroup.layout(ViewGroup.java:5575)\n\t
      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)\n\t
      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)\n\t
      at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)\n\t
      at android.view.View.layout(View.java:17641)\n\t
      at android.view.ViewGroup.layout(ViewGroup.java:5575)\n\t
      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)\n\t
      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)\n\t
      at android.view.View.layout(View.java:17641)\n\t
      at android.view.ViewGroup.layout(ViewGroup.java:5575)\n\t
      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)\n\t
      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)\n\t
      at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)\n\t
      at android.view.View.layout(View.java:17641)\n\t
      at android.view.ViewGroup.layout(ViewGroup.java:5575)\n\t
      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)\n\t
      at android.widget.FrameLayout.onLayout(FrameLayout.java:261)\n\t
      at com.android.internal.policy.DecorView.onLayout(DecorView.java:729)\n\t
      at android.view.View.layout(View.java:17641)\n\t
      at android.view.ViewGroup.layout(ViewGroup.java:5575)\n\t
      at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)\n\t
      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)\n\t
      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)\n\t
      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6344)\n\t
      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)\n\t
      at android.view.Choreographer.doCallbacks(Choreographer.java:686)\n\t
      at android.view.Choreographer.doFrame(Choreographer.java:621)\n\t
      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)\n\t
      at android.os.Handler.handleCallback(Handler.java:751)\n\t
      at android.os.Handler.dispatchMessage(Handler.java:95)\n\t
      at android.os.Looper.loop(Looper.java:154)\n\t
      at android.app.ActivityThread.main(ActivityThread.java:6186)\n\t
      at java.lang.reflect.Method.invoke(Native Method)\n\t
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)\n\t
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)\n"
   ],
   "user_comment": ""
}</pre>
</details>

**Comment by awgneo** [comment]
In my case, on Oreo, I had only downloaded a single file and it produced this bug. So for me, I was not filling up anything or creating too many objects, I think?

**Comment by hmedway** [comment]
@awgneo you may be right.  Java is Greek to me, but your log looks nearly identical to mine, so it's got to be a layout issue of some sort!

This line:

    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.ArrayList.add(java.lang.Object)' on a null object reference

At the top, isn't that implying that it's trying to draw something that doesn't exist?

**Comment by dakotagrvtt** [comment]
Emptying the download folders or creating and setting as the download folder seems to have fixed the problem. I can access the downloads ran now. I noticed simply removing the .giga files seemed to have the same effect as removing the files altogether. Maybe it had to do with those being corrupted somehow?

**Comment by dakrag** [comment]
Emptying the download folders or creating and setting as the download folder seems to have fixed the problem. I can access the downloads tab now. I noticed simply removing the .giga files seemed to have the same effect as removing the files altogether. Maybe it had to do with those being corrupted somehow?

**Comment by theScrabi** [comment]
I understand. That's nasty.
I suspect that I will find time on the weekend, but I was very happy if someone could help with a fix.

**Comment by adrium** [comment]
Same here. Removed the `.giga` files and Downloads could be opened again.

Already had problems when starting the download: it did not seem to start at first. When tapping on the notification, the download list opened, but the transfers seem to be frozen.

**Comment by hmedway** [comment]
Can confirm, I just had a failed download and an orphaned .giga file. The error triggered again. Removing the .giga files does relieve the issue.

**Comment by theScrabi** [comment]
fixed: https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.13.4
