### ISSUE TITLE
App crashes when I try to load Eminem

### ISSUE THREAD

**Issue by Somethingweirdhere** [TeamNewPipe/NewPipe#1477]
It sometimes works, but when I try to open the channel EminemVevo or share https://www.youtube.com/user/EminemVEVO to newpipe, it will sometimes crash. Other channels work fine. It's really weird, can someone reproduce it?

## Exception
* __User Action:__ requested channel
* __Request:__ https://www.youtube.com/channel/UC20vb-R_px4CguHzzBPhoyQ
* __Content Language:__ US
* __Service:__ YouTube
* __Version:__ 0.13.3
* __OS:__ Linux Android 8.0.0 - 26

<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get channel id
	at org.schabi.newpipe.extractor.services.youtube.YoutubeChannelExtractor.getId(YoutubeChannelExtractor.java:91)
	at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:59)
	at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:46)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getChannelInfo$4$ExtractorHelper(ExtractorHelper.java:117)
	at org.schabi.newpipe.util.ExtractorHelper$$Lambda$4.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3096)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3096)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:3940)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:13610)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:3940)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3096)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:571)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.attr(java.lang.String)' on a null object reference
	at org.schabi.newpipe.extractor.services.youtube.YoutubeChannelExtractor.getId(YoutubeChannelExtractor.java:89)
	... 28 more

```
</p></details>
<hr>

**Comment by rmsEfx** [comment]
It's crashing... One more channel too... And the good question is "Is it YouTube protection against third-party front-ends"... 
![img_20180614_122637_288](https://user-images.githubusercontent.com/19751507/41393158-a7b9f742-6fce-11e8-9e5f-58301d41de07.jpg)

**Comment by theScrabi** [comment]
@rmsEfx Don't post screenshots of bug reports. Describe you error and if necesary post the stacktrace.

**Comment by rmsEfx** [comment]
щас, разбежался..

**Comment by theScrabi** [comment]
@rmsEfx aand here goes the report :kissing_heart:
