### ISSUE TITLE
Unable to save downloads to SD card

### ISSUE THREAD

**Issue by snappyapple632** [TeamNewPipe/NewPipe#1544]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [X] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ US
* __Servicet:__ none
* __Version:__ 0.13.6
* __OS:__ Linux Android 8.0.0 - 26

```
java.lang.RuntimeException: java.io.IOException: Permission denied
	at us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:340)
Caused by: java.io.IOException: Permission denied
	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
	at java.io.File.createNewFile(File.java:1000)
	at us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:332)
java.io.IOException: Permission denied
	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:281)
	at java.io.File.createNewFile(File.java:1000)
	at us.shandian.giga.get.DownloadManagerImpl$Initializer.run(DownloadManagerImpl.java:332)

-------------------

This bug was mentioned in another issue but was never addressed. NewPipe needs permission to use a phone's SD card, apparently.

**Comment by switchtegrax1** [comment]
That's a know issue and its beeing worked on,the issue is that currently newpipe's downloader doesn't use the latest api's to access the sdcard,newpipe team is currently trying to replace newpipe's old downloader with a newer simpler one,but until then newpipe's sdcard download is brojen on anything higher than kitkat

**Comment by theScrabi** [comment]
Here we go: https://github.com/TeamNewPipe/NewPipe/issues/962

@snappyapple632 Your the first one who used the bug report converter. Thanks for that :)
