### ISSUE TITLE
When I am integrating this application with changing package name, my application is crashing in VideoItemDetailActivity.

### ISSUE THREAD

**Issue by SmartDroidDeveloper** [TeamNewPipe/NewPipe#157]
Please tell me why this is happened?

java.lang.ExceptionInInitializerError
                                                                             at services.youtube.YoutubeVideoExtractor.decryptSignature(YoutubeVideoExtractor.java:604)
                                                                             at services.youtube.YoutubeVideoExtractor.parseDashManifest(YoutubeVideoExtractor.java:472)
                                                                             at services.youtube.YoutubeVideoExtractor.getAudioStreams(YoutubeVideoExtractor.java:223)
                                                                             at services.VideoExtractor.getVideoInfo(VideoExtractor.java:84)
                                                                             at services.youtube.YoutubeVideoExtractor.getVideoInfo(YoutubeVideoExtractor.java:378)
                                                                             at VideoItemDetailFragment$VideoExtractorRunnable.run(VideoItemDetailFragment.java:111)
                                                                             at java.lang.Thread.run(Thread.java:856)
                                                                          Caused by: java.lang.ExceptionInInitializerError
                                                                             at org.mozilla.javascript.Context.<clinit>(Context.java:301)
                                                                             at services.youtube.YoutubeVideoExtractor.decryptSignature(YoutubeVideoExtractor.java:604) 
                                                                             at services.youtube.YoutubeVideoExtractor.parseDashManifest(YoutubeVideoExtractor.java:472) 
                                                                             at services.youtube.YoutubeVideoExtractor.getAudioStreams(YoutubeVideoExtractor.java:223) 
                                                                             at com.ecomapps.downloader.services.VideoExtractor.getVideoInfo(VideoExtractor.java:84) 
                                                                             at services.youtube.YoutubeVideoExtractor.getVideoInfo(YoutubeVideoExtractor.java:378) 
                                                                             at VideoItemDetailFragment$VideoExtractorRunnable.run(VideoItemDetailFragment.java:111) 
                                                                             at java.lang.Thread.run(Thread.java:856) 
                                                                          Caused by: java.lang.NoClassDefFoundError: org.mozilla.javascript.Scriptable
                                                                             at org.mozilla.javascript.ScriptRuntime.<clinit>(ScriptRuntime.java:135)
                                                                             at org.mozilla.javascript.Context.<clinit>(Context.java:301) 
                                                                             at services.youtube.YoutubeVideoExtractor.decryptSignature(YoutubeVideoExtractor.java:604) 
                                                                             at services.youtube.YoutubeVideoExtractor.parseDashManifest(YoutubeVideoExtractor.java:472) 
                                                                             at services.youtube.YoutubeVideoExtractor.getAudioStreams(YoutubeVideoExtractor.java:223) 
                                                                             at services.VideoExtractor.getVideoInfo(VideoExtractor.java:84) 
                                                                             at services.youtube.YoutubeVideoExtractor.getVideoInfo(YoutubeVideoExtractor.java:378) 
                                                                             at VideoItemDetailFragment$VideoExtractorRunnable.run(VideoItemDetailFragment.java:111) 
                                                                             at java.lang.Thread.run(Thread.java:856)

**Comment by theScrabi** [comment]
This error is caused inside the VideoExtractor, but I can't see a link between changing the package name, and this error.
