### ISSUE TITLE
Unable to Share Playlist from Youtube URL to NewPipe

### ISSUE THREAD

**Issue by MrOats** [TeamNewPipe/NewPipe#1579]
- [•] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [•] I checked if the issue/feature exists in the latest version.
- [•] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Version: 0.13.7
Steps to reproduce:

1. Open Youtube App
2. Find a playlist
3. Hit share and select NewPipe
4. Select any of the options, ideally "Information"
5. NewPipe reports error below

## Exception
* __User Action:__ requested playlist
* __Request:__ https://www.youtube.com/playlist?list=PLT1zim-_E9NEHF7GfkgInhE_glOTcK9S, opened with background_player
* __Content Language:__ GB
* __Service:__ YouTube
* __Version:__ 0.13.7
* __OS:__ Linux Android 8.1.0 - 27

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get playlist name
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubePlaylistExtractor.getName(YoutubePlaylistExtractor.java:50)
	at org.schabi.newpipe.extractor.playlist.PlaylistInfo.getInfo(PlaylistInfo.java:45)
	at org.schabi.newpipe.extractor.playlist.PlaylistInfo.getInfo(PlaylistInfo.java:28)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getPlaylistInfo$6$ExtractorHelper(ExtractorHelper.java:137)
	at org.schabi.newpipe.util.ExtractorHelper$$Lambda$6.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3310)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3310)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4073)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14349)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4073)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3310)
	at io.reactivex.internal.operators.single.SingleObserveOn.subscribeActual(SingleObserveOn.java:35)
	at io.reactivex.Single.subscribe(Single.java:3310)
	at io.reactivex.Single.subscribe(Single.java:3296)
	at org.schabi.newpipe.RouterActivity$FetcherService.handleChoice(RouterActivity.java:530)
	at org.schabi.newpipe.RouterActivity$FetcherService.onHandleIntent(RouterActivity.java:502)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)

-------------------

```

**Comment by MrOats** [comment]
Weird, my bad... it works fine. For some reason two playlists I tried didn't work. Clicked on the link I posted above and it to load on a web browser. 

Just tried a third one on the Youtube app and it worked fine.

Closing ticket, my apologies.

**Comment by theScrabi** [comment]
Hm, well this error says It could not get the name. When I click on the playlist I can not reach it... maybe it does not exist anymore.
