### ISSUE TITLE
NewPipe 0.14.0 app crash UI failure

### ISSUE THREAD

**Issue by Brimont** [TeamNewPipe/NewPipe#1656]
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ IT
* __Service:__ none
* __Version:__ 0.14.0
* __OS:__ Linux Android 4.2.1 - 17

```
java.lang.NullPointerException
	at android.widget.Spinner.makeAndAddView(Spinner.java:546)
	at android.widget.Spinner.layout(Spinner.java:495)
	at android.widget.Spinner.onLayout(Spinner.java:459)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.support.v7.widget.Toolbar.layoutChildLeft(Toolbar.java:1948)
	at android.support.v7.widget.Toolbar.onLayout(Toolbar.java:1887)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1670)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1528)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1441)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1171)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1670)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1528)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1441)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1670)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1528)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1441)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2183)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1947)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1139)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4879)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
	at android.view.Choreographer.doCallbacks(Choreographer.java:579)
	at android.view.Choreographer.doFrame(Choreographer.java:548)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:153)
	at android.app.ActivityThread.main(ActivityThread.java:5297)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(Native Method)

-------------------

```

**Comment by Brimont** [comment]
Crash when delet video download


## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ IT
* __Service:__ none
* __Version:__ 0.14.0
* __OS:__ Linux Android 4.2.1 - 17

```
io.reactivex.exceptions.OnErrorNotImplementedException: Invalid index 2, size is 2
	at io.reactivex.internal.observers.EmptyCompletableObserver.onError(EmptyCompletableObserver.java:51)
	at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.onError(CompletableSubscribeOn.java:74)
	at io.reactivex.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:38)
	at io.reactivex.Completable.subscribe(Completable.java:1919)
	at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:838)
Caused by: java.lang.IndexOutOfBoundsException: Invalid index 2, size is 2
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
	at java.util.ArrayList.get(ArrayList.java:304)
	at us.shandian.giga.get.DownloadManagerImpl.getMission(DownloadManagerImpl.java:193)
	at us.shandian.giga.get.DownloadManagerImpl.deleteMission(DownloadManagerImpl.java:101)
	at org.schabi.newpipe.download.DeleteDownloadManager.deletePending(DeleteDownloadManager.java:144)
	at org.schabi.newpipe.download.DownloadActivity$$Lambda$0.run(Unknown Source)
	at io.reactivex.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:34)
	... 11 more
java.lang.IndexOutOfBoundsException: Invalid index 2, size is 2
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
	at java.util.ArrayList.get(ArrayList.java:304)
	at us.shandian.giga.get.DownloadManagerImpl.getMission(DownloadManagerImpl.java:193)
	at us.shandian.giga.get.DownloadManagerImpl.deleteMission(DownloadManagerImpl.java:101)
	at org.schabi.newpipe.download.DeleteDownloadManager.deletePending(DeleteDownloadManager.java:144)
	at org.schabi.newpipe.download.DownloadActivity$$Lambda$0.run(Unknown Source)
	at io.reactivex.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:34)
	at io.reactivex.Completable.subscribe(Completable.java:1919)
	at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:838)

-------------------

```

**Comment by Brimont** [comment]
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ IT
* __Service:__ none
* __Version:__ 0.14.0
* __OS:__ Linux Android 4.2.1 - 17

```
java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{42bc7e58 position=0 id=-1, oldPos=-1, pLpos:-1} android.support.v7.widget.RecyclerView{42e33588 VFED.V.. .F....ID 0,0-540,838 #7f090115 app:id/items_list}, adapter:org.schabi.newpipe.info_list.InfoListAdapter@42dd6658, layout:android.support.v7.widget.LinearLayoutManager@42e6f8c8, context:org.schabi.newpipe.MainActivity@42167f80
	at android.support.v7.widget.RecyclerView$5.attachViewToParent(RecyclerView.java:842)
	at android.support.v7.widget.ChildHelper.attachViewToParent(ChildHelper.java:239)
	at android.support.v7.widget.RecyclerView.addAnimatingView(RecyclerView.java:1355)
	at android.support.v7.widget.RecyclerView.animateDisappearance(RecyclerView.java:4049)
	at android.support.v7.widget.RecyclerView$4.processDisappeared(RecyclerView.java:555)
	at android.support.v7.widget.ViewInfoStore.process(ViewInfoStore.java:242)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3882)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3540)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:985)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1171)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1670)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1528)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1441)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1670)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1528)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1441)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2183)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1947)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1139)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4879)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
	at android.view.Choreographer.doCallbacks(Choreographer.java:579)
	at android.view.Choreographer.doFrame(Choreographer.java:548)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:153)
	at android.app.ActivityThread.main(ActivityThread.java:5297)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(Native Method)

-------------------

```

**Comment by Brimont** [comment]
these are 3 different app crashes
