### ISSUE TITLE
Exception on pressing back arrow

### ISSUE THREAD

**Issue by Brimont** [TeamNewPipe/NewPipe#1674]
when you open YouTube link from your browser and press left arrow in newpipe an exception will show up.

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ IT
* __Service:__ none
* __Version:__ 0.14.1
* __OS:__ Linux Android 4.2.1 - 17

```
java.lang.NullPointerException
	at android.widget.Spinner.makeAndAddView(Spinner.java:546)
	at android.widget.Spinner.layout(Spinner.java:495)
	at android.widget.Spinner.onLayout(Spinner.java:459)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.support.v7.widget.Toolbar.layoutChildLeft(Toolbar.java:1948)
	at android.support.v7.widget.Toolbar.onLayout(Toolbar.java:1887)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1670)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1528)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1441)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1171)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1670)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1528)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1441)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1670)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1528)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1441)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2183)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1947)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1139)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4879)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
	at android.view.Choreographer.doCallbacks(Choreographer.java:579)
	at android.view.Choreographer.doFrame(Choreographer.java:548)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:153)
	at android.app.ActivityThread.main(ActivityThread.java:5297)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(Native Method)

-------------------

```
![screenshot_2018-09-08-11-45-00](https://user-images.githubusercontent.com/42345179/45252852-c4ce8780-b35d-11e8-88b5-75821481d1d1.png)
Test this link https://m.youtube.com/watch?v=4cyiL8n-5P8

**Comment by theScrabi** [comment]
Can not confirl. Please give further information.

**Comment by Brimont** [comment]
@TheScrabi test with emulator android 4.2

**Comment by Brimont** [comment]
every time I open a browser link when I press the back arrow the app crashes

**Comment by Brimont** [comment]
I have recording an video

<div style="width:100%;height:0px;position:relative;padding-bottom:200.000%;"><iframe src="https://streamable.com/s/8atkm/hpjleu" frameborder="0" width="100%" height="100%" allowfullscreen style="width:100%;height:100%;position:absolute;left:0px;top:0px;overflow:hidden;"></iframe></div>

**Comment by Brimont** [comment]
@theScrabi @gkeegan my video si fine?

**Comment by theScrabi** [comment]
Yrs i get it its when you return to that selection menu :/

**Comment by Brimont** [comment]
@theScrabi thanks for help me :)

**Comment by theScrabi** [comment]
@Brimont what is in your mein page, because it seems that the back button it self is not causing the error.

**Comment by Brimont** [comment]
![screenshot_2018-09-11-14-15-28](https://user-images.githubusercontent.com/42345179/45359573-37916a00-b5cd-11e8-98df-251f49a966fe.png)
![screenshot_2018-09-11-14-15-34](https://user-images.githubusercontent.com/42345179/45359577-3e1fe180-b5cd-11e8-95cc-5c5a656ab156.png)
![screenshot_2018-09-11-14-15-40](https://user-images.githubusercontent.com/42345179/45359588-4415c280-b5cd-11e8-9f53-b4a8ab6fda5f.png)

**Comment by Brimont** [comment]
@theScrabi try to use emulator of android (android studio or genymotion)

**Comment by Brimont** [comment]
I have this phone www.mediacomeurope.it/Prodotti/Scheda.aspx?XRI=2181
