### ISSUE TITLE
UI crashed displaying YouTube Channels  /bug report

### ISSUE THREAD

**Issue by michel90** [TeamNewPipe/NewPipe#1680]
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ GB
* __Service:__ none
* __Version:__ 0.14.1
* __OS:__ Linux Android 4.0.4 - 15

```
java.lang.NullPointerException
	at android.widget.Spinner.makeAndAddView(Spinner.java:394)
	at android.widget.Spinner.layout(Spinner.java:345)
	at android.widget.Spinner.onLayout(Spinner.java:309)
	at android.view.View.layout(View.java:11418)
	at android.view.ViewGroup.layout(ViewGroup.java:4328)
	at android.support.v7.widget.Toolbar.layoutChildLeft(Toolbar.java:1948)
	at android.support.v7.widget.Toolbar.onLayout(Toolbar.java:1887)
	at android.view.View.layout(View.java:11418)
	at android.view.ViewGroup.layout(ViewGroup.java:4328)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1652)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1510)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1415)
	at android.view.View.layout(View.java:11418)
	at android.view.ViewGroup.layout(ViewGroup.java:4328)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:443)
	at android.view.View.layout(View.java:11418)
	at android.view.ViewGroup.layout(ViewGroup.java:4328)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1171)
	at android.view.View.layout(View.java:11418)
	at android.view.ViewGroup.layout(ViewGroup.java:4328)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:443)
	at android.view.View.layout(View.java:11418)
	at android.view.ViewGroup.layout(ViewGroup.java:4328)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1652)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1510)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1415)
	at android.view.View.layout(View.java:11418)
	at android.view.ViewGroup.layout(ViewGroup.java:4328)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:443)
	at android.view.View.layout(View.java:11418)
	at android.view.ViewGroup.layout(ViewGroup.java:4328)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1652)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1510)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1415)
	at android.view.View.layout(View.java:11418)
	at android.view.ViewGroup.layout(ViewGroup.java:4328)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:443)
	at android.view.View.layout(View.java:11418)
	at android.view.ViewGroup.layout(ViewGroup.java:4328)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1489)
	at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2442)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4441)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
	at dalvik.system.NativeStart.main(Native Method)

-------------------

```
I can't see any channel homepage, this always happen when I touch a channel name

**Comment by skil3z** [comment]
Do you have the latest version? 
https://github.com/TeamNewPipe/NewPipe/releases

**Comment by terrawarra** [comment]
Thanks skil3z..... I just downloaded and installed that version from your link and now newpipe is working beautifully again.
Cheers

**Comment by michel90** [comment]
I use latest version 0.14.1 but before some time ago I had another old release and had same problem

**Comment by Neodymium5312** [comment]
Weirdly I'm still crashing with app UI error. On latest version of the app

**Comment by terrawarra** [comment]
in addition to my previous post..... when I tried to install the newer version v0.14.1,  it failed to install over the top of my existing older version of newpipe.
So, I then uninstalled the old version and the new version installed properly..

**Comment by michel90** [comment]
@terrawarra me too it failed to install over the top of my existing older version, anyway you could create a new issue to expose that problem in that way developers can organize issues better.

**Comment by theScrabi** [comment]
@Neodymium5312 is it the same error or is it a different one?

**Comment by Neodymium5312** [comment]
{
   "user_action": "ui error",
   "request": "App crash, UI failure",
   "content_language": "GB",
   "service": "none",
   "package": "org.schabi.newpipe",
   "version": "0.14.1",
   "os": "Linux motorola\/payton\/payton:8.1.0\/OPW28.46-21\/e3c72:user\/release-keys 8.1.0 - 27",
   "time": "2018-09-09 21:35",
   "exceptions": [
      "java.lang.NumberFormatException: For input string: \"\"\n\tat java.lang.Integer.parseInt(Integer.java:620)\n\tat java.lang.Integer.parseInt(Integer.java:643)\n\tat org.schabi.newpipe.util.ListHelper.compareVideoStreamResolution(ListHelper.java:396)\n\tat org.schabi.newpipe.util.ListHelper.computeDefaultResolution(ListHelper.java:113)\n\tat org.schabi.newpipe.util.ListHelper.getDefaultResolutionIndex(ListHelper.java:40)\n\tat org.schabi.newpipe.fragments.detail.VideoDetailFragment.setupActionBar(VideoDetailFragment.java:738)\n\tat org.schabi.newpipe.fragments.detail.VideoDetailFragment.handleResult(VideoDetailFragment.java:1204)\n\tat org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$startLoading$6$VideoDetailFragment(VideoDetailFragment.java:866)\n\tat org.schabi.newpipe.fragments.detail.VideoDetailFragment$$Lambda$5.accept(Unknown Source:4)\n\tat io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:63)\n\tat io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)\n\tat io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)\n\tat android.os.Handler.handleCallback(Handler.java:790)\n\tat android.os.Handler.dispatchMessage(Handler.java:99)\n\tat android.os.Looper.loop(Looper.java:164)\n\tat android.app.ActivityThread.main(ActivityThread.java:6545)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:809)\n"
   ],
   "user_comment": ""
}

**Comment by theScrabi** [comment]
@Neodymium5312
Pleas use the bug report converter.
Also this is a different issue.

**Comment by Neodymium5312** [comment]
It's the same issue. It's the exact same error that he was getting for the same version of the application. And honestly I don't know how to format it properly as I don't use github

**Comment by theScrabi** [comment]
@Neodymium5312 its not.

You have a NumberFormatException, while he has a NullpointerException. All I'm saying is that it might have been fixed form him, but not for you, so we now need to find out where your issue comes from :)

**Comment by terrawarra** [comment]
Oops..... I spoke too soon !
It's broken again !
I've switched to YouTube Pink in the meantime until newpipe is sorted !

**Comment by michel90** [comment]
@theScrabi  this is closed, that means this issue is fixed?

**Comment by theScrabi** [comment]
No its not sorry.

**Comment by theScrabi** [comment]
Though im still not able to reproduce it. Could somone create a video showing how to make it happen?

**Comment by rkaug27** [comment]
The Current Version NewPipe-v0.14.1 is worked well on my device...
