### ISSUE TITLE
UI failure

### ISSUE THREAD

**Issue by Umit-kokal** [TeamNewPipe/NewPipe#1687]
Hi all some one  know  about  it ?  

```
exceptions": [
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setVisibility(int)' on a null object reference 
at com.softmedya.streamyoutubeplayer.fragments.detail.VideoDetailFragment.handleResult(VideoDetailFragment.java:1217) 
at com.softmedya.streamyoutubeplayer.fragments.detail.VideoDetailFragment.lambda$startLoading$6$VideoDetailFragment(VideoDetailFragment.java:853) 
at com.softmedya.streamyoutubeplayer.fragments.detail.VideoDetailFragment$$Lambda$5.accept(Unknown Source) 
at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:63)
at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)\n\tat android.os.Handler.handleCallback(Handler.java:739) 
at android.os.Handler.dispatchMessage(Handler.java:95) 
at android.os.Looper.loop(Looper.java:234) 
at android.app.ActivityThread.main(ActivityThread.java:5526) 
t java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by theScrabi** [comment]
please tell us how to reproduce that bug. :)

**Comment by Umit-kokal** [comment]
This exception is thrown while attempting to connect a live stream.

**Comment by theScrabi** [comment]
Please post a link to an example live stream.

**Comment by Umit-kokal** [comment]
any live stream throws this error when i comment this line all his work

`detailControlsDownload.setVisibility(View.GONE);`

**Comment by theScrabi** [comment]
I can not not confirm. Latest version v0.14.1 works fine.

**Comment by Umit-kokal** [comment]
thks. can i ask, are  you  think about  made  auto play ?))

**Comment by theScrabi** [comment]
So i guess the issue is fixed then.

**Comment by theScrabi** [comment]
Auto play is implemented. Please open a new issue if there is something wrong with it. :)
