### ISSUE TITLE
Exception thrown when trying to play an open with intent

### ISSUE THREAD

**Issue by aaronwi** [TeamNewPipe/NewPipe#1696]
## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/embed/QqBmghaq-NE?list=PLPVve34yolHb_YVdmaXuIq2OQAeMz-8R9, opened with video_player
* __Content Language:__ GB
* __Service:__ YouTube
* __Version:__ 0.14.0
* __OS:__ Linux Android 7.0 - 24

```
org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor$DecryptException: Could not parse decrypt function 
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.loadDecryptionCode(YoutubeStreamExtractor.java:722)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:597)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:48)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:59)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:55)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3$ExtractorHelper(ExtractorHelper.java:113)
	at org.schabi.newpipe.util.ExtractorHelper$$Lambda$3.call(Unknown Source)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3310)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3310)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4073)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14349)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4073)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3310)
	at io.reactivex.internal.operators.single.SingleObserveOn.subscribeActual(SingleObserveOn.java:35)
	at io.reactivex.Single.subscribe(Single.java:3310)
	at io.reactivex.Single.subscribe(Single.java:3296)
	at org.schabi.newpipe.RouterActivity$FetcherService.handleChoice(RouterActivity.java:530)
	at org.schabi.newpipe.RouterActivity$FetcherService.onHandleIntent(RouterActivity.java:502)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: org.schabi.newpipe.extractor.utils.Parser$RegexException: failed to find pattern "(["\'])signature\1\s*,\s*([a-zA-Z0-9$]+)\(
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:63)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.loadDecryptionCode(YoutubeStreamExtractor.java:702)
	... 30 more

-------------------

```

**Comment by z3ntu** [comment]
Look at nearly every closed issue in this repo for the last 3 days. Install 0.14.1 from the GitHub releases or wait until F-Droid has built the update.

**Comment by aaronwi** [comment]
was not aware f-droid was not synced to github releases

**Comment by theScrabi** [comment]
No and we already have some discussion over at fdroid that we really need to speed up the update processes.
