### ISSUE TITLE
UI crashed touching back arrow icon /error report

### ISSUE THREAD

**Issue by michel90** [TeamNewPipe/NewPipe#1697]
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ GB
* __Service:__ none
* __Version:__ 0.14.1
* __OS:__ Linux Android 4.0.4 - 15

```
java.lang.NullPointerException
	at android.widget.Spinner.makeAndAddView(Spinner.java:394)
	at android.widget.Spinner.layout(Spinner.java:345)
	at android.widget.Spinner.onLayout(Spinner.java:309)
	at android.view.View.layout(View.java:11418)
	at android.view.ViewGroup.layout(ViewGroup.java:4328)
	at android.support.v7.widget.Toolbar.layoutChildLeft(Toolbar.java:1948)
	at android.support.v7.widget.Toolbar.onLayout(Toolbar.java:1887)
	at android.view.View.layout(View.java:11418)
	at android.view.ViewGroup.layout(ViewGroup.java:4328)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1652)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1510)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1415)
	at android.view.View.layout(View.java:11418)
	at android.view.ViewGroup.layout(ViewGroup.java:4328)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:443)
	at android.view.View.layout(View.java:11418)
	at android.view.ViewGroup.layout(ViewGroup.java:4328)
	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1171)
	at android.view.View.layout(View.java:11418)
	at android.view.ViewGroup.layout(ViewGroup.java:4328)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:443)
	at android.view.View.layout(View.java:11418)
	at android.view.ViewGroup.layout(ViewGroup.java:4328)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1652)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1510)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1415)
	at android.view.View.layout(View.java:11418)
	at android.view.ViewGroup.layout(ViewGroup.java:4328)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:443)
	at android.view.View.layout(View.java:11418)
	at android.view.ViewGroup.layout(ViewGroup.java:4328)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1652)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1510)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1415)
	at android.view.View.layout(View.java:11418)
	at android.view.ViewGroup.layout(ViewGroup.java:4328)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:443)
	at android.view.View.layout(View.java:11418)
	at android.view.ViewGroup.layout(ViewGroup.java:4328)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1489)
	at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2442)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4441)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
	at dalvik.system.NativeStart.main(Native Method)

-------------------

```
this always happens when I touch the arrow on the top left to go back, although the physical button to go back yes that works

**Comment by michel90** [comment]
maybe it's related to this [https://github.com/TeamNewPipe/NewPipe/issues/1680](url)
