### ISSUE TITLE
Popup video bug crash app

### ISSUE THREAD

**Issue by Brimont** [TeamNewPipe/NewPipe#1707]
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ IT
* __Service:__ none
* __Version:__ 0.14.1
* __OS:__ Linux Android 4.2.1 - 17

```
java.lang.NullPointerException
	at org.schabi.newpipe.player.PopupVideoPlayer$PopupWindowGestureListener.onTouch(PopupVideoPlayer.java:1070)
	at android.view.View.dispatchTouchEvent(View.java:7257)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2235)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1932)
	at android.view.View.dispatchPointerEvent(View.java:7442)
	at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3610)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3538)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4790)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4750)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4902)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:125)
	at android.os.Looper.loop(Looper.java:140)
	at android.app.ActivityThread.main(ActivityThread.java:5297)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(Native Method)

-------------------

```

**Comment by Coffeewithsnakes** [comment]
Same issue, 

Galaxy S9+
v0.14.1
Android v 8.0.0

**Comment by gkeegan** [comment]
What steps did you take to get this?

**Comment by Coffeewithsnakes** [comment]
Open NewPipe> Select any video > this error.

**Comment by theScrabi** [comment]
Im still not able to confirm.

**Comment by beNitinhere** [comment]
@Coffeewithsnakes did you try this in 0.14.2??

**Comment by diogogomes** [comment]
@beNitinhere, @theScrabi  I tested in 0.14.2 and I'm able to confirm the crash.

I tested with the video of NewPipe channel.

**Procedure:**
- Open the video in full screen
- Click to change to popup

**Error log:**

```
{
  "user_action": "ui error",
  "request": "App crash, UI failure",
  "content_language": "GB",
  "service": "none",
  "package": "org.schabi.newpipe",
  "version": "0.14.2",
  "os": "Linux Android 7.1.2 - 25",
  "time": "2019-01-16 18:38",
  "exceptions": [
    "java.lang.RuntimeException: Unable to stop activity {org.schabi.newpipe\/org.schabi.newpipe.player.MainVideoPlayer}: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.android.exoplayer2.SimpleExoPlayer.getPlaybackState()' on a null object reference
      at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4201)
      at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4257)
      at android.app.ActivityThread.-wrap6(ActivityThread.java)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1556)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:154)
      at android.app.ActivityThread.main(ActivityThread.java:6184)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.android.exoplayer2.SimpleExoPlayer.getPlaybackState()' on a null object reference
      at org.schabi.newpipe.player.BasePlayer.isPlaying(BasePlayer.java:1109)
      at org.schabi.newpipe.player.MainVideoPlayer.createPlayerState(MainVideoPlayer.java:252)
      at org.schabi.newpipe.player.MainVideoPlayer.onStop(MainVideoPlayer.java:237)
      at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1290)
      at android.app.Activity.performStop(Activity.java:6859)
      at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4196)
      ... 9 more
    java.lang.NullPointerException: Attempt to invoke virtual method 'int com.google.android.exoplayer2.SimpleExoPlayer.getPlaybackState()' on a null object reference
      at org.schabi.newpipe.player.BasePlayer.isPlaying(BasePlayer.java:1109)
      at org.schabi.newpipe.player.MainVideoPlayer.createPlayerState(MainVideoPlayer.java:252)
      at org.schabi.newpipe.player.MainVideoPlayer.onStop(MainVideoPlayer.java:237)
      at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1290)
      at android.app.Activity.performStop(Activity.java:6859)
      at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4196)
      at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4257)
      at android.app.ActivityThread.-wrap6(ActivityThread.java)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1556)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:154)
      at android.app.ActivityThread.main(ActivityThread.java:6184)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
      "
    ],
  "user_comment": ""
}
```

**Comment by beNitinhere** [comment]
Hey @diogogomes  , We have fixed it. This one will be not there in future releases
