### ISSUE TITLE
Requested Kiosk Exception Error in 0.14.1

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#1754]
Too deep to copy into FastHub-Libre from extractor. Here are a few frames from the trace:

## Exception
* __User Action:__ requested kiosk
* __Request:__ https://www.youtube.com/feed/trending
* __Content Language:__ GB
* __Service:__ YouTube
* __Version:__ 0.14.1
* __OS:__ Linux Android 8.1.0 - 27
Still working, but cannot find many HD with audio in this version of NewPipe.
```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get Duration: https://www.youtube.com/watch?v=XCQK6LmhYqc
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamInfoItemExtractor.getDuration(YoutubeStreamInfoItemExtractor.java:93)
	at org.schabi.newpipe.extractor.stream.StreamInfoItemsCollector.extract(StreamInfoItemsCollector.java:54)
	at org.schabi.newpipe.extractor.stream.StreamInfoItemsCollector.commit(StreamInfoItemsCollector.java:89)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeTrendingExtractor.getInitialPage(YoutubeTrendingExtractor.java:92)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)
	at org.schabi.newpipe.extractor.kiosk.KioskInfo.getInfo(KioskInfo.java:74)
	at org.schabi.newpipe.extractor.kiosk.KioskInfo.getInfo(KioskInfo.java:60)
```

**Comment by FlorianSteenbuck** [comment]
Add Description

**Comment by jhabdas** [comment]
Slow ya roll. ;)

**Comment by jhabdas** [comment]
Here are some more frames. The stack trace I got this time is several hundred frames long:

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get Duration: https://www.youtube.com/watch?v=6LKFTS-rZRU
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamInfoItemExtractor.getDuration(YoutubeStreamInfoItemExtractor.java:93)
	at org.schabi.newpipe.extractor.stream.StreamInfoItemsCollector.extract(StreamInfoItemsCollector.java:54)
	at org.schabi.newpipe.extractor.stream.StreamInfoItemsCollector.commit(StreamInfoItemsCollector.java:89)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeTrendingExtractor.getInitialPage(YoutubeTrendingExtractor.java:92)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)
```

Be useful to have a way to stream this into a reporter from XML within the app without going to JSON first, which I understand cannot be streamed easily.

**Comment by jhabdas** [comment]
Closing due to lack of response and emojis

**Comment by theScrabi** [comment]
:D lol
Try to search [Rita Ora - Let You Love Me](https://www.youtube.com/results?search_query=Rita+Ora+-+Let+You+Love+Me) in newpipe, and tell me if it still creates problems.
