### ISSUE TITLE
[mediaCCC] Scrolling to the end of search results causes crash

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipe#1966]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Search for something (e.g. "david") using the mediaCCC service and scroll to the end of the search results. To get the following crash, the search results must contain at least as many elements that the list is scrollable.

## Exception
* __User Action:__ searched
* __Request:__ david
* __Content Language:__ GB
* __Service:__ MediaCCC
* __Version:__ 0.14.2
* __OS:__ Linux ,release-keys 6.0 - 23

<details><summary><b>Crash log</b></summary><p>

```
java.lang.NullPointerException: The callable returned a null value
	at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

```
</p></details>
<hr>

**Comment by TobiGr** [comment]
#2083
