### ISSUE TITLE
Can't search

### ISSUE THREAD

**Issue by soenggam** [TeamNewPipe/NewPipe#1980]
Here is the log

  ## Exception
* __User Action:__ searched
* __Request:__ and
* __Content Language:__ GB
* __Service:__ YouTube
* __Version:__ 0.14.2
* __OS:__ Linux Android 5.1 - 22
undefined

<details><summary><b>Crash log</b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'org.jsoup.select.Elements org.jsoup.nodes.Element.children()' on a null object reference
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.collectItems(YoutubeSearchExtractor.java:115)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getInitialPage(YoutubeSearchExtractor.java:82)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:46)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:31)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$searchFor$0(ExtractorHelper.java:74)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$BBduYDeZ_vXMQYaemaggmTPtqvA.call(lambda)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

```
</p></details>
<hr>

**Comment by soenggam** [comment]
it keeps happening on my phone,I can search any video. Although I reinstall it,it is not still solved

**Comment by FaizKhan5** [comment]
Check 0.15.0

**Comment by sharljimhtsin** [comment]
> Check 0.15.0

it still exist @ version 0.15.1.

**Comment by theScrabi** [comment]
Which country are you trying to connect from?

**Comment by sharljimhtsin** [comment]
> Which country are you trying to connect from?

located at China Mainland, via proxy of HongKong.

**Comment by theScrabi** [comment]
Hm...
