### ISSUE TITLE
abnormal crash Newpipe 0.15.0

### ISSUE THREAD

**Issue by Brimont** [TeamNewPipe/NewPipe#2031]
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ IT
* __Service:__ none
* __Version:__ 0.15.0
* __OS:__ Linux Android 4.2.1 - 17

<details><summary><b>Crash log</b></summary><p>

```
java.lang.NullPointerException
	at us.shandian.giga.ui.adapter.MissionAdapter.setClearButtonVisibility(MissionAdapter.java:540)
	at us.shandian.giga.ui.adapter.MissionAdapter.onBindViewHolder(MissionAdapter.java:161)
	at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
	at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4194)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1670)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1528)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1441)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1670)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1528)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1441)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1670)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1528)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1441)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1670)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1528)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1441)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:14099)
	at android.view.ViewGroup.layout(ViewGroup.java:4464)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2183)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1947)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1139)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4879)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:776)
	at android.view.Choreographer.doCallbacks(Choreographer.java:579)
	at android.view.Choreographer.doFrame(Choreographer.java:548)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:762)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:153)
	at android.app.ActivityThread.main(ActivityThread.java:5297)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(Native Method)

```
</p></details>
<hr>

I have received this crash but the app work fine every time

**Comment by Brimont** [comment]
I have only this phone, but app work fine on my phone

**Comment by xdevelnet** [comment]
Check out relnotes: https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.15.0

```
drop support for android 4.1 - 4.3
```

**Comment by Brimont** [comment]
Android 4.1 and 4.2  have 1.2% and 1.9% of distribution and use
![780516](https://user-images.githubusercontent.com/42345179/51427800-0e788a00-1bfc-11e9-92ce-f3dc13a6d210.jpeg)
