### ISSUE TITLE
Soundcloud not working

### ISSUE THREAD

**Issue by hbarsaiyan** [TeamNewPipe/NewPipe#2058]
## Exception
* __User Action:__ searched
* __Request:__ hello
* __Content Language:__ GB
* __Service:__ SoundCloud
* __Version:__ 0.15.0
* __OS:__ Linux Android 9 - 28

<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get client id
	at org.schabi.newpipe.extractor.services.soundcloud.SoundcloudSearchQueryHandlerFactory.getUrl(SoundcloudSearchQueryHandlerFactory.java:52)
	at org.schabi.newpipe.extractor.linkhandler.ListLinkHandlerFactory.fromQuery(ListLinkHandlerFactory.java:38)
	at org.schabi.newpipe.extractor.linkhandler.SearchQueryHandlerFactory.fromQuery(SearchQueryHandlerFactory.java:29)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$searchFor$0(ExtractorHelper.java:77)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$BBduYDeZ_vXMQYaemaggmTPtqvA.call(Unknown Source:8)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: javax.net.ssl.SSLException: Read error: ssl=0x7ecdd33008: I/O error during system call, Connection reset by peer
	at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
	at com.android.org.conscrypt.NativeSsl.read(NativeSsl.java:399)
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:546)
	at okio.Okio$2.read(Okio.java:140)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:355)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227)
	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at org.schabi.newpipe.Downloader.getBody(Downloader.java:154)
	at org.schabi.newpipe.Downloader.download(Downloader.java:129)
	at org.schabi.newpipe.Downloader.download(Downloader.java:178)
	at org.schabi.newpipe.extractor.services.soundcloud.SoundcloudParsingHelper.clientId(SoundcloudParsingHelper.java:39)
	at org.schabi.newpipe.extractor.services.soundcloud.SoundcloudSearchQueryHandlerFactory.getUrl(SoundcloudSearchQueryHandlerFactory.java:45)
	... 15 more

```
</p></details>
<hr>

**Comment by TobiGr** [comment]
> javax.net.ssl.SSLException: Read error: ssl=0x7ecdd33008: I/O error during system call, Connection reset by peer

Hpw often do you get this exception? I can't reproduce this and this seems to be problem with SoundCloud. Might be related: https://stackoverflow.com/questions/30538640/javax-net-ssl-sslexception-read-error-ssl-0x9524b800-i-o-error-during-system
How fast was your internet at that moment?

**Comment by hbarsaiyan** [comment]
@TobiGr around 3mbps

**Comment by hbarsaiyan** [comment]
I tried different networks and different devices but every time I ran into the same issue.

**Comment by kapodamy** [comment]
The SSL certificate is not valid, is a soundcould problem. ¿have you tried to enter from a pc?

**Comment by nekobit1** [comment]
Works fine on my build. Probably is your network being funny. We should still write an exception for this, as technically, this isn't a bug, but an issue with the network (Like a toast to say: "Error fetching from SoundCloud Servers, check your connection")

**Comment by gkeegan** [comment]
Does it work if you use a VPN to a different country?

**Comment by hbarsaiyan** [comment]
@gkeegan yeah

**Comment by hbarsaiyan** [comment]
Please close this issue as the problem is related to my network and not the app. Apologies for the inconvenience caused.

**Comment by TobiGr** [comment]
No problem :)

@gkeegan and @kapodamy thanks for jumping in!

**Comment by gkeegan** [comment]
@hbarsaiyan No problem!
