### ISSUE TITLE
Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by essare** [TeamNewPipe/NewPipe#2065]
``` Log
# OS Version: 7.0
# Device: Galaxy A3(2016)
# RAM Free: 27.5%
# Disk Free: 43.7%

#0. Crashed: main
       at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2080)
       at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2106)
       at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:683)
       at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:637)
       at android.support.v4.app.DialogFragment.show(DialogFragment.java:144)
       at org.schabi.android.RouterActivity.lambda$openDownloadDialog$10$RouterActivity(RouterActivity.java:418)
       at org.schabi.android.RouterActivity$$Lambda$11.accept(Unknown Source)
       at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:63)
       at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
       at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)

--

Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2080)
       at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2106)
       at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:683)
       at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:637)
       at android.support.v4.app.DialogFragment.show(DialogFragment.java:144)
       at org.schabi.android.RouterActivity.lambda$openDownloadDialog$10$RouterActivity(RouterActivity.java:418)
       at org.schabi.android.RouterActivity$$Lambda$11.accept(Unknown Source)
       at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:63)
       at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
       at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)

**Comment by opusforlife2** [comment]
@essare Does this happen on 0.20.0?
