### ISSUE TITLE
Deleted playlist show up in "Bookmarked Playlist"-tab

### ISSUE THREAD

**Issue by connectety** [TeamNewPipe/NewPipe#2088]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.
## Exception
* __User Action:__ requested playlist
* __Request:__ https://www.youtube.com/playlist?list=PL0Joe-peBdGkQEnnc5mVmkysPksq4iIKI
* __Content Language:__ GB
* __Service:__ YouTube
* __Version:__ 0.15.1

### How To Reproduce:
1. Create a playlist on YouTube
2. Open playlist in NewPipe
3. Bookmark playlist in NewPipe
4. Delete playlist on YouTube
5. Open  "Bookmarked Playlist"-tab in NewPipe
6. **Notice the playlist is still visible in NewPipe**
7. (Try open deleted playlist)

<details><summary><b>Crash log (caused by opening deleted playlist)</b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get playlist name
    at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubePlaylistExtractor.getName(YoutubePlaylistExtractor.java:53)
    at org.schabi.newpipe.extractor.playlist.PlaylistInfo.getInfo(PlaylistInfo.java:48)
    at org.schabi.newpipe.extractor.playlist.PlaylistInfo.getInfo(PlaylistInfo.java:29)
    at org.schabi.newpipe.util.ExtractorHelper.lambda$getPlaylistInfo$6(ExtractorHelper.java:133)
    at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$VZ3nAAvIfeSqJNuSj0Lac16OssA.call(Unknown Source:4)
    at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
    at io.reactivex.Single.subscribe(Single.java:3438)
    at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
    at io.reactivex.Single.subscribe(Single.java:3438)
    at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
    at io.reactivex.Maybe.subscribe(Maybe.java:4154)
    at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
    at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
    at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
    at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
    at io.reactivex.Flowable.subscribe(Flowable.java:14479)
    at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
    at io.reactivex.Maybe.subscribe(Maybe.java:4154)
    at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
    at io.reactivex.Single.subscribe(Single.java:3438)
    at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
    at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
    at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
    at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    at java.lang.Thread.run(Thread.java:764)

```
</p></details>
<hr>

**Comment by connectety** [comment]
The Error itself is gone, but the UX is kinda bad.
"Content unavailable" does not necessarily mean as much as "The playlist does not exist." YouTube shows.
Also, there is still a report button.
But I know auto refreshing is a lot of work and I don't expect that...

So anyways I tried to, remove the playlist…

1. try: they little playlist add button does nothing.
2. try: Hamburger Menu > Add to playlist does uhm…
<details>
## Exception
* User Action: ui error
* Request: ACRA report
* Content Country: US
* Content Language: en-US
* App Language: en_US
* Service: none
* Version: 0.23.3
<summary><b>Crash log </b></summary><p>

```java
java.lang.NullPointerException:
 Attempt to invoke virtual method 'int org.schabi.newpipe.extractor.Info.getServiceId()' on a null object reference
 at org.schabi.newpipe.fragments.list.playlist.PlaylistFragment.getPlayQueue(PlaylistFragment.java:363)
 at org.schabi.newpipe.fragments.list.playlist.PlaylistFragment.getPlayQueue(PlaylistFragment.java:352)
 at org.schabi.newpipe.fragments.list.playlist.PlaylistFragment.onOptionsItemSelected(PlaylistFragment.java:244)
 at androidx.fragment.app.Fragment.performOptionsItemSelected(Fragment.java:3122)
 at androidx.fragment.app.FragmentManager.dispatchOptionsItemSelected(FragmentManager.java:3226)
 at androidx.fragment.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:416)
 at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:358)
 at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:264)
 at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
 at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
 at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:65)
 at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:208)
 at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
 at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
 at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
 at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
 at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
 at android.widget.AdapterView.performItemClick(AdapterView.java:376)
 at android.widget.AbsListView.performItemClick(AbsListView.java:1282)
 at android.widget.AbsListView$PerformClick.run(AbsListView.java:3558)
 at android.widget.AbsListView$3.run(AbsListView.java:4711)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:226)
 at android.os.Looper.loop(Looper.java:313)
 at android.app.ActivityThread.main(ActivityThread.java:8741)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

</details>
<hr>
3. You can infact remove it in the playlist overview.

**Comment by Shadow-302** [comment]
> But I kind of stopped caring about NewPipe... close this if you feel like it, or create another issue.

Using revanced now? Curious. 

<sub>Mod note: don't quote giant walls of text. Delete the irrelevant parts.</sub>
