### ISSUE TITLE
WebM muxer fails for some videos

### ISSUE THREAD

**Issue by DafabHoid** [TeamNewPipe/NewPipe#2114]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

The postprocessing of some downloaded WebM videos fails. 
One video where this reproducibly fails is https://www.youtube.com/watch?v=W5SdgWRxGsw
I tested at least 1080p and 480p.

The stack trace produced at 1080p is this:
```
02-10 23:16:01.204 30803  9084 E DownloadMission: Post-processing failed. algorithm = webm  args = [  ]
02-10 23:16:01.204 30803  9084 E DownloadMission: java.io.EOFException: parser go beyond limits of the Element. type=0xf43b675 offset=52866594 size=574621 position=98017261
02-10 23:16:01.204 30803  9084 E DownloadMission:       at org.schabi.newpipe.streams.WebMReader.ensure(WebMReader.java:212)
02-10 23:16:01.204 30803  9084 E DownloadMission:       at org.schabi.newpipe.streams.WebMReader.access$500(WebMReader.java:15)
02-10 23:16:01.204 30803  9084 E DownloadMission:       at org.schabi.newpipe.streams.WebMReader$Segment.getNextCluster(WebMReader.java:433)
02-10 23:16:01.204 30803  9084 E DownloadMission:       at org.schabi.newpipe.streams.WebMWriter.getNextBlockFrom(WebMWriter.java:350)
02-10 23:16:01.204 30803  9084 E DownloadMission:       at org.schabi.newpipe.streams.WebMWriter.build(WebMWriter.java:227)
02-10 23:16:01.204 30803  9084 E DownloadMission:       at us.shandian.giga.postprocessing.WebMMuxer.process(WebMMuxer.java:37)
02-10 23:16:01.204 30803  9084 E DownloadMission:       at us.shandian.giga.postprocessing.Postprocessing.run(Postprocessing.java:103)
02-10 23:16:01.204 30803  9084 E DownloadMission:       at us.shandian.giga.get.DownloadMission.doPostprocessing(DownloadMission.java:612)
02-10 23:16:01.204 30803  9084 E DownloadMission:       at us.shandian.giga.get.DownloadMission.notifyFinished(DownloadMission.java:379)
02-10 23:16:01.204 30803  9084 E DownloadMission:       at us.shandian.giga.get.DownloadRunnable.run(DownloadRunnable.java:176)
02-10 23:16:01.207 30803  9084 E DownloadMission: notifyError() code = 1007
```

On 480p it is quite similar:
```
02-10 23:22:45.460 30803 12960 E DownloadMission: Post-processing failed. algorithm = webm  args = [  ]
02-10 23:22:45.460 30803 12960 E DownloadMission: java.io.EOFException: parser go beyond limits of the Element. type=0xf43b675 offset=14396281 size=154168 position=130246593
02-10 23:22:45.460 30803 12960 E DownloadMission:       at org.schabi.newpipe.streams.WebMReader.ensure(WebMReader.java:212)
02-10 23:22:45.460 30803 12960 E DownloadMission:       at org.schabi.newpipe.streams.WebMReader.access$500(WebMReader.java:15)
[same as above]
```

It also fails for https://www.youtube.com/watch?v=ark3tT2WPSw with the same stack trace.

Version tested: 0.15.1
Android Version: 8.1

**Comment by theScrabi** [comment]
Confirmed. @kaptogamy could you please use the NewPipe native error reporter. It is more usefull and displays the whole stacktrace and has the abillity to report to sentry.schabi.org.

[](https://i.imgur.com/ogFn7he.png)

**Comment by kapodamy** [comment]
@theScrabi ok
