### ISSUE TITLE
Error when selecting channel from commends

### ISSUE THREAD

**Issue by theScrabi** [TeamNewPipe/NewPipe#2143]
So I encountered the first bug in [commends support](). Some chnnels you can select from the commends end up in having a stacktrace. Somehow these channels use a different URL format. This case should be handled in order not to make the app crash.

I suggest to transform the url. So if you get a url like `https://youtube.com/calligraphymasters` add a `usrer/` in the middle so it looks like this `https://youtube.com/user/calligraphymasters`.

@yausername please fix this before we can release the next version.

![cut mp4](https://user-images.githubusercontent.com/1891273/53284867-2e025580-375a-11e9-95a9-da0842af9009.gif)

## Exception
* __User Action:__ requested channel
* __Request:__ https://youtube.com/calligraphymasters
* __Content Language:__ DE
* __Service:__ YouTube
* __Version:__ 0.15.1
* __OS:__ Linux Android 8.1.0 - 27

<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Malformed unacceptable url: https://youtube.com/calligraphymasters
	at org.schabi.newpipe.extractor.linkhandler.LinkHandlerFactory.fromUrl(LinkHandlerFactory.java:43)
	at org.schabi.newpipe.extractor.linkhandler.ListLinkHandlerFactory.fromUrl(ListLinkHandlerFactory.java:27)
	at org.schabi.newpipe.extractor.StreamingService.getChannelExtractor(StreamingService.java:280)
	at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:47)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getChannelInfo$4(ExtractorHelper.java:123)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$u5W7VszTe8AoEexIsFM9huQfbkM.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

```
</p></details>
<hr>

**Comment by yausername** [comment]
transforming the url does not work always.
for https://www.youtube.com/jpltoyexperience neither https://www.youtube.com/user/jpltoyexperience  nor this https://www.youtube.com/channel/jpltoyexperience exist
but luckily we have a way to fetch the channel id https://www.youtube.com/channel/UCQTOFh22Pl3p81Z4KlufVCg
PR is open https://github.com/TeamNewPipe/NewPipeExtractor/pull/141
Thanks
