### ISSUE TITLE
Every 144p and 240p MPEG downloads failed ("Error")

### ISSUE THREAD

**Issue by Symbian9** [TeamNewPipe/NewPipe#2173]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

### Actual behavior

Every video download with "MPEG-4 144p" or "MPEG-4 240p" format failed at the end of downloading.

But if set "MPEG-4 360p" or higher it downloaded correctly.

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ GB
* __Service:__ none
* __Version:__ 0.16.0
* __OS:__ Linux Android 5.1.1 - 22

<details><summary><b>Crash log</b></summary><p>

```
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at android.support.v7.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:555)
	at android.support.v7.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:518)
	at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:466)
	at android.support.v7.app.AppCompatDialog.setContentView(AppCompatDialog.java:94)
	at android.support.v7.app.AlertController.installContent(AlertController.java:232)
	at android.support.v7.app.AlertDialog.onCreate(AlertDialog.java:279)
	at android.app.Dialog.dispatchOnCreate(Dialog.java)
	at android.app.Dialog.show(Dialog.java)
	at us.shandian.giga.ui.adapter.MissionAdapter.showError(MissionAdapter.java:438)
	at us.shandian.giga.ui.adapter.MissionAdapter.handlePopupItem(MissionAdapter.java:466)
	at us.shandian.giga.ui.adapter.MissionAdapter.access$200(MissionAdapter.java:68)
	at us.shandian.giga.ui.adapter.MissionAdapter$ViewHolderItem.lambda$buildPopup$2(MissionAdapter.java:700)
	at us.shandian.giga.ui.adapter.-$$Lambda$MissionAdapter$ViewHolderItem$WMTXzvtjV6uhlyLXNG5QCw_ELrY.onMenuItemClick(lambda)
	at android.widget.PopupMenu.onMenuItemSelected(PopupMenu.java)
	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java)
	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java)
	at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java)
	at android.widget.AdapterView.performItemClick(AdapterView.java)
	at android.widget.AbsListView.performItemClick(AbsListView.java)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java)
	at android.widget.AbsListView$3.run(AbsListView.java)
	at android.os.Handler.handleCallback(Handler.java)
	at android.os.Handler.dispatchMessage(Handler.java)
	at android.os.Looper.loop(Looper.java)
	at android.app.ActivityThread.main(ActivityThread.java)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)

```
</p></details>
<hr>

**Comment by Symbian9** [comment]
UPD: Crash log just added
