### ISSUE TITLE
Update check crashes on startup

### ISSUE THREAD

**Issue by snappyapple632** [TeamNewPipe/NewPipe#2197]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [X] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Title.

Crash report: 

## Exception
* __User Action:__ something
* __Request:__ could not parse app update JSON data
* __Content Language:__ US
* __Service:__ none
* __Version:__ 0.16.0
* __OS:__ Linux lge/lucye_nao_us/lucye:8.0.0/OPR1.170623.032/182541455e902:user/release-keys 8.0.0 - 26

<details><summary><b>Crash log</b></summary><p>

```
org.json.JSONException: Value <html><title>500 of type java.lang.String cannot be converted to JSONObject
	at org.json.JSON.typeMismatch(JSON.java:111)
	at org.json.JSONObject.<init>(JSONObject.java:163)
	at org.json.JSONObject.<init>(JSONObject.java:176)
	at org.schabi.newpipe.CheckForNewAppVersionTask.onPostExecute(CheckForNewAppVersionTask.java:104)
	at org.schabi.newpipe.CheckForNewAppVersionTask.onPostExecute(CheckForNewAppVersionTask.java:46)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.-wrap1(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6710)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)

```
</p></details>
<hr>

**Comment by TobiGr** [comment]
The [API](https://newpipe.schabi.org/api/data.json) is up again and works properly. Did the app crash or did you only get a warning via the snackbar? If the app crashes, we should change that.

**Comment by snappyapple632** [comment]
The app showed the crash on startup, but pressing the back button returned me to NewPipe. The error doesn't seem to be showing up anymore, so I'm assuming it was an API issue. I will be closing this.

**Comment by TobiGr** [comment]
@theScrabi @TheAssassin  IMO, we should try to show the error snackbar because this is not a critical error. I am considering to suppress warnings caused by the API not running properly.

**Comment by TheAssassin** [comment]
We don't have any kind of SLA right now for the API, downtimes are to be expected. Like @TobiGr suggests, IMO the app should tolerate API errors.

**Comment by test2a** [comment]
@theassasin I had mentioned a similar thing a week or so ago somewhere.

Apparently, Newpipe DOES not ask for or check if the user has already allowed display floating window permission.
If it is allowed, popup works. If not, the app crashes without telling the user.

**Comment by theScrabi** [comment]
That is new to me. Every time i start floating without having it enabled newpipe sends me to the corespomding system settings.
