### ISSUE TITLE
🔥 v0.16.1 Could not get web page url for the video

### ISSUE THREAD

**Issue by essare** [TeamNewPipe/NewPipe#2224]
_Every time i try to search a term a Snackbar appears and the result are only channels no videos and some time it shows "No results" (see screenshots)
PS: this happens on all my devices ( 5 devices - android 5 to 8 )_
PS2: I've updated the issue with the BugReport importer (Sorry for that)
## Exception
* __User Action:__ searched
* __Request:__ google
* __Content Language:__ US
* __Service:__ YouTube
* __Version:__ 0.16.1
* __OS:__ Linux Android 7.0 - 24
undefined

<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get web page url for the video
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamInfoItemExtractor.getUrl(YoutubeStreamInfoItemExtractor.java:68)
	at org.schabi.newpipe.extractor.stream.StreamInfoItemsCollector.extract(StreamInfoItemsCollector.java:45)
	at org.schabi.newpipe.extractor.search.InfoItemsSearchCollector.extract(InfoItemsSearchCollector.java:63)
	at org.schabi.newpipe.extractor.search.InfoItemsSearchCollector.extract(InfoItemsSearchCollector.java:47)
	at org.schabi.newpipe.extractor.InfoItemsCollector.commit(InfoItemsCollector.java:87)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.collectItems(YoutubeSearchExtractor.java:134)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getInitialPage(YoutubeSearchExtractor.java:82)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:20)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:51)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:31)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$searchFor$0(ExtractorHelper.java:77)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$Q2irADd3WozqQtYQpur_mvdiGSc.call(lambda)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: org.jsoup.select.Selector$SelectorParseException: Did not find balanced marker at 'class*="yt-lockup-video"'
	at org.jsoup.select.QueryParser.parse(QueryParser.java:44)
	at org.jsoup.select.Selector.select(Selector.java:91)
	at org.jsoup.nodes.Element.select(Element.java:363)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamInfoItemExtractor.getUrl(YoutubeStreamInfoItemExtractor.java:64)
	... 22 more

```
</p></details>
<hr>

+ Screen shots
[https://imgur.com/eGchsig](url)
[https://imgur.com/lhScwVf](url)

**Comment by theScrabi** [comment]
Please use the bugreport importer.

**Comment by WiiliamChik** [comment]
i have the same problem
