### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by burneracc69** [TeamNewPipe/NewPipe#2231]
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

## Exception
* __User Action:__ something
* __Request:__ could not parse app update JSON data
* __Content Language:__ GB
* __Service:__ none
* __Version:__ 0.16.1
* __OS:__ Linux Android 8.1.0 - 27

<details><summary><b>Crash log</b></summary><p>

```
org.json.JSONException: Value <html><title>500 of type java.lang.String cannot be converted to JSONObject
	at org.json.JSON.typeMismatch(JSON.java:111)
	at org.json.JSONObject.<init>(JSONObject.java:163)
	at org.json.JSONObject.<init>(JSONObject.java:176)
	at org.schabi.newpipe.CheckForNewAppVersionTask.onPostExecute(CheckForNewAppVersionTask.java:104)
	at org.schabi.newpipe.CheckForNewAppVersionTask.onPostExecute(CheckForNewAppVersionTask.java:46)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.-wrap1(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)

```
</p></details>
<hr>

**Comment by theScrabi** [comment]
Give further description and change the title of the issue.

**Comment by burneracc69** [comment]
I closed newpipe competely. Pressed a yt link in another app and chose show info and it crashed.

**Comment by TobiGr** [comment]
@theScrabi That was an web API bug. We need to ignore them as discussed earlier.

**Comment by theScrabi** [comment]
Yea... I see. Well the next version will fix showing the error when no netwoek connection is available.

**Comment by theScrabi** [comment]
We may not want to show this error at all, and just get notified through some other channel if the api service is not available.
