### ISSUE TITLE
Another error, bug.

### ISSUE THREAD

**Issue by burneracc69** [TeamNewPipe/NewPipe#2241]
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

No idea what happened, I opened the app and it crashed.

## Exception
* __User Action:__ something
* __Request:__ could not parse app update JSON data
* __Content Language:__ GB
* __Service:__ none
* __Version:__ 0.16.1
* __OS:__ Linux Android 8.1.0 - 27

<details><summary><b>Crash log</b></summary><p>

```
org.json.JSONException: Value <html><title>500 of type java.lang.String cannot be converted to JSONObject
	at org.json.JSON.typeMismatch(JSON.java:111)
	at org.json.JSONObject.<init>(JSONObject.java:163)
	at org.json.JSONObject.<init>(JSONObject.java:176)
	at org.schabi.newpipe.CheckForNewAppVersionTask.onPostExecute(CheckForNewAppVersionTask.java:104)
	at org.schabi.newpipe.CheckForNewAppVersionTask.onPostExecute(CheckForNewAppVersionTask.java:46)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.-wrap1(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)

```
</p></details>
<hr>

**Comment by burneracc69** [comment]
No, sorry. It didnt crash crash.. Like quitting the app, I just an error popup... Then I could just press the back button and load my subscriptions like normal

**Comment by TobiGr** [comment]
API, running correctly now, see #2197

**Comment by burneracc69** [comment]
Are you saying its fixed? Cuz its not.. Its far from fixed. I still get this crash everytime i reopen the app

**Comment by TobiGr** [comment]
The API as runnning properly the moment I closed this ticket. @TheAssassin Can you please take a look at why the API has the 500 code again?

**Comment by TobiGr** [comment]
@burneracc69 To fix this temporarily, you can disable the update check in the settings

**Comment by TheAssassin** [comment]
I have no clue, but our healthcheck also seems to be broken:

```sh
# (inside Docker container)
/ $ curl -f http://localhost:3000/data.json
<html><title>500: OK</title><body>500: OK</body></html>/ $ echo $?
0
```

Something is broken with that check, it seems. Although `500: OK` is definitely also broken. I assume the container doesn't forward the `500` status.

It seems the API is working again out of sudden, though.

**Comment by TheAssassin** [comment]
After tinkering with the code a bit, I am pretty sure the issue is that `500: OK` is a 200 response although there was some sort of error. The question is, how is this behavior caused? @TobiGr any ideas?

**Comment by burneracc69** [comment]
Yeah it's fine now again. I dont get the crash anymore. :P

**Comment by TobiGr** [comment]
@theAssassian tbh, I have no idea.
