### ISSUE TITLE
ExoPlayer memory leak

### ISSUE THREAD

**Issue by nv95** [TeamNewPipe/NewPipe#2257]
I noticed one problem, the allocated video memory is increased after seeking playback position.

![Screenshot_20190331_183423](https://user-images.githubusercontent.com/8948226/55291150-faaf8800-53e3-11e9-9ef4-8adf844fce61.png)
This bug available only on one of my devices. I found [this](https://github.com/google/ExoPlayer/issues/5151). Look like this is a internal bug of ExoPlayer, but I`m not sure. Are anyone has the same problem?

**Comment by raihanabbas232** [comment]
nv95 I am also facing this problem.
![Untitled](https://user-images.githubusercontent.com/30410006/55626116-1213ba00-57c4-11e9-9a70-fffcd9aad7e5.jpg) 
Is there any update regarding to this issue?
I am using Exoplayer v2.9.6
Thanks

**Comment by potatoker** [comment]
I do not operate seek， but I still found there are lot of memory allocated to allocationnode when I scroll the video list. I'm sure that I've released the player when the textureview is out of screen. But I still often get OOM problem.

![image](https://user-images.githubusercontent.com/5286501/59673055-37289e00-91f3-11e9-96ed-23f92cd14522.png)

really confused about the oom in video list.

anyone can help? thanks

**Comment by Yowlen** [comment]
Interesting. I had already figured out how the memory leak works elsewhere, but I didn't even think of seeking within the same video being a potential cause for it too. Nice find.

**Comment by opusforlife2** [comment]
@Redirion You said in your PR

> This might close

So Github automatically tagged this for closing. Reopening it.

@Yowlen Could you try this as well in 0.20.0?

**Comment by litetex** [comment]
I think we can close this or?

**Comment by nv95** [comment]
Can't check if it's relevant now because it only reproduced on only one of my devices which is now broken.

**Comment by litetex** [comment]
Okay the I guess we can close it and reopen/create a new issue if it's relevant again.

**Comment by IriaSomobu** [comment]
Apparently I can reproduce this issue on certain (that lasts 6+ hours) youtube videos.

<details>
<summary>Exception</summary>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected OutOfMemoryError: Failed to allocate a 65548 byte allocation with 26040 free bytes and 25KB until OOM
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:446)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 65548 byte allocation with 26040 free bytes and 25KB until OOM
	at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:104)
	at com.google.android.exoplayer2.source.SampleDataQueue.preAppend(SampleDataQueue.java:240)
	at com.google.android.exoplayer2.source.SampleDataQueue.sampleData(SampleDataQueue.java:174)
	at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:579)
	at com.google.android.exoplayer2.extractor.TrackOutput$-CC.$default$sampleData(TrackOutput.java:159)
	at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java)
	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:615)
	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:249)
	at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
	at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1049)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
	... 3 more
```

</details>

**Comment by opusforlife2** [comment]
@IriaSomobu Please open a new issue with full details.
