### ISSUE TITLE
"Kore app not found. Would you like to install it?"

### ISSUE THREAD

**Issue by benjo2000** [TeamNewPipe/NewPipe#226]
Hi,
i think i've found a bug in the "play with kodi"-feature.
When i search a video within newpipe i can play it on my kodi installation without problems via the "play with kodi" button in context menu. 
When i open a youtube link from the "open with" dialog in whatsapp or signal, i get to the correct youtube-video in newpipe, but when i try to send it to kodi with the "play with kodi"-button in conetxt-menu, newpipe claims, that kore app is not installed.   However, when i choose "share" and "play with kodi", it works.
Here's a log, i hope it helps.
Thanks for that wonderful app.
`V/WindowManager( 2961): Adding window Window{dc1093b u0 PopupWindow:152f1d99} at 7 of 12 (after Window{1b843480 u0 org.schabi.newpipe/org.schabi.newpipe.VideoItemDetailActivity})
I/libblt_hw( 1687): Library opened (handle = 7, fd = 73)
D/TrafficView( 4211): 947130,947130;21292079,21292455;49498677,49499695;0,369
D/TrafficView( 4211): 947130,947130;21292455,21292455;49499695,49500715;0,0
I/ActivityManager( 2961): START u0 {act=android.intent.action.VIEW dat=http://youtu.be/mapWRFAqrd8 pkg=org.xbmc.kore} from uid 10162 on display 0
W/System.err(26347): android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=http://youtu.be/mapWRFAqrd8 pkg=org.xbmc.kore }
W/System.err(26347):    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1781)
W/System.err(26347):    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1501)
W/System.err(26347):    at android.app.Activity.startActivityForResult(Activity.java:3745)
W/System.err(26347):    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
W/System.err(26347):    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:681)
W/System.err(26347):    at android.app.Activity.startActivityForResult(<Xposed>)
W/System.err(26347):    at android.app.Activity.startActivityForResult(Activity.java:3706)
W/System.err(26347):    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
W/System.err(26347):    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:681)
W/System.err(26347):    at android.app.Activity.startActivityForResult(<Xposed>)
W/System.err(26347):    at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:784)
W/System.err(26347):    at android.app.Activity.startActivity(Activity.java:4016)
W/System.err(26347):    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
W/System.err(26347):    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:681)
W/System.err(26347):    at android.app.Activity.startActivity(<Xposed>)
W/System.err(26347):    at android.app.Activity.startActivity(Activity.java:3984)
W/System.err(26347):    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
W/System.err(26347):    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:681)
W/System.err(26347):    at android.app.Activity.startActivity(<Xposed>)
W/System.err(26347):    at org.schabi.newpipe.VideoItemDetailFragment$8.onActionSelected(VideoItemDetailFragment.java:459)
W/System.err(26347):    at org.schabi.newpipe.ActionBarHandler.onItemSelected(ActionBarHandler.java:174)
W/System.err(26347):    at org.schabi.newpipe.VideoItemDetailFragment.onOptionsItemSelected(VideoItemDetailFragment.java:844)
W/System.err(26347):    at org.schabi.newpipe.VideoItemDetailActivity.onOptionsItemSelected(VideoItemDetailActivity.java:146)
W/System.err(26347):    at android.app.Activity.onMenuItemSelected(Activity.java:2885)
W/System.err(26347):    at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:361)
W/System.err(26347):    at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:147)
W/System.err(26347):    at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
W/System.err(26347):    at android.support.v7.app.AppCompatDelegateImplV7.onMenuItemSelected(AppCompatDelegateImplV7.java:620)
W/System.err(26347):    at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
W/System.err(26347):    at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
W/System.err(26347):    at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
W/System.err(26347):    at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
W/System.err(26347):    at android.support.v7.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:191)
W/System.err(26347):    at android.widget.AdapterView.performItemClick(AdapterView.java:305)
W/System.err(26347):    at android.widget.AbsListView.performItemClick(AbsListView.java:1146)
W/System.err(26347):    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3053)
W/System.err(26347):    at android.widget.AbsListView.onTouchUp(AbsListView.java:3872)
W/System.err(26347):    at android.widget.AbsListView.onTouchEvent(AbsListView.java:3637)
W/System.err(26347):    at android.support.v7.widget.ListViewCompat.onTouchEvent(ListViewCompat.java:120)
W/System.err(26347):    at android.view.View.dispatchTouchEvent(View.java:8471)
W/System.err(26347):    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2399)
W/System.err(26347):    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2092)
W/System.err(26347):    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2405)
W/System.err(26347):    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106)
W/System.err(26347):    at android.widget.PopupWindow$PopupViewContainer.dispatchTouchEvent(PopupWindow.java:1731)
W/System.err(26347):    at android.view.View.dispatchPointerEvent(View.java:8666)
W/System.err(26347):    at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4123)
W/System.err(26347):    at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3989)
W/System.err(26347):    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
W/System.err(26347):    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
W/System.err(26347):    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
W/System.err(26347):    at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3680)
W/System.err(26347):    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
W/System.err(26347):    at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3737)
W/System.err(26347):    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
W/System.err(26347):    at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3597)
W/System.err(26347):    at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3563)
W/System.err(26347):    at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3571)
W/System.err(26347):    at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3544)
W/System.err(26347):    at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5807)
W/System.err(26347):    at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5781)
W/System.err(26347):    at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5752)
W/System.err(26347):    at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5897)
W/System.err(26347):    at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
W/System.err(26347):    at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(26347):    at android.os.MessageQueue.next(MessageQueue.java:143)
W/System.err(26347):    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
W/System.err(26347):    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:681)
W/System.err(26347):    at android.os.MessageQueue.next(<Xposed>)
W/System.err(26347):    at android.os.Looper.loop(Looper.java:122)
W/System.err(26347):    at android.app.ActivityThread.main(ActivityThread.java:5254)
W/System.err(26347):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(26347):    at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err(26347):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
W/System.err(26347):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
W/System.err(26347):    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
I/AppCompatDelegate(26347): The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
V/WindowManager( 2961): not Base app: Adding window Window{24ec5db1 u0 org.schabi.newpipe/org.schabi.newpipe.VideoItemDetailActivity} at 8 of 13
W/InputEventReceiver(26347): Attempted to finish an input event but the input event receiver has already been disposed.
I/libblt_hw( 1687): Library opened (handle = 8, fd = 75)
I/libblt_hw( 1687): Library closed (handle = 7, fd = 73)`

My device: 
Samsung Galaxy SIII Mini
runs without gapps and with marvin's microg-framework

**Comment by theScrabi** [comment]
Ew am I supposed to read that log xD. Please use a paste bin the next time you paste code.

**Comment by theScrabi** [comment]
Ok, I changed something.
Before opening kore newpipe now translates urls like: "http://youtu.be/mapWRFAqrd8" into this "https://www.youtube.com/watch?v=mapWRFAqrd8" which is better.

**Comment by benjo2000** [comment]
Thanks, and sorry for the log flood.

**Comment by MyLogins** [comment]
Please reopen this issue, its still (or again) existing.
