### ISSUE TITLE
[NewPipe][v0.16.1]Exeption happen if i open the app without data connection.

### ISSUE THREAD

**Issue by maaudrana** [TeamNewPipe/NewPipe#2316]
<h4>Actual behavior</h4>
App showing error if i open the without data connection for first time.
<h4>Expected behavior</h4>
Expected that i can open the app without seeing the error.
<h4>How to reproduce</h4>
<ol>
<li>Install the apps and close data connection</li>
<li>open the app</li>
<li>see error</li>
</ol>
<h4>Information</h4>
<ul>
<li>App version:V0.16.1</li>
<li>OS:Android 9.0</li>
<li>Device:Samsung A10</li>
</ul>
<h4>Recording Of The Bug</h4>
<a href="https://youtu.be/-g6Sh2tDlCY">https://youtu.be/-g6Sh2tDlCY</a>
<h4>Logcat</h4>
<pre>
<code>
java.net.UnknownHostException: Unable to resolve host \"newpipe.schabi.org\": No address associated with hostnamet
at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:157)
at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:105)
at java.net.InetAddress.getAllByName(InetAddress.java:1154)
at okhttp3.Dns$1.lookup(Dns.java:40)
at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214)
at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)\n\tat okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
at okhttp3.RealCall.execute(RealCall.java:77)\n\tat org.schabi.newpipe.CheckForNewAppVersionTask.doInBackground(CheckForNewAppVersionTask.java:86)
at org.schabi.newpipe.CheckForNewAppVersionTask.doInBackground(CheckForNewAppVersionTask.java:46)\n\tat android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)\nCaused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
at libcore.io.Linux.android_getaddrinfo(Native Method)
at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:172)
at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:137)\n\t... 30 more
</code>
</pre>
Please add bug lebel if this issue is valid.tnx

**Comment by Redirion** [comment]
This is fixed in the upcoming 0.16.2. Please test it.

**Comment by maaudrana** [comment]
Thank you its working  fine now.
