### ISSUE TITLE
6 Logs / 3 Leaks

### ISSUE THREAD

**Issue by takid2848** [TeamNewPipe/NewPipe#2362]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

All of these logs were appeared in android 6.0 / builded 21 hours ago.

1. Leaks.
![Screenshot_20190528-000251](https://user-images.githubusercontent.com/31562186/58427994-344af980-80dc-11e9-87e1-0058d6dfea77.png)

Maybe 2nd and the 3rd one appeared because of low space;

Here's the file (sdcard/leaks...) the size is too big, so I uploaded to another site.

This file will be delete after 30 days.

[https://tmpstorage.com/download/yxn5pbdyos](https://tmpstorage.com/download/yxn5pbdyos)

<br>
2. Logs(5)

<hr>

[Log01.txt](https://github.com/TeamNewPipe/NewPipe/files/3224273/Log01.txt)

## Exception
* __User Action:__ searched
* __Request:__ little busters
* __Content Language:__ GB
* __Service:__ YouTube
* __Version:__ 0.16.0
* __OS:__ Linux Android 6.0.1 - 23
search 'little bustets' and view playlists.

<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Failed to extract playlist url
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubePlaylistInfoItemExtractor.getUrl(YoutubePlaylistInfoItemExtractor.java:65)
	at org.schabi.newpipe.extractor.playlist.PlaylistInfoItemsCollector.extract(PlaylistInfoItemsCollector.java:17)
	at org.schabi.newpipe.extractor.search.InfoItemsSearchCollector.extract(InfoItemsSearchCollector.java:67)
	at org.schabi.newpipe.extractor.search.InfoItemsSearchCollector.extract(InfoItemsSearchCollector.java:47)
	at org.schabi.newpipe.extractor.InfoItemsCollector.commit(InfoItemsCollector.java:87)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.collectItems(YoutubeSearchExtractor.java:139)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getInitialPage(YoutubeSearchExtractor.java:82)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:20)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:51)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:31)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$searchFor$0(ExtractorHelper.java:77)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$BBduYDeZ_vXMQYaemaggmTPtqvA.call(lambda)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.attr(java.lang.String)' on a null object reference
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubePlaylistInfoItemExtractor.getUrl(YoutubePlaylistInfoItemExtractor.java:56)
	... 23 more

```
</p></details>
<hr>

[Log02.txt](https://github.com/TeamNewPipe/NewPipe/files/3224274/Log02.txt)

## Exception
* __User Action:__ requested stream
* __Request:__ https://soundcloud.com/billiummoto/hdhr
* __Content Language:__ GB
* __Service:__ SoundCloud
* __Version:__ 0.16.0
* __OS:__ Linux Android 6.0.1 - 23
appears sometimes..

<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.attr(java.lang.String)' on a null object reference
	at org.schabi.newpipe.extractor.services.soundcloud.SoundcloudStreamLinkHandlerFactory.getUrl(SoundcloudStreamLinkHandlerFactory.java:25)
	at org.schabi.newpipe.extractor.linkhandler.LinkHandlerFactory.fromUrl(LinkHandlerFactory.java:47)
	at org.schabi.newpipe.extractor.StreamingService.getStreamExtractor(StreamingService.java:288)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:59)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(lambda)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.attr(java.lang.String)' on a null object reference
	at org.schabi.newpipe.extractor.services.soundcloud.SoundcloudParsingHelper.resolveUrlWithEmbedPlayer(SoundcloudParsingHelper.java:104)
	at org.schabi.newpipe.extractor.services.soundcloud.SoundcloudStreamLinkHandlerFactory.getUrl(SoundcloudStreamLinkHandlerFactory.java:23)
	... 30 more

```
</p></details>
<hr>

[Log03.txt](https://github.com/TeamNewPipe/NewPipe/files/3224275/Log03.txt)

## Exception
* __User Action:__ something
* __Request:__ null
* __Content Language:__ GB
* __Service:__ none
* __Version:__ 0.16.0
* __OS:__ Linux Android 6.0.1 - 23
share the second log to newpipe

<details><summary><b>Crash log</b></summary><p>

```
java.lang.IllegalArgumentException: The given URL is not valid
	at org.schabi.newpipe.extractor.services.youtube.linkHandler.YoutubeStreamLinkHandlerFactory.getId(YoutubeStreamLinkHandlerFactory.java:78)
	at org.schabi.newpipe.extractor.services.youtube.linkHandler.YoutubeStreamLinkHandlerFactory.onAcceptUrl(YoutubeStreamLinkHandlerFactory.java:182)
	at org.schabi.newpipe.extractor.linkhandler.LinkHandlerFactory.acceptUrl(LinkHandlerFactory.java:63)
	at org.schabi.newpipe.extractor.StreamingService.getLinkTypeByUrl(StreamingService.java:311)
	at org.schabi.newpipe.extractor.NewPipe.getServiceByUrl(NewPipe.java:75)
	at org.schabi.newpipe.RouterActivity.lambda$handleUrl$0(RouterActivity.java:135)
	at org.schabi.newpipe.-$$Lambda$RouterActivity$jGbV3sDp3V_oonJa1z1jLD1TKkg.call(lambda)
	at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:43)
	at io.reactivex.Observable.subscribe(Observable.java:12090)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

```
</p></details>
<hr>

[Log04.txt](https://github.com/TeamNewPipe/NewPipe/files/3224276/Log04.txt)

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ GB
* __Service:__ none
* __Version:__ 0.16.0
* __OS:__ Linux Android 6.0.1 - 23
I turn off the phone 4 hours;

<details><summary><b>Crash log</b></summary><p>

```
java.util.concurrent.TimeoutException: com.android.internal.os.BinderInternal$GcWatcher.finalize() timed out after 10 seconds
	at java.lang.System.log(Native Method)
	at java.lang.System.logE(System.java:1090)
	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:220)
	at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:200)
	at java.lang.Thread.run(Thread.java:818)

```
</p></details>
<hr>

[Log05.txt](https://github.com/TeamNewPipe/NewPipe/files/3224277/Log05.txt)

## Exception
* __User Action:__ requested stream
* __Request:__ https://soundcloud.com/billiummoto/drunk-bee
* __Content Language:__ GB
* __Service:__ SoundCloud
* __Version:__ 0.16.0
* __OS:__ Linux Android 6.0.1 - 23
this appears with no album art (this appears only on souncloud; check the screenshot file.

<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:187)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:67)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:59)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(lambda)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

```
</p></details>
<hr>

[Log06.txt](https://github.com/TeamNewPipe/NewPipe/files/3224556/Log06.txt)

## Exception
* __User Action:__ requested playlist
* __Request:__ https://soundcloud.com/saif-ali-siddiqui/sets/mue
* __Content Language:__ GB
* __Service:__ SoundCloud
* __Version:__ 0.16.0
* __OS:__ Linux Android 6.0.1 - 23

<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.attr(java.lang.String)' on a null object reference
	at org.schabi.newpipe.extractor.services.soundcloud.SoundcloudPlaylistLinkHandlerFactory.getUrl(SoundcloudPlaylistLinkHandlerFactory.java:35)
	at org.schabi.newpipe.extractor.linkhandler.ListLinkHandlerFactory.getUrl(ListLinkHandlerFactory.java:50)
	at org.schabi.newpipe.extractor.linkhandler.LinkHandlerFactory.fromUrl(LinkHandlerFactory.java:47)
	at org.schabi.newpipe.extractor.linkhandler.ListLinkHandlerFactory.fromUrl(ListLinkHandlerFactory.java:27)
	at org.schabi.newpipe.extractor.StreamingService.getPlaylistExtractor(StreamingService.java:284)
	at org.schabi.newpipe.extractor.playlist.PlaylistInfo.getInfo(PlaylistInfo.java:27)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getPlaylistInfo$8(ExtractorHelper.java:155)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$oXX6037sP0Rn784EpEbKFh6xH48.call(lambda)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.attr(java.lang.String)' on a null object reference
	at org.schabi.newpipe.extractor.services.soundcloud.SoundcloudParsingHelper.resolveUrlWithEmbedPlayer(SoundcloudParsingHelper.java:104)
	at org.schabi.newpipe.extractor.services.soundcloud.SoundcloudPlaylistLinkHandlerFactory.getUrl(SoundcloudPlaylistLinkHandlerFactory.java:33)
	... 32 more

```
</p></details>
<hr>

Log 1, 2, 5, 6 appears when "you search and view "in the newpipe".
When you opened the link/playlist/song with url, the error will not appear.
so you need to search in newpipe, and view things in newpipe.
I will display the searched words with [].

1. Log1

This error appears when searching playlists. (especially playlists has a lot of videos)

You can see this by searching "dynamix ost(284 videos)", lanota ost(165 videos) or ect.

[search "lanota ost" on youtube]

![Screenshot_20190528-002422](https://user-images.githubusercontent.com/31562186/58428976-395d7800-80df-11e9-8261-aaf1d3086d08.png)

2. Log2

This appears almost every song by soundclooud.

You can see this by searching billiummoto or other any soundtrack / and view the soundtrack info.

[search "billiummoto" on soundcloud and view "HDHR"]

3. Log3

This appears when sharing "Log2" to newpipe.

Not quite serious.

[generate the "Log2" and push the "share"(It's on the top, right.)and share to newpipe.

4. Log4

This appeared when I turned off the phone 6hours.

I don't know why this appeared.

[???]

5. Log5

This doesn't appears often :/

I think this when this error can't load album art.

I searched "billiummoto" and view Drunk bee(wip)

[search "billiummoto" on soundcloud and "do not view the profile; scroll down, and find "Drunk bee(WIP).
If error appeared, the album art will be empty.]

![Screenshot_20190527-235847](https://user-images.githubusercontent.com/31562186/58429248-4169e780-80e0-11e9-8234-fb3fbf8601be.png)

6. Log6

This appeared when I view the playlists in soundcloud

[search "mue" on soundcloud, and scroll down and find "saif-ali-siddiqui..." playlists"

Sorry about Inexperienced english / adverting some composers/composers..(but I didn't find a better way to report the error)

**Comment by theScrabi** [comment]
Please split up your issues so we can track them better.
