### ISSUE TITLE
Crash on search

### ISSUE THREAD

**Issue by ron42** [TeamNewPipe/NewPipe#2371]
## Exception
* __User Action:__ searched
* __Request:__ "chip tune" → page: https://www.youtube.com/results?q=chip+tune&gl=US&page=3
* __Content Language:__ US
* __Service:__ YouTube
* __Version:__ 0.16.1
* __OS:__ Linux Android 8.1.0 - 27

<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Failed to extract playlist url
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubePlaylistInfoItemExtractor.getUrl(YoutubePlaylistInfoItemExtractor.java:65)
	at org.schabi.newpipe.extractor.playlist.PlaylistInfoItemsCollector.extract(PlaylistInfoItemsCollector.java:17)
	at org.schabi.newpipe.extractor.search.InfoItemsSearchCollector.extract(InfoItemsSearchCollector.java:67)
	at org.schabi.newpipe.extractor.search.InfoItemsSearchCollector.extract(InfoItemsSearchCollector.java:47)
	at org.schabi.newpipe.extractor.InfoItemsCollector.commit(InfoItemsCollector.java:87)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.collectItems(YoutubeSearchExtractor.java:139)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getPage(YoutubeSearchExtractor.java:95)
	at org.schabi.newpipe.extractor.search.SearchInfo.getMoreItems(SearchInfo.java:63)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getMoreSearchItems$1(ExtractorHelper.java:90)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$DBE2dF7XqVvkl-TcN5nthmVnvzQ.call(Unknown Source:10)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Node.attr(java.lang.String)' on a null object reference
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubePlaylistInfoItemExtractor.getUrl(YoutubePlaylistInfoItemExtractor.java:56)
	... 20 more

```
</p></details>
<hr>

**Comment by Stypox** [comment]
Use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to post bug reports, as you should have been suggested when creating the issue. Edit the above with the converted bugreport and add some more information (what were you doing? does it always occour? ...), please :-)
Edit the title to a more explanatory one, too.

**Comment by ron42** [comment]
@Stypox fixed :)

**Comment by Stypox** [comment]
I'm looking into this: the search term you shared ("chip tune") used to cause errors but now it does not anymore. But now "playlist" does.

**Comment by Stypox** [comment]
The problem probably lies [here](https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubePlaylistInfoItemExtractor.java#L55): `div.select("a").first()` is `null`.
I have no idea how I would debug this, mostly because I can't find any way to understand which search item caused errors. I will try harder in the following days.

**Comment by Stypox** [comment]
After looking at Youtube's playlist results, it seems like [this playlist](https://www.youtube.com/playlist?list=PLx0sYbCqOb8TBPRdmBHs5Iftvv9TPboYG) is the item creating problems. I deleted all YT/Google cookies from my browser so that the search results were the same as in NewPipe.

**Comment by ron42** [comment]
Closing this issue since "chip tune" really doesn't cause a crash anymore.

**Comment by ron42** [comment]
Closing this issue since "chip tune" really doesn't cause a crash anymore.

**Comment by Stypox** [comment]
Reopen this issue please, the bug is still there even though it doesn't happen with "chip tune" anymore.

**Comment by ron42** [comment]
Another crash search term: "double pendulum". It happens for certain search terms when I scroll 2 or 3 pages down the search results.

**Comment by ron42** [comment]
@ron42 Corresponding logcat

## Exception
* __User Action:__ searched
* __Request:__ "double pendulum" → page: https://www.youtube.com/results?q=double+pendulum&gl=US&page=15
* __Content Language:__ US
* __Service:__ YouTube
* __Version:__ 0.16.1
* __OS:__ Linux Android 8.1.0 - 27


<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Failed to extract playlist url
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubePlaylistInfoItemExtractor.getUrl(YoutubePlaylistInfoItemExtractor.java:65)
	at org.schabi.newpipe.extractor.playlist.PlaylistInfoItemsCollector.extract(PlaylistInfoItemsCollector.java:17)
	at org.schabi.newpipe.extractor.search.InfoItemsSearchCollector.extract(InfoItemsSearchCollector.java:67)
	at org.schabi.newpipe.extractor.search.InfoItemsSearchCollector.extract(InfoItemsSearchCollector.java:47)
	at org.schabi.newpipe.extractor.InfoItemsCollector.commit(InfoItemsCollector.java:87)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.collectItems(YoutubeSearchExtractor.java:139)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getPage(YoutubeSearchExtractor.java:95)
	at org.schabi.newpipe.extractor.search.SearchInfo.getMoreItems(SearchInfo.java:63)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getMoreSearchItems$1(ExtractorHelper.java:90)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$DBE2dF7XqVvkl-TcN5nthmVnvzQ.call(Unknown Source:10)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Node.attr(java.lang.String)' on a null object reference
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubePlaylistInfoItemExtractor.getUrl(YoutubePlaylistInfoItemExtractor.java:56)
	... 20 more

```
</p></details>
<hr>

**Comment by ron42** [comment]
Try searching using any random words and quickly scroll _a lot_ down the search results.

**Comment by expobar** [comment]
## Exception
* __User Action:__ searched
* __Request:__ beach house topic
* __Content Language:__ GB
* __Service:__ YouTube
* __Version:__ 0.16.2
* __OS:__ Linux Android 9 - 28


<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Failed to extract playlist url
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubePlaylistInfoItemExtractor.getUrl(YoutubePlaylistInfoItemExtractor.java:65)
	at org.schabi.newpipe.extractor.playlist.PlaylistInfoItemsCollector.extract(PlaylistInfoItemsCollector.java:17)
	at org.schabi.newpipe.extractor.search.InfoItemsSearchCollector.extract(InfoItemsSearchCollector.java:67)
	at org.schabi.newpipe.extractor.search.InfoItemsSearchCollector.extract(InfoItemsSearchCollector.java:47)
	at org.schabi.newpipe.extractor.InfoItemsCollector.commit(InfoItemsCollector.java:87)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.collectItems(YoutubeSearchExtractor.java:139)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getInitialPage(YoutubeSearchExtractor.java:82)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:20)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:51)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:31)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$searchFor$0(ExtractorHelper.java:77)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$BBduYDeZ_vXMQYaemaggmTPtqvA.call(Unknown Source:8)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.attr(java.lang.String)' on a null object reference
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubePlaylistInfoItemExtractor.getUrl(YoutubePlaylistInfoItemExtractor.java:56)
	... 22 more

```
</p></details>
<hr>
