### ISSUE TITLE
Unable to generate unique name. Location is not a directory

### ISSUE THREAD

**Issue by SArsalanK** [TeamNewPipe/NewPipe#2429]
2019-06-28 22:28:27.559 10049-10049/com.allvideodownloader.youtube.debug E/DownloadManager: Unable to generate unique name
java.lang.IllegalArgumentException: location is not a directory: /storage/emulated/0/Movies/NewPipeDownloaderApp
        at us.shandian.giga.service.DownloadManager.generateUniqueName(DownloadManager.java:387)
        at us.shandian.giga.service.DownloadManager.startMission(DownloadManager.java:211)
        at us.shandian.giga.service.DownloadManagerService.lambda$onStartCommand$0(DownloadManagerService.java:196)
        at us.shandian.giga.service.-$$Lambda$DownloadManagerService$1vwqSXXTuUu9arKWuX4kTtB8qNQ.run(Unknown Source:20)
        at android.os.Handler.handleCallback(Handler.java:794)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:173)
        at android.app.ActivityThread.main(ActivityThread.java:6634)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:822)

**Comment by gkeegan** [comment]
Is this issue with NewPipe or some fork of it? allvideodownloader isn't NewPipe. 

Anyways, please use the [bug report to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/).

Paste the bug report there then post what is returned here. Please also add steps to reproduce the issue and describe the issue with more detail.

**Comment by kapodamy** [comment]
`NewPipeDownloaderApp` folder exists?

**Comment by kapodamy** [comment]
related to #2634

**Comment by opusforlife2** [comment]
@SArsalanK Do you still face this issue?
