### ISSUE TITLE
ui crashes when google serves a captcha page

### ISSUE THREAD

**Issue by tusch001** [TeamNewPipe/NewPipe#2484]
- [yes] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
--> I forgot to capture the crash report, error occurs randomly
- [yes] I checked if the issue/feature exists in the latest version. 16.2
- [ ] I did use the [incredible bugreport to markdown converter] (https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports. (next time)

I'm using orbot. Once in a while newpipe crashes when loading a video. By following the share link to external browser I just found out that google asks to solve a captcha because of high site traffic (last tor exit node heavily in use?).
If it happens again I will post the crash report (probably useless) but also the served html (for the extractor to learn to recognize the code).

**Comment by Stypox** [comment]
If the crash report you got was a ReCaptchaException then it is a known problem. Anyway I would take a look at the HTML just in case.
I captured one such HTML a few days ago, but it didn't contain a recaptcha, but just "an error occoured, try again". It is probably caused by too-many-requests, too.

**Comment by tusch001** [comment]
You were right, the UI error mentions the reCaptcha. After restarting Newpioe and opening the page in the browser I could save the html response. 
Maybe you can use it. The linked JavaScript file is short and should be downloadable. (Although it says in the first line PLEASE DON'T COPY AND PASTE THIS CODE :-) ). If not - let me know I saved the js file.

--------------- HTML Response (google.com - I'm in Germany) ---

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html DIR="LTR">
<head><meta http-equiv="content-type" content="text/html; charset=utf-8"><meta name="viewport" content="initial-scale=1"><title>https://www.youtube.com/watch?v=bdEsVoqbD5s</title></head>
<body style="font-family: arial, sans-serif; background-color: #fff; color: #000; padding:20px; font-size:18px;" onload="e=document.getElementById('captcha');if(e){e.focus();}">
<div style="max-width:400px;">
<hr noshade size="1" style="color:#ccc; background-color:#ccc;"><br>
<form id="captcha-form" action="index" method="post">
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
<script>var submitCallback = function(response) {document.getElementById('captcha-form').submit();};</script>
<div id="recaptcha" class="g-recaptcha" data-sitekey="6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b" data-callback="submitCallback" data-s="BBfKAu1Eom3pCRMZf7VDAbqXxfZhg_FZNClSE9ei8z7vM9o5g9Qgzq_ONxu1ADtQdJzBdu4LkFKQnUHYe_8J_R5DRc7qc1G2cpF8gjIyarRhzPTKU8d2v2xwkofySx3-0PddU7HOFFlR0JYyufh_kjRxr7Vs2BuQPuHdSHw0unQoVwAAobZpk8Ci-6B0NLtmwONU59kU1xBGCyq4l_KDSex3Ctt72SJo-pZvp3x369R6NEqrYUmEsLI"></div>
<input type='hidden' name='q' value='EgQzTTTYGNu73OoFIhkA8aeDS1a4MV1U262KuKjQoRIhE-o1nE_rMgFy'><input type="hidden" name="continue" value="https://www.youtube.com/watch?v=bdEsVoqbD5s">
</form>
<hr noshade size="1" style="color:#ccc; background-color:#ccc;">
<div style="font-size:13px;">
<b>Über diese Seite</b><br><br>Unsere Systeme haben ungewöhnlichen Datenverkehr aus Ihrem Computernetzwerk festgestellt. Diese Seite überprüft, ob die Anfragen wirklich von Ihnen und nicht von einem Robot gesendet werden. <a href="#" onclick="document.getElementById('infoDiv').style.display='block';">Warum?</a><br><br>
<div id="infoDiv" style="display:none; background-color:#eee; padding:10px; margin:0 0 15px 0; line-height:1.4em;">
Diese Seite wird angezeigt, wenn Google automatisch Anfragen aus Ihrem Computernetzwerk erkennt, die anscheinend gegen die <a href="//www.google.com/policies/terms/">Nutzungsbedingungen</a> verstoßen. Die Sperre läuft ab, sobald diese Anfragen eingestellt werden. In der Zwischenzeit können Sie unsere Dienste weiterhin mithilfe des oben stehenden CAPTCHAs nutzen.<br><br>Dieser Datenverkehr wurde möglicherweise von bösartiger Software, einem Browser-Plug-in oder einem Skript gesendet, das automatische Anfragen verschickt. Falls Sie Ihre Netzwerkverbindung mit anderen teilen, bitten Sie Ihren Administrator um Hilfe. Möglicherweise ist ein anderer Computer, der dieselbe IP-Adresse verwendet, für die Anfragen verantwortlich. <a href="//support.google.com/websearch/answer/86640">Weitere Informationen</a><br><br>Eventuell werden Sie um Eingabe des CAPTCHAs gebeten, weil Sie komplexe Anfragen verwenden, die bekanntermaßen von Robots verwendet werden, oder weil Sie sehr schnell Anfragen senden.

</div><br>
IP-Adresse: 51.77.52.216<br>Uhrzeit: 2019-08-16T21:19:29Z<br>URL: https://www.youtube.com/watch?v=bdEsVoqbD5s<br>
</div></div>
</body>
</html>

---- Error UI
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ GB
* __Service:__ none
* __Version:__ 0.17.0
* __OS:__ Linux Android 6.0.1 - 23


<details><summary><b>Crash log</b></summary><p>

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.schabi.newpipe/org.schabi.newpipe.ReCaptchaActivity}: android.view.InflateException: Binary XML file line #14: Binary XML file line #9: Error inflating class EditText at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) at android.app.ActivityThread.access$900(ActivityThread.java:150) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:148) at android.app.ActivityThread.main(ActivityThread.java:5417) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107) Caused by: android.view.InflateException: Binary XML file line #14: Binary XML file line #9: Error inflating class EditText at android.view.LayoutInflater.inflate(LayoutInflater.java:539) at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360) at android.view.LayoutInflater.inflate(<Xposed>) at android.view.LayoutInflater.inflate(LayoutInflater.java:423) at android.view.LayoutInflater.inflate(LayoutInflater.java:374) at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469) at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) at org.schabi.newpipe.ReCaptchaActivity.onCreate(ReCaptchaActivity.java:47) at android.app.Activity.performCreate(Activity.java:6292) at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) ... 10 more Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class EditText at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:782) at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971) at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360) at android.view.LayoutInflater.parseInclude(<Xposed>) at android.view.LayoutInflater.rInflate(LayoutInflater.java:831) at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971) at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360) at android.view.LayoutInflater.parseInclude(<Xposed>) at android.view.LayoutInflater.rInflate(LayoutInflater.java:831) at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) at android.view.LayoutInflater.inflate(LayoutInflater.java:515) ... 21 more Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 50: TypedValue{t=0x2/d=0x7f040203 a=-1} at android.content.res.TypedArray.getDrawable(TypedArray.java:867) at android.content.res.XResources$XTypedArray.getDrawable(XResources.java:1363) at android.widget.TextView.<init>(TextView.java:884) at android.widget.EditText.<init>(EditText.java:64) at android.widget.EditText.<init>(EditText.java:60) at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:69) at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:65) at android.support.v7.app.AppCompatViewInflater.createEditText(AppCompatViewInflater.java:192) at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:114) at android.support.v7.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1266) at android.support.v7.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1316) at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746) ... 39 more android.view.InflateException: Binary XML file line #14: Binary XML file line #9: Error inflating class EditText at android.view.LayoutInflater.inflate(LayoutInflater.java:539) at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360) at android.view.LayoutInflater.inflate(<Xposed>) at android.view.LayoutInflater.inflate(LayoutInflater.java:423) at android.view.LayoutInflater.inflate(LayoutInflater.java:374) at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469) at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) at org.schabi.newpipe.ReCaptchaActivity.onCreate(ReCaptchaActivity.java:47) at android.app.Activity.performCreate(Activity.java:6292) at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) at android.app.ActivityThread.access$900(ActivityThread.java:150) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:148) at android.app.ActivityThread.main(ActivityThread.java:5417) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107) Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class EditText at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:782) at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971) at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360) at android.view.LayoutInflater.parseInclude(<Xposed>) at android.view.LayoutInflater.rInflate(LayoutInflater.java:831) at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971) at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360) at android.view.LayoutInflater.parseInclude(<Xposed>) at android.view.LayoutInflater.rInflate(LayoutInflater.java:831) at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) at android.view.LayoutInflater.inflate(LayoutInflater.java:515) ... 21 more Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 50: TypedValue{t=0x2/d=0x7f040203 a=-1} at android.content.res.TypedArray.getDrawable(TypedArray.java:867) at android.content.res.XResources$XTypedArray.getDrawable(XResources.java:1363) at android.widget.TextView.<init>(TextView.java:884) at android.widget.EditText.<init>(EditText.java:64) at android.widget.EditText.<init>(EditText.java:60) at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:69) at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:65) at android.support.v7.app.AppCompatViewInflater.createEditText(AppCompatViewInflater.java:192) at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:114) at android.support.v7.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1266) at android.support.v7.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1316) at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746) ... 39 more android.view.InflateException: Binary XML file line #9: Error inflating class EditText at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:782) at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971) at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360) at android.view.LayoutInflater.parseInclude(<Xposed>) at android.view.LayoutInflater.rInflate(LayoutInflater.java:831) at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971) at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360) at android.view.LayoutInflater.parseInclude(<Xposed>) at android.view.LayoutInflater.rInflate(LayoutInflater.java:831) at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) at android.view.LayoutInflater.inflate(LayoutInflater.java:515) at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360) at android.view.LayoutInflater.inflate(<Xposed>) at android.view.LayoutInflater.inflate(LayoutInflater.java:423) at android.view.LayoutInflater.inflate(LayoutInflater.java:374) at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469) at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) at org.schabi.newpipe.ReCaptchaActivity.onCreate(ReCaptchaActivity.java:47) at android.app.Activity.performCreate(Activity.java:6292) at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) at android.app.ActivityThread.access$900(ActivityThread.java:150) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:148) at android.app.ActivityThread.main(ActivityThread.java:5417) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107) Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 50: TypedValue{t=0x2/d=0x7f040203 a=-1} at android.content.res.TypedArray.getDrawable(TypedArray.java:867) at android.content.res.XResources$XTypedArray.getDrawable(XResources.java:1363) at android.widget.TextView.<init>(TextView.java:884) at android.widget.EditText.<init>(EditText.java:64) at android.widget.EditText.<init>(EditText.java:60) at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:69) at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:65) at android.support.v7.app.AppCompatViewInflater.createEditText(AppCompatViewInflater.java:192) at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:114) at android.support.v7.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1266) at android.support.v7.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1316) at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746) ... 39 more java.lang.UnsupportedOperationException: Failed to resolve attribute at index 50: TypedValue{t=0x2/d=0x7f040203 a=-1} at android.content.res.TypedArray.getDrawable(TypedArray.java:867) at android.content.res.XResources$XTypedArray.getDrawable(XResources.java:1363) at android.widget.TextView.<init>(TextView.java:884) at android.widget.EditText.<init>(EditText.java:64) at android.widget.EditText.<init>(EditText.java:60) at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:69) at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:65) at android.support.v7.app.AppCompatViewInflater.createEditText(AppCompatViewInflater.java:192) at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:114) at android.support.v7.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1266) at android.support.v7.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1316) at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746) at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971) at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360) at android.view.LayoutInflater.parseInclude(<Xposed>) at android.view.LayoutInflater.rInflate(LayoutInflater.java:831) at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971) at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360) at android.view.LayoutInflater.parseInclude(<Xposed>) at android.view.LayoutInflater.rInflate(LayoutInflater.java:831) at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) at android.view.LayoutInflater.inflate(LayoutInflater.java:515) at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method) at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360) at android.view.LayoutInflater.inflate(<Xposed>) at android.view.LayoutInflater.inflate(LayoutInflater.java:423) at android.view.LayoutInflater.inflate(LayoutInflater.java:374) at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469) at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) at org.schabi.newpipe.ReCaptchaActivity.onCreate(ReCaptchaActivity.java:47) at android.app.Activity.performCreate(Activity.java:6292) at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) at android.app.ActivityThread.access$900(ActivityThread.java:150) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) at android.os.Handler.dispatchMessage(Handler.java:102) at android.os.Looper.loop(Looper.java:148) at android.app.ActivityThread.main(ActivityThread.java:5417) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107) 
```
</p></details>
<hr>

**Comment by tusch001** [comment]
ok that didn't work.
Github formatted part of the html. I place the files temporarily here:

https://nuchi.de/google_html.txt

and 

https://nuchi.de/google_js.txt

I will delete these files after you closed the issue.
Thanks

**Comment by Stypox** [comment]
I was able to reproduce this problem yesterday. My comment above is wrong, since I didn't know a ReCaptchaActivity existed :-/

Anyway the problem has to do with an EditText inside the common toolbar layout.

Warning for @tusch001 : the data you sent contains your IP... and it is probably unneeded, as this issue has to do with ui. Thank you for your time, anyway! I will try to send a correcting PR in the next days.
