### ISSUE TITLE
App crashes on video and audio settings

### ISSUE THREAD

**Issue by shadypt** [TeamNewPipe/NewPipe#2522]
Hi,

Starting from the v0.16.0 (I think) I started getting this error. To reproduce it go to settings -> video and audio, just scroll down and the app crashes. This is still present on the latest version.
Already reported several times via user report.
Thanks for the awesome app.

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ PT
* __Service:__ none
* __Version:__ 0.17.0
* __OS:__ Linux Android 8.1.0 - 27
going on settings, audio and video, and scrolling all the way down, the app crashes

<details><summary><b>Crash log</b></summary><p>

```
java.util.FormatFlagsConversionMismatchException: Conversion = s, Flags =  
	at java.util.Formatter$FormatSpecifier.failMismatch(Formatter.java:4398)
	at java.util.Formatter$FormatSpecifier.checkBadFlags(Formatter.java:3091)
	at java.util.Formatter$FormatSpecifier.checkGeneral(Formatter.java:3049)
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2816)
	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2624)
	at java.util.Formatter.parse(Formatter.java:2557)
	at java.util.Formatter.format(Formatter.java:2504)
	at java.util.Formatter.format(Formatter.java:2458)
	at java.lang.String.format(String.java:2770)
	at android.support.v7.preference.ListPreference.getSummary(ListPreference.java:178)
	at android.support.v7.preference.Preference.onBindViewHolder(Preference.java:584)
	at android.support.v7.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:381)
	at android.support.v7.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:45)
	at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
	at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
	at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:286)
	at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:343)
	at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:359)
	at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:366)
	at android.support.v7.widget.GapWorker.run(GapWorker.java:397)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6647)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

```
</p></details>
<hr>

**Comment by shadypt** [comment]
The same happens on v0.16.1, anybody knows what is the problem?

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ PT
* __Service:__ none
* __Version:__ 0.16.1
* __OS:__ Linux Android 8.1.0 - 27


<details><summary><b>Crash log</b></summary><p>

```
java.util.FormatFlagsConversionMismatchException: Conversion = s, Flags =  
	at java.util.Formatter$FormatSpecifier.failMismatch(Formatter.java:4398)
	at java.util.Formatter$FormatSpecifier.checkBadFlags(Formatter.java:3091)
	at java.util.Formatter$FormatSpecifier.checkGeneral(Formatter.java:3049)
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2816)
	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2624)
	at java.util.Formatter.parse(Formatter.java:2557)
	at java.util.Formatter.format(Formatter.java:2504)
	at java.util.Formatter.format(Formatter.java:2458)
	at java.lang.String.format(String.java:2770)
	at android.support.v7.preference.ListPreference.getSummary(ListPreference.java:178)
	at android.support.v7.preference.Preference.onBindViewHolder(Preference.java:584)
	at android.support.v7.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:381)
	at android.support.v7.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:45)
	at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
	at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
	at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
	at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
	at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:286)
	at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:343)
	at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:359)
	at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:366)
	at android.support.v7.widget.GapWorker.run(GapWorker.java:397)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6647)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

```
</p></details>
<hr>
