### ISSUE TITLE
Crash on parsing age-restricted video 

### ISSUE THREAD

**Issue by ron42** [TeamNewPipe/NewPipe#2545]
## Exception
* __User Action:__ requested stream
* __Request:__ https://m.youtube.com/watch?v=JI_JuXOMhho, opened with popup_player
* __Content Language:__ GB
* __Service:__ YouTube
* __Version:__ 0.16.2
* __OS:__ Linux Android 9 - 28
Opening an age-restricted video, via browser URL share intents, fails to open in NewPipe (even with age-restricted content allowed in settings).

<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.extractor.utils.Parser$RegexException: failed to find pattern ""sts"\s*:\s*(\d+)
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:71)
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:61)
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup1(Parser.java:52)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getEmbeddedInfo(YoutubeStreamExtractor.java:690)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:600)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:52)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:63)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:59)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleObserveOn.subscribeActual(SingleObserveOn.java:35)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.Single.subscribe(Single.java:3424)
	at org.schabi.newpipe.RouterActivity$FetcherService.handleChoice(RouterActivity.java:545)
	at org.schabi.newpipe.RouterActivity$FetcherService.onHandleIntent(RouterActivity.java:517)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.os.HandlerThread.run(HandlerThread.java:65)

```
</p></details>
<hr>

**Comment by Stypox** [comment]
Fixed in 0.17.0
