### ISSUE TITLE
NewPipe works only with VPN

### ISSUE THREAD

**Issue by minsk21** [TeamNewPipe/NewPipe#2662]
- [+] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [+] I checked if the issue/feature exists in the latest version.
- [+] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.
## Exception
* __User Action:__ requested channel
* __Request:__ https://www.youtube.com/channel/UC6cqazSR6CnVMClY0bJI0Lg
* __Content Language:__ US
* __Service:__ YouTube
* __Version:__ 0.17.3
* __OS:__ Linux Android 9 - 28

<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get channel name at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.getName(YoutubeChannelExtractor.java:101) at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:62) at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:49) at org.schabi.newpipe.util.ExtractorHelper.lambda$getChannelInfo$4(ExtractorHelper.java:123) at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$u5W7VszTe8AoEexIsFM9huQfbkM.call(Unknown Source:4) at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44) at io.reactivex.Single.subscribe(Single.java:3438) at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35) at io.reactivex.Single.subscribe(Single.java:3438) at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41) at io.reactivex.Maybe.subscribe(Maybe.java:4154) at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153) at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78) at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66) at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42) at io.reactivex.Flowable.subscribe(Flowable.java:14479) at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36) at io.reactivex.Maybe.subscribe(Maybe.java:4154) at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46) at io.reactivex.Single.subscribe(Single.java:3438) at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89) at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578) at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) at java.lang.Thread.run(Thread.java:764) Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.attr(java.lang.String)' on a null object reference at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.getName(YoutubeChannelExtractor.java:99) ... 28 more 
```
</p></details>
<hr>
App works only with VPN

**Comment by minsk21** [comment]
Maybe it's important: the official applications YouTube for TV/Switch/iOS/Android YouTube/in browser continue to work well

**Comment by TobiGr** [comment]
Unfortunately, I cannot reproduce. That's why I spend some time to extend our error reports to provide more information, especially on the documents which are parsed to gain the info.
The following APK didn't fix anything, but hopefully helps us to understand what's going wrong. Please make sure to enable `Append page content` before copying the report.

[app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/3658863/app-debug.apk.zip)

**Comment by minsk21** [comment]
## Exception
* __User Action:__ searched
* __Request:__ beatles
* __Content Country:__ US
* __Content Language:__ en
* __Service:__ YouTube
* __Version:__ 0.17.3
* __OS:__ Linux Android 9 - 28

<details><summary><b>Crash log 1)</b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get search result items
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.collectItems(YoutubeSearchExtractor.java:115)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getInitialPage(YoutubeSearchExtractor.java:82)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:20)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:51)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:31)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$searchFor$0(ExtractorHelper.java:77)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$BBduYDeZ_vXMQYaemaggmTPtqvA.call(Unknown Source:8)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```

```HTML
<!doctype html>
<html lang="en" dir="ltr">
 <head> 
  <link rel="icon" href="https://s.ytimg.com/yts/favicon-vfl8qSV2F.ico" type="image/x-icon"> 
  <link rel="shortcut icon" href="https://s.ytimg.com/yts/favicon-vfl8qSV2F.ico" type="image/x-icon"> 
  <title>
    YouTube
  </title> 
  <meta name="description" content="Share your videos with friends, family, and the world"> 
  <meta name="keywords" content="video, sharing, camera phone, video phone, free, upload"> 
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"> 
  <link href="https://fonts.googleapis.com/css?family=YT+Sans:500" rel="stylesheet"> 
  <link href="https://fonts.googleapis.com/css?family=Roboto:400,500" rel="stylesheet"> 
  <style>
    * {
      box-sizing: border-box;
    }
    a,
    body,
    div,
    h1,
    h2,
    h3,
    h4,
    h5,
    h6,
    html,
    img,
    li,
    ol,
    p,
    span,
    ul {
      margin: 0;
      padding: 0;
      border: 0;
      font-size: 100%;
      background: transparent;
    }
    html,
    body,
#page,
#content-container,
#content,
#body-wrapper {
      height: 100%;
    }
    body {
      background: white;
      color: #0D0D0D;
      font-family: 'Roboto', sans-serif;
      font-weight: 400;
      white-space: initial;
      overflow: initial;
      text-overflow: initial;
      -webkit-font-smoothing: antialiased;
    }
#header {
      height: 56px;
      padding: 16px 24px;
      background-color: rgba(256, 256, 256, 0.98);
      position: relative;
    }
    a {
      text-decoration: none;
      cursor: pointer;
    }
#logo-icon {
      position: absolute;
      top: 18px;
      left: 24px;
    }
#body-wrapper {
      height: auto;
      min-height: 100%;
      padding-bottom: 65px;
      position: relative;
    }
#main-content {
      max-width: 1068px;
      /* vertical+horizontal centering on all browsers: use absolute positioning
       * to center this element, then use negative margins equal to half the
       * width/height of this element to perfectly center it in its container.
       */
      position: absolute;
      top: 50%;
      left: 50%;
      margin: -165px 0 0 -534px;
    }
#art {
      display: inline-block;
      float: left;
    }
#browsers {
      display: inline-block;
      margin-left: 48px;
      max-width: 592px;
    }
    h1 {
      font-family: 'YT Sans', sans-serif;
      font-weight: 500;
      margin-bottom: 16px;
      font-size: 32px;
      line-height: 48px;
    }
    p {
      margin-bottom: 24px;
      line-height: 21px;
    }
#browsers-list {
      list-style: none;
    }
    .browser {
      display: inline-block;
      width: 136px;
      height: 136px;
      margin: 0 16px 16px 0;
      background: #F3F3F3;
      border-radius: 4px;
    }
    .browser.last {
      margin-right: 0;
    }
    .browser > a {
      display: block;
      width: 100%;
      height: 100%;
      padding: 16px;
      color: #0D0D0D;
    }
    .browser > a:visited {
      color: #0D0D0D;
    }
    .browser img {
      margin: 0 16px 8px 16px;
    }
    .browser h3 {
      font-size: 14px;
      font-weight: 500;
      line-height: 16px;
      text-align: center;
    }
#footer {
      border-top: 1px solid #F0F0F0;
      text-align: center;
      padding: 16px;
      margin-top: -65px;
      background: white;
      position: relative;
    }
    .site-links > * {
      display: inline-block;
      padding: 8px 0;
    }
    .site-link {
      margin-right: 40px;
      font-size: 14px;
      font-weight: 500;
      line-height: 16px;
    }
    .site-link a,
    .site-link a:visited {
      color: #606060;
    }
    .copyright {
      color: #909090;
      font-size: 13px;
    }
    @media (max-width: 1127px) {
#main-content {
        max-width: 1030px;
      }
#art {
        width: 390px;
        height: 260px;
      }
    }
    @media (max-width: 1069px) {
#main-content {
        position: relative;
        top: initial;
        left: initial;
        margin: 0 auto;
        max-width: 640px;
        text-align: center;
      }
#art {
        float: none;
      }
#browsers {
        margin-bottom: 24px;
        margin-left: 0;
      }
    }
    @media (max-width: 647px) {
#main-content {
        margin: 16px auto;
        max-width: 440px;
      }
#art {
        width: 360px;
        height: 240px;
      }
#browsers-list {
        margin-right: -16px;
        text-align: initial;
      }
#footer {
        position: relative;
      }
    }
    @media (max-width: 491px) {
#main-content {
        max-width: 288px;
      }
      h1 {
        font-size: 32px;
        line-height: 40px;
      }
#art {
        width: 300px;
        height: 200px;
      }
    }
  </style> 
  <!-- Smart CSS Insertion --> 
 </head> 
 <body id="" class="date-20190926 en_US ltr lite exp-invert-logo exp-kevlar-settings exp-mouseover-img exp-responsive exp-search-big-thumbs   site-center-aligned site-as-giant-card  gecko gecko-43" dir="ltr"> 
  <!-- begin page --> 
  <div id="page" class=""> 
   <div id="content-container"> 
    <!-- begin content --> 
    <div id="content"> 
     <div id="body-wrapper"> 
      <div id="header"> 
       <a id="logo" href="/" alt="YouTube home" title="YouTube home"> <img id="logo-icon" height="20px" src="/yts/img/marketing/browsers/yt_logo_rgb_light-vflc4oMnY.png"> </a> 
      </div> 
      <div id="main-content"> 
       <img id="art" width="420px" height="280px" alt="" src="/yts/img/marketing/browsers/dinosaur-vflc7WKGL.png"> 
       <div id="browsers"> 
        <h1>Please update your browser to access YouTube </h1> 
        <p>It looks like your browser isn't supported any more. Please update your browser to restore your access to YouTube and get all our latest features. </p> 
        <ul id="browsers-list">
         <li class="browser"><a href="https://www.microsoft.com/windows/microsoft-edge"><img src="/yts/img/marketing/browsers/edge-vflwRLb6V.png" alt="" width="72px" height="72px"><h3>Microsoft Edge</h3></a></li>
         <li class="browser"><a href="https://www.mozilla.org/firefox/new/?utm_source=youtube.com&amp;utm_medium=referral&amp;utm_campaign=supported-browser"><img src="/yts/img/marketing/browsers/firefox-vflMTE3Tn.png" alt="" width="72px" height="72px"><h3>Mozilla Firefox</h3></a></li>
         <li class="browser"><a href="https://www.opera.com/"><img src="/yts/img/marketing/browsers/opera-vflERXhu7.png" alt="" width="72px" height="72px"><h3>Opera</h3></a></li>
         <li class="browser last"><a href="https://www.google.com/chrome/index.html?brand=CHNY&amp;utm_campaign=en&amp;utm_source=en-et-youtube&amp;utm_medium=et"><img src="/yts/img/marketing/browsers/chrome-vflGHXqMv.png" alt="" width="72px" height="72px"><h3>Google Chrome</h3></a></li>
        </ul> 
       </div> 
      </div> 
     </div> 
     <div id="footer">
      <ol class="site-links">
       <li class="site-link"><a href="//www.youtube.com/yt/about/">About</a></li>
       <li class="site-link"><a href="//www.youtube.com/yt/copyright/">Copyright</a></li>
       <li class="site-link"><a href="/t/contact_us">Contact us</a></li>
       <li class="site-link"><a href="/t/terms">Terms</a></li>
       <li class="site-link"><a href="https://www.google.com/intl/en/policies/privacy/">Privacy</a></li>
       <li class="site-link"><a href="//www.youtube.com/yt/policyandsafety/">Policy &amp; Safety</a></li>
       <li class="copyright">© 2019 YouTube, LLC</li>
      </ol>
     </div> 
    </div> 
    <!-- end content --> 
   </div> 
  </div> 
  <!-- end page --> 
  <!-- Smart JS Insertion -->   
 </body>
</html>
```
</details>
<hr>

**Comment by minsk21** [comment]
In share mode from another application the option "Append page content"is missing

## Exception
* __User Action:__ requested stream
* __Request:__ https://youtu.be/kJQP7kiw5Fk
* __Content Country:__ US
* __Content Language:__ en
* __Service:__ YouTube
* __Version:__ 0.17.3
* __OS:__ Linux Android 9 - 28

<details><summary><b>Crash log 1)</b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.text()' on a null object reference
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getErrorMessage(YoutubeStreamExtractor.java:580)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getPlayerConfig(YoutubeStreamExtractor.java:668)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:647)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:52)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:63)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:59)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```
</details>
<hr>

**Comment by minsk21** [comment]
I think that #2662 and #2663 is the same problem (Belarus, without VPN does not work, appeared recently)

**Comment by minsk21** [comment]
I don’t know why, but youtube again worked fine.
Possible reasons:

- some problems with Google itself (Google Global Cache?) - Viber messenger in Belarus сould not generate a preview in chats for youtube links and the problem disappeared synchronously
- Goverment tested PDI filtration (paranoid version)

**Comment by minsk21** [comment]
I don’t know why, but youtube again worke fine.
Possible reasons:

some problems with Google itself (Google Global Cache?) - Viber messenger in Belarus сould not generate a preview in chats for youtube links and the problem disappeared synchronously
Goverment tested PDI filtration (paranoid version)

**Comment by minsk21** [comment]
**I don’t know why, but youtube again work fine.**

Viber messenger in Belarus сould not generate a preview in chats for youtube links and the problem disappeared synchronously with NewPipe.
Some problems with Google itself (Google global cache or other)?
Goverment tested PDI filtration (paranoid version)?

**Comment by minsk21** [comment]
**I don’t know why, but youtube again work fine.**

Viber messenger in Belarus сould not generate a preview in chats for youtube links and the problem disappeared synchronously with NewPipe.
Some problems with Google itself (Google global cache or other)?
Goverment tested DPI (paranoid version)?

**Comment by minsk21** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/2663#issuecomment-536160491

> Did not change anything in phone or settings, but everything works fine now.
> Sorry for causing troubles and thanks for helping.

**Comment by cammeltech** [comment]
Sorry for writing into a closed report. But i have the exact same Problem on two Devices. Both stopped working yesterday. Device 1: AndroidIam sorry for writing into a closed report. But i have the exact same Problem on two Devices. Both stopped working yesterday. Device 1: Android 8, Device 2: Lineage (android 9). Both with the newest apk from Github. 
Interesting coincidence: Skytube stopped working at the same time. Youtube App works fine.
If i connect via VPN (same Country i'am actualy in), all works fine. 8, Device 2: Lineage (android 9). Both with the newest apk from Github. 
Interesting coincidence: Skytube stopped working at the same time. Youtube App works fine.

**Comment by cammeltech** [comment]
Iam sorry for writing into a closed report. But i have the exact same Problem on two Devices. Both stopped working yesterday. Device 1: Android 8, Device 2: Lineage (android 9). Both with the newest apk from Github. 
Interesting coincidence: Skytube stopped working at the same time. Youtube App works fine.
If i connect via VPN (same Country i'am actualy in), all works fine.
