### ISSUE TITLE
Impossible to find or play any video

### ISSUE THREAD

**Issue by soccurrow** [TeamNewPipe/NewPipe#2663]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

<hr>
Since 2019/09/20 it is impossible to find or play (open) any video. Infinite loading on trending tab (it caused some UI error once, but can't reproduce it to get crash report). App reinstalling did not help.

SoundCloud and MediaCCC services are working without any issues.
Please inform, if any additional information is needed.
<hr>

Unable to find videos. Search suggestions are showing, search results not (error).

## Exception
* __User Action:__ searched
* __Request:__ video
* __Content Language:__ GB
* __Service:__ YouTube
* __Version:__ 0.17.3
* __OS:__ Linux Android 5.0.1 - 21

<details><summary><b>Crash log</b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'org.jsoup.select.Elements org.jsoup.nodes.Element.children()' on a null object reference
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.collectItems(YoutubeSearchExtractor.java:115)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getInitialPage(YoutubeSearchExtractor.java:82)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:20)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:51)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:31)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$searchFor$0(ExtractorHelper.java:77)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$BBduYDeZ_vXMQYaemaggmTPtqvA.call(lambda)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

```
</p></details>
<hr>

When opening link, any action (show info, open in player, etc.) causing error.

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=-cdveCh1kQk, opened with video_player
* __Content Language:__ GB
* __Service:__ YouTube
* __Version:__ 0.17.3
* __OS:__ Linux Android 5.0.1 - 21

<details><summary><b>Crash log</b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.text()' on a null object reference
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getErrorMessage(YoutubeStreamExtractor.java:578)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getPlayerConfig(YoutubeStreamExtractor.java:666)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:645)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:52)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:63)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:59)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(lambda)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleObserveOn.subscribeActual(SingleObserveOn.java:35)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.Single.subscribe(Single.java:3424)
	at org.schabi.newpipe.RouterActivity$FetcherService.handleChoice(RouterActivity.java:549)
	at org.schabi.newpipe.RouterActivity$FetcherService.onHandleIntent(RouterActivity.java:521)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.os.HandlerThread.run(HandlerThread.java:61)

```
</p></details>

**Comment by TobiGr** [comment]
I cannot reproduce this. Where are you located? Do you use any VPN?

**Comment by soccurrow** [comment]
Belarus.
Don't use any VPN.
Changing content country in setting not helping (tried US, GB, RU, BY).

**Comment by Stypox** [comment]
@TobiGr for these kind of issues we might need to generate full debug logs containing the content being analyzed by the extractor before crashing. For example, the html body of the current search item being processed. This was already proposed and it would really speed up the bug hunting process, since there would be (almost) no need to be able to reproduce the error on our PCs.

**Comment by TobiGr** [comment]
@Stypox tha's why I opened #1816

**Comment by TobiGr** [comment]
@soccurrow Can you still reproduce this? While trying to track this down, I guess YouTube rolled back some changes as everything works fine for me now...

**Comment by TobiGr** [comment]
@soccurrow Can you test this APK and tell us wheterh everything is resolved?
[app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/3652519/app-debug.apk.zip)

**Comment by minsk21** [comment]
Maybe this is the same problem as in the case of #2662 (also Belarus)

**Comment by soccurrow** [comment]
Same (search error, link opening error, infinite loading on trending tab). Changing content country not helping.
Debug options are enabled. Leaks app not showing anything (empty page, only header "Leaks in org.schabi.newpipe.debug").

<details><summary><b>Crash logs</b></summary>

## Exception
* __User Action:__ searched
* __Request:__ video
* __Content Language:__ GB
* __Service:__ YouTube
* __Version:__ 0.17.3
* __OS:__ Linux Android 5.0.1 - 21


<details><summary><b>Crash log</b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'org.jsoup.select.Elements org.jsoup.nodes.Element.children()' on a null object reference
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.collectItems(YoutubeSearchExtractor.java:115)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getInitialPage(YoutubeSearchExtractor.java:82)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:20)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:51)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:31)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$searchFor$0(ExtractorHelper.java:77)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$BBduYDeZ_vXMQYaemaggmTPtqvA.call(lambda)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

```
</p></details>
<hr>

#### Error on new line number

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=-cdveCh1kQk, opened with video_player
* __Content Language:__ GB
* __Service:__ YouTube
* __Version:__ 0.17.3
* __OS:__ Linux Android 5.0.1 - 21


<details><summary><b>Crash log</b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getPlayerConfig(YoutubeStreamExtractor.java:672)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:650)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:52)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:63)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:59)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(lambda)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleObserveOn.subscribeActual(SingleObserveOn.java:35)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.Single.subscribe(Single.java:3424)
	at org.schabi.newpipe.RouterActivity$FetcherService.handleChoice(RouterActivity.java:549)
	at org.schabi.newpipe.RouterActivity$FetcherService.onHandleIntent(RouterActivity.java:521)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.os.HandlerThread.run(HandlerThread.java:61)

```
</p></details>
</details>

**Comment by alexcrypt** [comment]
I'm from Belarus too and i have the same issue, but it works fine when VPN is on.

**Comment by TobiGr** [comment]
Unfortunately, I cannot reproduce both issues. That's why I spend some time to extend our error reports to provide more information, especially on the documents which are parsed to gain the info.
The following APK didn't fix anything, but hopefully helps us to understand what's going wrong. Please make sure to enable `Append page content` before copying the report.

[app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/3658863/app-debug.apk.zip)

**Comment by soccurrow** [comment]
<details><summary><b>Search error report</b></summary>

## Exception
* __User Action:__ searched
* __Request:__ video
* __Content Country:__ GB
* __Content Language:__ en
* __Service:__ YouTube
* __Version:__ 0.17.3
* __OS:__ Linux Android 5.0.1 - 21

<details><summary><b>Crash log 1)</b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get search result items
at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.collectItems(YoutubeSearchExtractor.java:115)
at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getInitialPage(YoutubeSearchExtractor.java:82)
at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:20)
at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:51)
at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:31)
at org.schabi.newpipe.util.ExtractorHelper.lambda$searchFor$0(ExtractorHelper.java:77)
at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$BBduYDeZ_vXMQYaemaggmTPtqvA.call(lambda)
at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
at io.reactivex.Single.subscribe(Single.java:3438)
at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
```

```HTML
<!doctype html>
<html lang="en" dir="ltr">
 <head> 
  <link rel="icon" href="https://s.ytimg.com/yts/" type="image/x-icon"> 
  <link rel="shortcut icon" href="https://s.ytimg.com/yts/" type="image/x-icon"> 
  <title>
    YouTube
  </title> 
  <meta name="description" content="Share your videos with friends, family, and the world"> 
  <meta name="keywords" content="video, sharing, camera phone, video phone, free, upload"> 
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"> 
  <link href="https://fonts." rel="stylesheet"> 
  <link href="https://fonts." rel="stylesheet"> 
  <style>
    * {
      box-sizing: border-box;
    }
    a,
    body,
    div,
    h1,
    h2,
    h3,
    h4,
    h5,
    h6,
    html,
    img,
    li,
    ol,
    p,
    span,
    ul {
      margin: 0;
      padding: 0;
      border: 0;
      font-size: 100%;
      background: transparent;
    }
    html,
    body,
#page,
#content-container,
#content,
#body-wrapper {
      height: 100%;
    }
    body {
      background: white;
      color: #0D0D0D;
      font-family: 'Roboto', sans-serif;
      font-weight: 400;
      white-space: initial;
      overflow: initial;
      text-overflow: initial;
      -webkit-font-smoothing: antialiased;
    }
#header {
      height: 56px;
      padding: 16px 24px;
      background-color: rgba(256, 256, 256, 0.98);
      position: relative;
    }
    a {
      text-decoration: none;
      cursor: pointer;
    }
#logo-icon {
      position: absolute;
      top: 18px;
      left: 24px;
    }
#body-wrapper {
      height: auto;
      min-height: 100%;
      padding-bottom: 65px;
      position: relative;
    }
#main-content {
      max-width: 1068px;
      /* vertical+horizontal centering on all browsers: use absolute positioning
       * to center this element, then use negative margins equal to half the
       * width/height of this element to perfectly center it in its container.
       */
      position: absolute;
      top: 50%;
      left: 50%;
      margin: -165px 0 0 -534px;
    }
#art {
      display: inline-block;
      float: left;
    }
#browsers {
      display: inline-block;
      margin-left: 48px;
      max-width: 592px;
    }
    h1 {
      font-family: 'YT Sans', sans-serif;
      font-weight: 500;
      margin-bottom: 16px;
      font-size: 32px;
      line-height: 48px;
    }
    p {
      margin-bottom: 24px;
      line-height: 21px;
    }
#browsers-list {
      list-style: none;
    }
    .browser {
      display: inline-block;
      width: 136px;
      height: 136px;
      margin: 0 16px 16px 0;
      background: #F3F3F3;
      border-radius: 4px;
    }
    .browser.last {
      margin-right: 0;
    }
    .browser > a {
      display: block;
      width: 100%;
      height: 100%;
      padding: 16px;
      color: #0D0D0D;
    }
    .browser > a:visited {
      color: #0D0D0D;
    }
    .browser img {
      margin: 0 16px 8px 16px;
    }
    .browser h3 {
      font-size: 14px;
      font-weight: 500;
      line-height: 16px;
      text-align: center;
    }
#footer {
      border-top: 1px solid #F0F0F0;
      text-align: center;
      padding: 16px;
      margin-top: -65px;
      background: white;
      position: relative;
    }
    .site-links > * {
      display: inline-block;
      padding: 8px 0;
    }
    .site-link {
      margin-right: 40px;
      font-size: 14px;
      font-weight: 500;
      line-height: 16px;
    }
    .site-link a,
    .site-link a:visited {
      color: #606060;
    }
    .copyright {
      color: #909090;
      font-size: 13px;
    }
    @media (max-width: 1127px) {
#main-content {
        max-width: 1030px;
      }
#art {
        width: 390px;
        height: 260px;
      }
    }
    @media (max-width: 1069px) {
#main-content {
        position: relative;
        top: initial;
        left: initial;
        margin: 0 auto;
        max-width: 640px;
        text-align: center;
      }
#art {
        float: none;
      }
#browsers {
        margin-bottom: 24px;
        margin-left: 0;
      }
    }
    @media (max-width: 647px) {
#main-content {
        margin: 16px auto;
        max-width: 440px;
      }
#art {
        width: 360px;
        height: 240px;
      }
#browsers-list {
        margin-right: -16px;
        text-align: initial;
      }
#footer {
        position: relative;
      }
    }
    @media (max-width: 491px) {
#main-content {
        max-width: 288px;
      }
      h1 {
        font-size: 32px;
        line-height: 40px;
      }
#art {
        width: 300px;
        height: 200px;
      }
    }
  </style> 
  <!-- Smart CSS Insertion --> 
 </head> 
 <body id="" class="date-20190926 en_US ltr lite exp-invert-logo exp-kevlar-settings exp-mouseover-img exp-responsive exp-search-big-thumbs   site-center-aligned site-as-giant-card  gecko gecko-43" dir="ltr"> 
  <!-- begin page --> 
  <div id="page" class=""> 
   <div id="content-container"> 
    <!-- begin content --> 
    <div id="content"> 
     <div id="body-wrapper"> 
      <div id="header"> 
       <a id="logo" href="/" alt="YouTube home" title="YouTube home"> <img id="logo-icon" height="20px" src="/yts/img/marketing/ 
      </div> 
      <div id="main-content"> 
       <img id="art" width="420px" height="280px" alt="" src="/yts/img/marketing/ 
       <div id="browsers"> 
        <h1>Please update your browser to access YouTube </h1> 
        <p>It looks like your browser isn't supported any more. Please update your browser to restore your access to YouTube and get all our latest features. </p> 
        <ul id="browsers-list">
         <li class="browser"><a href="https://www.mozilla.org/"><img src="/yts/img/marketing/
         <li class="browser"><a href="https://www.google.com/"><img src="/yts/img/marketing/
         <li class="browser"><a href="https://www.opera.com/">
         <li class="browser last"><a href="https://www.microsoft."><
        </ul> 
       </div> 
      </div> 
     </div> 
     <div id="footer">
      <ol class="site-links">
       <li class="site-link"><a href="//www.youtube.com/yt/">About</a></li>
       <li class="site-link"><a href="//www.youtube.com/yt/">Copyright</a></li>
       <li class="site-link"><a href="/t/contact_us">Contact us</a></li>
       <li class="site-link"><a href="/t/terms">Terms</a></li>
       <li class="site-link"><a href="https://www.google.com/">
       <li class="site-link"><a href="//www.youtube.com/yt/">Policy &amp; Safety</a></li>
       <li class="copyright">© 2019 YouTube, LLC</li>
      </ol>
     </div> 
    </div> 
    <!-- end content --> 
   </div> 
  </div> 
  <!-- end page --> 
  <!-- Smart JS Insertion -->   
 </body>
</html>
```
</details>
</details>
<hr>

It seems "open link" error report missing <code>Append page content</code> option. In any case:
<details><summary><b>Open link error report</b></summary>

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?, opened with video_player
* __Content Country:__ GB
* __Content Language:__ en
* __Service:__ YouTube
* __Version:__ 0.17.3
* __OS:__ Linux Android 5.0.1 - 21

<details><summary><b>Crash log 1)</b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.text()' on a null object reference
at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getErrorMessage(YoutubeStreamExtractor.java:580)
at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getPlayerConfig(YoutubeStreamExtractor.java:668)
at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:647)
at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:52)
at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:63)
at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:59)
at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)
at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(lambda)
at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
at io.reactivex.Single.subscribe(Single.java:3438)
at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
at io.reactivex.Single.subscribe(Single.java:3438)
at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
at io.reactivex.Maybe.subscribe(Maybe.java:4154)
at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
at io.reactivex.Flowable.subscribe(Flowable.java:14479)
at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
at io.reactivex.Maybe.subscribe(Maybe.java:4154)
at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
at io.reactivex.Single.subscribe(Single.java:3438)
at io.reactivex.internal.operators.single.SingleObserveOn.subscribeActual(SingleObserveOn.java:35)
at io.reactivex.Single.subscribe(Single.java:3438)
at io.reactivex.Single.subscribe(Single.java:3424)
at org.schabi.newpipe.RouterActivity$FetcherService.handleChoice(RouterActivity.java:549)
at org.schabi.newpipe.RouterActivity$FetcherService.onHandleIntent(RouterActivity.java:521)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.os.HandlerThread.run(HandlerThread.java:61)
```
</details>
</details>
<hr>

When was trying to open link using "show info" option got error as always, but a few moments later got [memory dump](https://drive.google.com/drive/folders/1mssoISFoUUHak5PQnnfZeaN40Enh17qo). Maybe it will help.

**Comment by Stypox** [comment]
It looks like your browser isn't supported any more. Please update your browser to restore your access to YouTube and get all our latest features.

This means we have to change user agent in requests

**Comment by soccurrow** [comment]
Did not change anything in phone or settings, but everything works fine now. And if it was working with VPN (#2662), maybe the reason was internet provider. Sorry for causing troubles and thanks for helping.
