### ISSUE TITLE
Crash when rotating the screen right after a search

### ISSUE THREAD

**Issue by devnoname120** [TeamNewPipe/NewPipe#269]
1) From the home, do a search.
2) Before it loads, rotate the device to switch from portrait to landscape mode.
3) The app crashes.

```
java.lang.IllegalStateException: Content view not yet created
    at android.support.v4.app.ListFragment.ensureList(ListFragment.java:328)
    at android.support.v4.app.ListFragment.setListShown(ListFragment.java:280)
    at android.support.v4.app.ListFragment.setListShown(ListFragment.java:258)
    at org.schabi.newpipe.VideoItemListFragment$2.run(VideoItemListFragment.java:351)
    at android.os.Handler.handleCallback(Handler.java:815)
    at android.os.Handler.dispatchMessage(Handler.java:104)
    at android.os.Looper.loop(Looper.java:194)
    at android.app.ActivityThread.main(ActivityThread.java:5549)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)

```

**Comment by theScrabi** [comment]
Confirmed.
