### ISSUE TITLE
Download failing at certain resolutions using SAF and an external SD card

### ISSUE THREAD

**Issue by lukahn** [TeamNewPipe/NewPipe#2889]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Hi TeamNewPipe,

I'm currently using the Samsung Galaxy S4 (on Android 5.0.1), and have set the default download path to the external SD card. I've noticed that the download functionality fails just before the download is complete (~90%) at certain resolutions due to post-processing. Resuming the failed download displays the post-processing errors below. This only happens when saving to the SD card  using SAF ((internal storage is fine). Without SAF, I get the error "The file can not be created" immediately on the download prompt when pressing the OK button (i.e. it doesn't even begin the download).
Note: Although I received the prompt to select a save location using SAF, I've not received the prompt to first select the root of the SD card as I'd normally see with other apps. Whether I select the root of the SD card, or a folder within, I still get the same errors. The file is actually downloaded to the SD card, which is without fault (for the successful resolutions), or the playback seems choppy (for the ones that fail).

Using the following example video: https://www.youtube.com/watch?v=3FNOKSwkg5U
144p - "Action denied by the system"
240p - "Action denied by the system"
360p - 100% - No error
480p - "Action denied by the system"
720p - 100% - No error
1080p - "Action denied by the system"

## Exception
* __User Action:__ download post-processing
* __Request:__ -
* __Content Language:__ GB
* __Service:__ -
* __Version:__ 0.17.4
* __OS:__ Linux Android 5.0.1 - 21

<details><summary><b>Crash log</b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.exists()' on a null object reference
	at us.shandian.giga.io.CircularFileWriter.<init>(CircularFileWriter.java:34)
	at us.shandian.giga.postprocessing.Postprocessing.run(Postprocessing.java:138)
	at us.shandian.giga.get.DownloadMission.doPostprocessing(DownloadMission.java:692)
	at us.shandian.giga.get.DownloadMission.notifyFinished(DownloadMission.java:375)
	at us.shandian.giga.get.-$$Lambda$7y-MX_I1zV-i12pHJExUQYwZRB0.run(lambda)
	at java.lang.Thread.run(Thread.java:818)

```
</p></details>
<hr>

**Comment by kapodamy** [comment]
SAF is falling in some devices with android 5 because those roms are not CTS complaint

**Comment by kapodamy** [comment]
¿can you test if the issue was fixed?
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4130473/app-debug.zip)

**Comment by lukahn** [comment]
Heya @kapodamy, thanks so much for looking into this.
Unfortunately I'm still seeing the same message as before (tested in the same way using the same 144p video):

## Exception
* __User Action:__ download post-processing
* __Request:__ https://www.youtube.com/watch?v=3FNOKSwkg5U [ {type=video format=MPEG-4 quality=144p videoOnly=true}  {type=audio format=m4a bitrate=128} ]
* __Content Language:__ GB
* __Service:__ YouTube
* __Version:__ 0.18.2
* __OS:__ Linux Android 5.0.1 - 21


<details><summary><b>Crash log</b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.exists()' on a null object reference
	at us.shandian.giga.io.CircularFileWriter.<init>(CircularFileWriter.java:34)
	at us.shandian.giga.postprocessing.Postprocessing.run(Postprocessing.java:154)
	at us.shandian.giga.get.DownloadMission.doPostprocessing(DownloadMission.java:702)
	at us.shandian.giga.get.DownloadMission.lambda$1gGnKY4qsIM8af3LqOOlrMGS3J4(DownloadMission.java)
	at us.shandian.giga.get.-$$Lambda$DownloadMission$1gGnKY4qsIM8af3LqOOlrMGS3J4.run(lambda)
	at java.lang.Thread.run(Thread.java:818)

```
</p></details>
<hr>

**Comment by kapodamy** [comment]
another try
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4135598/app-debug.zip)

**Comment by lukahn** [comment]
Thanks for that. I'm still getting errors, but with a slightly different JSON error message this time (tempFile was null):

## Exception
* __User Action:__ download post-processing
* __Request:__ https://www.youtube.com/watch?v=3FNOKSwkg5U [ {type=video format=MPEG-4 quality=144p videoOnly=true}  {type=audio format=m4a bitrate=128} ]
* __Content Language:__ GB
* __Service:__ YouTube
* __Version:__ 0.18.2
* __OS:__ Linux Android 5.0.1 - 21


<details><summary><b>Crash log</b></summary><p>

```
java.lang.NullPointerException: tempFile was null
	at us.shandian.giga.postprocessing.Postprocessing.run(Postprocessing.java:115)
	at us.shandian.giga.get.DownloadMission.doPostprocessing(DownloadMission.java:702)
	at us.shandian.giga.get.DownloadMission.lambda$1gGnKY4qsIM8af3LqOOlrMGS3J4(DownloadMission.java)
	at us.shandian.giga.get.-$$Lambda$DownloadMission$1gGnKY4qsIM8af3LqOOlrMGS3J4.run(lambda)
	at java.lang.Thread.run(Thread.java:818)

```
</p></details>
<hr>

**Comment by kapodamy** [comment]
another try
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4141956/app-debug.zip)

please:
* start a new download, do not resume the existings
* you will get a notification **Setting temporal dir to +/pending_download_temp**, folder path can vary
* or get another **NullPointerException** crash

for some reason `us.shandian.giga.postprocessing.Postprocessing#setTemporalDir()` doent get called or the variable` Postprocessing.tempFile` is dereferenced (weak reference).

**Comment by lukahn** [comment]
Hi @kapodamy, 

Thanks for the advice. I do get the toast message now:

![Screenshot_2020-02-01-14-33-49](https://user-images.githubusercontent.com/5970051/73586375-48af8380-4500-11ea-9d37-c965bcd1397c.png)

And the same message as before immediately after the download:

![Screenshot_2020-02-01-14-34-06](https://user-images.githubusercontent.com/5970051/73586376-52d18200-4500-11ea-99ee-92f8c3bb113c.png)

Then I get the same message as before when pressing start on the failed download (but I'll stop this test going forward at your request).

## Exception
* __User Action:__ download post-processing
* __Request:__ https://www.youtube.com/watch?v=3FNOKSwkg5U [ {type=video format=MPEG-4 quality=144p videoOnly=true}  {type=audio format=m4a bitrate=128} ]
* __Content Language:__ GB
* __Service:__ YouTube
* __Version:__ 0.18.2
* __OS:__ Linux Android 5.0.1 - 21


<details><summary><b>Crash log</b></summary><p>

```
java.lang.NullPointerException: tempFilePath was null
	at us.shandian.giga.postprocessing.Postprocessing.run(Postprocessing.java:139)
	at us.shandian.giga.get.DownloadMission.doPostprocessing(DownloadMission.java:702)
	at us.shandian.giga.get.DownloadMission.lambda$1gGnKY4qsIM8af3LqOOlrMGS3J4(DownloadMission.java)
	at us.shandian.giga.get.-$$Lambda$DownloadMission$1gGnKY4qsIM8af3LqOOlrMGS3J4.run(lambda)
	at java.lang.Thread.run(Thread.java:818)

```
</p></details>
<hr>

**Comment by kapodamy** [comment]
last attempt
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4145920/app-debug.zip)

**Comment by lukahn** [comment]
I've tried it again, but this time I don't see the toast, nor do I have the option to start a failed download to get the JSON.
However, despite giving an error after post-processing, the downloaded video appears to be working perfectly fine (without the stutters that it suffered from before)!

I've uploaded the whole process here:
**Installation:**
https://youtu.be/gaWGplJ7IxM

**Post-processing details:**
https://youtu.be/AXodesHrd4Y

There are no temporary files in:
This PC\Galaxy S4\Card\Android\data\org.schabi.newpipe.debug\files\pending_downloads_temp or This PC\Galaxy S4\Card\Android\data\org.schabi.newpipe.debug\files\pending_downloads
This PC\Galaxy S4\Phone\Android\data\org.schabi.newpipe.debug\files\pending_downloads_temp

But there are some in: 
This PC\Galaxy S4\Phone\Android\data\org.schabi.newpipe.debug\files\pending_downloads

![image](https://user-images.githubusercontent.com/5970051/73650847-3b98bd00-46d7-11ea-86b2-12b56b6e2293.png)

**Comment by kapodamy** [comment]
sorry for the delay, i cant believe this not fixed yet.
now seeing your video i cannot see any popup asking for read/write permissions like this one:
![ask](https://user-images.githubusercontent.com/16857233/74090889-afe4af00-4a8f-11ea-80c3-16f9ab362276.PNG)
also:
* there are files in "pending_downloads" but not in "pending_downloads_temp"
* cannot access to `/storage/emulated/0/Android/data/org.schabi.newpipe.debug/files/pending_downloads_temp` in background threads
* there no popup wih the text "Permission denied (write)"

Check if the storage permission is granted under **Android settings > Apps > NewPipe > Permissions** and try again, otherwise try this apk
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4176104/app-debug.zip)
and post the logcat of newpipe before the crash.

**Comment by lukahn** [comment]
Heya @kapodamy ,
Thanks for your persistence. I'm seeing the same behaviour as before with the new file (the video saves/converts fine without stutter, though I don't get the popup for SD card permission still).

Unfortunately I can't change the permissions of the app, but it *should* have everything.

![Screenshot_2020-02-09-20-29-29](https://user-images.githubusercontent.com/5970051/74099868-35de2400-4b7c-11ea-9ce5-2ddec74c0cea.png)

That said, MiXplorer has to ask for write permissions, and this needs to be repeated when I use the app again later, even without a reboot (leading me to think that SAF is generally a bit broken).

Is there a specific filter I should use with logcat? I've done a case insensitive grep on the full output for "newpipe", and attached the results. Let me know if you need the full log though.
`adb.exe logcat | grep -i newpipe > newpipe.txt`
[newpipe.txt](https://github.com/TeamNewPipe/NewPipe/files/4176693/newpipe.txt)

I've also included the file at "This PC\Galaxy S4\Phone\Android\data\org.schabi.newpipe.debug\files\pending_downloads\1581240350718" (renamed to add .txt), as this has some error information.

[Uploading 1581240350718.txt…]()

Otherwise I'm happy to close off this issue as the video saving feature is working as expected, but it just seems like the final cleanup is giving the error.

**Comment by kapodamy** [comment]
the logcat command is:
```bash
adb logcat | grep -F "`adb shell ps | grep org.schabi.newpipe.debug  | tr -s [:space:] ' ' | cut -d' ' -f2`"
```
or
```bash
pid=$(adb shell ps | grep "org.schabi.newpipe.debug" | cut -c10-15) && adb logcat | grep $pid
```

`grep -i newpipe` only lines with "newpipe" string

**Comment by lukahn** [comment]
Hi @kapodamy ,

Thanks for those adb commands. I ran the first one, and have the following logcat:
[logcat.log](https://github.com/TeamNewPipe/NewPipe/files/4190247/logcat.log)

And the last APK downloaded the files as expected (they play back without lag at 144p and 1080p), but there's just that error message at the end of the post-processing stage. I'd guess that it's not able to clean up some files afterwards (maybe those in ""This PC\Galaxy S4\Phone\Android\data\org.schabi.newpipe.debug\files\pending_downloads\"), but I'm not sure.

**Comment by kapodamy** [comment]
@lukahn after looking the log the exception is
```
java.io.IOException: ftruncate failed: EACCES (Permission denied)
	at java.nio.FileChannelImpl.truncate(FileChannelImpl.java:465)
	at us.shandian.giga.io.FileStreamSAF.setLength(FileStreamSAF.java:134)
	at us.shandian.giga.io.CircularFileWriter.finalizeFile(CircularFileWriter.java:148)
	at us.shandian.giga.postprocessing.Postprocessing.run(Postprocessing.java:177)
	at us.shandian.giga.get.DownloadMission.doPostprocessing(DownloadMission.java:693)
	at us.shandian.giga.get.DownloadMission.lambda$1gGnKY4qsIM8af3LqOOlrMGS3J4(DownloadMission.java)
	at us.shandian.giga.get.-$$Lambda$DownloadMission$1gGnKY4qsIM8af3LqOOlrMGS3J4.run(lambda)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: ftruncate failed: EACCES (Permission denied)
	at libcore.io.Posix.ftruncate(Native Method)
	at libcore.io.BlockGuardOs.ftruncate(BlockGuardOs.java:148)
	at java.nio.FileChannelImpl.truncate(FileChannelImpl.java:463)
	... 7 more
```
The exception is thrown while attemping to truncate the file. where go another workaround
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/4196202/app-debug.zip)

**Comment by lukahn** [comment]
Hi @kapodamy ,

Thank you for your patience.
Still the same as before from an end-user perspective (including the file in This PC\Galaxy S4\Phone\Android\data\org.schabi.newpipe.debug\files\pending_downloads). Still no permissions pop up either.

[logcat2.log](https://github.com/TeamNewPipe/NewPipe/files/4197766/logcat2.log)

I also had the option to export the error message (which is the same as the one you posted above):

## Exception
* __User Action:__ download failed
* __Request:__ https://www.youtube.com/watch?v=3FNOKSwkg5U [ {type=video format=MPEG-4 quality=144p videoOnly=true}  {type=audio format=m4a bitrate=128} ]
* __Content Language:__ GB
* __Service:__ YouTube
* __Version:__ 0.18.2
* __OS:__ Linux Android 5.0.1 - 21


<details><summary><b>Crash log</b></summary><p>

```
java.io.IOException: ftruncate failed: EACCES (Permission denied)
	at java.nio.FileChannelImpl.truncate(FileChannelImpl.java:465)
	at us.shandian.giga.io.StoredFileHelper.setLength(StoredFileHelper.java:208)
	at us.shandian.giga.postprocessing.Postprocessing.run(Postprocessing.java:198)
	at us.shandian.giga.get.DownloadMission.doPostprocessing(DownloadMission.java:690)
	at us.shandian.giga.get.DownloadMission.lambda$1gGnKY4qsIM8af3LqOOlrMGS3J4(DownloadMission.java)
	at us.shandian.giga.get.-$$Lambda$DownloadMission$1gGnKY4qsIM8af3LqOOlrMGS3J4.run(lambda)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: ftruncate failed: EACCES (Permission denied)
	at libcore.io.Posix.ftruncate(Native Method)
	at libcore.io.BlockGuardOs.ftruncate(BlockGuardOs.java:148)
	at java.nio.FileChannelImpl.truncate(FileChannelImpl.java:463)
	... 6 more

```
</p></details>
<hr>

Also, I noticed that an app called "Leaks" was installed at the same time as NewPipe Debug (possibly from https://github.com/TeamNewPipe/NewPipe/pull/1082), so I just wanted to check that this was legit.

![Screenshot_2020-02-13-14-38-53](https://user-images.githubusercontent.com/5970051/74426667-dea4c000-4ea9-11ea-9302-2e57be587bf8.png)

![Screenshot_2020-02-13-14-39-00](https://user-images.githubusercontent.com/5970051/74426673-e3697400-4ea9-11ea-8eef-6f37d4dc71d9.png)

**Comment by kapodamy** [comment]
last 2 attempts, im out of workarounds. this is a device bug like https://github.com/TeamNewPipe/NewPipe/issues/2470 and appears to be unfixable

workaround 1: using ftruncate directly
[app-debug_r0.zip](https://github.com/TeamNewPipe/NewPipe/files/4206781/app-debug_r0.zip)

workaround 2: using base context
[app-debug_r1.zip](https://github.com/TeamNewPipe/NewPipe/files/4206786/app-debug_r1.zip)

**Comment by lukahn** [comment]
Heya @kapodamy ,

Still the same behaviour unfortunately, so maybe it is a Samsung Android 5 ROM problem.
I also noticed that unfortunately the last three debug APKs (app-debug.zip - 13/02/2020, app-debug_r0.zip/app-debug_r1.zip - 15/02/2020) no longer allow the downloaded video to be played. I've gone back to test the other ones and they all work, along with the latest official release (0.18.3), so I just wanted to let you know.

Here are the logs for the last two debug APKs:

**app-debug_r0**
[logcat3.log](https://github.com/TeamNewPipe/NewPipe/files/4208455/logcat3.log)
## Exception
* __User Action:__ download failed
* __Request:__ https://www.youtube.com/watch?v=3FNOKSwkg5U [ {type=video format=MPEG-4 quality=144p videoOnly=true}  {type=audio format=m4a bitrate=128} ]
* __Content Language:__ GB
* __Service:__ YouTube
* __Version:__ 0.18.2
* __OS:__ Linux Android 5.0.1 - 21


<details><summary><b>Crash log</b></summary><p>

```
java.io.IOException: android.system.ErrnoException: ftruncate failed: EACCES (Permission denied)
	at us.shandian.giga.io.StoredFileHelper.setLength(StoredFileHelper.java:218)
	at us.shandian.giga.postprocessing.Postprocessing.run(Postprocessing.java:199)
	at us.shandian.giga.get.DownloadMission.doPostprocessing(DownloadMission.java:690)
	at us.shandian.giga.get.DownloadMission.lambda$1gGnKY4qsIM8af3LqOOlrMGS3J4(DownloadMission.java)
	at us.shandian.giga.get.-$$Lambda$DownloadMission$1gGnKY4qsIM8af3LqOOlrMGS3J4.run(lambda)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: ftruncate failed: EACCES (Permission denied)
	at libcore.io.Posix.ftruncate(Native Method)
	at libcore.io.BlockGuardOs.ftruncate(BlockGuardOs.java:148)
	at android.system.Os.ftruncate(Os.java:153)
	at us.shandian.giga.io.StoredFileHelper.setLength(StoredFileHelper.java:215)
	... 5 more

```
</p></details>
<hr>



**app-debug_r1**
[logcat4.log](https://github.com/TeamNewPipe/NewPipe/files/4208456/logcat4.log)
## Exception
* __User Action:__ download failed
* __Request:__ https://www.youtube.com/watch?v=3FNOKSwkg5U [ {type=video format=MPEG-4 quality=144p videoOnly=true}  {type=audio format=m4a bitrate=128} ]
* __Content Language:__ GB
* __Service:__ YouTube
* __Version:__ 0.18.2
* __OS:__ Linux Android 5.0.1 - 21


<details><summary><b>Crash log</b></summary><p>

```
java.io.IOException: android.system.ErrnoException: ftruncate failed: EACCES (Permission denied)
	at us.shandian.giga.io.StoredFileHelper.setLength(StoredFileHelper.java:222)
	at us.shandian.giga.postprocessing.Postprocessing.run(Postprocessing.java:198)
	at us.shandian.giga.get.DownloadMission.doPostprocessing(DownloadMission.java:690)
	at us.shandian.giga.get.DownloadMission.lambda$1gGnKY4qsIM8af3LqOOlrMGS3J4(DownloadMission.java)
	at us.shandian.giga.get.-$$Lambda$DownloadMission$1gGnKY4qsIM8af3LqOOlrMGS3J4.run(lambda)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: ftruncate failed: EACCES (Permission denied)
	at libcore.io.Posix.ftruncate(Native Method)
	at libcore.io.BlockGuardOs.ftruncate(BlockGuardOs.java:148)
	at android.system.Os.ftruncate(Os.java:153)
	at us.shandian.giga.io.StoredFileHelper.setLength(StoredFileHelper.java:219)
	... 5 more

```
</p></details>
<hr>


Otherwise I'm happy to close this ticket as the downloaded video now works, and in the meantime I'll ignore the error message and get a phone that's not 7 years old 😛

**Comment by kapodamy** [comment]
sad to hear, this issue cannot be fixed
