### ISSUE TITLE
Forced closed on version 18 when played video long than 5 min

### ISSUE THREAD

**Issue by V3ndetaa** [TeamNewPipe/NewPipe#2914]
I used newpipe version 0.16.2,because I couldn't get the report from version 18,this the report and sry I change the packaged name couse my linigade os have troubled when update new pipe as system apk.
## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=4Dk7eYoj5GI
* __Content Language:__ GB
* __Service:__ YouTube
* __Version:__ 0.16.2
* __OS:__ Linux Android 7.1.2 - 25

<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipex.extractor.exceptions.ParsingException: Could not get video length
	at org.schabi.newpipex.extractor.services.youtube.extractors.YoutubeStreamExtractor.getLength(YoutubeStreamExtractor.java:231)
	at org.schabi.newpipex.extractor.stream.StreamInfo.extractOptionalData(StreamInfo.java:207)
	at org.schabi.newpipex.extractor.stream.StreamInfo.getInfo(StreamInfo.java:68)
	at org.schabi.newpipex.extractor.stream.StreamInfo.getInfo(StreamInfo.java:59)
	at org.schabi.newpipex.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)
	at org.schabi.newpipex.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(lambda)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Node.attr(java.lang.String)' on a null object reference
	at org.schabi.newpipex.extractor.services.youtube.extractors.YoutubeStreamExtractor.getLength(YoutubeStreamExtractor.java:229)
	... 29 more

```
</p></details>
<hr>

**Comment by V3ndetaa** [comment]
After I checks with logcat,my sys not granted permission to new pipe to read something in sys.so this my rom the cause of this crash.
