### ISSUE TITLE
[Soundcloud] "Could not parse json response"

### ISSUE THREAD

**Issue by pihug12** [TeamNewPipe/NewPipe#2915]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [ ] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

There is currently, with NewPipe 0.18.0, the "Could not parse json response" exception when:
* searching a Soundcloud track: https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/extractor/src/main/java/org/schabi/newpipe/extractor/services/soundcloud/SoundcloudSearchExtractor.java#L69
* opening a Soundcloud link: https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/extractor/src/main/java/org/schabi/newpipe/extractor/services/soundcloud/SoundcloudParsingHelper.java#L118

**Comment by pihug12** [comment]
## Exception
* __User Action:__ requested stream
* __Request:__ https://soundcloud.com/impactmusicdnb/immersion-merge-free-dl
* __Content Language:__ FR
* __Service:__ SoundCloud
* __Version:__ 0.18.0
* __OS:__ Linux samsung/heroltexx/herolte:8.0.0/R16NW/G930FXXU4ESB4:user/release-keys 8.0.0 - 26


<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse json response
	at org.schabi.newpipe.extractor.services.soundcloud.SoundcloudParsingHelper.resolveFor(SoundcloudParsingHelper.java:118)
	at org.schabi.newpipe.extractor.services.soundcloud.SoundcloudStreamExtractor.onFetchPage(SoundcloudStreamExtractor.java:33)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:54)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:60)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: com.grack.nanojson.JsonParserException: Expected JSON value, got EOF on line 1, char 0
	at com.grack.nanojson.JsonParser.createParseException(Unknown Source:44)
	at com.grack.nanojson.JsonParser.currentValue(Unknown Source:30)
	at com.grack.nanojson.JsonParser.parse(Unknown Source:3)
	at com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source:15)
	at org.schabi.newpipe.extractor.services.soundcloud.SoundcloudParsingHelper.resolveFor(SoundcloudParsingHelper.java:116)
	... 30 more

```
</p></details>

**Comment by pihug12** [comment]
I can't reproduce the issue since I reinstall the app (still 0.18.0 from F-Droid). :disappointed: 

Maybe a cache issue?

**Comment by TobiGr** [comment]
As I explained [here](https://github.com/TeamNewPipe/NewPipeExtractor/pull/231#issuecomment-570540017)  and in the comment above, we might need to improve the method which checks whether a client_id is valid to always use the correct one.

**Comment by Salusbury** [comment]
Having the same issue on version 18.6

**Comment by tatami4** [comment]
Same issue on 0.19.2

**Comment by theScrabi** [comment]
I'm having this issue on all of my phones to, with version 0.19.5. Whats odd is that on some of my frieds phones it works flawlessly.

**Comment by opusforlife2** [comment]
Any change with 0.19.8?

**Comment by wb9688** [comment]
@opusforlife2: Yes, this should've been fixed by Mauricio in some NPE PR
