### ISSUE TITLE
Can't download subtitle due to SSL error

### ISSUE THREAD

**Issue by lyndmi** [TeamNewPipe/NewPipe#3021]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [N/A] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

An error caused downloader to gets stuck then reporting error. Happened on 0.18.0 and 0.18.2
Can be tested with 8 bit guy or LGR videos that have subs 
https://www.youtube.com/user/adric22
 
My tablet is denver running 4.4.4

![Screenshot_2020-01-27-21-08-32](https://user-images.githubusercontent.com/24647715/73210429-9156ed80-414a-11ea-8eac-9a4c56f35cb2.png)

I have captured the logcat

```
01-27 21:08:25.570 E/DownloadInitializer(5782): initializer failed, retrying
01-27 21:08:25.570 E/DownloadInitializer(5782): javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x5bfdf748: Failure in SSL library, usually a protocol error
01-27 21:08:25.570 E/DownloadInitializer(5782): error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol (external/openssl/ssl/s23_clnt.c:714 0x57098ce4:0x00000000)
01-27 21:08:25.570 E/DownloadInitializer(5782): 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:448)
01-27 21:08:25.570 E/DownloadInitializer(5782): 	at com.android.okhttp.Connection.upgradeToTls(Connection.java:146)
01-27 21:08:25.570 E/DownloadInitializer(5782): 	at com.android.okhttp.Connection.connect(Connection.java:107)
01-27 21:08:25.570 E/DownloadInitializer(5782): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
01-27 21:08:25.570 E/DownloadInitializer(5782): 	at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
01-27 21:08:25.570 E/DownloadInitializer(5782): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
01-27 21:08:25.570 E/DownloadInitializer(5782): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
01-27 21:08:25.570 E/DownloadInitializer(5782): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
01-27 21:08:25.570 E/DownloadInitializer(5782): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
01-27 21:08:25.570 E/DownloadInitializer(5782): 	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:136)
01-27 21:08:25.570 E/DownloadInitializer(5782): 	at us.shandian.giga.get.DownloadMission.establishConnection(DownloadMission.java:249)
01-27 21:08:25.570 E/DownloadInitializer(5782): 	at us.shandian.giga.get.DownloadInitializer.run(DownloadInitializer.java:58)
01-27 21:08:25.570 E/DownloadInitializer(5782): Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x5bfdf748: Failure in SSL library, usually a protocol error
01-27 21:08:25.570 E/DownloadInitializer(5782): error:14077102:SSL routines:SSL23_GET_SERVER_HELLO:unsupported protocol (external/openssl/ssl/s23_clnt.c:714 0x57098ce4:0x00000000)
01-27 21:08:25.570 E/DownloadInitializer(5782): 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
01-27 21:08:25.570 E/DownloadInitializer(5782): 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:405)
01-27 21:08:25.570 E/DownloadInitializer(5782): 	... 11 more

```

**Comment by Stypox** [comment]
This seems like a network error or a certificate error and should not be related to NewPipe. Does it always happen?

**Comment by lyndmi** [comment]
No it was working perfectly on 0.17.4 and below. It can't be my network fault since i never changed anything
I can still watch video with subtitle enabled and download video, just only subtitle i can't download. Maybe it's caused by this changes? https://github.com/TeamNewPipe/NewPipe/pull/2957

**Comment by lyndmi** [comment]
Seems it's only work on 5.0 and above. I can reproduce it on emulator running 4.4
Was TLS been enforced to latest version? TLSv1.1 and TLSv1.2 protocols are not enabled by default on kitkat 4.4

**Comment by Stypox** [comment]
@mqus could you take a look at this?

**Comment by lyndmi** [comment]
Yeah this could be TLS issues related. Should not be a problem if TLS 1.2 was enabled by the app.
Everything else still working fine though. maybe TLS 1.2 was not enabled for subtitle downloading?

**Comment by mqus** [comment]
I can't repro it on my phone right now, as I'm still waiting for FDroid to provide 0.18.2 (Youtube crashes ;)) . I'll try to look at it later this evening.

**Comment by lyndmi** [comment]
are you testing it on your phone running 4.4.x right?
It can be reproduced on emulator called Memu running 4.4 image
Works fine on 5.1 and 7.1

**Comment by mqus** [comment]
> are you testing it on your phone running 4.4.x right?

exactly ;)
I reproduced this in the normal android emulator coming with android studio on android 4.4.2@x86 right now, I'll try and see what I can do to fix it ;-)

**Comment by mqus** [comment]
So I tried the following two things:
1.: I turned on the debugger and set the TLSFactoryCompat directly in `DownloadMission` Line 230.

This still produced the error, and I'll check if this actually opens a TLS1.2 connection later. This shouldn't be solving anything though because that TLSFactoryCompat is set as a default at the start of MainActivity.

2.: I tried a sample URL from which the subtitles are actually downloaded (catched with the debugger). As this is a youtube.com url (`https://www.youtube.com/api/timedtext?v=[...etcpp]`), It should accept TLS 1.0 connections (the ones which are enabled by default on kitkat) anyway. So i tried with 
```
$ curl -vvv --http1.1 --tlsv1.0 'https://www.youtube.'com/api/timedtext?v=[...etcpp]'
```
And, sure enough, the handshake completed and the subtitles were downloaded/showed.

This both showed to me that this shouldn't be an issue with kitkats TLS support... but somehow it is. I'll look some more into it but as I'm not that familiar with android development or the NewPipe codebase I sure would welcome some help with this issue :)

**Comment by mqus** [comment]
After cross-checking with wireshark, It seems that DownloadMission is requesting some chunks with TLS 1.2 and some other chunks with SSL3 (not even TLS1.0), which fail the TLS Hello with an `Alert: Protocol Version`, probably leading to the error. I can't make out why android would do this. I'll try some more tomorrow.

**Comment by blackbox87** [comment]
It's a different exception, but NewPipe Legacy was also failing to download files on an old phone I test with. I pushed a single line fix to DownloadMission.java two hours ago.

https://github.com/TeamNewPipe/NewPipe-legacy/pull/21

**Comment by blackbox87** [comment]
@mqus It's a different exception, but NewPipe Legacy was also failing to download files on an old phone I test with. I pushed a single line fix that applies to DownloadMission.java two hours ago.

https://github.com/TeamNewPipe/NewPipe-legacy/pull/21

**Comment by blackbox87** [comment]
@mqus It's a different exception, but NewPipe Legacy was also failing to download files on an old phone I test with. I pushed a single line fix that applies to DownloadMission.java two hours ago.

https://github.com/TeamNewPipe/NewPipe-legacy/pull/21

I compiled NewPipe with the same fix applied and it allows me to download captions on Android 4.4.4.

**Comment by mqus** [comment]
you're right!
`conn.setRequestProperty("Accept-Encoding", "*");` fixes the whole thing. I'll do a PR later today, if no one else already did.

**Comment by gillhash** [comment]
NewPipe Legacy was also failing to download files on an old phone I test with. I pushed a single line fix that applies to DownloadMission.java two 
> I compiled NewPipe with the same fix applied and it allows me to download captions on Android 4.4.4.

@blackbox87 would you upload latest compiled apk with download fixes somewhere preferably in 
https://github.com/TeamNewPipe/NewPipe-legacy/pull/21
as it may take considrable time to update Legacy version by its maintainer.
and Btw your work is of great help to us.💖
