### ISSUE TITLE
Share a download from NewPipe creates an error. v18.2

### ISSUE THREAD

**Issue by eladkarako** [TeamNewPipe/NewPipe#3045]
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ GB
* __Service:__ none
* __Version:__ 0.18.2
* __OS:__ Linux Android 9 - 28

<details><summary><b>Crash log</b></summary><p>

```
android.os.FileUriExposedException: file:///storage/emulated/0/Download/Irish_Dancing_Flashmob_in_Essex_by_Aer_Lingus_Regional_and_London_Southend_Airport.mp4 exposed beyond app through ClipData.Item.getUri()
	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1978)
	at android.net.Uri.checkFileUriExposed(Uri.java:2371)
	at android.content.ClipData.prepareToLeaveProcess(ClipData.java:966)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:10917)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:10923)
	at android.content.Intent.prepareToLeaveProcess(Intent.java:10902)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1671)
	at android.app.Activity.startActivityForResult(Activity.java:4701)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
	at android.app.Activity.startActivityForResult(Activity.java:4659)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
	at android.app.Activity.startActivity(Activity.java:5020)
	at android.app.Activity.startActivity(Activity.java:4988)
	at us.shandian.giga.ui.adapter.MissionAdapter.shareFile(MissionAdapter.java:384)
	at us.shandian.giga.ui.adapter.MissionAdapter.handlePopupItem(MissionAdapter.java:661)
	at us.shandian.giga.ui.adapter.MissionAdapter.access$200(MissionAdapter.java:85)
	at us.shandian.giga.ui.adapter.MissionAdapter$ViewHolderItem.lambda$buildPopup$3$MissionAdapter$ViewHolderItem(MissionAdapter.java:934)
	at us.shandian.giga.ui.adapter.-$$Lambda$MissionAdapter$ViewHolderItem$RgJD8t6gH83XiFLVb3LGB9-h96A.onMenuItemClick(Unknown Source:2)
	at android.widget.PopupMenu$1.onMenuItemSelected(PopupMenu.java:105)
	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:776)
	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:155)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:923)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:913)
	at com.android.internal.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:362)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1689)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:4130)
	at android.widget.AbsListView$7.run(AbsListView.java:6612)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7078)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

```
</p></details>
<hr>

**Comment by Stypox** [comment]
Thanks for the report!
These exceptions are also related: https://github.com/TeamNewPipe/NewPipe/issues/2861#issuecomment-568301677 https://github.com/TeamNewPipe/NewPipe/issues/2861#issuecomment-568302519

**Comment by rahuldeshwal21** [comment]
I use  v0.18.2 
Mobile = Samsung M10
Many  times  Play  background  music  problem  Is  continuously play sound  with music (system Notification Sond )

**Comment by eladkarako** [comment]
solved. production v0.18.6

**Comment by eladkarako** [comment]
sorry my mistake it is still broken.
