### ISSUE TITLE
DeadSystemException

### ISSUE THREAD

**Issue by eladkarako** [TeamNewPipe/NewPipe#3059]
searched a video, clicked the ~40 result. app crash. repeated, same. force close clean install, same. reboot, same. 

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ GB
* __Service:__ none
* __Version:__ 0.18.2
* __OS:__ Linux Android 9 - 28

<details><summary><b>Crash log</b></summary><p>

```
java.lang.RuntimeException: android.os.DeadSystemException
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:160)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7078)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
Caused by: android.os.DeadSystemException
	... 8 more
android.os.DeadSystemException
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:160)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7078)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

```
</p></details>
<hr>

**Comment by Stypox** [comment]
This seems likely to be a device specific issue: https://stackoverflow.com/questions/42784731/android-deadsystemexception#44395215

Which phone are you using?

**Comment by eladkarako** [comment]
I thought so too.
Samsung Galaxy J400F. Android Pie. I too saw that stackoverflow, but it doesn't make much sense either.

**Comment by cool-student** [comment]
@eladkarako can you check your logcat ? maybe there's an exception thrown before the `DeadSystemException` ?

**Comment by eladkarako** [comment]
can't reproduce again. 
'think bug can be closed until more data would be available.
