### ISSUE TITLE
[Soundcloud] NewPipe crashes when searching 

### ISSUE THREAD

**Issue by snappyapple632** [TeamNewPipe/NewPipe#3072]
- [X] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [X] I checked if the issue/feature exists in the latest version.
- [X] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

Any attempt made to make searches or return search suggestions causes NewPipe to crash. See crash logs.

When returning search suggestions:
## Exception
* __User Action:__ get suggestions
* __Request:__ 
* __Content Language:__ US
* __Service:__ SoundCloud
* __Version:__ 0.18.2
* __OS:__ Linux Android 10 - 29

<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse json response
	at org.schabi.newpipe.extractor.services.soundcloud.SoundcloudSuggestionExtractor.suggestionList(SoundcloudSuggestionExtractor.java:47)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$suggestionsFor$2(ExtractorHelper.java:105)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$kAwiU5Tjeit-NCwHTWhD3V6UHS8.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleToObservable.subscribeActual(SingleToObservable.java:35)
	at io.reactivex.Observable.subscribe(Observable.java:12090)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12090)
	at io.reactivex.internal.operators.observable.ObservableZip$ZipCoordinator.subscribe(ObservableZip.java:110)
	at io.reactivex.internal.operators.observable.ObservableZip.subscribeActual(ObservableZip.java:72)
	at io.reactivex.Observable.subscribe(Observable.java:12090)
	at io.reactivex.internal.operators.observable.ObservableMaterialize.subscribeActual(ObservableMaterialize.java:28)
	at io.reactivex.Observable.subscribe(Observable.java:12090)
	at io.reactivex.internal.operators.observable.ObservableSwitchMap$SwitchMapObserver.onNext(ObservableSwitchMap.java:127)
	at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
	at io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver$DelayErrorInnerObserver.onNext(ObservableConcatMap.java:506)
	at io.reactivex.observers.SerializedObserver.onNext(SerializedObserver.java:111)
	at io.reactivex.internal.operators.observable.ObservableDebounceTimed$DebounceTimedObserver.emit(ObservableDebounceTimed.java:143)
	at io.reactivex.internal.operators.observable.ObservableDebounceTimed$DebounceEmitter.run(ObservableDebounceTimed.java:168)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: com.grack.nanojson.JsonParserException: Expected JSON value, got EOF on line 1, char 0
	at com.grack.nanojson.JsonParser.createParseException(Unknown Source:44)
	at com.grack.nanojson.JsonParser.currentValue(Unknown Source:30)
	at com.grack.nanojson.JsonParser.parse(Unknown Source:3)
	at com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source:15)
	at org.schabi.newpipe.extractor.services.soundcloud.SoundcloudSuggestionExtractor.suggestionList(SoundcloudSuggestionExtractor.java:40)
	... 26 more

```
</p></details>
<hr>

When executing a search:
## Exception
* __User Action:__ searched
* __Request:__ sschafi1
* __Content Language:__ US
* __Service:__ SoundCloud
* __Version:__ 0.18.2
* __OS:__ Linux Android 10 - 29

<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse json response
	at org.schabi.newpipe.extractor.services.soundcloud.SoundcloudSearchExtractor.onFetchPage(SoundcloudSearchExtractor.java:69)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:54)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:29)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$searchFor$0(ExtractorHelper.java:77)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$BBduYDeZ_vXMQYaemaggmTPtqvA.call(Unknown Source:8)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: com.grack.nanojson.JsonParserException: Expected JSON value, got EOF on line 1, char 0
	at com.grack.nanojson.JsonParser.createParseException(Unknown Source:44)
	at com.grack.nanojson.JsonParser.currentValue(Unknown Source:30)
	at com.grack.nanojson.JsonParser.parse(Unknown Source:3)
	at com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source:15)
	at org.schabi.newpipe.extractor.services.soundcloud.SoundcloudSearchExtractor.onFetchPage(SoundcloudSearchExtractor.java:67)
	... 15 more

```
</p></details>
<hr>

**Comment by Stypox** [comment]
@TobiGr I'll fix this, or are you already doing it?

**Comment by TobiGr** [comment]
:man_facepalming: didn't find the problem first while running the latest extractor commit. fixed by https://github.com/TeamNewPipe/NewPipeExtractor/commit/9112a106eab9c05ca5c9e574623d4908ecc15656. We need to push an update. However, we should investigate why `getClientId()` worked for the last few days although the clientId was invalid and now refused to work.

**Comment by TobiGr** [comment]
@Stypox The only question is whether to roll out a hotfix release with just one commit or 0.18.3 at its current state.

**Comment by Stypox** [comment]
@TobiGr there are too many changes in 0.18.3, I think it needs the usual week of testing before release... I think it would be better to push a hotfix

**Comment by TobiGr** [comment]
@Stypox @poolitzer Can someone write a small announcement for the blog?

**Comment by Stypox** [comment]
Telling that the client id was updated?

**Comment by TobiGr** [comment]
yes

**Comment by Stypox** [comment]
Ok

**Comment by Stypox** [comment]
I will open a PR at the website tomorrow, ok?

**Comment by snappyapple632** [comment]
Looks like the new release fixed it. Closing this issue.

**Comment by TobiGr** [comment]
@Stypox sure

**Comment by Poolitzer** [comment]
@tobigr since @stypox apparently already got it, Im gonna chicken out on that one ;P
