### ISSUE TITLE
java.net.MalformedURLException: unknown protocol: vnd.youtube

### ISSUE THREAD

**Issue by Offerel** [TeamNewPipe/NewPipe#3091]
If i click a YouTube link or thumbnail in an app like FeedMe or other RSS reader, NewPipe starts but crashes instantly with the error "org.schabi.newpipe.extractor.exceptions.ParsingException: Malformed url: vnd.youtube:thi73589" or some similar error. If I open the same link with standard YouTube app, the right video is opened.

**Comment by XiangRongLin** [comment]
Please use the [converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) and add the full crash log.

**Comment by Offerel** [comment]
## Exception
* __User Action:__ requested stream
* __Request:__ vnd.youtube:Jb8BqYYqDMQ
* __Content Language:__ GB
* __Service:__ YouTube
* __Version:__ v0.18.3
* __OS:__ Linux Android 10 - 29


<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Malformed url: vnd.youtube:Jb8BqYYqDMQ
	at org.schabi.newpipe.extractor.utils.Utils.getBaseUrl(Utils.java:184)
	at org.schabi.newpipe.extractor.linkhandler.LinkHandlerFactory.fromUrl(LinkHandlerFactory.java:46)
	at org.schabi.newpipe.extractor.StreamingService.getStreamExtractor(StreamingService.java:251)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:60)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.net.MalformedURLException: unknown protocol: vnd.youtube
	at java.net.URL.<init>(URL.java:608)
	at java.net.URL.<init>(URL.java:498)
	at java.net.URL.<init>(URL.java:447)
	at org.schabi.newpipe.extractor.utils.Utils.stringToURL(Utils.java:145)
	at org.schabi.newpipe.extractor.utils.Utils.getBaseUrl(Utils.java:182)
	... 29 more

```
</p></details>
<hr>

**Comment by Offerel** [comment]
BTW: I have installed Vanced after this error occurs, to check if a similar problem exists there also. Vanced opens, but cant load the video. It seems to load forever, but without a crash. Only the vanilla Youtube app could load the video. But i would prefer to deactivate vanilla Youtube and use Newpipe.

**Comment by XiangRongLin** [comment]
It seems like vnd.youtube is the URI for an intent to open the video in another app (YouTube app).

The part after the colon ":" should be the video id.

**Comment by Offerel** [comment]
I don't want to force but when will a fix for this issue be in the app?
