### ISSUE TITLE
ReCaptcha crashes NewPipe v0.18.3

### ISSUE THREAD

**Issue by jniniinoinoino** [TeamNewPipe/NewPipe#3112]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.
- [x] I did use the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) to paste bug reports.

I use Orbot, I sometimes get ReCaptcha popping up, after waiting for the page to load, NewPipe crashes.

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ US
* __Service:__ none
* __Version:__ v0.18.3
* __OS:__ Linux Android 9 - 28

<details><summary><b>Crash log</b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at org.schabi.newpipe.ReCaptchaActivity$ReCaptchaWebViewClient.find_access_cookies(ReCaptchaActivity.java:128)
	at org.schabi.newpipe.ReCaptchaActivity$ReCaptchaWebViewClient.onPageFinished(ReCaptchaActivity.java:113)
	at a7.b(PG:2)
	at nh.handleMessage(PG:64)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```
</p></details>
<hr>

**Comment by Stypox** [comment]
Try v0.18.4: #3114
