### ISSUE TITLE
Release v0.18.4

### ISSUE THREAD

**Issue by Stypox** [TeamNewPipe/NewPipe#3114]
### New
- Added language selector to change the app language #2921
- Added send to Kodi button to player collapsible menu #2310 
- Added ability to copy comments on long press #3053

### Improved
- Fix ReCaptcha activity and correctly save obtained cookies #3035 
- Remove dot-menu in favour of drawer and hide history button when "Watch history" is not enabled in settings #2960
- Ask for display over other apps permission in settings correctly on Android 6 and later #3004
- Rename local playlist by long-clicking in BookmarkFragment #2954
- Various PeerTube improvements #3044 :
  - Display full description instead of truncated
  - Handle age limit
- Improved several English source strings #2938

### Fixed
- Fixed player starting again although it is paused when option "minimize on app switch" enabled and NewPipe is minimized #2917 
- Fixed `.srt` subtitle downloads containing not all line breaks #2957
- Fixed download to SD card failing because some Android 5 devices are not CTF compliant  #2958
- Fixed downloading on Android KitKat #3032 
- Fixed corrupt video `.mp4` file being recognized as audio file #2959 
- Fixed wrong Chines language codes #2865
- Fix initial brightness value for gesture #3102
- Fixed corrupt mp4 downloads #3117
- [YouTube] Timestamps in description are clickable again #3044

------------------------
## APK for testing: RC1
[app-debug_RC1.zip](https://github.com/TeamNewPipe/NewPipe/files/4227084/app-debug.zip)
**PULL REQUEST #3113**

#### PLEASE REPORT ONLY *NEW* BUGS BELOW

**Comment by Stypox** [comment]
@TobiGr should I also add [NewPipeExtractor changelog](https://github.com/TeamNewPipe/NewPipeExtractor/releases) here?

**Comment by aaazv** [comment]
Do u have a telegram group?

**Comment by aaazv** [comment]
when will this bug of recaptcha get fixed?

**Comment by garawaa** [comment]
Please make it possible to download songs from soundcloud by sharing to
newpipe.

**Comment by Stypox** [comment]
@aaazv no, we don't have a Telegram group, see #2965
Recaptchas have been fixed in this version. Please post here only new issues you find in the provided RC apk.

@garawaa that's not a new bug related to this release and to the provided RC apk, but is just a feature request. There are already issues open for it.

**Comment by cool-student** [comment]
@Stypox 
I think we should merge https://github.com/TeamNewPipe/NewPipe/pull/3099 since it fixes a regression introduced in https://github.com/TeamNewPipe/NewPipe/pull/2959

**Comment by TobiGr** [comment]
> @TobiGr should I also add [NewPipeExtractor changelog](https://github.com/TeamNewPipe/NewPipeExtractor/releases) here?

@Stypox No. Thank you for taking care of this release. I have a changelog file, but I am waiting for #3098 and #3099 before I push it. Btw, please create a new branch for a release as described [in the our docs](https://teamnewpipe.github.io/documentation/05_releasing/) next time. I forgot to point that out yesterday :)

**Comment by aaazv** [comment]
Can u tell me when will this be released?

**Comment by Poolitzer** [comment]
if you need it now, download the debug apk

**Comment by opusforlife2** [comment]
@aaazv Yep. As @Poolitzer said, you can use the debug APK if it's urgent. It will install separately from the main app, and you can continue to use the debug app until the new version is released officially.

**Comment by aaazv** [comment]
A problem.

As I close every app as "kill foreground app", whenever I try to open a utube video with newpipe again, the video doesnt come the first time. the forst attempt, the app shows up on the default page, what ever it is, then u have to click on the link again to see the video in newpipe.
I checked this woth official app and its not like this.

This bothers a little.
Another thing is that the videos dont load sometimes and the rest of the time, load slower than other apps.

But still, its better than vanced or snaptube or original app. thanks.

**Comment by Poolitzer** [comment]
How do you try to open it.

**Comment by aaazv** [comment]
> How do you try to open it.
By searching a video in google and clicking on a vid coming up in search results. Then it asks me to open woth chrome or newpipe, I choose newpipe.

This way, first the app starts without showing the content I want.

**Comment by aaazv** [comment]
By searching a video in google and clicking on a vid coming up in search results. Then it asks me to open woth chrome or newpipe, I choose newpipe.

This way, first the app starts without showing the content I want.

**Comment by Stypox** [comment]
@aaazv is this a new bug introduced by this release? If not, please open a new issue

Anyway, we would need the device model and OS, and it would help if you intercepted the "open" intent using Intent Intercept: https://f-droid.org/app/de.k3b.android.intentintercept

**Comment by opusforlife2** [comment]
GUYS! REGRESSION!

> Remove dot-menu in favour of drawer

I thought this setting would replace the dot menu with the drawer everywhere. Turns out that it just removes the dot menu. The drawer is only accessible from the home screen.

If you must remove the dot menu, please make the drawer accessible from all screens.

**Comment by B0pol** [comment]
I don't think you need to access settings everywhere, why would you?

I've watched the behavior on some other app, and all are the same : you can only access drawer on main page. If you are in a subactivity (ie there is a back button in appbar), you can't access settings.

**Comment by opusforlife2** [comment]
> If you are in a subactivity (ie there is a back button in appbar), you can't access settings.

Not true. Play Store > My apps & games has the back button, yet the side drawer is accessible.

Anyway, why would you want to take functionality _away_ from the user?

**Comment by Stypox** [comment]
@TobiGr what should we do about this menu issue? The only button needeed from everywhere is probably "Settings".

**Comment by opusforlife2** [comment]
I think there is nothing wrong with the direction this is going in. If you were to ask me what I preferred, dot menu or sidebar, I would choose sidebar. Is it difficult to make it accessible on other screens?

**Comment by gillhash** [comment]
But, why dot menu is being removed in first place, a function that i use routinely.

.. a dot menu one touch away is so helpful.

**Comment by Stypox** [comment]
I found an issue in this release: pressing "Switch to Popup" in the background player queue activity generates a crash. I tried to look into it but  I was not able to understand why this happens and how to fix it. Switching to MainPlayer works, and switching from MainPlayer to other players works.

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ en_GB
* __Service:__ none
* __Version:__ 0.18.4
* __OS:__ Linux Android 7.0 - 24


<details><summary><b>Crash log</b></summary><p>

```
android.content.ActivityNotFoundException: Unable to find explicit activity class {org.schabi.newpipe.debug/org.schabi.newpipe.player.PopupVideoPlayer}; have you declared this activity in your AndroidManifest.xml?
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1850)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1544)
	at android.app.ContextImpl.startActivity(ContextImpl.java:885)
	at android.app.ContextImpl.startActivity(ContextImpl.java:855)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:356)
	at org.schabi.newpipe.player.ServicePlayerActivity.switchTo(ServicePlayerActivity.java:199)
	at org.schabi.newpipe.player.BackgroundPlayerActivity.onPlayerOptionSelected(BackgroundPlayerActivity.java:58)
	at org.schabi.newpipe.player.ServicePlayerActivity.onOptionsItemSelected(ServicePlayerActivity.java:171)
	at android.app.Activity.onMenuItemSelected(Activity.java:3356)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:384)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:219)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:313)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1201)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3195)
	at android.widget.AbsListView$3.run(AbsListView.java:4138)
	at android.os.Handler.handleCallback(Handler.java:761)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6523)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

```
</p></details>
<hr>

**Comment by opusforlife2** [comment]
> pressing "Switch to Popup" in the background player queue activity generates a crash

Confirmed.

**Comment by TobiGr** [comment]
Uh. I guess this was introduced by #2917. I'll look into it tonight :(

**Comment by TobiGr** [comment]
I reverted ef90493c27af898d8e79adbb5e8d449ef5d0ae35 partly in 0bc769b9714db1fa163b41d07d52f6f1a2adfcaa. This fixes the crash for me, but does not introduce the old buggy behaviour. Here is the last RC for this release: [NewPipe_v0.18.4_RC3.zip](https://github.com/TeamNewPipe/NewPipe/files/4239845/NewPipe_v0.18.4_RC3.zip)
CC @opusforlife2 @Stypox

**Comment by Stypox** [comment]
Mmmh, strange, we will have to look into this after the release... Anyway, the apk works for me, thanks for looking into it :-).

**Comment by opusforlife2** [comment]
Confirmed. Crash fixed. Release time!

**Comment by opusforlife2** [comment]
By the way, @Stypox I downloaded mauricio's PR 2309 apk. He renamed the package. If you could encourage other PR authors to rename their apks as well, we could test multiple apks side by side without having to  go through the hassle of uninstalling and reinstalling.

**Comment by TobiGr** [comment]
@opusforlife2 Good idea. We might want to add this information to the contribution guidelines and to the pull request teplate. Btw.. we should also create more issue templates. One for bug reports and one for feature requests

**Comment by Stypox** [comment]
Yeah, great idea. What about adding a ".branchname" at the end of the app signature, only if the current branch name is not "master" or "dev"? Also, we could set the app name to "NewPipe branchname" with the rules above. This should be doable with gradle.

**Comment by Poolitzer** [comment]
@tobiGR I wanted to do those templates anyway, can do that in a bit (after I updated the blog post)

**Comment by TobiGr** [comment]
New version is released.

**Comment by B0pol** [comment]
Why you mentioned [the custom F-Droid repo](https://archive.newpipe.net/fdroid/repo?fingerprint=E2402C78F9B97C6C89E97DB914A2751FDA1D02FE2039CC0897A462BDB57E7501) on [reddit only](https://www.reddit.com/r/NewPipe/comments/f800fa/newpipe_v0184_released/)? That's neat :rocket:
