### ISSUE TITLE
Crash when share video to download

### ISSUE THREAD

**Issue by rancidfrog** [TeamNewPipe/NewPipe#3163]
Steps to reproduce:
- Share a video to newpipe and select download.
- Share another video to newpipe and click download
- open newpipe from notification, before title to save appears (it usually takes a few seconds before dialog appears)
![](https://i.imgur.com/IX0T67N.png)
this dialogue
![](https://i.imgur.com/mMAanP2.png)

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ GB
* __Service:__ none
* __Version:__ 0.18.5
* __OS:__ Linux Android 7.1.1 - 25

<details><summary><b>Crash log</b></summary><p>

```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at androidx.fragment.app.FragmentManagerImpl.checkStateLoss(FragmentManagerImpl.java:1536)
	at androidx.fragment.app.FragmentManagerImpl.enqueueAction(FragmentManagerImpl.java:1558)
	at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:317)
	at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:282)
	at androidx.fragment.app.DialogFragment.show(DialogFragment.java:155)
	at org.schabi.newpipe.RouterActivity.lambda$openDownloadDialog$10$RouterActivity(RouterActivity.java:443)
	at org.schabi.newpipe.-$$Lambda$RouterActivity$xUnqF5q9vTU7PVoyXeI1RNn0Etg.accept(lambda)
	at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6334)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

```
</p></details>
<hr>

**Comment by Stypox** [comment]
@rancidfrog 
Please use the [Incredible Error Report to Markdown Converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) before sending bug reports, as you should have been told when creating the issue.

**Comment by opusforlife2** [comment]
Drop a comment if this still happens in 0.19.8.
