### ISSUE TITLE
Error while browsing a channel ("Requesting Stream") 

### ISSUE THREAD

**Issue by eladkarako** [TeamNewPipe/NewPipe#3238]
https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.18.6

I've subscribed to my channel (https://www.youtube.com/channel/UCRedgf5rdWzUCIP5HGwU84w) then closed and reopened NewPipe, headed over to the 'whats new' and clicked the latest video.

I'm getting a popup message for an error.
![20200317_021628](https://user-images.githubusercontent.com/415238/76810051-6b1e0780-67f5-11ea-863f-f13ed8c39f51.jpg)

Repeatable.

<hr/>

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=NmoSBw7YDu0
* __Content Language:__ GB
* __Service:__ YouTube
* __Version:__ 0.18.6
* __OS:__ Linux Android 9 - 28

<details><summary><b>Crash log</b></summary><p>

```
java.lang.NumberFormatException: For input string: ""
	at java.lang.Long.parseLong(Long.java:606)
	at java.lang.Long.parseLong(Long.java:636)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getViewCount(YoutubeStreamExtractor.java:282)
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractOptionalData(StreamInfo.java:229)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:70)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:61)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```
</p></details>
<hr>

**Comment by wb9688** [comment]
I can't reproduce :/

**Comment by eladkarako** [comment]
I can see the error each time I open https://www.youtube.com/watch?v=Kngw5U1wuOQ for some reason, after visiting the channel videos.

**Comment by wb9688** [comment]
Could confirm. It's because it says "No views", which doesn't contain a number. I'll fix that soon.
