### ISSUE TITLE
App loops in null pointer with bookmarks exception. 

### ISSUE THREAD

**Issue by abhishekshah67** [TeamNewPipe/NewPipe#3261]
### Version

- 0.18.7

### Steps to reproduce the bug

1. Go to 'Bookmarks' tab in customized option. 
2. Press on 'Open a video'. 
3. This exception is encountered. 
4. This loops every time once encountered when the app is opened and does not let you use the app. Back option loops back. App opens with same exception.

Workaround: Delete application data.

### Expected behavior
Application to recover once error is encountered. 

### Actual behaviour
App opens with an exception each time. 
## Exception
* __User Action:__ something
* __Request:__ Bookmark
* __Content Language:__ US
* __Service:__ none
* __Version:__ 0.18.6
* __OS:__ Linux Android 10 - 29

<details><summary><b>Crash log</b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.compareToIgnoreCase(java.lang.String)' on a null object reference
	at org.schabi.newpipe.local.bookmark.BookmarkFragment.lambda$merge$5(BookmarkFragment.java:318)
	at org.schabi.newpipe.local.bookmark.-$$Lambda$BookmarkFragment$xyICh5nkFcv-vlmtOC6D7_wKbpc.compare(Unknown Source:4)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:356)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1492)
	at java.util.ArrayList.sort(ArrayList.java:1470)
	at java.util.Collections.sort(Collections.java:206)
	at org.schabi.newpipe.local.bookmark.BookmarkFragment.merge(BookmarkFragment.java:317)
	at org.schabi.newpipe.local.bookmark.BookmarkFragment.lambda$5fzG24vJKYacvKjzZORX8tBl-ak(Unknown Source:0)
	at org.schabi.newpipe.local.bookmark.-$$Lambda$BookmarkFragment$5fzG24vJKYacvKjzZORX8tBl-ak.apply(Unknown Source:4)
	at io.reactivex.internal.functions.Functions$Array2Func.apply(Functions.java:529)
	at io.reactivex.internal.functions.Functions$Array2Func.apply(Functions.java:516)
	at io.reactivex.internal.operators.flowable.FlowableCombineLatest$CombineLatestCoordinator.drainAsync(FlowableCombineLatest.java:362)
	at io.reactivex.internal.operators.flowable.FlowableCombineLatest$CombineLatestCoordinator.drain(FlowableCombineLatest.java:406)
	at io.reactivex.internal.operators.flowable.FlowableCombineLatest$CombineLatestCoordinator.innerValue(FlowableCombineLatest.java:250)
	at io.reactivex.internal.operators.flowable.FlowableCombineLatest$CombineLatestInnerSubscriber.onNext(FlowableCombineLatest.java:521)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onNext(FlowableSubscribeOn.java:97)
	at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.innerSuccess(FlowableFlatMapMaybe.java:175)
	at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber$InnerObserver.onSuccess(FlowableFlatMapMaybe.java:397)
	at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:61)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.onNext(FlowableFlatMapMaybe.java:132)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:407)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:260)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:225)
	at androidx.room.TransactionExecutor$1.run(TransactionExecutor.java:45)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</p></details>
<hr>

### Screenshots/Screen records
If applicable, add screenshots or a screen recording to help explain your problem. GitHub should support uploading them directly in the issue field. If your file is too big, feel free to paste a link from an image/video hoster here instead.

### Logs
If your bug includes a crash, please head over to the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/). Copy the result. Paste it here:

**Comment by wb9688** [comment]
Like the issue template says, please use the incredible bugreport to markdown converter.

**Comment by abhishekshah67** [comment]
looks better now.
