### ISSUE TITLE
Crash when sharing a certain playlist to Newpipe

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipe#3277]
### Version

- 0.18.7
### Steps to reproduce the bug

Share this playlist with Newpipe: https://www.youtube.com/playlist?list=PLoHg1UZiy8oG_j8mN7byXpybTONmYDXt_
### Expected behavior
Newpipe should open the playlist normally. (It opens normally if you paste this URL into the search bar.)

### Actual behaviour
Error.

### Logs
If your bug includes a crash, please head over to the [incredible bugreport to markdown converter](https://teamnewpipe.github.io/CrashReportToMarkdown/). Copy the result. Paste it here:

## Exception
* __User Action:__ requested playlist
* __Request:__ https://www.youtube.com/playlist?list=PLoHg1UZiy8oGj8mN7byXpybTONmYDXt
* __Content Language:__ en_IN
* __Service:__ YouTube
* __Version:__ 0.18.7
* __OS:__ Linux Android 9 - 28

<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ContentNotAvailableException: Got error: "The playlist does not exist."
	at org.schabi.newpipe.extractor.services.youtube.linkHandler.YoutubeParsingHelper.defaultAlertsCheck(YoutubeParsingHelper.java:402)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubePlaylistExtractor.onFetchPage(YoutubePlaylistExtractor.java:43)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:56)
	at org.schabi.newpipe.extractor.playlist.PlaylistInfo.getInfo(PlaylistInfo.java:29)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getPlaylistInfo$8(ExtractorHelper.java:155)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$oXX6037sP0Rn784EpEbKFh6xH48.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```
</p></details>
<hr>

**Comment by B0pol** [comment]
It opens https://www.youtube.com/oops for me, and with the crash reporter: « The playlist doesn't exist »

**Comment by wb9688** [comment]
You forgot sharing the last _ with NewPipe, so this is not an issue.

**Comment by opusforlife2** [comment]
What? 😆 No.

I copied this link from _within_ Newpipe, and shared it with _another_ Newpipe. GitHub ignoring the underscore is probably a markdown artifact.

This most certainly is an issue. Considering your comment, @wb9688, Newpipe (not the android clipboard, since it works from the search bar) is ignoring the trailing underscore.

**Comment by wb9688** [comment]
Sharing from NewPipe to NewPipe indeed doesn't work. Sharing from NewPipe to browser to NewPipe does work though.

**Comment by opusforlife2** [comment]
> Sharing from NewPipe to browser to NewPipe does work though.

Not for me. I'm sharing it to the release apk. Which apk are you trying it with?

**Comment by XiangRongLin** [comment]
@wb9688 @opusforlife2 
The reason for it crashing is that the RouterActivity removes the last underscore from the shared url [here](https://github.com/TeamNewPipe/NewPipe/blob/55c577e76ec96fad3a52279eaea2201f8f05c2a7/app/src/main/java/org/schabi/newpipe/RouterActivity.java#L672).  

This happens if you share it as an url from the browser (1) and do not use the "Open in App" action (2). Reason being that (1) goes the "if" [path](https://github.com/TeamNewPipe/NewPipe/blob/55c577e76ec96fad3a52279eaea2201f8f05c2a7/app/src/main/java/org/schabi/newpipe/RouterActivity.java#L638) where the above mentioned method does NOT get called and (2) goes the "else if" path where it does get called"

**Comment by opusforlife2** [comment]
So am I understanding it correctly that the underscore is mistakenly identified as a regular expression that needs to be removed?

**Comment by XiangRongLin** [comment]
> So am I understanding it correctly that the underscore is mistakenly identified as a regular expression that needs to be removed?

That's how i understood it from going through it with a debugger.
But i have no clue what the intended use case for that regex is.
