### ISSUE TITLE
Deleted Channels Throw An Error When Refreshing Subscription Feed

### ISSUE THREAD

**Issue by PeterHindes** [TeamNewPipe/NewPipe#3313]
Using the latest version. If the user imports a subscription list with a deleted chaneel such as 
![image](https://user-images.githubusercontent.com/19994487/77964930-3b630b00-729d-11ea-9042-cb1b3455d936.png)
results in a null pointer exception as a snack-bar error.

## Exception
* __User Action:__ requested feed
* __Request:__ Loading feed
* __Content Language:__ US
* __Service:__ none
* __Version:__ 0.19.0
* __OS:__ Linux Android 10 - 29

<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.local.feed.service.FeedLoadService$RequestException: 0:https://www.youtube.com/channel/UCcNE9TRcOCOoOB0Dy5ediPg
	at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:220)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:63)
	at io.reactivex.internal.operators.parallel.ParallelMap$ParallelMapSubscriber.onNext(ParallelMap.java:113)
	at io.reactivex.internal.operators.parallel.ParallelFilter$ParallelFilterSubscriber.tryOnNext(ParallelFilter.java:130)
	at io.reactivex.internal.operators.parallel.ParallelRunOn$RunOnConditionalSubscriber.run(ParallelRunOn.java:397)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.text()' on a null object reference
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeFeedExtractor.getId(YoutubeFeedExtractor.java:53)
	at org.schabi.newpipe.extractor.feed.FeedInfo.getInfo(FeedInfo.java:39)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getFeedInfoFallbackToChannelInfo$6(ExtractorHelper.java:149)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$ugdV6CfeDCyyO_ocIIpHyBlriuE.call(Unknown Source:4)
	at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:46)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeSwitchIfEmptySingle.subscribeActual(MaybeSwitchIfEmptySingle.java:45)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.Single.blockingGet(Single.java:2699)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:210)
	... 11 more

```
</p></details>
<hr>

**Comment by PeterHindes** [comment]
Expected behavior is to notify the user and ask them to delete the channel from their subscriptions.

**Comment by PeterHindes** [comment]
[Page In Question](https://www.youtube.com/channel/UCcNE9TRc0C0o0B0Dy5ediPg)

**Comment by opusforlife2** [comment]
@mauriciocolli Have a look.

**Comment by Mhowser** [comment]
I have the same problem. I have 2 or 3 nonexistent channels without any easy way to remove them.

**Comment by Stypox** [comment]
@Mhowser you can long press on channels you want to unsubscribe from in the subscription tab

**Comment by Mhowser** [comment]
I know that, it gives no clear indication if the channel is deleted on YouTube. I would need to manually check all 200+ channels that I have. 

https://github.com/TeamNewPipe/NewPipe/issues/3313#issuecomment-606268478 this is a preferred solution. Another solution would be displaying a warning sign next to the deleted channel in the channel list.

**Comment by opusforlife2** [comment]
> Another solution would be displaying a warning sign next to the deleted channel in the channel list.

I was about to suggest this. Feed refresh is the only time when the app queries all the channels for new videos one by one. That is the optimal way to alert the user about deleted channels.

**Comment by prg318** [comment]
Hi,

I don't think it's easily possible to add a banned channel to NewPipe in order to test this issue.  If anyone would like to reproduce this issue, I've attached a NewPipe configuration zip that contains two banned channels that should trigger this error.  
[NewPipeData-TwoBannedChannels-20201113_142545.zip](https://github.com/TeamNewPipe/NewPipe/files/5538930/NewPipeData-TwoBannedChannels-20201113_142545.zip)

**Comment by BigClarky** [comment]
Sorry if this is considered off topic, how would I go about removing a deleted channel?

**Comment by Atemu** [comment]
I'm not sure if that's how I did it when I came across this bug but perhaps you can long-press on the deleted channel in your subscriptions overview and unsubscribe that way?

**Comment by BigClarky** [comment]
> 
> I'm not sure if that's how I did it when I came across this bug but perhaps you can long-press on the deleted channel in your subscriptions overview and unsubscribe that way?

I had so scroll a bit but that seems to have worked, thanks.

**Comment by MD77MD** [comment]
any updates, 

"Another solution would be displaying a warning sign next to the deleted channel in the channel list."

i like this solution, also we can make newpipe creat a separate group with those problematic channels for the user to decide later. thus whenever newpipe faces a problem with a channel would just dump it there and keep the experience clean
