### ISSUE TITLE
Feed fragment crash when reloading multiple times

### ISSUE THREAD

**Issue by Stypox** [TeamNewPipe/NewPipe#3411]
### Version
- 0.19.1 on F-Droid
- 0.19.2 on GitHub

### Steps to reproduce the bug
Hitting multiple times the refresh button in the new feed fragment leads to this crash @mauriciocolli 
This bug was sent to me by a user. 

### Logs
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ IN
* __Service:__ none
* __Version:__ 0.19.1
* __OS:__ Linux realme/RMX1971/RMX1971:10/QKQ1.190918.001/1579185288:user/release-keys 10 - 29

<details><summary><b>Crash log</b></summary><p>

```
java.lang.IllegalArgumentException: Receiver not registered: org.schabi.newpipe.local.feed.service.FeedLoadService$setupBroadcastReceiver$1@2f310a9
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1469)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1568)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:675)
	at org.schabi.newpipe.local.feed.service.FeedLoadService.disposeAll(FeedLoadService.kt:134)
	at org.schabi.newpipe.local.feed.service.FeedLoadService.stopService(FeedLoadService.kt:143)
	at org.schabi.newpipe.local.feed.service.FeedLoadService.access$stopService(FeedLoadService.kt:63)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$resultSubscriber$1.onComplete(FeedLoadService.kt:264)
	at io.reactivex.internal.util.HalfSerializer.onComplete(HalfSerializer.java:90)
	at io.reactivex.internal.subscribers.StrictSubscriber.onComplete(StrictSubscriber.java:109)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.checkTerminated(FlowableObserveOn.java:215)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:399)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:228)
	at android.app.ActivityThread.main(ActivityThread.java:7782)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)

```
</p></details>
<hr>

**Comment by XiangRongLin** [comment]
I had something like this occur in one of my apps on in slower phones where you could tap a button multiple times before the action of the button could occur (thus disabling/removing the button).

**Comment by Stypox** [comment]
I think this was fixed in the meantime, I haven't encountered it in a long time. FeedFragment underwent many changes.
