### ISSUE TITLE
UI crash when resuming the about activity

### ISSUE THREAD

**Issue by Bart-0110** [TeamNewPipe/NewPipe#3447]
### Version

- v0.19.2

### Steps to reproduce the bug

1. Open the app
2. Select about from the hamburger menu
3. (Maybe not necessery) scroll down a bit
4. Open a resource heavy app (like snapchat) so it pauses the NewPipe activity
5. Re-open the NewPipe app
6. _Crashes_

### Expected behavior

Resume the about activity app or redirect to the home activity.

### Actual behaviour

An exception occured

### Device information & exception information

| Key | Value |
|---|---|
| Action | UI Error |
| Content Language | nl-NL |
| Service | None |
| Package | org.schabi.newpipe |
| Version | 0.19.2 |
| OS | Linux samsung/starltexx/starlte:10/QP1A.190711.020/G960FXXU7DTAA:user/release-keys 10 - 29 |
| Device | Samsung Galaxy S9 |

### Logs

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.schabi.newpipe/org.schabi.newpipe.about.AboutActivity}: java.lang.ClassCastException: android.os.Parcelable[] cannot be cast to org.schabi.newpipe.about.SoftwareComponent[]
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3448)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7811)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
Caused by: java.lang.ClassCastException: android.os.Parcelable[] cannot be cast to org.schabi.newpipe.about.SoftwareComponent[]
	at org.schabi.newpipe.about.LicenseFragment.onCreate(LicenseFragment.java:49)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2586)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:838)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
	at androidx.fragment.app.FragmentManagerImpl.dispatchCreate(FragmentManagerImpl.java:2607)
	at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:235)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:316)
	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
	at org.schabi.newpipe.about.AboutActivity.onCreate(AboutActivity.java:70)
	at android.app.Activity.performCreate(Activity.java:7955)
	at android.app.Activity.performCreate(Activity.java:7944)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3423)
	... 11 more
java.lang.ClassCastException: android.os.Parcelable[] cannot be cast to org.schabi.newpipe.about.SoftwareComponent[]
	at org.schabi.newpipe.about.LicenseFragment.onCreate(LicenseFragment.java:49)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2586)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:838)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
	at androidx.fragment.app.FragmentManagerImpl.dispatchCreate(FragmentManagerImpl.java:2607)
	at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:235)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:316)
	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
	at org.schabi.newpipe.about.AboutActivity.onCreate(AboutActivity.java:70)
	at android.app.Activity.performCreate(Activity.java:7955)
	at android.app.Activity.performCreate(Activity.java:7944)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3423)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7811)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
```

**Comment by opusforlife2** [comment]
Reply if reproducible in 0.19.8.
