### ISSUE TITLE
Opening a video URL (vnd.youtube://) from Music Detector gets an error

### ISSUE THREAD

**Issue by eladkarako** [TeamNewPipe/NewPipe#3514]
Opening a video link from _Music Detector_ (https://play.google.com/store/apps/details?id=com.musicdetectorapp)  gets an error (might be a short URL - my guess..🤔).
  
![GIF-200502_225859](https://user-images.githubusercontent.com/415238/80890842-bd918580-8cc8-11ea-8f2d-736325558b8d.gif)

## Exception
* __User Action:__ something
* __Request:__ null
* __Content Language:__ GB
* __Service:__ none
* __Version:__ 0.19.2
* __OS:__ Linux samsung/j4ltejx/j4lte:9/PPR1.180610.011/J400FXXU4BSJ1:user/release-keys 9 - 28

<details><summary><b>Crash log</b></summary><p>

```
java.lang.IllegalArgumentException: The given URL is not valid
	at org.schabi.newpipe.extractor.services.media_ccc.linkHandler.MediaCCCStreamLinkHandlerFactory.getId(MediaCCCStreamLinkHandlerFactory.java:24)
	at org.schabi.newpipe.extractor.services.media_ccc.linkHandler.MediaCCCStreamLinkHandlerFactory.onAcceptUrl(MediaCCCStreamLinkHandlerFactory.java:48)
	at org.schabi.newpipe.extractor.linkhandler.LinkHandlerFactory.acceptUrl(LinkHandlerFactory.java:80)
	at org.schabi.newpipe.extractor.StreamingService.getLinkTypeByUrl(StreamingService.java:287)
	at org.schabi.newpipe.extractor.NewPipe.getServiceByUrl(NewPipe.java:93)
	at org.schabi.newpipe.RouterActivity.lambda$handleUrl$0$RouterActivity(RouterActivity.java:139)
	at org.schabi.newpipe.-$$Lambda$RouterActivity$jGbV3sDp3V_oonJa1z1jLD1TKkg.call(Unknown Source:4)
	at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:43)
	at io.reactivex.Observable.subscribe(Observable.java:12090)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```
</p></details>
<hr>

**Comment by wb9688** [comment]
Download Intent Intercept from F-Droid, share it to that, and post what it shows here

**Comment by eladkarako** [comment]
That's a good idea, 
I already have it (https://f-droid.org/en/packages/de.k3b.android.intentintercept/), 
But sadly 'share' doesn't trigger the bug, it just opens up the info box for viewing video or playing the video (etc.. - which works fine by the way).
sorry, capturing the intent isn't possible since intent intercept doesn't get triggered, it might be mimetype or "protocol prefix" preserved for youtube apps..

**Comment by eladkarako** [comment]
@wb9688 I was wondering if you know away to debug opening up links by NewPipe (not sharing a link)? Would the pre-release (with debug) version help somehow (better crash report than the production one)?

**Comment by wb9688** [comment]
@eladkarako: No, I'd have to create a custom .apk that directly crashes on share containing the neccessary information in the crash report.

**Comment by eladkarako** [comment]
> directly crashes on share. 

*I'm pretty sure it isn't a share action. Share did worked just fine.
Its opening a link (probably of one of those domains `*.youtube.com`.

**Comment by Stypox** [comment]
I was able to extract the url from the intent. This is an example: `vnd.youtube://n8X9_MgEdCg`

**Comment by Stypox** [comment]
@eladkarako test the apk provided in TeamNewPipe/NewPipeExtractor#324

**Comment by eladkarako** [comment]
oh cool, did you've reverse the music id apk to get the view intent from the xml? or just had another way with something similar to the intent inspector?

**Comment by Stypox** [comment]
I had NewPipe print out the type of url it received, and that was it. I neither have the skills nor the time to reverse engineer a proguard-obfuscated apk 😂

**Comment by eladkarako** [comment]
nice. I've always thought those <a href="https://en.wikipedia.org/wiki/Mobile_deep_linking">deep-links</a> were nasty (or at-least not as simply elegant sharing). 
nice catch, 
even though it wasn't through reverse-engineering the cr^ap out of someone else's apk ;)

**Comment by wb9688** [comment]
@eladkarako: It's pretty much the same thing. Both are just (implicit) [`Intent`](https://developer.android.com/reference/android/content/Intent)s.

**Comment by eladkarako** [comment]
yep.

The fixed apk seems to be working fine. b.t.w.
