### ISSUE TITLE
0.19.3 instant crash

### ISSUE THREAD

**Issue by sh3zb0t** [TeamNewPipe/NewPipe#3524]
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ en_GB
* __Service:__ none
* __Version:__ 0.19.3
* __OS:__ Linux motorola/channel_reteu/channel:9/PPY29.105-134/e13ed:user/release-keys 9 - 28
1. set the language to polish
(havent tested other languages yet)
2. try to load "whats new page"

<details><summary><b>Crash log</b></summary><p>

```
java.util.FormatFlagsConversionMismatchException: Conversion = s, Flags = 
	at java.util.Formatter$FormatSpecifier.failMismatch(Formatter.java:4398)
	at java.util.Formatter$FormatSpecifier.checkBadFlags(Formatter.java:3091)
	at java.util.Formatter$FormatSpecifier.checkGeneral(Formatter.java:3049)
	at java.util.Formatter$FormatSpecifier.(Formatter.java:2816)
	at java.util.Formatter$FormatSpecifierParser.(Formatter.java:2624)
	at java.util.Formatter.parse(Formatter.java:2557)
	at java.util.Formatter.format(Formatter.java:2504)
	at java.util.Formatter.format(Formatter.java:2458)
	at java.lang.String.format(String.java:2883)
	at android.content.res.Resources.getString(Resources.java:466)
	at androidx.fragment.app.Fragment.getString(Fragment.java:873)
	at org.schabi.newpipe.local.feed.FeedFragment.updateRefreshViewState(FeedFragment.kt:283)
	at org.schabi.newpipe.local.feed.FeedFragment.updateRelativeTimeViews(FeedFragment.kt:273)
	at org.schabi.newpipe.local.feed.FeedFragment.onResume(FeedFragment.kt:83)
	at androidx.fragment.app.Fragment.performResume(Fragment.java:2649)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:922)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
	at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6923)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)

```
</p></details>
<hr>

**Comment by androidSwDev099** [comment]
@sh3zb0t, 
NewPipe team wants us to use templates here https://github.com/TeamNewPipe/NewPipe/issues/new/choose
and use
https://teamnewpipe.github.io/CrashReportToMarkdown/

**Comment by wb9688** [comment]
That's caused by the space between the % and the s in https://github.com/TeamNewPipe/NewPipe/blob/dev/app/src/main/res/values-pl/strings.xml#L593. There are similar issues in other places for other languages.

@TobiGr: We really need to check this kind of stuff somehow.

**Comment by TobiGr** [comment]
@wb9688 I'll write some basic tests tonight

**Comment by wb9688** [comment]
These are currently wrong in NewPipe. Everyone could fix them on Weblate. I didn't check if anyone fixed anything on Weblate (or messed up more) though.

![Screenshot_2020-05-11 Lint Report](https://user-images.githubusercontent.com/46277131/81537304-4a91aa00-936d-11ea-9de3-b4f17363c270.png)
![Screenshot_2020-05-11 Lint Report(1)](https://user-images.githubusercontent.com/46277131/81537312-4bc2d700-936d-11ea-9181-8d5b9b7b2c1d.png)
