### ISSUE TITLE
Allow playing DRM content like Youtube Movies

### ISSUE THREAD

**Issue by Hunter9888x** [TeamNewPipe/NewPipe#3538]
## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=Ct9VTQnPa5c
* __Content Language:__ US
* __Service:__ YouTube
* __Version:__ 0.19.3
* __OS:__ Linux Android 10 - 29

needs exoplayer
https://exoplayer.dev/

<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:192)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:70)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:62)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</p></details>
<hr>

**Comment by gkeegan** [comment]
See #3203. This feature is not possible due to DRM.

**Comment by Hunter9888x** [comment]
This app should add built in browser to view youtube free movies

**Comment by Hunter9888x** [comment]
@gkeegan Widevine CDM
watch DRM HTML5 videos
(like Netflix)
https://m.youtube.com/watch?v=9GgjIrpYksE

**Comment by Stypox** [comment]
Theoretically this is possible, though it would be complex: https://exoplayer.dev/drm.html

**Comment by Hunter9888x** [comment]
@Stypox ExoPlayer is the video player running in the Android YouTube app Interesting

**Comment by TheAssassin** [comment]
As mentioned on IRC, I am not a fan of any DRM support in NewPipe. I think we should not support this kind of broken concept, feeding the content industry that way.

Also, it'll make devices more identifiable again to have anything like that in place.

If you have to watch DRM-ed content, please do so on YouTube directly, but NewPipe certainly should not implement any such feature.
