### ISSUE TITLE
Error in subscriptions when loading premieres

### ISSUE THREAD

**Issue by B0pol** [TeamNewPipe/NewPipe#3543]
### Version

- 0.19.3

### Steps to reproduce the bug

Well, it's easy to reproduce, but also hard because it's rare.
0. Disable fast mode if enabled
1. Subscribe to a channel that will have a premiere video.
2. Refresh before it has started, it's working fine (e.g. the upload date shown is "in 5 minutes").
3. When it has started, refresh and now you have the error, and the channel is considered as "not loaded"

### Expected behavior

The premiere is shown with a specific tag, for example PREMIERE.
### Actual behaviour

The channel isn't loaded

## Exception
* __User Action:__ requested feed
* __Request:__ Loading feed
* __Content Language:__ fr_FR
* __Service:__ none
* __Version:__ 0.19.3
* __OS:__ Linux Android 9 - 28

<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.local.feed.service.FeedLoadService$RequestException: 0:https://www.youtube.com/channel/UCacgofzftbbkUhcftPvUzQg
	at org.schabi.newpipe.local.feed.service.FeedLoadService$RequestException$Companion.wrapList(FeedLoadService.kt:163)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$databaseConsumer$1$1.run(FeedLoadService.kt:312)
	at androidx.room.RoomDatabase.runInTransaction(RoomDatabase.java:386)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$databaseConsumer$1.accept(FeedLoadService.kt:301)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$databaseConsumer$1.accept(FeedLoadService.kt:64)
	at io.reactivex.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onNext(FlowableDoOnEach.java:86)
	at io.reactivex.internal.operators.flowable.FlowableBuffer$PublisherBufferExactSubscriber.onNext(FlowableBuffer.java:126)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:407)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get duration
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamInfoItemExtractor.getDuration(YoutubeStreamInfoItemExtractor.java:120)
	at org.schabi.newpipe.extractor.stream.StreamInfoItemsCollector.extract(StreamInfoItemsCollector.java:54)
	at org.schabi.newpipe.extractor.stream.StreamInfoItemsCollector.commit(StreamInfoItemsCollector.java:94)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.collectStreamsFrom(YoutubeChannelExtractor.java:277)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.getInitialPage(YoutubeChannelExtractor.java:228)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)
	at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:82)
	at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:47)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getChannelInfo$4(ExtractorHelper.java:124)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$u5W7VszTe8AoEexIsFM9huQfbkM.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.Single.blockingGet(Single.java:2699)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:215)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:64)
	at io.reactivex.internal.operators.parallel.ParallelMap$ParallelMapSubscriber.onNext(ParallelMap.java:113)
	at io.reactivex.internal.operators.parallel.ParallelFilter$ParallelFilterSubscriber.tryOnNext(ParallelFilter.java:130)
	at io.reactivex.internal.operators.parallel.ParallelRunOn$RunOnConditionalSubscriber.run(ParallelRunOn.java:397)
	... 7 more

```
</p></details>
<hr>

**Comment by Stypox** [comment]
I guess this can be reproduced by subscribing to 3blue1brown, with keeps doing premieres for math videos

**Comment by ShareASmile** [comment]
Some very old issues are still open, ones which can't be reproduced anymore like this one.

**Comment by ShareASmile** [comment]
Other thing I noted in channel page is Play all button fails to skip first video (which premieres in x-time) to play next video in the list like background & Popup button successfully do, but that is an another bug 🐛 
![Screenshot_20230905_132104_NewPipe nightly](https://github.com/TeamNewPipe/NewPipe/assets/60492161/00452f70-589d-49f8-9220-d84e391cee40)

**Comment by ShareASmile** [comment]
> Could you open a new issue for it?

Sorry for very late reply, opus , i will open one when on PC. Actually i was waiting for 0.26.0 to land and then forgot about it.

**Comment by ShareASmile** [comment]
> Could you open a new issue for it?

#7119 is already there as i checked before opening new issue.

**Comment by Stypox** [comment]
Closing as this was probably fixed during the channel tabs rework. Feel free to reopen if it can still be reproduced (but I have seen various premieres in my feed lately and none of them created errors).
