### ISSUE TITLE
Crash when quickly swiping away search suggestions

### ISSUE THREAD

**Issue by wb9688** [TeamNewPipe/NewPipe#3575]
Happens on at least v0.19.3 and dev, I didn't test other versions.

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ nl_NL
* __Service:__ none
* __Version:__ 0.19.3
* __OS:__ Linux samsung/a50eea/a50:10/QP1A.190711.020/A505FNXXU4BTC9:user/release-keys 10 - 29

<details><summary><b>Crash log</b></summary><p>

```
java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
	at java.util.ArrayList.get(ArrayList.java:439)
	at org.schabi.newpipe.fragments.list.search.SuggestionListAdapter.getItem(SuggestionListAdapter.java:82)
	at org.schabi.newpipe.fragments.list.search.SearchFragment.getSuggestionMovementFlags(SearchFragment.java:1023)
	at org.schabi.newpipe.fragments.list.search.SearchFragment$1.getMovementFlags(SearchFragment.java:329)
	at androidx.recyclerview.widget.ItemTouchHelper.swipeIfNecessary(ItemTouchHelper.java:1194)
	at androidx.recyclerview.widget.ItemTouchHelper.select(ItemTouchHelper.java:601)
	at androidx.recyclerview.widget.ItemTouchHelper.onChildViewDetachedFromWindow(ItemTouchHelper.java:900)
	at androidx.recyclerview.widget.RecyclerView.dispatchChildDetached(RecyclerView.java:7261)
	at androidx.recyclerview.widget.RecyclerView$5.removeViewAt(RecyclerView.java:867)
	at androidx.recyclerview.widget.ChildHelper.removeViewAt(ChildHelper.java:168)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.removeViewAt(RecyclerView.java:8374)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.scrapOrRecycleView(RecyclerView.java:8944)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.detachAndScrapAttachedViews(RecyclerView.java:8930)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:580)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4194)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1818)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1584)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1058)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3679)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3139)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2200)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8999)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:996)
	at android.view.Choreographer.doCallbacks(Choreographer.java:794)
	at android.view.Choreographer.doFrame(Choreographer.java:729)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7814)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

```
</p></details>
<hr>

**Comment by Flam3z** [comment]
Can Reproduce. 

Device: Galaxy S10
Version: 0.19.3

**Comment by B0pol** [comment]
Sentry issue: [NEWPIPE-37J](https://sentry.schabi.org/sentry/newpipe/issues/3331/?referrer=github_plugin)

I could reproduce too.
Btw, what happened with the template @wb9688 🤔
