### ISSUE TITLE
Couldn't get any stream

### ISSUE THREAD

**Issue by allendema** [TeamNewPipe/NewPipe#3576]
### Version
 Version 0.19.3

### Steps to reproduce the bug
       1. Search anything you want, maybe something that includes livestreams.
2. Click the first result, and then the second till the 5th result.
      

### Expected behavior

Stream should normally show up.
### Actual behaviour

Tried the exact same search 3 times.
Stream doesn't show up, but instead the error below

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=ZEf9cRoTmzQ
* __Content Language:__ DE
* __Service:__ YouTube
* __Version:__ 0.19.3
* __OS:__ Linux Android 10 - 29

<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:192)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:70)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:62)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</p></details>
<hr>

 See the log here too [https://haste.tchncs.de/icujifevuj.avrasm](https://haste.tchncs.de/icujifevuj.avrasm)

**Comment by B0pol** [comment]
Sentry issue: [NEWPIPE-3ZZ](https://sentry.schabi.org/sentry/newpipe/issues/4119/?referrer=github_plugin)

I could reproduce, but not everytime. 
Here are the steps: open a video, be unlucky and have this error (yeah, not easily reproduceable). Stypox encountered it too, see https://github.com/TeamNewPipe/NewPipeExtractor/pull/329

**Comment by allendema** [comment]
I will see it

**Comment by wb9688** [comment]
@allendema: I can't fix it without having the page where it occurs. Could you reliably reproduce this issue? I've only seen it once myself. If you could reliably reproduce it, I could make an APK for you that dumps the page in case of an error like this.

**Comment by allendema** [comment]
Played with it again, now searched for “jazz“
After selecting livestreams and pressing play, it loadsfor a while then “stream couldn't be played” comes up.

**Comment by wb9688** [comment]
@allendema: Are you able to (semi-)regularly reproduce it? If so, could you download https://wb9688.stackstorage.com/s/bekYrunPaZ7Yff4, manually give it storage permission in Android settings, browse around until you find a video that gives that exception and wasn't a livestream or premiere, and give me the JSON it dumps in /sdcard/? The differences from dev in that APK is that it dumps YouTube's streams' JSON to /sdcard/, it has the additional regexes and recognizes DASH manifests in playerResponse.

**Comment by allendema** [comment]
I'm afraid i can not do it right now.

**Comment by Suncatcher** [comment]
## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=pjN_-nzzoiU
* __Content Language:__ GB
* __Service:__ YouTube
* __Version:__ 0.19.3
* __OS:__ Linux Android 9 - 28


<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:192)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:70)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:62)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```
</p></details>
<hr>

**Comment by allendema** [comment]
Can someone reproduce this: 
Version 0.19.13 / Android 10
1. Search for “jazz” or “piano live”.
2. Click on any livestream (sometime also happens on normal videos too)

Couldn't play stream shows up.

I don't belive this happend on 0.19.0

**Comment by B0pol** [comment]
@lbrunkho says in duplicate (#3615)

Title: Music videos - could not parse website 
Content:
I cant seem to open any video that's related to music. It starts to load the comments but then fails to load the actual video, and gives me this dump.

_He posted a crash log_

I think this might have to do with the YouTube music implementation bc its just in this version (0.19.3) that im having this issue with and all other videos work fine.

**Comment by B0pol** [comment]
I did encounter this bug on some random videos in trending or in my subscription feeds that were not music. But indeed it was more frequent when opening music videos.

**Comment by B0pol** [comment]
These reddit posts probably have the same issue

https://reddit.com/comments/gmh5g6
https://reddit.com/comments/gn3crn

**Comment by hp8wvvvgnj6asjm7** [comment]
same here, many videos crashing.

**Comment by ale5000-git** [comment]
@wb9688

Here the JSON: [initialAjax1590606270929.zip](https://github.com/TeamNewPipe/NewPipe/files/4691195/initialAjax1590606270929.zip)

**Comment by wb9688** [comment]
@ale5000-git: Thanks for the JSON, however that's a recently ended livestream, which isn't supported and a different issue from this one. The problem with recently ended livestreams is that they're temporarily still in the livestream format instead of the normal video format, and we only support the livestream format for actual (still live) livestreams.

**Comment by ale5000-git** [comment]
I don't see "agree" at all.

**Comment by wb9688** [comment]
@ale5000-git: Interesting, could you show a screenshot of that dialog?

**Comment by ale5000-git** [comment]
I see it like this: 
![Screenshot_2020-05-27-21-53-53](https://user-images.githubusercontent.com/15793015/83066087-cd507f80-a064-11ea-919f-d8c114857b4f.png)

**Comment by wb9688** [comment]
@ale5000-git: This is what it should look like in Italian (which I normally don't use, as I don't speak it, but I wanted to check whether it's a language specific bug):

![Screenshot_20200527-220058_NewPipe Debug](https://user-images.githubusercontent.com/46277131/83066617-9fb80600-a065-11ea-8014-7aad07b732e2.png)

**Comment by ale5000-git** [comment]
I think it is related to the screen size.

**Comment by wb9688** [comment]
@ale5000-git: Do you see the accept button then when you increase minimum width in Android's developer settings? For me it's still visible at 320 dp, which is the lowest I could go.

**Comment by ale5000-git** [comment]
@wb9688: I don't have the option to change it (stock ROM, Android 5.1.1).

`adb shell wm density` show `Physical density: 240`.

**Comment by wb9688** [comment]
@ale5000-git: Are you sure? I haven't seen phones where you couldn't change it, though a minimum width of 240 dp is really low.

![Screenshot_20200528-073630_Settings](https://user-images.githubusercontent.com/46277131/83103166-78d5f000-a0b6-11ea-930c-7475a0b05431.png)

**Comment by B0pol** [comment]
Create a new issue @wb9688 @ale5000-git

**Comment by B0pol** [comment]
@eladkarako @pgenderson @jennyfromtheblockwiththegoodhair  and @everyone having such issues, can you test this APK? [NewPipe_3576-fix.zip](https://github.com/TeamNewPipe/NewPipe/files/4697239/NewPipe_3576-fix.zip).

I used NewPipe extractor version TeamNewPipe/NewPipeExtractor#333 and NewPipe dev branch, it should fix it, **when it's not about a recently ended live stream**.

**Comment by lbrunkho** [comment]
Yup the abovementioned apk fixed the issue... Just cross tested it with the current main release and it fixed 2 out of 2 videos I tried!

**Comment by jennyfromtheblockwiththegoodhair** [comment]
Yes! It works perfectly thank you!

**Comment by eladkarako** [comment]
great fix(s).

**Comment by theScrabi** [comment]
@TobiGr can we have an emergancy release for this?

**Comment by TobiGr** [comment]
@theScrabi It is planned for later today once I am done with my lectures

**Comment by Stypox** [comment]
@theScrabi @TobiGr #3670

**Comment by cesarmoi** [comment]
hello team 

about the last version 0.19.4 is not worked on the most phone  as Huawei and Samsung  that have version android 10     the major problem the old version are nt still worked also .

hope find solution as soon as possible 


![WhatsApp Image 2020-05-30 at 17 14 52 (2)](https://user-images.githubusercontent.com/25723596/83333227-c497bd80-a29f-11ea-8639-ae41473c9e34.jpeg)
![WhatsApp Image 2020-05-30 at 17 41 29](https://user-images.githubusercontent.com/25723596/83333231-c792ae00-a29f-11ea-9f52-14483b106ad7.jpeg)

**Comment by wb9688** [comment]
@cesarmoi: For above issue, see #3686. Below issue is probably not our problem, unless you could prove that www.youtube.com doesn't say "Content unavailable" at the same time for that video when set to the same locale, etc.
