### ISSUE TITLE
App crashes when downloading subscribed feed (since 0.19.3)

### ISSUE THREAD

**Issue by Etua** [TeamNewPipe/NewPipe#3601]
### Version

-0.19.3

### Steps to reproduce the bug
Try to open subscribed channels feed (default or custom)

### Expected behavior

See my subscribed feed.

### Actual behaviour

NewPipe crashes

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ GB
* __Service:__ none
* __Version:__ 0.19.3
* __OS:__ Linux Android 9 - 28

<details><summary><b>Crash log</b></summary><p>

```
java.util.FormatFlagsConversionMismatchException: Conversion = s, Flags =  
	at java.util.Formatter$FormatSpecifier.failMismatch(Formatter.java:4398)
	at java.util.Formatter$FormatSpecifier.checkBadFlags(Formatter.java:3091)
	at java.util.Formatter$FormatSpecifier.checkGeneral(Formatter.java:3049)
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2816)
	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2624)
	at java.util.Formatter.parse(Formatter.java:2557)
	at java.util.Formatter.format(Formatter.java:2504)
	at java.util.Formatter.format(Formatter.java:2458)
	at java.lang.String.format(String.java:2883)
	at android.content.res.Resources.getString(Resources.java:466)
	at androidx.fragment.app.Fragment.getString(Fragment.java:873)
	at org.schabi.newpipe.local.feed.FeedFragment.updateRefreshViewState(FeedFragment.kt:283)
	at org.schabi.newpipe.local.feed.FeedFragment.updateRelativeTimeViews(FeedFragment.kt:273)
	at org.schabi.newpipe.local.feed.FeedFragment.onResume(FeedFragment.kt:83)
	at androidx.fragment.app.Fragment.performResume(Fragment.java:2649)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:922)
	at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
	at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
	at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
	at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
	at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
	at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
	at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```
</p></details>
<hr>

**Comment by wb9688** [comment]
Does it work when switching app language to English?

**Comment by Etua** [comment]
It does, for some reason I missed that bug when searching for duplicates.
