### ISSUE TITLE
Most music-related videos un-parseable

### ISSUE THREAD

**Issue by Christopher-Peterson** [TeamNewPipe/NewPipe#3667]
### Version

- 0.19.3

### Steps to reproduce the bug

1. Search for music-related videos
2. Attempt to open, play, or enqueue the results.

A few videos that trigger the bug:

https://www.youtube.com/watch?v=0G383538qzQ
https://www.youtube.com/watch?v=AZm1_jtY1SQ
https://www.youtube.com/watch?v=6vwNcNOTVzY
https://www.youtube.com/watch?v=zqNTltOGh5c

A few videos that don't trigger the bug
https://www.youtube.com/watch?v=UayFuEbHxrs
https://www.youtube.com/watch?v=ZxnVYd3TpJs
https://www.youtube.com/watch?v=krv9J3KZu3I

### Expected behavior

The video opens, plays, or enqueues, or loads in some manner

### Actual behaviour

Guru Mediation: Could not parse website

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=0G383538qzQ
* __Content Language:__ US
* __Service:__ YouTube
* __Version:__ 0.19.3
* __OS:__ Linux Android 7.1.2 - 25

<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:192)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:70)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:62)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(lambda)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14479)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4154)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3438)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

```
</p></details>
<hr>

**Comment by wb9688** [comment]
See the pinned issue. The contribution guidelines, which you should've read, clearly say to look for existing issies first.

**Comment by theScrabi** [comment]
@wb9688 but from the title of #3576 i wouldn't have gieset it was related to only music. Honestly I'd have done the same as @Christopher-Peterson

**Comment by B0pol** [comment]
It's not only related to music, I saw films, or random vlog videos, though indeed it's more frequent with music
