### ISSUE TITLE
Searching on soundcloud sometimes will crash the app

### ISSUE THREAD

**Issue by surrodox2001** [TeamNewPipe/NewPipe#3677]
When searching on soundcloud with latest version, sometimes the search suggestions? will cause an error.

The error seemingly doesn't appear when New & hot is selected before searching.

## Exception
* __User Action:__ get suggestions
* __Request:__ none
* __Content Language:__ MY
* __Service:__ SoundCloud
* __Version:__ 0.19.4
* __OS:__ Linux Android 5.1 - 22

<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse json response
	at org.schabi.newpipe.extractor.services.soundcloud.extractors.SoundcloudSuggestionExtractor.suggestionList(SoundcloudSuggestionExtractor.java:48)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$suggestionsFor$2(ExtractorHelper.java:107)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$kAwiU5Tjeit-NCwHTWhD3V6UHS8.call(lambda)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleToObservable.subscribeActual(SingleToObservable.java:35)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableZip$ZipCoordinator.subscribe(ObservableZip.java:110)
	at io.reactivex.internal.operators.observable.ObservableZip.subscribeActual(ObservableZip.java:72)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMaterialize.subscribeActual(ObservableMaterialize.java:28)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSwitchMap$SwitchMapObserver.onNext(ObservableSwitchMap.java:127)
	at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
	at io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver$DelayErrorInnerObserver.onNext(ObservableConcatMap.java:506)
	at io.reactivex.observers.SerializedObserver.onNext(SerializedObserver.java:111)
	at io.reactivex.internal.operators.observable.ObservableDebounceTimed$DebounceTimedObserver.emit(ObservableDebounceTimed.java:143)
	at io.reactivex.internal.operators.observable.ObservableDebounceTimed$DebounceEmitter.run(ObservableDebounceTimed.java:168)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: com.grack.nanojson.JsonParserException: Expected JSON value, got 0 on line 1, char 0
	at com.grack.nanojson.JsonTokener.createParseException(Unknown Source)
	at com.grack.nanojson.JsonParser.currentValue(Unknown Source)
	at com.grack.nanojson.JsonParser.parse(Unknown Source)
	at com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source)
	at org.schabi.newpipe.extractor.services.soundcloud.extractors.SoundcloudSuggestionExtractor.suggestionList(SoundcloudSuggestionExtractor.java:41)
	... 27 more

```
</p></details>
<hr>

**Comment by ganderson04** [comment]
This is happening on all three tabs for me on Android 10.

**Comment by Stypox** [comment]
#2915
