### ISSUE TITLE
"New & Hot" & "Top 50" songs' list is not getting displayed

### ISSUE THREAD

**Issue by SArsalanK** [TeamNewPipe/NewPipe#3693]
Device: 
Xiaomi Redmi S2

Version: 
0.19.5

Problem:
"New & Hot" & "Top 50" songs' list is not getting displayed for SoundCloud. Please see attachment.

![Screenshot_2020-05-31-05-50-02-534_org schabi newpipe debug](https://user-images.githubusercontent.com/2125947/83341976-eece9700-a302-11ea-96cb-9b042a10a01b.jpg)

**Comment by B0pol** [comment]
I can't reproduce. What is your setting for Content country in settings -> content -> content country?
if system default, what is your phone language?

**Comment by wb9688** [comment]
If that happens, does searching, etc also not work?

**Comment by SArsalanK** [comment]
> I can't reproduce. What is your setting for Content country in settings -> content -> content country?
> if system default, what is your phone language?

Its System Default for all settings.
Phone Language is English

**Comment by SArsalanK** [comment]
> If that happens, does searching, etc also not work?

Yes, searching works

**Comment by wb9688** [comment]
What country, etc have you set? And is there an error toast?

**Comment by SArsalanK** [comment]
> What country, etc have you set? And is there an error toast?

I haven't set any. It's the default.
No, there is no error toast.

**Comment by wb9688** [comment]
So it says "System default" under default content country and language in Settings -> Content? If so, could you tell what language and country you have set in Android's settings?

**Comment by SArsalanK** [comment]
> So it says "System default" under default content country and language in Settings -> Content? 
YES
If so, could you tell what language and country you have set in Android's settings?
Language : ENGLISH (UK)
Country : RUSSIA

**Comment by FireMasterK** [comment]
## Exception
* __User Action:__ requested kiosk
* __Request:__ https://soundcloud.com/charts/top
* __Content Language:__ US
* __Service:__ SoundCloud
* __Version:__ 0.19.5
* __OS:__ Linux Android 10 - 29


<details><summary><b>Crash log</b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse json response
	at org.schabi.newpipe.extractor.services.soundcloud.SoundcloudParsingHelper.getStreamsFromApi(SoundcloudParsingHelper.java:239)
	at org.schabi.newpipe.extractor.services.soundcloud.extractors.SoundcloudChartsExtractor.computeNextPageAndStreams(SoundcloudChartsExtractor.java:68)
	at org.schabi.newpipe.extractor.services.soundcloud.extractors.SoundcloudChartsExtractor.getInitialPage(SoundcloudChartsExtractor.java:83)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)
	at org.schabi.newpipe.extractor.kiosk.KioskInfo.getInfo(KioskInfo.java:72)
	at org.schabi.newpipe.extractor.kiosk.KioskInfo.getInfo(KioskInfo.java:58)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getKioskInfo$11(ExtractorHelper.java:184)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$3nu_IUHVaX-6ert-LLLuUGJnfDU.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: com.grack.nanojson.JsonParserException: Expected JSON value, got 0 on line 1, char 0
	at com.grack.nanojson.JsonTokener.createParseException(Unknown Source:44)
	at com.grack.nanojson.JsonParser.currentValue(Unknown Source:31)
	at com.grack.nanojson.JsonParser.parse(Unknown Source:4)
	at com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source:19)
	at org.schabi.newpipe.extractor.services.soundcloud.SoundcloudParsingHelper.getStreamsFromApi(SoundcloudParsingHelper.java:237)
	... 31 more

```
</p></details>
<hr>

**Comment by FireMasterK** [comment]
On a side note, nothing works for me in SoundCloud. I can't search, I can't see any of the charts too.

**Comment by aasutossh** [comment]
Searching works, but Hot and Top 50 doesn't work for me too. Never worked.

**Comment by wb9688** [comment]
@aasutossh: What content country & language have you set in NewPipe's settings (under Content)? I think the "New & Hot" and "Top 50" issue might be related to that.

@FireMasterK: SoundCloud in general not working sometimes is a different issue.

**Comment by aasutossh** [comment]
@wb9688 Content country is Nepal. But changing it doesn't affect anything.

I tried clearing data, but I still get No Videos showing up.

I tried NewPipe Legacy, and there SoundCloud features work without any hassle. I even changed the content country to Nepal. Still works.

**Comment by wb9688** [comment]
@aasutossh: What version of NewPipe Legacy is that?

**Comment by aasutossh** [comment]
0.18.2, I got it from F Droid.

**Comment by wb9688** [comment]
@aasutossh: Could you confirm that v0.19.2 doesn't have the issue while v0.19.3 has the issue? I think that's where a relevant change happened.

**Comment by aasutossh** [comment]
0.19.2 lists, but trying to play results in error.
```
{
   "user_action": "requested stream",
   "request": "https:\/\/soundcloud.com\/uiceheidd\/tell-me-you-love-me",
   "content_language": "en_US",
   "service": "SoundCloud",
   "package": "org.schabi.newpipe",
   "version": "0.19.2",
   "os": "Linux Android 6.0.1 - 23",
   "time": "2020-06-03 07:40",
   "exceptions": [
      "org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:189)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:69)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:61)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:120)\n\tat org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(lambda)\n\tat io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4154)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)\n\tat io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)\n\tat io.reactivex.Flowable.subscribe(Flowable.java:14479)\n\tat io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)\n\tat io.reactivex.Maybe.subscribe(Maybe.java:4154)\n\tat io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)\n\tat io.reactivex.Single.subscribe(Single.java:3438)\n\tat io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)\n\tat io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:237)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)\n\tat java.lang.Thread.run(Thread.java:818)\n"
   ],
   "user_comment": ""
}
```

Turns out, only one track produces this error. I can play others. The track is new & hot #1 https://soundcloud.com/uiceheidd/tell-me-you-love-me.

I'll test 0.19.3 then update this.

**Comment by githammerer** [comment]
Can't display New & Hot and Top 50 and can't search, content language is United Kingdom.


<details>
  <summary>Crash log for New & Hot and Top 50:</summary>

```
{"user_action":"get suggestions","request":"none","content_language":"en_GB","service":"SoundCloud","package":"org.schabi.newpipe","version":"0.19.5","os":"Linux Android 9 - 28","time":"2020-06-30 22:58","exceptions":["org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse json response\n\tat org.schabi.newpipe.extractor.services.soundcloud.extractors.SoundcloudSuggestionExtractor.suggestionList(SoundcloudSuggestionExtractor.java:48)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$suggestionsFor$2(ExtractorHelper.java:107)\n\tat org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$kAwiU5Tjeit-NCwHTWhD3V6UHS8.call(Unknown Source:4)\n\tat io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)\n\tat io.reactivex.Single.subscribe(Single.java:3666)\n\tat io.reactivex.internal.operators.single.SingleToObservable.subscribeActual(SingleToObservable.java:35)\n\tat io.reactivex.Observable.subscribe(Observable.java:12284)\n\tat io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)\n\tat io.reactivex.Observable.subscribe(Observable.java:12284)\n\tat io.reactivex.internal.operators.observable.ObservableZip$ZipCoordinator.subscribe(ObservableZip.java:110)\n\tat io.reactivex.internal.operators.observable.ObservableZip.subscribeActual(ObservableZip.java:72)\n\tat io.reactivex.Observable.subscribe(Observable.java:12284)\n\tat io.reactivex.internal.operators.observable.ObservableMaterialize.subscribeActual(ObservableMaterialize.java:28)\n\tat io.reactivex.Observable.subscribe(Observable.java:12284)\n\tat io.reactivex.internal.operators.observable.ObservableSwitchMap$SwitchMapObserver.onNext(ObservableSwitchMap.java:127)\n\tat io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)\n\tat io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver$DelayErrorInnerObserver.onNext(ObservableConcatMap.java:506)\n\tat io.reactivex.observers.SerializedObserver.onNext(SerializedObserver.java:111)\n\tat io.reactivex.internal.operators.observable.ObservableDebounceTimed$DebounceTimedObserver.emit(ObservableDebounceTimed.java:143)\n\tat io.reactivex.internal.operators.observable.ObservableDebounceTimed$DebounceEmitter.run(ObservableDebounceTimed.java:168)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:764)\nCaused by: com.grack.nanojson.JsonParserException: Expected JSON value, got 0 on line 1, char 0\n\tat com.grack.nanojson.JsonTokener.createParseException(Unknown Source:44)\n\tat com.grack.nanojson.JsonParser.currentValue(Unknown Source:31)\n\tat com.grack.nanojson.JsonParser.parse(Unknown Source:4)\n\tat com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source:19)\n\tat org.schabi.newpipe.extractor.services.soundcloud.extractors.SoundcloudSuggestionExtractor.suggestionList(SoundcloudSuggestionExtractor.java:41)\n\t... 26 more\n"],"user_comment":""}

--------
```
</details>

<details>
  <summary>Crash log for searching:</summary>

```
{"user_action":"get suggestions","request":"test","content_language":"en_GB","service":"SoundCloud","package":"org.schabi.newpipe","version":"0.19.5","os":"Linux Android 9 - 28","time":"2020-06-30 22:59","exceptions":["org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse json response\n\tat org.schabi.newpipe.extractor.services.soundcloud.extractors.SoundcloudSuggestionExtractor.suggestionList(SoundcloudSuggestionExtractor.java:48)\n\tat org.schabi.newpipe.util.ExtractorHelper.lambda$suggestionsFor$2(ExtractorHelper.java:107)\n\tat org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$kAwiU5Tjeit-NCwHTWhD3V6UHS8.call(Unknown Source:4)\n\tat io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)\n\tat io.reactivex.Single.subscribe(Single.java:3666)\n\tat io.reactivex.internal.operators.single.SingleToObservable.subscribeActual(SingleToObservable.java:35)\n\tat io.reactivex.Observable.subscribe(Observable.java:12284)\n\tat io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)\n\tat io.reactivex.Observable.subscribe(Observable.java:12284)\n\tat io.reactivex.internal.operators.observable.ObservableZip$ZipCoordinator.subscribe(ObservableZip.java:110)\n\tat io.reactivex.internal.operators.observable.ObservableZip.subscribeActual(ObservableZip.java:72)\n\tat io.reactivex.Observable.subscribe(Observable.java:12284)\n\tat io.reactivex.internal.operators.observable.ObservableMaterialize.subscribeActual(ObservableMaterialize.java:28)\n\tat io.reactivex.Observable.subscribe(Observable.java:12284)\n\tat io.reactivex.internal.operators.observable.ObservableSwitchMap$SwitchMapObserver.onNext(ObservableSwitchMap.java:127)\n\tat io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)\n\tat io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver$DelayErrorInnerObserver.onNext(ObservableConcatMap.java:506)\n\tat io.reactivex.observers.SerializedObserver.onNext(SerializedObserver.java:111)\n\tat io.reactivex.internal.operators.observable.ObservableDebounceTimed$DebounceTimedObserver.emit(ObservableDebounceTimed.java:143)\n\tat io.reactivex.internal.operators.observable.ObservableDebounceTimed$DebounceEmitter.run(ObservableDebounceTimed.java:168)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)\n\tat io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)\n\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)\n\tat java.lang.Thread.run(Thread.java:764)\nCaused by: com.grack.nanojson.JsonParserException: Expected JSON value, got 0 on line 1, char 0\n\tat com.grack.nanojson.JsonTokener.createParseException(Unknown Source:44)\n\tat com.grack.nanojson.JsonParser.currentValue(Unknown Source:31)\n\tat com.grack.nanojson.JsonParser.parse(Unknown Source:4)\n\tat com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source:19)\n\tat org.schabi.newpipe.extractor.services.soundcloud.extractors.SoundcloudSuggestionExtractor.suggestionList(SoundcloudSuggestionExtractor.java:41)\n\t... 26 more\n"],"user_comment":""}

--------
```
</details>

**Comment by allendema** [comment]
Try updating to latest relase.

**Comment by opusforlife2** [comment]
And drop a comment if the issue still exists.

**Comment by FireMasterK** [comment]
![Screenshot_20200816-173651_NewPipe](https://user-images.githubusercontent.com/20838718/90333991-0ce59280-dfe8-11ea-9caa-cefb2cbe966a.png)
Not sure if this is related but there's no errors or bugs reported by NewPipe.
