### ISSUE TITLE
NoNonsense-File-Picker: Crash when a file is deleted and redownloaded

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipe#3782]
### Version

- 0.19.5

### Steps to reproduce the bug

1. Ensure SAF is off. The bug doesn't occur for SAF.
2. Download a file.
3. Delete it from your file explorer app. Notice the entry remains in the Downloads activity.
4. Download the same file again. -> Crash.

If you first close the app, then do this, it works fine. I suspect it is because the download menu entry gets removed upon closing the app.

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ en_IN
* __Service:__ none
* __Version:__ 0.19.5
* __OS:__ Linux Android 9 - 28

<details><summary><b>Crash log</b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equalsIgnoreCase(java.lang.String)' on a null object reference
	at us.shandian.giga.io.StoredFileHelper.equals(StoredFileHelper.java:319)
	at us.shandian.giga.service.DownloadManager.getFinishedMissionIndex(DownloadManager.java:340)
	at us.shandian.giga.service.DownloadManager.checkForExistingMission(DownloadManager.java:501)
	at org.schabi.newpipe.download.DownloadDialog.checkSelectedDownload(DownloadDialog.java:739)
	at org.schabi.newpipe.download.DownloadDialog.prepareSelectedDownload(DownloadDialog.java:712)
	at org.schabi.newpipe.download.DownloadDialog.lambda$initToolbar$4$DownloadDialog(DownloadDialog.java:452)
	at org.schabi.newpipe.download.-$$Lambda$DownloadDialog$ERBEc9wJhJOkaeWUyVXNR5O1TqU.onMenuItemClick(Unknown Source:2)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:981)
	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:625)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
	at android.view.View.performClick(View.java:6597)
	at android.view.View.performClickInternal(View.java:6574)
	at android.view.View.access$3100(View.java:778)
	at android.view.View$PerformClick.run(View.java:25906)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```
</p></details>
<hr>

**Comment by wb9688** [comment]
With or without my SAF PR? Or both? I'll probably fix it tomorrow if I could reproduce.

**Comment by opusforlife2** [comment]
With _and_ without. This is the release version I've logged. It also happens on other debug apks I've tested. So it is independent of your PR.
