### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by be-neth** [TeamNewPipe/NewPipe#386]
Hello,

I cannot use Newpipe when using my VPN on Android 7.
From logcat when searching "test" video I have the following exception :

~~~~
12-04 11:07:43.719 20419 23161 W System.err: java.io.IOException: java.io.FileNotFoundException: https://www.youtube.com/results?search_query=test&page=0&filters=video
12-04 11:07:43.720 20419 23161 W System.err:    at org.schabi.newpipe.Downloader.dl(Downloader.java:88)
12-04 11:07:43.721 20419 23161 W System.err:    at org.schabi.newpipe.Downloader.download(Downloader.java:65)
12-04 11:07:43.721 20419 23161 W System.err:    at org.schabi.newpipe.Downloader.download(Downloader.java:47)
12-04 11:07:43.721 20419 23161 W System.err:    at org.schabi.newpipe.extractor.services.youtube.YoutubeSearchEngine.search(YoutubeSearchEngine.java:88)
12-04 11:07:43.721 20419 23161 W System.err:    at org.schabi.newpipe.extractor.SearchResult.getSearchResult(SearchResult.java:32)
12-04 11:07:43.721 20419 23161 W System.err:    at org.schabi.newpipe.search_fragment.SearchWorker$SearchRunnable.run(SearchWorker.java:103)
12-04 11:07:43.721 20419 23161 W System.err:    at java.lang.Thread.run(Thread.java:761)
12-04 11:07:43.722 20419 23161 W System.err: Caused by: java.io.FileNotFoundException: https://www.youtube.com/results?search_query=test&page=0&filters=video
12-04 11:07:43.722 20419 23161 W System.err:    at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:250)
12-04 11:07:43.722 20419 23161 W System.err:    at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
12-04 11:07:43.722 20419 23161 W System.err:    at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
12-04 11:07:43.722 20419 23161 W System.err:    at org.schabi.newpipe.Downloader.dl(Downloader.java:78)
12-04 11:07:43.722 20419 23161 W System.err:    ... 6 more
~~~~

And when I am connecting to youtube via a browser, I need to enter a captcha before accessing any video.
I am suspecting that this is the cause of my issue. If I disable the VPN connection it works fine.

Do you think we can implement the captcha system into newpipe application ?

Thanks.

Ps: if you use Newpipe via tor network, I suspect you will have the same issue.

**Comment by theScrabi** [comment]
This is probbably the problem with tor. So yes we need a captcha system.

**Comment by be-neth** [comment]
Hi @theScrabi ,
Just to say that I am trying to work on it.

I have done a basic and ugly implementation but it works!
I will try to clean it and send to you a pull request.

I am not very familiar with Android development (And Java in general) but NewPipe code seems to me rather simple to read :)Thanks !

**Comment by theScrabi** [comment]
I saw the commit thank you for that :) I'll check it later.

**Comment by be-neth** [comment]
updated see : #404 .
(Not a joke :) )

**Comment by theScrabi** [comment]
All right merged, and released :)
