### ISSUE TITLE
Crashing When Deleting From Playlist Tab

### ISSUE THREAD

**Issue by nate2014jatc** [TeamNewPipe/NewPipe#3891]
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.19.6
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
java.lang.ArrayIndexOutOfBoundsException: length=15; index=-1
	at java.util.ArrayList.remove(ArrayList.java:506)
	at org.schabi.newpipe.local.LocalItemListAdapter.removeItem(LocalItemListAdapter.java:128)
	at org.schabi.newpipe.local.playlist.LocalPlaylistFragment.deleteItem(LocalPlaylistFragment.java:621)
	at org.schabi.newpipe.local.playlist.LocalPlaylistFragment.lambda$showStreamItemDialog$19$LocalPlaylistFragment(LocalPlaylistFragment.java:791)
	at org.schabi.newpipe.local.playlist.-$$Lambda$LocalPlaylistFragment$90syoQLDH9fDdmrHKGkSeGndyvo.onClick(Unknown Source:4)
	at org.schabi.newpipe.util.StreamDialogEntry.clickOn(StreamDialogEntry.java:105)
	at org.schabi.newpipe.local.playlist.LocalPlaylistFragment.lambda$showStreamItemDialog$20$LocalPlaylistFragment(LocalPlaylistFragment.java:794)
	at org.schabi.newpipe.local.playlist.-$$Lambda$LocalPlaylistFragment$XkVgE8RSZjjT9Ft0r7B-0GYSTrk.onClick(Unknown Source:4)
	at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1169)
	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1192)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3169)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6758)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```
</details>
<hr>
~~Could be related to #3887 but this has a different crash log.~~

My mistake, it was actually caused when I was deleting a video from a local Playlist.

**Comment by wb9688** [comment]
What exactly did you do? Please just fill in the whole issue template.

That error seems to happen from trying to remove an item…

**Comment by nate2014jatc** [comment]
You are correct, my apologies.
it was caused when I was removing an item from a Playlist.
I have updated the title and body accordingly.
what data am I missing from the report? I pasted it directly from the app.

**Comment by opusforlife2** [comment]
@nate2014jatc Has this happened since or was it a one-off?

**Comment by sauravrao637** [comment]
@nate2014jatc can you please test the apk generated by [PR#6127](https://github.com/TeamNewPipe/NewPipe/pull/6127)

**Comment by nate2014jatc** [comment]
Let me make sure this is still a bug, and then I'll try the new version.

**Comment by nate2014jatc** [comment]
This appears to no longer be an issue on 0.21.2.

**Comment by mustanggb** [comment]
With 0.21.15 it still occurs.
