### ISSUE TITLE
Error while opening content in browser

### ISSUE THREAD

**Issue by drov-drov** [TeamNewPipe/NewPipe#3925]
### Version

0.19.6

### Steps to reproduce the bug

1. Go to 'info about video'
2. Press on 'open in browser'

### Expected behavior

Opening url in browser.

### Actual behaviour

UI crashes

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Language:__ ru
* __Service:__ none
* __Version:__ 0.19.6
* __OS:__ Linux Android 7.0 - 24

<details><summary><b>Crash log</b></summary><p>

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://www.youtube.com/... pkg=com.huawei.android.internal.app }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1854)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1544)
	at android.app.Activity.startActivityForResult(Activity.java:4391)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
	at android.app.Activity.startActivityForResult(Activity.java:4335)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
	at android.app.Activity.startActivity(Activity.java:4697)
	at android.app.Activity.startActivity(Activity.java:4665)
	at org.schabi.newpipe.util.ShareUtils.openUrlInBrowser(ShareUtils.java:36)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.onOptionsItemSelected(VideoDetailFragment.java:702)
	at androidx.fragment.app.Fragment.performOptionsItemSelected(Fragment.java:2830)
	at androidx.fragment.app.FragmentManager.dispatchOptionsItemSelected(FragmentManager.java:2717)
	at androidx.fragment.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:412)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:389)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:219)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:64)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:313)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1203)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3197)
	at android.widget.AbsListView$3.run(AbsListView.java:4140)
	at android.os.Handler.handleCallback(Handler.java:761)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6617)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

```
</p></details>
<hr>

**Comment by Stypox** [comment]
Apparently there is no default browser on your phone and neither there is an application able to handle that url. 
Btw, please use the [Incredible Error Report to Markdown Converter](https://teamnewpipe.github.io/CrashReportToMarkdown/) before sending bug reports next time, as you should have been told when creating the issue, or copy the formatted report directly from the app.

**Comment by test2a** [comment]
@Stypox i had the same error in https://github.com/TeamNewPipe/NewPipe/issues/4140 and setting the default browser did the trick. How about there is an error message instead of a crash?

**Comment by wb9688** [comment]
Imho we should catch that exception and fall back to a regular share

**Comment by TiA4f8R** [comment]
@Stypox I have this bug too on my device, an Honor 9X, running EMUI 10. Even if I'm not an Android developer, I tried something (here is [my code](https://github.com/TiA4f8R/NewPipe/blob/TiA4f8R-fix-crash-open-in-browser/app/src/main/java/org/schabi/newpipe/util/ShareUtils.java#L38-L46)) and it works: I can select in which app I want to open the content. Can you please take a look at code and say if code is good, and if yes, can I open a PR?
(Note also that I'm new to GitHub so please be indulgent with me.)

Debug APK to test: [NewPipe fix open in browser.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/5609135/NewPipe.fix.open.in.browser.apk.zip)

Thanks in advance.

**Comment by TiA4f8R** [comment]
@test2a @DrovGamedev With my debug apk above, when setting no default browser on your device, did you get a list of apps to open the URL (when using open in browser command), or something else?
Thanks in advance for your answer.

**Comment by test2a** [comment]
@TiA4f8R hi. i just checked your debug app but just like .20.4, if i click on globe icon, a new newpipe app opens and video plays. i think it might be due to url intent given to newpipe for opening all youtube apps. because i still have no default browser, it is falling back to url intent.

clicking on any other link in the descrption for example opens the browser intent popup correctly.

**Comment by TiA4f8R** [comment]
@test2a does it opens the NewPipe release or my debug APK? Here is my behavior on my device:

![Screenshot Open in Browser NewPipe debug.jpg](https://user-images.githubusercontent.com/74829229/100639229-31664000-3335-11eb-8523-466b98bf2416.jpg)

**Comment by test2a** [comment]
![recording_20201130_223713](https://user-images.githubusercontent.com/39449563/100640986-f5df6c00-335c-11eb-96cd-8127122974ff.gif)

no. it opens the installed base newpipe. i have that sponsorblock apk also installed, but plain newpipe opens always

**Comment by TiA4f8R** [comment]
@test2a Can you go to Settings, Apps, NewPipe release v0.20.4, Open by default and check if the Remove default settings button is clickable? If yes, tap it and retry and let me now.
About the links in description, I didn't normally change nothing with my APK.

**Comment by TiA4f8R** [comment]
@test2a If you want to test if my fix is working in an other way, you can also share a URL which NewPipe can't open to my debug APK and use Open in browser command. If a list of apps is showing, it means that my fix is working.

**Comment by test2a** [comment]
OK. I checked the settings. I have set "open supported links" as "aways in this app". If I set it to don't open,  then it works as expected.

Dunno. Is there a way around this?  If I set to always open, this would always happen unless there is some way to break the URL intent somehow

**Comment by TiA4f8R** [comment]
@test2a I don't really know, I think not, but I am not an Android developer. May be someone from NewPipe's team can really answer you, like @TobiGr or @Stypox.
Just beacuse I am curious, can you share a screenshot of your "Open in browser" dialog?

**Comment by test2a** [comment]
![Screenshot_20201130-232952](https://user-images.githubusercontent.com/39449563/100646591-38f10d80-3364-11eb-947d-d07f4b0e38d3.png)

this is your debug app click on browser button with newpipe dont open default links set

**Comment by TiA4f8R** [comment]
(@test2a If you want to have the NewPipe release back in the list, don't forget to set "open supported links" as "always ask" in your Android settings for the app.)

So this bug should be fixed thanks a lot for testing this!

**Comment by test2a** [comment]
Sounds a nice compromise. Thanks.

**Comment by TiA4f8R** [comment]
@test2a Can you test my APK in #5129 and let me know if all works? Thanks in advance.
