### ISSUE TITLE
Newpipe crashing on startup

### ISSUE THREAD

**Issue by CactiChameleon9** [TeamNewPipe/NewPipe#3995]
## Exception
* __User Action:__ something
* __Request:__ Bookmark
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.19.8
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN): Could not open database
	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:197)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:915)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:895)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:759)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:748)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:374)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:317)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:92)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:53)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:476)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:281)
	at androidx.room.RoomDatabase.query(RoomDatabase.java:324)
	at androidx.room.util.DBUtil.query(DBUtil.java:83)
	at org.schabi.newpipe.database.playlist.dao.PlaylistRemoteDAO_Impl$6.call(PlaylistRemoteDAO_Impl.java:285)
	at org.schabi.newpipe.database.playlist.dao.PlaylistRemoteDAO_Impl$6.call(PlaylistRemoteDAO_Impl.java:282)
	at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:46)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.onNext(FlowableFlatMapMaybe.java:132)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:407)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</details>
<hr>

I uninstalled the fdroid version and installed the latest, and when I open it I get the error above. I have cleared data just to be sure. I do not have play services if that matters.

**Comment by Stypox** [comment]
Try to manually grant NewPipe the permission to write to external storage (it shouldn't matter, but maybe it helps)

**Comment by CactiChameleon9** [comment]
Nope... still crashing

**Comment by wb9688** [comment]
Does this occur when you re-install? And does this occur when you install v0.19.7?

**Comment by CactiChameleon9** [comment]
Very odd.... I redownloaded, and uninstalled and reinstalled and it now works. Maybe the first download was corrupt?

**Comment by wb9688** [comment]
@CactiChameleon9: If the download is corrupt, it won't install. What phone do you have?

**Comment by CactiChameleon9** [comment]
I am have Samsung galaxy tab A (2016) with a unofficial Lineage OS with microg rooted with magisk and

**Comment by ravilov** [comment]
Sounds like some stuff got left over from the previous install and wasn't cleaned up properly by the OS when you uninstalled. Completely removing `/data/data/org.schabi.newpipe/` should do the trick. But I see you got it working anyway.

**Comment by CactiChameleon9** [comment]
@ravilov The odd thing is I tried that, IDK what happened really to make it crash.
