### ISSUE TITLE
Database Read Crash on fresh install of v0.19.8

### ISSUE THREAD

**Issue by Yowlen** [TeamNewPipe/NewPipe#4007]
### Version

- v0.19.8 (GitHub version)
Update: Just found out about your F-Droid repo and decided to test that version too. That one works fine, so this is apparently only applicable to the GitHub apk.

### Steps to reproduce the bug

Install, then start it up.

### Expected behavior

It goes to the main screen without issue.
### Actual behaviour

It briefly shows the main screen without any content, then shows an error report about not being able to open a database.
## Exception
* __User Action:__ something
* __Request:__ Bookmark
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.19.8
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN): Could not open database
	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:211)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:195)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:503)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:204)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:196)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:880)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:865)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:739)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:729)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:355)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:298)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:92)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:53)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:476)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:281)
	at androidx.room.RoomDatabase.query(RoomDatabase.java:324)
	at androidx.room.util.DBUtil.query(DBUtil.java:83)
	at org.schabi.newpipe.database.playlist.dao.PlaylistRemoteDAO_Impl$6.call(PlaylistRemoteDAO_Impl.java:285)
	at org.schabi.newpipe.database.playlist.dao.PlaylistRemoteDAO_Impl$6.call(PlaylistRemoteDAO_Impl.java:282)
	at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:46)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.onNext(FlowableFlatMapMaybe.java:132)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:407)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```
</details>
<hr>

**Comment by Stypox** [comment]
This is probably caused by uninstall issues, see #3995
