### ISSUE TITLE
Newpipe crashes when Wifi connection gets lost 

### ISSUE THREAD

**Issue by Flo082002** [TeamNewPipe/NewPipe#4008]
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ GB
* __Content Language:__ en
* __App Language:__ de_DE
* __Service:__ none
* __Version:__ 0.19.8
* __OS:__ Linux Android 8.0.0 - 26
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Thread.isAlive()' on a null object reference
	at us.shandian.giga.get.DownloadMission.joinForThreads(DownloadMission.java:816)
	at us.shandian.giga.get.DownloadMission.pauseThreads(DownloadMission.java:520)
	at us.shandian.giga.get.DownloadMission.notifyError(DownloadMission.java:362)
	at us.shandian.giga.get.DownloadMission.notifyError(DownloadMission.java:308)
	at us.shandian.giga.get.DownloadRunnable.run(DownloadRunnable.java:145)

```
</details>
<hr>

When I download videos and the Wifi connection gets lost, newpipe crashes.

**Comment by FireMasterK** [comment]
Could reproduce this on Android 10, here's the reproduction steps:
1. Start downloading something
2. While it's downloading, turn off your wifi and mobile data
3. Open the app and close it (not sure if necessary)
4. Turn on WiFi back on

Not too sure, but this may be blocked/fixed by #962

**Comment by NicolasToussaint** [comment]
If it helps, just reproduced this.
I switched WiFi connection less than a minute before the crash.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.25.2
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Thread.isAlive()' on a null object reference
	at us.shandian.giga.get.DownloadMission.joinForThreads(DownloadMission.java:814)
	at us.shandian.giga.get.DownloadMission.pauseThreads(DownloadMission.java:518)
	at us.shandian.giga.get.DownloadMission.notifyError(DownloadMission.java:360)
	at us.shandian.giga.get.DownloadMission.notifyError(DownloadMission.java:308)
	at us.shandian.giga.get.DownloadRunnable.run(DownloadRunnable.java:145)

```
</details>
<hr>
