### ISSUE TITLE
Crash when closing the background player

### ISSUE THREAD

**Issue by FireMasterK** [TeamNewPipe/NewPipe#4024]
### Version
- 0.19.8

### Steps to reproduce the bug
Not too sure if this reproducible, here's what I did before I got the crash screen.
1. I played a video in background mode
2. Paused it
3. Opened other apps for ~15 minutes
4. Clicked on the play button
4. Immediately clicked on the close button
5. Get the crash report screen

### Expected behavior
The notification goes away without crashing

### Actual behaviour
The app crashed when I clicked on the close button

### Screenshots/Screen recordings
NA, this is the first time this has happened

### Additional Context
I have battery saver on, a custom rom with "Agressive Battery" enabled, this is likely a software specific issue.

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ US
* __Content Language:__ en
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.19.8
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to read from field 'org.schabi.newpipe.player.helper.MediaSessionManager org.schabi.newpipe.player.BasePlayer.mediaSessionManager' on a null object reference
	at org.schabi.newpipe.player.BackgroundPlayer.setLockScreenThumbnail(BackgroundPlayer.java:236)
	at org.schabi.newpipe.player.BackgroundPlayer.createNotification(BackgroundPlayer.java:221)
	at org.schabi.newpipe.player.BackgroundPlayer.resetNotification(BackgroundPlayer.java:199)
	at org.schabi.newpipe.player.BackgroundPlayer.access$100(BackgroundPlayer.java:67)
	at org.schabi.newpipe.player.BackgroundPlayer$BasePlayerImpl.onLoadingComplete(BackgroundPlayer.java:403)
	at com.nostra13.universalimageloader.core.DisplayBitmapTask.run(DisplayBitmapTask.java:72)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7361)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

```
</details>
<hr>

**Comment by opusforlife2** [comment]
It's a one-off bug, but could this have been solved by the Unified Player or the MediaStyle notification?

**Comment by FireMasterK** [comment]
Possible, I'll close this as this was in 0.19.8.
