### ISSUE TITLE
View hierarchy touched by a wrong thread

### ISSUE THREAD

**Issue by crazo7924** [TeamNewPipe/NewPipe#4030]
### Steps to reproduce the bug

Its not reproducible always
1. Open main page content editor
2. Add a playlist tab

### Expected behavior

No error should be left uncaught

### Actual behaviour

An ui error occurred because it was not handled properly

## Exception
* __User Action:__ ui error
* __Request:__ 
* __Content Country:__ IN
* __Content Language:__ en-IN
* __App Language:__ en_IN
* __Service:__ none
* __Version:__ 0.19.8
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7760)
	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1225)
	at android.view.View.requestLayout(View.java:23114)
	at android.view.View.requestLayout(View.java:23114)
	at android.view.View.requestLayout(View.java:23114)
	at android.view.View.requestLayout(View.java:23114)
	at android.view.View.requestLayout(View.java:23114)
	at android.view.View.setFlags(View.java:14102)
	at android.view.View.setVisibility(View.java:9992)
	at org.schabi.newpipe.settings.SelectPlaylistFragment.displayPlaylists(SelectPlaylistFragment.java:143)
	at org.schabi.newpipe.settings.SelectPlaylistFragment.lambda$OKidrRDkz4wytGdEytcZ56EPSTU(Unknown Source:0)
	at org.schabi.newpipe.settings.-$$Lambda$SelectPlaylistFragment$OKidrRDkz4wytGdEytcZ56EPSTU.accept(Unknown Source:4)
	at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65)
	at io.reactivex.internal.operators.flowable.FlowableCombineLatest$CombineLatestCoordinator.drainAsync(FlowableCombineLatest.java:374)
	at io.reactivex.internal.operators.flowable.FlowableCombineLatest$CombineLatestCoordinator.drain(FlowableCombineLatest.java:406)
	at io.reactivex.internal.operators.flowable.FlowableCombineLatest$CombineLatestCoordinator.innerValue(FlowableCombineLatest.java:250)
	at io.reactivex.internal.operators.flowable.FlowableCombineLatest$CombineLatestInnerSubscriber.onNext(FlowableCombineLatest.java:521)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onNext(FlowableSubscribeOn.java:97)
	at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.innerSuccess(FlowableFlatMapMaybe.java:175)
	at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber$InnerObserver.onSuccess(FlowableFlatMapMaybe.java:397)
	at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:61)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.onNext(FlowableFlatMapMaybe.java:132)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:407)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```
</details>
<hr>

**Comment by Stypox** [comment]
Could you check if the apk in this comment works? https://github.com/TeamNewPipe/NewPipe/pull/3930#issuecomment-664915869

**Comment by crazo7924** [comment]
@Stypox yes, that works and #4030 didn't occur

**Comment by ShareASmile** [comment]
Couldn't reproduce it on latest 0.28.5, hence closing.
