### ISSUE TITLE
UI crash when selecting text in video description

### ISSUE THREAD

**Issue by gwilherm** [TeamNewPipe/NewPipe#4036]
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ FR
* __Content Language:__ fr
* __App Language:__ fr_FR
* __Service:__ none
* __Version:__ 0.19.8
* __OS:__ Linux Android 6.0 - 23
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalArgumentException: Invalid offset: -1. Valid range is [0, 431]
	at android.text.method.WordIterator.checkOffsetIsValid(WordIterator.java:380)
	at android.text.method.WordIterator.isBoundary(WordIterator.java:101)
	at android.widget.Editor$SelectionStartHandleView.positionAtCursorOffset(Editor.java:4300)
	at android.widget.Editor$HandleView.updatePosition(Editor.java:3736)
	at android.widget.Editor$PositionListener.onPreDraw(Editor.java:2513)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2419)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1323)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6710)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
	at android.view.Choreographer.doCallbacks(Choreographer.java:696)
	at android.view.Choreographer.doFrame(Choreographer.java:631)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5765)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

```
</details>
<hr>
Select some text in a video description,
Press somewhere else in the description,
Crash occurs systematically on my system

**Comment by wb9688** [comment]
Doesn't happen on my phone with Android 10. I could try it later in an emulator with Android 6. What phone do you have?

**Comment by gwilherm** [comment]
Brand: Wiko (French rebranded Tinno)
Model: U Feel Lite

**Comment by panacist** [comment]
can confirm on my android 6 phone (kinda hard to reproduce) !

**Comment by opusforlife2** [comment]
@gwilherm @panacist Can you link a video where this happens?

**Comment by AudricV** [comment]
Is it still an issue with the latest version of the app (0.26.1 currently)?

**Comment by gwilherm** [comment]
I could not say, my old phone is broken and I cannot reproduce the issue with my new Android 14 phone.
I think you can close the topic (android 6 is quite old now)
