### ISSUE TITLE
Expandable player with unified UI ANDROID 4.4.4 crash normale player

### ISSUE THREAD

**Issue by Domiuns** [TeamNewPipe/NewPipe#4060]
When i click play on normal player app crash, but popup player work and music player work :( i have find this problem because now i have try apk with last change. (I test sponsorblock apk)
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ IT
* __Content Language:__ it-IT
* __App Language:__ it_IT
* __Service:__ none
* __Version:__ 0.19.8
* __OS:__ Linux Android 4.4.4 - 19
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NoClassDefFoundError: java.util.Objects
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.openMainPlayer(VideoDetailFragment.java:1180)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$dAtumQzji3VV2MwKInn8YF6nNs8(VideoDetailFragment.java)
	at org.schabi.newpipe.fragments.detail.-$$Lambda$VideoDetailFragment$dAtumQzji3VV2MwKInn8YF6nNs8.run(lambda)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.replaceQueueIfUserConfirms(VideoDetailFragment.java:2101)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.openVideoPlayer(VideoDetailFragment.java:1148)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.access$1400(VideoDetailFragment.java:133)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$1.onServiceConnected(VideoDetailFragment.java:311)
	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1131)
	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1148)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:153)
	at android.app.ActivityThread.main(ActivityThread.java:5297)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(Native Method)

```
</details>
<hr>

![IMG_20200803_022700](https://user-images.githubusercontent.com/53193434/89136097-3c00fc00-d532-11ea-9eba-154deb7ca943.JPG)

**Comment by avently** [comment]
Will be fixed in #4061 
If not a secret what device do you have and what operating system it runs on (it's probably non-AOSP)?

**Comment by Domiuns** [comment]
Is Huawei with android 4.4.4

**Comment by ingingin** [comment]
@avently I hope you understand this is an apk where another unofficial PR has been added so you shouldn't take time off to fix something unofficial. Wait for the right time when the PR is merged

**Comment by avently** [comment]
@ingingin  in this case it doesn't matter, the code that triggers this exception is still on it's place in dev branch
