### ISSUE TITLE
(Bug) Could not get comment text

### ISSUE THREAD

**Issue by allendema** [TeamNewPipe/NewPipe#4077]
### Version

- 0.19.8

### Steps to reproduce the bug

This can be reproduced just by opening this random stream in the logs, either sharing the link to NewPipe or pasting it in the search bar.

### Expected behavior

All comments to normally load.

### Actual behaviour

Error shows up. 
Comments are loaded but some of them maybe are missing.

## Exception
* __User Action:__ requested comments
* __Request:__ https://www.youtube.com/watch?v=VM_6n762j6M
* __Content Country:__ DE
* __Content Language:__ de
* __App Language:__ de_DE
* __Service:__ YouTube
* __Version:__ 0.19.8
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get comment text
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsInfoItemExtractor.getCommentText(YoutubeCommentsInfoItemExtractor.java:89)
	at org.schabi.newpipe.extractor.comments.CommentsInfoItemsCollector.extract(CommentsInfoItemsCollector.java:33)
	at org.schabi.newpipe.extractor.comments.CommentsInfoItemsCollector.commit(CommentsInfoItemsCollector.java:79)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.collectCommentsFrom(YoutubeCommentsExtractor.java:122)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getPage(YoutubeCommentsExtractor.java:100)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getInitialPage(YoutubeCommentsExtractor.java:52)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:40)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:25)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getCommentsInfo$7(ExtractorHelper.java:155)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$Xyj84g1UeNZqX9LVYNvWZsdT-kI.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
	at org.schabi.newpipe.extractor.utils.Utils.removeUTF8BOM(Utils.java:175)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsInfoItemExtractor.getCommentText(YoutubeCommentsInfoItemExtractor.java:87)
	... 34 more

```
</details>
<hr>

Log https://haste.tchncs.de/siyulilija.cs

**Comment by opusforlife2** [comment]
Reproduced just now. 👍

**Comment by allendema** [comment]
Note that there seems to be a blank comment.

**Comment by opusforlife2** [comment]
Yeah. It can be copied to the clipboard, but not pasted. Some sort of non printable data.

**Comment by TobiGr** [comment]
there is no data: `contentText` is empty: `"contentText": {},`

<details><summary>commentThreadRenderer</summary>

``` JSON

{
  "commentThreadRenderer": {
    "comment": {
      "commentRenderer": {
        "authorText": {
          "simpleText": "Arta Bajrami"
        },
        "authorThumbnail": {
          "thumbnails": [
            {
              "url": "https://yt3.ggpht.com/a/AATXAJztl3o2gugWX94_4Xl4scb3tdQSuJ2-Z5gMml4owA=s48-c-k-c0xffffffff-no-rj-mo",
              "width": 32,
              "height": 32
            },
            {
              "url": "https://yt3.ggpht.com/a/AATXAJztl3o2gugWX94_4Xl4scb3tdQSuJ2-Z5gMml4owA=s48-c-k-c0xffffffff-no-rj-mo",
              "width": 48,
              "height": 48
            },
            {
              "url": "https://yt3.ggpht.com/a/AATXAJztl3o2gugWX94_4Xl4scb3tdQSuJ2-Z5gMml4owA=s48-c-k-c0xffffffff-no-rj-mo",
              "width": 76,
              "height": 76
            }
          ],
          "accessibility": {
            "accessibilityData": {
              "label": "Arta Bajrami"
            }
          }
        },
        "authorEndpoint": {
          "clickTrackingParams": "CJUBELZ1IhMIvOPIrK-C6wIViUbgCh0IKghk",
          "commandMetadata": {
            "webCommandMetadata": {
              "url": "/channel/UCnDD3MMW1ZbqI9NolubdeIQ",
              "webPageType": "WEB_PAGE_TYPE_BROWSE",
              "rootVe": 3611
            }
          },
          "browseEndpoint": {
            "browseId": "UCnDD3MMW1ZbqI9NolubdeIQ",
            "canonicalBaseUrl": "/channel/UCnDD3MMW1ZbqI9NolubdeIQ"
          }
        },
        "contentText": {},
        "publishedTimeText": {
          "runs": [
            {
              "text": "vor 5 Jahren",
              "navigationEndpoint": {
                "clickTrackingParams": "CJUBELZ1IhMIvOPIrK-C6wIViUbgCh0IKghk",
                "commandMetadata": {
                  "webCommandMetadata": {
                    "url": "/watch?v=VM_6n762j6M\u0026lc=Ugga_h1-EXdHB3gCoAEC",
                    "webPageType": "WEB_PAGE_TYPE_WATCH",
                    "rootVe": 3832
                  }
                },
                "watchEndpoint": {
                  "videoId": "VM_6n762j6M",
                  "params": "ehRVZ2dhX2gxLUVYZEhCM2dDb0FFQ6ICA8ABAA%3D%3D"
                }
              }
            }
          ]
        },
        "isLiked": false,
        "likeCount": 67,
        "commentId": "Ugga_h1-EXdHB3gCoAEC",
        "actionButtons": {
          "commentActionButtonsRenderer": {
            "likeButton": {
              "toggleButtonRenderer": {
                "style": {
                  "styleType": "STYLE_TEXT"
                },
                "size": {
                  "sizeType": "SIZE_DEFAULT"
                },
                "isToggled": false,
                "isDisabled": false,
                "defaultIcon": {
                  "iconType": "LIKE"
                },
                "trackingParams": "CJsBEJhNIhMIvOPIrK-C6wIViUbgCh0IKghk",
                "defaultTooltip": "Mag ich",
                "toggledTooltip": "Mag ich nicht mehr",
                "toggledStyle": {
                  "styleType": "STYLE_DEFAULT_ACTIVE"
                },
                "defaultNavigationEndpoint": {
                  "clickTrackingParams": "CJsBEJhNIhMIvOPIrK-C6wIViUbgCh0IKghk",
                  "commandMetadata": {
                    "webCommandMetadata": {
                      "url": "https://accounts.google.com/ServiceLogin?service=youtube\u0026uilel=3\u0026passive=true\u0026continue=https%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26app%3Ddesktop%26hl%3Dde%26next%3D%252Fwatch%253Fv%253DVM_6n762j6M\u0026hl=de",
                      "rootVe": 83769
                    }
                  },
                  "signInEndpoint": {
                    "nextEndpoint": {
                      "clickTrackingParams": "CJsBEJhNIhMIvOPIrK-C6wIViUbgCh0IKghk",
                      "commandMetadata": {
                        "webCommandMetadata": {
                          "url": "/watch?v=VM_6n762j6M",
                          "webPageType": "WEB_PAGE_TYPE_WATCH",
                          "rootVe": 3832
                        }
                      },
                      "watchEndpoint": {
                        "videoId": "VM_6n762j6M"
                      }
                    }
                  }
                },
                "accessibilityData": {
                  "accessibilityData": {
                    "label": "Klicke bei diesem Kommentar auf \"Mag ich\", genau wie 67 andere Personen"
                  }
                },
                "toggledAccessibilityData": {
                  "accessibilityData": {
                    "label": "Mag ich nicht mehr"
                  }
                }
              }
            },
            "replyButton": {
              "buttonRenderer": {
                "style": "STYLE_TEXT",
                "size": "SIZE_DEFAULT",
                "text": {
                  "runs": [
                    {
                      "text": "Antworten"
                    }
                  ]
                },
                "navigationEndpoint": {
                  "clickTrackingParams": "CJoBEPBbIhMIvOPIrK-C6wIViUbgCh0IKghk",
                  "commandMetadata": {
                    "webCommandMetadata": {
                      "url": "https://accounts.google.com/ServiceLogin?service=youtube\u0026uilel=3\u0026passive=true\u0026continue=https%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26app%3Ddesktop%26hl%3Dde%26next%3D%252Fwatch%253Fv%253DVM_6n762j6M\u0026hl=de",
                      "rootVe": 83769
                    }
                  },
                  "signInEndpoint": {
                    "nextEndpoint": {
                      "clickTrackingParams": "CJoBEPBbIhMIvOPIrK-C6wIViUbgCh0IKghk",
                      "commandMetadata": {
                        "webCommandMetadata": {
                          "url": "/watch?v=VM_6n762j6M",
                          "webPageType": "WEB_PAGE_TYPE_WATCH",
                          "rootVe": 3832
                        }
                      },
                      "watchEndpoint": {
                        "videoId": "VM_6n762j6M"
                      }
                    }
                  }
                },
                "trackingParams": "CJoBEPBbIhMIvOPIrK-C6wIViUbgCh0IKghk"
              }
            },
            "dislikeButton": {
              "toggleButtonRenderer": {
                "style": {
                  "styleType": "STYLE_TEXT"
                },
                "size": {
                  "sizeType": "SIZE_DEFAULT"
                },
                "isToggled": false,
                "isDisabled": false,
                "defaultIcon": {
                  "iconType": "DISLIKE"
                },
                "trackingParams": "CJkBEJhNIhMIvOPIrK-C6wIViUbgCh0IKghk",
                "defaultTooltip": "Mag ich nicht",
                "toggledTooltip": "\"Mag ich nicht\"-Bewertung entfernen",
                "toggledStyle": {
                  "styleType": "STYLE_DEFAULT_ACTIVE"
                },
                "defaultNavigationEndpoint": {
                  "clickTrackingParams": "CJkBEJhNIhMIvOPIrK-C6wIViUbgCh0IKghk",
                  "commandMetadata": {
                    "webCommandMetadata": {
                      "url": "https://accounts.google.com/ServiceLogin?service=youtube\u0026uilel=3\u0026passive=true\u0026continue=https%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26app%3Ddesktop%26hl%3Dde%26next%3D%252Fwatch%253Fv%253DVM_6n762j6M\u0026hl=de",
                      "rootVe": 83769
                    }
                  },
                  "signInEndpoint": {
                    "nextEndpoint": {
                      "clickTrackingParams": "CJkBEJhNIhMIvOPIrK-C6wIViUbgCh0IKghk",
                      "commandMetadata": {
                        "webCommandMetadata": {
                          "url": "/watch?v=VM_6n762j6M",
                          "webPageType": "WEB_PAGE_TYPE_WATCH",
                          "rootVe": 3832
                        }
                      },
                      "watchEndpoint": {
                        "videoId": "VM_6n762j6M"
                      }
                    }
                  }
                },
                "accessibilityData": {
                  "accessibilityData": {
                    "label": "Diesen Kommentar nicht mögen"
                  }
                },
                "toggledAccessibilityData": {
                  "accessibilityData": {
                    "label": "\"Mag ich nicht\"-Bewertung entfernen"
                  }
                }
              }
            },
            "trackingParams": "CJgBELV1IhMIvOPIrK-C6wIViUbgCh0IKghk",
            "style": "COMMENT_ACTION_BUTTON_STYLE_TYPE_DESKTOP_TOOLBAR"
          }
        },
        "authorIsChannelOwner": true,
        "voteStatus": "INDIFFERENT",
        "trackingParams": "CJUBELZ1IhMIvOPIrK-C6wIViUbgCh0IKghk",
        "voteCount": {
          "accessibility": {
            "accessibilityData": {
              "label": "67 \"Mag ich\"-Bewertungen"
            }
          },
          "simpleText": "67"
        },
        "expandButton": {
          "buttonRenderer": {
            "style": "STYLE_TEXT",
            "size": "SIZE_DEFAULT",
            "text": {
              "runs": [
                {
                  "text": "Mehr anzeigen"
                }
              ]
            },
            "accessibility": {
              "label": "Mehr anzeigen"
            },
            "trackingParams": "CJcBEK_YAiITCLzjyKyvgusCFYlG4AodCCoIZA=="
          }
        },
        "collapseButton": {
          "buttonRenderer": {
            "style": "STYLE_TEXT",
            "size": "SIZE_DEFAULT",
            "text": {
              "runs": [
                {
                  "text": "Weniger anzeigen"
                }
              ]
            },
            "accessibility": {
              "label": "Weniger anzeigen"
            },
            "trackingParams": "CJYBELDYAiITCLzjyKyvgusCFYlG4AodCCoIZA=="
          }
        },
        "authorCommentBadge": {
          "authorCommentBadgeRenderer": {
            "icon": {
              "iconType": "OFFICIAL_ARTIST_BADGE"
            },
            "color": {
              "basicColorPaletteData": {
                "backgroundColor": 4287137928,
                "foregroundTitleColor": 4294967295
              }
            },
            "authorText": {
              "accessibility": {
                "accessibilityData": {
                  "label": "Arta Bajrami, Offizieller Künstlerkanal"
                }
              },
              "simpleText": "Arta Bajrami"
            },
            "authorEndpoint": {
              "clickTrackingParams": "CJUBELZ1IhMIvOPIrK-C6wIViUbgCh0IKghk",
              "commandMetadata": {
                "webCommandMetadata": {
                  "url": "/channel/UCnDD3MMW1ZbqI9NolubdeIQ",
                  "webPageType": "WEB_PAGE_TYPE_BROWSE",
                  "rootVe": 3611
                }
              },
              "browseEndpoint": {
                "browseId": "UCnDD3MMW1ZbqI9NolubdeIQ",
                "canonicalBaseUrl": "/channel/UCnDD3MMW1ZbqI9NolubdeIQ"
              }
            },
            "iconTooltip": "Offizieller Künstlerkanal"
          }
        },
        "replyCount": 8,
        "loggingDirectives": {
          "trackingParams": "CJUBELZ1IhMIvOPIrK-C6wIViUbgCh0IKghk",
          "visibility": {
            "types": "12"
          }
        }
      }
    },
    "replies": {
      "commentRepliesRenderer": {
        "continuations": [
          {
            "nextContinuationData": {
              "continuation": "EkQSC1ZNXzZuNzYyajZNwAEAyAEA4AECogINKP___________wFAAMICGxoXaHR0cHM6Ly93d3cueW91dHViZS5jb20iABgGMkcaRRIUVWdnYV9oMS1FWGRIQjNnQ29BRUMiAggAKhhVQ25ERDNNTVcxWmJxSTlOb2x1YmRlSVEyC1ZNXzZuNzYyajZNQAFICg%3D%3D",
              "clickTrackingParams": "CJQBEMm3AiITCLzjyKyvgusCFYlG4AodCCoIZA==",
              "label": {
                "runs": [
                  {
                    "text": "Mehr Antworten ansehen"
                  }
                ]
              }
            }
          }
        ],
        "moreText": {
          "runs": [
            {
              "text": "8 Antworten ansehen"
            }
          ]
        },
        "trackingParams": "CJEBEL51IhMIvOPIrK-C6wIViUbgCh0IKghk",
        "lessText": {
          "runs": [
            {
              "text": "8 Antworten ausblenden"
            }
          ]
        },
        "viewReplies": {
          "buttonRenderer": {
            "text": {
              "runs": [
                {
                  "text": "8 Antworten ansehen"
                }
              ]
            },
            "icon": {
              "iconType": "ARROW_DROP_DOWN"
            },
            "trackingParams": "CJMBEKLABCITCLzjyKyvgusCFYlG4AodCCoIZA==",
            "iconPosition": "BUTTON_ICON_POSITION_TYPE_LEFT_OF_TEXT"
          }
        },
        "hideReplies": {
          "buttonRenderer": {
            "text": {
              "runs": [
                {
                  "text": "8 Antworten ausblenden"
                }
              ]
            },
            "icon": {
              "iconType": "ARROW_DROP_UP"
            },
            "trackingParams": "CJIBENvNBCITCLzjyKyvgusCFYlG4AodCCoIZA==",
            "iconPosition": "BUTTON_ICON_POSITION_TYPE_LEFT_OF_TEXT"
          }
        }
      }
    },
    "commentTargetTitle": {
      "simpleText": "Arta - I njejti ke mbet ( Re-Upload )"
    },
    "trackingParams": "CJABEMJ1GAQiEwi848isr4LrAhWJRuAKHQgqCGQ=",
    "renderingPriority": "RENDERING_PRIORITY_UNKNOWN",
    "loggingDirectives": {
      "trackingParams": "CJABEMJ1GAQiEwi848isr4LrAhWJRuAKHQgqCGQ=",
      "visibility": {
        "types": "12"
      }
    }
  }
}
```
</details>
