### ISSUE TITLE
UI Error on specific video

### ISSUE THREAD

**Issue by njmdietrich** [TeamNewPipe/NewPipe#4112]
I get a crash that comes up as UI error trying to play back this video: https://m.youtube.com/watch?v=eueyYOMCRuc
The video overview page with comments and description loads fine, but trying to play the video yields this error:
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.19.8
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Collections.java:4511)
	at org.schabi.newpipe.player.helper.PlayerHelper.autoQueueOf(PlayerHelper.java:165)
	at org.schabi.newpipe.player.BasePlayer.maybeAutoQueueNextStream(BasePlayer.java:1336)
	at org.schabi.newpipe.player.BasePlayer.maybeUpdateCurrentMetadata(BasePlayer.java:1320)
	at org.schabi.newpipe.player.BasePlayer.onTimelineChanged(BasePlayer.java:677)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$0$ExoPlayerImpl$PlaybackInfoUpdate(ExoPlayerImpl.java:804)
	at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$PlaybackInfoUpdate$N_S5kRfhaRTAkH28P5luFgKnFjQ.invokeListener(Unknown Source:2)
	at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:182)
	at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:845)
	at com.google.android.exoplayer2.ExoPlayerImpl.access$000(ExoPlayerImpl.java:43)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.run(ExoPlayerImpl.java:802)
	at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:736)
	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:710)
	at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:652)
	at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:595)
	at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:127)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

```
</details>
<hr>

**Comment by njmdietrich** [comment]
Just realised it is an age restricted video. So this issue is already known.

**Comment by wb9688** [comment]
No, you have auto-play enabled while there are no next videos (which is always the case for age restricted videos on YouTube). This bug should be trivial to fix.
