### ISSUE TITLE
Random crash while trying to play some specific videos

### ISSUE THREAD

**Issue by NRG-600** [TeamNewPipe/NewPipe#4165]
### Version
- 0.19.8 (F-Droid)

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.19.8
* __OS:__ Linux HONOR/LND-AL30/HWLND-Q:8.0.0/HONORLND-AL30/184(C675):user/release-keys 8.0.0 - 26
<details><summary><b>Crash log </b></summary><p>

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://github.com/... pkg=com.huawei.android.internal.app }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1981)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1636)
	at android.app.Activity.startActivityForResult(Activity.java:4762)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
	at android.app.Activity.startActivityForResult(Activity.java:4702)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
	at android.app.Activity.startActivity(Activity.java:5123)
	at android.app.Activity.startActivity(Activity.java:5091)
	at org.schabi.newpipe.util.ShareUtils.openUrlInBrowser(ShareUtils.java:36)
	at org.schabi.newpipe.report.ErrorActivity.lambda$openPrivacyPolicyDialog$6$ErrorActivity(ErrorActivity.java:296)
	at org.schabi.newpipe.report.-$$Lambda$ErrorActivity$5_1f6_qlMC4kGJ25uzULCSB-nFE.onClick(Unknown Source:4)
	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:168)
	at android.os.Handler.dispatchMessage(Handler.java:108)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7529)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

```
</details>
<hr>

**Comment by wb9688** [comment]
>Random crash while trying to play some specific videos

No, the crash log you posted is from pressing the button at the thing that shows up on a crash to open our privacy policy in a browser while not having a browser installed.

**Comment by NRG-600** [comment]
Yup maybe you're right. I pressed the report to Github button but nothing except NewPipe relaunch itself. 

I've a different log file too, should I post that one instead...?

**Comment by NRG-600** [comment]
> >Random crash while trying to play some specific videos
> 
> No, the crash log you posted is from pressing the button at the thing that shows up on a crash to open our privacy policy in a browser while not having a browser installed.

It's my first time reporting any kind of bug on GitHub, please forgive me for my mistake

**Comment by wb9688** [comment]
@NRG-600: Yes, please post the different log as well.

**Comment by NRG-600** [comment]
> @NRG-600: Yes, please post the different log as well.

Should I post that different log file here or create a new bug report...?

**Comment by opusforlife2** [comment]
Post it here.

**Comment by Stypox** [comment]
> Post it here

@NRG-600 ^

**Comment by opusforlife2** [comment]
@NRG-600 Don't leave us in suspense. What was that other log file?
