### ISSUE TITLE
Crash after searching for a video or channel name

### ISSUE THREAD

**Issue by GitHubTAKK** [TeamNewPipe/NewPipe#4177]
## Steps to reproduce the bug

1. In home screen, click on search icon
2. Type some search terms
3. Wait a moment, and the crash appears

# Description 

- This is a special case that occurs frequently for different search terms. I overcome it sometimes by clearing the app storage and cache or even reinstall.

- Extra information: I sometime use Orbot in VPN mode. But regardless I get this crash. I have Lineage OS installed on Galaxy S9+ (if such information helps)

## Exception
* User Action: get suggestions
* Request: luke smith
* Content Country: US
* Content Language: en-US
* App Language: en_US
* Service: YouTube
* Version: 0.19.8
* OS: Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse json response
 at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSuggestionExtractor.suggestionList(YoutubeSuggestionExtractor.java:72)
 at org.schabi.newpipe.util.ExtractorHelper.lambda$suggestionsFor$2(ExtractorHelper.java:107)
 at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$kAwiU5Tjeit-NCwHTWhD3V6UHS8.call(Unknown Source:4)
 at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
 at io.reactivex.Single.subscribe(Single.java:3666)
 at io.reactivex.internal.operators.single.SingleToObservable.subscribeActual(SingleToObservable.java:35)
 at io.reactivex.Observable.subscribe(Observable.java:12284)
 at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
 at io.reactivex.Observable.subscribe(Observable.java:12284)
 at io.reactivex.internal.operators.observable.ObservableZip$ZipCoordinator.subscribe(ObservableZip.java:110)
 at io.reactivex.internal.operators.observable.ObservableZip.subscribeActual(ObservableZip.java:72)
 at io.reactivex.Observable.subscribe(Observable.java:12284)
 at io.reactivex.internal.operators.observable.ObservableMaterialize.subscribeActual(ObservableMaterialize.java:28)
 at io.reactivex.Observable.subscribe(Observable.java:12284)
 at io.reactivex.internal.operators.observable.ObservableSwitchMap$SwitchMapObserver.onNext(ObservableSwitchMap.java:127)
 at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
 at io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver$DelayErrorInnerObserver.onNext(ObservableConcatMap.java:506)
 at io.reactivex.observers.SerializedObserver.onNext(SerializedObserver.java:111)
 at io.reactivex.internal.operators.observable.ObservableDebounceTimed$DebounceTimedObserver.emit(ObservableDebounceTimed.java:143)
 at io.reactivex.internal.operators.observable.ObservableDebounceTimed$DebounceEmitter.run(ObservableDebounceTimed.java:168)
 at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
 at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:919)
Caused by: com.grack.nanojson.JsonParserException: Unexpected token 'ml' on line 1, char 1
 at com.grack.nanojson.JsonTokener.createParseException(Unknown Source:44)
 at com.grack.nanojson.JsonTokener.createHelpfulException(Unknown Source:119)
 at com.grack.nanojson.JsonTokener.advanceToToken(Unknown Source:95)
 at com.grack.nanojson.JsonParser.advanceToken(Unknown Source:12)
 at com.grack.nanojson.JsonParser.parse(Unknown Source:1)
 at com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source:19)
 at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSuggestionExtractor.suggestionList(YoutubeSuggestionExtractor.java:62)
 ... 26 more
```

</details>
<hr>

**Comment by hp8wvvvgnj6asjm7** [comment]
## Exception
* __User Action:__ searched
* __Request:__ typescript
* __Content Country:__ DE
* __Content Language:__ en
* __App Language:__ en_DE
* __Service:__ YouTube
* __Version:__ 0.20.0
* __OS:__ Linux Android 5.0.2 - 21
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get ytInitialData
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getInitialData(YoutubeParsingHelper.java:203)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.extractClientVersionAndKey(YoutubeParsingHelper.java:222)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getKey(YoutubeParsingHelper.java:298)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getNewNextPageFrom(YoutubeSearchExtractor.java:233)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getInitialPage(YoutubeSearchExtractor.java:127)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:55)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:30)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$searchFor$0(ExtractorHelper.java:81)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$BBduYDeZ_vXMQYaemaggmTPtqvA.call(lambda)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: org.schabi.newpipe.extractor.utils.Parser$RegexException: failed to find pattern "window\["ytInitialData"\]\s*=\s*(\{.*?\});
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:72)
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:61)
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup1(Parser.java:52)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getInitialData(YoutubeParsingHelper.java:200)
	... 21 more

```
</details>
<hr>
`

**Comment by Feuerswut** [comment]
Status?
