### ISSUE TITLE
newpipe can't load any youtube link and show no result for any search

### ISSUE THREAD

**Issue by mhdzli** [TeamNewPipe/NewPipe#4201]
### Version

-0.19.8

### Steps to reproduce the bug

1. I search for anything in newpipe and there is no result with a `sorry some error occurred` message.
2. If I open any youtube link in newpipe it can't load the page and info.

## Exception
* __User Action:__ searched
* __Request:__ swaywm
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.19.8
* __OS:__ Linux samsung/a6pltedx/a6plte:10/QP1A.190711.020/A605GDXU6CTC9:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get ytInitialData
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getInitialData(YoutubeParsingHelper.java:203)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.extractClientVersionAndKey(YoutubeParsingHelper.java:222)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getKey(YoutubeParsingHelper.java:298)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getNewNextPageFrom(YoutubeSearchExtractor.java:233)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getInitialPage(YoutubeSearchExtractor.java:127)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:55)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:30)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$searchFor$0(ExtractorHelper.java:81)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$BBduYDeZ_vXMQYaemaggmTPtqvA.call(Unknown Source:8)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: org.schabi.newpipe.extractor.utils.Parser$RegexException: failed to find pattern "window\["ytInitialData"\]\s*=\s*(\{.*?\});
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:72)
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:61)
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup1(Parser.java:52)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getInitialData(YoutubeParsingHelper.java:200)
	... 20 more

```
</details>
<hr>

**Comment by opusforlife2** [comment]
Interesting! I've never seen that error message before.

**Comment by sandeeptardigrade** [comment]
this is so frustrating. I am also facing the same error from about a month , before that it was working fine. my phone oneplus 5

**Comment by mhdzli** [comment]
@sandeeptardigrade 
I just delete all newpipe data and it works for a while till this happen again ¯\_(ツ)_/¯

**Comment by wb9688** [comment]
If you could still reproduce it, could you install a debug version, connect your phone to your PC through USB, open Chrome, go to `chrome://inspect`, open that debug version of NewPipe on your phone, select that NewPipe instance in Chrome, go to the Network tab, try to reproduce the issue, and once you've successfully reproduced the issue, right-click in Chrome, select "Save as HAR with Content" and send me that HAR? Then I might be able to fix this issue.

**Comment by mhdzli** [comment]
@wb9688 
Absolutely sure! I will be happy if I can be of any help.

**Comment by wb9688** [comment]
@mhdzli: You could download a debug apk at https://github.com/TeamNewPipe/NewPipe/files/5083926/app-debug.zip (it will install side-by-side)

You'll probably need to export database (in Settings -> Content) from your normal NewPipe and import it into that debugging NewPipe to be able to reproduce it.

Btw have you at any point got a reCAPTCHA in NewPipe?

**Comment by mhdzli** [comment]
@wb9688 
Yes I got reCAPCHA every now and then. And thank you and all of newpipe team for this great app.

**Comment by vomindoraan** [comment]
I am having the same issues. Homepage, search and video preview pages all show “Network error”.

The issues first started about a week ago, then the app went back to normal for a few days, and then it started acting up again yesterday. Both times it started happening around the time I reinstalled my browser app (Firefox), but I doubt that's related.

Screenshots:
![Screenshot_20200906-120301](https://user-images.githubusercontent.com/1969863/92323454-1b4c2a80-f039-11ea-8a5b-6059892e0f92.jpg)
![Screenshot_20200906-120330](https://user-images.githubusercontent.com/1969863/92323460-243cfc00-f039-11ea-92b9-23f7161d9daa.jpg)

Version info:
NewPipe v0.19.8
Android 7.1.1
SM-J510FN

**Comment by opusforlife2** [comment]
@vomindoraan Could you try this https://github.com/TeamNewPipe/NewPipe/issues/4201#issuecomment-683668294? Thanks.

**Comment by vomindoraan** [comment]
@opusforlife2 I will try that later tonight.

**Comment by Tybalta** [comment]
I have the same issue...

**Comment by opusforlife2** [comment]
@Tybalta Could you try this https://github.com/TeamNewPipe/NewPipe/issues/4201#issuecomment-683668294? Thanks.

**Comment by vomindoraan** [comment]
@opusforlife2 I tried reproducing the issue with the debug app several times, like you suggested, but every time the problem seemed to magically go away, just to come back the next day.

In the end I realized that the issue only seemed to occur when I was using NewPipe on mobile data. As soon as I connected to Wi-Fi, the app would work like normal again. Since my phone was always connected to my home Wi-Fi network whenever I tried debugging with Chrome, I couldn't reproduce the issue.

@Tybalta @mhdzli Can you guys confirm if the app works for you on Wi-Fi?

**Comment by opusforlife2** [comment]
@vomindoraan That's good to know! So can you try this using mobile hotspot?

**Comment by vomindoraan** [comment]
Here's a screen recording that demonstrates this:

![screen recording](https://i.imgur.com/O2X6Rq3.mp4)

**Comment by vomindoraan** [comment]
https://www.dropbox.com/s/9rygt6hqx3ldyhn/newpipe_networkerror_har.zip?dl=1

The above archive contains three HARs:
1. a snapshot after opening the app, doing a search and getting a network error;
2. a snapshot after doing a second search and getting another network error;
3. a snapshot after opening the preview page for a video and getting a third network error.

**Comment by opusforlife2** [comment]
Thanks!

**Comment by Tybalta** [comment]
> @Tybalta Could you try this [#4201 (comment)](https://github.com/TeamNewPipe/NewPipe/issues/4201#issuecomment-683668294)? Thanks.

I dont know how to do that in chrome? Which chrome? Phone or Pc chrome?

**Comment by opusforlife2** [comment]
That's okay. We have got HARs above. If none of them helps solve the problem, then we could ask for them again.

Chrome on PC, by the way.

**Comment by mhdzli** [comment]
@wb9688
I installed the debug version and tried reproducing it several times, but everything works fine and the problem just went away. I did everything came into my mind. If you can think of anything that I should consider give me the instruction and I'll try again.

**Comment by vomindoraan** [comment]
I am still experiencing this issue on v0.20.0 when not connected to Wi-Fi.

**Comment by Stypox** [comment]
> The above archive contains three HARs:

Unfortunately I couldn't find any useful information in those HARs: they contain only a bunch of successful search suggestion requests and one successful comment request, so for some reason there is nothing that could cause an error

**Comment by vomindoraan** [comment]
I have had no similar issues with any applications other than NewPipe v0.19.2 and v0.20.0. To the best of my knowledge, there is nothing on my phone that could be blocking requests. Also, the fact that it only breaks on mobile data while working fine on Wi-Fi, and the fact that other users are experiencing similar problems, leads me to believe that the issue is on NewPipe's end.

If the requests in the HAR were successful, how come the application reported network errors having occurred?

**Comment by Stypox** [comment]
The HARs just do not contain the failing requests: those are probably blocked by something else before they are even sent. This is then probably caused by the outdated OkHttp version we have to use in order to support Android 4.4

**Comment by opusforlife2** [comment]
I'm more and more convinced that this issue is caused by some error or corruption during database import.

**Comment by mrlinnth** [comment]
Working fine until few days ago. I didn't do any import or anything.

Below is the log.

## Exception
* __User Action:__ searched
* __Request:__ alan watts
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.20.0
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get ytInitialData
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getInitialData(YoutubeParsingHelper.java:203)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.extractClientVersionAndKey(YoutubeParsingHelper.java:222)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getKey(YoutubeParsingHelper.java:298)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getNewNextPageFrom(YoutubeSearchExtractor.java:233)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getInitialPage(YoutubeSearchExtractor.java:127)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:55)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:30)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$searchFor$0(ExtractorHelper.java:81)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$BBduYDeZ_vXMQYaemaggmTPtqvA.call(Unknown Source:8)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: org.schabi.newpipe.extractor.utils.Parser$RegexException: failed to find pattern "window\["ytInitialData"\]\s*=\s*(\{.*?\});
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:72)
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:61)
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup1(Parser.java:52)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getInitialData(YoutubeParsingHelper.java:200)
	... 20 more

```
</details>
<hr>

**Comment by opusforlife2** [comment]
Oh hey! I just got this error when searching. And on Wi-Fi. Yay!

Only got it the once, though. Same search worked a second time. :/

**Comment by mrpr3s** [comment]
Just now facing this issue. Using latest 0.20.0 git release.

None of search result query fetched always shows no result. Tried searching multiple times.

Here is the LOGS:
https://del.dog/icyporimyp

**Comment by Freepony** [comment]
This is what I could figure out. First I cleaned up app cache and that didn't work. Then I made data backup (settings - content), cleaned up app data and restored backup WITH restoring app settings. That didn't work either. Deleting metadata, search history and so on in History and Search menu did no good.
So I again cleaned up app data, restored backup WITHOUT restoring app settings and it worked. The search now works and I could save all the subscriptions and search results which is important for me. But still I have no idea what setting causes the error.

**Comment by Stypox** [comment]
Here is the two network files causing the following crash @wb9688 [network.zip](https://github.com/TeamNewPipe/NewPipe/files/5393194/network.zip)

## Exception
* __User Action:__ searched
* __Request:__ fsd
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.20.0
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get ytInitialData
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getInitialData(YoutubeParsingHelper.java:203)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.extractClientVersionAndKey(YoutubeParsingHelper.java:222)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getKey(YoutubeParsingHelper.java:298)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getNewNextPageFrom(YoutubeSearchExtractor.java:233)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getInitialPage(YoutubeSearchExtractor.java:127)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:55)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:30)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$searchFor$0(ExtractorHelper.java:81)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$qyxpuXgomWa-cbONQns-pd7zxm0.call(Unknown Source:8)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: org.schabi.newpipe.extractor.utils.Parser$RegexException: failed to find pattern "window\["ytInitialData"\]\s*=\s*(\{.*?\});
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:72)
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:61)
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup1(Parser.java:52)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getInitialData(YoutubeParsingHelper.java:200)
	... 20 more

```
</details>
<hr>

**Comment by TobiGr** [comment]
Please test the APK and tell us if the problem still persists: [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5393685/app-debug.zip)

**Comment by wb9688** [comment]
@TobiGr: I was just about to upload the following APK: [app-debug.apk.zip](https://github.com/TeamNewPipe/NewPipe/files/5393694/app-debug.apk.zip)

**Comment by mehedihasanziku** [comment]
> Please test the APK and tell us if the problem still persists: [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/5393685/app-debug.zip)

![Screenshot_2020-10-17-00-46-19](https://user-images.githubusercontent.com/48652123/96297200-51a29f80-1012-11eb-8533-7a6dc097f8fb.png)
![Screenshot_2020-10-17-00-46-06](https://user-images.githubusercontent.com/48652123/96297204-5404f980-1012-11eb-8a29-4aa66464e249.png)


Just tested seems working fine.

Step:
Installed > Import Database from release version > Searched Multiple times, working fine

**Comment by opusforlife2** [comment]
@mehedihasanziku We don't need the screenshots. Your word is enough.

**Comment by EliasKomar** [comment]
so i had the same issue the past couple of days and I was wondering what I should do now. Will a fix be released or should I use the apk that you provided?

**Comment by opusforlife2** [comment]
@EliasKomar It's already released.

**Comment by EliasKomar** [comment]
I'm not sure where to put this question, but i can't install the apk from the website and f-droid warns me that the version is signed with a different key and that I would have to delete the old app (I would lose all the data) in order to install it. Why did the key change and how can I transition without losing my data?

**Comment by opusforlife2** [comment]
@EliasKomar Export database, uninstall the app, install the new version, import database.

**Comment by wb9688** [comment]
@EliasKomar: If you've downloaded it from F-Droid, it's possible you downloaded the version that was signed by F-Droid. On GitHub, and on our F-Droid repo we of course sign it with our own keys. Normal F-Droid nowadays has an .apk signed by us and one signed by them.

**Comment by EliasKomar** [comment]
Thanks, it works now and I am going to use the NewPipe signed version from now on since I trust the project :)

**Comment by opusforlife2** [comment]
@EliasKomar Since Newpipe is reproducible, F-Droid's server also signs using Newpipe's key, which means your trust is verified as well. ;)

**Comment by vomindoraan** [comment]
I was able to sidestep this issue by changing my DNS resolver to 1.1.1.1 using the Cloudflare [1.1.1.1 app](https://play.google.com/store/apps/details?id=com.cloudflare.onedotonedotonedotone&hl=en_US&gl=US) from the Play Store. Only after doing this has NewPipe v0.20.2 started working over mobile data on my Android 7.1.1 phone.

The issue seems to have occurred because www.youtube.com was inaccessible, whereas m.youtube.com was working fine.

**Comment by mehedihasanziku** [comment]
> I was able to sidestep this issue by changing my DNS resolver to 1.1.1.1 using the Cloudflare [1.1.1.1 app](https://play.google.com/store/apps/details?id=com.cloudflare.onedotonedotonedotone&hl=en_US&gl=US) from the Play Store. Only after doing this has NewPipe v0.20.2 started working over mobile data on my Android 7.1.1 phone.
> 
> The issue seems to have occurred because [www.youtube.com](http://www.youtube.com) was inaccessible, whereas m.youtube.com was working fine.

It was fixed on last version and it was captcha cookie issue, so your issue seems to me different.

**Comment by G-i-o** [comment]
HI.

Just wanted to report that I also was unable to do any search nor downloads or even access any video. Then I read few comments above and sb deleted the app data with success. It happened to me too; once I deleted the cache + data NewPipe appeared to work again. 

I have saved the report log of when the issue presented and if you want me to post it or send it somewhere, JLMK. 🙏🏼

P.S. Big thank You to the devs, by the way, for all their great efforts.

**Comment by opusforlife2** [comment]
@G-i-o Please send it right here as an attachment to your comment. 👍

**Comment by G-i-o** [comment]
👍 @opusforlife2 

Please find it below:

[2021.05.15 NewPipe Report.txt](https://github.com/TeamNewPipe/NewPipe/files/6483166/2021.05.15.NewPipe.Report.txt)

Hope it helps.

**Comment by opusforlife2** [comment]
Oh. @G-i-o I thought you meant you took a logcat or network activity log of when the issue occurred. What you've sent is the Newpipe crash report, which is the same as the original poster's crash report. But thanks, anyway!

**Comment by G-i-o** [comment]
Thought so. Sorry for that. 

I'll report if it happens again and then try to
get a better report following your instructions
(I'll ask again then).

🙏️

**Comment by WickyNilliams** [comment]
Exporting my database, clearing data, then reimporting _without_ settings fixed this issue for me. Thanks!
