### ISSUE TITLE
Constant UI error on attempt to play video.

### ISSUE THREAD

**Issue by Flam3z** [TeamNewPipe/NewPipe#4243]
### Version
0.19.8

-

### Steps to reproduce the bug
1. View the video on NewPipe: https://www.youtube.com/watch?v=3Zl2DVBX5dk
2. UI Error should appear.

### Expected behavior

Expected to view the video with no issues on load.

### Actual behaviour

Ran into a constant UI error.

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ US
* __Content Language:__ en
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.19.8
* __OS:__ Linux samsung/beyond1qltesq/beyond1q:10/QP1A.190711.020/G973USQU3DTE8:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IndexOutOfBoundsException: Index: 0
	at java.util.Collections$EmptyList.get(Collections.java:4511)
	at org.schabi.newpipe.player.helper.PlayerHelper.autoQueueOf(PlayerHelper.java:165)
	at org.schabi.newpipe.player.BasePlayer.maybeAutoQueueNextStream(BasePlayer.java:1336)
	at org.schabi.newpipe.player.BasePlayer.maybeUpdateCurrentMetadata(BasePlayer.java:1320)
	at org.schabi.newpipe.player.BasePlayer.onTimelineChanged(BasePlayer.java:677)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$0$ExoPlayerImpl$PlaybackInfoUpdate(ExoPlayerImpl.java:804)
	at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$PlaybackInfoUpdate$N_S5kRfhaRTAkH28P5luFgKnFjQ.invokeListener(Unknown Source:2)
	at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:182)
	at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:845)
	at com.google.android.exoplayer2.ExoPlayerImpl.access$000(ExoPlayerImpl.java:43)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.run(ExoPlayerImpl.java:802)
	at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:736)
	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:710)
	at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:652)
	at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:595)
	at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:127)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8034)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

```
</details>
<hr>

**Comment by snappyapple632** [comment]
I'm not able to reproduce with the steps given.

**Comment by avently** [comment]
@snappyapple632 missing step is to enable Autoplay of the next stream from the bottom of the page.
There is no suggested videos that's why it crashes. Should be fixes easily

**Comment by wb9688** [comment]
@avently: Yup, this issue has been reported before in #4112 though (and is caused by some PR I made).
