### ISSUE TITLE
Unable to open error activity: too much data put into the intent

### ISSUE THREAD

**Issue by Stypox** [TeamNewPipe/NewPipe#4262]
### Version

- 0.19.8
- also apk from # 3178

### Steps to reproduce the bug

This is not reproducible consistently, but the solution should just be to dump the error to disk instead of passing it via the intent.

### Logs

* User Action: ui error
* Request: App crash, UI failure
* Content Country: GB
* Content Language: en-GB
* App Language: en
* Service: none
* Version: 0.19.8
* OS: Linux Android 7.0 - 24
<details><summary><b>Crash log </b></summary>
<p><pre>
java.lang.RuntimeException: Failure from system
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1546)
	at android.app.Activity.startActivityForResult(Activity.java:4391)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
	at android.app.Activity.startActivityForResult(Activity.java:4335)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
	at android.app.Activity.startActivity(Activity.java:4702)
	at android.app.Activity.startActivity(Activity.java:4670)
	at org.schabi.newpipe.report.ErrorActivity.startErrorActivity(ErrorActivity.java:121)
	at org.schabi.newpipe.report.ErrorActivity.lambda$reportError$0(ErrorActivity.java:107)
	at org.schabi.newpipe.report.-$$Lambda$ErrorActivity$EKKqNRPfPrIj_XzvDeJIdwTG77M.onClick(lambda)
	at com.google.android.material.snackbar.Snackbar$1.onClick(Snackbar.java:296)
	at android.view.View.performClick(View.java:5646)
	at android.view.View$PerformClick.run(View.java:22473)
	at android.os.Handler.handleCallback(Handler.java:761)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6517)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
Caused by: android.os.TransactionTooLargeException: data parcel size 1123020 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:617)
	at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3096)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1539)
	... 19 more
</pre>
</details>
<hr>

**Comment by opusforlife2** [comment]
> dump the error to disk 

And then read from disk to generate the crash report?

**Comment by Stypox** [comment]
Yes
