### ISSUE TITLE
RequestException on loading feed

### ISSUE THREAD

**Issue by yopox** [TeamNewPipe/NewPipe#4269]
## Exception
* User Action: requested feed
* Request: Loading feed
* Content Country: US
* Content Language: en-US
* App Language: en_US
* Service: none
* Version: 0.19.8
* OS: Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

org.schabi.newpipe.local.feed.service.FeedLoadService$RequestException: 0:https://www.youtube.com/channel/UCkjEqPY4fcDZFYER-rF8kmA
 at org.schabi.newpipe.local.feed.service.FeedLoadService$RequestException$Companion.wrapList(FeedLoadService.kt:165)
 at org.schabi.newpipe.local.feed.service.FeedLoadService$databaseConsumer$1$1.run(FeedLoadService.kt:314)
 at androidx.room.RoomDatabase.runInTransaction(RoomDatabase.java:410)
 at org.schabi.newpipe.local.feed.service.FeedLoadService$databaseConsumer$1.accept(FeedLoadService.kt:303)
 at org.schabi.newpipe.local.feed.service.FeedLoadService$databaseConsumer$1.accept(FeedLoadService.kt:66)
 at io.reactivex.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onNext(FlowableDoOnEach.java:86)
 at io.reactivex.internal.operators.flowable.FlowableBuffer$PublisherBufferExactSubscriber.onNext(FlowableBuffer.java:126)
 at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:407)
 at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
 at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
 at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:923)
Caused by: org.schabi.newpipe.extractor.exceptions.ContentNotSupportedException: This channel has no Videos tab
 at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.getVideoTab(YoutubeChannelExtractor.java:322)
 at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.getInitialPage(YoutubeChannelExtractor.java:234)
 at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)
 at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:83)
 at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:48)
 at org.schabi.newpipe.util.ExtractorHelper.lambda$getChannelInfo$4(ExtractorHelper.java:124)
 at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$u5W7VszTe8AoEexIsFM9huQfbkM.call(Unknown Source:4)
 at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
 at io.reactivex.Single.subscribe(Single.java:3666)
 at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
 at io.reactivex.Single.subscribe(Single.java:3666)
 at io.reactivex.Single.blockingGet(Single.java:2869)
 at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:217)
 at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:66)
 at io.reactivex.internal.operators.parallel.ParallelMap$ParallelMapSubscriber.onNext(ParallelMap.java:113)
 at io.reactivex.internal.operators.parallel.ParallelFilter$ParallelFilterSubscriber.tryOnNext(ParallelFilter.java:130)
 at io.reactivex.internal.operators.parallel.ParallelRunOn$RunOnConditionalSubscriber.run(ParallelRunOn.java:397)
 ... 7 more

</details>
<hr>

It happens every time I refresh the feed. New elements continue to appear though.

**Comment by wb9688** [comment]
You've subscribed to https://www.youtube.com/channel/UCkjEqPY4fcDZFYER-rF8kmA, which doesn't have a Videos tab

**Comment by TobiGr** [comment]
We should handle that better.

**Comment by opusforlife2** [comment]
So shouldn't we keep this open? Or is this a duplicate of some other issue?

**Comment by wb9688** [comment]
@opusforlife2: This is definitely a duplicate of many other issues. Also this issue shouldn't be kept open, as it's expected behavior. Someone might however create another issue requesting a better UI for such cases, though maybe we already did that at some point, not sure.

**Comment by opusforlife2** [comment]
@wb9688 I opened the channel in 0.19.8. It says "this content is not supported, future version, etc."

So the case of opening the channel is handled well.

But it seems like the Feed code doesn't take such channels into account, and that's what we need to handle?

**Comment by yopox** [comment]
From a user point of view it's unclear that this error concerns a channel without videos. Such channels could be skipped when importing subs, or the exception could be hidden if the channel exists. (maybe it will have videos one day?)

**Comment by opusforlife2** [comment]
Oops. I forgot to link. Duplicate of #3646.
