### ISSUE TITLE
External player didn't work; exoplayer didn't work, and now app won't stop flashing white screen.

### ISSUE THREAD

**Issue by Rbagman** [TeamNewPipe/NewPipe#428]
I tried the external player (VLC) and it didn't work; I tried exoplayer and it didn't work: just kep flashing blank white screen. After clearing cache/data and uninstall/reinstall all the app does is 
flashing a white scree.

[Samsung GT-N7100/Android 4.4.2]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.schabi.newpipe/org.schabi.newpipe.report.ErrorActivity}: android.view.InflateException: Binary XML file line #41: Error inflating class TextView
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
	at android.app.ActivityThread.access$900(ActivityThread.java:175)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5602)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.view.InflateException: Binary XML file line #41: Error inflating class TextView
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:719)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
	at android.view.LayoutInflater.inflate(Native Method)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:288)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:143)
	at org.schabi.newpipe.report.ErrorActivity.onCreate(ErrorActivity.java:244)
	at android.app.Activity.performCreate(Activity.java:5451)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377)
	... 12 more
Caused by: android.content.res.Resources$NotFoundException: Resource is not a ColorStateList (color or path): TypedValue{t=0x5/d=0x1001 a=2 r=0x105002b}
	at android.content.res.Resources.loadColorStateList(Resources.java:3588)
	at android.content.res.TypedArray.getColorStateList(TypedArray.java:343)
	at android.content.res.XResources$XTypedArray.getColorStateList(XResources.java:912)
	at android.widget.TextView.<init>(TextView.java:1485)
	at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:62)
	at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:58)
	at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
	at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1021)
	at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1080)
	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:47)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:690)
	... 27 more
```

**Comment by ksyko** [comment]
Did you try this?
https://github.com/TeamNewPipe/NewPipe/pull/427

**Comment by Rbagman** [comment]
I tried newpipe88.apk
The errir popped when I tried to go to the downloads screen after starting a download.

{
   "user_action": "ui error",
   "exceptions": [
      "java.lang.NullPointerException\n\tat us.shandian.giga.ui.adapter.MissionAdapter.<init>(MissionAdapter.java:59)\n\tat us.shandian.giga.ui.fragment.MissionsFragment.updateList(MissionsFragment.java:116)\n\tat us.shandian.giga.ui.fragment.MissionsFragment.access$200(MissionsFragment.java:30)\n\tat us.shandian.giga.ui.fragment.MissionsFragment$1.onServiceConnected(MissionsFragment.java:51)\n\tat android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1114)\n\tat android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1131)\n\tat android.os.Handler.handleCallback(Handler.java:733)\n\tat android.os.Handler.dispatchMessage(Handler.java:95)\n\tat android.os.Looper.loop(Looper.java:146)\n\tat android.app.ActivityThread.main(ActivityThread.java:5602)\n\tat java.lang.reflect.Method.invokeNative(Native Method)\n\tat java.lang.reflect.Method.invoke(Method.java:515)\n\tat com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)\n\tat de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)\n\tat dalvik.system.NativeStart.main(Native Method)\n"
   ],
   "os": "Linux Android 4.4.2 - 19",
   "time": "2017-01-27 13:25",
   "ip_range": "71.174.0.0",
   "request": "App crash, UI failure",
   "package": "org.schabi.newpipe",
   "service": "none",
   "content_language": "en",
   "user_comment": "",
   "version": "0.8.8"
}

**Comment by ksyko** [comment]
`private void viewFileWithFileProvider(File file, String mimetype) {
		String ourPackage = mContext.getApplicationContext().getPackageName();
		Uri uri = FileProvider.getUriForFile(mContext,  ourPackage + ".provider", file);
		Intent intent = new Intent();
		intent.setAction(Intent.ACTION_VIEW);
		intent.setDataAndType(uri, mimetype);
		intent.addFlags(FLAG_GRANT_READ_URI_PERMISSION);
		if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
			intent.addFlags(FLAG_GRANT_PREFIX_URI_PERMISSION);
		}
		//mContext.grantUriPermission(packageName, uri, Intent.FLAG_GRANT_READ_URI_PERMISSION);
		Log.v(TAG, "Starting intent: " + intent);
		mContext.startActivity(intent);
	}`

I guess this is the issue. [MissionAdapter.java : 273]

**Comment by ksyko** [comment]
Could it because of line 273 [here?](https://github.com/TeamNewPipe/NewPipe/blob/master/app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java#footer)

One of the line is only for lollipop+

**Comment by coffeemakr** [comment]
It seems like `mContext == null` in [MissionAdapter.java:59](https://github.com/TeamNewPipe/NewPipe/blob/master/app/src/main/java/us/shandian/giga/ui/adapter/MissionAdapter.java#L59) which would mean that the [binder](https://github.com/TeamNewPipe/NewPipe/blob/master/app/src/main/java/us/shandian/giga/ui/fragment/MissionsFragment.java#L48) is called before [onAttached](https://github.com/TeamNewPipe/NewPipe/blob/master/app/src/main/java/us/shandian/giga/ui/fragment/MissionsFragment.java#L88) is called (which sets mActivity).

Does this error occur every time?

**Comment by Rbagman** [comment]
F-Droid updated to the latest version.

{
   "user_action": "ui error",
   "exceptions": [
      "java.lang.NullPointerException\n\tat us.shandian.giga.ui.adapter.MissionAdapter.<init>(MissionAdapter.java:59)\n\tat us.shandian.giga.ui.fragment.MissionsFragment.updateList(MissionsFragment.java:116)\n\tat us.shandian.giga.ui.fragment.MissionsFragment.access$200(MissionsFragment.java:30)\n\tat us.shandian.giga.ui.fragment.MissionsFragment$1.onServiceConnected(MissionsFragment.java:51)\n\tat android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1114)\n\tat android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1131)\n\tat android.os.Handler.handleCallback(Handler.java:733)\n\tat android.os.Handler.dispatchMessage(Handler.java:95)\n\tat android.os.Looper.loop(Looper.java:146)\n\tat android.app.ActivityThread.main(ActivityThread.java:5602)\n\tat java.lang.reflect.Method.invokeNative(Native Method)\n\tat java.lang.reflect.Method.invoke(Method.java:515)\n\tat com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)\n\tat de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)\n\tat dalvik.system.NativeStart.main(Native Method)\n"
   ],
   "os": "Linux Android 4.4.2 - 19",
   "time": "2017-02-05 23:44",
   "ip_range": "71.174.0.0",
   "request": "App crash, UI failure",
   "package": "org.schabi.newpipe",
   "service": "none",
   "content_language": "en",
   "user_comment": "",
   "version": "0.8.9"
}
