### ISSUE TITLE
Could not load decrypt function

### ISSUE THREAD

**Issue by priyankvirani** [TeamNewPipe/NewPipe#431]
```
01-31 10:13:10.628 20522-20796/org.schabi.newpipe D/OpenGLRenderer: endAllStagingAnimators on 0xa072f000 (RippleDrawable) with handle 0xa0c4e380
01-31 10:13:10.923 20522-20892/org.schabi.newpipe W/System.err: org.schabi.newpipe.extractor.services.youtube.YoutubeStreamExtractor$DecryptException: Could not load decrypt function
01-31 10:13:10.923 20522-20892/org.schabi.newpipe W/System.err:     at org.schabi.newpipe.extractor.services.youtube.YoutubeStreamExtractor.loadDecryptionCode(YoutubeStreamExtractor.java:815)
01-31 10:13:10.923 20522-20892/org.schabi.newpipe W/System.err:     at org.schabi.newpipe.extractor.services.youtube.YoutubeStreamExtractor.<init>(YoutubeStreamExtractor.java:217)
01-31 10:13:10.923 20522-20892/org.schabi.newpipe W/System.err:     at org.schabi.newpipe.extractor.services.youtube.YoutubeService.getExtractorInstance(YoutubeService.java:51)
01-31 10:13:10.923 20522-20892/org.schabi.newpipe W/System.err:     at org.schabi.newpipe.detail.StreamInfoWorker$StreamExtractorRunnable.run(StreamInfoWorker.java:80)
01-31 10:13:10.923 20522-20892/org.schabi.newpipe W/System.err:     at java.lang.Thread.run(Thread.java:818)
01-31 10:13:10.923 20522-20892/org.schabi.newpipe W/System.err: Caused by: java.net.MalformedURLException: Protocol not found: /yts/jsbin/player-en_US-vflV3n15C/base.js
01-31 10:13:10.923 20522-20892/org.schabi.newpipe W/System.err:     at java.net.URL.<init>(URL.java:176)
01-31 10:13:10.923 20522-20892/org.schabi.newpipe W/System.err:     at java.net.URL.<init>(URL.java:125)
01-31 10:13:10.923 20522-20892/org.schabi.newpipe W/System.err:     at org.schabi.newpipe.Downloader.download(Downloader.java:141)
01-31 10:13:10.923 20522-20892/org.schabi.newpipe W/System.err:     at org.schabi.newpipe.extractor.services.youtube.YoutubeStreamExtractor.loadDecryptionCode(YoutubeStreamExtractor.java:794)
```

**Comment by theScrabi** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/430

**Comment by priyankvirani** [comment]
any solution for Could not load decrypt function ?
>>

**Comment by theScrabi** [comment]
Please look at the thread if linked to this one.

**Comment by theScrabi** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/430
