### ISSUE TITLE
Unable to load comments + (Re)Captcha issue

### ISSUE THREAD

**Issue by johnth3doe** [TeamNewPipe/NewPipe#4312]
Bug report:- 
## Exception
* __User Action:__ requested comments
* __Request:__ https://m.youtube.com/watch?v=YZRCepJLFtk
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en
* __Service:__ YouTube
* __Version:__ 0.19.8
<details><summary><b>Crash log </b></summary><p>

```
java.lang.StringIndexOutOfBoundsException: length=9616; regionStart=14; regionLength=-15
	at java.lang.String.startEndAndLength(String.java:298)
	at java.lang.String.substring(String.java:1087)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.findValue(YoutubeCommentsExtractor.java:165)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getInitialPage(YoutubeCommentsExtractor.java:51)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:40)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:25)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getCommentsInfo$7(ExtractorHelper.java:155)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$Xyj84g1UeNZqX9LVYNvWZsdT-kI.call(lambda)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

```
</details>
<hr>

Note: I have simultaneously been afflicted by the issue mentioned in #3714 regardless of network or WiFi connection, however using a VPN service negates the issue.
Also Note: Comment issue started after uninstalling and reinstalling NP.

**Comment by Abdel-ilah** [comment]
Yeah me too, but only when I use G4 internet connection, work fine with WiFi, any good news for this issue?
Thanks Developers

**Comment by Stypox** [comment]
#3714

**Comment by johnth3doe** [comment]
@Stypox: Kindly reopen the issue. While #3714 has been mentioned in the main post, the "comments" issue is a separate (if not unrelated) bug.

**Comment by johnth3doe** [comment]
> Yeah me too, but only when I use G4 internet connection, work fine with WiFi, any good news for this issue?
> Thanks Developers

As I mentioned, the issue still persists on WiFi for me.

Also, while the following comment suggests no solution:- 
https://github.com/TeamNewPipe/NewPipe/issues/3714#issuecomment-636674777

I came across:-
https://github.com/TeamNewPipe/NewPipe/pull/3414

That being said, please feel free to correct and improve my understanding if I am mistaken.
