### ISSUE TITLE
Scheduled streams, which did not take place, are not extracted properly 

### ISSUE THREAD

**Issue by sarathpkanichodu** [TeamNewPipe/NewPipe#4314]
## Exception
* __User Action:__ requested feed
* __Request:__ Loading feed
* __Content Country:__ IN
* __Content Language:__ en-IN
* __App Language:__ en_IN
* __Service:__ none
* __Version:__ 0.19.8
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.local.feed.service.FeedLoadService$RequestException: 0:https://www.youtube.com/channel/UCKMnl27hDMKvch--noWe5CA
	at org.schabi.newpipe.local.feed.service.FeedLoadService$RequestException$Companion.wrapList(FeedLoadService.kt:165)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$databaseConsumer$1$1.run(FeedLoadService.kt:314)
	at androidx.room.RoomDatabase.runInTransaction(RoomDatabase.java:410)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$databaseConsumer$1.accept(FeedLoadService.kt:303)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$databaseConsumer$1.accept(FeedLoadService.kt:66)
	at io.reactivex.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onNext(FlowableDoOnEach.java:86)
	at io.reactivex.internal.operators.flowable.FlowableBuffer$PublisherBufferExactSubscriber.onComplete(FlowableBuffer.java:152)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.checkTerminated(FlowableObserveOn.java:215)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:399)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get duration
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamInfoItemExtractor.getDuration(YoutubeStreamInfoItemExtractor.java:117)
	at org.schabi.newpipe.extractor.stream.StreamInfoItemsCollector.extract(StreamInfoItemsCollector.java:54)
	at org.schabi.newpipe.extractor.stream.StreamInfoItemsCollector.commit(StreamInfoItemsCollector.java:94)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.collectStreamsFrom(YoutubeChannelExtractor.java:289)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.getInitialPage(YoutubeChannelExtractor.java:239)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)
	at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:83)
	at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:48)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getChannelInfo$4(ExtractorHelper.java:124)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$u5W7VszTe8AoEexIsFM9huQfbkM.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.Single.blockingGet(Single.java:2869)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:217)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:66)
	at io.reactivex.internal.operators.parallel.ParallelMap$ParallelMapSubscriber.onNext(ParallelMap.java:113)
	at io.reactivex.internal.operators.parallel.ParallelFilter$ParallelFilterSubscriber.tryOnNext(ParallelFilter.java:130)
	at io.reactivex.internal.operators.parallel.ParallelRunOn$RunOnConditionalSubscriber.run(ParallelRunOn.java:397)
	... 7 more

```
</details>
<hr>

**Comment by wb9688** [comment]
Hmm… it seems to be unable to get the duration of one of the videos from https://www.youtube.com/channel/UCKMnl27hDMKvch--noWe5CA

I could reproduce it here.

**Comment by TobiGr** [comment]
https://www.youtube.com/watch?v=VniAzlaW4fU is a livestream `Scheduled for 20 Jun 2017`. that seems either to be a bug on YouTube's side or the channel planned a livestream, but never streamed and did not remove the scheduled event...

![Screenshot_2020-09-25 Cogito](https://user-images.githubusercontent.com/17365767/94278319-f3225e00-ff4a-11ea-8f24-a55398e868da.png)

That's a scenario we should have tested. Why didn't we think of something like that :rofl:

**Comment by opusforlife2** [comment]
> Why didn't we think of something like that 🤣

Who would have? O.o

**Comment by TobiGr** [comment]
Why are you closing the issue? The problem is still there.

**Comment by sarathpkanichodu** [comment]
Sorry. I reopened the issue

**Comment by sarathpkanichodu** [comment]
Sorry I reopened the issue.

**Comment by opusforlife2** [comment]
Is this a crash or just an error?

**Comment by AudricV** [comment]
The live tab of channel has disappeared. As this is a very rare issue and as I think this should be now handled properly (or will be very soon to adapt with the lockup view model rollout on channels last month), I am closing this issue as stale.
