### ISSUE TITLE
Constant error message pop up.

### ISSUE THREAD

**Issue by Flam3z** [TeamNewPipe/NewPipe#4385]
### Checklist
(Sorry i dont know how to add in the check)

- [yes ] I am using the latest version. 
- [yes ] I checked, but didn't find any duplicates of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ yes] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1.Practically do amy action on NewPipe
2.Wait until said, error message appears.

### Actual behaviour

App says it has encountered an error

### Expected behavior

Error message shouldn't come up as I did not experience any issues.

## Exception
* __User Action:__ requested feed
* __Request:__ Loading feed
* __Content Country:__ US
* __Content Language:__ en
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.20.0
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.local.feed.service.FeedLoadService$RequestException: 0:https://www.youtube.com/channel/UCxJf49T4iTO_jtzWX3rW_jg
	at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:223)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:66)
	at io.reactivex.internal.operators.parallel.ParallelMap$ParallelMapSubscriber.onNext(ParallelMap.java:113)
	at io.reactivex.internal.operators.parallel.ParallelFilter$ParallelFilterSubscriber.tryOnNext(ParallelFilter.java:130)
	at io.reactivex.internal.operators.parallel.ParallelRunOn$RunOnConditionalSubscriber.run(ParallelRunOn.java:397)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.RuntimeException: org.schabi.newpipe.extractor.exceptions.ContentNotAvailableException: Got error: "This account has been terminated due to multiple or severe violations of YouTube's policy prohibiting content designed to harass, bully or threaten."
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
	at io.reactivex.Single.blockingGet(Single.java:2870)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:217)
	... 11 more
Caused by: org.schabi.newpipe.extractor.exceptions.ContentNotAvailableException: Got error: "This account has been terminated due to multiple or severe violations of YouTube's policy prohibiting content designed to harass, bully or threaten."
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.defaultAlertsCheck(YoutubeParsingHelper.java:546)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.onFetchPage(YoutubeChannelExtractor.java:109)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:56)
	at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:47)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getChannelInfo$4(ExtractorHelper.java:124)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$u5W7VszTe8AoEexIsFM9huQfbkM.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.Single.blockingGet(Single.java:2869)
	... 12 more

```
</details>
<hr>

Device Info: Galaxy S10 (Running Android 10)

**Comment by TobiGr** [comment]
You have a channel which has been terminated / banned. Please unsubscribe from it.
We should improve handling of these cases. But that's already disscussed in another ticket

**Comment by wb9688** [comment]
You could check the checkboxes by replacing the space with a x, or by going to the preview and just checking them.

**Comment by Flam3z** [comment]
@wb9688 @TobiGR thank you both for the helpful info.

**Comment by rachmadaniHaryono** [comment]
>  We should improve handling of these cases. But that's already disscussed in another ticket

@TobiGr can you point me which one?

**Comment by TobiGr** [comment]
https://www.youtube.com/channel/UCxJf49T4iTO_jtzWX3rW_jg

**Comment by opusforlife2** [comment]
The user asked for the ticket, @TobiGr, not an example of a deleted channel. 🤭

**Comment by TobiGr** [comment]
Oh, sorry :laughing: 

#3313
