### ISSUE TITLE
Fast forward crush 

### ISSUE THREAD

**Issue by baraa272** [TeamNewPipe/NewPipe#4390]
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.20.0
* __OS:__ Linux Android 7.0 - 24
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to read from field 'java.util.ArrayList androidx.core.app.NotificationCompat$Builder.mActions' on a null object reference
	at org.schabi.newpipe.player.NotificationUtil.shouldUpdateBufferingSlot(NotificationUtil.java:151)
	at org.schabi.newpipe.player.VideoPlayerImpl.onBuffering(VideoPlayerImpl.java:1121)
	at org.schabi.newpipe.player.BasePlayer.changeState(BasePlayer.java:583)
	at org.schabi.newpipe.player.VideoPlayerImpl.changeState(VideoPlayerImpl.java:1102)
	at org.schabi.newpipe.player.BasePlayer.onPlayerStateChanged(BasePlayer.java:798)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$5$ExoPlayerImpl$PlaybackInfoUpdate(ExoPlayerImpl.java:828)
	at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$PlaybackInfoUpdate$AYkTJomZb3BnUDA59u8cvRVoKcM.invokeListener(lambda)
	at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:182)
	at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:845)
	at com.google.android.exoplayer2.ExoPlayerImpl.access$000(ExoPlayerImpl.java:43)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.run(ExoPlayerImpl.java:826)
	at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:736)
	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:710)
	at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:652)
	at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:595)
	at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:127)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6692)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

```
</details>
<hr>

**Comment by wb9688** [comment]
@baraa272: Could you give exact steps to reproduce, like asked in the issue template?

@Stypox: Could you look at this?

**Comment by baraa272** [comment]
1. Go full screen in landscape 
2. Pause the video 
3. Do a fast forward 
Baaaaaam crush 
Notice doesn't happen when video is played

**Comment by opusforlife2** [comment]
It's scary how this bug slipped through.

**Comment by opusforlife2** [comment]
@TobiGr I think this is bad enough to warrant a hotfix.
