### ISSUE TITLE
it always crashes 

### ISSUE THREAD

**Issue by CaiusCosades** [TeamNewPipe/NewPipe#4448]
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ US
* __Content Language:__ en
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.20.0
* __OS:__ Linux samsung/dreamltexx/dreamlte:9/PPR1.180610.011/G950FXXU9DTF1:user/release-keys 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List org.schabi.newpipe.extractor.stream.StreamInfo.getAudioStreams()' on a null object reference
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.openBackgroundPlayer(VideoDetailFragment.java:1018)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.onClick(VideoDetailFragment.java:478)
	at android.view.View.performClick(View.java:7352)
	at android.widget.TextView.performClick(TextView.java:14230)
	at android.view.View.performClickInternal(View.java:7318)
	at android.view.View.access$3200(View.java:846)
	at android.view.View$PerformClick.run(View.java:27800)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7050)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

```
</details>
<hr>

**Comment by opusforlife2** [comment]
Why do people seem to think that having a crash log is some sort of "Get out of jail free" card when it comes to filling the template? xD

Edit your issue. Fill in the template. Tell us how you produce the crash. If it happens in multiple ways, tell us all the ways.

Closing until more information is provided.

**Comment by MD77MD** [comment]
maybe because, like review else, I thought that it already includes all the information needed.

**Comment by opusforlife2** [comment]
It doesn't say that anywhere in the app or the Error activity. I suppose we'll have to put in yet another line telling people that the crash report just contains basic information and they still need to fill out the bug report template. :/
