### ISSUE TITLE
Crash on `ui error`

### ISSUE THREAD

**Issue by yashpalgoyal1304** [TeamNewPipe/NewPipe#4546]
### Checklist

- [x] I am using the latest version. 
- [x] I checked, but didn't find any duplicates of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. The background queue was playing with auto-play on, 
2. i searched for smth (in newpipe ofc) and clicked on one video to go to details page. 
3. it crashed.

### Logs

Have a running playlist in background, and open a new video from search results.
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ DE
* __Content Language:__ en-US
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.20.0
* __OS:__ Linux Android 7.0 - 24
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int org.schabi.newpipe.player.playqueue.PlayQueueItem.getServiceId()' on a null object reference
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.onQueueUpdate(VideoDetailFragment.java:1736)
	at org.schabi.newpipe.player.helper.PlayerHolder$2.onQueueUpdate(PlayerHolder.java:181)
	at org.schabi.newpipe.player.VideoPlayerImpl.updateQueue(VideoPlayerImpl.java:1982)
	at org.schabi.newpipe.player.VideoPlayerImpl.setFragmentListener(VideoPlayerImpl.java:1955)
	at org.schabi.newpipe.player.helper.PlayerHolder.startPlayerListener(PlayerHolder.java:130)
	at org.schabi.newpipe.player.helper.PlayerHolder.setListener(PlayerHolder.java:39)
	at org.schabi.newpipe.player.helper.PlayerHolder.startService(PlayerHolder.java:51)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.initListeners(VideoDetailFragment.java:712)
	at org.schabi.newpipe.BaseFragment.onViewCreated(BaseFragment.java:72)
	at org.schabi.newpipe.fragments.BaseStateFragment.onViewCreated(BaseStateFragment.java:56)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:332)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6146)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: 7.0
 - Device model: Prime P30

----
source of the package: fdroid repo

**Comment by opusforlife2** [comment]
That checklist isn't optional, you know. You should read the contribution guidelines and _always_ check for duplicates.

**Comment by yashpalgoyal1304** [comment]
i do, but when i have at least some clue of either the thing/issue, or the project. But since i dont know either of these (it just crashed & am new to the project) - i couldnt figure out how to search for it. Plus i got sidetracked many times already while browsing through existing issues and comments.

I have read the guidelines now, and there was nothing new/non obvious.

**Comment by opusforlife2** [comment]
Different STR but same crash: https://github.com/TeamNewPipe/NewPipe/issues/3440#issuecomment-689169727

**Comment by yashpalgoyal1304** [comment]
STR!!?

**Comment by opusforlife2** [comment]
Special Theory of Relativity, or... Steps To Reproduce.

Take your pick. :P

**Comment by yashpalgoyal1304** [comment]
also, any comment on if u were able to reproduce the crash @opusforlife2 {& the related info as usual} ?!

**Comment by opusforlife2** [comment]
Good point. I don't get a crash.

Can you try the same steps once again just to confirm? If you can still reproduce the crash, a screen record might be helpful.

**Comment by UserX404** [comment]
Maybe a (the) similar problem:
Backgroud player crashes/locks my phone. I have to insert my unlock pattern but afterwards it gets locked again. I'm not able to use my phone and have to reboot it.
So i'm also not able to submit a log.
Sony Xperia XZ2c
Android 10
Tested with 0.20.0 and 0.20.1.
0.19.8 is the last functional version.

**Comment by nonremittal** [comment]
Same deal as above, Xiaomi Mi A2.

When using the background player and unlocking my phone, it either re-locks, displays a black screen, or (in one instance) got rid of the notification bar for my entire phone!

A few times it has caused my phone to crash completely and restart in a terminal mode which was very scary.

I really hope 0.19 continues to work for the foreseeable future. I'm not a fan of the unified player at all (back button doesn't work how I expect, takes way more taps to do the same things, etc.)

**Comment by opusforlife2** [comment]
@UserX404 @nonremittal Please try the test APK in #4555.

@nonremittal Check out #4569.

**Comment by UserX404** [comment]
@opusforlife2 Thanks for response.
I've tested the debug edition. First it seems backgroundplayer is working but after some attemps to start different videos in fore- and background while a video is running (fore- or background) my phone get locked and i run into the same situation which i mentioned above.
Is there a possibility to submit debug logs or something else that can help you?
Heap dump -> [2020-10-20_19-33-42_541_heap.zip](https://github.com/TeamNewPipe/NewPipe/files/5410493/2020-10-20_19-33-42_541_heap.zip)

**Comment by yashpalgoyal1304** [comment]
i also tried 2-3 times on same version as reported in description (0.20.0, 954) but cant reproduce. so, when i cant reproduce it in this version itself, how can i test if its fixed or not 😃. so, am unable to check that debug one too for the time being. 

~"needs reproducibility"

**Comment by opusforlife2** [comment]
@UserX404 Thank you for the logs. When you test an APK you're testing that PR's code, so it is more appropriate to post your findings in the PR thread.

@Stypox Logs for you.

**Comment by nonremittal** [comment]
@opusforlife2 Tried it, same issue. Constant black screen, can't unlock my phone until I restart.

Seems like a really serious bug so I hope it's fixed soon!

**Comment by yashpalgoyal1304** [comment]
hi, i think it can be closed. 'cz this issue was not reproducible with me
