### ISSUE TITLE
/!\Can access app, cannot play any media/¡\

### ISSUE THREAD

**Issue by Josephmama** [TeamNewPipe/NewPipe#4672]
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.20.1
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int org.schabi.newpipe.player.playqueue.PlayQueueItem.getServiceId()' on a null object reference
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.onQueueUpdate(VideoDetailFragment.java:1736)
	at org.schabi.newpipe.player.helper.PlayerHolder$2.onQueueUpdate(PlayerHolder.java:181)
	at org.schabi.newpipe.player.VideoPlayerImpl.updateQueue(VideoPlayerImpl.java:1982)
	at org.schabi.newpipe.player.VideoPlayerImpl.setFragmentListener(VideoPlayerImpl.java:1955)
	at org.schabi.newpipe.player.helper.PlayerHolder.startPlayerListener(PlayerHolder.java:130)
	at org.schabi.newpipe.player.helper.PlayerHolder.setListener(PlayerHolder.java:39)
	at org.schabi.newpipe.player.helper.PlayerHolder.startService(PlayerHolder.java:51)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.initListeners(VideoDetailFragment.java:712)
	at org.schabi.newpipe.BaseFragment.onViewCreated(BaseFragment.java:72)
	at org.schabi.newpipe.fragments.BaseStateFragment.onViewCreated(BaseStateFragment.java:56)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:332)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2169)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7386)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

```
</details>
<hr>

**Comment by opusforlife2** [comment]
Could you test the steps in #4546?

**Comment by thowan** [comment]
v20 is so bugged it's like a joke compared to the previous versions. Who asked for a "unified" player? Why break a fully functional nearly flawless app for something nobody asked for?

**Comment by TheAssassin** [comment]
Closing, as the new release has been published.

**Comment by opusforlife2** [comment]
@TheAssassin Different error.

**Comment by ender2448** [comment]
I'm getting this same error, even after trying all the steps listed in #4546

**Comment by opusforlife2** [comment]
@ender2448 Those are steps to reproduce, which means when you repeat the steps, you _should_ get the problem. There is no solution posted in that issue.

**Comment by Stypox** [comment]
#4546
