### ISSUE TITLE
App/UI Crashed

### ISSUE THREAD

**Issue by Crimnoist** [TeamNewPipe/NewPipe#4683]
-------------------------------------
java.lang.RuntimeException: Error receiving broadcast Intent { act=org.schabi.newpipe.VideoDetailFragment.ACTION_PLAYER_STARTED flg=0x10 } in org.schabi.newpipe.MainActivity$3@6f4c412
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1493)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7050)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1691)
	at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1731)
	at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:321)
	at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:286)
	at org.schabi.newpipe.util.NavigationHelper.showMiniPlayer(NavigationHelper.java:399)
	at org.schabi.newpipe.MainActivity$3.onReceive(MainActivity.java:822)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0(LoadedApk.java:1483)
	... 8 more
-------------------------------------

**Comment by opusforlife2** [comment]
Please edit your issue and fill the template properly.
