### ISSUE TITLE
Random pause/play UI crash - app v20.2

### ISSUE THREAD

**Issue by Wahbam** [TeamNewPipe/NewPipe#4742]
I was playing a video in full screen on my Galaxy Tab A (SM-T350).  I think I accidentally paused the video by tapping the screen, but maybe it wasn't me.  When that happened, I tried double tapping on the left half of the screen to rewind 10seconds.  That's when the screen went black except for the triangular "play" icon in the middle.  I immediately pressed that to resume the video, and received this crash error.

I wont polute this bug report with confusing info about other problems I experience without supporting reports, but I'll say that I get a lot of crashes on a daily basis, 5 to 20 per day.  The last couple of versions have been especially bad for me, and that's aside from the captcha/app data problem that was fixed in 20.2.  This is not meant to complain, just inform of my concurrent issues which may have to do with app support for my older device.

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ CA
* __Content Language:__ en-CA
* __App Language:__ en_CA
* __Service:__ none
* __Version:__ 0.20.2
* __OS:__ Linux Android 7.1.1 - 25
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to read from field 'java.util.ArrayList androidx.core.app.NotificationCompat$Builder.mActions' on a null object reference
	at org.schabi.newpipe.player.NotificationUtil.shouldUpdateBufferingSlot(NotificationUtil.java:151)
	at org.schabi.newpipe.player.VideoPlayerImpl.onBuffering(VideoPlayerImpl.java:1121)
	at org.schabi.newpipe.player.BasePlayer.changeState(BasePlayer.java:583)
	at org.schabi.newpipe.player.VideoPlayerImpl.changeState(VideoPlayerImpl.java:1102)
	at org.schabi.newpipe.player.BasePlayer.onPlayerStateChanged(BasePlayer.java:798)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$5$ExoPlayerImpl$PlaybackInfoUpdate(ExoPlayerImpl.java:828)
	at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$PlaybackInfoUpdate$AYkTJomZb3BnUDA59u8cvRVoKcM.invokeListener(lambda)
	at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:182)
	at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:845)
	at com.google.android.exoplayer2.ExoPlayerImpl.access$000(ExoPlayerImpl.java:43)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.run(ExoPlayerImpl.java:826)
	at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:736)
	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:710)
	at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:652)
	at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:595)
	at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:127)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6823)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

```
</details>
<hr>

**Comment by Wahbam** [comment]
This report was posted in duplicate.  The first post returned a 404 error, leading me to believe it had not been submitted.  Closing this one.
