### ISSUE TITLE
App/UI crash when skipping while the video is paused

### ISSUE THREAD

**Issue by Ferrero11** [TeamNewPipe/NewPipe#4746]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Beginning playing any video.
2. PAUSE THE VIDEO. 
2. Attempt to skip through the playback using the double tap gestures.
3. App freezes for a second and shows a App UI crash log. 

### Actual behaviour
App UI Crash if the video is paused and you try to skip forward or back.

### Expected behavior
Skip through video playback using double tap gestures while paused

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.20.2
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to read from field 'java.util.ArrayList androidx.core.app.NotificationCompat$Builder.mActions' on a null object reference
	at org.schabi.newpipe.player.NotificationUtil.shouldUpdateBufferingSlot(NotificationUtil.java:151)
	at org.schabi.newpipe.player.VideoPlayerImpl.onBuffering(VideoPlayerImpl.java:1121)
	at org.schabi.newpipe.player.BasePlayer.changeState(BasePlayer.java:583)
	at org.schabi.newpipe.player.VideoPlayerImpl.changeState(VideoPlayerImpl.java:1102)
	at org.schabi.newpipe.player.BasePlayer.onPlayerStateChanged(BasePlayer.java:798)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$5$ExoPlayerImpl$PlaybackInfoUpdate(ExoPlayerImpl.java:828)
	at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$PlaybackInfoUpdate$AYkTJomZb3BnUDA59u8cvRVoKcM.invokeListener(Unknown Source:2)
	at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:182)
	at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:845)
	at com.google.android.exoplayer2.ExoPlayerImpl.access$000(ExoPlayerImpl.java:43)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.run(ExoPlayerImpl.java:826)
	at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:736)
	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:710)
	at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:652)
	at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:595)
	at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:127)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: Android 10 ASOiP 10-Quiche-RMX1931-20200812
 - Device model: Realme X2 Pro RMX 1931

**Comment by Stypox** [comment]
Already fixed, wait for 0.20.3
