### ISSUE TITLE
Could not parse shortened YouTube URL (from share button in official app)

### ISSUE THREAD

**Issue by tomaspinho** [TeamNewPipe/NewPipe#4758]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open official YouTube app
2. Press share on any video on feed
3. Open with NewPipe
4. Attempt playback in popup player (for example)

### Actual behaviour

App crashes

### Expected behavior

Start video playback

## Exception
* __User Action:__ requested stream
* __Request:__ https://youtu.be/VaO7MmghoqA, opened with popup_player
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ YouTube
* __Version:__ 0.20.1
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: YouTube did not provide player config even after three attempts
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:664)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:56)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:68)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleObserveOn.subscribeActual(SingleObserveOn.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.Single.subscribe(Single.java:3652)
	at org.schabi.newpipe.RouterActivity$FetcherService.handleChoice(RouterActivity.java:703)
	at org.schabi.newpipe.RouterActivity$FetcherService.onHandleIntent(RouterActivity.java:675)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:67)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: Oxygen OS 10.3.6
 - Device model: OnePlus 6

**Comment by opusforlife2** [comment]
Read the template carefully.

**Comment by tomaspinho** [comment]
I have edited the fields I found missing. Please reopen.

**Comment by tomaspinho** [comment]
@opusforlife2 please considering releasing the new version on Fdroid. I had no pending updates, and that's where I'm getting them.

**Comment by opusforlife2** [comment]
> please considering releasing the new version on Fdroid

Read the checklist comments in the template carefully.

**Comment by tomaspinho** [comment]
> > please considering releasing the new version on Fdroid
> 
> Read the checklist comments in the template carefully.

Sure, but why the "computer says no" approach to life? 😅

The comment isn't even related to the checklist. A fix for this has been released, but not on Fdroid. That's what I was pointing out. But I guess people here are not just very welcoming, that's a bit sad.

**Comment by opusforlife2** [comment]
@tomaspinho Now that you have read the template properly, you know your issue was invalid and didn't need to be opened.

If you instead search for f-droid updates here, you will see multiple issues where you're advised to either wait for F-Droid, or use our custom repo linked from the website.
