### ISSUE TITLE
Error when trying to play any video. 

### ISSUE THREAD

**Issue by jehutyy** [TeamNewPipe/NewPipe#4760]
I got this error when trying to play a video. Background or foreground doesn't matter it crashes with both.

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ GB
* __Content Language:__ en
* __App Language:__ fr_FR
* __Service:__ none
* __Version:__ 0.20.1
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'long org.schabi.newpipe.player.playqueue.PlayQueueItem.getRecoveryPosition()' on a null object reference
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.updateProgressInfo(VideoDetailFragment.java:1660)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.handleResult(VideoDetailFragment.java:1538)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.prepareAndHandleInfo(VideoDetailFragment.java:898)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$prepareAndHandleInfoIfNeededAfterDelay$2$VideoDetailFragment(VideoDetailFragment.java:882)
	at org.schabi.newpipe.fragments.detail.-$$Lambda$VideoDetailFragment$_RFesK110zEyxLwyqqz87oayaZg.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>
<hr>

**Comment by Stypox** [comment]
Update to 0.20.2
