### ISSUE TITLE
UI error in version 0.20.2 when adding content (playlist icon) to the UI

### ISSUE THREAD

**Issue by RaveZero** [TeamNewPipe/NewPipe#4769]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [X ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to 'New pipe settings'
2. Press on "content" => Content of the main page => Plus Icon
3. Select "playlist site"
4. The following error appears

## Exception
* __User Action:__ ui error
* __Request:__ 
* __Content Country:__ US
* __Content Language:__ en-EN
* __App Language:__ en_EN
* __Service:__ none
* __Version:__ 0.20.2
* __OS:__ Linux Android 5.1.1 - 22
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: The current thread must have a looper!
	at android.view.Choreographer$1.initialValue(Choreographer.java:98)
	at android.view.Choreographer$1.initialValue(Choreographer.java:93)
	at java.lang.ThreadLocal$Values.getAfterMiss(ThreadLocal.java:460)
	at java.lang.ThreadLocal.get(ThreadLocal.java:65)
	at android.view.Choreographer.getInstance(Choreographer.java:200)
	at android.animation.ValueAnimator$AnimationHandler.<init>(ValueAnimator.java:656)
	at android.animation.ValueAnimator$AnimationHandler.<init>(ValueAnimator.java:631)
	at android.animation.ValueAnimator.getOrCreateAnimationHandler(ValueAnimator.java:1453)
	at android.animation.ValueAnimator.end(ValueAnimator.java:1079)
	at android.graphics.drawable.AnimatedVectorDrawable.stop(AnimatedVectorDrawable.java:459)
	at android.widget.ProgressBar.stopAnimation(ProgressBar.java:1508)
	at android.widget.ProgressBar.onVisibilityChanged(ProgressBar.java:1568)
	at android.view.View.dispatchVisibilityChanged(View.java:9009)
	at android.view.View.setFlags(View.java:10099)
	at android.view.View.setVisibility(View.java:6962)
	at android.widget.ProgressBar.setVisibility(ProgressBar.java:1548)
	at org.schabi.newpipe.settings.SelectPlaylistFragment.displayPlaylists(SelectPlaylistFragment.java:143)
	at org.schabi.newpipe.settings.SelectPlaylistFragment.lambda$OKidrRDkz4wytGdEytcZ56EPSTU(SelectPlaylistFragment.java)
	at org.schabi.newpipe.settings.-$$Lambda$SelectPlaylistFragment$OKidrRDkz4wytGdEytcZ56EPSTU.accept(lambda)
	at io.reactivex.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65)
	at io.reactivex.internal.operators.flowable.FlowableCombineLatest$CombineLatestCoordinator.drainAsync(FlowableCombineLatest.java:374)
	at io.reactivex.internal.operators.flowable.FlowableCombineLatest$CombineLatestCoordinator.drain(FlowableCombineLatest.java:406)
	at io.reactivex.internal.operators.flowable.FlowableCombineLatest$CombineLatestCoordinator.innerValue(FlowableCombineLatest.java:250)
	at io.reactivex.internal.operators.flowable.FlowableCombineLatest$CombineLatestInnerSubscriber.onNext(FlowableCombineLatest.java:521)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onNext(FlowableSubscribeOn.java:97)
	at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.innerSuccess(FlowableFlatMapMaybe.java:175)
	at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber$InnerObserver.onSuccess(FlowableFlatMapMaybe.java:397)
	at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:61)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.onNext(FlowableFlatMapMaybe.java:132)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:407)
	at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

```
</details>
<hr>

### Expected behavior
Usually a playlist icon is added to the interface

### Logs
See above

### Device info

 - Android version/Custom ROM version: see above native Amazon OS with PlayStore/F-Droid
 - Device model: Amazon FireHD 10 2017

**Comment by Stypox** [comment]
@RaveZero could you test if the apk in #4771 fixes your issue?

**Comment by RaveZero** [comment]
> @RaveZero could you test if the apk in #4771 fixes your issue?

APK testing
@RaveZero could you test if this fixes your issue?
app-debug.zip

Yes, thank you, I was on a business trip and could successful ly test it today, no more errors also the videos are playing again.
