### ISSUE TITLE
Couldnt Parse Website

### ISSUE THREAD

**Issue by burakcemil731** [TeamNewPipe/NewPipe#4831]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour

after clicking on the video, it starts loading, comments dont show up and then it crashes with the error message that it couldnt parse the website

### Expected behavior

normally it should just play the video and load the comments

### Screenshots/Screen recordings

![Screenshot_20201107-124253_NewPipe](https://user-images.githubusercontent.com/71037199/98440097-da36cc00-20f6-11eb-8a80-ef4685603f6a.jpg)
![Screenshot_20201107-124247_NewPipe](https://user-images.githubusercontent.com/71037199/98440098-dacf6280-20f6-11eb-86d4-70730118f97a.jpg)
![Screenshot_20201107-124411_NewPipe](https://user-images.githubusercontent.com/71037199/98440112-fcc8e500-20f6-11eb-89b4-1405b5e17ac5.jpg)
![Screenshot_20201107-124409_NewPipe](https://user-images.githubusercontent.com/71037199/98440115-fdfa1200-20f6-11eb-8971-5b398a769bc8.jpg)

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=7i8ARjIeM2k
* __Content Country:__ US
* __Content Language:__ en
* __App Language:__ de_DE
* __Service:__ YouTube
* __Version:__ 0.20.1
* __OS:__ Linux samsung/dreamltexx/dreamlte:9/PPR1.180610.011/G950FXXU9DTF1:user/release-keys 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: YouTube did not provide player config even after three attempts
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:664)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:56)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:68)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by opusforlife2** [comment]
Pay close attention to the text of the issue template and you'll solve your own problem.
