### ISSUE TITLE
11Oxygen

### ISSUE THREAD

**Issue by bondik77** [TeamNewPipe/NewPipe#4832]
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ RU
* __Content Language:__ ru
* __App Language:__ ru
* __Service:__ none
* __Version:__ 0.9.4
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.ArrayIndexOutOfBoundsException: length=4; index=4
	at androidx.preference.ListPreference.getEntry(ListPreference.java:213)
	at androidx.preference.ListPreference.getSummary(ListPreference.java:164)
	at androidx.preference.Preference.onBindViewHolder(Preference.java:510)
	at androidx.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:418)
	at androidx.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:47)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:245)
	at android.app.ActivityThread.main(ActivityThread.java:7953)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

```
</details>
<hr>

**Comment by mhmdanas** [comment]
0.9.4 is a very old version. The latest version is 0.20.2, which is the one you should be using. In general, upgrade to the latest version before reporting a bug to check if the bug is still present.

**Comment by opusforlife2** [comment]
I really have to ask. Where did you get version 0.9.4??

**Comment by bondik77** [comment]
play market

  
>Суббота, 7 ноября 2020, 18:56 +03:00 от opusforlife2 <notifications@github.com>:
> 
> 
>Мне действительно нужно спросить.  Где вы взяли версию 0.9.4 ??
>- 
>Вы получаете это, потому что вы являетесь автором темы. 
>Ответьте на это письмо напрямую,  просмотрите его на GitHub или  откажитесь от подписки . 
 
 
--
Евгений RRRRRR

**Comment by opusforlife2** [comment]
@bondik77 Read https://github.com/TeamNewPipe/NewPipe#updates

The most secure source to get Newpipe from is F-Droid.

**Comment by bondik77** [comment]
play market

**Comment by opusforlife2** [comment]
@bondik77 That's probably a fake clone.

**Comment by opusforlife2** [comment]
> play market

@bondik77 Also, could you give a link to the app there?

**Comment by bondik77** [comment]
https://play.google.com/store/apps/details?id=you.tube.vanced



-- 
Евгений Филенков

**Comment by bondik77** [comment]
>https://play.google.com/store/apps/details?id=you.tube.vanced

**Comment by opusforlife2** [comment]
Thanks! That's definitely a clone. You should remove it completely and install Newpipe from Github or F-Droid instead.
