### ISSUE TITLE
"Play all" button in lists misbehaves when something is already playing

### ISSUE THREAD

**Issue by Stypox** [TeamNewPipe/NewPipe#4843]
### Checklist
- [x] I am using the latest version - 0.20.2 and (in the future) 0.20.3 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
- enqueue a random video in the background
- open a local playlist, a remote playlist, a channel or the history fragment
- tap on "Play all"

### Actual behaviour
The video details of the first item of the list are shown without starting the main player and the rest of the queue is not preserved

### Expected behavior
The main player should start playing right away and the already-playing queue should be completely replaced by the whole list (see #4562)

**Comment by LargePrime** [comment]
Yep, crash
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ CA
* __Content Language:__ en-CA
* __App Language:__ en_CA
* __Service:__ none
* __Version:__ 0.20.2
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start service org.schabi.newpipe.player.MainPlayer@720b36b with Intent { cmp=org.schabi.newpipe/.player.MainPlayer (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'int org.schabi.newpipe.player.playqueue.PlayQueueItem.getServiceId()' on a null object reference
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3821)
	at android.app.ActivityThread.access$1800(ActivityThread.java:207)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1779)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6863)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int org.schabi.newpipe.player.playqueue.PlayQueueItem.getServiceId()' on a null object reference
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.onQueueUpdate(VideoDetailFragment.java:1736)
	at org.schabi.newpipe.player.helper.PlayerHolder$2.onQueueUpdate(PlayerHolder.java:181)
	at org.schabi.newpipe.player.VideoPlayerImpl.updateQueue(VideoPlayerImpl.java:1982)
	at org.schabi.newpipe.player.VideoPlayerImpl.initPlayback(VideoPlayerImpl.java:714)
	at org.schabi.newpipe.player.BasePlayer.handleIntent(BasePlayer.java:376)
	at org.schabi.newpipe.player.VideoPlayer.handleIntent(VideoPlayer.java:273)
	at org.schabi.newpipe.player.VideoPlayerImpl.handleIntent(VideoPlayerImpl.java:235)
	at org.schabi.newpipe.player.MainPlayer.onStartCommand(MainPlayer.java:127)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3802)
	... 8 more

```
</details>
<hr>

**Comment by litetex** [comment]
Works as expected on ``0.22.0``
