### ISSUE TITLE
Constant "could not parse" issue.

### ISSUE THREAD

**Issue by Flam3z** [TeamNewPipe/NewPipe#4864]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1.View any video on 720p60fps

### Actual behaviour

Video is unable to play and a "could not parse website" error appears constantly.

### Expected behavior

Video to play as normal.

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=GyAGvXUCAJg
* __Content Country:__ US
* __Content Language:__ en
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.20.2
* __OS:__ Linux samsung/beyond1qltesq/beyond1q:10/QP1A.190711.020/G973USQU4ETH7:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get name
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getName(YoutubeStreamExtractor.java:135)
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractImportantData(StreamInfo.java:105)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:71)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: Android 10
 - Device model: Galaxy S10

**Comment by lu4p** [comment]
YouTube is currently down: https://twitter.com/TeamYouTube/status/1326681978037444608?s=19

**Comment by Flam3z** [comment]
Thanks for the update @lu4p

**Comment by xxxserxxx** [comment]
I don't think the outage is still causing this. I can watch videos on the YouTube website, in Slide's pop-up viewer, and in the official app as well, while NewPipe displays the "unable to parse website" for every video. This has been going on for days. E.g., video ZvPrR0lMMb4 works everywhere *except* NewPipe.

 This is with 0.21.1 from F-Droid.

**Comment by opusforlife2** [comment]
@xxxserxxx Update.

**Comment by xxxserxxx** [comment]
F-Droid is stuck at 0.20.1(3 weeks old), and (obvs) you can't install a differently signed apk. After exporting the DB and uninstalling newpipe,  I was able to install the apk from the releases and import the DB. Videos started working after that.

Any idea when the entry will be updated in f-droid? It's a recommended way of installing in the readme.

**Comment by opusforlife2** [comment]
> Any idea when the entry will be updated in f-droid?

Nope.

> It's a recommended way of installing in the readme.

We actually updated the Readme and now the recommended method is to use our custom F-Droid repo.

**Comment by xxxserxxx** [comment]
Ah, cool. Thanks.
