### ISSUE TITLE
Crash on scroll to top in local lists after rotation

### ISSUE THREAD

**Issue by vkay94** [TeamNewPipe/NewPipe#5035]
### Checklist

- [x] I am using the latest version - 0.20.4 and 0.20.5 (dev) (because of the `ErrorActivity` bug in latest version) 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

0. Add many items to your history or create a local playlist with many item and enable auto-rotation.
1. Within history or playlist details start a video in main player and wait until it plays.
2. Minimize the player and scroll down until the header isn't visible anymore.
3. Rotate your device.
4. Scroll to the top.

### Actual behaviour

After the rotation the header item is stuck to the top below one video item. After scrolling up to the top the app crashes with the below exception.

### Expected behavior

The header item shouldn't be stuck to the top after rotation.

### Logs

<details>
  <summary>Exception</summary>
  
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ DE
* __Content Language:__ de-DE
* __App Language:__ de_DE
* __Service:__ none
* __Version:__ 0.20.5
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7080)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

```
</details>
<hr>
  
</details>

### Device info

 - Android version/Custom ROM version: LineageOS 17.1 / Android 10
 - Device model: S4

**Comment by Stypox** [comment]
#4475
