### ISSUE TITLE
Importing database with a random zip file crashes NewPipe

### ISSUE THREAD

**Issue by c-shubh** [TeamNewPipe/NewPipe#5055]
### Checklist

- [x] I am using the latest version - 0.20.5 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Re-install NewPipe or Clear Data from android settings
2. Go to Settings -> Content -> Import database
3. Select any random zip file (Not NewPipe exported database)
4. Agree when asked to override your current setup.

### Actual behaviour

NewPipe crashes.

### Expected behavior

Not crash and preferably show a toast saying "Invalid NewPipe Database"

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.20.5
* __OS:__ Linux Android 6.0.1 - 23
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'char java.lang.String.charAt(int)' on a null object reference
	at j$.util.DesugarGregorianCalendar.from(:1)
	at org.schabi.newpipe.util.Localization.relativeTime(Localization.java:317)
	at org.schabi.newpipe.info_list.holder.StreamInfoItemHolder.getFormattedRelativeUploadDate(StreamInfoItemHolder.java:98)
	at org.schabi.newpipe.info_list.holder.StreamInfoItemHolder.getStreamInfoDetailLine(StreamInfoItemHolder.java:83)
	at org.schabi.newpipe.info_list.holder.StreamInfoItemHolder.updateFromItem(StreamInfoItemHolder.java:65)
	at org.schabi.newpipe.info_list.InfoListAdapter.onBindViewHolder(InfoListAdapter.java:337)
	at org.schabi.newpipe.info_list.InfoListAdapter.onBindViewHolder(InfoListAdapter.java:360)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
	at android.view.View.layout(View.java:18010)
	at android.view.ViewGroup.layout(ViewGroup.java:5817)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
	at android.view.View.layout(View.java:18010)
	at android.view.ViewGroup.layout(ViewGroup.java:5817)
	at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
	at android.view.View.layout(View.java:18010)
	at android.view.ViewGroup.layout(ViewGroup.java:5817)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
	at android.view.View.layout(View.java:18010)
	at android.view.ViewGroup.layout(ViewGroup.java:5817)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
	at android.view.View.layout(View.java:18010)
	at android.view.ViewGroup.layout(ViewGroup.java:5817)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
	at android.view.View.layout(View.java:18010)
	at android.view.ViewGroup.layout(ViewGroup.java:5817)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
	at android.view.View.layout(View.java:18010)
	at android.view.ViewGroup.layout(ViewGroup.java:5817)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
	at android.view.View.layout(View.java:18010)
	at android.view.ViewGroup.layout(ViewGroup.java:5817)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:18010)
	at android.view.ViewGroup.layout(ViewGroup.java:5817)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
	at android.view.View.layout(View.java:18010)
	at android.view.ViewGroup.layout(ViewGroup.java:5817)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
	at android.view.View.layout(View.java:18010)
	at android.view.ViewGroup.layout(ViewGroup.java:5817)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:3175)
	at android.view.View.layout(View.java:18010)
	at android.view.ViewGroup.layout(ViewGroup.java:5817)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2776)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2477)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1544)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7607)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
	at android.view.Choreographer.doFrame(Choreographer.java:622)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:7402)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: Android 6.0.1
 - Device model: Samsung SM-G550FY

### Additional Context

This happened when accidentally selecting a random zip file instead of NewPipe database zip.

I further tried selecting other file types, but NewPipe handled it with a toast "No valid ZIP file".

**Comment by Stypox** [comment]
This was fixed some time ago, and now NewPipe does not crash anymore when importing a random zip file, but instead says "Could not import all files".
