### ISSUE TITLE
Guru Meditation when opening any video

### ISSUE THREAD

**Issue by letorbi** [TeamNewPipe/NewPipe#5101]
The following exception happens for quite some time now. I don't know when exactly anymore, but I am talking about weeks, not days.

It happens with any YouTube video I try to open. I did not test any other services. I've already cleared the storage and also reinstalled the app, but no change. I am using version 20.1 from F-Droid on Lineage OS.

I've searched for other open "Guru Meditation" issues and was quite surprised that I could not find one, so I am creating a new one here. Would be great if you could investigate it :)

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=nCgQDjiotG0
* __Content Country:__ DE
* __Content Language:__ en-DE
* __App Language:__ en_DE
* __Service:__ YouTube
* __Version:__ 0.20.1
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: YouTube did not provide player config even after three attempts
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:664)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:56)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:68)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```

**Comment by c-shubh** [comment]
install the latest release from https://github.com/TeamNewPipe/NewPipe/releases/

**Comment by xibr** [comment]
See for more info https://github.com/TeamNewPipe/NewPipe#updates

**Comment by letorbi** [comment]
Thank for the hint! I wasn't aware that there is a new release already. I always thought, that the F-Droid package is up to date.

Isn't F-Droid a reliable (up to date) source for NewPipe releases anymore?

**Comment by xibr** [comment]
F-Droid has a bug in it's signature process therefore is not available to deliver the update.

**Comment by letorbi** [comment]
OK, thx for the info.

**Comment by n1trux** [comment]
Would be nice if you could add this info to the error message itself so people like me don't send unneccessary bug report information via mail.
