### ISSUE TITLE
Request feed

### ISSUE THREAD

**Issue by anonimQwerty** [TeamNewPipe/NewPipe#5136]
## Exception
* __User Action:__ requested feed
* __Request:__ Loading feed
* __Content Country:__ UA
* __Content Language:__ uk
* __App Language:__ uk_UA
* __Service:__ none
* __Version:__ 0.20.5
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.local.feed.service.FeedLoadService$RequestException: 3:https://videos.testimonia.org/api/v1/video-channels/black_triangle
	at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:224)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:66)
	at io.reactivex.rxjava3.internal.operators.parallel.ParallelMap$ParallelMapSubscriber.onNext(ParallelMap.java:114)
	at io.reactivex.rxjava3.internal.operators.parallel.ParallelFilter$ParallelFilterSubscriber.tryOnNext(ParallelFilter.java:130)
	at io.reactivex.rxjava3.internal.operators.parallel.ParallelRunOn$RunOnConditionalSubscriber.run(ParallelRunOn.java:397)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.RuntimeException: org.schabi.newpipe.extractor.exceptions.ParsingException: Unable to get displayName
	at io.reactivex.rxjava3.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
	at io.reactivex.rxjava3.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:94)
	at io.reactivex.rxjava3.core.Single.blockingGet(Single.java:3645)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:218)
	... 11 more
Caused by: org.schabi.newpipe.extractor.exceptions.ParsingException: Unable to get displayName
	at org.schabi.newpipe.extractor.utils.JsonUtils.getValue(JsonUtils.java:28)
	at org.schabi.newpipe.extractor.utils.JsonUtils.getString(JsonUtils.java:34)
	at org.schabi.newpipe.extractor.services.peertube.extractors.PeertubeChannelExtractor.getName(PeertubeChannelExtractor.java:153)
	at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:63)
	at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:48)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getChannelInfo$4(ExtractorHelper.java:125)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$BOLWstv98dC8pFAG_uir5gPXYwY.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.core.Single.blockingGet(Single.java:3644)
	... 12 more

```
</details>
<hr>
 Xiaomi redmi 6

**Comment by mhmdanas** [comment]
Please don't remove the template when you open an issue. Open a new issue with the template properly filled and followed. Thanks!
