### ISSUE TITLE
Issue while copying text in description of a video

### ISSUE THREAD

**Issue by shivasagarrao** [TeamNewPipe/NewPipe#5155]
### Checklist

- [x] I am using the latest version - 0.20.6 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open any youtube video
2. Click on video title it opens description box.
3. Select any text for copying. Don't click on copy or select all. After selection of text just click anywhere inside description box(red box in screenshot attached) app crashes. If I click on copy or select all no crash is happening.

### Actual behaviour

NewPipe crashes abruptly.

### Expected behavior

App shouldn't crash.

### Screenshots/Screen recordings

![newpipe](https://user-images.githubusercontent.com/46630255/101954193-ac770280-3c21-11eb-82be-15976ed0b73c.png)

### Device info

 - Android version/Custom ROM version: 6.0.1
 - Device model: Redmi Note 3

**Comment by MD77MD** [comment]
tried it and it doesn't crash... it just deselect... 

newpipe v.0.20.5

**Comment by shivasagarrao** [comment]
> Can you share the crash report?

No crash report is being generated by NewPipe. Is there any way to generate crash report? If I cllick anywhere inside description box after selection of text app closes automatically so from where should I copy crash report?

**Comment by TiA4f8R** [comment]
@shivasagarrao You should use Android's logcat (with ADB or an app which has permission to read logs (you'll need to grant it with ADB too))

**Comment by shivasagarrao** [comment]
@TiA4f8R I'm not that tech savvy. Any other easy way?

**Comment by TiA4f8R** [comment]
@shivasagarrao Unfortunately, I don't think there is an other mean but here's a guide to get a logcat:

1. Enable developer options if it isn't the case in your device's settings.
2. Enable USB debugging.
3. Connect your Phone to a computer with an USB cable.
4. Allow file transfer via USB.
5. You may need to search for ADB drivers depending on the OS present on your PC (restart your computer if you install drivers).
6. Download the latest version of Android SDK Plateform tools here on your computer: [https://developer.android.com/studio/releases/platform-tools#downloads
](https://developer.android.com/studio/releases/platform-tools#downloads).
7. Decompress the ZIP obtained and open a terminal window in the folder of decompressed Plateform Tools (or use command cd + the path to Plateform Tools' folder in a terminal window)
8. Type adb devices and unlock your device if it isn't the case.
9. Allow your computer by clicking Allow (tick the box if you don't want to do at each time).
10. Run command `adb logcat > logcat.txt`.
11. Reproduce the crash on your phone. Wait a few seconds.
12. Close the terminal window.
13. Check logcat.txt file in Plateform Tools' folder. Open it and search for NewPipe's entries (org.schabi.newpipe) and **only** post its entires (because a logcat can contain sensitive data). You should have `FATAL EXCEPTION: main` in the stack trace.
14. Launch a new terminal window and tap `adb kill-server` to be able to disconnect your phone properly from your computer.

Hope that it helps you.

PS: Check other issues, like my first issue (#5222) to see an example of what you need to get.
Note: I'm not an Android/Java developer nor a developer.

**Comment by shivasagarrao** [comment]
Thanks for such a detailed guide. I will soon try to upload logcat of this issue.

**Comment by TiA4f8R** [comment]
@shivasagarrao You're welcome

**Comment by TiA4f8R** [comment]
@shivasagarrao Does this bug is still reproducible in 0.21.0 version?

**Comment by shivasagarrao** [comment]
@TiA4f8R I'm currently using 0.21.0 version. Am unable to view the description of any video. I think it is a **bug**.

**Comment by TiA4f8R** [comment]
Did you disable the `Show description` option in the content settings? If no, click on the last tab at the bottom right to see the description.

**Comment by shivasagarrao** [comment]
> If no, click on the last tab at the bottom right to see the description.

Now am able to see description of the video. 


> @shivasagarrao Does this bug is still reproducible in 0.21.0 version?
 
Yes.

**Comment by TiA4f8R** [comment]
@shivasagarrao So are you able to generate a crash report by following my steps above? We can't know what is the bug without a stack trace.

**Comment by shivasagarrao** [comment]
I didn't generate crash report yet. I will soon generate it with the steps you have mentioned above.

**Comment by shivasagarrao** [comment]
@TiA4f8R 
When I checked in `logcat.txt` file, I didn't got `FATAL EXCEPTION: main` for Newpipe app but I got `FATAL EXCEPTION: main` for another app in my phone.

I got `IndexOutOfBoundsException` for Newpipe app. Following text has been copied from logcat file after executing adb logcat command

```
04-06 20:51:28.700 22726 22726 E ACRA    : ACRA caught a IndexOutOfBoundsException for org.schabi.newpipe
04-06 20:51:28.700 22726 22726 E ACRA    : java.lang.IndexOutOfBoundsException: setSpan (-1 ... -1) starts before 0
04-06 20:51:28.700 22726 22726 E ACRA    : 	at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:358)
04-06 20:51:28.700 22726 22726 E ACRA    : 	at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:79)
04-06 20:51:28.700 22726 22726 E ACRA    : 	at android.text.SpannableString.setSpan(SpannableString.java:46)
04-06 20:51:28.700 22726 22726 E ACRA    : 	at android.text.Selection.setSelection(Selection.java:78)
04-06 20:51:28.700 22726 22726 E ACRA    : 	at android.widget.Editor$SelectionStartHandleView.updateSelection(Editor.java:4968)
04-06 20:51:28.700 22726 22726 E ACRA    : 	at android.widget.Editor$HandleView.positionAtCursorOffset(Editor.java:4491)
04-06 20:51:28.700 22726 22726 E ACRA    : 	at android.widget.Editor$HandleView.updatePosition(Editor.java:4514)
04-06 20:51:28.700 22726 22726 E ACRA    : 	at android.widget.Editor$PositionListener.onPreDraw(Editor.java:2477)
04-06 20:51:28.700 22726 22726 E ACRA    : 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
04-06 20:51:28.700 22726 22726 E ACRA    : 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2092)
04-06 20:51:28.700 22726 22726 E ACRA    : 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1144)
04-06 20:51:28.700 22726 22726 E ACRA    : 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6102)
04-06 20:51:28.700 22726 22726 E ACRA    : 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
04-06 20:51:28.700 22726 22726 E ACRA    : 	at android.view.Choreographer.doCallbacks(Choreographer.java:672)
04-06 20:51:28.700 22726 22726 E ACRA    : 	at android.view.Choreographer.doFrame(Choreographer.java:608)
04-06 20:51:28.700 22726 22726 E ACRA    : 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
04-06 20:51:28.700 22726 22726 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:742)
04-06 20:51:28.700 22726 22726 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-06 20:51:28.700 22726 22726 E ACRA    : 	at android.os.Looper.loop(Looper.java:157)
04-06 20:51:28.700 22726 22726 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:5603)
04-06 20:51:28.700 22726 22726 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
04-06 20:51:28.700 22726 22726 E ACRA    : 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
04-06 20:51:28.700 22726 22726 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
```

**Comment by TiA4f8R** [comment]
@shivasagarrao Thank you.
Do you have any results when you search for org.schabi.newpipe?

**Comment by shivasagarrao** [comment]
When I searched `org.schabi.newpipe` am getting lot of text. From which line which line should I copy?
From above logcat do you understand why app is crashing when I try to copy text?

**Comment by TiA4f8R** [comment]
Can you copy the entries around the ACRA exceptions (with `at org.schabi.newpipe`, **not** `org.schabi.newpipe`)?

**Comment by shivasagarrao** [comment]
Around ACRA exceptions I got entries as shown in the above [comment](https://github.com/TeamNewPipe/NewPipe/issues/5155#issuecomment-814240576).

I also got following entry after many lines below ACRA exception

`04-06 20:51:42.979 12269 12381 D PowerKeeper.Event: notifyAMProcDied pacakageName: org.schabi.newpipe, pid:24917`

**Comment by TiA4f8R** [comment]
@tiwarys Does PR #7061 fixes your issue? If not, it may be an issue with your ROM. In this case, I don't know if we can do something to this in the app.
