### ISSUE TITLE
New Pipe 0.20.6  crash android system 10

### ISSUE THREAD

**Issue by scsi1054** [TeamNewPipe/NewPipe#5162]
### Checklist

- [x] I am using the latest version - 0.20.6 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. start the background player with a bookmarked playlist. i used bt headphones
2. after few minute the android crashed
3. android 10 start in recovery mode

### Device info

 - Android version/Custom ROM version: Android 10 QKQ1.190910.002 V11.0.17.0.QDIMIXM
 - Device model: Xio Mi A2

**Comment by mhmdanas** [comment]
Does this only happen with NewPipe? I find it a bit hard to believe that NewPipe would cause something that would break Android.

**Comment by scsi1054** [comment]
yes it only happens with NewPipe. i was very confused when music stopped.
I got this issuie with New Pipe 0.20.6. Older versions didnt crashed my android.

**Comment by mhmdanas** [comment]
Could you try varying things a bit (e.g. using different headphones or no headphones, different playlist or even no playlist)?

**Comment by scsi1054** [comment]
this happend with 2 diffrent playlist.
i try if i can replicate the bug without using blue tooth headphones.  -> maybe there is some trouble with "corona contact tracing app germany"

**Comment by dkraft** [comment]
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.9.4
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.ArrayIndexOutOfBoundsException: length=4; index=4
	at androidx.preference.ListPreference.getEntry(ListPreference.java:213)
	at androidx.preference.ListPreference.getSummary(ListPreference.java:164)
	at androidx.preference.Preference.onBindViewHolder(Preference.java:510)
	at androidx.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:418)
	at androidx.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:47)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>
<hr>

**Comment by xibr** [comment]
@dkraft Where did you get version 0.9.4? 

Anyway, update to latest version (0.20.6).
https://github.com/TeamNewPipe/NewPipe#updates

**Comment by nonremittal** [comment]
Try disabling "Show thumbnail" in Settings -> Notification.

**Comment by scsi1054** [comment]
I have some news.
after my last bug report I deinstall "corona contact tracing app germany", to check if there is a problem.

today i got 2x times the bug again, without using bt headphones and not using bookmarked playlist.
I played  a song with the background player and switched to twitter app.
then after a while, the mobile phone the display turns black and is in logging screen. Afterwards, i tried to unlock my phone with my pin code. Now there start a loop. 
the display toggle to black then to log screen.
After 5-6 loops the phone restarts and starts in recovery mode.

**Comment by scsi1054** [comment]
here i filmed the bug
https://youtu.be/eZ6Irb-zwLU

**Comment by mhmdanas** [comment]
@scsi1054 could you see if [this suggestion](https://github.com/TeamNewPipe/NewPipe/issues/5211#issuecomment-747879952) fixes it?

**Comment by scsi1054** [comment]
thanks. i will check, if it fix the problem

**Comment by ntoshev** [comment]
@mhmdanas I had the same problem and this suggestion fixed it.

**Comment by ojdo** [comment]
Same here (0.20.6, Android 10 on Sony Xperia XZ2 Compact): linked suggestion fixes the issue as well.

**Comment by scsi1054** [comment]
the suggestion fixed the bug. i didnt get it anymore 😊

**Comment by Stypox** [comment]
#4638
