### ISSUE TITLE
Database export to removable storage fails on Android 10

### ISSUE THREAD

**Issue by johanw666** [TeamNewPipe/NewPipe#5198]
### Checklist

- [x] I am using the latest version - 0.20.6 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to the settings, content, export database
2. Select a folder in the removable storage
3. Press OK
4. Crash

### Actual behaviour
A screen with an exception shows.

### Expected behavior
A database is exported. This worked OK on my Android 4, 6  and 7 devices, but on Android 10 it crashes (no permission).

## Exception
* __User Action:__ ui error
* __Request:__ 
* __Content Country:__ US
* __Content Language:__ en
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.20.6
* __OS:__ Linux samsung/a50eea/a50:10/QP1A.190711.020/A505FNXXU4BTC9:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.io.FileNotFoundException: /storage/A34D-12E4/tmp/internalsd/NewPipeData-20201216_222951.zip: open failed: EACCES (Permission denied)
	at libcore.io.IoBridge.open(IoBridge.java:496)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:125)
	at org.schabi.newpipe.settings.ContentSettingsFragment.exportDatabase(ContentSettingsFragment.java:215)
	at org.schabi.newpipe.settings.ContentSettingsFragment.onActivityResult(ContentSettingsFragment.java:197)
	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:170)
	at android.app.Activity.dispatchActivityResult(Activity.java:8292)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5090)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5138)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7814)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7691)
	at libcore.io.IoBridge.open(IoBridge.java:482)
	... 18 more

```
</details>
<hr>

### Device info

 - Android version: 10 (Stock ROM, rooted)
 - Device model: Samsung A50

**Comment by mhmdanas** [comment]
This works just fine for me. From the error, it appears like you have not given NewPipe storage permission. Could you check that you actually gave it the permission?

**Comment by johanw666** [comment]
I just checked, I did give it storage permission.

**Comment by mhmdanas** [comment]
Ah, wait, I missed the fact that you were using removable storage, which is probably the cause. For now, can you check if you can export the database to your phone's internal storage and move it to the external storage?

**Comment by johanw666** [comment]
Yes, exporting to internal SD works fine.

**Comment by ShareASmile** [comment]
SAF permission is needed to write to external storage. SAF can be enabled in NewPipe by going to Settings, Download then Toggle Use SAF ON & select external storage or any folder inside.

However things will be easier when work being done on it is completed. See https://github.com/TeamNewPipe/NewPipe/pull/3777

**Comment by johanw666** [comment]
Unfortunately switching on SAF gives the same error.

**Comment by Stypox** [comment]
Could you check if [this apk](https://github.com/TeamNewPipe/NewPipe/suites/1834544416/artifacts/35447435) from #5415 solves the issue?

**Comment by johanw666** [comment]
Yes, this apk can export the database and settings to emovable storage. Thanks.

**Comment by johanw666** [comment]
This still does not work in 0.20.9, when will this PR, https://github.com/TeamNewPipe/NewPipe/pull/5415 , merged?

**Comment by Thewisem** [comment]
Same for android 7
