### ISSUE TITLE
Crash report UI isn't showing for UI crashes in debug builds the first time you open it or after a force-stop

### ISSUE THREAD

**Issue by TiA4f8R** [TeamNewPipe/NewPipe#5222]
### Checklist

- [x] I am using the latest version - debug build based on recent dev branch
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Install or force-stop a debug build.
2. Do something that make NewPipe crash with an UI error (use the crash button provided in #5672).
3. Observe app's comportment.

### Actual behaviour

The first time NewPipe crash, no Crash UI is shown. App just crash.

### Expected behavior

Crash UI is shown everytime NewPipe crash.

### Screenshots/Screen recordings (when bug #3925 was present and happened on my device, same behavoir on a recent build based on dev branch)

https://user-images.githubusercontent.com/74829229/102692293-b8128c80-4212-11eb-8ef4-8c37e83e5e34.mp4

### Logs (same behavoir on a recent build based on dev branch, from Android's logcat)

First that the app crashed:

```
--------- beginning of crash
03-20 19:44:52.037 15219 15219 E AndroidRuntime: FATAL EXCEPTION: main
03-20 19:44:52.037 15219 15219 E AndroidRuntime: Process: org.schabi.newpipe.debug.shareimprovements, PID: 15219
03-20 19:44:52.037 15219 15219 E AndroidRuntime: java.lang.RuntimeException
03-20 19:44:52.037 15219 15219 E AndroidRuntime: 	at org.schabi.newpipe.settings.DebugSettingsFragment.lambda$onCreate$1(DebugSettingsFragment.java:31)
03-20 19:44:52.037 15219 15219 E AndroidRuntime: 	at org.schabi.newpipe.settings.-$$Lambda$DebugSettingsFragment$fkJ92_RI_mUwtmo-9cigCdvXZa4.onPreferenceClick(Unknown Source:0)
03-20 19:44:52.037 15219 15219 E AndroidRuntime: 	at androidx.preference.Preference.performClick(Preference.java:1184)
03-20 19:44:52.037 15219 15219 E AndroidRuntime: 	at androidx.preference.Preference.performClick(Preference.java:1166)
03-20 19:44:52.037 15219 15219 E AndroidRuntime: 	at androidx.preference.Preference$1.onClick(Preference.java:181)
03-20 19:44:52.037 15219 15219 E AndroidRuntime: 	at android.view.View.performClick(View.java:7192)
03-20 19:44:52.037 15219 15219 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7166)
03-20 19:44:52.037 15219 15219 E AndroidRuntime: 	at android.view.View.access$3500(View.java:824)
03-20 19:44:52.037 15219 15219 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:27592)
03-20 19:44:52.037 15219 15219 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:888)
03-20 19:44:52.037 15219 15219 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
03-20 19:44:52.037 15219 15219 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:213)
03-20 19:44:52.037 15219 15219 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8178)
03-20 19:44:52.037 15219 15219 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-20 19:44:52.037 15219 15219 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
03-20 19:44:52.037 15219 15219 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
03-20 19:44:52.038 15219 15219 E ACRA    : ACRA caught a RuntimeException for org.schabi.newpipe.debug.shareimprovements
03-20 19:44:52.038 15219 15219 E ACRA    : java.lang.RuntimeException
03-20 19:44:52.038 15219 15219 E ACRA    : 	at org.schabi.newpipe.settings.DebugSettingsFragment.lambda$onCreate$1(DebugSettingsFragment.java:31)
03-20 19:44:52.038 15219 15219 E ACRA    : 	at org.schabi.newpipe.settings.-$$Lambda$DebugSettingsFragment$fkJ92_RI_mUwtmo-9cigCdvXZa4.onPreferenceClick(Unknown Source:0)
03-20 19:44:52.038 15219 15219 E ACRA    : 	at androidx.preference.Preference.performClick(Preference.java:1184)
03-20 19:44:52.038 15219 15219 E ACRA    : 	at androidx.preference.Preference.performClick(Preference.java:1166)
03-20 19:44:52.038 15219 15219 E ACRA    : 	at androidx.preference.Preference$1.onClick(Preference.java:181)
03-20 19:44:52.038 15219 15219 E ACRA    : 	at android.view.View.performClick(View.java:7192)
03-20 19:44:52.038 15219 15219 E ACRA    : 	at android.view.View.performClickInternal(View.java:7166)
03-20 19:44:52.038 15219 15219 E ACRA    : 	at android.view.View.access$3500(View.java:824)
03-20 19:44:52.038 15219 15219 E ACRA    : 	at android.view.View$PerformClick.run(View.java:27592)
03-20 19:44:52.038 15219 15219 E ACRA    : 	at android.os.Handler.handleCallback(Handler.java:888)
03-20 19:44:52.038 15219 15219 E ACRA    : 	at android.os.Handler.dispatchMessage(Handler.java:100)
03-20 19:44:52.038 15219 15219 E ACRA    : 	at android.os.Looper.loop(Looper.java:213)
03-20 19:44:52.038 15219 15219 E ACRA    : 	at android.app.ActivityThread.main(ActivityThread.java:8178)
03-20 19:44:52.038 15219 15219 E ACRA    : 	at java.lang.reflect.Method.invoke(Native Method)
03-20 19:44:52.038 15219 15219 E ACRA    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
03-20 19:44:52.038 15219 15219 E ACRA    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
03-20 19:44:52.039  1159 15325 I QarthDisFileCreator: pattern not match
03-20 19:44:52.052  1159  1424 D ZrHung.AppEyeTransparentWindow: handleMessage CHECK_TRANS_WINDOW_ERROR_MSG
03-20 19:44:52.070   445   445 E SELinux : avc:  denied  { find } for service=meminfo pid=15338 uid=10257 scontext=u:r:untrusted_app:s0:c1,c257,c512,c768 tcontext=u:object_r:meminfo_service:s0 tclass=service_manager permissive=0
03-20 19:44:52.081  1159  3525 V ActivityTaskManager: positionChild stackId=0 to top.
03-20 19:44:52.128  1159  8940 V ActivityManager: startProcess: name=org.schabi.newpipe.debug.shareimprovements:acra app=null knownToBeDead=true thread=null pid=-1
03-20 19:44:52.133 15219 15219 I Process : Sending signal. PID: 15219 SIG: 9
03-20 19:44:52.141   568   568 D Zygote  : Forked child process 15342
03-20 19:44:52.143  1159  1432 I ActivityManager: Start proc 15342:org.schabi.newpipe.debug.shareimprovements:acra/u0a257 for service {org.schabi.newpipe.debug.shareimprovements/org.acra.sender.JobSenderService}
03-20 19:44:52.143  1159  1933 E ProcessInfoCollector: getProcessInfo: failed to find this proc 
03-20 19:44:52.147 15342 15342 I provements:acr: Late-enabling -Xcheck:jni
03-20 19:44:52.171  1159  1639 W InputDispatcher: channel '53bfa40 org.schabi.newpipe.debug.shareimprovements/org.schabi.newpipe.settings.SettingsActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
03-20 19:44:52.171  1159  1639 E InputDispatcher: channel '53bfa40 org.schabi.newpipe.debug.shareimprovements/org.schabi.newpipe.settings.SettingsActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
03-20 19:44:52.171  1159  1639 I WindowManager: WINDOW DIED Window{53bfa40 u0 org.schabi.newpipe.debug.shareimprovements/org.schabi.newpipe.settings.SettingsActivity}
03-20 19:44:52.171  1159  1639 V WindowManager: removeIfPossible: Window{53bfa40 u0 org.schabi.newpipe.debug.shareimprovements/org.schabi.newpipe.settings.SettingsActivity} callers=com.android.server.wm.WindowState.removeIfPossible:2260 com.android.server.wm.InputManagerCallback.notifyInputChannelBroken:60 com.android.server.input.InputManagerService.notifyInputChannelBroken:1881 <bottom of call stack> <bottom of call stack> 
03-20 19:44:52.171  1159  1639 W InputDispatcher: Attempted to unregister already unregistered input channel '53bfa40 org.schabi.newpipe.debug.shareimprovements/org.schabi.newpipe.settings.SettingsActivity (server)'
03-20 19:44:52.172  1159  1639 V WindowManager: Not removing Window{53bfa40 u0 org.schabi.newpipe.debug.shareimprovements/org.schabi.newpipe.settings.SettingsActivity EXITING} due to exit animation 
03-20 19:44:52.177  1159  1639 W InputDispatcher: channel 'f3f9e8f org.schabi.newpipe.debug.shareimprovements/org.schabi.newpipe.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
03-20 19:44:52.177  1159  1639 E InputDispatcher: channel 'f3f9e8f org.schabi.newpipe.debug.shareimprovements/org.schabi.newpipe.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
03-20 19:44:52.177 15342 15342 E provements:acr: Unknown bits set in runtime_flags: 0x8000
03-20 19:44:52.179 15342 15342 I provements:acr: Reinit property: dalvik.vm.checkjni= false
03-20 19:44:52.180  1159  1639 I WindowManager: WINDOW DIED Window{f3f9e8f u0 org.schabi.newpipe.debug.shareimprovements/org.schabi.newpipe.MainActivity}
03-20 19:44:52.180  1159  1639 V WindowManager: removeIfPossible: Window{f3f9e8f u0 org.schabi.newpipe.debug.shareimprovements/org.schabi.newpipe.MainActivity} callers=com.android.server.wm.WindowState.removeIfPossible:2260 com.android.server.wm.InputManagerCallback.notifyInputChannelBroken:60 com.android.server.input.InputManagerService.notifyInputChannelBroken:1881 <bottom of call stack> <bottom of call stack> 
03-20 19:44:52.180  1159  1639 W InputDispatcher: Attempted to unregister already unregistered input channel 'f3f9e8f org.schabi.newpipe.debug.shareimprovements/org.schabi.newpipe.MainActivity (server)'
03-20 19:44:52.180  1159  1639 V WindowManager: postWindowRemoveCleanupLocked: Window{f3f9e8f u0 org.schabi.newpipe.debug.shareimprovements/org.schabi.newpipe.MainActivity}
03-20 19:44:52.181  1159  1639 V WindowManager: Removing Window{f3f9e8f u0 org.schabi.newpipe.debug.shareimprovements/org.schabi.newpipe.MainActivity} from AppWindowToken{8e902c3 token=Token{ed9be72 ActivityRecord{9a3db27 u0 org.schabi.newpipe.debug.shareimprovements/org.schabi.newpipe.MainActivity t16}}}
03-20 19:44:52.187   568   568 I Zygote  : Process 15219 exited due to signal 9 (Killed)
03-20 19:44:52.188  1159  2184 I ActivityManager: Process org.schabi.newpipe.debug.shareimprovements (pid 15219) has died: fore TOP 
03-20 19:44:52.188  1159  8783 I WindowManager: WIN DEATH: Window{53bfa40 u0 org.schabi.newpipe.debug.shareimprovements/org.schabi.newpipe.settings.SettingsActivity EXITING}
03-20 19:44:52.188  1159  2184 D ActivityManager: cleanUpApplicationRecord app: ProcessRecord{39a176c 15219:org.schabi.newpipe.debug.shareimprovements/u0a257}, app.bad: false, restarting: false, allowRestart: true
03-20 19:44:52.189  1159  8783 V WindowManager: removeIfPossible: Window{53bfa40 u0 org.schabi.newpipe.debug.shareimprovements/org.schabi.newpipe.settings.SettingsActivity EXITING} callers=com.android.server.wm.WindowState.access$300:262 com.android.server.wm.WindowState$DeathRecipient.binderDied:2927 android.os.BinderProxy.sendDeathNotice:636 <bottom of call stack> <bottom of call stack> 
03-20 19:44:52.189  1159  8783 V WindowManager: Not removing Window{53bfa40 u0 org.schabi.newpipe.debug.shareimprovements/org.schabi.newpipe.settings.SettingsActivity EXITING} due to exit animation 
03-20 19:44:52.189  1159  1433 I libprocessgroup: Successfully killed process cgroup uid 10257 pid 15219 in 0ms
03-20 19:44:52.191  1159 10493 E InputDispatcher: Window handle Window{53bfa40 u0 org.schabi.newpipe.debug.shareimprovements/org.schabi.newpipe.settings.SettingsActivity} has no registered input channel
03-20 19:44:52.198  1159  2184 V WindowManager: Exit animation finished in Window{53bfa40 u0 org.schabi.newpipe.debug.shareimprovements/org.schabi.newpipe.settings.SettingsActivity EXITING}: remove=true
03-20 19:44:52.198  1159  2184 E WindowManager: win=Window{53bfa40 u0 org.schabi.newpipe.debug.shareimprovements/org.schabi.newpipe.settings.SettingsActivity EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true
03-20 19:44:52.199  1159  2184 V WindowManager: postWindowRemoveCleanupLocked: Window{53bfa40 u0 org.schabi.newpipe.debug.shareimprovements/org.schabi.newpipe.settings.SettingsActivity}
03-20 19:44:52.199  1159  2184 V WindowManager: Removing Window{53bfa40 u0 org.schabi.newpipe.debug.shareimprovements/org.schabi.newpipe.settings.SettingsActivity} from AppWindowToken{9d174e6 token=Token{9fe741 ActivityRecord{cf8e28 u0 org.schabi.newpipe.debug.shareimprovements/org.schabi.newpipe.settings.SettingsActivity t16}}}
03-20 19:44:52.202 15342 15342 E libc    : Access denied finding property "runtime.mmitest.isrunning"
03-20 19:44:52.195 15342 15342 W re-initialized>: type=1400 audit(0.0:13714): avc: denied { read } for pid=15342 name="u:object_r:mmi_prop:s0" dev="tmpfs" ino=15348 scontext=u:r:untrusted_app:s0:c1,c257,c512,c768 tcontext=u:object_r:mmi_prop:s0 tclass=file permissive=0
03-20 19:44:52.202  1159  2184 V WindowManager: removeAppToken: AppWindowToken{9d174e6 token=Token{9fe741 ActivityRecord{cf8e28 u0 org.schabi.newpipe.debug.shareimprovements/org.schabi.newpipe.settings.SettingsActivity t16}}} delayed=true Callers=com.android.server.wm.DisplayContent.removeAppToken:1204 com.android.server.wm.ActivityRecord.removeWindowContainer:1298 com.android.server.wm.ActivityStack.removeActivityFromHistoryLocked:4927 com.android.server.wm.ActivityStack.removeHistoryRecordsForAppLocked:5346 
03-20 19:44:52.203  1159  2184 V WindowManager: removeAppToken: AppWindowToken{8e902c3 token=Token{ed9be72 ActivityRecord{9a3db27 u0 org.schabi.newpipe.debug.shareimprovements/org.schabi.newpipe.MainActivity t16}}} delayed=true Callers=com.android.server.wm.DisplayContent.removeAppToken:1204 com.android.server.wm.ActivityRecord.removeWindowContainer:1298 com.android.server.wm.ActivityStack.removeActivityFromHistoryLocked:4927 com.android.server.wm.ActivityStack.removeHistoryRecordsForAppLocked:5346 
```

Second time that the app crashed:

```
Wil post log later
```

### Device info

 - Android version/Custom ROM version: Android 10 / EMUI 10.0.0
 - Device model: Honor 9X

**Comment by TiA4f8R** [comment]
Also, when a debug APK is compiled, this warning in :app:processDebugMainManifest task is always shown:

```
path_to_newpipe's_project/app/src/debug/AndroidManifest.xml:39:9-45:51 Warning:
	provider#org.acra.attachment.AcraContentProvider@android:authorities was tagged at AndroidManifest.xml:39 to replace other declarations but no other declaration present

```

So fix this may fix this issue?

**Comment by TiA4f8R** [comment]
Cannot reproduce with a debug build based on 0.21.0 version. Closing.

**Comment by TacoTheDank** [comment]
Considering ACRA was updated, does this issue still occur on the latest version?

**Comment by TiA4f8R** [comment]
Yes, it still occurs (on the last commit of the `dev` branch).
