### ISSUE TITLE
Crash on vanced app this is the crash report.ort

### ISSUE THREAD

**Issue by bigred1710** [TeamNewPipe/NewPipe#5265]
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.9.4
* __OS:__ Linux motorola/ginna_t/ginna:10/QPG30.82-105/80737:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.ArrayIndexOutOfBoundsException: length=4; index=4
	at androidx.preference.ListPreference.getEntry(ListPreference.java:213)
	at androidx.preference.ListPreference.getSummary(ListPreference.java:164)
	at androidx.preference.Preference.onBindViewHolder(Preference.java:510)
	at androidx.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:418)
	at androidx.preference.PreferenceGroupAdapter.onBindViewHolder(PreferenceGroupAdapter.java:47)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:7604)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)

```
</details>
<hr>

**Comment by shivasagarrao** [comment]
> Version: 0.9.4

You are using old version. Update to latest version by downloading latest apk from [Github releases](https://github.com/TeamNewPipe/NewPipe/releases). Your bug might be resolved.

**Comment by mhmdanas** [comment]
@bigred1710 you are likely using a copy of NewPipe from the Play Store; you should not do that. NEVER use NewPipe clones from the Play Store. See https://newpipe.net/#download for how to install the legitimate version of NewPipe.

**Comment by shivasagarrao** [comment]
@mhmdanas How did you find that he is using a copy of NewPipe?

**Comment by mhmdanas** [comment]
@shivasagarrao see #4832.
