### ISSUE TITLE
Error with audio lounge

### ISSUE THREAD

**Issue by B0pol** [TeamNewPipe/NewPipe#5293]
### Checklist

- [x] I am using the latest version - 0.20.8 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Open https://streaming.media.ccc.de/rc3/ambientlounge in newpipe

### Actual behaviour

-> infinite loading
-> snackbar showing up
-> when you click on report, the crash reporter crashes:
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ FR
* __Content Language:__ fr-FR
* __App Language:__ fr_FR
* __Service:__ none
* __Version:__ 0.20.8
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.Throwable.printStackTrace(java.io.PrintWriter)' on a null object reference
	at org.schabi.newpipe.report.ErrorActivity.getStackTrace(ErrorActivity.java:164)
	at org.schabi.newpipe.report.ErrorActivity.elToSl(ErrorActivity.java:172)
	at org.schabi.newpipe.report.ErrorActivity.startErrorActivity(ErrorActivity.java:114)
	at org.schabi.newpipe.report.ErrorActivity.lambda$reportError$0(ErrorActivity.java:102)
	at org.schabi.newpipe.report.-$$Lambda$ErrorActivity$HI3F3TjOpAv-degtFRP9Y1N7-5o.onClick(Unknown Source:8)
	at com.google.android.material.snackbar.Snackbar$1.onClick(Snackbar.java:307)
	at android.view.View.performClick(View.java:6597)
	at android.view.View.performClickInternal(View.java:6574)
	at android.view.View.access$3100(View.java:778)
	at android.view.View$PerformClick.run(View.java:25906)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```
</details>
<hr>

### Expected behavior

It plays fine.

btw, it's a audio only livestream, it should be detected as such by NewPipeExtractor. It's not the case because there is not the same layout as soundcloud one with audio only.

### Device info

 - Android version/Custom ROM version: 9
 - Device model: pocophone F1

**Comment by Stypox** [comment]
Could you check if [this apk](https://github.com/TeamNewPipe/NewPipe/suites/1836810430/artifacts/35510945) from the ci in #5148 solves the error-reporter-crashing issue?
