### ISSUE TITLE
NullPointerException at search on media.ccc.de

### ISSUE THREAD

**Issue by MathJoDE** [TeamNewPipe/NewPipe#5306]
### Checklist

- [x] I am using the latest version - 0.20.8
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. open NewPipe
2. go to media.ccc.de (via the sidebar)
3. search for "eGovernment" (without the quotation marks)

### Actual behaviour

No results are found an the error notification bar pops up at the bottom (see screenshot below) 

### Expected behavior

Maybe some search results, or just no results

### Screenshots/Screen recordings

![Screenshot_20201229-114846](https://user-images.githubusercontent.com/59893632/103279193-90b77e80-49cd-11eb-9cfc-a7831c1bfc42.png)

## Exception
* __User Action:__ searched
* __Request:__ eGovernment
* __Content Country:__ DE
* __Content Language:__ de-DE
* __App Language:__ en
* __Service:__ media.ccc.de
* __Version:__ 0.20.8
* __OS:__ Linux Android 7.0 - 24
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: text
	at java.util.Objects.requireNonNull(Objects.java:228)
	at j$.time.format.DateTimeFormatter.e(:1)
	at j$.time.OffsetDateTime.parse(:2)
	at j$.time.OffsetDateTime.parse()
	at org.schabi.newpipe.extractor.services.media_ccc.extractors.MediaCCCParsingHelper.parseDateFrom(MediaCCCParsingHelper.java:25)
	at org.schabi.newpipe.extractor.services.media_ccc.extractors.infoItems.MediaCCCStreamInfoItemExtractor.getUploadDate(MediaCCCStreamInfoItemExtractor.java:59)
	at org.schabi.newpipe.extractor.stream.StreamInfoItemsCollector.extract(StreamInfoItemsCollector.java:69)
	at org.schabi.newpipe.extractor.search.InfoItemsSearchCollector.extract(InfoItemsSearchCollector.java:84)
	at org.schabi.newpipe.extractor.search.InfoItemsSearchCollector.extract(InfoItemsSearchCollector.java:50)
	at org.schabi.newpipe.extractor.InfoItemsCollector.commit(InfoItemsCollector.java:87)
	at org.schabi.newpipe.extractor.services.media_ccc.extractors.MediaCCCSearchExtractor.getInitialPage(MediaCCCSearchExtractor.java:84)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:60)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:30)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$searchFor$0(ExtractorHelper.java:92)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$qyxpuXgomWa-cbONQns-pd7zxm0.call(lambda)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:776)

```
</details>
<hr>

### Device Model
Huawei P9 lite (HWVNS-L31)

[edit: device model information added]

**Comment by TobiGr** [comment]
hm. you can get the same error when searching for "bahn".

The problem: media.ccc.de lists videos even if they have not been published yet, e.g. https://media.ccc.de/v/rc3-929578-the_reclaimyourface_campaign
These videos appear in the search results, but have `upload_date: null`. that causes the NPE. The normal `date` field points to some future timestamp where the talk is expected to be hold. 
When fixing the NPE, there is another problem: The search entry points to some future event, having no streams => "Could not get any streams" error is thrown.

For this reason, I suggest to remove future videos from the search results.
