### ISSUE TITLE
Post-processing failed

### ISSUE THREAD

**Issue by hrdisaac** [TeamNewPipe/NewPipe#5315]
## Exception
* __User Action:__ download post-processing
* __Request:__ https://www.youtube.com/watch?v=8YH_AVwjyD4 [ {type=audio format=m4a bitrate=128} ]
* __Content Country:__ GB
* __Content Language:__ en
* __App Language:__ en_GB
* __Service:__ YouTube
* __Version:__ 0.20.8
* __OS:__ Linux samsung/greatltexx/greatlte:9/PPR1.180610.011/N950FXXUDDTH1:user/release-keys 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
java.io.IOException: The chunk is empty or invalid
	at us.shandian.giga.io.ChunkFileInputStream.<init>(ChunkFileInputStream.java:28)
	at us.shandian.giga.postprocessing.Postprocessing.run(Postprocessing.java:131)
	at us.shandian.giga.get.DownloadMission.doPostprocessing(DownloadMission.java:702)
	at us.shandian.giga.get.DownloadMission.lambda$J0GR1urTFneOp2O30GpOM3TNG0I(Unknown Source:0)
	at us.shandian.giga.get.-$$Lambda$DownloadMission$J0GR1urTFneOp2O30GpOM3TNG0I.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:764)

```
</details>
<hr>

**Comment by TobiGr** [comment]
i could not reproduce this issue on Android 9. I guess NewPipe was interrupted and needed to restart downloading a part of the audio (tried to force that by interrupting my internet connection),
Did you try to download the audio again?

**Comment by mhmdanas** [comment]
@hrdisaac thanks for opening an issue! Please open a new issue that follows the template properly.
