### ISSUE TITLE
"Sorry, something went wrong" after blind drawing tablet compatability test

### ISSUE THREAD

**Issue by esotericDisciple** [TeamNewPipe/NewPipe#5345]
I wanted to see if my phone automatically recognized a Parblo a610plus tablet, but it thinks it's a keyboard (similar issue on Linux as well), so I disconnected it. After that newpipe started complaining, so I'm assuming that's related to my experiment...
Report text:

```
## Exception
* __User Action:__ requested feed
* __Request:__ Loading feed
* __Content Country:__ US
* __Content Language:__ en
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.20.2
* __OS:__ Linux samsung/beyond2qlteue/beyond2q:10/QP1A.190711.020/G975U1UEU4ETH8:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>


org.schabi.newpipe.local.feed.service.FeedLoadService$RequestException: 0:https://www.youtube.com/channel/UC_Jkj_gPEgksmXWECXw2dkg
	at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:223)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:66)
	at io.reactivex.internal.operators.parallel.ParallelMap$ParallelMapSubscriber.onNext(ParallelMap.java:113)
	at io.reactivex.internal.operators.parallel.ParallelFilter$ParallelFilterSubscriber.tryOnNext(ParallelFilter.java:130)
	at io.reactivex.internal.operators.parallel.ParallelRunOn$RunOnConditionalSubscriber.run(ParallelRunOn.java:397)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.RuntimeException: org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get channel id
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
	at io.reactivex.Single.blockingGet(Single.java:2870)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:217)
	... 11 more
Caused by: org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get channel id
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.getId(YoutubeChannelExtractor.java:133)
	at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:60)
	at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:48)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getChannelInfo$4(ExtractorHelper.java:124)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$u5W7VszTe8AoEexIsFM9huQfbkM.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.Single.blockingGet(Single.java:2869)
	... 12 more


</details>
<hr>
```

**Comment by AlexN1997** [comment]
Can you re do this experiment with v0.20.8?

**Comment by mhmdanas** [comment]
@esotericDisciple mind checking if this still happens with 0.20.8? If it does, please open a new issue following the template. I suspect this is related somehow to #3313, but I'm still not sure.

**Comment by esotericDisciple** [comment]
Is this version in fdroid/auroradroid? i haven't seen any updates for newpipe there in months

**Comment by mhmdanas** [comment]
There's an issue preventing us from publishing NewPipe updates to the main F-Droid repo (the latest available version on there is 0.20.1 I think). See https://github.com/TeamNewPipe/NewPipe#updates on how to get the latest version. You should read the whole section.

**Comment by esotericDisciple** [comment]
20.8 is unsuable because the "blank page" content tab isn't available

**Comment by mhmdanas** [comment]
I'm not sure what you're talking about. I went to "Settings > Content > Content of main page" and added "blank page" and it works just fine for me.
