### ISSUE TITLE
Incomplete subscription videos list

### ISSUE THREAD

**Issue by xgorex** [TeamNewPipe/NewPipe#5372]
Hi,
At the beginning, thank you for a gr8 work.

Now, the issue I am facing is the list of videos for selected (not all) subscribed channel are not updating for recent videos. For now two of them presents  more than 2 weeks old videos in the NewPIPE. The same channel on Youtube contains recent videos (e.g. 1h old, etc.). At the same time I have a subscribed channel which is updating correctly.
Do you see similar issue?
What data/info You could I provide to You in order to try to identify the issue?

Example problematic channels: 
https://www.youtube.com/channel/UCgo2BrI5xkXduYvYv6lskkg
https://www.youtube.com/channel/UCJ0VFYHC4J6KhC_ohzrJ0eA

Thank you. Andrzej

**Comment by LostWanita21** [comment]
I get this where I get a guru meditation error where it wont load a channel


## Exception
* __User Action:__ requested feed
* __Request:__ Loading feed
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.20.8
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.local.feed.service.FeedLoadService$RequestException: 0:https://www.youtube.com/channel/UChS9wazLlTUHSTeKVG39hZw
	at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:225)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:67)
	at io.reactivex.rxjava3.internal.operators.parallel.ParallelMap$ParallelMapSubscriber.onNext(ParallelMap.java:114)
	at io.reactivex.rxjava3.internal.operators.parallel.ParallelFilter$ParallelFilterSubscriber.tryOnNext(ParallelFilter.java:130)
	at io.reactivex.rxjava3.internal.operators.parallel.ParallelRunOn$RunOnConditionalSubscriber.run(ParallelRunOn.java:397)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.RuntimeException: org.schabi.newpipe.extractor.exceptions.ContentNotAvailableException: Got error: "This account has been terminated for a violation of YouTube's Terms of Service."
	at io.reactivex.rxjava3.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
	at io.reactivex.rxjava3.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:94)
	at io.reactivex.rxjava3.core.Single.blockingGet(Single.java:3645)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:219)
	... 11 more
Caused by: org.schabi.newpipe.extractor.exceptions.ContentNotAvailableException: Got error: "This account has been terminated for a violation of YouTube's Terms of Service."
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.defaultAlertsCheck(YoutubeParsingHelper.java:648)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.onFetchPage(YoutubeChannelExtractor.java:108)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:54)
	at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:47)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getChannelInfo$4(ExtractorHelper.java:135)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$BOLWstv98dC8pFAG_uir5gPXYwY.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.core.Single.blockingGet(Single.java:3644)
	... 12 more

```
</details>
<hr>

**Comment by mhmdanas** [comment]
@xgorex thanks for opening an issue! Do you have fast mode enabled? You can check if it is enabled by pressing the three lines at the screen's corner, pressing "What's New," press the button with a question mark in the app bar, and check if the button says "disable fast mode" or "enable fast mode". If it's the latter, it means that it's enabled and that we indeed have a bug here, otherwise fast mode is enabled and your problem may be fixed by disabling it. If you don't have fast mode enabled, or disabled it and the bug is still present, please open a new issue from the GitHub website that follows the bug report template properly.

@LostWanita21 please don't post unrelated comments. You're getting the error because you have a terminated channel in your subscriptions. Unfortunately, you'll have to search in your subscriptions to remove the terminated channel(s). See #3313.
