### ISSUE TITLE
Could not parse website (?)

### ISSUE THREAD

**Issue by mildyspec** [TeamNewPipe/NewPipe#5381]
### Checklist

- [x] I am using the latest version - 0.20.1 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to 'NewPipe' app
2. Press on 'Search'
3. Swipe down to any video that comes out

### Actual behaviour
Results in the 'Guru Meditation' and to the 'what happened' part, it reads : 'Could not parse website'

### Expected behavior
It should produce the video window with the option to play it, queue or background play.

### Screenshots/Screen recordings

![Uploading 13
![137588650_417810176034086_2984376720502618252_n](https://user-images.githubusercontent.com/77230432/104122062-71184280-534b-11eb-94a5-93c81f11a9fc.png)
7213512_431274961248805_8403746259684604303_n.png…]()

Also here is a link for the screenshot (just to be sure) : https://we.tl/t-DZxey6zeSe

## Exception
* _User Action:_ requested stream
* _Request:_ https://www.youtube.com/watch?v=YuBeBjqKSGQ
* _Content Country:_ GB
* _Content Language:_ en-GB
* _App Language:_ en_GB
* _Service:_ YouTube
* _Version:_ 0.20.1
* _OS:_ Linux xiaomi/daisy/daisy_sprout:10/QKQ1.191002.002/V11.0.14.0.QDLMIXM:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

org.schabi.newpipe.extractor.exceptions.ParsingException: YouTube did not provide player config even after three attempts
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:664)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:56)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:68)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$5fJcha6Sq5APJBLdG6osaJby-mc.call(Unknown Source:4)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

</details>
<hr>

### Device info

 - Android version/Custom ROM version: 10
 - Device model: Xiaomi Mi A2 Lite

**Comment by xibr** [comment]
Update to latest version (0.20.8).
https://github.com/TeamNewPipe/NewPipe#updates
