### ISSUE TITLE
Crashes switching back to App while in Video description

### ISSUE THREAD

**Issue by blauertee** [TeamNewPipe/NewPipe#5382]
### Checklist

- [x] I am using the latest version - 0.20.8 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Watch <a href="https://www.youtube.com/watch?v=VN562bgJRZ4">this</a> video in NewPipe
2. Open the video description, sroll down a bit
3. Switch to your music streaming app
4. Switch back to NewPipe

I wasn't able to reliably reproduce the bug with other Videos. But with this specific Video it happened six times and one time NewPipe actually behaved as expected. I also got a Bug report only one of these seven tries, so in the other cases where the App just closed without any notice the issue might be something different.

### Actual behaviour
App Immediately closes after switching back to it, playback stops and I'm at my home screen. 

### Expected behavior
Playback continues, I can go on reading the video description

### Logs

As I said I only got the error message once and this was still on 0.20.6 then I updated. The behaviour did not change on 0.20.8 but I never got an error notification there, this is why this log is from 0.20.6

## Exception
* User Action: ui error
* Request: App crash, UI failure
* Content Country: DE
* Content Language: de-DE
* App Language: de_DE
* Service: none
* Version: 0.20.6
* OS: Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

java.lang.StringIndexOutOfBoundsException: length=9; index=10
 at java.lang.String.substring(String.java:2060)
 at java.lang.String.subSequence(String.java:2107)
 at android.widget.TextView.onProvideStructure(TextView.java:11714)
 at android.view.View.onProvideAutofillStructure(View.java:8781)
 at android.view.View.dispatchProvideStructure(View.java:9992)
 at android.view.View.dispatchProvideAutofillStructure(View.java:9985)
 at android.view.ViewGroup.dispatchProvideAutofillStructure(ViewGroup.java:3674)
 at android.view.ViewGroup.dispatchProvideAutofillStructure(ViewGroup.java:3674)
 at android.view.ViewGroup.dispatchProvideAutofillStructure(ViewGroup.java:3674)
 at android.view.ViewGroup.dispatchProvideAutofillStructure(ViewGroup.java:3674)
 at android.view.ViewGroup.dispatchProvideAutofillStructure(ViewGroup.java:3674)
 at android.view.ViewGroup.dispatchProvideAutofillStructure(ViewGroup.java:3674)
 at android.view.ViewGroup.dispatchProvideAutofillStructure(ViewGroup.java:3674)
 at android.view.ViewGroup.dispatchProvideAutofillStructure(ViewGroup.java:3674)
 at android.view.ViewGroup.dispatchProvideAutofillStructure(ViewGroup.java:3674)
 at android.app.assist.AssistStructure$WindowNode.<init>(AssistStructure.java:528)
 at android.app.assist.AssistStructure.<init>(AssistStructure.java:2205)
 at android.app.ActivityThread.handleRequestAssistContextExtras(ActivityThread.java:3706)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2027)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:223)
 at android.app.ActivityThread.main(ActivityThread.java:7660)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

</details>
<hr>

**Comment by mhmdanas** [comment]
Thanks for opening an issue!

> Switch to your music streaming app

Can you specify what you mean exactly by a "music streaming app"?

**Comment by Stypox** [comment]
Could you check if [this apk](https://github.com/TeamNewPipe/NewPipe/suites/1836810430/artifacts/35510945) from the ci in #5148 solves the issue?

**Comment by blauertee** [comment]
Actually I wasn't able to reproduce the bug for now. So I can not tell you whether the apk from #5148 solves the issue. Sorry it seemed to be very reproducible maybe I should have restarted my device before submitting a bug report. 
The streaming app I use is Tidal. Feel free to close the Issue if this thing does not seem to be important :)

**Comment by Stypox** [comment]
For now I'm closing this. If you can find more information feel free to reopen it @blauertee ;-)
