### ISSUE TITLE
[dev] Crash when pressing back button in search

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipe#5436]
### Checklist

- [x] I am using the latest version - dev at 098c954ef1c5df41b2fd0201804c4e536b6b6b0b
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to search
2. Press on the back arrow in the app bar
3. get a crash

### Related issues
#5414
@Isira-Seneviratne Can you help?

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.20.8
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Fragment no longer exists for key f0: unique id 07596823-40d9-4d5f-a1b9-866b4e9f4af3
	at androidx.fragment.app.FragmentManager.getFragment(FragmentManager.java:772)
	at androidx.fragment.app.FragmentStatePagerAdapterMenuWorkaround.restoreState(FragmentStatePagerAdapterMenuWorkaround.java:311)
	at androidx.viewpager.widget.ViewPager.onRestoreInstanceState(ViewPager.java:1461)
	at android.view.View.dispatchRestoreInstanceState(View.java:20743)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3986)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3992)
	at android.view.View.restoreHierarchyState(View.java:20721)
	at androidx.fragment.app.Fragment.restoreViewState(Fragment.java:573)
	at androidx.fragment.app.FragmentStateManager.restoreViewState(FragmentStateManager.java:356)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1189)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
	at androidx.fragment.app.BackStackRecord.executePopOps(BackStackRecord.java:510)
	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2166)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1992)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1947)
	at androidx.fragment.app.FragmentManager.popBackStackImmediate(FragmentManager.java:658)
	at androidx.fragment.app.FragmentManager.popBackStackImmediate(FragmentManager.java:596)
	at org.schabi.newpipe.util.NavigationHelper.gotoMainFragment(NavigationHelper.java:283)
	at org.schabi.newpipe.MainActivity.onHomeButtonPressed(MainActivity.java:646)
	at org.schabi.newpipe.MainActivity.lambda$updateDrawerNavigation$3$MainActivity(MainActivity.java:738)
	at org.schabi.newpipe.-$$Lambda$MainActivity$x4OATthNilXVns6OoQlHV6SMv8w.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7448)
	at android.view.View.performClickInternal(View.java:7425)
	at android.view.View.access$3600(View.java:810)
	at android.view.View$PerformClick.run(View.java:28305)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: API 30
 - Device model: Pixel emulator

**Comment by TobiGr** [comment]
nvm. I started the wrong np version... it too late.
