### ISSUE TITLE
Crash when reordering channel groups

### ISSUE THREAD

**Issue by Br1ght0ne** [TeamNewPipe/NewPipe#5596]
### Checklist

- [x] I am using the latest version - 0.20.10
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Create 2+ channel groups
2. Press on the reorder icon right of the "Channel groups" text
3. Attempt to move any group

### Actual behaviour

The app crashes.

### Expected behavior

The group is moved, the app doesn't crash.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/12615679/107941019-c3bfcc80-6f91-11eb-99be-d11103dd5584.mp4

### Logs

(working on getting a logcat)

### Device info

 - Android version/Custom ROM version: Android 6.0.1, MIUI Global 10.2.2.0
 - Device model: Xiaomi Redmi 3S (land)

**Comment by XiangRongLin** [comment]
I'll take a shot of the dark and say it's from view binding
https://github.com/TeamNewPipe/NewPipe/pull/4814/commits/f04b5fd42f493df0dc6b35c8c45b3b498f4ef9f5

@Isira-Seneviratne

**Comment by Stypox** [comment]
I don't know why ACRA didn't start for you, but here is a crash report:

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ US
* __Content Language:__ en
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.20.10
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int com.xwray.groupie.Item.getDragDirs()' on a null object reference
	at com.xwray.groupie.GroupieViewHolder.getDragDirs(GroupieViewHolder.java:87)
	at com.xwray.groupie.TouchCallback.getDragDirs(TouchCallback.java:18)
	at androidx.recyclerview.widget.ItemTouchHelper$SimpleCallback.getMovementFlags(ItemTouchHelper.java:2293)
	at androidx.recyclerview.widget.ItemTouchHelper$Callback.getAbsoluteMovementFlags(ItemTouchHelper.java:1593)
	at androidx.recyclerview.widget.ItemTouchHelper$Callback.hasDragFlag(ItemTouchHelper.java:1598)
	at androidx.recyclerview.widget.ItemTouchHelper.startDrag(ItemTouchHelper.java:1092)
	at org.schabi.newpipe.local.subscription.item.FeedGroupReorderItem$bind$1.onTouch(FeedGroupReorderItem.kt:38)
	at android.view.View.dispatchTouchEvent(View.java:13949)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2698)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:465)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1849)
	at android.app.Dialog.dispatchTouchEvent(Dialog.java:861)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:423)
	at android.view.View.dispatchPointerEvent(View.java:14212)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5652)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5455)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5011)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4977)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5117)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4985)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5174)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5011)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4977)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4985)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7675)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7644)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7605)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7800)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:188)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:174)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

```
</details>
<hr>

**Comment by XiangRongLin** [comment]
@Isira-Seneviratne So any updates on this?

**Comment by Isira-Seneviratne** [comment]
> @Isira-Seneviratne So any updates on this?

@XiangRongLin Sorry my changes seem to be causing issues 😅

I'm currently away from home, so I'll check in a couple of days.

**Comment by XiangRongLin** [comment]
@Br1ght0ne Can you test out the changes in the linked PR and report any issues there?
