### ISSUE TITLE
comment bug

### ISSUE THREAD

**Issue by Nathawat-lab** [TeamNewPipe/NewPipe#5604]
## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=hF-_2JiI7gs
* __Content Country:__ TH
* __Content Language:__ th
* __App Language:__ th_TH
* __Service:__ YouTube
* __Version:__ 1.6
* __OS:__ Linux Android 7.0 - 24
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse date: "2021-02-10"
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.parseDateFrom(YoutubeParsingHelper.java:187)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getUploadDate(YoutubeStreamExtractor.java:191)
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractOptionalData(StreamInfo.java:266)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:73)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$YTHJjScxCJNO1LTCqs3IKy35iyY.call(lambda)
	at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:776)
Caused by: j$.time.format.DateTimeParseException: Text '2021-02-10' could not be parsed at index 10
	at j$.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
	at j$.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
	at j$.time.OffsetDateTime.parse(OffsetDateTime.java:402)
	at j$.time.OffsetDateTime.parse(OffsetDateTime.java:387)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.parseDateFrom(YoutubeParsingHelper.java:185)
	... 30 more

```
</details>
<hr>

**Comment by xibr** [comment]
Update to 0.20.10
See https://github.com/TeamNewPipe/NewPipe#installation-and-updates

**Comment by mhmdanas** [comment]
@Nathawat-lab the NewPipe version you're using raises some eyebrows. We don't have a 1.6 release. Mind saying where you got it from?
