### ISSUE TITLE
Crash when requesting a Channel/Feed/Subscriptions

### ISSUE THREAD

**Issue by h4lfh0nk** [TeamNewPipe/NewPipe#5707]
<h1>EDIT</h1>
This is an issue with youtube not us: https://support.google.com/youtube/thread/99787251

---

### Checklist

- [x] I am using the latest version - 20.10
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Request any Channel

### Actual behaviour

Crash

### Expected behavior

Channel opens

## Exception
* __User Action:__ requested channel
* __Request:__ https://www.youtube.com/channel/UCp96ZKaODsGQwWYCR5T3DeA
* __Content Country:__ DE
* __Content Language:__ de-DE
* __App Language:__ de_DE
* __Service:__ YouTube
* __Version:__ 0.20.10
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get channel id
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.getId(YoutubeChannelExtractor.java:130)
	at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:60)
	at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:48)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getChannelInfo$4(ExtractorHelper.java:136)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$BOLWstv98dC8pFAG_uir5gPXYwY.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version:
 - Device model: One Plus 8 pro and Fire TV ( Same Bug)

**Comment by pooppp3** [comment]
ok

**Comment by h4lfh0nk** [comment]
Its working again, maybd YouTube die try Something.
I tried with two devices - mobile and Fire TV. And two Networks - mobile and cable.

**Comment by pooppp3** [comment]
yay

**Comment by adaasch** [comment]
I have the same problem and it persists.

**Comment by pooppp3** [comment]
aw man

**Comment by h4lfh0nk** [comment]
Damn, its On and Off for me now... Definitely worth to observe

**Comment by pooppp3** [comment]
ok

**Comment by Imarok** [comment]
This also happens on youtube itself. So I guess youtube just has some issues with their site/servers and it's not a bug of newpipe.

**Comment by SanderAZ** [comment]
Same problem here. Requesting any channel leads to a crash, and I get the same "could not get channel id" message.

Google Pixel 3a XL | Android 11, build RQ1A.210205.004 | Newpipe 0.20.10

**Comment by iomintz** [comment]
I just checked the channel link from the original post. Channels load now, both on youtube.com and on NewPipe.
