### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Thewisem** [TeamNewPipe/NewPipe#5712]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.20.10
* __OS:__ Linux Android 7.1.1 - 25
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IndexOutOfBoundsException: setSpan (-1 ... -1) starts before 0
	at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:434)
	at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:155)
	at android.text.SpannableString.setSpan(SpannableString.java:46)
	at android.text.Selection.setSelection(Selection.java:76)
	at android.widget.TextView.semSetSelection(TextView.java:11588)
	at android.widget.Editor$SelectionModifierCursorController.resetDragAcceleratorState(Editor.java:6895)
	at android.widget.Editor$SelectionModifierCursorController.resetTouchOffsets(Editor.java:6884)
	at android.widget.Editor.onFocusChanged(Editor.java:1360)
	at android.widget.TextView.onFocusChanged(TextView.java:9739)
	at android.view.View.clearFocusInternal(View.java:6859)
	at android.view.View.unFocus(View.java:6892)
	at android.view.ViewGroup.unFocus(ViewGroup.java:1001)
	at android.view.ViewGroup.unFocus(ViewGroup.java:1001)
	at android.view.ViewGroup.unFocus(ViewGroup.java:1001)
	at android.view.ViewGroup.unFocus(ViewGroup.java:1001)
	at android.view.ViewGroup.unFocus(ViewGroup.java:1001)
	at android.view.ViewGroup.unFocus(ViewGroup.java:1001)
	at android.view.ViewGroup.unFocus(ViewGroup.java:1001)
	at android.view.ViewGroup.requestChildFocus(ViewGroup.java:738)
	at org.schabi.newpipe.views.FocusAwareCoordinator.requestChildFocus(FocusAwareCoordinator.java:54)
	at android.view.ViewGroup.requestChildFocus(ViewGroup.java:744)
	at android.view.ViewGroup.requestChildFocus(ViewGroup.java:744)
	at android.view.View.handleFocusGainInternal(View.java:6675)
	at android.view.ViewGroup.handleFocusGainInternal(ViewGroup.java:720)
	at android.view.View.requestFocusNoSearch(View.java:9904)
	at android.view.View.requestFocus(View.java:9883)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:3048)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3088)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:3044)
	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3088)
	at android.view.ViewGroup.requestFocus(ViewGroup.java:3047)
	at android.view.View.requestFocus(View.java:9850)
	at android.view.View.requestFocus(View.java:9829)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.moveFocusToMainFragment(VideoDetailFragment.java:2153)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.access$800(VideoDetailFragment.java:127)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$5.onStateChanged(VideoDetailFragment.java:2240)
	at com.google.android.material.bottomsheet.BottomSheetBehavior.setStateInternal(BottomSheetBehavior.java:1109)
	at com.google.android.material.bottomsheet.BottomSheetBehavior$SettleRunnable.run(BottomSheetBehavior.java:1540)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:930)
	at android.view.Choreographer.doCallbacks(Choreographer.java:705)
	at android.view.Choreographer.doFrame(Choreographer.java:637)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:916)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6823)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by TobiGr** [comment]
Please tell us how you encountered this crash and fill in the template. Otherwise we cannot reproduce and fix it. Please leave a comment once you filled in the data.

**Comment by Thewisem** [comment]
No clue. Honestly I had no idea

**Comment by Thewisem** [comment]
All I could say is I was too busy with some other app and when I came baxk this happend if that makes any sense.

**Comment by Thewisem** [comment]
I would help If I know what would reproduce this. But this is one of those moments where you have no idea how it happend but it did happen

**Comment by TiA4f8R** [comment]
Similar to #5155 but the end of the stacktrace is different and this crash seems to be linked with the `VideoDetailFragment`.
