### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by jzzunl** [TeamNewPipe/NewPipe#5777]
## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ GB
* __Content Language:__ en
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.20.11
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.schabi.newpipe/org.schabi.newpipe.MainActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: android.support.v4.app.FragmentManagerState
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3302)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3441)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2045)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7399)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: android.support.v4.app.FragmentManagerState
	at android.os.Parcel.readParcelableCreator(Parcel.java:3042)
	at android.os.Parcel.readParcelable(Parcel.java:2964)
	at android.os.Parcel.readValue(Parcel.java:2866)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:3244)
	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
	at android.os.BaseBundle.unparcel(BaseBundle.java:236)
	at android.os.BaseBundle.getBoolean(BaseBundle.java:899)
	at android.app.Activity.restoreHasCurrentPermissionRequest(Activity.java:8164)
	at android.app.Activity.performCreate(Activity.java:7865)
	at android.app.Activity.performCreate(Activity.java:7858)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3277)
	... 11 more

```
</details>
<hr>

Additional info:
Device: Lenovo m10 2nd gen wifi version
Model number: TB-X606F
Root status: Rooted with magisk

**Comment by jzzunl** [comment]
Enabling magisk hide and systemless hosts support in the magisk app fixed it
