### ISSUE TITLE
Crash when resuming from background after playback ended

### ISSUE THREAD

**Issue by danielzgtg** [TeamNewPipe/NewPipe#5800]
### Checklist

- [x] I am using the latest version - 0.20.11
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Play a video in the background
2. Multitask away from NewPipe
3. Wait until it ends
4. Wait a long time, use the phone for something else, and even not use the phone for some time. (Basically give Android a potential reason to kill the app)
5. Open Android recents
6. Resume NewPipe

This bug doesn't happen all the time.

### Actual behaviour

I saw an empty playback queue flash once or twice, then I saw the crash dialog.

### Expected behavior

It should not crash

### Screenshots/Screen recordings

I wasn't able to take a screenshot before I saw the error page

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ GB
* __Content Language:__ en
* __App Language:__ en_CA
* __Service:__ none
* __Version:__ 0.20.11
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.exoplayer2.PlaybackParameters org.schabi.newpipe.player.Player.getPlaybackParameters()' on a null object reference
	at org.schabi.newpipe.player.PlayQueueActivity.onCreateOptionsMenu(PlayQueueActivity.java:106)
	at android.app.Activity.onCreatePanelMenu(Activity.java:4212)
	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:324)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3070)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:456)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:57)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8010)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: OP7Pro_O2_BETA_3
 - Device model: OnePlus 7 Pro

**Comment by litetex** [comment]
Should be fixed by #8244
