### ISSUE TITLE
Crash on tapping anywhere on video after long-pressing 'Popup' button

### ISSUE THREAD

**Issue by jarp0l** [TeamNewPipe/NewPipe#5804]
### Checklist

- [x] I am using the latest version - 0.20.11 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open any video (play it or pause it, doesn't matter).
2. Long-press (press and hold) the 'Popup' button, 'Enqueued' dialog appears.
3. Tap anywhere on video.

### Actual behaviour

The app immediately crashes and displays crash log.

The app still crashes when you:
- play next video and tap anywhere on the video.
- go to Downloads by long-pressing the Download button, then come back to the video and like above tap anywhere on the video.

### Expected behavior

Tapping anywhere on the video should display the controls (Play/Pause and others) rather than crashing.

### Screenshots/Screen recordings

<img src="https://user-images.githubusercontent.com/57973356/110599603-25e3aa00-81ab-11eb-958b-4178b550d0dc.gif" alt="crash-recording" height="592" width="288"/>

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.20.11
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException
	at org.schabi.newpipe.player.event.BasePlayerGestureListener.onDownInPopup(BasePlayerGestureListener.kt:232)
	at org.schabi.newpipe.player.event.BasePlayerGestureListener.onDown(BasePlayerGestureListener.kt:222)
	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:661)
	at org.schabi.newpipe.player.event.BasePlayerGestureListener.onTouchInPopup(BasePlayerGestureListener.kt:108)
	at org.schabi.newpipe.player.event.BasePlayerGestureListener.onTouch(BasePlayerGestureListener.kt:82)
	at android.view.View.dispatchTouchEvent(View.java:14372)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3857)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3492)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:733)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1922)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4051)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:691)
	at android.view.View.dispatchPointerEvent(View.java:14644)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6526)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6313)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5751)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5804)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5770)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5926)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5778)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5983)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5751)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5804)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5770)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5778)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5751)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8910)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8771)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8724)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9046)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:194)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:197)
	at android.app.ActivityThread.main(ActivityThread.java:7948)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

```
</details>
<hr>

### More Information

I was also able to reproduce this on Android 6.0.1 - 23 and NewPipe v0.20.10 as well; all on Samsung devices (J4+, Tab E and J2 Prime, all Galaxy series). 

However, I couldn't reproduce it on NewPipe v0.20.8 (on Xioami Redmi Note 3), because when the 'Popup' button is long-pressed, video plays on Popup mode. But after upgrading to the latest version I could reproduce the crash on this device too.

**Comment by iamthesenate1** [comment]
Can reproduce on Redmi Note 5A, Android 7.1.2

**Comment by jarp0l** [comment]
Reproduced only on v0.20.1 and 0.20.11, but not on 0.20.8 and 0.20.9.

**Comment by wangear** [comment]
Hello! I'd like to work on this enhancement. Can i assigned to this issue? :)

**Comment by wangear** [comment]
Hello. Can I assigned to this issue?

**Comment by ShareASmile** [comment]
@mhmdanas  ☝☝

**Comment by wangear** [comment]
Thank you

**Comment by mhmdanas** [comment]
@wangear I assigned you to the issue, but to be clear, you don't have to be assigned to an issue to work on it.

**Comment by wangear** [comment]
@mhmdanas sorry.I don't understand what you mean. Is this an issue someone is working on?

**Comment by mhmdanas** [comment]
No, but I meant that you didn't have to wait for me to assign you to this issue to start working on it.

**Comment by wangear** [comment]
@mhmdanas Oh..I see. Thanks a lot!

**Comment by mhmdanas** [comment]
@wangear you have not opened a PR. You only pushed a commit (which is a prerequisite to open a PR). See https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request for instructions on how to open a PR.

**Comment by wangear** [comment]
@mhmdanas ok. Sorry.
