### ISSUE TITLE
Crash when opening very quickly the search window after NewPipe launch

### ISSUE THREAD

**Issue by Massedil** [TeamNewPipe/NewPipe#5812]
### Checklist

- [x] I am using the latest version - 0.20.11 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open NewPipe and very quickly click on the search icon as soon as it appears

### Actual behaviour

NewPipe crashes.

### Expected behavior

No crash and possibility to search !

## Exception
* __User Action:__ ui error
* __Request:__ App crash, UI failure
* __Content Country:__ FR
* __Content Language:__ fr
* __App Language:__ fr_FR
* __Service:__ none
* __Version:__ 0.20.11
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to read from field 'android.widget.TextView org.schabi.newpipe.databinding.PlaylistHeaderBinding.playlistTitleView' on a null object reference
at org.schabi.newpipe.fragments.list.playlist.PlaylistFragment.setTitle(PlaylistFragment.java:449)
at org.schabi.newpipe.fragments.list.BaseListInfoFragment.handleResult(BaseListInfoFragment.java:205)
at org.schabi.newpipe.fragments.list.playlist.PlaylistFragment.handleResult(PlaylistFragment.java:273)
at org.schabi.newpipe.fragments.list.playlist.PlaylistFragment.handleResult(PlaylistFragment.java:67)
at org.schabi.newpipe.fragments.list.BaseListInfoFragment.lambda$startLoading$0(BaseListInfoFragment.java:135)
at org.schabi.newpipe.fragments.list.BaseListInfoFragment.lambda$startLoading$0$BaseListInfoFragment(Unknown Source:0)
at org.schabi.newpipe.fragments.list.-$$Lambda$BaseListInfoFragment$Gn1fP3-8OJnktT5gkmUmbW-egTg.accept(Unknown Source:4)
at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7356)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: Android 10 / LineageOS 17.1
 - Device model: Samasung Galaxy S5 (klte)

**Comment by Massedil** [comment]
Still here with 0.21.1. Can you reopen this bug ?

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ FR
* __Content Language:__ fr
* __App Language:__ fr_FR
* __Service:__ none
* __Version:__ 0.21.1
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to read from field 'android.widget.TextView org.schabi.newpipe.databinding.PlaylistHeaderBinding.playlistTitleView' on a null object reference
	at org.schabi.newpipe.fragments.list.playlist.PlaylistFragment.setTitle(PlaylistFragment.java:426)
	at org.schabi.newpipe.fragments.list.BaseListInfoFragment.handleResult(BaseListInfoFragment.java:222)
	at org.schabi.newpipe.fragments.list.playlist.PlaylistFragment.handleResult(PlaylistFragment.java:276)
	at org.schabi.newpipe.fragments.list.playlist.PlaylistFragment.handleResult(PlaylistFragment.java:66)
	at org.schabi.newpipe.fragments.list.BaseListInfoFragment.lambda$startLoading$0(BaseListInfoFragment.java:145)
	at org.schabi.newpipe.fragments.list.BaseListInfoFragment.lambda$startLoading$0$BaseListInfoFragment(Unknown Source:0)
	at org.schabi.newpipe.fragments.list.-$$Lambda$BaseListInfoFragment$Gn1fP3-8OJnktT5gkmUmbW-egTg.accept(Unknown Source:4)
	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

```
</details>
<hr>
