### ISSUE TITLE
Error "guru meditation"

### ISSUE THREAD

**Issue by reno-a** [TeamNewPipe/NewPipe#5870]
## Exception
* __User Action:__ requested feed
* __Request:__ Loading feed
* __Content Country:__ FR
* __Content Language:__ fr-FR
* __App Language:__ fr_FR
* __Service:__ none
* __Version:__ 0.20.11
* __OS:__ Linux motorola/aljeter/aljeter:9/PPP29.55-35-18/f7946:user/release-keys 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.local.feed.service.FeedLoadService$RequestException: 0:https://www.youtube.com/channel/UC0AuOxCr9TZ0TtEgL1zpIgA
	at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:226)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:68)
	at io.reactivex.rxjava3.internal.operators.parallel.ParallelMap$ParallelMapSubscriber.onNext(ParallelMap.java:114)
	at io.reactivex.rxjava3.internal.operators.parallel.ParallelFilter$ParallelFilterSubscriber.tryOnNext(ParallelFilter.java:130)
	at io.reactivex.rxjava3.internal.operators.parallel.ParallelRunOn$RunOnConditionalSubscriber.run(ParallelRunOn.java:397)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.RuntimeException: org.schabi.newpipe.extractor.exceptions.ContentNotAvailableException: Got error: "This account has been terminated for violating YouTube's Community Guidelines."
	at io.reactivex.rxjava3.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
	at io.reactivex.rxjava3.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:94)
	at io.reactivex.rxjava3.core.Single.blockingGet(Single.java:3645)
	at org.schabi.newpipe.local.feed.service.FeedLoadService$startLoading$7.apply(FeedLoadService.kt:220)
	... 11 more
Caused by: org.schabi.newpipe.extractor.exceptions.ContentNotAvailableException: Got error: "This account has been terminated for violating YouTube's Community Guidelines."
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.defaultAlertsCheck(YoutubeParsingHelper.java:685)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.onFetchPage(YoutubeChannelExtractor.java:116)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:54)
	at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:47)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getChannelInfo$4(ExtractorHelper.java:136)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$BOLWstv98dC8pFAG_uir5gPXYwY.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.core.Single.blockingGet(Single.java:3644)
	... 12 more

```
</details>
<hr>

**Comment by snappyapple632** [comment]
The channel you were trying to refresh was terminated.

**Comment by mhmdanas** [comment]
@reno-a it's as @snappyapple632 says. The channel's name appears to be "FranceNoir." Remove your subscription from that channel and feed fetching should work again. Also, please don't remove the template next time you open an issue.

**Comment by reno-a** [comment]
Thank-you for tour help.---R. AIGOINLe 22 mars 2021 06:08, Mohammed Anas ***@***.***> a écrit :
@reno-a it's as @snappyapple632 says. The channel's name appears to be "FranceNoir." Remove your subscription from that channel and feed fetching should work again. Also, please don't remove the template next time you open an issue.
