### ISSUE TITLE
Nothing at all loading. 

### ISSUE THREAD

**Issue by hagueyno1** [TeamNewPipe/NewPipe#5905]
## Exception
* __User Action:__ requested playlist
* __Request:__ https://www.youtube.com/playlist?list=PLQeroY7XkiFGY2FGfeTMUjGNMFrseZ9Yn
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ YouTube
* __Version:__ 0.20.11
* __OS:__ Linux Android 8.0.0 - 26
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: JSON response is too short
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getValidJsonResponseBody(YoutubeParsingHelper.java:597)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getJsonResponse(YoutubeParsingHelper.java:652)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubePlaylistExtractor.onFetchPage(YoutubePlaylistExtractor.java:55)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:54)
	at org.schabi.newpipe.extractor.playlist.PlaylistInfo.getInfo(PlaylistInfo.java:30)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getPlaylistInfo$9(ExtractorHelper.java:183)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$RLOrwix0kCDfcc_WpFBc8DTJw0Q.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

```
</details>
<hr>

**Comment by TiA4f8R** [comment]
Please fill correctly the template. Do you use any VPN or not? I just tried on my phone and it works.

**Comment by hagueyno1** [comment]
Hi no not using a VPN, I'll turn it on and try it, and apologies I was really busy that's why I just hit the copy part and sent it in. I'll get screenshots too in a minute

**Comment by hagueyno1** [comment]
I've sent it in via email too
![Uploading Screenshot_20210324-184916_NewPipe.jpg…]()

**Comment by TiA4f8R** [comment]
Does it happens when you open on the YouTube website on your device? And on other playlists? The screenshot you tried to upload isn't shown, the upload failed.
If yes, try to reboot your Internet router first.

**Comment by hagueyno1** [comment]
Hi,
It's directly from my phones Internet, I've tried with a vpn and without and it won't load anything, , its always worked fine except lately the capthca has been happening more often, I have it here ready to copy and paste but I don't know where you'd want that

**Comment by hagueyno1** [comment]
I'll video it and see if that works so you can see what's going on, absolutely nothing works, I darent uninstall with the sheer amount of playlists and songs I have saved.
Give me 10 mins I'll video it

**Comment by hagueyno1** [comment]
Those is the screenshot, it won't let me upload the video, keeps telling me
it's too large but I don't know how to reduce its size.

**Comment by hagueyno1** [comment]
I've emailed the screenshot, it won't let me send the video though, even though I've made more than one to try make it smaller in size but still it's too large to send it.

**Comment by TobiGr** [comment]
to which email address did you send the video?

**Comment by hagueyno1** [comment]
This is the screenshot, I'll try the video again though.

**Comment by hagueyno1** [comment]
Hi I've tried multiple times with different sized videos but none will send
they just get returned with the message that it's too large but no way to
Roydon /reduce its size.

**Comment by hagueyno1** [comment]
The screenshot I sent you is exactly what happens on absolutely anything I
try to open/watch /listen in the background to, very frustrating, your app
is hands down the best ever and I'm hoping there is a fix for it.

**Comment by TiA4f8R** [comment]
Please upload the screenshot **with GitHub, not with your email client**.
If your screencast is too big, try lowering the resolution by half with [Video Transcoder](https://f-droid.org/packages/protect.videoeditor).

**Comment by hagueyno1** [comment]
https://user-images.githubusercontent.com/25346219/112378487-e9ea3200-8cde-11eb-8b48-60d3a9cf12f9.mp4

**Comment by hagueyno1** [comment]
Done it pal, I think it's finally worked using the app you told me to get
👍.
I've done the video I'll do the screenshot too.

**Comment by TobiGr** [comment]
Please create a HAR by following these insrtuctions: https://github.com/TeamNewPipe/NewPipe/wiki/Additional-Debugging-Info
You can use this APK for it: https://github.com/TeamNewPipe/NewPipe/files/6178575/NewPipe_0.21.0_RC1.zip
Send the HAR to tnp@newpipe.schabi.org

**Comment by hagueyno1** [comment]
![20210324_202908](https://user-images.githubusercontent.com/25346219/112379194-c1166c80-8cdf-11eb-961c-52a0cfeed0c0.jpg)

**Comment by hagueyno1** [comment]
![20210324_202921](https://user-images.githubusercontent.com/25346219/112379235-ce335b80-8cdf-11eb-931b-68770f8f69bc.jpg)

**Comment by hagueyno1** [comment]
![20210324_202927](https://user-images.githubusercontent.com/25346219/112379261-d8555a00-8cdf-11eb-98b4-da63520f8b07.jpg)

**Comment by hagueyno1** [comment]
Hi I'm really sorry, I've tried to do what I can, I've enabled usb
debugging etc but I don't have have a pc or laptop I've no need, I've
always just used my phone, I've emailed to the generic email address the
report is taken though sorry pal, if I can do anything else let me know
I've rebooted my phone and that's not worked either.

**Comment by hagueyno1** [comment]
Right what you've sent me the link etc actually works fine I can even import my settings, so it's obviously something that's halterneck /happened at my end and I've a feeling it's the bloody YouTube recaptcha at I was getting it upto 5 times a day some days, where do wet go from here?

**Comment by Abdel-ilah** [comment]
I confirm that trading page not loading

**Comment by TiA4f8R** [comment]
> I confirm that trading page not loading

Trending page is an other issue which will be fixed in 0.21.0.

**Comment by hagueyno1** [comment]
What does that mean?
The other apk version of newpipe I was sent works perfect it's I think
0.21.0 it just won't load what's trending which isn't an issue for me but
I'd rather the latest be working. Thankyou.

**Comment by hagueyno1** [comment]
Oh cool, thankyou 👍

**Comment by corkiejp** [comment]
Downloaded the RC1 and getting 'Sorry, Something went wrong'.

Are you using webview in the app maybe related?
https://www.xda-developers.com/google-confirms-webview-issue-crashing-android-apps/

**Comment by hagueyno1** [comment]
Hi, so strangely I can't find it in my settings and also when I find it
through the play store it has no option to remove the update on fact it has
no option at all which I can screenshot for you but its very strange.

**Comment by hagueyno1** [comment]
OK, so I've literally gone through every single setting in the app now the
one that wouldn't work and one that's appeared one not seen before is clear
recaptcha data so I've done that still checked all other settings, cleared
the app off and back on and it seems to ask be back to normal and working
fine. Very strange, it just be to do with those recaptchas from YouTube.
Sorry for any inconvenience caused, I love this app and rely on it so much
and when I can't use it then it leaves a kind of hole. Thanks again, James.

**Comment by JohnKyonSmith** [comment]
Ya lleguéYa llegué

**Comment by danffosddu** [comment]
Mine doing the same. Open App and timer just turns in centre. Blank screen with tabs at top nut nothing loads. Have uninstall and reinstalled. Was working fine till a few weeks ago

**Comment by litetex** [comment]
Does the problem still persist?
There are a lot of not meaningful comments in this issue.
So I kind of lost the overview.

@TobiGr 
Did we receive a HAR file?

Otherwise I think we should close this issue 😄

**Comment by litetex** [comment]
Closing - no feedback
