### ISSUE TITLE
ParsingException: Could not get ytInitialData

### ISSUE THREAD

**Issue by Mattrazol** [TeamNewPipe/NewPipe#5977]
## Exception
* __User Action:__ requested channel
* __Request:__ Start loading: http://www.youtube.com/c/TheMoonCarl
* __Content Country:__ US
* __Content Language:__ en
* __App Language:__ en
* __Service:__ YouTube
* __Version:__ 0.21.0
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get ytInitialData
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getInitialData(YoutubeParsingHelper.java:270)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.extractClientVersionAndKey(YoutubeParsingHelper.java:288)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getKey(YoutubeParsingHelper.java:366)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.getNextPageFrom(YoutubeChannelExtractor.java:303)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.getInitialPage(YoutubeChannelExtractor.java:251)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)
	at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:83)
	at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:48)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getChannelInfo$4(ExtractorHelper.java:123)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$BOLWstv98dC8pFAG_uir5gPXYwY.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: org.schabi.newpipe.extractor.utils.Parser$RegexException: failed to find pattern "var\s*ytInitialData\s*=\s*(\{.*?\});"
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:74)
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:63)
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup1(Parser.java:54)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getInitialData(YoutubeParsingHelper.java:266)
	... 33 more

```
</details>
<hr>

**Comment by bauspanderu** [comment]
I'm having the same issue, I think it's because of a new cookie site that opens before the actual channel.

**Comment by Neeqstock** [comment]
Same issue: Could not get ytInitialData

**Comment by TobiGr** [comment]
We are on it

**Comment by TobiGr** [comment]
Can you please test this debug version and tell me whether the problem is solved?
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/6243573/app-debug.zip)

**Comment by Mattrazol** [comment]
@TobiGr Yes it seems to work now.

**Comment by noahjutz** [comment]
> Can you please test this debug version and tell me whether the problem is solved?
> [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/6243573/app-debug.zip)

Works for me, too.

**Comment by Neeqstock** [comment]
> 
> 
> Can you please test this debug version and tell me whether the problem is solved?
> [app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/6243573/app-debug.zip)

This test version works for me also.

**Comment by TobiGr** [comment]
Here is another debug APK. This time with no consent given (`PENDING+999`). Please test again.
Note: No cookie set, using the `CONSENT` header....
[app-debug.zip](https://github.com/TeamNewPipe/NewPipe/files/6251337/app-debug.zip)

**Comment by Mattrazol** [comment]
@TobiGr yes, this last one seems to work as well for me.

**Comment by Gaffen** [comment]
I tried a version earlier today and it worked, then I uninstalled it. I reinstalled just now and got prompted to do the cookie thing. I completed it successfully and returned to newpipe but search wouldn't work; I get the ytinitialdata error again.

**Comment by darrenmothersele** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/5977#issuecomment-812728868

Works for me. Thanks.

**Comment by Gaffen** [comment]
> I tried a version earlier today and it worked, then I uninstalled it. I reinstalled just now and got prompted to do the cookie thing. I completed it successfully and returned to newpipe but search wouldn't work; 

> I tried a version earlier today and it worked, then I uninstalled it. I reinstalled just now and got prompted to do the cookie thing. I completed it successfully and returned to newpipe but search wouldn't work; I get the ytinitialdata error again.

My bad; I uninstalled uninstalled and reinstalled the most recently linked debug version; I now appear to be able to use the search facility.

**Comment by deltragon** [comment]
> However, when I import my old settings it no longer works
Same problem here, however it only affects the settings - if I clear the data, and import only subscriptions, playlist and history, but decline settings, it keeps working.

**Comment by Mattrazol** [comment]
After the latest update it got worse. Before if I did the challenge it would work for a few videos, but now it doesn't work at all. It keeps asking to solve the challenge over and over without reproducing any videos whatsoever.

**Comment by Neeqstock** [comment]
Same here (internet access from Italy).
Version 0.21.1 gives the same issue as before. Cannot search for any video, although it can reproduce videos from links.

Strangely enough, the Debug Version posted by TobiGr (0.21.0 Debug, app-debug.zip) still works perfectly without giving the ytInitialData issue.

**Comment by darrenmothersele** [comment]
I can confirm that search isn't working with version 0.21.1
Error: org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get ytInitialData

But version 0.21.0 Debug from above is working fine.

**Comment by Gaffen** [comment]
To add more confusion to the mix, a few days ago my v0.21.0 spontaneously started working again for no discernable reason (using in the UK that is, as I get the feeling this issue concerns GDPR stuff).

**Comment by darrenmothersele** [comment]
The debug version stopped working (with the parse error). I uninstalled and reinstalled and it's working again.

**Comment by 12people** [comment]
Clearing ReCaptcha data under Settings > Content fixed this problem for me.

**Comment by Mattrazol** [comment]
@12people Wow! That is true! I wonder how long this is going to last though.. But hey, at least now it works! Thanks!

**Comment by TiA4f8R** [comment]
If what @12people said doesn't work, can you reproduce the problem with #5997 and/or with the APK generated in the checks tab of https://github.com/TiA4f8R/NewPipe/pull/3?

**Comment by straves16** [comment]
> ## Exception
> * **User Action:** requested channel
> * **Request:** Start loading: http://www.youtube.com/c/TheMoonCarl
> * **Content Country:** US
> * **Content Language:** en
> * **App Language:** en
> * **Service:** YouTube
> * **Version:** 0.21.0
> * **OS:** Linux Android 11 - 30
> 
> Crash log
> I'm also having problem fetching my Subscriptions 76/86 don't get updated.

**Comment by TiA4f8R** [comment]
@12people Did you try the RC of the 0.21.3 version or my APK using the link I mentioned above? Can you reproduce the bug with these two versions?

**Comment by martinambrus** [comment]
Latest debug version from the linked build page works for me in Europe - Slovakia.

**Comment by Ignacy-s** [comment]
> Now I'm having the same problem again, but the option to clear reCaptcha no longer appears in settings.
> 
> I use an EU VPN and turning off the VPN fixes the problem.

This is a working workaround for me! Thanks much! 

WORKAROUND:
VPN trough non-EU state (tested with USA and Nord).
Search works now.

**Comment by TiA4f8R** [comment]
Can you try the 3rd RC of the 0.21.6 version (see the pinned issue) and let us know if it works? Thank you in advance.

**Comment by Ignacy-s** [comment]
> Can you try the 3rd RC of the 0.21.6 version (see the pinned issue) and let us know if it works? Thank you in advance.

Tested and works from Poland, both mobile network and family Wi-Fi from local provider.

However, if client is force-closed from app-info, and then VPN is turned on, networking won't work. But if NewPipe was run first without VPN, and then after connecting successfully, trough VPN, it works.

Error log when resetting the app and trying to connect trough VPN, even suggested videos don't work (which worked before when search didn't work). Tried using NordVPN and countries both in EU and North America.

## Exception
* __User Action:__ searched
* __Request:__ grobix
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.21.6
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.net.UnknownHostException: Unable to resolve host "www.youtube.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at okhttp3.Dns$1.lookup(Dns.java:40)
	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:215)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
	at okhttp3.RealCall.execute(RealCall.java:93)
	at org.schabi.newpipe.DownloaderImpl.execute(DownloaderImpl.java:264)
	at org.schabi.newpipe.extractor.downloader.Downloader.get(Downloader.java:70)
	at org.schabi.newpipe.extractor.downloader.Downloader.get(Downloader.java:54)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.isHardcodedClientVersionValid(YoutubeParsingHelper.java:295)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getClientVersion(YoutubeParsingHelper.java:368)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.addClientInfoHeaders(YoutubeParsingHelper.java:719)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.addYouTubeHeaders(YoutubeParsingHelper.java:705)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getJsonResponse(YoutubeParsingHelper.java:668)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.onFetchPage(YoutubeSearchExtractor.java:60)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:54)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:29)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$searchFor$0(ExtractorHelper.java:81)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$qyxpuXgomWa-cbONQns-pd7zxm0.call(Unknown Source:8)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:202)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	... 46 more

```
</details>
<hr>

**Comment by martinambrus** [comment]
all features of the 3rd RC version of 0.21.6 works for me im Europe - Slovakia (cellular operator, 4G data as well as 3G data roamed through another EU operator)

**Comment by hp8wvvvgnj6asjm7** [comment]
this will never be fixed..

**Comment by AlertSubject** [comment]
Having the same issue
2 of my subscriptions cannot be loaded

**Comment by Stypox** [comment]
Is it fixed in 0.21.8? Maybe switching to youtubei solved something, I don't know.
