### ISSUE TITLE
Channels dont load from subscriptions. Comments arent showing

### ISSUE THREAD

**Issue by Hogerys** [TeamNewPipe/NewPipe#5985]
### Checklist

- [x] I am using the latest version 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Solved:

I had to clear the captchas fuck me.

### Steps to reproduce the bug

Open newpipe.
Tap on reload bar
Bar is going
Videos not showing, (not loaded: *number*)

Open video 
go to comments
error

### Actual behaviour

When i try to load a feed i see the loading line going (maybe a bit too fast) but the reload bar says "Not loaded: *number*". It doesnt give an arror screen or log. Also i cant view the comments, this gives error, i pasted it below. Tried closing, clearing cache reinstalling did not work. The issue is the same as #5977 but many people say the debug-app.zip apk worked for them, this didnt for me so i opened an issue too to be safe.

### Expected behavior

Subscriptions and comments parsing.

## Exception
* __User Action:__ requested comments
* __Request:__ Start loading: https://www.youtube.com/watch?v=EXJgfj-Nlek
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.21.0
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.utils.Parser$RegexException: failed to find pattern "INNERTUBE_CONTEXT_CLIENT_NAME\":(.*?)[,}]"
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:74)
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup1(Parser.java:58)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.onFetchPage(YoutubeCommentsExtractor.java:137)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:54)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:34)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:25)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getCommentsInfo$7(ExtractorHelper.java:154)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$60N_-UL7E5eaxFaFO1bZZmnfwM8.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```
</details>
<hr>

**Comment by Hogerys** [comment]
VPN with USA connection isnt working either so the 592 issue on Newpipeextractor doesnt seem to be the issue.

**Comment by Blackfire-dev** [comment]
Commenting to follow this. 
Same issue for me in the UK with or without VPN
Force stop and Restart didn't work.
Going back to 0.20.11 until someone better than me comes up with a solution.

**Comment by joshontech** [comment]
I had this issue while using my vpn connected to switzerland. I connected to the US servers and problem solved. Subconscious are loading and comments are showing.

Newpipe 0.21.0

**Comment by RobertKillick** [comment]
Having this same issue as described above from the UK, NewPipe 0.20.1

**Comment by TiA4f8R** [comment]
If you are living in the European Union, it's #5977.
Is it your case @Hogerys? If yes, please close this issue as a duplicate.

**Comment by Hogerys** [comment]
> "The issue is the same as #5977 but many people say the debug-app.zip apk worked for them, this didnt for me so i opened an issue too to be safe."

No.

@Blackfire-dev 's problem are the same for me. It carries over, but the hot feed not loading for him wasnt the result of this bug. I had it in the previous release but it got fixed with this new one. Then a few days later i got this loading error.

**Comment by TiA4f8R** [comment]
@Hogerys Ok, that's strange, what's happens if you open this video in the website in incognito mode several times with different sessions (like 10 or 15 tries with different incognito sessions, to be sure that cookies are cleared)? Do you get a prompt with something like `Before you continue to YouTube` on consent.youtube.com website?

If no, can you capture network traffic of the debug app by following https://github.com/TeamNewPipe/NewPipe/wiki/Additional-Debugging-Info and send the HAR to tnp@newpipe.schabi.org? Note that there is a bug in latest version of Chrome, try this version of Chromium https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win/827102/ (for Windows) if you encounter this bug or use Edge Chromium.
Thanks!

**Comment by Hogerys** [comment]
I get these prompts if i try to use Google stuff on computer. I do not use Chrome.

**Comment by Hogerys** [comment]
I also cannot search for stuff.

**Comment by Hogerys** [comment]
I cleared the captchas its solved @Blackfire-dev

**Comment by xibr** [comment]
## Exception
* __User Action:__ requested comments
* __Request:__ Start loading: https://www.youtube.com/watch?v=OvuNv834ja0
* __Content Country:__ KR
* __Content Language:__ ko
* __App Language:__ en
* __Service:__ YouTube
* __Version:__ 0.21.1
* __OS:__ Linux samsung/star2ltexx/star2lte:10/QP1A.190711.020/G965FXXUCFTK1:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.utils.Parser$RegexException: failed to find pattern "INNERTUBE_CONTEXT_CLIENT_NAME\":(.*?)[,}]"
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:74)
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup1(Parser.java:58)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.onFetchPage(YoutubeCommentsExtractor.java:137)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:54)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:34)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:25)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getCommentsInfo$7(ExtractorHelper.java:154)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$60N_-UL7E5eaxFaFO1bZZmnfwM8.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</details>
<hr>

**Comment by NilsIrl** [comment]
I had this issue for multiple weeks. Using a VPN (to the USA) (I live in the UK), solved it. Today I cleared the captchas and it was solved.
