### ISSUE TITLE
Unable to start activity ComponentInfo{org.schabi.newpipe/org.schabi.newpipe.MainActivity}: java.lang.NullPointerException: Attempt to get length of null array

### ISSUE THREAD

**Issue by TCH69** [TeamNewPipe/NewPipe#5996]
### Checklist

- [x] I am using the latest version - 0.21.0 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Open the app.

### Actual behaviour

The logo shows up for a second, then disappears and goes back to the launcher screen. A few seconds later the error screen comes up.
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.21.0
* __OS:__ Linux OPPO/CPH1605/CPH1605:5.1/LMY47I/1471871662:user/release-keys 6.0 - 23
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.schabi.newpipe/org.schabi.newpipe.MainActivity}: java.lang.NullPointerException: Attempt to get length of null array
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2687)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2753)
	at android.app.ActivityThread.access$1100(ActivityThread.java:186)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1609)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:238)
	at android.app.ActivityThread.main(ActivityThread.java:6016)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:937)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:798)
Caused by: java.lang.NullPointerException: Attempt to get length of null array
	at org.schabi.newpipe.util.StateSaver.clearStateFiles(StateSaver.java:302)
	at org.schabi.newpipe.MainActivity.initFragments(MainActivity.java:702)
	at org.schabi.newpipe.MainActivity.onCreate(MainActivity.java:149)
	at android.app.Activity.performCreate(Activity.java:6466)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2640)
	... 9 more

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: ColorOS 3.0.0i - Android 6.0
 - Device model: Oppo A39

**Comment by TCH69** [comment]
p/s sometimes it takes up to a minutes for the error screen to show up

**Comment by wangear** [comment]
Hello. May I assigned to me?

**Comment by TCH69** [comment]
I hope it'll work in the next update, for now I think I'll close this error

**Comment by TiA4f8R** [comment]
@TCH69 Please do not close issues when a bug happens and can be fixed with a PR until it's fixed. Can you try the APK in #5999 and see if it works for you? Comment your answer in this PR.
