### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by leomayer** [TeamNewPipe/NewPipe#5998]
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ AT
* __Content Language:__ de-AT
* __App Language:__ de_AT
* __Service:__ none
* __Version:__ 0.21.0
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Fragment VideoDetailFragment{ffcd192} (8e3b6fb5-bbde-4bb3-84d4-8d5d8863261c)} not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:805)
	at org.schabi.newpipe.error.ErrorActivity.reportErrorInSnackbar(ErrorActivity.java:98)
	at org.schabi.newpipe.fragments.BaseStateFragment.showSnackBarError(BaseStateFragment.java:211)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$2.onLoadingFailed(VideoDetailFragment.java:690)
	at com.nostra13.universalimageloader.core.LoadAndDisplayImageTask$2.run(LoadAndDisplayImageTask.java:360)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8387)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

```
</details>
<hr>

**Comment by leomayer** [comment]
Viewing

https://www.youtube.com/watch?v=dkw9qvOFS00 

On Huawei Matepad Pro(no Google!)

**Comment by mhmdanas** [comment]
Thanks for opening an issue! Please create a new issue that follows the template properly.
