### ISSUE TITLE
Crash when opening some links from comments.

### ISSUE THREAD

**Issue by saskadaniel** [TeamNewPipe/NewPipe#6010]
### Checklist

- [x] I am using the latest version - 0.21.0 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
Example video: https://www.youtube.com/watch?v=Ws0npSEwEOg
Go to the comment section and tap to the link inside a comment and the app will crash. It seems like it's specific to og-sg.net I can't reproduce with other links. The same link from the description works as it should.

### Actual behaviour
The app will crash.

### Expected behavior
The app should ask to choose an application to open the link.

### Screenshots/Screen recordings
![image](https://user-images.githubusercontent.com/44613177/113594621-39faba00-9638-11eb-84be-1c163a4e7c97.png)

## Exception
* _User Action:_ ui error
* _Request:_ ACRA report
* _Content Country:_ HU
* _Content Language:_ hu-HU
* _App Language:_ hu_HU
* _Service:_ none
* _Version:_ 0.21.0
* _OS:_ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1605)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:115)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at okhttp3.Dns$1.lookup(Dns.java:40)
	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:215)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
	at okhttp3.RealCall.execute(RealCall.java:93)
	at org.schabi.newpipe.DownloaderImpl.execute(DownloaderImpl.java:264)
	at org.schabi.newpipe.extractor.downloader.Downloader.get(Downloader.java:70)
	at org.schabi.newpipe.extractor.downloader.Downloader.get(Downloader.java:29)
	at org.schabi.newpipe.extractor.services.bandcamp.extractors.BandcampExtractorHelper.isSupportedDomain(BandcampExtractorHelper.java:95)
	at org.schabi.newpipe.extractor.services.bandcamp.linkHandler.BandcampChannelLinkHandlerFactory.onAcceptUrl(BandcampChannelLinkHandlerFactory.java:83)
	at org.schabi.newpipe.extractor.linkhandler.LinkHandlerFactory.acceptUrl(LinkHandlerFactory.java:100)
	at org.schabi.newpipe.extractor.StreamingService.getLinkTypeByUrl(StreamingService.java:291)
	at org.schabi.newpipe.extractor.NewPipe.getServiceByUrl(NewPipe.java:93)
	at org.schabi.newpipe.util.CommentTextOnTouchListener.handleUrl(CommentTextOnTouchListener.java:98)
	at org.schabi.newpipe.util.CommentTextOnTouchListener.onTouch(CommentTextOnTouchListener.java:69)
	at android.view.View.dispatchTouchEvent(View.java:14306)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
	at android.view.ViewGroup.dispat

**Comment by TiA4f8R** [comment]
@saskadaniel Can you reproduce this bug with the APK in #5523?

**Comment by succeedmr123** [comment]
New confirmation: it is still occuring in 0.21.5 release

android 10 in this case
the rest is reported to the dav directly via an e-mail named "Exception in NewPipe 0.21.5,similar to github #6010 ... (was more convenient in that particular moment (feel free to post here as I could not at the time being)

**Comment by litetex** [comment]
Should be fixed now with https://github.com/TeamNewPipe/NewPipe/commit/40317776063b55c52a6e86f36b1ad417ca623fec#diff-233e43e669885d26b604deab0b90eebc7734fa8a09336f5e663bcdaa3cdf1796
