### ISSUE TITLE
Search "something went wrong"

### ISSUE THREAD

**Issue by smellymoo** [TeamNewPipe/NewPipe#6043]
### Checklist

- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one feature request. I will open one issue for every feature I want to request.

#### Describe the feature you want
When a search fails because the catchya cache needs clearing:
- could the error page display a button to clear the catchya cache?
- could it automatically clear the catchya cache?

#### Is your feature request related to a problem? Please describe it
sometimes (#6019, #6009, #5987, #5979, etc)  search fails because the catchya cache needs clearing.

#### How will you/everyone benefit from this feature?
less crashes, less error reports. Happy users, happy developers.

**Comment by speendo** [comment]
I also still have this issue even after updating to 0.21.1

Crash Report:

## Exception

* __User Action:__ searched

* __Request:__ pen pineapple apple pen

* __Content Country:__ AT

* __Content Language:__ en

* __App Language:__ de_DE

* __Service:__ YouTube

* __Version:__ 0.21.1

* __OS:__ Linux Android 10 - 29

<details><summary><b>Crash log </b></summary><p>

```

org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get ytInitialData

	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getInitialData(YoutubeParsingHelper.java:278)

	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.extractClientVersionAndKey(YoutubeParsingHelper.java:296)

	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getKey(YoutubeParsingHelper.java:374)

	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getNewNextPageFrom(YoutubeSearchExtractor.java:233)

	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getInitialPage(YoutubeSearchExtractor.java:127)

	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)

	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:60)

	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:30)

	at org.schabi.newpipe.util.ExtractorHelper.lambda$searchFor$0(ExtractorHelper.java:80)

	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$qyxpuXgomWa-cbONQns-pd7zxm0.call(Unknown Source:8)

	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)

	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)

	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)

	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)

	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)

	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)

	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)

	at java.lang.Thread.run(Thread.java:919)

Caused by: org.schabi.newpipe.extractor.utils.Parser$RegexException: failed to find pattern "var\s*ytInitialData\s*=\s*(\{.*?\});"

	at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:74)

	at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:63)

	at org.schabi.newpipe.extractor.utils.Parser.matchGroup1(Parser.java:54)

	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getInitialData(YoutubeParsingHelper.java:274)

	... 20 more

```

</details>

<hr>

**Comment by mhmdanas** [comment]
Those issues are all duplicates of #5977; the issue is not about CAPTCHAs, but about a cookie consent agreement for EU countries.
