### ISSUE TITLE
solving captcha won't show video anymore

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [TeamNewPipe/NewPipe#6055]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour

The video is not displayed, instead it shows the "solve" button. Pressing retry won't change it.
Clearing recaptcha cookies won't fix the problem.

### Expected behavior

?

### Device info

 - Android version/Custom ROM version: Lollipop
 - Device model: HTC ONE
- Additional Info: ProtonVPN / NL IP Address

**Comment by trinity-geology-unstable** [comment]
I am experiencing this issue also. When I select a video to watch I am given the option to solve a captcha, but after I do that I am returned to the same screen and asked to solve a captcha again. Repeat ad-infinitum.

I am also running a custom ROM and using a commercial VPN provider.

**Comment by PulkitBhardwaj1** [comment]
Same issue

**Comment by Himanshu-kumar-gupta** [comment]
I am facing the same issue. Whenever I open a video it is showing to solve captcha or retry and after I solved it, I am having the same screen to solve and retry once more.

**Comment by hp8wvvvgnj6asjm7** [comment]
I haven't been able to watch any videos with newpipe for days now ;(

**Comment by d4f5409d** [comment]
Same issue, after I searched something after solving captcha it did drop me this error:

## Exception
* __User Action:__ searched
* __Request:__ **randomized**
* __Content Country:__ EN
* __Content Language:__ en
* __App Language:__ en_UK
* __Service:__ YouTube
* __Version:__ 0.21.1
* __OS:__ Linux samsung/dreamltexx/dreamlte:9 [Samsung S8, Android 9]
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get ytInitialData
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getInitialData(YoutubeParsingHelper.java:278)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.extractClientVersionAndKey(YoutubeParsingHelper.java:296)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getKey(YoutubeParsingHelper.java:374)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getNewNextPageFrom(YoutubeSearchExtractor.java:233)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.getInitialPage(YoutubeSearchExtractor.java:127)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:60)
	at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:30)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$searchFor$0(ExtractorHelper.java:80)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$qyxpuXgomWa-cbONQns-pd7zxm0.call(Unknown Source:8)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: org.schabi.newpipe.extractor.utils.Parser$RegexException: failed to find pattern "var\s*ytInitialData\s*=\s*(\{.*?\});"
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:74)
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup(Parser.java:63)
	at org.schabi.newpipe.extractor.utils.Parser.matchGroup1(Parser.java:54)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getInitialData(YoutubeParsingHelper.java:274)
	... 20 more

```
</details>
<hr>

**Comment by d4f5409d** [comment]
For me it's okay now. It does not show me that bug anymore.

**Comment by anedroid** [comment]
I experience the same issue. I used to think that's because I use TOR, but there's problem with application - if I open same video in Firefox or YouTube Vanced, playing's starting immediately without need to solve captcha.

**Comment by isor1** [comment]
Same problem! Reinstalling previous version works fine btw.

**Comment by TiA4f8R** [comment]
@boringhexi You're welcome! This fix will be included in the next release.
