### ISSUE TITLE
Landscape Mode

### ISSUE THREAD

**Issue by free-tinker** [TeamNewPipe/NewPipe#6057]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour

I was trying landscape mode on my galaxy grand duos phone but only black screen. The sound and player works in landscape mode. When back to portrait mode, the app becomes laggy and i have to force it close.
I just found another issue. When i switch to menu switcher and go back to the app, even in portrait mode, the screen blank but player and sound work as well as in landscape mode and then exiting by itself. When i try to open the app again, it shows error log (I put the error log on logs part).

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.2
* __OS:__ Linux Android 7.1.2 - 25
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to destroy activity {org.schabi.newpipe/org.schabi.newpipe.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.IWindowSession.performDeferredDestroy(android.view.IWindow)' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4240)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4258)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4532)
	at android.app.ActivityThread.-wrap19(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1502)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.IWindowSession.performDeferredDestroy(android.view.IWindow)' on a null object reference
	at android.view.SurfaceView.updateWindow(SurfaceView.java:654)
	at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:247)
	at android.view.View.dispatchDetachedFromWindow(View.java:15555)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3179)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3179)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3179)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3179)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3179)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3179)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3179)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4715)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4689)
	at android.view.ViewGroup.removeView(ViewGroup.java:4620)
	at androidx.fragment.app.FragmentContainerView.removeView(FragmentContainerView.java:317)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1250)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
	at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:2609)
	at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:330)
	at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:365)
	at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:242)
	at org.schabi.newpipe.MainActivity.onDestroy(MainActivity.java:460)
	at android.app.Activity.performDestroy(Activity.java:6886)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1154)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4227)
	... 10 more

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: lineage os 14.1-20180326-UNOFFICIAL-i9082
 - Device model: GT-I9082

**Comment by AhmedHalim96** [comment]
Same problem using 0.21.0`## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.0
* __OS:__ Linux OPPO/CPH1803/CPH1803:8.1.0/OPM1.171019.026/1595211000:user/release-keys 8.1.0 - 27
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.schabi.newpipe/org.schabi.newpipe.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment org.schabi.newpipe.fragments.EmptyFragment: could not find Fragment constructor
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2995)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3073)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5062)
	at android.app.ActivityThread.-wrap18(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1780)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:198)
	at android.app.ActivityThread.main(ActivityThread.java:7055)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:523)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:836)
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment org.schabi.newpipe.fragments.EmptyFragment: could not find Fragment constructor
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:563)
	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:390)
	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:74)
	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2454)
	at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1706)
	at androidx.fragment.app.Fragment.onCreate(Fragment.java:1683)
	at org.schabi.newpipe.BaseFragment.onCreate(BaseFragment.java:55)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.onCreate(VideoDetailFragment.java:279)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2684)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1175)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
	at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2571)
	at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:236)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:315)
	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
	at org.schabi.newpipe.MainActivity.onCreate(MainActivity.java:139)
	at android.app.Activity.performCreate(Activity.java:7314)
	at android.app.Activity.performCreate(Activity.java:7305)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2948)
	... 10 more
Caused by: java.lang.NoSuchMethodException: <init> []
	at java.lang.Class.getConstructor0(Class.java:2320)
	at java.lang.Class.getConstructor(Class.java:1725)
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:548)
	... 34 more

```
</details>
<hr>
`

**Comment by rancidfrog** [comment]
Crash when rotate device before video loads when sharing
### Steps to reproduce the bug

1. Open youtube video in browser
2. Share video to newpipe video mode
3. Rotate device before video loads (Bad connection makes it worse as it takes longer to load video giving it more time to crash, as if the video loads before rotating app does not crash)
4. App crashes when you rotate device before youtube parses and loads video




### Actual behaviour

App crashes


### Expected behavior

Switch to landscape mode without crashing


### Screenshots/Screen recordings






### Logs




## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ UM
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.21.1
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.schabi.newpipe/org.schabi.newpipe.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment org.schabi.newpipe.fragments.EmptyFragment: could not find Fragment constructor
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5279)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5187)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment org.schabi.newpipe.fragments.EmptyFragment: could not find Fragment constructor
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:563)
	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:390)
	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:74)
	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2454)
	at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1706)
	at androidx.fragment.app.Fragment.onCreate(Fragment.java:1683)
	at org.schabi.newpipe.BaseFragment.onCreate(BaseFragment.java:55)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.onCreate(VideoDetailFragment.java:279)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2684)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1175)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
	at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2571)
	at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:236)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:315)
	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
	at org.schabi.newpipe.MainActivity.onCreate(MainActivity.java:139)
	at android.app.Activity.performCreate(Activity.java:7824)
	at android.app.Activity.performCreate(Activity.java:7813)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	... 13 more
Caused by: java.lang.NoSuchMethodException: org.schabi.newpipe.fragments.EmptyFragment.<init> []
	at java.lang.Class.getConstructor0(Class.java:2332)
	at java.lang.Class.getConstructor(Class.java:1728)
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:548)
	... 37 more

```
</details>
<hr>




### Device info

 - Android version/Custom ROM version: Android 10 | LineageOS

**Comment by TiA4f8R** [comment]
@AhmedHalim96 @rancidfrog The crashes you posted are duplicates of #5941. Please do not post this again, it's a know issue.
