### ISSUE TITLE
Play Queue screen crashes on split-screen resize

### ISSUE THREAD

**Issue by boringhexi** [TeamNewPipe/NewPipe#6078]
### Checklist

- [x] I am using the latest version - 0.21.1 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Open another app that supports split-screen (e.g. Clock).
2. Open NewPipe and start a video/playlist/anything.
3. Go to the NewPipe play queue. To do this, I tap the NewPipe media-playing notification in my notification center.
4. Enter split-screen with the other app. To do this, I enter the app switcher, tap the icon at the top of the NewPipe app, choose "Split screen", then choose the other app.
5. At this point, NewPipe should be in split-screen with the other app. Now adjust/resize the border between the two apps, and NewPipe should crash.
 

### Actual behaviour

NewPipe crashes.

### Expected behavior

NewPipe should adjust to the size of the split-screen border.

### Screenshots/Screen recordings

Screenshot of split-screen before I adjust the split-screen border and cause the crash. 

![Screenshot_20210414-095502](https://user-images.githubusercontent.com/36807140/114724252-5c13cc80-9d09-11eb-8bd6-ba8d5d2266d6.png)

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.1
* __OS:__ Linux motorola/sofia_trac/sofia:10/QPM30.80-63-6-8/a0f3f:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.exoplayer2.PlaybackParameters org.schabi.newpipe.player.Player.getPlaybackParameters()' on a null object reference
	at org.schabi.newpipe.player.PlayQueueActivity.onCreateOptionsMenu(PlayQueueActivity.java:106)
	at android.app.Activity.onCreatePanelMenu(Activity.java:4085)
	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:324)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3070)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:456)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:57)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
	at android.view.Choreographer.doFrame(Choreographer.java:721)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:241)
	at android.app.ActivityThread.main(ActivityThread.java:7617)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: Android 10
 - Device model: Moto G Power (XT2041DL)

**Comment by litetex** [comment]
Fixed by https://github.com/TeamNewPipe/NewPipe/pull/8244
