### ISSUE TITLE
Exception when opening a link

### ISSUE THREAD

**Issue by leomayer** [TeamNewPipe/NewPipe#6186]
## Exception
* __User Action:__ requested playlist
* __Request:__ Start loading: https://music.youtube.com/watch?v=icuULD-sz1Y&list=RDAMVMiGg4oYGo5Kk
* __Content Country:__ AT
* __Content Language:__ de-AT
* __App Language:__ de_AT
* __Service:__ YouTube
* __Version:__ 0.21.2
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ContentNotAvailableException: Got error: "This playlist type is unviewable."
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.defaultAlertsCheck(YoutubeParsingHelper.java:765)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubePlaylistExtractor.onFetchPage(YoutubePlaylistExtractor.java:58)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:54)
	at org.schabi.newpipe.extractor.playlist.PlaylistInfo.getInfo(PlaylistInfo.java:30)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getPlaylistInfo$9(ExtractorHelper.java:170)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$RLOrwix0kCDfcc_WpFBc8DTJw0Q.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

```
</details>
<hr>

**Comment by TiA4f8R** [comment]
That's strange, it works on the desktop website.
Please follow the issue template when you open an issue next time.

**Comment by leomayer** [comment]
Stilll I cannot follow the link. 

Note: I have a Huawei Matepad Pro without any kind of Google Services installed. Is it required to have other libs installed?

**Comment by TiA4f8R** [comment]
> I have a Huawei Matepad Pro without any kind of Google Services installed. Is it required to have other libs installed?

No, because we are parsing the JSON website data, so it is not needed. The app doesn't require at all the Google Services to work.

This error occurs beacuse the app tries to view a mix playlist with the youtube.com website without the video id: mix playlists don't exist without a video. You can the check on the YouTube website (https://www.youtube.com/watch?v=icuULD-sz1Y&list=RDAMVMiGg4oYGo5Kk), you will get the error message: `This playlist type is unviewable.`.

**Comment by leomayer** [comment]
Hmmm... If I open the link on my mobile with installed YouTube than YouTube
can open it.... Hmm...

TiA4f8R ***@***.***> schrieb am So., 9. Mai 2021, 12:51:

**Comment by chrstfer** [comment]
@TiA4f8R is the fact that that link opened fine for me with most recent releaze 0.21.7 evidence this issue is fixed and should be closed?

**Comment by litetex** [comment]
We got a similar problem in #7344:
Link: https://www.youtube.com/watch?v=Se45aW5IElM&list=PU2AnkjPy95aL0X-q9MPm2-Q
