### ISSUE TITLE
Crash when opening very quickly the search window after NewPipe launch

### ISSUE THREAD

**Issue by Massedil** [TeamNewPipe/NewPipe#6231]
### Checklist

- [x] I am using the latest version - 0.21.2 
- [x I checked, and I have found a closed issue (#5812), but the problem is still here.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Open NewPipe and very quickly click on the search icon as soon as it appears

### Actual behaviour

NewPipe crashes.

### Expected behavior

No crash and possibility to search !

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ FR
* __Content Language:__ fr
* __App Language:__ fr_FR
* __Service:__ none
* __Version:__ 0.21.2
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.RelativeLayout org.schabi.newpipe.databinding.PlaylistHeaderBinding.getRoot()' on a null object reference
at org.schabi.newpipe.fragments.list.playlist.PlaylistFragment.handleResult(PlaylistFragment.java:277)
at org.schabi.newpipe.fragments.list.playlist.PlaylistFragment.handleResult(PlaylistFragment.java:65)
at org.schabi.newpipe.fragments.list.BaseListInfoFragment.lambda$startLoading$0(BaseListInfoFragment.java:146)
at org.schabi.newpipe.fragments.list.BaseListInfoFragment.lambda$startLoading$0$BaseListInfoFragment(Unknown Source:0)
at org.schabi.newpipe.fragments.list.-$$Lambda$BaseListInfoFragment$Gn1fP3-8OJnktT5gkmUmbW-egTg.accept(Unknown Source:4)
at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7356)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: Android 10 / LineageOS 17.1
 - Device model: Samsung Galaxy S5

**Comment by sauravrao637** [comment]
Hi! @Massedil 
Thanks for reporting the issue :) till we fix the issue please slow down your reflexes ;)
#### Now to the developers 
The reason behind this bug is obvious that the headerBinding is still inflating (idts) or  never been called to inflate yet and thus is null.
I  don't think just doing null check here is enough  because the ui work must be done after headerBinding is inflated , so what we can do is check if it's null we call getHeaderBinding and then proceed forward with ui work but I doubt if this is the best approach.
So I would like to know if this is a good approach and I proceed further or there is a better one?

**Comment by mhmdanas** [comment]
@sauravrao637 sorry, I'm not very familiar with NewPipe's code (or Android development in general). You'd probably be better served by asking in the IRC channel (see https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md#communication).

**Comment by vhouriet** [comment]
Hey, maybe I'm too slow, but I can't reproduce this behaviour. Is it still a problem ?

**Comment by Massedil** [comment]
I can't reproduce too. I seems to be corrected ! Thanks !

**Comment by Massedil** [comment]
In fact, it still crashes in the latest version. 


## Exception
* __User Action:__ get suggestions
* __Request:__ 
* __Content Country:__ FR
* __Content Language:__ fr
* __App Language:__ fr_FR
* __Service:__ YouTube
* __Version:__ 0.21.15
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to read from field 'androidx.recyclerview.widget.RecyclerView org.schabi.newpipe.databinding.FragmentSearchBinding.suggestionsList' on a null object reference
	at org.schabi.newpipe.fragments.list.search.SearchFragment.handleSuggestions(SearchFragment.java:973)
	at org.schabi.newpipe.fragments.list.search.SearchFragment.lambda$initSuggestionObserver$13(SearchFragment.java:814)
	at org.schabi.newpipe.fragments.list.search.SearchFragment.$r8$lambda$0KRipyJJS1-v4wlqLTlO9OsWksw(Unknown Source:0)
	at org.schabi.newpipe.fragments.list.search.SearchFragment$$ExternalSyntheticLambda11.accept(Unknown Source:4)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>
<hr>

**Comment by Massedil** [comment]
Something related to this issue that can help. 

On my SM-G900F, Android 11, LineageOS 18.1 : 
- With Parameters > Accessibility > Disable animations = On, the crash occurs.
- With Parameters > Accessibility > Disable animations = Off, the crash does not occurs.

To reproduce the crash : "Open NewPipe and very quickly click on the search icon as soon as it appears".

**Comment by Massedil** [comment]
> Hello, does this issue still occur on curretly latest v0.27.2?

I tried on 2 devices and can't reproduce with latest version.
