### ISSUE TITLE
Crash on minimizing

### ISSUE THREAD

**Issue by yashpalgoyal1304** [TeamNewPipe/NewPipe#6300]
### Checklist

- [x] I am using the latest version - 0.21.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

i was just watching a video in the main and minimised (press the home/circle button).

### Actual behaviour

the crash screen popped up.

### Expected behavior

Nothing specific

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ DE
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.2
* __OS:__ Linux Android 7.0 - 24
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.IWindowSession.performDeferredDestroy(android.view.IWindow)' on a null object reference
	at android.view.SurfaceView.updateWindow(SurfaceView.java:644)
	at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:251)
	at android.view.View.dispatchWindowVisibilityChanged(View.java:10293)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1291)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1291)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1291)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1291)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1291)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1291)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1291)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1291)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1291)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1291)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1291)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1291)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1291)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1291)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1291)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1537)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1249)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6331)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
	at android.view.Choreographer.doCallbacks(Choreographer.java:683)
	at android.view.Choreographer.doFrame(Choreographer.java:619)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6146)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version:
 - Device model:

------
source: fdroid official repo

**Comment by litetex** [comment]
Same exception as in #6301

Assuming this is fixed now.
