### ISSUE TITLE
Crash on sharing via main players button

### ISSUE THREAD

**Issue by yashpalgoyal1304** [TeamNewPipe/NewPipe#6301]
### Checklist

- [x] I am using the latest version - 0.21.2 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

i was watching a video in the main screen and clicked the share button in player ui

### Actual behaviour

crashed

### Expected behavior

share dialog to open

### Logs

Clicked the share button when in a video main ui
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ DE
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.2
* __OS:__ Linux Android 7.0 - 24
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.IWindowSession.performDeferredDestroy(android.view.IWindow)' on a null object reference
	at android.view.SurfaceView.updateWindow(SurfaceView.java:644)
	at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:251)
	at android.view.View.dispatchWindowVisibilityChanged(View.java:10293)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1291)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1291)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1291)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1291)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1291)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1291)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1291)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1291)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1291)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1291)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1291)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1291)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1291)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1291)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1291)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1537)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1249)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6331)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
	at android.view.Choreographer.doCallbacks(Choreographer.java:683)
	at android.view.Choreographer.doFrame(Choreographer.java:619)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6146)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version:
 - Device model:

-----
source of downloading: fdroid main repo

**Comment by iamthesenate1** [comment]
Can you please share the link of the respective video?

**Comment by yashpalgoyal1304** [comment]
@iamthesenate1 i think it was this one: [NSFW](https://www.youtube.com/watch?v=G-T2EEOn5nM)

**Comment by iamthesenate1** [comment]
You must Activate Age Restricted content in settings.
![IMG_20210514_200821](https://user-images.githubusercontent.com/77978836/118305130-3e947700-b4f0-11eb-8413-026ba6718abf.jpg)

**Comment by iamthesenate1** [comment]
Works for me on that video too so this must be device specific.
Did you give Newpipe all the necessary permissions? (Had some wierdness without all of them enabled in the past)

**Comment by yashpalgoyal1304** [comment]
agw restricted is already enabled. and even if it werent, then too, crash would still be a mistake :)

It has asked only for 2 permissions,  and since i have uninstalled the fdroid instance and switched to github/newpipe custom repo release now,  dont know with full certainity, but i am pretty sure i had enabled both those (storage and draw overother apps)

**Comment by yashpalgoyal1304** [comment]
also, have edited the comment in whicb i shared the link

**Comment by iamthesenate1** [comment]
There are some additional permitions in the settings, that you sometimes aren't asked about.

**Comment by iamthesenate1** [comment]
I tried queueing it too. No crash.

**Comment by iamthesenate1** [comment]
More users should test this, but I think this issue should be tagged as device/software specific.

**Comment by yashpalgoyal1304** [comment]
0. Permissions ss
[Imagepipe_0](https://user-images.githubusercontent.com/19423063/118307861-e5850d00-b508-11eb-87fb-a82806315ba2.png)
1. doesnt crash log help somehow?
2. What is the source of ur fdroid install? (like gh/fdroid/self etc)

**Comment by iamthesenate1** [comment]
I installed it as an apk so this might be tied to fdroid builds?

**Comment by yashpalgoyal1304** [comment]
yeah, am suspect that fdroid build have smth missing in the process - thats why they crash a lot. I shared rhis concern on #newpipe too, buti guess nobody was active a-that-m.

I was using v20.8 from gh, faced no crash in months, just today used v21.2 from fdroid, already crashes twice. And before v20.8 i used fdroid builds too, newpipe used to crash a lot back then too.

Convinced that fdroid official repo builds are unusably ubstable for me, i made no delays to switch to newpipe custom fdroid repo after filling these issues.

**Comment by yashpalgoyal1304** [comment]
clarification: i didnt try to reproduce these issues, u might considered these as random bugs. i just filed it in hopes that maybe crash log can help in finding some behaviour and avoiding it in future.

**Comment by litetex** [comment]
> I was using v20.8 from gh, faced no crash in months
> ...just today used v21.2 from fdroid, already crashed twice

Looks like this is fixed.

**Comment by yashpalgoyal1304** [comment]
> Looks like this is fixed.
Can u mention the related commits?

**Comment by litetex** [comment]
Oh whoops, I read ``v20.8`` as ``v21.8`` 😆 

Anyway, is this still a problem?
If yes, reopen the issue please 😄

**Comment by yashpalgoyal1304** [comment]
> also please fill in `Device info`

ahw, i was wondering why havent i filled that. but then i saw this: "Please fill this out when you dont provide logs"

![image](https://user-images.githubusercontent.com/19423063/153539167-8e19eed2-3057-484a-9510-1a3ca18e3c6e.png)
