### ISSUE TITLE
Age-Gated Videos Not Playing [Again]

### ISSUE THREAD

**Issue by johnth3doe** [TeamNewPipe/NewPipe#6348]
### Checklist

- [x] I am using version - 0.21.0 (I am avoiding the 0.21.2 update because of the behavior mentioned in #6179 [which I understand was introduced in that version]) 
- [x] I checked, found issue #4161, then realized that I had altogether forgot to reply when the issue was resolved (at that time) and it was closed. Therefore opening this one in its place. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Expected behaviour
All videos can be played without any issue or errors.

### Actual behavior
As explained above, and in the previous mentioned issue; any [age-restricted] video (including the shown example) results in a sad face [unplayable].

### Screenshots/Screen recordings
N/A

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=n79KoPVeCJg
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en
* __Service:__ YouTube
* __Version:__ 0.21.0
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException
	at java.io.StringReader.<init>(StringReader.java:47)
	at com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.fetchVideoInfoPage(YoutubeStreamExtractor.java:801)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:730)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:54)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:68)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:115)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$YTHJjScxCJNO1LTCqs3IKy35iyY.call(lambda)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

```
</details>
<hr>

### Additional Notes

1) I have made sure that the necessary settings are respectively set to allow viewing the content in question.
2) The issue (in this instance) has surfaced since the last 2 or 3 days, before which NewPipe was working normally.

Thank you for your time, patience and consideration.
___
PS. I would like it to be known that I am genuinely sorry to @opusforlife2 because, in lieu of their respectful patience, I showed underwhelming etiquette in the absence of a response in the previous instance of this issue.
PPS. I understand that, in general, the checklist asks to check that there are no other issues [open or closed] therefore I would also suggest that if need be, consider re-opening issue #4161 (since this satisfies the criteria as per https://github.com/TeamNewPipe/NewPipe/issues/4161#issuecomment-723544041? and the checklist.

**Comment by jeromegoldwin8695** [comment]
Same problem here but this is the latest version

**Comment by Imericxu** [comment]
Reproduced bug on 0.21.2 with this [video](https://www.youtube.com/watch?v=61Ev-YvBw2c).

**Comment by XiangRongLin** [comment]
will be fixed by https://github.com/TeamNewPipe/NewPipeExtractor/pull/629

**Comment by SameenAhnaf** [comment]
Still age-restricted videos like [this] (https://www.youtube.com/watch?v=61Ev-YvBw2c). don't load on version 0.21.3. Reopening this issue makes sense.

**Comment by XiangRongLin** [comment]
@SameenAhnaf are the Error logs the same? if not you can open a new issue with the new logs

**Comment by opusforlife2** [comment]
@johnth3doe Absolutely no issues, mate. ✌️ This is FOSS, it's kind of understood that if someone doesn't respond, it probably means they don't have the time. Even bug reporters are volunteers, after all. There is nothing to be apologetic about.
