### ISSUE TITLE
UI crash

### ISSUE THREAD

**Issue by ShravanBhat** [TeamNewPipe/NewPipe#6354]
java.lang.IllegalArgumentException: Invalid offset: -1. Valid range is [0, 2148]
	at android.text.method.WordIterator.checkOffsetIsValid(WordIterator.java:380)
	at android.text.method.WordIterator.isBoundary(WordIterator.java:101)
	at android.widget.Editor$SelectionStartHandleView.positionAtCursorOffset(Editor.java:4371)
	at android.widget.Editor$HandleView.updatePosition(Editor.java:3819)
	at android.widget.Editor$PositionListener.onPreDraw(Editor.java:2517)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2412)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1321)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6732)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
	at android.view.Choreographer.doCallbacks(Choreographer.java:696)
	at android.view.Choreographer.doFrame(Choreographer.java:631)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5740)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:766)
-------------------------------------

How to reproduce?
A- 
https://www.youtube.com/watch?v=rqSYgzF9a2I
Go to description section
Long press on any time stamp to that copy,select,etc option opens .
Then press anywhere at the side and app crashes

**Comment by TiA4f8R** [comment]
Please open an new issue that follows the bug report template properly.
