### ISSUE TITLE
Background audio repetition button not working and sending error

### ISSUE THREAD

**Issue by Thewisem** [TeamNewPipe/NewPipe#6401]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to newpipe and press a video
2. Press on a video
3. Let it play in the background
4. Open notificaion and click repetition
5. Open newpipe and see error

### Actual behaviour

Error

### Expected behavior

Song to be repeated indefinitely

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.21.3
* __OS:__ Linux Android 7.1.1 - 25
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Error receiving broadcast Intent { act=org.schabi.newpipe.player.MainPlayer.REPEAT flg=0x10000010 launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } bqHint=0 bnds=[376,187][424,235] } in org.schabi.newpipe.player.Player$3@b531747
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1195)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6823)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
Caused by: java.lang.ClassCastException: android.widget.ImageButton cannot be cast to androidx.appcompat.widget.AppCompatImageButton
	at org.schabi.newpipe.player.Player.onRepeatModeChanged(Player.java:2257)
	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$setRepeatMode$2(ExoPlayerImpl.java:564)
	at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$rgrcbaqP9Y8LgzdByBnAfUO4ydU.invokeListener(lambda)
	at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:279)
	at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:1498)
	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$notifyListeners$6(ExoPlayerImpl.java:1318)
	at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$b59raXxaB-trjwE5bgpZInm1QnU.run(lambda)
	at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:1328)
	at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:1318)
	at com.google.android.exoplayer2.ExoPlayerImpl.setRepeatMode(ExoPlayerImpl.java:564)
	at com.google.android.exoplayer2.SimpleExoPlayer.setRepeatMode(SimpleExoPlayer.java:1636)
	at org.schabi.newpipe.player.Player.setRepeatMode(Player.java:2247)
	at org.schabi.newpipe.player.Player.onRepeatClicked(Player.java:2226)
	at org.schabi.newpipe.player.Player.onBroadcastReceived(Player.java:1118)
	at org.schabi.newpipe.player.Player.access$200(Player.java:190)
	at org.schabi.newpipe.player.Player$3.onReceive(Player.java:1055)
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1185)
	... 7 more

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by jachhj** [comment]
same for me being on android 7. will my crash report be of any help? I can add it in chat i guess.

**Comment by jachhj** [comment]
app crashes when playing music in background and trying to click the replay button to get the song on replay. as soon as it is pressed it crashes.
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ NL
* __Content Language:__ en
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.21.5
* __OS:__ Linux samsung/gts28vewifixx/gts28vewifi:7.0/NRD90M/T713XXU2BSA1:user/release-keys 7.0 - 24
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Error receiving broadcast Intent { act=org.schabi.newpipe.player.MainPlayer.REPEAT flg=0x10000010 launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } bqHint=0 bnds=[752,537][848,633] } in org.schabi.newpipe.player.Player$3@56015ee
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1195)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6780)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1500)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1390)
Caused by: java.lang.ClassCastException: android.widget.ImageButton cannot be cast to androidx.appcompat.widget.AppCompatImageButton
	at org.schabi.newpipe.player.Player.onRepeatModeChanged(Player.java:2257)
	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$setRepeatMode$2(ExoPlayerImpl.java:564)
	at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$rgrcbaqP9Y8LgzdByBnAfUO4ydU.invokeListener(lambda)
	at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:279)
	at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:1498)
	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$notifyListeners$6(ExoPlayerImpl.java:1318)
	at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$b59raXxaB-trjwE5bgpZInm1QnU.run(lambda)
	at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:1328)
	at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:1318)
	at com.google.android.exoplayer2.ExoPlayerImpl.setRepeatMode(ExoPlayerImpl.java:564)
	at com.google.android.exoplayer2.SimpleExoPlayer.setRepeatMode(SimpleExoPlayer.java:1636)
	at org.schabi.newpipe.player.Player.setRepeatMode(Player.java:2247)
	at org.schabi.newpipe.player.Player.onRepeatClicked(Player.java:2226)
	at org.schabi.newpipe.player.Player.onBroadcastReceived(Player.java:1118)
	at org.schabi.newpipe.player.Player.access$200(Player.java:190)
	at org.schabi.newpipe.player.Player$3.onReceive(Player.java:1055)
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1185)
	... 7 more

```
</details>
<hr>

**Comment by jachhj** [comment]
well strangely enough, the bug is resolved for me, did not update the app. 
I can now press the replay button without any crashes.

**Comment by GabrielPivot** [comment]
how?

**Comment by GabrielPivot** [comment]
Why are they mentioning this issue if it's not even solved?

**Comment by opusforlife2** [comment]
> 
> 
> well strangely enough, the bug is resolved for me, did not update the app.
> I can now press the replay button without any crashes.

@jachhj Did you change any setting?

**Comment by AudricV** [comment]
Is it still an issue on 0.26.1?
