### ISSUE TITLE
App crashes if opened after a long time (booted from RAM?)

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipe#6407]
### Checklist

- [x] I am using the latest version - 0.21.3 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

Not reproducible reliably, but:

1. Open some video page.
2. Leave Newpipe for a long time, and use other apps.
3. Come back to Newpipe.

### Actual behaviour

Crash. Caught by Scoop. Newpipe's error activity doesn't open for this.

### Expected behavior

Resume Newpipe exactly how you left it.

### Logs

```
FATAL EXCEPTION: main
Process: org.schabi.newpipe, PID: 7132
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.schabi.newpipe/org.schabi.newpipe.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment org.schabi.newpipe.fragments.EmptyFragment: could not find Fragment constructor
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment org.schabi.newpipe.fragments.EmptyFragment: could not find Fragment constructor
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:563)
	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:390)
	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:74)
	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2454)
	at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1706)
	at androidx.fragment.app.Fragment.onCreate(Fragment.java:1683)
	at org.schabi.newpipe.BaseFragment.onCreate(BaseFragment.java:55)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.onCreate(VideoDetailFragment.java:279)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2684)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1175)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
	at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2571)
	at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:236)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:315)
	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
	at org.schabi.newpipe.MainActivity.onCreate(MainActivity.java:141)
	at android.app.Activity.performCreate(Activity.java:7824)
	at android.app.Activity.performCreate(Activity.java:7813)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	... 11 more
Caused by: java.lang.NoSuchMethodException: org.schabi.newpipe.fragments.EmptyFragment.<init> []
	at java.lang.Class.getConstructor0(Class.java:2332)
	at java.lang.Class.getConstructor(Class.java:1728)
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:548)
	... 35 more
```

### Device info

 - Android version/Custom ROM version: Android 10 (LOS 17.1)

**Comment by mhmdanas** [comment]
The crash looks the similar to/ the same as #5941's (haven't checked it thoroughly).

**Comment by opusforlife2** [comment]
No rotation involved in my case.

**Comment by mhmdanas** [comment]
Well, yes, but I thought it might be related.

**Comment by SameenAhnaf** [comment]
Apk from #6242 seems to solve the bug me. I think, you should try that apk.

**Comment by opusforlife2** [comment]
Since this bug is so sporadic, I would be better off testing the release version and see if I encounter it again. Either Newpipe will crash (this bug) or I will see #6408.

**Comment by mbe24** [comment]
If I open the app after a long time I get a NPE.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.3
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int org.schabi.newpipe.player.playqueue.PlayQueue.getIndex()' on a null object reference
	at org.schabi.newpipe.player.Player.onCompleted(Player.java:2177)
	at org.schabi.newpipe.player.Player.changeState(Player.java:2016)
	at org.schabi.newpipe.player.Player.onPlayerStateChanged(Player.java:1936)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$6(ExoPlayerImpl.java:1443)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$6$ExoPlayerImpl$PlaybackInfoUpdate(Unknown Source:0)
	at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$PlaybackInfoUpdate$b8AtGdawGxQCz-_rX1H1__vkxF4.invokeListener(Unknown Source:2)
	at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:279)
	at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:1498)
	at com.google.android.exoplayer2.ExoPlayerImpl.access$100(ExoPlayerImpl.java:56)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.run(ExoPlayerImpl.java:1440)
	at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:1328)
	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:956)
	at com.google.android.exoplayer2.ExoPlayerImpl.prepare(ExoPlayerImpl.java:320)
	at com.google.android.exoplayer2.SimpleExoPlayer.prepare(SimpleExoPlayer.java:1402)
	at com.google.android.exoplayer2.DefaultControlDispatcher.dispatchPrepare(DefaultControlDispatcher.java:57)
	at com.google.android.exoplayer2.ext.mediasession.MediaSessionConnector$ComponentListener.onPlay(MediaSessionConnector.java:1151)
	at android.support.v4.media.session.MediaSessionCompat$Callback$MediaSessionCallbackApi21.onPlay(MediaSessionCompat.java:1614)
	at android.media.session.MediaSession$Callback.onMediaButtonEvent(MediaSession.java:928)
	at android.support.v4.media.session.MediaSessionCompat$Callback$MediaSessionCallbackApi21.onMediaButtonEvent(MediaSessionCompat.java:1604)
	at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1566)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```
</details>
<hr>

**Comment by mhmdanas** [comment]
@mbe24 that sounds like #6233.

**Comment by opusforlife2** [comment]
The app no longer crashes for me. Instead, in the worst case scenario of complete removal from RAM, it opens the home page, if nothing else.
