### ISSUE TITLE
crash when switching to fullscreen from floating window

### ISSUE THREAD

**Issue by jerome-tgl** [TeamNewPipe/NewPipe#6462]
- [x] I am using the latest version - 0.21.4
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. In app preferences, set  video/audio behavior "open as" "floaitbg window"
2. Open a YouTube link from web browser (should open as floating window)
3. Tap on the full screen/ expand button in top right corner of floating button 

### Actual behaviour
Bug report screen with the following details

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en
* __App Language:__ fr_FR
* __Service:__ none
* __Version:__ 0.21.4
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.exoplayer2.PlaybackParameters org.schabi.newpipe.player.Player.getPlaybackParameters()' on a null object reference
	at org.schabi.newpipe.player.PlayQueueActivity.onCreateOptionsMenu(PlayQueueActivity.java:107)
	at android.app.Activity.onCreatePanelMenu(Activity.java:4087)
	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:324)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3070)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:456)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:57)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```
</details>
<hr>

### Expected behavior
App opens the page of the video, and continues playing at current time

**Comment by litetex** [comment]
Should be fixed by #8244
