### ISSUE TITLE
Wont connect with VPN

### ISSUE THREAD

**Issue by doobydooby72** [TeamNewPipe/NewPipe#6465]
Just updated to the latest variant x.4, it no longer works via a VPN connection. No searches, no thumbnails, nothing. If i disconnect it works fine, reconnect and it fails again. Surfshark is the VPN via the official app if thats of any use too.
Please fix, this app has been my go to for years now and thanks for the efforts.

**Comment by mhmdanas** [comment]
Are you connecting to an EU country? If so, it's #5977. If not, please make a comment.

Also, don't remove the template next time you open an issue.

**Comment by doobydooby72** [comment]
It may be an issue with the vpn altogether, apologies. Ill monitor it to make sure though. No not any EU country. 

Apologies for deleting the template but it seemed extensively superfluous unless one has been vague with directions, of which ive been as accurate as possible to my knowledge of the situation and recreating it is unknowable since its been consistent since it occured so there is nothing i can do to varify a methodology for recreation of any sort. 

As a note i appreciate that if one can fill out the template wholly that it would make your work easier but if its only causing people not to report issues because of its rigidness its not actually aiding you in aquiring even a basic sense of the issue. Eg absolutely nothing having changed since it was working in my case besides updates to apps which i did after it stopped working because i remembered a while ago you having to update it cos youtube messed up the way it passed the information making an older varient of the app unusable. Thank you, keep up the good work.

**Comment by DrDro94** [comment]
Hi, I have the same problem. When I use VPN newpipe don't work, even if I put the app in the whitelist of the VPN. This is the bug report
## Exception
* __User Action:__ requested kiosk
* __Request:__ Start loading: https://www.youtube.com/feed/trending
* __Content Country:__ IT
* __Content Language:__ it-IT
* __App Language:__ it_IT
* __Service:__ YouTube
* __Version:__ 0.21.4
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.net.UnknownHostException: Unable to resolve host "www.youtube.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at okhttp3.Dns$1.lookup(Dns.java:40)
	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:215)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
	at okhttp3.RealCall.execute(RealCall.java:93)
	at org.schabi.newpipe.DownloaderImpl.execute(DownloaderImpl.java:264)
	at org.schabi.newpipe.extractor.downloader.Downloader.get(Downloader.java:70)
	at org.schabi.newpipe.extractor.downloader.Downloader.get(Downloader.java:54)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.isHardcodedClientVersionValid(YoutubeParsingHelper.java:290)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getClientVersion(YoutubeParsingHelper.java:363)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.addClientInfoHeaders(YoutubeParsingHelper.java:714)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.addYouTubeHeaders(YoutubeParsingHelper.java:700)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getJsonResponse(YoutubeParsingHelper.java:663)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeTrendingExtractor.onFetchPage(YoutubeTrendingExtractor.java:60)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:54)
	at org.schabi.newpipe.extractor.kiosk.KioskInfo.getInfo(KioskInfo.java:57)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getKioskInfo$11(ExtractorHelper.java:183)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$NbG7JFGg0N9HK-3exJNRB9r_hYY.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:202)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	... 48 more

```
</details>
<hr>

**Comment by mhmdanas** [comment]
> Apologies for deleting the template but it seemed extensively superfluous unless one has been vague with directions, of which ive been as accurate as possible to my knowledge of the situation and recreating it is unknowable since its been consistent since it occured so there is nothing i can do to varify a methodology for recreation of any sort.

You don't have to fill _every_ section of the template. In this case you don't have logs, so you can remove the "Logs" section for example. The template also doesn't only exist for making people providing needed information only; it's also there to make sure they actually e.g. checked the repo for duplicates. In addition, the steps don't necessarily have to be reproduced on other devices, although that would of course be very helpful.

> As a note i appreciate that if one can fill out the template wholly that it would make your work easier but if its only causing people not to report issues because of its rigidness its not actually aiding you in aquiring even a basic sense of the issue.

Again, you don't have to follow it to the T. Just fill out the general structure and delete what's not needed.

Also, just to provide an example of information you have forgotten to add: you didn't specify either your Android version or device, both of which might be related to your problem (probably not the device though).

In any case, I have no plans of continuing this discussion anymore because I've had it more than I'd like to, so just please, next time, fill the template. Not necessarily rigidly, just fill it and delete what's not needed.

---

So, anyway, back to the issue. What country are you connecting to? What about your Android version and device? Does the YouTube website work fine? If you have any other devices, could you try to reproduce the issue on there?

**Comment by mhmdanas** [comment]
@DrDro94 that's not an issue with NewPipe, but with your VPN. For some reason, NewPipe is unable to resolve www.youtube.com. It might be caused by DNS issues with your VPN. Can you test the YouTube website?

**Comment by DrDro94** [comment]
Hi, thank you for the answer. I have grapheneOs and I try to open YouTube with Brave and it's work. Every app and website works with the VPN and work fine. How can I fix it? Changing the DNS?

**Comment by mhmdanas** [comment]
I'm not sure how to fix it for sure, but yeah, you can try changing your DNS.

**Comment by DrDro94** [comment]
I tried with DNS but don't work. I downgraded newpipe and now it work. Thank you for the help.

**Comment by doobydooby72** [comment]
It appeared to be the VPNs issue for myself. I think this issue can be closed, sorry for the confusion. I never had to downgrade version. Ill leave this open for now in case someone has any disagreements still. Thank you
