### ISSUE TITLE
Crash on newpipe when pressing on chapter

### ISSUE THREAD

**Issue by Thewisem** [TeamNewPipe/NewPipe#6467]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to newpipe
2. Click on this video https://www.youtube.com/watch?v=SwcqhZHB4To
3. Click on the chapter button.
4. 

### Actual behaviour

It crashed.

### Expected behavior

Shows chapter of the video

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.21.4
* __OS:__ Linux Android 7.1.1 - 25
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
	at org.schabi.newpipe.player.Player.onSegmentsClicked(Player.java:3032)
	at org.schabi.newpipe.player.Player.onClick(Player.java:3572)
	at android.view.View.performClick(View.java:6308)
	at android.view.View$PerformClick.run(View.java:23969)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6823)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by botistreamer** [comment]
I can also recreate the bug on the Galaxy Tab S7 (SM-T870), Android 11 - OneUI 3.1
Newpipe 21.4

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.4
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setVisibility(int)' on a null object reference
	at org.schabi.newpipe.player.Player.onSegmentsClicked(Player.java:3032)
	at org.schabi.newpipe.player.Player.onClick(Player.java:3572)
	at android.view.View.performClick(View.java:8160)
	at android.view.View.performClickInternal(View.java:8137)
	at android.view.View.access$3700(View.java:888)
	at android.view.View$PerformClick.run(View.java:30236)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```
</details>
<hr>

**Comment by litetex** [comment]
You are both using a tablet/tv right - basically a larger device?

Code analysis:
Looks like the ``itemsListHeaderDuration`` element is missing in the ``large-hand`` player:
https://github.com/TeamNewPipe/NewPipe/blob/v0.21.4/app/src/main/java/org/schabi/newpipe/player/Player.java#L3032
![grafik](https://user-images.githubusercontent.com/40789489/121741361-b4dfc580-cafe-11eb-9752-1f4bc7c6c88b.png)

**Comment by Thewisem** [comment]
So chapters need to be fixed until then we use the timestamps in the descriptions

**Comment by Thewisem** [comment]
Samsung Galaxy Tab A. Sooo yeah Big device

**Comment by Thewisem** [comment]
Thanks for fixing
