### ISSUE TITLE
NewPipe crashes when switching back to the play queue from the main player.

### ISSUE THREAD

**Issue by Drakim42** [TeamNewPipe/NewPipe#6473]
### Checklist

- [x] I am using the latest version - 0.21.4 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Play any playlist in the background.
2. Tap on NewPipe's notification to open the play queue.
3. Open the kebab menu and select 'Switch to Main'
4. Tap on the currently playing video and tap the play queue icon.

### Actual behaviour

NewPipe crashes every time.

### Expected behavior

NewPipe doesn't crash and I see the play queue again.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.4
* __OS:__ Linux Android 7.1.2 - 25
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
	at org.schabi.newpipe.player.Player.onQueueClicked(Player.java:2995)
	at org.schabi.newpipe.player.Player.onClick(Player.java:3569)
	at android.view.View.performClick(View.java:5637)
	at android.view.View$PerformClick.run(View.java:22433)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

```
</details>
<hr>

**Comment by Drakim42** [comment]
This was fixed in the latest release.
