### ISSUE TITLE
Crash on attempt to enable Repeat function

### ISSUE THREAD

**Issue by babyrig** [TeamNewPipe/NewPipe#6509]
### Checklist

- [x] I am using the latest version - 0.21.5 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. I just tried to enable the repeat button
2. Press on repeat button

### Actual behaviour

Crash 

### Expected behavior

Enable repeat function (last checked working just fine on 0.21.2)

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ BR
* __Content Language:__ pt-BR
* __App Language:__ pt_BR
* __Service:__ none
* __Version:__ 0.21.5
* __OS:__ Linux Android 5.1.1 - 22
<details><summary><b>Cr

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by sauravrao637** [comment]
@babyrig  Thanks for reporting the issue !
It will be of great help if you can please share the logs of the crash.

**Comment by babyrig** [comment]
@sauravrao637 this message below ? or there is another place to the log ? It's only happening here in my device or do you could reproduce this error too ? 

-------------------------------------
java.lang.RuntimeException: Error receiving broadcast Intent { act=org.schabi.newpipe.player.MainPlayer.REPEAT flg=0x10000010 bnds=[686,188][772,246] } in org.schabi.newpipe.player.Player$3@211d452
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:876)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Caused by: java.lang.ClassCastException: android.widget.ImageButton cannot be cast to androidx.appcompat.widget.AppCompatImageButton
	at org.schabi.newpipe.player.Player.onRepeatModeChanged(Player.java:2257)
	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$setRepeatMode$2(ExoPlayerImpl.java:564)
	at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$rgrcbaqP9Y8LgzdByBnAfUO4ydU.invokeListener(lambda)
	at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:279)
	at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:1498)
	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$notifyListeners$6(ExoPlayerImpl.java:1318)
	at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$b59raXxaB-trjwE5bgpZInm1QnU.run(lambda)
	at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:1328)
	at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:1318)
	at com.google.android.exoplayer2.ExoPlayerImpl.setRepeatMode(ExoPlayerImpl.java:564)
	at com.google.android.exoplayer2.SimpleExoPlayer.setRepeatMode(SimpleExoPlayer.java:1636)
	at org.schabi.newpipe.player.Player.setRepeatMode(Player.java:2247)
	at org.schabi.newpipe.player.Player.onRepeatClicked(Player.java:2226)
	at org.schabi.newpipe.player.Player.onBroadcastReceived(Player.java:1118)
	at org.schabi.newpipe.player.Player.access$200(Player.java:190)
	at org.schabi.newpipe.player.Player$3.onReceive(Player.java:1055)
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:866)
	... 8 more
---------------------------------

**Comment by sauravrao637** [comment]
@babyrig 
Yes it's the log, thanks for it.
No I am not able to produce this, this maybe device specific or maybe the playlist/stream specific, need to look into it :)

**Comment by babyrig** [comment]
I forgot to mention this happening here when put on background player and try to enable the repeat function then the NewPipe crash. Attaching the video may helps better. 

https://user-images.githubusercontent.com/38074298/122486521-9c185980-cfaf-11eb-9fdf-9f52e532fde4.mp4

**Comment by sauravrao637** [comment]
Thanks for reporting the error but this is already an open [issue](https://github.com/TeamNewPipe/NewPipe/issues/6401) .
U can follow the updates there :)
