### ISSUE TITLE
reCAPTCHA crash

### ISSUE THREAD

**Issue by CaiusCosades** [TeamNewPipe/NewPipe#6519]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [ ] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [ ] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behaviour

it shows "recaptcha challenge requested" when I open the video
It just crashes when I press solve
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.5
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalArgumentException: reasonPhrase can't be empty.
	at android.webkit.WebResourceResponse.setStatusCodeAndReasonPhrase(WebResourceResponse.java:139)
	at android.webkit.WebResourceResponse.<init>(WebResourceResponse.java:77)
	at xH.a(SourceFile:286)
	at ayK.handleMessage(SourceFile:67)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7050)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by TobiGr** [comment]
Does it always crash when you press solve?
What's your webview version?

**Comment by CaiusCosades** [comment]
yesalways 72.0.3626.121

**Comment by TobiGr** [comment]
> yes always  

ok. that's bad.

> 72.0.3626.121

According to [this chromium / webview ticket](https://bugs.chromium.org/p/chromium/issues/detail?id=925887#c10) the bug was fixed in version 73.


Could you try updating the system webview?

**Comment by CaiusCosades** [comment]
ok!! i updated chrome it dosent ask for capcha anymore
