### ISSUE TITLE
Playing a live stream that ends at the same time causes crash on next open

### ISSUE THREAD

**Issue by ageneric** [TeamNewPipe/NewPipe#6652]
### Checklist

- [x] I am using the latest version - 0.21.5 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file. `two crashes: second is attached`

### Steps to reproduce the bug

Cannot reproduce. Previous actions were:
1. View a live stream (YouTube) using NewPipe. The stream ended at approximately the same time. The player only shows less than 5 seconds from the end of the stream.
2. Exit video using back button. This displays a toast "Could not play stream".
3. Unfocus NewPipe then attempt to close NewPipe. NewPipe crashes during this step. This error message was not saved and is not the subject of this report.
4. Close NewPipe.
5. Open NewPipe. NewPipe crashes immediately.

### Actual behavior

NewPipe crashes and brings up the bug reporting screen.

### Expected behavior

Any appropriate method to deal with end of stream.

### Logs

Error on app open following "Could not play stream" toast message and closing app. Produced on non-root Android Marshmallow. Not logged in.
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.21.5
* __OS:__ Linux ,release-keys 6.0 - 23
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'long org.schabi.newpipe.player.playqueue.PlayQueueItem.getRecoveryPosition()' on a null object reference
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.updateProgressInfo(VideoDetailFragment.java:1644)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.handleResult(VideoDetailFragment.java:1547)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$runWorker$6(VideoDetailFragment.java:893)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$runWorker$6$VideoDetailFragment(VideoDetailFragment.java)
	at org.schabi.newpipe.fragments.detail.-$$Lambda$VideoDetailFragment$X-UcNln23jPsop2TvHe2VPTu0NQ.accept(lambda)
	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

```
</details>
<hr>

### Device info

 - Android version: 6.0
 - Device model: Motorola E (2nd Generation)

### Footnote
Unfortunately, capturing the first crash would have been more useful.

**Comment by litetex** [comment]
Note that a similar error now starts occurring on https://github.com/TeamNewPipe/NewPipe/blob/v0.21.9/app/src/main/java/org/schabi/newpipe/player/Player.java#L674

There seems to be a similar underlying cause

**Comment by licaon-kter** [comment]
Seeing this most of the time with latest version.

Kinda fixed if I FC the app and clean cache. On reopen same video just works fine.
