### ISSUE TITLE
0.21.6 Unable to export to nexcloud uing SAF

### ISSUE THREAD

**Issue by imcmjha** [TeamNewPipe/NewPipe#6665]
### Checklist

- [x] I am using the latest version - 0.21.6
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to `Export Database`
2. Select `Nextcloud` menu in file.
3. Tap on `SAVE` button

### Actual behavior
It throws the error text `Sorry. Something went wrong.` and stores a file with 0 byte size.

### Expected behavior
The file should be exported to nextcloud.

## Exception
* User Action: ui error
* Request: Exporting database
* Content Country: IN
* Content Language: en
* App Language: en_US
* Service: none
* Version: 0.21.6
* OS: Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

java.io.FileNotFoundException: Error downloading file: NewPipeData-20210715_122300.zip
 at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:149)
 at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:631)
 at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1521)
 at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1338)
 at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1286)
 at us.shandian.giga.io.FileStreamSAF.<init>(FileStreamSAF.java:32)
 at org.schabi.newpipe.streams.io.StoredFileHelper.getStream(StoredFileHelper.java:190)
 at org.schabi.newpipe.settings.ContentSettingsManager.exportDatabase(ContentSettingsManager.kt:24)
 at org.schabi.newpipe.settings.ContentSettingsFragment.exportDatabase(ContentSettingsFragment.java:200)
 at org.schabi.newpipe.settings.ContentSettingsFragment.requestExportPathResult(ContentSettingsFragment.java:170)
 at org.schabi.newpipe.settings.ContentSettingsFragment.lambda$8bBkxkdGnhK6YvPK6sE5N6ky1yA(Unknown Source:0)
 at org.schabi.newpipe.settings.-$$Lambda$ContentSettingsFragment$8bBkxkdGnhK6YvPK6sE5N6ky1yA.onActivityResult(Unknown Source:4)
 at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:148)
 at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
 at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
 at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
 at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
 at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
 at androidx.fragment.app.Fragment.performStart(Fragment.java:3026)
 at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:589)
 at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:300)
 at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
 at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
 at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
 at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:3079)
 at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:262)
 at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:510)
 at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
 at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1432)
 at android.app.Activity.performStart(Activity.java:7848)
 at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3295)
 at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
 at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
 at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2017)
 at android.os.Handler.dispatchMessage(Handler.java:107)
 at android.os.Looper.loop(Looper.java:214)
 at android.app.ActivityThread.main(ActivityThread.java:7397)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

</details>
<hr>

### Device info

 - Android version/Custom ROM version: android 10-29
 - Device model: Redmi Note 5 Pro(Whyred)

**Comment by skyGtm** [comment]
since its linked with SAF.
https://github.com/TeamNewPipe/NewPipe/pull/6701 might fix the issue.

**Comment by Stypox** [comment]
@skyGtm #6701 is completely unrelated, as it only solves a UI problem ;-)
I have no idea if this is solvable: there seems to be some issue when opening the file for writing. I do not have NextCloud so I can't check.

**Comment by Inrumpo** [comment]
I'm experiencing a similar problem:

Exporting

- subscriptions
- database

directly to a Nextcloud folder doesn't work. As a workaround I have to save those files locally and then manually move them from my phone (files) to Nextcloud.

**Same goes for importing.** Just the other way round.
