### ISSUE TITLE
Crashing when downloading because of SAF

### ISSUE THREAD

**Issue by castrik** [TeamNewPipe/NewPipe#6687]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

download any video or go to see download folder in the app, app restarts a couple of time and crashes

happening only if I enable SAF, its default in 0.21.6 also happens in 0.21.5 if I enabled it

but in 0.21.5, I could atleast see my downloads folder, in 0.21.6 it crashes in both cases, seeing the downloads folder or downloading a video/audio

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/84063610/126030104-584b3d52-d456-4769-9c7d-dbb55cd1a863.mp4

### Logs

`## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.6
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to create service us.shandian.giga.service.DownloadManagerService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4412)
	at android.app.ActivityThread.access$1800(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2118)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at us.shandian.giga.service.DownloadManager.loadPendingMissions(DownloadManager.java:165)
	at us.shandian.giga.service.DownloadManager.<init>(DownloadManager.java:77)
	at us.shandian.giga.service.DownloadManagerService.onCreate(DownloadManagerService.java:142)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4400)
	... 8 more

```
</details>
<hr>
`

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by bew** [comment]
I have the same crash & behavior.
What is `SAF` ?

**Comment by castrik** [comment]
> What is `SAF` ?

read the blog post of the update release
https://newpipe.net/blog/pinned/release/newpipe-0.21.6-released/

**Comment by bew** [comment]
Thanks! I tried to disable SAF, but I still get the same error:

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.6
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to create service us.shandian.giga.service.DownloadManagerService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3579)
	at android.app.ActivityThread.access$1300(ActivityThread.java:197)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1669)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6671)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at us.shandian.giga.service.DownloadManager.loadPendingMissions(DownloadManager.java:165)
	at us.shandian.giga.service.DownloadManager.<init>(DownloadManager.java:77)
	at us.shandian.giga.service.DownloadManagerService.onCreate(DownloadManagerService.java:142)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3567)
	... 8 more

```
</details>

**Comment by timjefferies** [comment]
Same issue for me. I'm on Android 11 so no option to disable.

`## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.21.6
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to create service us.shandian.giga.service.DownloadManagerService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4198)
	at android.app.ActivityThread.access$1500(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1932)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at us.shandian.giga.service.DownloadManager.loadPendingMissions(DownloadManager.java:165)
	at us.shandian.giga.service.DownloadManager.<init>(DownloadManager.java:77)
	at us.shandian.giga.service.DownloadManagerService.onCreate(DownloadManagerService.java:142)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4186)
	... 8 more

```
</details>
<hr>
`

**Comment by skyGtm** [comment]
It seems to have fixed.
You guys should try debug apk from this PR. https://github.com/TeamNewPipe/NewPipe/pull/6701

**Comment by Stypox** [comment]
@skyGtm again, that PR is unrelated ;-)

**Comment by timjefferies** [comment]
Issue remains on version 0.21.7

`## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.21.7
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to create service us.shandian.giga.service.DownloadManagerService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4198)
	at android.app.ActivityThread.access$1500(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1932)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at us.shandian.giga.service.DownloadManager.loadPendingMissions(DownloadManager.java:165)
	at us.shandian.giga.service.DownloadManager.<init>(DownloadManager.java:77)
	at us.shandian.giga.service.DownloadManagerService.onCreate(DownloadManagerService.java:142)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4186)
	... 8 more

```
</details>
<hr>
`

**Comment by Stypox** [comment]
@timjefferies @bew @castrik does #6721 fix the problem for you?

**Comment by castrik** [comment]
> @timjefferies @bew @castrik does #6721 fix the problem for you?

thank you, works flawlessly now

**Comment by massyas** [comment]
Hello,
I also have the same issue on Android 10 (Oxygen OS 10.3.11 on OnePlus 6) and even with version 0.21.7 crash is still there.
I tried to reset the download folder once SAF has been enabled by default but without success.

**Comment by TobiGr** [comment]
@massyas Did you test the APK from #6721?

**Comment by massyas** [comment]
Hello @TobiGr 
My mistake, I thought the fix was already integrated in 0.21.7
It works perfect with debug APK from #6721 
Thanks !

**Comment by massyas** [comment]
Hello @TobiGr 
Unfortunately the problem has reappeared at my side on the debug version with a different stack apparently but same consequence

```
java.lang.RuntimeException: Unable to create service us.shandian.giga.service.DownloadManagerService: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.exists()' on a null object reference
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4082)
	at android.app.ActivityThread.access$1800(ActivityThread.java:231)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1968)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7682)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.exists()' on a null object reference
	at org.schabi.newpipe.streams.io.StoredFileHelper.existsAsFile(StoredFileHelper.java:295)
	at us.shandian.giga.get.DownloadMission.hasInvalidStorage(DownloadMission.java:667)
	at us.shandian.giga.service.DownloadManager.loadPendingMissions(DownloadManager.java:152)
	at us.shandian.giga.service.DownloadManager.<init>(DownloadManager.java:77)
	at us.shandian.giga.service.DownloadManagerService.onCreate(DownloadManagerService.java:142)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4070)
`
Hope this can help...

**Comment by Stypox** [comment]
@massyas could you test #6778?

**Comment by massyas** [comment]
> @massyas could you test #6778?

Hello @Stypox , #6778 apk seems to work ok. I set the same download folder as before and tried to download several videos with success.
Thanks 👍

**Comment by Movisivi** [comment]
Still crashing when trying to download. Been this way since 0.21.6.  0.21.8 was released and its still not fixed...

**Comment by Stypox** [comment]
@Movisivi please provide a crash report

**Comment by subsonik** [comment]
I'm having the same issue.

When "Ask where to download" is enabled, I click Download, select Audio/Video, click OK, the file chooser pops up (MiXplorer in my case), I select a folder, but then NewPipe says "Action denied by the system". The "Files and media" permission is granted.

If "Ask where to download" is disabled and I try to select a "Video/Audio download folder", the app just exits without error.

**Comment by Stypox** [comment]
@subsonik do other apps using SAF work on your system?

**Comment by bew** [comment]
Opening the download queue stiff fails with 0.21.8 (I thought this fix was included in this last release, was it not? Why not?

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.8
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to create service us.shandian.giga.service.DownloadManagerService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3579)
	at android.app.ActivityThread.access$1300(ActivityThread.java:197)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1669)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6671)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at us.shandian.giga.service.DownloadManager.loadPendingMissions(DownloadManager.java:165)
	at us.shandian.giga.service.DownloadManager.<init>(DownloadManager.java:77)
	at us.shandian.giga.service.DownloadManagerService.onCreate(DownloadManagerService.java:142)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3567)
	... 8 more

```
</details>
<hr>

**Comment by Stypox** [comment]
> I thought this fix was included in this last release, was it not?

No, it wasn't, 0.21.8 was a hotfix release for youtube, just look at the release notes.
