### ISSUE TITLE
Crash when rotating device on unsupported channels

### ISSUE THREAD

**Issue by TiA4f8R** [TeamNewPipe/NewPipe#6696]
### Checklist
- [x] I am using the latest version - 0.21.15
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Open a channel which is not supported by NewPipe.
2. Rotate your device.
3. Observe app's behavior.

### Actual behavior
The app crashes.

### Expected behavior
The app displays the unsupported channel after device's rotation.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/74829229/126073585-ca479278-202b-4429-b4a5-5d8fd932bd23.mp4

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ FR
* __Content Language:__ fr-FR
* __App Language:__ fr_FR
* __Service:__ none
* __Version:__ 0.21.6
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to read from field 'android.widget.TextView org.schabi.newpipe.databinding.FragmentChannelBinding.errorContentNotSupported' on a null object reference
	at org.schabi.newpipe.fragments.list.channel.ChannelFragment.showContentNotSupported(ChannelFragment.java:510)
	at org.schabi.newpipe.fragments.list.channel.ChannelFragment.handleResult(ChannelFragment.java:477)
	at org.schabi.newpipe.fragments.list.channel.ChannelFragment.handleResult(ChannelFragment.java:67)
	at org.schabi.newpipe.fragments.list.BaseListInfoFragment.doInitialLoadLogic(BaseListInfoFragment.java:115)
	at org.schabi.newpipe.fragments.BaseStateFragment.onViewCreated(BaseStateFragment.java:42)
	at org.schabi.newpipe.fragments.list.channel.ChannelFragment.onViewCreated(ChannelFragment.java:125)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:501)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
	at android.app.Activity.performStart(Activity.java:8024)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3475)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>
<hr>

### Devices info

 - Android version/Custom ROM version: EMUI 10 + Android 11
 - Device model: Honor 9X + Pixel 4A (Android emulator)

**Comment by TiA4f8R** [comment]
I'm afraid I don't know if that's the good way to fix this, as I don't know specific things about Android development.

Anyway, you are now assigned :)

**Comment by Stypox** [comment]
Use this link to test: https://www.youtube.com/channel/UClYV6hHlupm_S_ObS1W-DYw
