### ISSUE TITLE
Application get crash with downloads

### ISSUE THREAD

**Issue by RealLenouche** [TeamNewPipe/NewPipe#6729]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behavior

- Go on youtube (for example)
- Select any video
- Click on share button and select newpipe
- Select Download
- Select any video or audio quality and press "OK"
- You got a crash error (everytime if you try theses steps)

### Expected behavior

- If you follow theses steps below downloads work and videos are stored in /movies/newpipe (if video) or /music/newpipe (if audio)

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ FR
* __Content Language:__ fr-FR
* __App Language:__ fr_FR
* __Service:__ none
* __Version:__ 0.21.7
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE flg=0x43 (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2258)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1914)
	at android.app.Activity.startActivityForResult(Activity.java:5326)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:574)
	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:234)
	at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:208)
	at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:166)
	at androidx.fragment.app.Fragment$9.launch(Fragment.java:3510)
	at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
	at org.schabi.newpipe.download.DownloadDialog.launchDirectoryPicker(DownloadDialog.java:690)
	at org.schabi.newpipe.download.DownloadDialog.prepareSelectedDownload(DownloadDialog.java:749)
	at org.schabi.newpipe.download.DownloadDialog.lambda$initToolbar$1(DownloadDialog.java:359)
	at org.schabi.newpipe.download.DownloadDialog.lambda$initToolbar$1$DownloadDialog(Unknown Source:0)
	at org.schabi.newpipe.download.-$$Lambda$DownloadDialog$QfMS-FoXWFjSoHiNV7JREecQBWg.onMenuItemClick(Unknown Source:2)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:779)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:975)
	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:623)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
	at android.view.View.performClick(View.java:7520)
	at android.view.View.performClickInternal(View.java:7489)
	at android.view.View.access$3600(View.java:826)
	at android.view.View$PerformClick.run(View.java:28555)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:245)
	at android.app.ActivityThread.main(ActivityThread.java:8004)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version:
 - Device model:

**Comment by MingScott** [comment]
Experiencing this as well

**Comment by n8chz** [comment]
Me too. Playback is fine. Attempting a download, screen goes red (with NewPipe logo in middle), then guru meditation. Null pointer exception attempting to call some method on a Null object reference.

**Comment by JosieDraus** [comment]
Same here. LG Stylo 5, Android kernel 4.9.112. Can't download starting with 0.21.6 and including 0.21.7. Afraid to downgrade b/c I don't want to risk losing my history.

**Comment by MingScott** [comment]
Interesting, my crash log is actually different from the issue above on review:

<summary>crash log<details>

``-------------------------------------
java.lang.RuntimeException: Unable to create service us.shandian.giga.service.DownloadManagerService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4535)
	at android.app.ActivityThread.access$2600(ActivityThread.java:296)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2243)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at us.shandian.giga.service.DownloadManager.loadPendingMissions(DownloadManager.java:165)
	at us.shandian.giga.service.DownloadManager.<init>(DownloadManager.java:77)
	at us.shandian.giga.service.DownloadManagerService.onCreate(DownloadManagerService.java:142)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4521)
	... 8 more
-------------------------------------``
</details></summary>

**Comment by bew** [comment]
> Interesting, my crash log is actually different from the issue above on review:
> crash log
> 
> `------------------------------------- java.lang.RuntimeException: Unable to create service us.shandian.giga.service.DownloadManagerService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference at android.app.ActivityThread.handleCreateService(ActivityThread.java:4535) at android.app.ActivityThread.access$2600(ActivityThread.java:296) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2243) at android.os.Handler.dispatchMessage(Handler.java:107) at android.os.Looper.loop(Looper.java:213) at android.app.ActivityThread.main(ActivityThread.java:8178) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101) Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference at us.shandian.giga.service.DownloadManager.loadPendingMissions(DownloadManager.java:165) at us.shandian.giga.service.DownloadManager.<init>(DownloadManager.java:77) at us.shandian.giga.service.DownloadManagerService.onCreate(DownloadManagerService.java:142) at android.app.ActivityThread.handleCreateService(ActivityThread.java:4521) ... 8 more -------------------------------------`

This is #6687

**Comment by litetex** [comment]
@RealLenouche 
> `` No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE flg=0x43 (has extras) }``

Looks like you have no file-manager...
Can you check if you have one?

Could you also please fill out "Device info"?

**Comment by RealLenouche** [comment]
> @RealLenouche
> 
> > ` No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE flg=0x43 (has extras) }`
> 
> Looks like you have no file-manager...
> Can you check if you have one?
> 
> Could you also please fill out "Device info"?

I have disable the google file manager BUT I have the native oneplus file manager and Mixplorer.
(I reenable native file manager and I test if work or not work I add an "EDIT" to this message)

**Comment by alabotski** [comment]
I have the some problem... I deleted default manager and use MixPlorer - my stacktrace error - 7400 issue

**Comment by opusforlife2** [comment]
Can everyone here try Material Files? - https://f-droid.org/en/packages/me.zhanghai.android.files/

**Comment by opusforlife2** [comment]
@litetex Since we've seen multiple issues opened around this, I think we should add another FAQ entry for this. We have another app to suggest here, too. What say?

**Comment by alabotski** [comment]
> Can everyone here try Material Files? - [f-droid.org/en/packages/me.zhanghai.android.files](https://f-droid.org/en/packages/me.zhanghai.android.files/)

That didn't work for me. I am guessing due to the Material Files being installed as a custom app and not a system one

I restored a deleted copy of the default File Manager with a search for Debloat and this error disappeared

**Comment by litetex** [comment]
> @litetex Since we've seen multiple issues opened around this, I think we should add another FAQ entry for this. We have another app to suggest here, too. What say?

https://github.com/TeamNewPipe/NewPipe/issues/7113 😉
