### ISSUE TITLE
YT comments fail to load

### ISSUE THREAD

**Issue by litetex** [TeamNewPipe/NewPipe#6744]
### Checklist
- [x] I am using the latest version - dev-Branch and v0.21.7
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
Open any YT video that has comments (maybe check on the YT website)

You maybe have to open multiple videos, to see the problem.
Currently the error rate is ~50%

### Logs
Error that occurs when using 0.21.7:
```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse json data for comments
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getPage(YoutubeCommentsExtractor.java:100)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getInitialPage(YoutubeCommentsExtractor.java:55)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:40)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:25)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getCommentsInfo$7(ExtractorHelper.java:154)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$60N_-UL7E5eaxFaFO1bZZmnfwM8.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: com.grack.nanojson.JsonParserException: Unexpected character: < on line 1, char 1
	at com.grack.nanojson.JsonTokener.createParseException(Unknown Source:44)
	at com.grack.nanojson.JsonTokener.advanceToToken(Unknown Source:118)
	at com.grack.nanojson.JsonParser.advanceToken(Unknown Source:12)
	at com.grack.nanojson.JsonParser.parse(Unknown Source:1)
	at com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source:19)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getPage(YoutubeCommentsExtractor.java:98)
	... 19 more

```

On the ``dev``-branch no error occurs but the "Comments are disabled" view (which is new, see https://github.com/TeamNewPipe/NewPipeExtractor/issues/577) is shown:
![grafik](https://user-images.githubusercontent.com/40789489/126837541-3eb393e6-18c3-4cb6-b4b8-511537d0a9cc.png)

### Analysis
YT currently seems to [A/B test](https://en.wikipedia.org/wiki/A/B_testing) a new comments endpoint/reply with different data structure (that's also why the problem is happening since a few weeks ago).

So sometimes it returns:
```
"sectionListRenderer": {
    "contents": [
        {
            "itemSectionRenderer": {
                "contents": [
                    {
                        "continuationItemRenderer": {
                            "trigger": "CONTINUATION_TRIGGER_ON_ITEM_SHOWN",
                            "continuationEndpoint": {
                                "clickTrackingParams":"xxx",
                                "commandMetadata": {
                                    "webCommandMetadata": {
                                        "sendPost": true,
                                        "apiUrl": "\/youtubei\/v1\/next"
                                    }
                                },
                                "continuationCommand": {
                                    "token": "Eg0SC0FBR0lpNjItc0FVGAYyOCIRIgtBQUdJaTYyLXNBVTAAeAIwAUIhZW5nYWdlbWVudC1wYW5lbC1jb21tZW50cy1zZWN0aW9u",
                                    "request": "CONTINUATION_REQUEST_TYPE_WATCH_NEXT"
                                }
                            }
                        }
                    }
                ],
                "trackingParams":"xxx",
                "targetId": "engagement-panel-comments-section"
            }
        }
    ],
    "trackingParams":"xxx"
}
```
instead of
```
"sectionListRenderer": {
    "continuations": [
        {
            "reloadContinuationData": {
                "continuation": "Eg0SC3V6a0Q1U2V1d3pNGAYyFSIRIgt1emtENVNldXd6TTAAeAIwAQ%3D%3D",
                "clickTrackingParams": "xxx"
            }
        }
    ],
    "trackingParams":"xxx"
}
```

Which causes the extractor to fail, because we're unable to locate the pattern ``continuation":"`` anywhere.

This causes the old extractor in (current) release 0.21.7 to fail with a nested bug:
> * The ``findValue`` in ``YoutubeCommentsExtractor`` was faulty: If no "start" was found (e.g. ``continuation":"`` for the continuation token) it searched nearly everything, found ``apple-itunes-app`` (from ``<!DOCTYPE html><head><meta name="apple-itunes-app" content="app-id=544007664, app-argume...`` and used that as continuation-token, which resulted in the response of an internal server error (500) by YT's servers and caused NewPipe to show the error
Explanation from https://github.com/TeamNewPipe/NewPipeExtractor/pull/652#issue-669103276

In the ``dev``-Version the exception is fixed and it's just unable to locate the token, which is interpreted as disabled comments.

#### How to fix this?

The extractor has to be reworked (→ https://github.com/TeamNewPipe/NewPipeExtractor/issues/688)
Maybe we also need https://github.com/TeamNewPipe/NewPipeExtractor/pull/604, because the new internal API is called.

### Other
For additional information check these duplicates:
* #6730
* #6728
* #6690
* #6641
* #6579
* #6587

**Comment by Thewisem** [comment]
Yeah having the same issue here. Except the percentage is more like 90% - 70%. It has been happening to me a lot

## Exception
* __User Action:__ requested comments
* __Request:__ Start loading: https://www.youtube.com/watch?v=GzkiK0RQgn8
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ YouTube
* __Version:__ 0.21.7
* __OS:__ Linux Android 7.1.1 - 25
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse json data for comments
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getPage(YoutubeCommentsExtractor.java:100)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getInitialPage(YoutubeCommentsExtractor.java:55)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:40)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:25)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getCommentsInfo$7(ExtractorHelper.java:155)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$60N_-UL7E5eaxFaFO1bZZmnfwM8.call(lambda)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)
Caused by: com.grack.nanojson.JsonParserException: Unexpected character: < on line 1, char 1
	at com.grack.nanojson.JsonTokener.createParseException(Unknown Source)
	at com.grack.nanojson.JsonTokener.advanceToToken(Unknown Source)
	at com.grack.nanojson.JsonParser.advanceToken(Unknown Source)
	at com.grack.nanojson.JsonParser.parse(Unknown Source)
	at com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getPage(YoutubeCommentsExtractor.java:98)
	... 30 more

```
</details>
<hr>

**Comment by dfinf2** [comment]
Same Issue:
## Exception
* __User Action:__ requested comments
* __Request:__ Start loading: https://www.youtube.com/watch?v=wOwUZqlfmqI
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.21.7
* __OS:__ Linux samsung/d2qsq/d2q:11/RP1A.200720.012/N975USQU6FUD9:user/release-keys 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse json data for comments
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getPage(YoutubeCommentsExtractor.java:100)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getInitialPage(YoutubeCommentsExtractor.java:55)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:40)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:25)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getCommentsInfo$7(ExtractorHelper.java:155)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$60N_-UL7E5eaxFaFO1bZZmnfwM8.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: com.grack.nanojson.JsonParserException: Unexpected character: < on line 1, char 1
	at com.grack.nanojson.JsonTokener.createParseException(Unknown Source:44)
	at com.grack.nanojson.JsonTokener.advanceToToken(Unknown Source:118)
	at com.grack.nanojson.JsonParser.advanceToken(Unknown Source:12)
	at com.grack.nanojson.JsonParser.parse(Unknown Source:1)
	at com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source:19)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getPage(YoutubeCommentsExtractor.java:98)
	... 30 more

```
</details>
<hr>

**Comment by Somadima** [comment]
When I enable "Turn on YouTube's 'Restricted Mode" can't load comments on YouTube

**Comment by litetex** [comment]
Thank you guys for your feedback. 
However reporting the same things as stated above doesn't help and we just get more unnecessary notifications.

If you have the same issue please simply give it a thumbs up 😄

**Comment by chrstfer** [comment]
Im guessing this is obvious to people actually contributing here, but this issue strikes me as almost certainly related to a few of the crash bugs that have been reported.  The extractor is returning a ton of null pointers that should be formatted strings (json in this case, the other errors that caused CTDs have all been video or playlist URIs).

**Comment by swarupbhanjachowdhury** [comment]
Same issue facing

**Comment by Long-FA** [comment]
Sometimes, repeatedly spamming the retry button will load the comment. God knows why.

**Comment by infinitewaveparticle** [comment]
@Long-FA I noticed that too for a while, but that doesn't work at all for me anymore. I can hit Retry 100 times and it never loads.

**Comment by MasterEric** [comment]
> Sometimes, repeatedly spamming the retry button will load the comment. God knows why.



> @Long-FA I noticed that too for a while, but that doesn't work at all for me anymore. I can hit Retry 100 times and it never loads.

I believe this is because, as mentioned in the parent comment, the issue is with a new A/B test causing only some users to experience issues.

I came here to report but it appears the team is already aware of the issue and its root cause. Great to see them on the ball here and I have high expectations that it will be resolved soon.

**Comment by TiA4f8R** [comment]
Can you test the APK provided in TiA4f8R/NewPipe#1? YouTube comments should load on this APK.

**Comment by gotmax23** [comment]
It worked! Thank you.

**Comment by TiA4f8R** [comment]
For users who have issues when downloading or extracting the APK from the ZIP you have downloaded, here is a reupload of it: [app.zip](https://github.com/TeamNewPipe/NewPipe/files/6911556/app.zip)

**Comment by MasterEric** [comment]
> Can you test the APK provided in [TiA4f8R#1](https://github.com/TiA4f8R/NewPipe/pull/1)? YouTube comments should load on this APK.
> 
> For users who have issues when downloading or extracting the APK from the ZIP you have downloaded, here is a reupload of it: [app.zip](https://github.com/TeamNewPipe/NewPipe/files/6911556/app.zip)

Hey @TiA4f8R,

This modified APK appears to resolve the issues I have been having in regards to loading comments.

If I experience any other bugs I will report them in TiA4f8R/NewPipe#1

**Comment by noko00** [comment]
> For users who have issues when downloading or extracting the APK from the ZIP you have downloaded, here is a reupload of it: [app.zip](https://github.com/TeamNewPipe/NewPipe/files/6911556/app.zip)

**Comment by noko00** [comment]
Comments are fine. No rebuffer. No cache problem.

**Comment by litetex** [comment]
Should be fixed by https://github.com/TeamNewPipe/NewPipeExtractor/pull/604

**Comment by gotmax23** [comment]
> Should be fixed by [TeamNewPipe/NewPipeExtractor#604](https://github.com/TeamNewPipe/NewPipeExtractor/pull/604)

Thanks for fixing this!

Will there be a bug fix release with this change coming out soon?

**Comment by TiA4f8R** [comment]
@gotmax23 Yes

**Comment by gotmax23** [comment]
Cool. Thank you!

**Comment by AA-Coder-Beg** [comment]
> For users who have issues when downloading or extracting the APK from the ZIP you have downloaded, here is a reupload of it: [app.zip](https://github.com/TeamNewPipe/NewPipe/files/6911556/app.zip)
When I downloaded the link, it said "Cannot open this file"...

**Comment by TobiGr** [comment]
You do not need to download that file. We have already published an update containing these fixes.

**Comment by AA-Coder-Beg** [comment]
> You do not need to download that file. We have already published an update containing these fixes.

Ah, thanks for letting me know. Looks like I need to delete and recopy the address, because Newpipe didn't update on its own

**Comment by TobiGr** [comment]
F-Droid might not offer you the update, because you might have installed the NewPipe from their repository signed by their keys. See https://newpipe.net/FAQ/#download-signing-keys
