### ISSUE TITLE
Crash when sharing link of a video not on supported platform

### ISSUE THREAD

**Issue by Thewisem** [TeamNewPipe/NewPipe#6780]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Open this link https://tilvids.com/videos/watch/f869e331-1cfa-44b1-8685-5d35ffa0c516​
2. Open with newpipe
3. See error

### Actual behavior

Showed itself for a video platform it does not support

### Expected behavior

Not show in open with

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.21.6
* __OS:__ Linux Android 7.1.1 - 25
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to create service org.schabi.newpipe.player.MainPlayer: java.lang.RuntimeException: org.schabi.newpipe.extractor.exceptions.ParsingException: Embedded info did not provide YouTube player js url
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3573)
	at android.app.ActivityThread.-wrap6(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1749)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6823)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
Caused by: java.lang.RuntimeException: org.schabi.newpipe.extractor.exceptions.ParsingException: Embedded info did not provide YouTube player js url
	at org.schabi.newpipe.player.helper.PlayerDataSource.<init>(PlayerDataSource.java:80)
	at org.schabi.newpipe.player.Player.<init>(Player.java:396)
	at org.schabi.newpipe.player.MainPlayer.createView(MainPlayer.java:106)
	at org.schabi.newpipe.player.MainPlayer.onCreate(MainPlayer.java:100)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3563)
	... 8 more
Caused by: org.schabi.newpipe.extractor.exceptions.ParsingException: Embedded info did not provide YouTube player js url
	at org.schabi.newpipe.extractor.services.youtube.YoutubeJavaScriptExtractor.extractJavaScriptUrl(YoutubeJavaScriptExtractor.java:82)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeJavaScriptExtractor.extractJavaScriptCode(YoutubeJavaScriptExtractor.java:40)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeJavaScriptExtractor.extractJavaScriptCode(YoutubeJavaScriptExtractor.java:56)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeThrottlingDecrypter.<init>(YoutubeThrottlingDecrypter.java:45)
	at org.schabi.newpipe.player.helper.PlayerDataSource.<init>(PlayerDataSource.java:44)
	... 12 more

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: V 7.1.1 Nougat
 - Device model: Samsung Galaxy Tab A SM P555

**Comment by litetex** [comment]
> https://tilvids.com/videos/watch/f869e331-1cfa-44b1-8685-5d35ffa0c516​

This is not a YouTube link or any other supported platform so it fails.

----

Also marked the issue as ``user-ignored-template-instructions`` because of:

> - [x] I am using the latest version - x.xx.x 
> 
> ``- [x] I am using the latest version - x.xx.x <!-- Check https://github.com/TeamNewPipe/NewPipe/releases -->``

No you are not.

> Version: 0.21.6

As seen in the stack-trace, you are also using @XiangRongLin experimental ``YoutubeThrottlingDecrypter`` from https://github.com/TeamNewPipe/NewPipe/pull/6673
