### ISSUE TITLE
UI crashes on download related actions on Android 11

### ISSUE THREAD

**Issue by johnsonlin** [TeamNewPipe/NewPipe#6806]
### Checklist

- [x] I am using the latest version - 0.21.7 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to 'Downloads'
2. UI crashes and I see error report screen
3. Go to a video and click 'Download'
4. UI crashes and I see error report screen

### Actual behavior

UI crashes and go to error report screen

### Expected behavior

Go to 'Downloads' screen or show download video dialog.

### Logs

Error log for Step 2👇
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ AU
* __Content Language:__ en-AU
* __App Language:__ en_AU
* __Service:__ none
* __Version:__ 0.21.7
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to create service us.shandian.giga.service.DownloadManagerService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4396)
	at android.app.ActivityThread.access$1900(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2117)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8035)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at us.shandian.giga.service.DownloadManager.loadPendingMissions(DownloadManager.java:165)
	at us.shandian.giga.service.DownloadManager.<init>(DownloadManager.java:77)
	at us.shandian.giga.service.DownloadManagerService.onCreate(DownloadManagerService.java:142)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4384)
	... 8 more

```
</details>
<hr>

Error log for Step 4👇

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ AU
* __Content Language:__ en-AU
* __App Language:__ en_AU
* __Service:__ none
* __Version:__ 0.21.7
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to create service us.shandian.giga.service.DownloadManagerService: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4396)
	at android.app.ActivityThread.access$1900(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2117)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8035)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.toString()' on a null object reference
	at us.shandian.giga.service.DownloadManager.loadPendingMissions(DownloadManager.java:165)
	at us.shandian.giga.service.DownloadManager.<init>(DownloadManager.java:77)
	at us.shandian.giga.service.DownloadManagerService.onCreate(DownloadManagerService.java:142)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4384)
	... 8 more

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: Android 11 (Oxygen OS 11.2.8.8)
 - Device model: OnePlus 9

**Comment by dagoogle** [comment]
Likely duplicate, try with this pull #6778 
See #6687
