### ISSUE TITLE
Clicking the 1st comment of this youtube video to expand exists & crashes newpipe to homescreen

### ISSUE THREAD

**Issue by PurpleCodingWizard** [TeamNewPipe/NewPipe#6842]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behavior

Newpipe exists to the homescreen which I believe is a form of crash. This does not invoke Guru Meditation or any other bug report pop-up

### Expected behavior

Expand the comment with ellipsis "..."

### Screenshots/Screen recordings

![The comment which crashes the app in question](https://user-images.githubusercontent.com/34276732/128179619-c85e2eae-6184-45b7-bfe7-1bcd17824744.jpg)

### Device info

 - Android version/Custom ROM version: Android 10, miui 12

 - Device model: Redmi 7a

**Comment by litetex** [comment]
>  I am using the latest version - x.xx.x 
What version are you using?

I'm using 0.21.8 and everything works fine (at least when I watch kurzgesagt videos).

Under what video/comment happens the problem?

**Comment by litetex** [comment]
I managed to find the affected video and comment by myself:
https://www.youtube.com/watch?v=kzqhEZCJ2LQ

This Pinned comment causes the issue:
```
...
https://www.linkedin.com/feed/update/activity:6825845156034482176/
```

```
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.schabi.newpipe.debug, PID: 6853
    java.lang.NumberFormatException: For input string: "6825845156034482176"
        at java.lang.Integer.parseInt(Integer.java:618)
        at java.lang.Integer.parseInt(Integer.java:650)
        at org.schabi.newpipe.info_list.holder.CommentsMiniInfoItemHolder$1.transformUrl(CommentsMiniInfoItemHolder.java:67)
        at android.text.util.Linkify.makeUrl(Linkify.java:616)
        at android.text.util.Linkify.addLinks(Linkify.java:594)
        at android.text.util.Linkify.addLinks(Linkify.java:537)
        at android.text.util.Linkify.addLinks(Linkify.java:470)
        at android.text.util.Linkify.addLinks(Linkify.java:445)
        at org.schabi.newpipe.info_list.holder.CommentsMiniInfoItemHolder.linkify(CommentsMiniInfoItemHolder.java:258)
        at org.schabi.newpipe.info_list.holder.CommentsMiniInfoItemHolder.expand(CommentsMiniInfoItemHolder.java:252)
        at org.schabi.newpipe.info_list.holder.CommentsMiniInfoItemHolder.toggleEllipsize(CommentsMiniInfoItemHolder.java:245)
        at org.schabi.newpipe.info_list.holder.CommentsMiniInfoItemHolder.lambda$updateFromItem$1$CommentsMiniInfoItemHolder(CommentsMiniInfoItemHolder.java:156)
        at org.schabi.newpipe.info_list.holder.-$$Lambda$CommentsMiniInfoItemHolder$0fvlfbx4UGcHQ9bF6ke9G9oLHSM.onClick(Unknown Source:4)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/ACRA: ACRA caught a NumberFormatException for org.schabi.newpipe.debug
    java.lang.NumberFormatException: For input string: "6825845156034482176"
        at java.lang.Integer.parseInt(Integer.java:618)
        at java.lang.Integer.parseInt(Integer.java:650)
        at org.schabi.newpipe.info_list.holder.CommentsMiniInfoItemHolder$1.transformUrl(CommentsMiniInfoItemHolder.java:67)
        at android.text.util.Linkify.makeUrl(Linkify.java:616)
        at android.text.util.Linkify.addLinks(Linkify.java:594)
        at android.text.util.Linkify.addLinks(Linkify.java:537)
        at android.text.util.Linkify.addLinks(Linkify.java:470)
        at android.text.util.Linkify.addLinks(Linkify.java:445)
        at org.schabi.newpipe.info_list.holder.CommentsMiniInfoItemHolder.linkify(CommentsMiniInfoItemHolder.java:258)
        at org.schabi.newpipe.info_list.holder.CommentsMiniInfoItemHolder.expand(CommentsMiniInfoItemHolder.java:252)
        at org.schabi.newpipe.info_list.holder.CommentsMiniInfoItemHolder.toggleEllipsize(CommentsMiniInfoItemHolder.java:245)
        at org.schabi.newpipe.info_list.holder.CommentsMiniInfoItemHolder.lambda$updateFromItem$1$CommentsMiniInfoItemHolder(CommentsMiniInfoItemHolder.java:156)
        at org.schabi.newpipe.info_list.holder.-$$Lambda$CommentsMiniInfoItemHolder$0fvlfbx4UGcHQ9bF6ke9G9oLHSM.onClick(Unknown Source:4)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

Looks like that got matched for the pattern of the video timestamps (e.g. 1:23:45).
