### ISSUE TITLE
Crash when playing PeerTube videos

### ISSUE THREAD

**Issue by 4d30** [TeamNewPipe/NewPipe#6860]
navigated newpipe to the video at
https://watch.breadtube.tv/videos/watch/2a7d96e2-3f4e-432c-97cc-f3774659324f

Newpipe threw the following exception:

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.8
* __OS:__ Linux samsung/crownqltesq/crownqltesq:9/PPR1.180610.011/N960USQU2CSGA:user/release-keys 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NumberFormatException: For input string: ""
	at java.lang.Integer.parseInt(Integer.java:627)
	at java.lang.Integer.parseInt(Integer.java:650)
	at org.schabi.newpipe.util.ListHelper.compareVideoStreamResolution(ListHelper.java:488)
	at org.schabi.newpipe.util.ListHelper.compareVideoStreamResolution(ListHelper.java:503)
	at org.schabi.newpipe.util.ListHelper.lambda$UGNhfSv5KuYwsqrcThyeG189sI0(Unknown Source:0)
	at org.schabi.newpipe.util.-$$Lambda$ListHelper$UGNhfSv5KuYwsqrcThyeG189sI0.compare(Unknown Source:4)
	at java.util.Collections$ReverseComparator2.compare(Collections.java:5226)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1498)
	at java.util.ArrayList.sort(ArrayList.java:1470)
	at java.util.Collections.sort(Collections.java:201)
	at org.schabi.newpipe.util.ListHelper.sortStreamList(ListHelper.java:269)
	at org.schabi.newpipe.util.ListHelper.getSortedStreamVideosList(ListHelper.java:243)
	at org.schabi.newpipe.util.ListHelper.getSortedStreamVideosList(ListHelper.java:130)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.handleResult(VideoDetailFragment.java:1540)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$runWorker$6(VideoDetailFragment.java:893)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$runWorker$6$VideoDetailFragment(Unknown Source:0)
	at org.schabi.newpipe.fragments.detail.-$$Lambda$VideoDetailFragment$X-UcNln23jPsop2TvHe2VPTu0NQ.accept(Unknown Source:8)
	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:6990)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

```
</details>
<hr>

**Comment by 4d30** [comment]
Exception also thrown in version 0.21.9

**Comment by TobiGr** [comment]
will be fixed by #6537

**Comment by yashpalgoyal1304** [comment]
copying over my input from https://github.com/TeamNewPipe/NewPipe/pull/7481#issuecomment-984460590

update: yeah, seems the u are right and also, that issue itself is heading in right direction. as i tried accessing peertube's video from within newpipe (by changing in the sidebar) and yes, opening any video crashed it, and playing it in bg eventually showed the toast that "couldnt play this stream"

**Comment by Discostu36** [comment]
My ticket has been closed and linked to this one, but in my case it is not an audio only stream.

**Comment by 4d30** [comment]
Changed title back to original. Issue is not specific to audio only steams. Confirmed still an issue with version 0.21.16

**Comment by TiA4f8R** [comment]
Most of videos on PeerTube instances have an audio stream, extracted right now by the extractor as a video stream, which is the upstream origin of the crash. The ones without an audio stream plays fine.

That's I wanted to say with `Crash when playing PeerTube videos with audio-only streams`.

See #6537 for more details about the crash and a debuggable APK with the fix.
