### ISSUE TITLE
Seemingly random videos say 'Video not available'

### ISSUE THREAD

**Issue by F7-Trianth** [TeamNewPipe/NewPipe#6910]
### Checklist

- [x] I am using the latest version - 0.21.7, via F-Droid 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behavior

 Video takes an unusually long time to load, and ultimately, does not. This occurs with seemingly random videos, including new videos, and videos I have already watched on newpipe in a previous version. The included example is just one of the many disconnected and connected videos this happens to; there's a few more in the same playlist, even. It is entirely consistent through closing the app, restarting the phone, and reinstalling newpipe entirely. It occurs regardless of the status of my internet connection.

### Expected behavior

Expected video to play.

### Screenshots/Screen recordings

https://dl.dropboxusercontent.com/s/oyihke00desr3ai/Screenshot_20210812-004028.png?dl=0

### Logs

```
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:194)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
	at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$YTHJjScxCJNO1LTCqs3IKy35iyY.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
```

### Device info

 - Android version/Custom ROM version: 10, software version q720qm20f
 - Device model: LM-q720qm

**Comment by TiA4f8R** [comment]
It has been fixed with the 0.21.8 version, now available on F-Droid, by using in addition of the `WEB` YouTube client, the `ANDROID` YouTube client (which has no "protections" of streaming URLs) (to get video and audio formats).

Please do not close the issue, something still needs to be fixed (some regular expressions in NewPipe Extractor) to parse again the formats returned on the `WEB` client.
