### ISSUE TITLE
Startup errors opening videos

### ISSUE THREAD

**Issue by heberjeur** [TeamNewPipe/NewPipe#6976]
### Checklist

- [x] I am using the latest version - 0.21.9
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to search icon , trending menu,what's new, history menu,
2. Press on any video and don't wait thumbnails of videos
3. The crash appears

### Actual behavior

The app crash 10-15 per day, it is really painful to wait 5-7 sec every time when I opened NewPipe !

### Expected behavior

The normal situation that I can use the NewPipe from the first 0 seconds of opening the app

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ TN
* __Content Language:__ fr
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.21.9
* __OS:__ Linux samsung/a50dd/a50:11/RP1A.200720.012/A505FDDU8CUE5:user/release-keys 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.NullPointerException: Attempt to read from field 'androidx.recyclerview.widget.RecyclerView org.schabi.newpipe.databinding.FragmentSearchBinding.suggestionsList' on a null object reference
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:717)
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:714)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onError(LambdaObserver.java:77)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:67)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: java.lang.NullPointerException: Attempt to read from field 'androidx.recyclerview.widget.RecyclerView org.schabi.newpipe.databinding.FragmentSearchBinding.suggestionsList' on a null object reference
	at org.schabi.newpipe.fragments.list.search.SearchFragment.handleSuggestions(SearchFragment.java:971)
	at org.schabi.newpipe.fragments.list.search.SearchFragment.lambda$initSuggestionObserver$15(SearchFragment.java:817)
	at org.schabi.newpipe.fragments.list.search.SearchFragment.lambda$initSuggestionObserver$15$SearchFragment(Unknown Source:0)
	at org.schabi.newpipe.fragments.list.search.-$$Lambda$SearchFragment$q2wTJo-kDxgd91qkgYweNQgQ484.accept(Unknown Source:4)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	... 10 more

```
</details>
<hr>

### Device info

 - Android version: 11
 - Device model: Samsung A50 SM-A505F

**Comment by heberjeur** [comment]
@litetex you see like this bug or not ?

**Comment by litetex** [comment]
No I don't have that error otherwise I would have reported/up-voted it😉 

I can't see an obvious error in the code according to the bug report, so I guess we need more information here.

Does e.g. dis/enabling suggestions fix the problem or any other option that may be related to the problem?
Does it also fail when you reset (clear all app-data) the app? - Keep in mind that you may ant to export your setting first 😉 

Also please fill out the checklist completely (fixed the broken format for you so far) :)

**Comment by mhmdanas** [comment]
Is this still present in the latest version (0.21.2)?

**Comment by heberjeur** [comment]
https://user-images.githubusercontent.com/11852634/138534754-8a612ff9-a46b-4567-b2f9-43b2b6123dff.mp4
