### ISSUE TITLE
Can't Import/Export in anything above version 2.5

### ISSUE THREAD

**Issue by Omar-tamer** [TeamNewPipe/NewPipe#6983]
this might be a device specific issue but, whenever i try to  import, export or even change where my files are downloaded Newpipe crashes and gives me an error 
, ill attach the error report below

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.21.8
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT cat=[android.intent.category.OPENABLE] typ=*/* flg=0x43 (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2076)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1720)
	at android.app.Activity.startActivityForResult(Activity.java:5258)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:574)
	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:234)
	at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:208)
	at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:166)
	at androidx.fragment.app.Fragment$9.launch(Fragment.java:3510)
	at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
	at org.schabi.newpipe.local.subscription.SubscriptionFragment.onImportPreviousSelected(SubscriptionFragment.kt:192)
	at org.schabi.newpipe.local.subscription.SubscriptionFragment.access$onImportPreviousSelected(SubscriptionFragment.kt:68)
	at org.schabi.newpipe.local.subscription.SubscriptionFragment$setupInitialLayout$2.invoke(SubscriptionFragment.kt:268)
	at org.schabi.newpipe.local.subscription.SubscriptionFragment$setupInitialLayout$2.invoke(SubscriptionFragment.kt:68)
	at org.schabi.newpipe.local.subscription.item.FeedImportExportItem$setupImportFromItems$1.onClick(FeedImportExportItem.kt:91)
	at android.view.View.performClick(View.java:7862)
	at android.view.View.performClickInternal(View.java:7831)
	at android.view.View.access$3600(View.java:879)
	at android.view.View$PerformClick.run(View.java:29359)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

```
</details>
<hr>

P.S. if you fix this issue then THX A TON !!!
if not Then......
ALSO THX A TON FOR MAKING NEWPIPE IN THE FIRST PLACE!!!

**Comment by litetex** [comment]
Closing this for now, as it was stated in #6997 that the user uninstalled the built in file manager
