### ISSUE TITLE
closing the app with bug

### ISSUE THREAD

**Issue by frezer26** [TeamNewPipe/NewPipe#7029]
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ AE
* __Content Language:__ ar-AE
* __App Language:__ ar_AE
* __Service:__ none
* __Version:__ 0.21.9
* __OS:__ Linux Android 4.4.4 - 19
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start service org.schabi.newpipe.player.MainPlayer@44780c40 with Intent { cmp=org.schabi.newpipe/.player.MainPlayer (has extras) }: java.lang.NullPointerException
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2872)
	at android.app.ActivityThread.access$2100(ActivityThread.java:155)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1341)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5433)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at org.schabi.newpipe.player.Player.handleIntent(Player.java:674)
	at org.schabi.newpipe.player.MainPlayer.onStartCommand(MainPlayer.java:129)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2855)
	... 10 more

```
</details>
<hr>

**Comment by litetex** [comment]
Same error as in https://github.com/TeamNewPipe/NewPipe/issues/7010

Should be handled with https://github.com/TeamNewPipe/NewPipe/issues/6652
