### ISSUE TITLE
"NumberFormatException" when loading a certain YouTube video

### ISSUE THREAD

**Issue by xxxxme** [TeamNewPipe/NewPipe#7069]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to youtube.com/watch?v=g5ZgUIobSj0 in NewPipe

### Actual behavior

After loading for a short period, an error report screen appears.

### Expected behavior

The video page displays.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.9
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NumberFormatException: For input string: "61803398875"
	at java.lang.Integer.parseInt(Integer.java:618)
	at java.lang.Integer.parseInt(Integer.java:650)
	at org.schabi.newpipe.info_list.holder.CommentsMiniInfoItemHolder$1.transformUrl(CommentsMiniInfoItemHolder.java:64)
	at android.text.util.Linkify.makeUrl(Linkify.java:615)
	at android.text.util.Linkify.addLinks(Linkify.java:593)
	at android.text.util.Linkify.addLinks(Linkify.java:536)
	at android.text.util.Linkify.addLinks(Linkify.java:469)
	at android.text.util.Linkify.addLinks(Linkify.java:444)
	at org.schabi.newpipe.info_list.holder.CommentsMiniInfoItemHolder.linkify(CommentsMiniInfoItemHolder.java:258)
	at org.schabi.newpipe.info_list.holder.CommentsMiniInfoItemHolder.ellipsize(CommentsMiniInfoItemHolder.java:230)
	at org.schabi.newpipe.info_list.holder.CommentsMiniInfoItemHolder.lambda$a9Jqshj_OD1wN932a-ym1V5C7tk(Unknown Source:0)
	at org.schabi.newpipe.info_list.holder.-$$Lambda$CommentsMiniInfoItemHolder$a9Jqshj_OD1wN932a-ym1V5C7tk.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)

```
</details>
<hr>

**Comment by mhmdanas** [comment]
The error is happening because the integer shown in the log is higher (_much_ higher) than the maximum value of a Java integer (which is `2 ** 31 - 1` or `2,147,483,647`). I imagine a possible fix would be using a `long` instead, but I haven't really seen the code.

**Comment by litetex** [comment]
Comment causing the problem:
![grafik](https://user-images.githubusercontent.com/40789489/132914628-342473c2-d185-4332-8ab5-1107c0b4ede9.png)

**Comment by litetex** [comment]
@xxxxme 

This should be fixed with https://github.com/TeamNewPipe/NewPipe/pull/6851

However it wasn't released yet. 
Could you check if the problem still happens with the preview for the next release which is available at https://github.com/TeamNewPipe/NewPipe/issues/7066

**Comment by xxxxme** [comment]
@litetex  The preview release at #7066 fixes the issue for me.
