### ISSUE TITLE
Issue with accessing storage

### ISSUE THREAD

**Issue by sugarcane29** [TeamNewPipe/NewPipe#7073]
The app crashes everytime I try to download anything or import databases.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ IN
* __Content Language:__ en-IN
* __App Language:__ en_IN
* __Service:__ none
* __Version:__ 0.21.9
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT cat=[android.intent.category.OPENABLE] typ=*/* flg=0x43 (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2199)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1860)
	at android.app.Activity.startActivityForResult(Activity.java:4599)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:237)
	at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:210)
	at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:167)
	at androidx.fragment.app.Fragment$9.launch(Fragment.java:3510)
	at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
	at org.schabi.newpipe.settings.ContentSettingsFragment.lambda$onCreatePreferences$0(ContentSettingsFragment.java:79)
	at org.schabi.newpipe.settings.ContentSettingsFragment.lambda$onCreatePreferences$0$ContentSettingsFragment(Unknown Source:0)
	at org.schabi.newpipe.settings.-$$Lambda$ContentSettingsFragment$IJ0-sY_2nFZ8j0D13C6AQ28cAn0.onPreferenceClick(Unknown Source:2)
	at androidx.preference.Preference.performClick(Preference.java:1184)
	at androidx.preference.Preference.performClick(Preference.java:1166)
	at androidx.preference.Preference$1.onClick(Preference.java:181)
	at android.view.View.performClick(View.java:6669)
	at android.view.View.performClickInternal(View.java:6638)
	at android.view.View.access$3100(View.java:789)
	at android.view.View$PerformClick.run(View.java:26145)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```
</details>
<hr>

**Comment by mhmdanas** [comment]
You don't seem to have a file manager installed. Installing one should get the issue fixed. If not, please make a comment.

**Comment by sugarcane29** [comment]
I too thought that was the issue, but my file manager is working properly. 
I'm using a OnePlus 6T, so the default one's there. 
I even installed another one to see if that would provide the hook, but the issue still persists.

**Comment by opusforlife2** [comment]
@sugarcane29 Please try this one: https://f-droid.org/en/packages/me.zhanghai.android.files/

**Comment by sugarcane29** [comment]
@opusforlife2 Thanks for sharing the file explorer. Installing it didn't help.
However, the problem got resolved after untoggling the "Storage Access Framework" setting.
When I turn SAF back on, the app starts crashing again.

**Comment by tsiflimagas** [comment]
It seems to me that oneplus has messed SAF up with its own file manager app.

**Comment by sugarcane29** [comment]
@tsiflimagas That could be the case, but I'm still on Android 9. 
So its possible changes made to make the app for Android 10+, may not be entire backwards compatible.

**Comment by TheBlubb14** [comment]
> 
> 
> @sugarcane29 Please try this one: https://f-droid.org/en/packages/me.zhanghai.android.files/

Im using the Chromecast with GoogleTV and had trouble importing my settings. After multiple different file explorer apps, this finally worked. Thanks!

Can you maybe add this somewhere in the readme or wiki, so other people can try this app when they cannot get the import to work?

**Comment by opusforlife2** [comment]
Thanks for the suggestion. We're currently looking at implementing a more holistic solution.
