### ISSUE TITLE
Not able to download the videos

### ISSUE THREAD

**Issue by gane83** [TeamNewPipe/NewPipe#7076]
When clicking the download button in the application the app is getting closed automatically. Not sure how to get the report for the issue.. please guide to how to get the report that show the issue..

**Comment by mhmdanas** [comment]
Let's start with the necessary information: whate NewPipe version are you using? Device? Android/custom ROM version?

Also, please don't remove the template next time you open an issue. In addition, the bug report template would have suited this issue better, not the question template.

**Comment by gane83** [comment]
NewPipe Version: 0.21.9
Device: Realme RMX2040
Build number: RMX2040_11_C.08
Android version: 11

Note: i tried to install the NewPipe Legacy version 0.20.8 and am able to download the videos successfully.

**Comment by litetex** [comment]
Please provide some logs / screen recordings etc.
Also please fill out the issue according to it's template:
https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by gane83** [comment]
updated the template and provided the link of screen recording.

**Comment by litetex** [comment]
@gane83 
What did you update?
I don't see any changes in this issue...

**Comment by gane83** [comment]
I just filled the issue template you shared. Not able to upload the screen recording video so uploaded in Google drive and shared the link. Let me know if i have collect some other logs from the mobile.

**Comment by mhmdanas** [comment]
Maybe you're making some kind of mistake here; you are supposed to edit the issue body to put in the filled template.

**Comment by litetex** [comment]
Okay I think I found your link in here:
https://github.com/gane83/NewPipe/blob/patch-1/.github/ISSUE_TEMPLATE/bug_report.md

However the provided video is unplayable 🤔

**Comment by gane83** [comment]
Created new captures and uploaded to Google drive - https://drive.google.com/file/d/1YEfnJ-8DZM1BQd97CnxQLDjNUnV-Z5kk/view?usp=drivesdk

**Comment by Uhu-Stick** [comment]
Hello
I think I have the same issue (video download failed)
When I validate the download of a video, the application crashes each time
Here is the crash log ˋ

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ FR
* __Content Language:__ fr-FR
* __App Language:__ fr_FR
* __Service:__ none
* __Version:__ 0.21.9
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE flg=0x43 (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2007)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1673)
	at android.app.Activity.startActivityForResult(Activity.java:4587)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:237)
	at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:210)
	at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:167)
	at androidx.fragment.app.Fragment$9.launch(Fragment.java:3510)
	at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
	at org.schabi.newpipe.download.DownloadDialog.launchDirectoryPicker(DownloadDialog.java:690)
	at org.schabi.newpipe.download.DownloadDialog.prepareSelectedDownload(DownloadDialog.java:749)
	at org.schabi.newpipe.download.DownloadDialog.lambda$initToolbar$1(DownloadDialog.java:359)
	at org.schabi.newpipe.download.DownloadDialog.lambda$initToolbar$1$DownloadDialog(Unknown Source:0)
	at org.schabi.newpipe.download.-$$Lambda$DownloadDialog$QfMS-FoXWFjSoHiNV7JREecQBWg.onMenuItemClick(Unknown Source:2)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:208)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:975)
	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
	at android.view.View.performClick(View.java:6597)
	at android.view.View.performClickInternal(View.java:6574)
	at android.view.View.access$3100(View.java:778)
	at android.view.View$PerformClick.run(View.java:25906)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```
</details>
<hr>



Thanks for tour help

**Comment by litetex** [comment]
@Uhu-Stick 

No I think that's a completely different problem:

> No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE flg=0x43 (has extras) }

Looks like you don't have a file-manager on your device.

Please open a new issue next time and also check for similar issues 😄

**Comment by litetex** [comment]
@gane83 
Hmm can't really get more information from that video...
Is there a crash report when the app closes?

Would also be extremely helpful if you could get the logs when this happens.
Short manual:
> Use [logcat](https://developer.android.com/studio/command-line/logcat) which is shipped with [ADB](https://developer.android.com/studio/command-line/adb)
> 
> There are a [bunch of manual online available](https://www.google.com/search?q=android+get+logs), e.g:
> * https://android.stackexchange.com/a/14431 (recommended)
> * https://wiki.lineageos.org/how-to/logcat#with-a-computer
> * https://stackoverflow.com/a/2888222

**Comment by Relwi** [comment]
I have the same error as @Uhu-Stick and @gane83.
I was trying to get the logcat and the first two attemp the app crashes like @gane83 video and when I tried the third time it appears the same error as @Uhu-Stick in the Error report. In both cases the error was this:

## Exception
* User Action: ui error
* Request: ACRA report
* Content Country: ES
* Content Language: en
* App Language: en
* Service: none
* Version: 0.21.9
* OS: Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>


android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE flg=0x43 (has extras) }
 at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2067)
 at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
 at android.app.Activity.startActivityForResult(Activity.java:5314)
 at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
 at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:237)
 at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:210)
 at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:167)
 at androidx.fragment.app.Fragment$9.launch(Fragment.java:3510)
 at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
 at org.schabi.newpipe.download.DownloadDialog.launchDirectoryPicker(DownloadDialog.java:690)
 at org.schabi.newpipe.download.DownloadDialog.prepareSelectedDownload(DownloadDialog.java:747)
 at org.schabi.newpipe.download.DownloadDialog.lambda$initToolbar$1(DownloadDialog.java:359)
 at org.schabi.newpipe.download.DownloadDialog.lambda$initToolbar$1$DownloadDialog(Unknown Source:0)
 at org.schabi.newpipe.download.-$$Lambda$DownloadDialog$QfMS-FoXWFjSoHiNV7JREecQBWg.onMenuItemClick(Unknown Source:2)
 at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:208)
 at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
 at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
 at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
 at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
 at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:975)
 at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
 at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
 at android.view.View.performClick(View.java:7448)
 at android.view.View.performClickInternal(View.java:7425)
 at android.view.View.access$3600(View.java:810)
 at android.view.View$PerformClick.run(View.java:28305)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:223)
 at android.app.ActivityThread.main(ActivityThread.java:7664)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)


</details>
<hr>

Is like you said @litetex, maybe is that the app doesn't detect a file manager or something, but in previous releases of the app the download feature was working so idk what happens, I have always using the Material Files from F-Droid if this helps.

**Comment by litetex** [comment]
@Relwi 

This is a duplicate of https://github.com/TeamNewPipe/NewPipe/issues/6899 and https://github.com/TeamNewPipe/NewPipe/issues/6729
Found by using the search:
https://github.com/TeamNewPipe/NewPipe/search?q=No+Activity+found+to+handle+Intent+%7B+act%3Dandroid.intent.action.OPEN_DOCUMENT_TREE+flg%3D0x43&type=issues

Btw the same statement in https://github.com/TeamNewPipe/NewPipe/issues/7076#issuecomment-920226578 also counts for you 😉 

---

So I narrowed this down a bit where the problem comes from:

> ... maybe is that the app doesn't detect a file manager or something...

The app works perfectly fine on **standard** android devices.

Your custom OS ``LineageOS`` seems to be the problem as
*  it's seems to be shipped without a file explorer → https://review.lineageos.org/c/LineageOS/android/+/163484
* or it is somehow broken? https://gitlab.com/LineageOS/issues/android/-/issues/884

I can't diagnose this on OS-level any further as I don't use it and don't know the code.

> ...previous releases of the app the download feature was working...

That's because in [v0.21.6](https://github.com/TeamNewPipe/NewPipe/releases/tag/v0.21.6)  https://github.com/TeamNewPipe/NewPipe/pull/5415 was introduced.

> ... always using the Material Files from F-Droid...

This app does not support ``OPEN_DOCUMENT_TREE``:
https://github.com/zhanghai/MaterialFiles/issues/299 → https://github.com/zhanghai/MaterialFiles/issues/153

Workaround for now:
Try disabling SAF in the settings.

**Comment by litetex** [comment]
That the crash UI doesn't work properly could be this problem:
https://github.com/TeamNewPipe/NewPipe/issues/5222

**Comment by Relwi** [comment]
Thank you very much for your help!
Sorry for not informing me about this before (about looking at duplicate or similar issues).
The ROM I have has a file manager but I uninstalled it to install another one so probably was a problem there.
Thanks again!

**Comment by Uhu-Stick** [comment]
I am using "Ghost Commander" as file manager, I just installed the latest beta of it and I can download files again on New Pipe
Thank you for your time

**Comment by Relwi** [comment]
> @Relwi ˋ was your material files up to date?

Yes, is all fine now, I reinstalled the stock file manager and now the app works perfectly!
