### ISSUE TITLE
unable to export database

### ISSUE THREAD

**Issue by pokegamer5547** [TeamNewPipe/NewPipe#7102]
### Checklist

- [x] I am using the latest version - 0.21.9 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Select export database
2. Select the folder using android default native documentsui and click save.

### Actual behavior
After clicking save, newpipe says "sorry something went wrong" and gives report option thus not exporting the database.

### Expected behavior
It should export the database obviously 😅

## Exception
* __User Action:__ ui error
* __Request:__ Exporting database
* __Content Country:__ US
* __Content Language:__ en
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.21.9
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.UnsupportedOperationException
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:174)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
	at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:704)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1816)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1631)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1578)
	at us.shandian.giga.io.FileStreamSAF.<init>(FileStreamSAF.java:32)
	at org.schabi.newpipe.streams.io.StoredFileHelper.getStream(StoredFileHelper.java:195)
	at org.schabi.newpipe.settings.ContentSettingsManager.exportDatabase(ContentSettingsManager.kt:24)
	at org.schabi.newpipe.settings.ContentSettingsFragment.exportDatabase(ContentSettingsFragment.java:202)
	at org.schabi.newpipe.settings.ContentSettingsFragment.requestExportPathResult(ContentSettingsFragment.java:171)
	at org.schabi.newpipe.settings.ContentSettingsFragment.lambda$8bBkxkdGnhK6YvPK6sE5N6ky1yA(Unknown Source:0)
	at org.schabi.newpipe.settings.-$$Lambda$ContentSettingsFragment$8bBkxkdGnhK6YvPK6sE5N6ky1yA.onActivityResult(Unknown Source:4)
	at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:148)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:3026)
	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:589)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:300)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
	at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:3079)
	at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:262)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:510)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1441)
	at android.app.Activity.performStart(Activity.java:8018)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3458)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: Havoc OS 4.8 Android 11
 - Device model: Redmi note 9 pro

**Comment by litetex** [comment]
Did the same on my default Android emulator with Android 11 and no problems at all...
Are there any special settings in the app or on the device active (like animations=off) or any extraordinary steps you did to get the problem?

``Havoc OS 4.8`` I never heard of this OS... 
Looks like a OS problem to me or a very rare race condition...

**Comment by pokegamer5547** [comment]
Walt now i reliazed, in documentsui my phone usually opens app files(or remotes to be precise) with RCX(rclone for android). Maybe that's why it eas showing error, now expoting is working again so i'll close the issue.

**Comment by Mr-Mime** [comment]
I know it is closed but wanted to add, that I got the same error when I wanted to export directly to my nextcloud folder.
Maybe its something with access rights to different storage types (cloud vs. local).  
When I exported to the default phones "Documents" folder it worked fine.
