### ISSUE TITLE
"Play all" fails on a channel that has an upcoming video (i.e. future premiere)

### ISSUE THREAD

**Issue by denilsonsa** [TeamNewPipe/NewPipe#7119]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Find a YouTube channel that has any upcoming video (i.e. video premiere in the future).
2. Open that channel in NewPipe. It will show a list of all videos (the first one will be the unreleased one), with buttons `Background`, `Play All` and `Popup`.
3. Try "Play All".

### Actual behavior

The "Content unavailable" view shows up, with a button to report the error. I cannot skip this video to the next one. In fact, it is impossible to reach the playlist/queue at all from this state.

### Expected behavior

The video should have been skipped, and the rest of the videos should have been played.

In fact, `Background` and `Popup` do work. They both skip the unavailable video and move to the second from the list. So, a workaround would be to start as a popup, and then move back to full screen. (But this workaround is not possible on devices without popup support, such as Android TV.)

### Screenshots/Screen recordings

None needed.

### Logs

None needed.

### Device info

 - Android version/Custom ROM version: 11
 - Device model: Reproduced both on a tablet and on Android TV. Probably reproducible anywhere.

**Comment by dino8890** [comment]
Hi, this same issue happened to me as well, but instead of upcoming video, the song I was listening to was blocked due to copyright reasons (might have been country locked, can't exactly rember) resulting in "Content unavailable" message.

Two videos in this playlist caused the issue:
https://www.youtube.com/watch?v=UD7CgUL_RKQ&list=PLJsbOZ5vMmJiDR_Kq9ayC0ddF5PGJ6AQH&index=1

### Device Info
Android version: 11
Device model: Motorola g9 Plus

**Comment by cbiere** [comment]
Background and Popup crashes. It doesn't skip over. At least not if it's the first item.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ DE
* __Content Language:__ en-DE
* __App Language:__ en_DE
* __Service:__ none
* __Version:__ 0.21.15
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'org.schabi.newpipe.extractor.stream.StreamInfo org.schabi.newpipe.player.resolver.MediaSourceTag.getMetadata()' on a null object reference
	at org.schabi.newpipe.player.Player.onPlayerError(Player.java:2526)
	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$updatePlaybackInfo$10(ExoPlayerImpl.java:1269)
	at com.google.android.exoplayer2.ExoPlayerImpl.$r8$lambda$-K5msfvAakBrxKAsG9AjoK30L1g(Unknown Source:0)
	at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda7.invoke(Unknown Source:4)
	at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(ListenerSet.java:283)
	at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(ListenerSet.java:170)
	at com.google.android.exoplayer2.util.ListenerSet.$r8$lambda$NbKDn9xtItiyMgYZmjIx_Sv1FFQ(Unknown Source:0)
	at com.google.android.exoplayer2.util.ListenerSet$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at com.google.android.exoplayer2.util.ListenerSet.flushEvents(ListenerSet.java:191)
	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:1340)
	at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:1175)
	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$new$1(ExoPlayerImpl.java:216)
	at com.google.android.exoplayer2.ExoPlayerImpl.$r8$lambda$nOBJYkeEQ2uz3sBKLToLWmzrgZk(Unknown Source:0)
	at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda22.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>
<hr>

**Comment by ShareASmile** [comment]
More info [in this comment](https://github.com/TeamNewPipe/NewPipe/issues/3543#issuecomment-1706132396)

**Comment by vibhor-kulshrestha** [comment]
Hi @ShareASmile , I'd like to work on this. I'm a new contributor — can I be assigned this issue?

**Comment by ShareASmile** [comment]
> I'd like to work on this. I'm a new contributor — can I be assigned this issue?

@vibhor-kulshrestha yes, please go ahead, I am assigning it to you & sorry for the late response.
