### ISSUE TITLE
Migration error after updating to 0.21.10

### ISSUE THREAD

**Issue by pinembour** [TeamNewPipe/NewPipe#7144]
### Checklist

- [x] I am using the latest version - 0.21.10 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Update to latest version 0.21.10 from 0.21.9
2. Open the app

### Actual behavior

The app crashes with the error log below.

### Expected behavior

The app doesn't crash.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ FR
* __Content Language:__ fr
* __App Language:__ fr_FR
* __Service:__ none
* __Version:__ 0.21.10
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Migration didn't properly handle: feed_group(org.schabi.newpipe.database.feed.model.FeedGroupEntity).
 Expected:
TableInfo{name='feed_group', columns={name=Column{name='name', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0, defaultValue='null'}, uid=Column{name='uid', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=1, defaultValue='null'}, icon_id=Column{name='icon_id', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=0, defaultValue='null'}, sort_order=Column{name='sort_order', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=0, defaultValue='null'}}, foreignKeys=[], indices=[Index{name='index_feed_group_sort_order', unique=false, columns=[sort_order]}]}
 Found:
TableInfo{name='feed_group', columns={uid=Column{name='uid', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=1, defaultValue='null'}, name=Column{name='name', type='TEXT', affinity='2', notNull=true, primaryKeyPosition=0, defaultValue='null'}, icon_id=Column{name='icon_id', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=0, defaultValue='null'}, sort_order=Column{name='sort_order', type='INTEGER', affinity='3', notNull=true, primaryKeyPosition=0, defaultValue='0'}}, foreignKeys=[], indices=[]}
	at androidx.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.java:103)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(FrameworkSQLiteOpenHelper.java:177)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:416)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:145)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:106)
	at androidx.room.RoomDatabase.internalBeginTransaction(RoomDatabase.java:482)
	at androidx.room.RoomDatabase.beginTransaction(RoomDatabase.java:471)
	at org.schabi.newpipe.database.playlist.dao.PlaylistStreamDAO_Impl$9.call(PlaylistStreamDAO_Impl.java:445)
	at org.schabi.newpipe.database.playlist.dao.PlaylistStreamDAO_Impl$9.call(PlaylistStreamDAO_Impl.java:442)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:47)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.onNext(FlowableFlatMapMaybe.java:131)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:402)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:322)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.runEager(ExecutorScheduler.java:287)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:248)
	at androidx.room.TransactionExecutor$1.run(TransactionExecutor.java:47)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```
</details>
<hr>

**Comment by pinembour** [comment]
The issue also happens on a fresh install if I try to import this  backup.
[NewPipeData-20210804_160527.zip](https://github.com/TeamNewPipe/NewPipe/files/7212407/NewPipeData-20210804_160527.zip)

**Comment by litetex** [comment]
@pinembour 
Hi, thank you for the issue.
It seems like your database is damaged (pretty similar to #3299)

On the right side is a normal/correct database (mine) on the left yours:
![grafik](https://user-images.githubusercontent.com/40789489/135515901-c5b53311-e8ff-4bb8-bdd2-a0a6483ce3d0.png)

I think I managed to repair it, checkout:
[NewPipeData-20210804_160527_fixed.zip](https://github.com/TeamNewPipe/NewPipe/files/7261941/NewPipeData-20210804_160527_fixed.zip)

**Comment by pinembour** [comment]
Thank you, with the fixed export everything seems to work fine.
I have no idea however how the database got corrupted.
