### ISSUE TITLE
Cannot import Youtube subscriptions from youtube

### ISSUE THREAD

**Issue by albynotar** [TeamNewPipe/NewPipe#7203]
### Checklist

- [x] I am using the latest version - 0.21.10 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Click 'Subscriptions' button
2. Click Import from 'YouTube'
3. Click 'IMPORT FILE'

### Actual behavior
The app crashes.

### Expected behavior
The app should give the option to select the zip archive or csv file from your phone storage containing the youtube subscriptions downloaded from google takeout.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/77164768/136085618-d51eb56e-aff9-4216-aeff-bc120e6b8313.mp4

## Exception
* _User Action:_ ui error
* _Request:_ ACRA report
* _Content Country:_ IT
* _Content Language:_ it-IT
* _App Language:_ en
* _Service:_ none
* _Version:_ 0.21.10
* _OS:_ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT cat=[android.intent.category.OPENABLE] typ=*/* flg=0x43 (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2258)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1914)
	at android.app.Activity.startActivityForResult(Activity.java:5326)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
	at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:237)
	at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:210)
	at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:167)
	at androidx.fragment.app.Fragment$9.launch(Fragment.java:3510)
	at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
	at org.schabi.newpipe.local.subscription.SubscriptionsImportFragment.onImportFile(SubscriptionsImportFragment.java:181)
	at org.schabi.newpipe.local.subscription.SubscriptionsImportFragment.onImportClicked(SubscriptionsImportFragment.java:168)
	at org.schabi.newpipe.local.subscription.SubscriptionsImportFragment.lambda$initListeners$0(SubscriptionsImportFragment.java:158)
	at org.schabi.newpipe.local.subscription.SubscriptionsImportFragment.lambda$initListeners$0$SubscriptionsImportFragment(Unknown Source:0)
	at org.schabi.newpipe.local.subscription.-$$Lambda$SubscriptionsImportFragment$4_N3_HtVY3hbG--lTbAQ6l6ErME.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7520)
	at android.view.View.performClickInternal(View.java:7489)
	at android.view.View.access$3600(View.java:826)
	at android.view.View$PerformClick.run(View.java:28555)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8010)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

</details>
<hr>

### Device info

 - Android version/Custom ROM version: Android 11 / OxygenOS 11.0.8.13
 - Device model: Oneplus 8T KB2003

**Comment by mhmdanas** [comment]
See the discussion in #7073. We're looking to improve the situation surrounding this in the future.

**Comment by albynotar** [comment]
@mhmdanas Thank You! Following the advice in #7073 I installed the file manager suggested and the problem is fixed.
