### ISSUE TITLE
annoying crash

### ISSUE THREAD

**Issue by arydevy** [TeamNewPipe/NewPipe#7204]
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.10
* __OS:__ Linux samsung/j2y18lteser/j2y18lte:7.1.1/NMF26X/G998BXWU2ASK1:user/release-keys 11 - 25
<details><summary><b>Crash log </b></summary><p>

```
java.lang.OutOfMemoryError: Failed to allocate a 4355412 byte allocation with 2376032 free bytes and 2MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:700)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:535)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1182)
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:770)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:621)
	at android.content.res.Resources.loadDrawable(Resources.java:1733)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:945)
	at android.widget.ImageView.<init>(ImageView.java:162)
	at android.widget.ImageView.<init>(ImageView.java:150)
	at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:74)
	at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:69)
	at androidx.appcompat.app.AppCompatViewInflater.createImageView(AppCompatViewInflater.java:199)
	at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:119)
	at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1563)
	at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1614)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:873)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:525)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
	at org.schabi.newpipe.databinding.ChannelHeaderBinding.inflate(ChannelHeaderBinding.java:88)
	at org.schabi.newpipe.fragments.list.channel.ChannelFragment.getListHeader(ChannelFragment.java:151)
	at org.schabi.newpipe.fragments.list.BaseListFragment.initViews(BaseListFragment.java:257)
	at org.schabi.newpipe.fragments.list.BaseListInfoFragment.initViews(BaseListInfoFragment.java:50)
	at org.schabi.newpipe.BaseFragment.onViewCreated(BaseFragment.java:68)
	at org.schabi.newpipe.fragments.BaseStateFragment.onViewCreated(BaseStateFragment.java:41)
	at org.schabi.newpipe.fragments.list.channel.ChannelFragment.onViewCreated(ChannelFragment.java:128)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6816)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1565)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1453)

```
</details>
<hr>

**Comment by danmanrana** [comment]
Is that much RAM really needed to run Newpipe if you rarely use any other app?

**Comment by arydevy** [comment]
well want more information is required?
idk what better title to use
