### ISSUE TITLE
Newpipe crashed

### ISSUE THREAD

**Issue by pawanrai9999** [TeamNewPipe/NewPipe#7223]
Opened Newpipe and it crashed
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-IN
* __App Language:__ en_IN
* __Service:__ none
* __Version:__ 0.21.10
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Fragment VideoDetailFragment{d8ee295} (c57fcccc-4c3f-4bcb-b360-37104b7810dc) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:900)
	at org.schabi.newpipe.error.ErrorActivity.reportErrorInSnackbar(ErrorActivity.java:98)
	at org.schabi.newpipe.fragments.BaseStateFragment.showSnackBarError(BaseStateFragment.java:211)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$2.onError(VideoDetailFragment.java:698)
	at com.squareup.picasso.ImageViewAction.error(ImageViewAction.java:72)
	at com.squareup.picasso.Picasso.deliverAction(Picasso.java:581)
	at com.squareup.picasso.Picasso.complete(Picasso.java:528)
	at com.squareup.picasso.Picasso$1.handleMessage(Picasso.java:122)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

```
</details>
<hr>

**Comment by paolostivanin** [comment]
Nope, all good from my side (Android 11)! Thanks :+1:

**Comment by opusforlife2** [comment]
Closing then. Please open a new issue if you encounter this again.
