### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Ranbeer600** [TeamNewPipe/NewPipe#7285]
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.12
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.SecurityException: UID 10315 does not have permission to content://com.android.externalstorage.documents/document/primary%3ANewpipe%2FTHIS%20DIWALI%20BE%20CAREFUL%20_%20Round2Hell%20_%20R2H.mp4 [user 0] [prefix]; you could obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.os.Parcel.readException(Parcel.java:2282)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3695)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1735)
	at android.app.Activity.startActivityForResult(Activity.java:5314)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
	at android.app.Activity.startActivityForResult(Activity.java:5272)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:583)
	at android.app.Activity.startActivity(Activity.java:5658)
	at android.app.Activity.startActivity(Activity.java:5611)
	at org.schabi.newpipe.util.external_communication.ShareUtils.openIntentInApp(ShareUtils.java:144)
	at us.shandian.giga.ui.adapter.MissionAdapter.viewWithFileProvider(MissionAdapter.java:363)
	at us.shandian.giga.ui.adapter.MissionAdapter.access$300(MissionAdapter.java:91)
	at us.shandian.giga.ui.adapter.MissionAdapter$ViewHolderItem.lambda$new$1(MissionAdapter.java:903)
	at us.shandian.giga.ui.adapter.MissionAdapter$ViewHolderItem.$r8$lambda$PAQE6UWV_7gFHr9RCCIksMCusOo(Unknown Source:0)
	at us.shandian.giga.ui.adapter.MissionAdapter$ViewHolderItem$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7448)
	at android.view.View.performClickInternal(View.java:7425)
	at android.view.View.access$3600(View.java:810)
	at android.view.View$PerformClick.run(View.java:28306)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7666)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermissionUnlocked(UriGrantsManagerService.java:1281)
	at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermissionFromIntentUnlocked(UriGrantsManagerService.java:624)
	at com.android.server.uri.UriGrantsManagerService.access$1000(UriGrantsManagerService.java:117)
	at com.android.server.uri.UriGrantsManagerService$LocalService.checkGrantUriPermissionFromIntent(UriGrantsManagerService.java:1443)
	at com.android.server.wm.ActivityStarter$Request.resolveActivity(ActivityStarter.java:530)


```
</details>
<hr>

**Comment by litetex** [comment]
May be a permission problem.

Please [reopen this issue with a proper template](https://github.com/TeamNewPipe/NewPipe/issues/new/choose).

Without any information how this happens we can't fix it.
