### ISSUE TITLE
NewPipe intent from ADB?

### ISSUE THREAD

**Issue by Clooos** [TeamNewPipe/NewPipe#7295]
Hello, I really love this app, using it for a long time, I just wanted to know is there is any way to play a YouTube playlist or any content from an intent (sended from ADB), I want to use Home Assistant to do some automation with NewPipe, it could be a great feature if it's not possible at the moment 🙂 

Thanks again for your work and thank you in advance for your answer 👍

**Comment by mhmdanas** [comment]
To make sure I understand: you have a YouTube URL (that points to a playlist, video, or whatever), and you want to launch it on NewPipe using ADB, right? If so, https://gist.github.com/mick88/1d04309c380bc61aab0616656c1b2aa6 seems to be what you want.

**Comment by Quentin-Cloos** [comment]
> To make sure I understand: you have a YouTube URL (that points to a playlist, video, or whatever), and you want to launch it on NewPipe using ADB, right? If so, https://gist.github.com/mick88/1d04309c380bc61aab0616656c1b2aa6 seems to be what you want.

Yes something like that, but this command will start the playlist directly in YouTube or a browser (not tested), because there is no mention to NewPipe in it.

**Comment by mhmdanas** [comment]
Well, then you need to set the default app for YouTube URLs on your phone to NewPipe.

**Comment by mhmdanas** [comment]
Hmm, then I'm not sure. :/

**Comment by starsep** [comment]
Solution from the gist works for me if no video is playing:
`adb shell am start -a android.intent.action.VIEW -d https://youtu.be/VIDEO_ID`

If some video is playing already then error toast appears and video is paused.
It works properly on the phone, seems Android TV specific.
Logs:
```
ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:587)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.IllegalStateException
        at android.media.MediaCodec.native_setSurface(Native Method)
        at android.media.MediaCodec.setOutputSurface(MediaCodec.java:2043)
        at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.setOutputSurface(SynchronousMediaCodecAdapter.java:183)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:1271)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutput(MediaCodecVideoRenderer.java:562)
        at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:509)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:1504)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:1468)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:1443)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:509)
        at android.os.Handler.dispatchMessage(Handler.java:103) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
```
