### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#7310]
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.13
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int org.schabi.newpipe.player.playqueue.PlayQueue.size()' on a null object reference
	at org.schabi.newpipe.player.helper.PlayerHolder.getQueueSize(PlayerHolder.java:74)
	at org.schabi.newpipe.local.history.StatisticsPlaylistFragment.showStreamDialog(StatisticsPlaylistFragment.java:344)
	at org.schabi.newpipe.local.history.StatisticsPlaylistFragment.access$100(StatisticsPlaylistFragment.java:56)
	at org.schabi.newpipe.local.history.StatisticsPlaylistFragment$1.held(StatisticsPlaylistFragment.java:157)
	at org.schabi.newpipe.local.history.StatisticsPlaylistFragment$1.held(StatisticsPlaylistFragment.java:143)
	at org.schabi.newpipe.local.holder.LocalStatisticStreamItemHolder.lambda$updateFromItem$1(LocalStatisticStreamItemHolder.java:129)
	at org.schabi.newpipe.local.holder.LocalStatisticStreamItemHolder.$r8$lambda$K1bfFLBYmJNdhOJtwG-Fy16Q-Do(Unknown Source:0)
	at org.schabi.newpipe.local.holder.LocalStatisticStreamItemHolder$$ExternalSyntheticLambda1.onLongClick(Unknown Source:4)
	at android.view.View.performLongClickInternal(View.java:8240)
	at android.view.View.performLongClick(View.java:8198)
	at android.view.View.performLongClick(View.java:8216)
	at android.view.View$CheckForLongPress.run(View.java:30194)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8577)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```
</details>
<hr>

**Comment by Stypox** [comment]
Could you test if #7704 solves the issue?
