### ISSUE TITLE
java.lang.NullPointerException: Attempt to read from field on a null object reference

### ISSUE THREAD

**Issue by janTaja** [TeamNewPipe/NewPipe#7379]
### Checklist

- [x] I am using the latest version - 0.21.13 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.* 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

*I think this could be connected to #6696, though? They seem to have the same or a similar error in logs, I can’t tell if this is the same bug or not.

### Steps to reproduce the bug

I can’t reproduce that but I opened a short video (https://www.youtube.com/watch?v=f3WW-Q4LAug), clicked play and entered fullscreen mode. The video was playing in landscape without the image (only sound) for a couple seconds, I was touching the screen while I was waiting for it to load, it switched to portrait and the app crashed

### Actual behavior

Crash

### Expected behavior

Video loading normally without crashing

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.21.13
* __OS:__ Linux samsung/a3y17ltexx/a3y17lte:8.0.0/R16NW/A320FXXU4CRL1:user/release-keys 8.0.0 - 26
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to read from field 'android.widget.TextView org.schabi.newpipe.databinding.FragmentVideoDetailBinding.touchAppendDetail' on a null object reference
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$getOnControlsTouchListener$3(VideoDetailFragment.java:682)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.$r8$lambda$vLEH4pcM9Zih8nQ0ZNDuXPnQ54Y(Unknown Source:0)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda18.run(Unknown Source:2)
	at org.schabi.newpipe.ktx.ViewUtils$animateAlpha$1.onAnimationEnd(View.kt:176)
	at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1122)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1209)
	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1449)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.-wrap2(Unknown Source:0)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:655)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: Android 8.0.0
 - Device model: Samsung Galaxy A3 (2017) / a3y17lte

**Comment by TacoTheDank** [comment]
@janTaja Hi, does this issue still occur on version 0.22.1?

**Comment by TacoTheDank** [comment]
Interesting... In that case I will close it. If it somehow happens again, feel free to open another issue :)
