### ISSUE TITLE
Crash while tilting - Android 12

### ISSUE THREAD

**Issue by Feuerswut** [TeamNewPipe/NewPipe#7393]
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ DE
* __Content Language:__ de-DE
* __App Language:__ de
* __Service:__ none
* __Version:__ 0.21.13
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalArgumentException: View=android.widget.PopupWindow$PopupDecorView{3d742c4 V.E...... R.....ID 0,0-515,756} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:534)
	at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:423)
	at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:140)
	at android.widget.PopupWindow.update(PopupWindow.java:2210)
	at android.widget.PopupWindow.update(PopupWindow.java:2331)
	at android.widget.PopupWindow.update(PopupWindow.java:2432)
	at android.widget.PopupWindow.update(PopupWindow.java:2381)
	at android.widget.ListPopupWindow.show(ListPopupWindow.java:683)
	at android.widget.ListPopupWindow$PopupDataSetObserver.onChanged(ListPopupWindow.java:1321)
	at android.database.DataSetObservable.notifyChanged(DataSetObservable.java:37)
	at android.widget.BaseAdapter.notifyDataSetChanged(BaseAdapter.java:54)
	at com.android.internal.view.menu.MenuAdapter.notifyDataSetChanged(MenuAdapter.java:120)
	at com.android.internal.view.menu.StandardMenuPopup.updateMenuView(StandardMenuPopup.java:251)
	at com.android.internal.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:273)
	at com.android.internal.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:1008)
	at com.android.internal.view.menu.MenuBuilder.removeGroup(MenuBuilder.java:536)
	at org.schabi.newpipe.player.Player.buildQualityMenu(Player.java:3380)
	at org.schabi.newpipe.player.Player.updateStreamRelatedViews(Player.java:3328)
	at org.schabi.newpipe.player.Player.onPlaying(Player.java:2131)
	at org.schabi.newpipe.player.Player.changeState(Player.java:2065)
	at org.schabi.newpipe.player.Player.onPlayerStateChanged(Player.java:1996)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$6(ExoPlayerImpl.java:1443)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.$r8$lambda$b8AtGdawGxQCz-_rX1H1__vkxF4(Unknown Source:0)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate$$ExternalSyntheticLambda10.invokeListener(Unknown Source:2)
	at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:279)
	at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:1498)
	at com.google.android.exoplayer2.ExoPlayerImpl.access$100(ExoPlayerImpl.java:56)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.run(ExoPlayerImpl.java:1440)
	at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:1328)
	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:956)
	at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:920)
	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$new$0(ExoPlayerImpl.java:162)
	at com.google.android.exoplayer2.ExoPlayerImpl.$r8$lambda$Krt_XK5S7OaAWWQo8WMLuiuwNGE(Unknown Source:0)
	at com.google.android.exoplayer2.ExoPlayerImpl$$ExternalSyntheticLambda5.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```
</details>
<hr>

While tilting screen on Android 12 (Pixel 6)

**Comment by sstraightea** [comment]
I'm having a similar issue on Android 13.

The error occurs _sometimes_ when rotating the view or changing the resolution. Sometimes it happens when a video ends, and in a few cases also just randomly during playback. 

My crash log is the following:

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_FAILED_RUNTIME_CHECK] occurred while playing https://www.youtube.com/watch?v=wdBGCI0_wfg
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ YouTube
* __Version:__ 0.24.1
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.lang.IllegalArgumentException
	at android.media.MediaCodec.native_setSurface(Native Method)
	at android.media.MediaCodec.setOutputSurface(MediaCodec.java:2233)
	at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter$$ExternalSyntheticApiModelOutline0.m(Unknown Source:0)
	at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.setOutputSurface(AsynchronousMediaCodecAdapter.java:262)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:1451)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutput(MediaCodecVideoRenderer.java:646)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:584)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:1546)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:1510)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:1485)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:521)
	... 4 more

```
</details>
<hr>

**Comment by opusforlife2** [comment]
@sstraightea You're looking for #9329. This is a different error.

**Comment by Feuerswut** [comment]
Can't repro with recent version
