### ISSUE TITLE
CheckForNewAppVersion randomly fails (when app is in background)

### ISSUE THREAD

**Issue by homocomputeris** [TeamNewPipe/NewPipe#7397]
### Checklist

- [x] I am using the latest version - 0.21.13 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

No idea. NewPipe popped up from background with the error message.

### Actual behavior

NewPipe popped up from background with the error message.

### Expected behavior

Do not pop up with random

### Device info

 - Android version/Custom ROM version: lineage_enchilada-userdebug 11 RQ3A.211001.001 10036215
 - Device model: OnePlus 6

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ RU
* __Content Language:__ ru-RU
* __App Language:__ ru_RU
* __Service:__ none
* __Version:__ 0.21.13
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.schabi.newpipe/.CheckForNewAppVersion }: app is in background uid UidRecord{27dcaf3 u0a248 CAC  bg:+1m47s807ms idle change:idle procs:1 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1715)
	at android.app.ContextImpl.startService(ContextImpl.java:1670)
	at android.content.ContextWrapper.startService(ContextWrapper.java:720)
	at org.schabi.newpipe.CheckForNewAppVersion.startNewVersionCheckService(CheckForNewAppVersion.java:258)
	at org.schabi.newpipe.MainActivity.onPostCreate(MainActivity.java:175)
	at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1383)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3484)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:58)
	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:5414)
	at android.app.ActivityThread.access$3300(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2076)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>
<hr>

**Comment by litetex** [comment]
The same error occurred here: #7357

Developer note:
Maybe a try-catch block helps?

**Comment by ANUKULJHA1506** [comment]
can u assign me this issue
