### ISSUE TITLE
Importing YouTube Abos from CSV fails with exception

### ISSUE THREAD

**Issue by Fruchtzwerg94** [TeamNewPipe/NewPipe#7411]
### Checklist

- [x] I am using the latest version - 0.21.13 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Go to Menu
2. G to Abos
3. Import from YouTube
4. Select CSV file

### Actual behavior
Exception showed at importing the CSV file

### Expected behavior
Import successful

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ DE
* __Content Language:__ de-DE
* __App Language:__ de_DE
* __Service:__ none
* __Version:__ 0.21.13
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start service org.schabi.newpipe.local.subscription.services.SubscriptionsImportService@e2486eb with Intent { cmp=org.schabi.newpipe/.local.subscription.services.SubscriptionsImportService (has extras) }: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{66aa690 7020:org.schabi.newpipe/u0a306} (pid=7020, uid=10306) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4657)
	at android.app.ActivityThread.access$2000(ActivityThread.java:247)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7838)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{66aa690 7020:org.schabi.newpipe/u0a306} (pid=7020, uid=10306) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
	at android.os.Parcel.createException(Parcel.java:2409)
	at android.os.Parcel.readException(Parcel.java:2392)
	at android.os.Parcel.readException(Parcel.java:2334)
	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5850)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:6972)
	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3336)
	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2526)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1844)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1675)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1622)
	at us.shandian.giga.io.FileStreamSAF.<init>(FileStreamSAF.java:32)
	at org.schabi.newpipe.streams.io.StoredFileHelper.getStream(StoredFileHelper.java:195)
	at org.schabi.newpipe.local.subscription.services.SubscriptionsImportService.onStartCommand(SubscriptionsImportService.java:118)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4639)
	... 9 more

```
</details>
<hr>

### Device info
 - Android version/Custom ROM version: Android 12
 - Device model: Google Pixel 4 5G

**Comment by litetex** [comment]
> Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{66aa690 7020:org.schabi.newpipe/u0a306} (pid=7020, uid=10306) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs

Looks like a permission is missing or something similar (maybe the file is protected by something?).
Might be related to Android 12.

**Comment by Fruchtzwerg94** [comment]
> 
> 
> > Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{66aa690 7020:org.schabi.newpipe/u0a306} (pid=7020, uid=10306) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
> 
> Looks like a permission is missing or something similar (maybe the file is protected by something?). Might be related to Android 12.

Since I also stumpled over problems liks this in some of my projects, I've also tried to place the file at different locations (Download, Movies, ...) unfortunately without success.

**Comment by R030t1** [comment]
I moved it into Music and still get a crash. The documentation references subscriptions being provided as json, not csv. The format is expected?

**Comment by Fruchtzwerg94** [comment]
Hi @R030t1

CSV is definitively expected. This is a translation issue which I've already fixed for the german language in the Weblate translation project.

**Comment by litetex** [comment]
> I moved it into Music and still get a crash.

Could you paste the crash/exception here?

**Comment by Pentazer** [comment]
Also getting this problem. Attempting to import the csv says "could not import subscriptions." I also tried using this:
https://juandarr.github.io/json-youtube-export/
To create a subscriptions json file but that file also returns the same problem.

**Comment by wh0isit** [comment]
A workaround is to download a video first. This triggers the folder permission screen and the csv will import successfully.

**Comment by azazar** [comment]
It crashes when I try to import YouTube subscriptions from CSV.

Version: 0.23.0 downloaded from F-Droid

```
java.lang.RuntimeException: Unable to start service org.schabi.newpipe.local.subscription.services.SubscriptionsImportService@b4ce94b with Intent { cmp=org.schabi.newpipe/.local.subscription.services.SubscriptionsImportService (has extras) }: java.lang.IllegalArgumentException: Media is read-only
 at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4500)
 at android.app.ActivityThread.access$2100(ActivityThread.java:261)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2063)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:236)
 at android.app.ActivityThread.main(ActivityThread.java:8051)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
Caused by: java.lang.IllegalArgumentException: Media is read-only
 at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
 at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
 at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:704)
 at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1841)
 at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1656)
 at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1603)
 at us.shandian.giga.io.FileStreamSAF.<init>(FileStreamSAF.java:32)
 at org.schabi.newpipe.streams.io.StoredFileHelper.getStream(StoredFileHelper.java:195)
 at org.schabi.newpipe.local.subscription.services.SubscriptionsImportService.onStartCommand(SubscriptionsImportService.java:118)
 at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4477)
 ... 8 more
```

**Comment by WhyNotHugo** [comment]
Same issue here on LineageOS 18 (Android 11).

**Comment by arima0k** [comment]
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.23.0
* __OS:__ Linux Android 12 - 32
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start service org.schabi.newpipe.local.subscription.services.SubscriptionsImportService@dfad024 with Intent { cmp=org.schabi.newpipe/.local.subscription.services.SubscriptionsImportService (has extras) }: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{a8fd2b0 8100:org.schabi.newpipe/u0a171} (pid=8100, uid=10171) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4724)
	at android.app.ActivityThread.access$2000(ActivityThread.java:256)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2129)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{a8fd2b0 8100:org.schabi.newpipe/u0a171} (pid=8100, uid=10171) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
	at android.os.Parcel.createException(Parcel.java:2409)
	at android.os.Parcel.readException(Parcel.java:2392)
	at android.os.Parcel.readException(Parcel.java:2334)
	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5907)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:7010)
	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3365)
	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2526)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1844)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1675)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1622)
	at us.shandian.giga.io.FileStreamSAF.<init>(FileStreamSAF.java:32)
	at org.schabi.newpipe.streams.io.StoredFileHelper.getStream(StoredFileHelper.java:195)
	at org.schabi.newpipe.local.subscription.services.SubscriptionsImportService.onStartCommand(SubscriptionsImportService.java:118)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4706)
	... 9 more

```
</details>
<hr>

**Comment by StayFN** [comment]
Same Issue here.  
Moving it from the Download Folder into Music still works for me.

**Comment by RenanSD007** [comment]
For me when the file was in the Download folder Newpipe crashed but when I moved the file to the Documents folder the file imported successfully :)

**Comment by chris122380** [comment]
I couldn't import the subscriptions.csv from Download, Documents, or Music folder.  

Newpipe 0.28.7

**Comment by ShareASmile** [comment]
Please test apk from #13535 and report back.

**Comment by ShareASmile** [comment]
> I couldn't import the subscriptions.csv from Download, Documents, or Music folder.
> 
> Newpipe 0.28.7

Your issue is due to recent regression #13442, not this one, it looks.
