### ISSUE TITLE
Parsing Error - Soundcloud

### ISSUE THREAD

**Issue by Feuerswut** [TeamNewPipe/NewPipe#7413]
When searching SoundCloud:
could not parse JSON response.

## Exception
* __User Action:__ get suggestions
* __Request:__ a
* __Content Country:__ 
* __Content Language:__ de-
* __App Language:__ de
* __Service:__ SoundCloud
* __Version:__ 0.21.13
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse json response
	at org.schabi.newpipe.extractor.services.soundcloud.extractors.SoundcloudSuggestionExtractor.suggestionList(SoundcloudSuggestionExtractor.java:48)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$suggestionsFor$2(ExtractorHelper.java:107)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$kgV3vMftlbQH0zdv8hszrHLyMLU(Unknown Source:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda8.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleToObservable.subscribeActual(SingleToObservable.java:35)
	at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13102)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
	at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13102)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableZip$ZipCoordinator.subscribe(ObservableZip.java:110)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableZip.subscribeActual(ObservableZip.java:72)
	at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13102)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableMaterialize.subscribeActual(ObservableMaterialize.java:28)
	at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13102)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableSwitchMap$SwitchMapObserver.onNext(ObservableSwitchMap.java:127)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver$DelayErrorInnerObserver.onNext(ObservableConcatMap.java:498)
	at io.reactivex.rxjava3.observers.SerializedObserver.onNext(SerializedObserver.java:113)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableDebounceTimed$DebounceTimedObserver.emit(ObservableDebounceTimed.java:143)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableDebounceTimed$DebounceEmitter.run(ObservableDebounceTimed.java:168)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: com.grack.nanojson.JsonParserException: Expected JSON value, got 0 on line 1, char 0
	at com.grack.nanojson.JsonTokener.createParseException(Unknown Source:44)
	at com.grack.nanojson.JsonParser.currentValue(Unknown Source:31)
	at com.grack.nanojson.JsonParser.parse(Unknown Source:4)
	at com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source:19)
	at org.schabi.newpipe.extractor.services.soundcloud.extractors.SoundcloudSuggestionExtractor.suggestionList(SoundcloudSuggestionExtractor.java:40)
	... 26 more

```
</details>
<hr>

**Comment by mstempell** [comment]
Same problem here, exact same error trace, with this URL, coming from an instagram story click (the instagram "story" itself was the result of a track shared from soundcloud):
`https://soundcloud.com/dma-sc/what-have-you-done?ref=instagram&p=a&c=1&si=c0f717e597d44a30ab31f86dad762788&utm_campaign=social_sharing&utm_medium=story&utm_source=instagram`

**Comment by 84436** [comment]
I got the exact same error and the same stack trace when I attempt to*:
• get autocomplete hints when typing on the search bar
• search for a song
• open a SoundCloud link to a song from third-party apps (e.g. browsers)
• open a SoundCloud link to an artist's profile from third-party apps (e.g. browsers)

Apparently SoundCloud support has been broken for a while; I guess this has something to do with NewPipeExtractor failing to parse the website/API response due to changes on SoundCloud's side? I'm not too well-versed in these backend things so I'm sorry if my input isn't helpful.

\* tested on my physical device:
NewPipe `0.21.16` (latest at the time of this writing)
Android 11 (`RKQ1.210503.001`)
MIUI Stable `12.5.14.0`
Xiaomi, Mi 11 Lite 5G NE (codename: `lisa`)

**Comment by opusforlife2** [comment]
@Feuerswut?

**Comment by Feuerswut** [comment]
yes?

**Comment by opusforlife2** [comment]
Thanks. I needed you to state the reason for future readers to understand.
