### ISSUE TITLE
404 HTTP error when loading thumbnail of a video

### ISSUE THREAD

**Issue by homocomputeris** [TeamNewPipe/NewPipe#7416]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Open https://www.youtube.com/watch?v=fk32u6__sRM

### Actual behavior

An error message appears at the bottom of the screen

### Expected behavior

No error

## Exception
* User Action: load image
* Request: https://i.ytimg.com/vi_webp/fk32u6__sRM/maxresdefault.webp
* Content Country: RU
* Content Language: ru-RU
* App Language: ru_RU
* Service: YouTube
* Version: 0.21.13
* OS: Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

com.squareup.picasso.NetworkRequestHandler$ResponseException: HTTP 404
 at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:51)
 at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:219)
 at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:175)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:923)
 at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:354)

</details>
<hr>

### Device info

 - Android version/Custom ROM version: LineageOS 18.1
 - Device model: OnePlus 6

**Comment by litetex** [comment]
Is this still a problem in the latest version?

**Comment by BrightDV** [comment]
> Is this still a problem in the latest version?

I tried with 0.21.16 and the bug is still there, it is the thumbnail which is causing the problem

**Comment by litetex** [comment]
Hmm I think there is something broken on YT itself, because the thumbnail is also missing there:
![grafik](https://user-images.githubusercontent.com/40789489/153720211-e521c39e-8529-48f5-883f-dfd649167a97.png)

**Comment by opusforlife2** [comment]
But we should be able to handle it more gracefully?

**Comment by TobiGr** [comment]
Correct, we should detect the that the exception is network related

**Comment by homocomputeris** [comment]
## Exception
* __User Action:__ load image
* __Request:__ https://i.ytimg.com/vi_webp/fk32u6__sRM/maxresdefault.webp
* __Content Country:__ RU
* __Content Language:__ ru-RU
* __App Language:__ ru_RU
* __Service:__ YouTube
* __Version:__ 0.21.16
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
com.squareup.picasso.NetworkRequestHandler$ResponseException: HTTP 404
	at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:51)
	at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:219)
	at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
	at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:354)

```
</details>
<hr>

**Comment by homocomputeris** [comment]
Opens fine on YouTube

**Comment by AudricV** [comment]
Like said before, such issues are from the services itself (I got the same issue for a PeerTube video recently) and there is nothing we can do, except not logging such issues: that's done with #10066.
