### ISSUE TITLE
Crash when importing Youtube subscriptions

### ISSUE THREAD

**Issue by Jykke76** [TeamNewPipe/NewPipe#7450]
### Checklist

- [x] I am using the latest version - 0.21.13 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to Subscritions import from > Youtube 
2. Press on IMPORT FILE
3. Crash
4. Can be produced every time

### Actual behavior

AP/UI crashed

### Expected behavior

No crash

### Logs

Notes!, [27.11.2021 12.05]
## Exception
* User Action: ui error
* Request: ACRA report
* Content Country: US
* Content Language: en-US
* App Language: en_US
* Service: none
* Version: 0.21.13
* OS: Linux Android 7.0 - 24
<details><summary><b>Crash log </b></summary><p>

android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT cat=[android.intent.category.OPENABLE] typ=*/* flg=0x43 (has extras) }
 at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1809)
 at android.app.Instrumentation.execStartActivity(Instrumentation.java:1523)
 at android.app.Activity.startActivityForResult(Activity.java:4224)
 at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
 at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:237)
 at androidx.activity.ComponentActivity$2.onLaunch(ComponentActivity.java:210)
 at androidx.activity.result.ActivityResultRegistry$2.launch(ActivityResultRegistry.java:167)
 at androidx.fragment.app.Fragment$9.launch(Fragment.java:3510)
 at androidx.activity.result.ActivityResultLauncher.launch(ActivityResultLauncher.java:47)
 at org.schabi.newpipe.local.subscription.SubscriptionsImportFragment.onImportFile(SubscriptionsImportFragment.java:181)
 at org.schabi.newpipe.local.subscription.SubscriptionsImportFragment.onImportClicked(SubscriptionsImportFragment.java:168)
 at org.schabi.newpipe.local.subscription.SubscriptionsImportFragment.lambda$initListeners$0(SubscriptionsImportFragment.java:158)
 at org.schabi.newpipe.local.subscription.SubscriptionsImportFragment.$r8$lambda$4_N3_HtVY3hbG--lTbAQ6l6ErME(SubscriptionsImportFragment.java)
 at org.schabi.newpipe.local.subscription.SubscriptionsImportFragment$$ExternalSyntheticLambda0.onClick(Unknown Source)
 at android.view.View.performClick(View.java:5609)
 at android.view.View$PerformClick.run(View.java:22262)
 at android.os.Handler.handleCallback(Handler.java:751)
 at android.os.Handler.dispatchMessage(Handler.java:95)
 at android.os.Looper.loop(Looper.java:154)
 at android.app.ActivityThread.main(ActivityThread.java:6097)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1041)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:931)

</details>
<hr>

### Device info

 - Android version/Custom ROM version: 1.6.1
 - Device model: Formuler CC

**Comment by litetex** [comment]
See also #7113

----
https://github.com/TeamNewPipe/NewPipe/issues/6729#issuecomment-886230249

Looks like you have no file-manager...
Can you check if you have one?

**Comment by Jykke76** [comment]
> See also #7113
> 
> [#6729 (comment)](https://github.com/TeamNewPipe/NewPipe/issues/6729#issuecomment-886230249)
> 
> Looks like you have no file-manager... Can you check if you have one?

Sot sure how to do that. Please advice

**Comment by litetex** [comment]
> Not sure how to do that. Please advise

Check if you have an app installed which let's you explore files.

You likely won't have one (as the exception above says) so either install one like https://f-droid.org/en/packages/me.zhanghai.android.files/ or try to disable "Use system folder picker (SAF)" in the download-settings.

**Comment by Jykke76** [comment]
Ok, after installing "Material Files" the crash does not occur anymore.
