### ISSUE TITLE
Subscription import/export options hidden behind secret UI action

### ISSUE THREAD

**Issue by opusforlife2** [TeamNewPipe/NewPipe#7453]
### Checklist

- [x] I am using the latest version - 0.21.3 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Subscribe to at least one channel.
2. Open the Subscriptions tab.

### Actual behavior

The import/export options get collapsed into the Subscriptions header. From this point, if a user is not already aware of the fact that the header needs to be tapped to expand the import/export options again, then it probably seems like Newpipe only offers this functionality once.

### Expected behavior

The import/export options should be placed somewhere visible, or the action to make them visible should be very obvious to Android users. Or, just don't automatically collapse the header. Let the user figure out how to do that manually.

Another suggestion is given in #7047 (option 2b).

### Context

https://github.com/TeamNewPipe/NewPipe/issues/7326#issuecomment-980270339

**Comment by litetex** [comment]
@TobiGr 
Checkout #7458

**Comment by noormohammedb** [comment]
Encountered crash on 22.1 when importing subscription's list from take out


`## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.22.1
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start service org.schabi.newpipe.local.subscription.services.SubscriptionsImportService@7a3bebd with Intent { cmp=org.schabi.newpipe/.local.subscription.services.SubscriptionsImportService (has extras) }: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{3bd6a55 30257:org.schabi.newpipe/u0a340} (pid=30257, uid=10340) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4399)
	at android.app.ActivityThread.access$1900(ActivityThread.java:244)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1989)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7861)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{3bd6a55 30257:org.schabi.newpipe/u0a340} (pid=30257, uid=10340) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2376)
	at android.os.Parcel.createException(Parcel.java:2360)
	at android.os.Parcel.readException(Parcel.java:2343)
	at android.os.Parcel.readException(Parcel.java:2285)
	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5933)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:6973)
	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2954)
	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2509)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1827)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1658)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1605)
	at us.shandian.giga.io.FileStreamSAF.<init>(FileStreamSAF.java:32)
	at org.schabi.newpipe.streams.io.StoredFileHelper.getStream(StoredFileHelper.java:195)
	at org.schabi.newpipe.local.subscription.services.SubscriptionsImportService.onStartCommand(SubscriptionsImportService.java:118)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4376)
	... 8 more

```
</details>
<hr>

`

**Comment by TacoTheDank** [comment]
@noormohammedb This does not go here; it belongs in #7411. Please refrain from posting crashlogs in unrelated issues.
