### ISSUE TITLE
TV Fullscreen error when clicking recommended videos

### ISSUE THREAD

**Issue by wifislow** [TeamNewPipe/NewPipe#7504]
### Checklist

- [x] I am using the latest version - 0.21.13 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behavior

Selecting recommended videos causes "Unrecoverable player error" and video doesn't open in fullscreen.

### Expected behavior

Selecting recommended videos should open videos in fullscreen like it does when you search for and click on a video.

### Device info

 - Android version/Custom ROM version: Android 9 Pie (android version irrelevant)
 - Device model: Sony BRAVIA Android TV (model irrelevant)

**Comment by Bugginme** [comment]
Issue occurs on phones/tablet tested, running NewPipe 0.21.15. Issue doesnt occur when fullscreen toggle is off  in settings, fullscreen issues seem to be connected.

**Comment by marcostux06** [comment]
This error still persists :-/

## Exception
* User Action: ui error
* Request: ACRA report
* Content Country: US
* Content Language: es-US
* App Language: es_US
* Service: none
* Version: 0.23.3
* OS: Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

java.lang.RuntimeException: Unable to start service org.schabi.newpipe.player.MainPlayer@41c2b29 with Intent { cmp=org.schabi.newpipe/.player.MainPlayer (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context org.schabi.newpipe.player.Player.getContext()' on a null object reference
 at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3721)
 at android.app.ActivityThread.access$1600(ActivityThread.java:200)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:193)
 at android.app.ActivityThread.main(ActivityThread.java:6744)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context org.schabi.newpipe.player.Player.getContext()' on a null object reference
 at org.schabi.newpipe.player.NotificationUtil.createNotification(NotificationUtil.java:92)
 at org.schabi.newpipe.player.NotificationUtil.createNotificationAndStartForeground(NotificationUtil.java:179)
 at org.schabi.newpipe.player.MainPlayer.onStartCommand(MainPlayer.java:126)
 at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3702)
 ... 8 more

**Comment by marcostux06** [comment]
> @marcostux06 You've posted the same crash report on 2 issues. Do you get this using the steps posted in the issue description? Does the crash vanish if you toggle off "Start player in fullscreen"?

No, sorry, the crash continues

**Comment by opusforlife2** [comment]
@marcostux06 Then your comments are off-topic here. Hiding.

**Comment by ShareASmile** [comment]
Is it still an issue on 0.26.1?

**Comment by marcostux06** [comment]
> Is it still an issue on 0.26.1?

Yes, that has been solved, the error that still persists is when you want to put any video you are watching in full screen, this only happens on Android TV.
