### ISSUE TITLE
Live listening FC

### ISSUE THREAD

**Issue by 9Orlaf2** [TeamNewPipe/NewPipe#7513]
### Checklist

- [x] I am using the latest version - 0.21.13 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Connect to a "not stable" network.
2. Open a live video (of songs for example).
3. Listen it in background.

### Actual behavior

The app shows an error about the "interruption of the video data" and once opened again in foreground it crashes.

### Logs

```
java.lang.RuntimeException: Error receiving broadcast Intent { act=org.schabi.newpipe.debug.seamlesstransitionplayers.VideoDetailFragment.ACTION_VIDEO_FRAGMENT_RESUMED flg=0x10 } in org.schabi.newpipe.player.Player$3@5996f45
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1815)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8582)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:220)
	at org.schabi.newpipe.player.Player.useVideoSource(Player.java:4149)
	at org.schabi.newpipe.player.Player.onBroadcastReceived(Player.java:1171)
	at org.schabi.newpipe.player.Player.access$200(Player.java:205)
	at org.schabi.newpipe.player.Player$3.onReceive(Player.java:1098)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1805)
	... 9 more
``` 

### Device info

 - Android version/Custom ROM version:
 12/One Ui 4.0
 - Device model:
S21

**Comment by mhmdanas** [comment]
It seems like you're using the APK from #7349, not a stable NewPipe version. Please try to reproduce this issue on 0.21.13 proper. If you can consistently reproduce with #7349's APK but not on 0.21.13, please post a comment on #7349 with a link to this issue.

**Comment by 9Orlaf2** [comment]
> It seems like you're using the APK from #7349, not a stable NewPipe version. Please try to reproduce this issue on 0.21.13 proper. If you can consistently reproduce with #7349's APK but not on 0.21.13, please post a comment on #7349 with a link to this issue.

I'll try...

**Comment by 9Orlaf2** [comment]
Ok this is seems a problem of the specific build taken from this pull https://github.com/TeamNewPipe/NewPipe/pull/7349

The problem in question (from what I understand) is related to cache. In practice it's not big enough to always make this PR work correctly.

**Comment by mhmdanas** [comment]
I posted a comment in #7513. Seeing as this is an issue with the PR, closing the issue.
