### ISSUE TITLE
Video loading / buffering Crash.

### ISSUE THREAD

**Issue by Monstanner** [TeamNewPipe/NewPipe#7528]
### Checklist

- [x] I am using the latest version - 0.21.14 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Actual behavior

If you choose to start a video in the background or in the pop-up, it can happen if the video is still loading in the background and you want to add another one to the playlist, so that NewPipe then crashes.

### Expected behavior

Newpipe shouldn't crash.

### Device info

 - Android version/Custom ROM version: Android 10 Vanilla
 - Device model: Nokia 6.1

**Comment by osjasmine** [comment]
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.14
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int org.schabi.newpipe.player.playqueue.PlayQueue.size()' on a null object reference
	at org.schabi.newpipe.player.helper.PlayerHolder.getQueueSize(PlayerHolder.java:74)
	at org.schabi.newpipe.fragments.list.BaseListFragment.showStreamDialog(BaseListFragment.java:358)
	at org.schabi.newpipe.fragments.list.BaseListFragment$1.held(BaseListFragment.java:282)
	at org.schabi.newpipe.fragments.list.BaseListFragment$1.held(BaseListFragment.java:274)
	at org.schabi.newpipe.info_list.holder.StreamMiniInfoItemHolder.lambda$enableLongClick$1(StreamMiniInfoItemHolder.java:136)
	at org.schabi.newpipe.info_list.holder.StreamMiniInfoItemHolder.$r8$lambda$mm6ASq2GCzBAsOq1wCHCNeC_Fv4(Unknown Source:0)
	at org.schabi.newpipe.info_list.holder.StreamMiniInfoItemHolder$$ExternalSyntheticLambda1.onLongClick(Unknown Source:4)
	at android.view.View.performLongClickInternal(View.java:7960)
	at android.view.View.performLongClick(View.java:7910)
	at android.view.View.performLongClick(View.java:7928)
	at android.view.View$CheckForLongPress.run(View.java:29321)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7948)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

```
</details>
<hr>

A similar thing happens in my case as well. When I start playing a video in background or popup and then, while the video has not yet loaded, I try to start another video in background or popup (by long pressing the video) the app crashes (in fact the crash happens just by long pressing the video). 
Also for some reason this only happens if there is no video shown as now playing. Like if there is a video shown/loaded (it can be paused), and then you repeat the above steps for reproducing the crash, the crash wont happen. Basically as long as there is a video loaded, the crash doesnt happen.

**Comment by Stypox** [comment]
Could you test if #7704 solves the issue?

**Comment by osjasmine** [comment]
Not the author but I would haved liked to test the changes but just cant figure out how to download the debug apk. 
I followed the steps listed in the pull but I cant seem to be able to click the artifact ("app") in order to initiate the download. Its seems to be not a clickable link.

**Comment by opusforlife2** [comment]
@osjasmine You need to be signed in to do it. Github limitation.

**Comment by osjasmine** [comment]
Oh thanks that worked, downloaded the apk.

And the pull request fixed the crash for me (thank you).
