### ISSUE TITLE
Exception in NewPipe 0.20.1

### ISSUE THREAD

**Issue by superbfahad** [TeamNewPipe/NewPipe#7536]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [ ] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Device info

 - Android version/Custom ROM version: MIUI 12.5.3 Android: 11
 - Device model: Redmi Note 8 Pro

**Comment by SameenAhnaf** [comment]
Please fill in the template properly. Devs are unable to help with such a little amount of information. Also, make sure to use the latest version 0.21.4 before opening an issue.

**Comment by 0xTyagi** [comment]
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en
* __App Language:__ en_IN
* __Service:__ none
* __Version:__ 0.21.14
* __OS:__ Linux Android 7.0 - 24
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.IWindowSession.performDeferredDestroy(android.view.IWindow)' on a null object reference
	at android.view.SurfaceView.updateWindow(SurfaceView.java:658)
	at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:255)
	at android.view.View.dispatchDetachedFromWindow(View.java:15437)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3222)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4758)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4732)
	at android.view.ViewGroup.removeView(ViewGroup.java:4663)
	at org.schabi.newpipe.player.MainPlayer.removeViewFromParent(MainPlayer.java:240)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.removeVideoPlayerView(VideoDetailFragment.java:1305)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.hideMainPlayerOnLoadingNewStream(VideoDetailFragment.java:1225)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$runWorker$6(VideoDetailFragment.java:908)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.$r8$lambda$X-UcNln23jPsop2TvHe2VPTu0NQ(VideoDetailFragment.java)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda11.accept(Unknown Source)
	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6077)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

```
</details>
<hr>
