### ISSUE TITLE
Sorry that should not have happened. Guru Meditation 

### ISSUE THREAD

**Issue by veeralakrishna** [TeamNewPipe/NewPipe#7541]
## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=KK_TlPkmCZk
* __Content Country:__ IN
* __Content Language:__ en-IN
* __App Language:__ en_IN
* __Service:__ YouTube
* __Version:__ 0.21.13
* __OS:__ Linux Android 11 - 30
<details><summary><b>Exceptions (2)</b></summary><p>
<details><summary><b>Crash log 1</b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get like count
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getLikeCount(Unknown Source:91)
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractOptionalData(Unknown Source:168)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(Unknown Source:11)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(Unknown Source:4)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(Unknown Source:4)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(Unknown Source:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda6.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(Unknown Source:16)
	at io.reactivex.rxjava3.core.Single.subscribe(Unknown Source:14)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(Unknown Source:7)
	at io.reactivex.rxjava3.core.Single.subscribe(Unknown Source:14)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(Unknown Source:7)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Unknown Source:14)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(Unknown Source:90)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(Unknown Source:11)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(Unknown Source:20)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(Unknown Source:7)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Unknown Source:15)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(Unknown Source:9)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Unknown Source:14)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(Unknown Source:9)
	at io.reactivex.rxjava3.core.Single.subscribe(Unknown Source:14)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(Unknown Source:2)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Unknown Source:9)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(Unknown Source:13)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: org.schabi.newpipe.extractor.exceptions.ParsingException: Ratings are enabled even though the like button is missing
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getLikeCount(Unknown Source:76)
	... 30 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getLikeCount(Unknown Source:32)
	... 30 more

```
</details>
<details><summary><b>Crash log 2</b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get dislike count
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getDislikeCount(Unknown Source:91)
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractOptionalData(Unknown Source:180)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(Unknown Source:11)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(Unknown Source:4)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(Unknown Source:4)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(Unknown Source:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda6.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(Unknown Source:16)
	at io.reactivex.rxjava3.core.Single.subscribe(Unknown Source:14)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(Unknown Source:7)
	at io.reactivex.rxjava3.core.Single.subscribe(Unknown Source:14)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(Unknown Source:7)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Unknown Source:14)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(Unknown Source:90)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(Unknown Source:11)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(Unknown Source:20)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(Unknown Source:7)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Unknown Source:15)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(Unknown Source:9)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Unknown Source:14)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(Unknown Source:9)
	at io.reactivex.rxjava3.core.Single.subscribe(Unknown Source:14)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(Unknown Source:2)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Unknown Source:9)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(Unknown Source:13)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: org.schabi.newpipe.extractor.exceptions.ParsingException: Ratings are enabled even though the dislike button is missing
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getDislikeCount(Unknown Source:76)
	... 30 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String[] java.lang.String.split(java.lang.String)' on a null object reference
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getDislikeCount(Unknown Source:32)
	... 30 more

```
</details>
</p></details>
<hr>

**Comment by TiA4f8R** [comment]
Update to version 0.21.14 to fix the issue.

Please use [our issue templates](https://github.com/TeamNewPipe/NewPipe/issues/new/choose) the next time you want to open an issue, in order to avoid to report known issues or feature requests. Thank you!
