### ISSUE TITLE
App crashed on subscription csv file import 

### ISSUE THREAD

**Issue by subhrm** [TeamNewPipe/NewPipe#7547]
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.13
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start service org.schabi.newpipe.local.subscription.services.SubscriptionsImportService@8156733 with Intent { cmp=org.schabi.newpipe/.local.subscription.services.SubscriptionsImportService (has extras) }: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{36581b6 11696:org.schabi.newpipe/u0a423} (pid=11696, uid=10423) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4802)
	at android.app.ActivityThread.access$1900(ActivityThread.java:301)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2204)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{36581b6 11696:org.schabi.newpipe/u0a423} (pid=11696, uid=10423) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2385)
	at android.os.Parcel.createException(Parcel.java:2369)
	at android.os.Parcel.readException(Parcel.java:2352)
	at android.os.Parcel.readException(Parcel.java:2294)
	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:6701)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:7764)
	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3090)
	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2491)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1810)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1641)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1588)
	at us.shandian.giga.io.FileStreamSAF.<init>(FileStreamSAF.java:32)
	at org.schabi.newpipe.streams.io.StoredFileHelper.getStream(StoredFileHelper.java:195)
	at org.schabi.newpipe.local.subscription.services.SubscriptionsImportService.onStartCommand(SubscriptionsImportService.java:118)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4784)
	... 8 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:9027)
	at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:8866)
	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:9567)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2851)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3628)


```
</details>
<hr>

**Comment by XiangRongLin** [comment]
https://github.com/TeamNewPipe/NewPipe/issues/7411
