### ISSUE TITLE
Crash on tap and hold in search results while bg queue is loading

### ISSUE THREAD

**Issue by yashpalgoyal1304** [TeamNewPipe/NewPipe#7608]
### Checklist

- [x] I am using the latest version - 0.21.15 (see this: [comment] )
I am using the older version - 0.21.13
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
gh 🔍 : [crash on click and hold search result] ; [crash on search result]
- [x] I have read the contribution guidelines given at [CONTRIBUTING.md].
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

[crash on click and hold search result]: https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+crash+on+tap+and+hold+search+result+is%3Aclosed
[crash on search result]: https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+crash+on+search+result+is%3Aopen

[CONTRIBUTING.md]: https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md
[comment]: https://github.com/TeamNewPipe/NewPipe/issues/7608#issuecomment-1008247813

### Steps to reproduce the bug

1. Search for anything
2. Press and hold on any search result
3. Tap on "Start playing in the bg"
4. Quickly repeat step 2, i.e. before the song loads and starts playing
5. Confirmed crash

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/19423063/147868057-b71eb9d6-f4af-4e41-ab1d-74f578dc4605.mp4

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.13
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int org.schabi.newpipe.player.playqueue.PlayQueue.size()' on a null object reference
	at org.schabi.newpipe.player.helper.PlayerHolder.getQueueSize(PlayerHolder.java:74)
	at org.schabi.newpipe.fragments.list.BaseListFragment.showStreamDialog(BaseListFragment.java:358)
	at org.schabi.newpipe.fragments.list.BaseListFragment$1.held(BaseListFragment.java:282)
	at org.schabi.newpipe.fragments.list.BaseListFragment$1.held(BaseListFragment.java:274)
	at org.schabi.newpipe.info_list.holder.StreamMiniInfoItemHolder.lambda$enableLongClick$1(StreamMiniInfoItemHolder.java:136)
	at org.schabi.newpipe.info_list.holder.StreamMiniInfoItemHolder.$r8$lambda$mm6ASq2GCzBAsOq1wCHCNeC_Fv4(Unknown Source:0)
	at org.schabi.newpipe.info_list.holder.StreamMiniInfoItemHolder$$ExternalSyntheticLambda1.onLongClick(Unknown Source:4)
	at android.view.View.performLongClickInternal(View.java:7665)
	at android.view.View.performLongClick(View.java:7623)
	at android.view.View.performLongClick(View.java:7641)
	at android.view.View$CheckForLongPress.run(View.java:28822)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:261)
	at android.app.ActivityThread.main(ActivityThread.java:8259)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: realme UI V2.0
 - Device model: realme RMX3381

**Comment by yashpalgoyal1304** [comment]
Can anyone reproduce this on latest version of newpipe and post their findings?

**Comment by BrightDV** [comment]
Same result occurs for me on 0.21.15

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ FR
* __Content Language:__ fr-FR
* __App Language:__ fr_FR
* __Service:__ none
* __Version:__ 0.21.15
* __OS:__ Linux samsung/a21snseea/a21s:11/RP1A.200720.012/A217FXXU7CUI7:user/release-keys 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int org.schabi.newpipe.player.playqueue.PlayQueue.size()' on a null object reference
	at org.schabi.newpipe.player.helper.PlayerHolder.getQueueSize(PlayerHolder.java:74)
	at org.schabi.newpipe.fragments.list.BaseListFragment.showStreamDialog(BaseListFragment.java:358)
	at org.schabi.newpipe.fragments.list.BaseListFragment$1.held(BaseListFragment.java:282)
	at org.schabi.newpipe.fragments.list.BaseListFragment$1.held(BaseListFragment.java:274)
	at org.schabi.newpipe.info_list.holder.StreamMiniInfoItemHolder.lambda$enableLongClick$1(StreamMiniInfoItemHolder.java:136)
	at org.schabi.newpipe.info_list.holder.StreamMiniInfoItemHolder.$r8$lambda$mm6ASq2GCzBAsOq1wCHCNeC_Fv4(Unknown Source:0)
	at org.schabi.newpipe.info_list.holder.StreamMiniInfoItemHolder$$ExternalSyntheticLambda1.onLongClick(Unknown Source:4)
	at android.view.View.performLongClickInternal(View.java:8240)
	at android.view.View.performLongClick(View.java:8198)
	at android.view.View.performLongClick(View.java:8216)
	at android.view.View$CheckForLongPress.run(View.java:30194)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```
</details>
<hr>

**Comment by ndr1224** [comment]
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ TR
* __Content Language:__ tr
* __App Language:__ tr
* __Service:__ none
* __Version:__ 0.21.15
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Fragment RelatedItemsFragment{eea796} (6d389a1b-a5db-414c-968b-71f0829e5f70) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:900)
	at org.schabi.newpipe.fragments.list.videos.RelatedItemsFragment.onSharedPreferenceChanged(RelatedItemsFragment.java:173)
	at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:637)
	at android.app.SharedPreferencesImpl$EditorImpl.lambda$notifyListeners$0$SharedPreferencesImpl$EditorImpl(SharedPreferencesImpl.java:643)
	at android.app.-$$Lambda$SharedPreferencesImpl$EditorImpl$3CAjkhzA131V3V-sLfP2uy0FWZ0.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7666)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>
<hr>

**Comment by Stypox** [comment]
Could you test if #7704 solves the issue?

**Comment by yashpalgoyal1304** [comment]
> Could you test if #7704 solves the issue?

hey so, i tested that. 
* it didnt crash, but 
* it didnt enqueue either. 
* What more, it deceptively showed the toast "Enqueue" 
* so... i will not consider the issue to be fixed, the issue just became less severe
* the false showing of enqueue toast is something bad

**Comment by Stypox** [comment]
> What more, it deceptively showed the toast "Enqueued"

You are right, I'm going to fix this, thank you for the feedback. Up until the play queue is ready it's not possible to do any action with the player, so I'll just consider the player as closed when that's the case and show the stream dialog with the closed-player-entries.

**Comment by yashpalgoyal1304** [comment]
> so I'll just consider the player as closed when that's the case

i know that's a very stupid question of mine, but can the player & queue starting logic be improved - at least surfacially. say like 
* making the player with empty queue ready before hand, or like 
* shifting the logic so that the time consuming part can be put later

is this a relatively new problem that player takes so long to start, or was it this way from starting?

**Comment by Stypox** [comment]
I completely agree with you, and there is a separate issue exactly for that: #7673 :-)

**Comment by badsha000000** [comment]
Hi **Yashpalgoyal1304,** 
       Are you using Realme8s 5g??
Did you unlock your bootloader ?

I am **realme 8s (RMS3381)** user. On this device Realme UI if fully filled with bugs and some other problems. I just want to change my rom. Can you help me?

U want to unlock bootloader and root my device. 

No in-depth apk works

**Comment by yashpalgoyal1304** [comment]
> Realme UI if fully filled with bugs and some other problems. I just want to change my rom

this is OT for this issue. I am available at telegram if you want to talk directly with me. share your username here, and i will get back to you there.

**Comment by badsha000000** [comment]
My telegram id  @SkylarRohit

**Comment by badsha000000** [comment]
My telegram id
@SkylarRohit

@yashpalgoyal1304
