### ISSUE TITLE
Crash report ( java.lang.SecurityException ) despite successful file download

### ISSUE THREAD

**Issue by SamTada** [TeamNewPipe/NewPipe#7696]
### Checklist

- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Download video
2. Go to Downloads in Settings
3. Select video
4. Crash report

### Actual behavior

Can not open video file from within NewPipe app although it is confirmedly present in Internal Storage Downloads. The file itself is fine and opening well in other apps.

### Expected behavior

Access youtube-like videos in app for clarity.

⮕ Note:
There was a similar issue  Crash #7285 opened on 20 Oct 2021 and closed on 04 Nov 2021 due to lack of response from the author when requested for more information.
Consequently it had no follow-up, suggested fix, nor can I add any comment to it.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.21.15
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.SecurityException: UID 10332 does not have permission to content://com.android.providers.downloads.documents/document/219 [user 0] [prefix]; you could obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2376)
	at android.os.Parcel.createException(Parcel.java:2360)
	at android.os.Parcel.readException(Parcel.java:2343)
	at android.os.Parcel.readException(Parcel.java:2285)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3939)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1733)
	at android.app.Activity.startActivityForResult(Activity.java:5444)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
	at android.app.Activity.startActivityForResult(Activity.java:5395)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:583)
	at android.app.Activity.startActivity(Activity.java:5795)
	at android.app.Activity.startActivity(Activity.java:5748)
	at org.schabi.newpipe.util.external_communication.ShareUtils.openIntentInApp(ShareUtils.java:144)
	at us.shandian.giga.ui.adapter.MissionAdapter.viewWithFileProvider(MissionAdapter.java:363)
	at us.shandian.giga.ui.adapter.MissionAdapter.access$300(MissionAdapter.java:91)
	at us.shandian.giga.ui.adapter.MissionAdapter$ViewHolderItem.lambda$new$1(MissionAdapter.java:903)
	at us.shandian.giga.ui.adapter.MissionAdapter$ViewHolderItem.$r8$lambda$PAQE6UWV_7gFHr9RCCIksMCusOo(Unknown Source:0)
	at us.shandian.giga.ui.adapter.MissionAdapter$ViewHolderItem$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7509)
	at android.view.View.performClickInternal(View.java:7486)
	at android.view.View.access$3600(View.java:841)
	at android.view.View$PerformClick.run(View.java:28720)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8059)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermissionUnlocked(UriGrantsManagerService.java:1249)
	at com.android.server.uri.UriGrantsManagerService.checkGrantUriPermissionFromIntentUnlocked(UriGrantsManagerService.java:618)
	at com.android.server.uri.UriGrantsManagerService.access$1000(UriGrantsManagerService.java:118)
	at com.android.server.uri.UriGrantsManagerService$LocalService.checkGrantUriPermissionFromIntent(UriGrantsManagerService.java:1422)
	at com.android.server.wm.ActivityStarter$Request.resolveActivity(ActivityStarter.java:564)


```
</details>
<hr>

### Device info

 - Android 11 / MIUI Global 12.5.6
 - Device model: M2101K6G

**Comment by slappyslap** [comment]
Same error and android 11 & newpipe v0.22.0

**Comment by ShareASmile** [comment]
Is it still an issue on 0.26.1?

**Comment by ccpp** [comment]
Same here in current fdroid version 0.72.2.
Any workaround for this?
