### ISSUE TITLE
No video in split screen

### ISSUE THREAD

**Issue by Dakkaron** [TeamNewPipe/NewPipe#7711]
### Checklist

- [x] I am using the latest version - 0.21.15 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

On Android 11:
1. Open and start a video
2. Enable split screen view
3. Push the split a bit to the top, so that there is just enough space for the video

### Actual behavior
The video is gone (black) audio, subtitles and controls are still working.

### Expected behavior
The video should stay visible.

### Screenshots/Screen recordings

<img src="https://user-images.githubusercontent.com/6311558/151515380-0588dbc1-a787-4f70-ac58-1069fd4cd45e.png" height=500 />

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=hhqMiqJerTw
* __Content Country:__ GB
* __Content Language:__ en
* __App Language:__ de_AT
* __Service:__ YouTube
* __Version:__ 0.21.15
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getStreamSegments(YoutubeStreamExtractor.java:1335)
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractOptionalData(StreamInfo.java:333)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:73)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(Unknown Source:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda6.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: Android 11, stock
 - Device model: Fairphone 4

**Comment by litetex** [comment]
Thank you for the report.

However this works as expected on a stock Android 11 emulator:
![grafik](https://user-images.githubusercontent.com/40789489/151604822-76de64ba-951f-4d99-aacb-9d929f0bff16.png)

Does the problem also appear on other videos?
Is the crash related to the above problem?

**Comment by Dakkaron** [comment]
It's not always reproducible on my phone. Maybe once in 3 tries. Sometimes it does work.

I am not sure if the crash log is really causing the problem, but it coincides in timing.

**Comment by Dakkaron** [comment]
If it's helpful, I could try to replicate it with logcat running and give you the output. Maybe there is something useful in there.

**Comment by litetex** [comment]
> If it's helpful, I could try to replicate it with logcat running and give you the output. Maybe there is something useful in there.

Sounds great.
Would definitely help here 😄

**Comment by Dakkaron** [comment]
Sorry for the late answer. The problem still exists in the newest version. Here are some parts form the logcat that look relevant to me:

```02-25 10:04:34.493 15267 15267 W Player  : Broadcast receiver already unregistered: Receiver not registered: org.schabi.newpipe.player.Player$4@6b5437d
02-25 10:04:34.500 15267 15510 E VideoFrameReleaseHelper: Failed to call Surface.setFrameRate
02-25 10:04:34.500 15267 15510 E VideoFrameReleaseHelper:   java.lang.IllegalStateException: Surface has already been released.
02-25 10:04:34.500 15267 15510 E VideoFrameReleaseHelper:       at android.view.Surface.checkNotReleasedLocked(Surface.java:698)
02-25 10:04:34.500 15267 15510 E VideoFrameReleaseHelper:       at android.view.Surface.setFrameRate(Surface.java:929)
02-25 10:04:34.500 15267 15510 E VideoFrameReleaseHelper:       at com.google.android.exoplayer2.video.VideoFrameReleaseHelper.setSurfaceFrameRateV30(VideoFrameReleaseHelper.java:368)
02-25 10:04:34.500 15267 15510 E VideoFrameReleaseHelper:       at com.google.android.exoplayer2.video.VideoFrameReleaseHelper.updateSurfacePlaybackFrameRate(VideoFrameReleaseHelper.java:349)
02-25 10:04:34.500 15267 15510 E VideoFrameReleaseHelper:       at com.google.android.exoplayer2.video.VideoFrameReleaseHelper.onSurfaceChanged(VideoFrameReleaseHelper.java:166)
02-25 10:04:34.500 15267 15510 E VideoFrameReleaseHelper:       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutput(MediaCodecVideoRenderer.java:555)
02-25 10:04:34.500 15267 15510 E VideoFrameReleaseHelper:       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:509)
02-25 10:04:34.500 15267 15510 E VideoFrameReleaseHelper:       at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:1504)
02-25 10:04:34.500 15267 15510 E VideoFrameReleaseHelper:       at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:1468)
02-25 10:04:34.500 15267 15510 E VideoFrameReleaseHelper:       at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:1443)
02-25 10:04:34.500 15267 15510 E VideoFrameReleaseHelper:       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:509)
02-25 10:04:34.500 15267 15510 E VideoFrameReleaseHelper:       at android.os.Handler.dispatchMessage(Handler.java:102)
02-25 10:04:34.500 15267 15510 E VideoFrameReleaseHelper:       at android.os.Looper.loop(Looper.java:223)
02-25 10:04:34.500 15267 15510 E VideoFrameReleaseHelper:       at android.os.HandlerThread.run(HandlerThread.java:67)```

```
02-25 10:04:34.656  1714  4353 I MediaFocusControl: abandonAudioFocus() from uid/pid 10274/15267 clientId=android.media.AudioManager@426d13corg.schabi.newpipe.player.helper.AudioReactor@8af8ec5
02-25 10:04:34.658  1714  1714 W AS.AudioService: couldn't find receiver package for effect intent
02-25 10:04:34.659  1714  4353 D MediaSessionService: Media button session is changed to null
02-25 10:04:34.665 15267 15267 I ExoPlayerImpl: Init 19e001a [ExoPlayerLib/2.14.2] [FP4, FP4, Fairphone, 30]
02-25 10:04:34.671  1714  4353 D MediaSessionService: Media button session is changed to org.schabi.newpipe/MediaSessionManager (userId=0)
02-25 10:04:31.248  1714  2401 I Nat464Xlat: Android Xlat is disabled
02-25 10:04:34.708  1714  1714 D NotificationService: 0|org.schabi.newpipe|123789|null|10274: granting content://settings/system/notification_sound
02-25 10:04:34.728  2507  2507 D InterruptionStateProvider: No alerting: filtered notification: 0|org.schabi.newpipe|123789|null|10274
02-25 10:04:34.729  2507  2507 D InterruptionStateProvider: No alerting: filtered notification: 0|org.schabi.newpipe|123789|null|10274
02-25 10:04:34.734 15267 15522 D SeekbarPrevThumbHolder: Clearing seekbarPreviewData
02-25 10:04:34.734 15267 15522 D SeekbarPrevThumbHolder: Strategy for seekbarPreviewData: high quality
02-25 10:04:34.745 15267 15520 D CacheFactory: initExoPlayerCache: cacheDir = /storage/emulated/0/Android/data/org.schabi.newpipe/cache/exoplayer
02-25 10:04:34.746  2507  2507 V MediaTimeout: processState: null
02-25 10:04:34.746  2507  2507 V MediaTimeout: schedule timeout for 0|org.schabi.newpipe|123789|null|10274
02-25 10:04:34.746  2507  2507 D MediaResumeListener: Checking for service component for org.schabi.newpipe
```

```
02-25 10:04:38.281  4316 19641 D iris@ForegroundUtils: Id: 15267 ProcessName: org.schabi.newpipe  Label: NewPipe
02-25 10:04:38.281  4316 19641 D iris@ForegroundUtils: dispatchActivityChanged: pkg = org.schabi.newpipe
02-25 10:04:38.283  4316 19641 D iris@ForegroundUtils: dispatchActivityChanged: 1234, pkg = org.schabi.newpipe
02-25 10:04:38.283  4316 19641 D iris@ForegroundUtils: dispatchActivityChanged: 2222
02-25 10:04:38.283  4316 19641 D nxt@AbsFeatrueService: onUidToForeground2() called with: pkg = [org.schabi.newpipe], cls = [], activityType = [-1]
02-25 10:04:38.283  4316 19641 D Iris3EnhanceService: doCheckSdr2Hdr() called with: pkg = [org.schabi.newpipe], cls = [], activityType = [-1]
02-25 10:04:38.284  4316 19641 D Iris3EnhanceService: doCheckSdr2Hdr() called with: pkg = [org.schabi.newpipe], cls = [], activityType = [-11]
02-25 10:04:38.284  4316 19641 D nxt@BaseService: onCheckSdrTohdrDecoding() called with: currentPkg = [org.schabi.newpipe] isDecoding = false mDecodingPkg: null
02-25 10:04:38.284  4316 19641 W nxt@Iris6CmdUtil: SET A IRIS6 CMD from last setp closeMultimediaEnhancementInternal to closeReadingmode
02-25 10:04:38.284  4316 19641 D nxt@BaseService: checkNotification() called with: pkg = [org.schabi.newpipe]
```

```
02-25 10:04:38.486  4316 19641 D nxt@Iris6CmdUtil: openVideoOrGameEnhanceForWhiteList: pkg=org.schabi.newpipefalsefalsefalse
```

```
02-25 10:04:38.571 15267 15550 D CCodecBufferChannel: [c2.android.aac.decoder#562] MediaCodec discarded an unknown buffer
02-25 10:04:38.571 15267 15550 I chatty  : uid=10274(org.schabi.newpipe) identical 2 lines
02-25 10:04:38.571 15267 15550 D CCodecBufferChannel: [c2.android.aac.decoder#562] MediaCodec discarded an unknown buffer
```

```
02-25 10:04:48.814  1018  1018 E Layer   : [Bounds for - org.schabi.newpipe/org.schabi.newpipe.MainActivity#0] No local sync point found
02-25 10:04:48.831  1018  1018 E Layer   : [SurfaceView - org.schabi.newpipe/org.schabi.newpipe.MainActivity#0] No local sync point found
```

**Comment by Dakkaron** [comment]
Here is another logcat output with what I believe is the actual error.

```
org.schabi.newpipe.App : RxJavaPlugin: Undeliverable Exception received: 
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not store JavaScript player
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.storePlayerJs(YoutubeStreamExtractor.java:1104)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.initStsFromPlayerJsIfNeeded(YoutubeStreamExtractor.java:1172)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:826)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:78)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:73)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:118)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(Unknown Source:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda6.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15868)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: org.schabi.newpipe.extractor.exceptions.ParsingException: Embedded info did not provide YouTube player js url
	at org.schabi.newpipe.extractor.services.youtube.YoutubeJavaScriptExtractor.extractJavaScriptUrl(YoutubeJavaScriptExtractor.java:116)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeJavaScriptExtractor.extractJavaScriptCode(YoutubeJavaScriptExtractor.java:46)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeJavaScriptExtractor.extractJavaScriptCode(YoutubeJavaScriptExtractor.java:65)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.storePlayerJs(YoutubeStreamExtractor.java:1102)
	... 32 more
```

**Comment by opusforlife2** [comment]
This latest log can't be caused the same way as your other described steps in this issue.

First of all, do the description steps still work for the latest version?

**Comment by Dakkaron** [comment]
Yes, the issue is still the same. I tested it with a lot of different video apps (VLC, Prime, real YouTube, YouTube in a browser, Disney Plus) and it doesn't occur on any other app.

It could also be that there is no error thrown at all, and I'm just reporting concurrent error messages, that also appear when changing the split screen size.

Every once in a while (~1 in 20 tries) the error also doesn't trigger and video playback is fine.

I can reproduce a related (if not the same) issue on the Android 11 emulator:

![grafik](https://user-images.githubusercontent.com/6311558/195812604-85ce647a-9443-4d85-b945-359e1accaebf.png)

As you can see, the image is shifted and part of it is stuck. On the emulator this happens ~1 in 3 times.

I've seen similar things on my physical device, where, after resizing the split screen, the image is shifted partially outside the viewport. I could imagine that the "black screen" issue is actually an "image is shifted fully outside of the viewport" issue.

**Comment by ShareASmile** [comment]
Is it still an issue on 0.26.1?
