### ISSUE TITLE
UI Crash

### ISSUE THREAD

**Issue by aravind-alpha07** [TeamNewPipe/NewPipe#7722]
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.15
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1844)
	at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1884)
	at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:329)
	at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:294)
	at androidx.fragment.app.DialogFragment.show(DialogFragment.java:260)
	at org.schabi.newpipe.RouterActivity.lambda$openDownloadDialog$19(RouterActivity.java:646)
	at org.schabi.newpipe.RouterActivity.$r8$lambda$--0YcizsE0Kz2-_9bdoMW02jdkQ(Unknown Source:0)
	at org.schabi.newpipe.RouterActivity$$ExternalSyntheticLambda14.accept(Unknown Source:4)
	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loopOnce(Unknown Source:176)
	at android.os.Looper.loop(Unknown Source:76)
	at android.app.ActivityThread.main(Unknown Source:138)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:306)

```
</details>
<hr>

**Comment by Magicfulness** [comment]
Is this related to my bug report, #7825? I doubt it, but posting just in case.

**Comment by mhmdanas** [comment]
@Magicfulness the errors are different, so I don't think so.

@aravind-alpha07 don't delete the template please, the error is not enough for us to figure out the issue. What were you doing when the crash happened? Can you reproduce it reliably? What is your device?
