### ISSUE TITLE
What is Guru Meditation template

### ISSUE THREAD

**Issue by Isssuemaker** [TeamNewPipe/NewPipe#7757]
#6949

**Comment by mhmdanas** [comment]
Please don't remove the issue template when opening an issue. In any case, I don't understand you, can you clarify?

**Comment by Isssuemaker** [comment]
What is Guru Meditation meaning in Newpipe

**Comment by mhmdanas** [comment]
It means that an error happened. It's a reference to https://en.wikipedia.org/wiki/Guru_meditation.

Anyway, can you share the error by pressing the report button? You're probably facing #7734, but I'd like to be certain before closing this.

**Comment by Isssuemaker** [comment]
> It means that an error happened. It's a reference to https://en.wikipedia.org/wiki/Guru_meditation.
> 
> Anyway, can you share the error by pressing the report button? You're probably facing #7734, but I'd like to be certain before closing this.

Yes it is same issue when will it get resolved

**Comment by Isssuemaker** [comment]
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.15
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.extractor.playlist.PlaylistInfo.getThumbnailUrl()' on a null object reference
	at org.schabi.newpipe.fragments.list.playlist.PlaylistFragment.onOptionsItemSelected(PlaylistFragment.java:271)
	at androidx.fragment.app.Fragment.performOptionsItemSelected(Fragment.java:3122)
	at androidx.fragment.app.FragmentManager.dispatchOptionsItemSelected(FragmentManager.java:3226)
	at androidx.fragment.app.FragmentController.dispatchOptionsItemSelected(FragmentController.java:416)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:358)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:264)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:65)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:208)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:975)
	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
	at android.view.View.performClick(View.java:7575)
	at android.view.View.performClickInternal(View.java:7531)
	at android.view.View.access$3900(View.java:842)
	at android.view.View$PerformClick.run(View.java:28872)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:261)
	at android.app.ActivityThread.main(ActivityThread.java:8314)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

```
</details>
<hr>


> It means that an error happened. It's a reference to https://en.wikipedia.org/wiki/Guru_meditation.
> 
> Anyway, can you share the error by pressing the report button? You're probably facing #7734, but I'd like to be certain before closing this.
