### ISSUE TITLE
Play 404

### ISSUE THREAD

**Issue by Violet-VE** [TeamNewPipe/NewPipe#7795]
404
Harmony OS
V2ray NG  Can visit google
can search in Newpipe,But play page 404

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=Q-X7F3Ab8C4
* __Content Country:__ CN
* __Content Language:__ zh-CN
* __App Language:__ zh_CN_#Hans
* __Service:__ YouTube
* __Version:__ 0.21.14
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:194)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(Unknown Source:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda6.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

```
</details>
<hr>

**Comment by Violet-VE** [comment]
![Uploading Screenshot_20220204_125912_org.schabi.newpipe.jpg…]()

**Comment by Violet-VE** [comment]
![Screenshot_20220204_125912_org schabi newpipe](https://user-images.githubusercontent.com/37390307/152474656-d9501fae-0252-4e0f-af12-c1bed9374eff.jpg)

**Comment by brnwlshubh** [comment]
Update Newpipe https://github.com/TeamNewPipe/NewPipe/releases/download/v0.21.16/NewPipe_v0.21.16.apk

**Comment by Violet-VE** [comment]
> Update Newpipe https://github.com/TeamNewPipe/NewPipe/releases/download/v0.21.16/NewPipe_v0.21.16.apk

yes, my app store not prompt updates, so....

**Comment by TiA4f8R** [comment]
Please don't remove the issue template the next time you open an issue, there are good reasons to keep it. Thank you.
