### ISSUE TITLE
UI error crash when rotating screen while "add to playlist" modal is open.

### ISSUE THREAD

**Issue by Magicfulness** [TeamNewPipe/NewPipe#7825]
### Checklist

- [x] I am using the latest version - 0.21.15 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Long hold on any video and press add to playlist. (Alternatively, select the "add to playlist" option under any video when watching).
2. Rotate the screen while "auto-rotate" feature is on.

### Actual behavior
App crashes, and we are sent to home page.

### Expected behavior
App does not crash. Ideally the "add to playlist" modal is still open, but doesn't matter if it isn't.

### Screenshots/Screen recordings

https://github.com/TeamNewPipe/NewPipe/issues/7825#issuecomment-1030768989

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.21.15
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.schabi.newpipe/org.schabi.newpipe.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment org.schabi.newpipe.local.dialog.PlaylistAppendDialog: could not find Fragment constructor
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3622)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3786)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5666)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5572)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2257)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8030)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment org.schabi.newpipe.local.dialog.PlaylistAppendDialog: could not find Fragment constructor
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:628)
	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728)
	at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198)
	at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149)
	at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:322)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
	at org.schabi.newpipe.MainActivity.onCreate(MainActivity.java:143)
	at android.app.Activity.performCreate(Activity.java:8006)
	at android.app.Activity.performCreate(Activity.java:7990)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3595)
	... 13 more
Caused by: java.lang.NoSuchMethodException: org.schabi.newpipe.local.dialog.PlaylistAppendDialog.<init> []
	at java.lang.Class.getConstructor0(Class.java:2332)
	at java.lang.Class.getConstructor(Class.java:1728)
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:613)
	... 27 more

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: Android 11, official version by OnePlus
 - Device model: OnePlus 8T

**Comment by Magicfulness** [comment]
https://user-images.githubusercontent.com/24852038/152671466-6de53efb-8675-4233-a1d9-849e818568e7.mp4

**Comment by opusforlife2** [comment]
Thanks for the great bug report!

**Comment by GGAutomaton** [comment]
I've found the problem and would like to work on this issue.

**Comment by GGAutomaton** [comment]
Crash log:
```
{"user_action":"ui error","request":"ACRA report","content_language":"zh-CN","content_country":"CN","app_language":"zh_CN_#Hans","service":"none","package":"org.schabi.newpipe","version":"0.22.1","os":"Linux Android 10 - 29","time":"2022-04-03 19:42","exceptions":["java.lang.RuntimeException: Unable to start activity ComponentInfo{org.schabi.newpipe/org.schabi.newpipe.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment org.schabi.newpipe.local.dialog.PlaylistAppendDialog: could not find Fragment constructor
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4060)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4247)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6253)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6144)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment org.schabi.newpipe.local.dialog.PlaylistAppendDialog: could not find Fragment constructor
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:628)
	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728)
	at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198)
	at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149)
	at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:322)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
	at org.schabi.newpipe.MainActivity.onCreate(MainActivity.java:143)
	at android.app.Activity.performCreate(Activity.java:8214)
	at android.app.Activity.performCreate(Activity.java:8202)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4033)
	... 13 more
Caused by: java.lang.NoSuchMethodException: org.schabi.newpipe.local.dialog.PlaylistAppendDialog.<init> []
	at java.lang.Class.getConstructor0(Class.java:2332)
	at java.lang.Class.getConstructor(Class.java:1728)
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:613)
	... 27 more
"],"user_comment":""}
```

Going to fix it with [this method](https://stackoverflow.com/questions/51831053/could-not-find-fragment-constructor).
