### ISSUE TITLE
Comments very rarely fail to load with an "ArrayIndexOutOfBoundsException" error

### ISSUE THREAD

**Issue by TheMCNerd2017** [TeamNewPipe/NewPipe#7843]
### Checklist

- [x] I am using the latest version - 0.21.16 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to any YouTube video.
2. Wait while the comments load.

### Actual behavior

The comments fail to load, and let you retry (which should work) or view the error. This issue seems to be very rare as I've only encountered it once and could not get it to come up again so I'm not sure what caused it.

### Expected behavior

The comments should load without the chance of an error.

### Screenshots/Screen recordings

N/A

## Exception
* __User Action:__ requested comments
* __Request:__ Start loading: https://www.youtube.com/watch?v=Exh9ToCuf7c
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.21.16
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
	at java.util.ArrayList.get(ArrayList.java:439)
	at com.grack.nanojson.JsonArray.get(Unknown Source:6)
	at com.grack.nanojson.JsonArray.getObject(Unknown Source:0)
	at com.grack.nanojson.JsonArray.getObject(Unknown Source:5)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.collectCommentsFrom(YoutubeCommentsExtractor.java:191)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getPage(YoutubeCommentsExtractor.java:182)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getInitialPage(YoutubeCommentsExtractor.java:72)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:48)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:29)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getCommentsInfo$7(ExtractorHelper.java:155)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$60N_-UL7E5eaxFaFO1bZZmnfwM8(Unknown Source:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda2.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

```
</details>
<hr>

### Device info

 - Android version/Custom ROM version: GrapheneOS 12 (SQ1A.220105.002.2022013120)
 - Device model: Pixel 4 XL

**Comment by litetex** [comment]
Problem occurs on: 
https://github.com/TeamNewPipe/NewPipeExtractor/blob/v0.21.13/extractor/src/main/java/org/schabi/newpipe/extractor/services/youtube/extractors/YoutubeCommentsExtractor.java#L189-L192

Reason: Missing input validation.

**Comment by seanzzy** [comment]
Hi! I would like to work on this issue. Can I get assigned to it?

**Comment by litetex** [comment]
Sure

**Comment by seanzzy** [comment]
I think this issue has been fixed in this commit on 22 February.
https://github.com/TeamNewPipe/NewPipeExtractor/commit/f79ce1f52a451c9b8722f09d9cb6885d91446918
Maybe I'll try to find a new one to work on 😄

**Comment by opusforlife2** [comment]
Closing as fixed by https://github.com/TeamNewPipe/NewPipeExtractor/pull/799 then. Thanks!
