### ISSUE TITLE
Menu to change resolution does not work in screen+ mode

### ISSUE THREAD

**Issue by bastiion** [TeamNewPipe/NewPipe#7864]
### Checklist

- [x] I am using the latest version - 0.21.16 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Enter the Screen+ mode on a recent LG smartphone
2. Play a video from YouTube
3. Click on the resolution menu

This error appears, while trying to switch resolution (open the menu) in Screen+ mode on a LG Velvet . The Screen plus mode is a desktop-like mode, which is very useful in combination with an external monitor.

### Actual behavior

It crashes with the following message below.

### Expected behavior

Menu for resolution change to appear.

### Logs

```
{
    "user_action": "ui error",
    "request": "ACRA report",
    "content_language": "de-DE",
    "content_country": "DE",
    "app_language": "de_DE",
    "service": "none",
    "package": "org.schabi.newpipe",
    "version": "0.21.16",
    "os": "Linux lge/caymanlm_e/caymanlm:11/RKQ1.201105.002/212521942c7f7.COM1_EU:user/release-keys 11 - 30",
    "time": "2022-02-12 15:10",
    "exceptions": [
        "android.view.WindowManager$BadTokenException: Unable to add window -- token android.view.ViewRootImpl$WEx@954281e is not valid; is your activity running?
			at android.view.ViewRootImpl.setView(ViewRootImpl.java:1106)
			at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:437)
			at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:116)
			at android.widget.PopupWindow.invokePopup(PopupWindow.java:1636)
			at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1445)
			at android.widget.ListPopupWindow.show(ListPopupWindow.java:742)
			at com.android.internal.view.menu.CascadingMenuPopup.showMenu(CascadingMenuPopup.java:433)
			at com.android.internal.view.menu.CascadingMenuPopup.show(CascadingMenuPopup.java:248)
			at com.android.internal.view.menu.MenuPopupHelper.showPopup(MenuPopupHelper.java:283)
			at com.android.internal.view.menu.MenuPopupHelper.tryShow(MenuPopupHelper.java:178)
			at com.android.internal.view.menu.MenuPopupHelper.show(MenuPopupHelper.java:142)
			at android.widget.PopupMenu.show(PopupMenu.java:230)
			at org.schabi.newpipe.player.Player.onQualitySelectorClicked(Player.java:3513)
			at org.schabi.newpipe.player.Player.onClick(Player.java:3645)
			at android.view.View.performClick(View.java:7461)
			at android.view.View.performClickInternal(View.java:7438)
			at android.view.View.access$4000(View.java:815)
			at android.view.View$PerformClick.run(View.java:28396)
			at android.os.Handler.handleCallback(Handler.java:938)
			at android.os.Handler.dispatchMessage(Handler.java:99)
			at android.os.Looper.loop(Looper.java:223)
			at android.app.ActivityThread.main(ActivityThread.java:7867)
			at java.lang.reflect.Method.invoke(Native Method)
			at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
			at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
	"
    ],
    "user_comment": ""
}
```

### Device info

 - Android version: 11
 - ROM version: Stock Rom  V20j-EEA-XX
 - Device model: LG LM-G900EM

**Comment by litetex** [comment]
Issue was merged (with similar ones) into #7865.
Please go on with the conversation inside there.
