### ISSUE TITLE
NewPipe crashes when used on external screen/vendor specific screen-sharing (Samsung DEX, LG Screen+, WSA)

### ISSUE THREAD

**Issue by litetex** [TeamNewPipe/NewPipe#7865]
### Checklist
- [x] I am using the latest version - x.xx.x 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Preamble
This issue combines multiple existing issues into one issue because - despite being implement by different manufactures - these results in the same bug.

### Steps to reproduce the bug
1. Play a video
2. Open something that has uese "popup"/dropdown, e.g. change the resolution or subtitles

### Actual behavior
App crashes

### Expected behavior
App works as expected

#### Samsung DEX

* __User Action:__ ui error
* __Request:__ ACRA report
...
* __Service:__ none
* __Version:__ 0.21.13
* __OS:__ Linux samsung/t2sxeea/t2s:11/RP1A.200720.012/G996BXXU3AUIE:user/release-keys 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
android.view.WindowManager$BadTokenException: Unable to add window -- token android.view.ViewRootImpl$W@fda8ca is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1444)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:469)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:114)
	at android.widget.PopupWindow.invokePopup(PopupWindow.java:1657)
	at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1460)
	at android.widget.ListPopupWindow.show(ListPopupWindow.java:771)
	at com.android.internal.view.menu.CascadingMenuPopup.showMenu(CascadingMenuPopup.java:480)
	at com.android.internal.view.menu.CascadingMenuPopup.show(CascadingMenuPopup.java:289)
	at com.android.internal.view.menu.MenuPopupHelper.showPopup(MenuPopupHelper.java:303)
	at com.android.internal.view.menu.MenuPopupHelper.tryShow(MenuPopupHelper.java:192)
	at com.android.internal.view.menu.MenuPopupHelper.show(MenuPopupHelper.java:156)
	at android.widget.PopupMenu.show(PopupMenu.java:230)
	at org.schabi.newpipe.player.Player.onCaptionClicked(Player.java:3563)
	at org.schabi.newpipe.player.Player.onClick(Player.java:3670)
	at android.view.View.performClick(View.java:8160)
	at android.widget.TextView.performClick(TextView.java:16222)
	at android.view.View.performClickInternal(View.java:8137)
	at android.view.View.access$3700(View.java:888)
	at android.view.View$PerformClick.run(View.java:30236)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```
</details>
<hr>

#### Windows Subsystem for Android/WSA
* __User Action:__ ui error
...
* __Version:__ 0.21.13
* __OS:__ Linux Android 11 - 30

<details><summary><b>Crash log </b></summary><p>

```
android.view.WindowManager$BadTokenException: Unable to add window -- token android.view.ViewRootImpl$W@11424e0 is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1071)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:409)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:109)
	at android.widget.PopupWindow.invokePopup(PopupWindow.java:1576)
	at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1423)
	at android.widget.ListPopupWindow.show(ListPopupWindow.java:722)
	at com.android.internal.view.menu.CascadingMenuPopup.showMenu(CascadingMenuPopup.java:432)
	at com.android.internal.view.menu.CascadingMenuPopup.show(CascadingMenuPopup.java:247)
	at com.android.internal.view.menu.MenuPopupHelper.showPopup(MenuPopupHelper.java:283)
	at com.android.internal.view.menu.MenuPopupHelper.tryShow(MenuPopupHelper.java:178)
	at com.android.internal.view.menu.MenuPopupHelper.show(MenuPopupHelper.java:142)
	at android.widget.PopupMenu.show(PopupMenu.java:230)
	at org.schabi.newpipe.player.Player.onQualitySelectorClicked(Player.java:3532)
	at org.schabi.newpipe.player.Player.onClick(Player.java:3664)
	at android.view.View.performClick(View.java:7448)
	at android.view.View.performClickInternal(View.java:7425)
	at android.view.View.access$3600(View.java:810)
	at android.view.View$PerformClick.run(View.java:28305)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>
<hr>

#### LG screen+

<details><summary>Click to expand</summary>

```
{
    "user_action": "ui error",
    ...
    "service": "none",
    "package": "org.schabi.newpipe",
    "version": "0.21.16",
    "os": "Linux lge/caymanlm_e/caymanlm:11/RKQ1.201105.002/212521942c7f7.COM1_EU:user/release-keys 11 - 30",
    "time": "2022-02-12 15:10",
    "exceptions": [
        "android.view.WindowManager$BadTokenException: Unable to add window -- token android.view.ViewRootImpl$WEx@954281e is not valid; is your activity running?
			at android.view.ViewRootImpl.setView(ViewRootImpl.java:1106)
			at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:437)
			at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:116)
			at android.widget.PopupWindow.invokePopup(PopupWindow.java:1636)
			at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1445)
			at android.widget.ListPopupWindow.show(ListPopupWindow.java:742)
			at com.android.internal.view.menu.CascadingMenuPopup.showMenu(CascadingMenuPopup.java:433)
			at com.android.internal.view.menu.CascadingMenuPopup.show(CascadingMenuPopup.java:248)
			at com.android.internal.view.menu.MenuPopupHelper.showPopup(MenuPopupHelper.java:283)
			at com.android.internal.view.menu.MenuPopupHelper.tryShow(MenuPopupHelper.java:178)
			at com.android.internal.view.menu.MenuPopupHelper.show(MenuPopupHelper.java:142)
			at android.widget.PopupMenu.show(PopupMenu.java:230)
			at org.schabi.newpipe.player.Player.onQualitySelectorClicked(Player.java:3513)
			at org.schabi.newpipe.player.Player.onClick(Player.java:3645)
			at android.view.View.performClick(View.java:7461)
			at android.view.View.performClickInternal(View.java:7438)
			at android.view.View.access$4000(View.java:815)
			at android.view.View$PerformClick.run(View.java:28396)
			at android.os.Handler.handleCallback(Handler.java:938)
			at android.os.Handler.dispatchMessage(Handler.java:99)
			at android.os.Looper.loop(Looper.java:223)
			at android.app.ActivityThread.main(ActivityThread.java:7867)
			at java.lang.reflect.Method.invoke(Native Method)
			at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
			at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
	"
    ],
    "user_comment": ""
}
```

</details>

### Device info
* Android version/Custom ROM version: Android 11+

#### Affected platforms:
* Samsung DEX #7391
* Windows Subsystem for Android/WSA #7396
* LG screen+ #7864

**Comment by NeatNit** [comment]
I don't know if this is helpful, but I just encountered this bug myself when trying to change video quality in Samsung DeX. Crash log is below.

(I almost just opened a new issue, that checklist really works!)

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ CA
* __Content Language:__ en-CA
* __App Language:__ en_CA
* __Service:__ none
* __Version:__ 0.23.0
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
android.view.WindowManager$BadTokenException: Unable to add window -- token android.view.ViewRootImpl$W@b2895a2 is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1588)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:509)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:133)
	at android.widget.PopupWindow.invokePopup(PopupWindow.java:1688)
	at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1489)
	at androidx.appcompat.widget.AppCompatPopupWindow.showAsDropDown(AppCompatPopupWindow.java:77)
	at androidx.core.widget.PopupWindowCompat$Api19Impl.showAsDropDown(PopupWindowCompat.java:247)
	at androidx.core.widget.PopupWindowCompat.showAsDropDown(PopupWindowCompat.java:71)
	at androidx.appcompat.widget.ListPopupWindow.show(ListPopupWindow.java:754)
	at androidx.appcompat.view.menu.CascadingMenuPopup.showMenu(CascadingMenuPopup.java:487)
	at androidx.appcompat.view.menu.CascadingMenuPopup.show(CascadingMenuPopup.java:266)
	at androidx.appcompat.view.menu.MenuPopupHelper.showPopup(MenuPopupHelper.java:296)
	at androidx.appcompat.view.menu.MenuPopupHelper.tryShow(MenuPopupHelper.java:182)
	at androidx.appcompat.view.menu.MenuPopupHelper.show(MenuPopupHelper.java:144)
	at androidx.appcompat.widget.PopupMenu.show(PopupMenu.java:238)
	at org.schabi.newpipe.player.listeners.view.QualityClickListener.onClick(QualityClickListener.kt:29)
	at android.view.View.performClick(View.java:7792)
	at android.widget.TextView.performClick(TextView.java:16112)
	at android.view.View.performClickInternal(View.java:7769)
	at android.view.View.access$3800(View.java:910)
	at android.view.View$PerformClick.run(View.java:30218)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```
</details>
<hr>

**Comment by opusforlife2** [comment]
> (I almost just opened a new issue, that checklist really works!)

You, sir, are a real Super Saiyan.

**Comment by The-unknown-Shadowman** [comment]
I' using the latest version 0.24 on Samsung S20 FE 5G and Samsung Dex. The problem still exists. NewPipe crashes after trying to change resolution or another menu that should show a popup menu.

**Comment by TriplEight** [comment]
I keep having this on Samsung S 21 U when I'm pressing the Cast button. But on the phone, there is no issues with the dropdowns in the player window. Also no issue with the comments section.

Just tested in Dex mode - can confirm, same issue with the same crash log. Happens on a dropdown which hides cast and sharing options and a quality chooser.

I believe, the Cast button also tries to open a pop-up with the devices to cast to.

The worst part about it is that the `backNav` button exits the app instead of returning to the content.


<details><summary>Guru meditation</summary>
"user_action":"ui error"
"request":"ACRA report"
"content_language":"en"
"content_country":"GB"
"app_language":"en_IE""service":"none"
"package":"org.schabi.newpipe"
"version":"0.24.1"
"os":"Linux Android 13 - 33"
"time":"2022-12-19 15:29"

"exceptions":["android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?\n\tat android.view.ViewRootImpl.setView(ViewRootImpl.java:1732)\n\tat android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:541)\n\tat android.view.WindowManagerImpl.addView(WindowManagerImpl.java:148)\n\tat android.app.Dialog.show(Dialog.java:523)\n\tat org.schabi.newpipe.util.external_communication.KoreUtils.showInstallKoreDialog(KoreUtils.java:39)\n\tat org.schabi.newpipe.player.ui.VideoPlayerUi.onPlayWithKodiClicked(VideoPlayerUi.java:1479)\n\tat org.schabi.newpipe.player.ui.VideoPlayerUi.onClick(VideoPlayerUi.java:1353)\n\tat org.schabi.newpipe.player.ui.MainPlayerUi.onClick(MainPlayerUi.java:863)\n\tat android.view.View.performClick(View.java:7881)\n\tat android.view.View.performClickInternal(View.java:7858)\n\tat android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)\n\tat android.view.View$PerformClick.run(View.java:30863)\n\tat android.os.Handler.handleCallback(Handler.java:942)\n\tat android.os.Handler.dispatchMessage(Handler.java:99)\n\tat android.os.Looper.loopOnce(Looper.java:226)\n\tat android.os.Looper.loop(Looper.java:313)\n\tat android.app.ActivityThread.main(ActivityThread.java:8741)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)\n"],"user_comment":""
</details>

**Comment by DarkCrypt** [comment]
Sadly, WSA will no longer be supported after March 5, 2025. Learn more at [Microsoft/WSA](https://github.com/microsoft/WSA/discussions/536) (GitHub) and [Microsoft Learn](https://learn.microsoft.com/en-us/windows/android/wsa/).

**Comment by bartvanandel** [comment]
I'm still running into this issue a couple years after the first bug report. I'm on a Samsung S23, and using Dex to connect to an external monitor.

Looks like there's about a 50% chance of a crash whenever doing the following:

- Going fullscreen
- Exiting fullscreen
- Trying to change the resolution (open the popup)

Sometimes even pausing a video, or reaching the end of it, will cause the crash.

**Comment by pawlosck** [comment]
I have the saame issue at Samsung S24 Ultra in Dex mode.
All crashes happens:
a) in full screen mode,
b)  using normal mouse via bluetooth.
c) phone connected  to TV via adapter usb-c to hdmi

What to do
1. Pause the movie - sometimes yoou have to wait, or switch to next movie. Generally it happen very often, but not always.
2. Change resolution - press area with resolution number (top right) - it happen always

If I remember, there were other situationns, but I don't remember

If you have any question, tell me and I will try to answer for all questions. I need it.

**Comment by pawlosck** [comment]
Is there any chance to fix it? You can find solution in pipepipe, because this app works well with dex.

**Comment by pawlosck** [comment]
I know where is problem when I am pausing movie. 
When I left mouse cursor inside circle (center of screen), then Newpipe crash. When I pause movie and later left cursor outside circle, then Newpipe works without problems.

**Comment by idealist1508** [comment]
It's a really frustrating bug on Samsung DeX. I found two situations when it occurs:

1. When calling the `Show` method on `PopupMenu` in the player.
2. When displaying a `ToolTip` in the player.

In both cases, there seems to be some issue with the `context` (an instance of `PlayerService`).

Unfortunately, I'm a complete newbie in Android development. 😉  @ShareASmile 
With the help of AI, I was only able to replace `context` with `MainActivity`. Check out cd9566d961e604e99d54260f292085618e7215d5 commit in my branch.  

In this form, the app runs without crashes. I understand that this is not a production-ready solution, but maybe you have an idea on how to fix this professionally?

**Comment by idealist1508** [comment]
The `ToolTip` still isn’t working perfectly. There are still some crashes. I think there's a timing issue. I believe it crashes right when a `ToolTip` is supposed to be displayed and the "overlay with the controls" is being hidden at the same time.

**Comment by spoltier** [comment]
Adding a crash report on DeX when trying to go full screen (clicked the maximize button in the lower right corner) 

Samsung S20 FE (4G), Android 13, Model SM-G780G/DS

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Timestamp:__ 2025-03-30T16:11:11.682+02:00
* __Package:__ org.schabi.newpipe
* __Service:__ none
* __Version:__ 0.27.6
* __OS:__ Linux samsung/r8qeea/r8q:13/TP1A.220624.014/G780GXXU6EWH5:user/release-keys 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
android.view.WindowManager$BadTokenException: Unable to add window -- token android.view.ViewRootImpl$W@7f0c524 is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1764)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:567)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:148)
	at com.android.internal.view.TooltipPopup.show(TooltipPopup.java:140)
	at android.view.View.showTooltip(View.java:33139)
	at android.view.View.showHoverTooltip(View.java:33186)
	at android.view.View.$r8$lambda$27VXCdyLVNkujfByQKuywAc_nkI(Unknown Source:0)
	at android.view.View$$ExternalSyntheticLambda2.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```
</details>
<hr>
