### ISSUE TITLE
not working matepad 10.4

### ISSUE THREAD

**Issue by 8uu** [TeamNewPipe/NewPipe#7892]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

101.21

### Steps to reproduce the bug

1. Open
2. Import subscriber from. Youtube. Approved
3. Open any video

### Expected behavior

Play video

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ ar-US
* __App Language:__ ar_US
* __Service:__ none
* __Version:__ 101.21.Huawei
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.huawei.hms.ads.banner.BannerView.setAdId(java.lang.String)' on a null object reference
	at com.jmomobilehwawi.vancedus.adsmanager.AdsManagers.loadBannerAd(AdsManagers.java:48)
	at com.jmomobilehwawi.vancedus.fragments.detail.VideoDetailFragment.initViews(VideoDetailFragment.java:640)
	at com.jmomobilehwawi.vancedus.BaseFragment.onViewCreated(BaseFragment.java:67)
	at com.jmomobilehwawi.vancedus.fragments.BaseStateFragment.onViewCreated(BaseStateFragment.java:42)
	at com.jmomobilehwawi.vancedus.fragments.detail.VideoDetailFragment.onViewCreated(VideoDetailFragment.java:600)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8349)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)

```
</details>
<hr>

### Screenshots/Screen recordings

https://youtu.be/HYH_HBjzWGE

### Affected device model

 matepad 10.4

**Comment by mhmdanas** [comment]
This is definitely not NewPipe. Have you installed it from the Huawei AppGallery? We don't distribute NewPipe there, it's almost certainly a copycat that you shouldn't be using. See https://github.com/TeamNewPipe/NewPipe#installation-and-updates for how to install the real NewPipe.
