### ISSUE TITLE
Error when downloading: "too many SQL variables"

### ISSUE THREAD

**Issue by SpruceFeathers** [TeamNewPipe/NewPipe#7922]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.0

### Steps to reproduce the bug

1. Go to any video
2. Hit the download button 
3. Hit "Ok"

### Expected behavior

For the video to download normally 

### Actual behavior

I get an error page, and have to close and restart the app

### Screenshots/Screen recordings

<img alt="Screenshot_20220221-002225_NewPipe" src="https://user-images.githubusercontent.com/100111719/154894295-4f9b6c73-43de-4188-aeca-e927a702e72d.jpg" height=600 />

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.22.0
* __OS:__ Linux samsung/crownqltesq/crownqltesq:10/QP1A.190711.020/N960USQU9FUK1:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
android.database.sqlite.SQLiteException: too many SQL variables (code 1 SQLITE_ERROR[1]): , while compiling: SELECT instance_id, duration, description, orientation, height, is_drm, bucket_display_name, owner_package_name, volume_name, date_modified, date_expires, _display_name, datetaken, mime_type, referer_uri, _id, _data, _hash, _size, title, width, is_trashed, group_id, document_id, is_pending, date_added, download_uri, primary_directory, secondary_directory, original_document_id, bucket_id, relative_path FROM downloads WHERE ((is_pending=0) AND (is_trashed=0) AND (volume_name IN ( 'external_primary' ))) AND (_data NOT IN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) AND relative_path=?)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:184)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
	at android.content.ContentResolver.query(ContentResolver.java:951)
	at android.content.ContentResolver.query(ContentResolver.java:887)
	at android.content.ContentResolver.query(ContentResolver.java:843)
	at org.schabi.newpipe.streams.io.StoredDirectoryHelper.findFileSAFHelper(StoredDirectoryHelper.java:302)
	at org.schabi.newpipe.streams.io.StoredDirectoryHelper.findFile(StoredDirectoryHelper.java:218)
	at org.schabi.newpipe.download.DownloadDialog.prepareSelectedDownload(DownloadDialog.java:786)
	at org.schabi.newpipe.download.DownloadDialog.lambda$initToolbar$1(DownloadDialog.java:360)
	at org.schabi.newpipe.download.DownloadDialog.$r8$lambda$QfMS-FoXWFjSoHiNV7JREecQBWg(Unknown Source:0)
	at org.schabi.newpipe.download.DownloadDialog$$ExternalSyntheticLambda6.onMenuItemClick(Unknown Source:2)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:208)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:975)
	at androidx.appcompat.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:151)
	at android.view.View.performClick(View.java:7862)
	at android.widget.TextView.performClick(TextView.java:15004)
	at android.view.View.performClickInternal(View.java:7831)
	at android.view.View.access$3600(View.java:879)
	at android.view.View$PerformClick.run(View.java:29359)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 10

### Affected device model

Android note 9

### Additional information

No additional information

**Comment by litetex** [comment]
Thank you for the detailed issue.

This issue is similar to #7569

**Comment by SpruceFeathers** [comment]
Issue resolved, the folder i had it set to download files to did not exist, my bad. Thank you for the help :)
