### ISSUE TITLE
Crash when opening Video&Audio menu setting

### ISSUE THREAD

**Issue by d4f5409d** [TeamNewPipe/NewPipe#7927]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.0

### Steps to reproduce the bug

1. Go to setting
2. Enter Video&Audio
3. Experience the crash

### Expected behavior

It would open Video&audio submenu

### Actual behavior

It crashes the app

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en_US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.22.0
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.preference.ListPreference.setEntryValues(java.lang.CharSequence[])' on a null object reference
	at org.schabi.newpipe.settings.VideoAudioSettingsFragment.updateSeekOptions(VideoAudioSettingsFragment.java:91)
	at org.schabi.newpipe.settings.VideoAudioSettingsFragment.onCreatePreferences(VideoAudioSettingsFragment.java:28)
	at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:160)
	at org.schabi.newpipe.settings.BasePreferenceFragment.onCreate(BasePreferenceFragment.java:28)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8030)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 11 / OxygenOS

### Affected device model

OnePlus 8

**Comment by d4f5409d** [comment]
Edit: it looks like it works now

**Comment by d4f5409d** [comment]
Edit: it somerimes does crash, sometime it does not.

**Comment by litetex** [comment]
Works without problems on my device.

Could you paste a dump of your settings here?

You may also try to reset the app (maybe save your data first)

**Comment by d4f5409d** [comment]
Sorry, my bad, it is the fork's bug (NewPipe SponsorBlock)
