### ISSUE TITLE
Get stuck on continuing playback after a while

### ISSUE THREAD

**Issue by orschiro** [TeamNewPipe/NewPipe#7967]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.0

### Steps to reproduce the bug

1. Play a video in background
2. Keep the notification player open and what for a day
3. Tomorrow, continue playback from the notification player

### Expected behavior

Seamlessly continue playback

### Actual behavior

Playback gets stuck and I need to close and reopen the video. 

Annoying because I need to remember last playback position and go back manually.

**Comment by dev-a** [comment]
I confirm that I have the same problem for most of the videos that I stopped during playback. I don't need to wait days to encounter the problem

**Comment by Hikariii** [comment]
+1:
```
## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_PARSING_CONTAINER_UNSUPPORTED] occurred while playing https://www.youtube.com/watch?v=kbYHVQlO11A
* __Content Country:__ NL
* __Content Language:__ nl-NL
* __App Language:__ nl_NL
* __Service:__ YouTube
* __Version:__ 0.23.0
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>
```

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:611)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:245)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.ParserException: Skipping atom with length > 2147483647 (unsupported).
	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readAtomHeader(FragmentedMp4Extractor.java:440)
	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:331)
	at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
	at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1042)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```

**Comment by ACodeHX** [comment]
Me too, when I exit after watching a video and then watch another video, there will be obvious lag.
