### ISSUE TITLE
ExoPlaybackException - MediaCodecVideoDecoderException

### ISSUE THREAD

**Issue by Gitogitos** [TeamNewPipe/NewPipe#8016]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

When I play YouTube, with video rotation sometimes without video rotation 

### Expected behavior

The video should play

### Actual behavior

It's stop with error message 

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=1] occurred while playing https://www.youtube.com/watch?v=qrIDMfPRF6I
* __Content Country:__ PL
* __Content Language:__ pl-PL
* __App Language:__ pl_PL
* __Service:__ YouTube
* __Version:__ 0.22.0 and 0.22.1
* __OS:__ Linux motorola/athene/athene:7.0/NPJ25.93-14/16:user/release-keys 7.0 - 24
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(1, null, null, video/avc, avc1.64001F, -1, null, [1280, 720, 30.0], [-1, -1]), format_supported=YES
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:555)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.qcom.video.decoder.avc
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1410)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:864)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:945)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478)
	... 3 more
Caused by: java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
	at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2513)
	at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueInputBufferIndex(SynchronousMediaCodecAdapter.java:93)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:1209)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:845)
	... 5 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 7.0

### Affected device model

Motorola Moto G4

**Comment by litetex** [comment]
I think I have to clarify this exceptions a bit:
Whenever you encounter a ``ExoPlaybackException - MediaCodecVideoDecoderException`` it's usually a hardware/Exoplayer problem (like e.g. a GPU error on your PC) as can be seen in the stacktrace ``android.media.MediaCodec.native_dequeueInputBuffer(Native Method)``.
AFAIK there is nothing we can change/fix here.

This is only more often reported recently due to #7482 (before there was simply a toast saying ``Unexpected error`` and you couldn't report it).

**Comment by litetex** [comment]
I think we need a better error handling if such a problem occurs. All few days a new issue pops up that describes this or a similar problem related to ``MediaCodec``

**Comment by watashibeme** [comment]
Once there used to be an option in android to whether use exo or not in developer options, it's annoying the hell out of me, exiting the player , recovering from player error, changing orientation, again, pause midway, again
Aaaaaaaaaaaaaaaa

**Comment by watashibeme** [comment]
Now I just wanna go back to previous android for this sole reason

**Comment by watashibeme** [comment]
Oh, so you know🤣
I would use LOS if it had some sort of customization section.
But I get your point, I'll think about it

**Comment by Dan-TBA** [comment]
sooo, whats the solution?

**Comment by tranquil222** [comment]
I fixed this on my tablet by changing the default resolution to1080p instead of 2160p. The higher resolution made it crash with this error code  for some reason.
