### ISSUE TITLE
Unable to download/export any content

### ISSUE THREAD

**Issue by Vinesauced** [TeamNewPipe/NewPipe#8021]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1. Go to any video
2. Press download
3. Press OK

### Expected behavior

Expected to download

### Actual behavior

An error popups saying "No app on your device can open this" "No appropriate file manager was found for this action. Please install a Storage Access Framework compatible file manager" despite having a file manager with this capability.

### Affected Android/Custom ROM version

Android 11

### Affected device model

Samsung Galaxy A02s

### Additional information

I have installed nearly every file manager on f-droid and tested this error, enabled NewPipe to access files in the permission manager, used a file manager that was recommended here on github (Material Files by Hai Zhang), and the error also occurs when attempting to export subscriptions. I have disabled Samsung's default file manager.

**Comment by litetex** [comment]
So as the error states there was not an appropriate file-manager found.

I think if you enable Samsung's default file manager everything should work as expected.

However ["Material Files"](https://f-droid.org/de/packages/me.zhanghai.android.files/) should work normally - at least what I have heard from other users.

**Comment by opusforlife2** [comment]
> used a file manager that was recommended here on github (Material Files by Hai Zhang), 

Apparently not.

**Comment by finedust** [comment]
I have the same problem using 21.16 or higher (up to current 22.1), even with Material Files.

I tried reinstalling old 21.15 version and the standard download (no SAF) works smoothly, while enabling SAF gives the following error:

## Exception
* User Action: ui error
* Request: ACRA report
* Content Country: GB
* Content Language: en-GB
* App Language: en_GB
* Service: none
* Version: 0.21.5
* OS: Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>


android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE flg=0x43 (has extras) }
 at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2064)
 at android.app.Instrumentation.execStartActivity(Instrumentation.java:1718)
 at android.app.Activity.startActivityForResult(Activity.java:5210)
 at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
 at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:234)
 at androidx.fragment.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:795)
 at androidx.fragment.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:932)
 at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1278)
 at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1266)
 at org.schabi.newpipe.settings.DownloadSettingsFragment.onPreferenceTreeClick(DownloadSettingsFragment.java:206)
 at androidx.preference.Preference.performClick(Preference.java:1192)
 at androidx.preference.Preference.performClick(Preference.java:1166)
 at androidx.preference.Preference$1.onClick(Preference.java:181)
 at android.view.View.performClick(View.java:7260)
 at android.view.View.performClickInternal(View.java:7237)
 at android.view.View.access$3600(View.java:802)
 at android.view.View$PerformClick.run(View.java:27915)
 at android.os.Handler.handleCallback(Handler.java:883)
 at android.os.Handler.dispatchMessage(Handler.java:100)
 at android.os.Looper.loop(Looper.java:214)
 at android.app.ActivityThread.main(ActivityThread.java:7356)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)


</details>
<hr>

**Comment by finedust** [comment]
The issue is still here with 0.23.1.  

@litetex, since I'm with Android 10 (CrDroid 6.8) on a Xiaomi Mi A3, this doesn't seem to be device specific. Moreover, it doesn't depend on the file manager.

**Comment by litetex** [comment]
> The issue is still here with 0.23.1.

This is not app specific, it's a problem that arises because a pre-installed OS component (SAF compatible file manager) is missing.

> since I'm with Android 10 (CrDroid 6.8) on a Xiaomi Mi A3

Doesn't look like the default OS to me. Does it have an fully SAF compatible file manager?


----

> However ["Material Files"](https://f-droid.org/de/packages/me.zhanghai.android.files/) should work normally

I recently found out that Material Files might not be able to save files using SAF (e.g. Export Database is not working). However read operations work fine for me.

**Comment by finedust** [comment]
> @litetex, since I'm with Android 10 (CrDroid 6.8) on a Xiaomi Mi A3, this doesn't seem to be device specific. Moreover, it doesn't depend on the file manager.

I'm sorry, this was my fault. Nevertheless, it may be useful to clarify what was the problem for me; @Vinesauced, see if this solves the issue for you.

[As stated here](https://github.com/zhanghai/MaterialFiles/issues/513#issuecomment-841857235) **Material Files it is not a SAF provider**, hence if you lack [Files (com.android.documentsui)](https://android.googlesource.com/platform/packages/apps/DocumentsUI/) - usually the default file manager - then SAF access won't work.
If you have uninstalled that app, you may want to have a look to #7127. Here is a [giude by LineageOS](https://wiki.lineageos.org/extracting_blobs_from_zips) on how to extract the app from their zips and here is a [guide](https://android.stackexchange.com/questions/180389/unable-to-install-apk-from-system-priv-app?noredirect=1&lq=1) on how to install it correctly.

**Comment by furiousmorse** [comment]
I suspect that the issue arises because the (com.google.android.documentsui) is not pre-installed. Due to that is a system app, I can't install it without root.

**Comment by drleandroceranto-debug** [comment]
Mesmo problema na versão v0.28.0 da minha TV Box que usa Android 11. Outros aplicativos funcionam normalmente (testei o https://github.com/anandnet/Harmony-Music), fazem download - não daria pra copiar o milagre que o projeto do Harmony faz em termos de download aqui para o NewPipe?

**Comment by simonwiles** [comment]
Yeah, same problem with a Samsung Galaxy Tablet :(
