### ISSUE TITLE
Subscriptions import crashes newpipe

### ISSUE THREAD

**Issue by daemonspudguy** [TeamNewPipe/NewPipe#8028]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1. Export subscriptions from Google Takeout
2. Import CSV into newpipe

### Expected behavior

Subscriptions get added

### Actual behavior

App crashes.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.22.1
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start service org.schabi.newpipe.local.subscription.services.SubscriptionsImportService@98bb264 with Intent { cmp=org.schabi.newpipe/.local.subscription.services.SubscriptionsImportService (has extras) }: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{6373497 4967:org.schabi.newpipe/u0a514} (pid=4967, uid=10514) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4657)
	at android.app.ActivityThread.access$2000(ActivityThread.java:247)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{6373497 4967:org.schabi.newpipe/u0a514} (pid=4967, uid=10514) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
	at android.os.Parcel.createException(Parcel.java:2409)
	at android.os.Parcel.readException(Parcel.java:2392)
	at android.os.Parcel.readException(Parcel.java:2334)
	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5869)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:6973)
	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3339)
	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2526)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1844)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1675)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1622)
	at us.shandian.giga.io.FileStreamSAF.<init>(FileStreamSAF.java:32)
	at org.schabi.newpipe.streams.io.StoredFileHelper.getStream(StoredFileHelper.java:195)
	at org.schabi.newpipe.local.subscription.services.SubscriptionsImportService.onStartCommand(SubscriptionsImportService.java:118)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4639)
	... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ContentProviderHelper.checkAssociationAndPermissionLocked(ContentProviderHelper.java:611)
	at com.android.server.am.ContentProviderHelper.getContentProviderImpl(ContentProviderHelper.java:235)
	at com.android.server.am.ContentProviderHelper.getContentProvider(ContentProviderHelper.java:125)
	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:6008)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2451)


```
</details>
<hr>

### Affected Android/Custom ROM version

Descendant 12

### Affected device model

Pixel 4a

**Comment by ztjuh** [comment]
I have the same problem on OPPO Reno6 Pro 5G

**Comment by nikhilvishwanath** [comment]
I'm facing same issue on OnePlus 8
