### ISSUE TITLE
Strange freeze behavior when playing videos in the background

### ISSUE THREAD

**Issue by silvaDominic** [TeamNewPipe/NewPipe#8030]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

~21.14+

### Steps to reproduce the bug

1. Open a video
2. Play it in the background
3. After several minutes the video will freeze and
- never return to playback
- return to playback when unlocking the phone or tapping the volume up/down button

### Expected behavior

A video should play in the background, possibly buffer, and return to play once buffered without any human interaction.

### Actual behavior

Video freezes and does not return playing unless intervening.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/12387334/158082304-f23e5d1a-7ad5-4c18-b5ab-9d58bff4797b.mp4

### Logs

<s>**This is *not* the error log for the above video**

Usually this does not produce an error. However, while listening to a fireplace video last night, it did. Unfortunately, I accidentally saved the non-formatted version. Sorry :/</s>

I was able to produce an error on same video stream as above.

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=0] occurred while playing https://www.youtube.com/watch?v=vzFG6mdkS70
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.22.1
* __OS:__ Linux samsung/beyond0qlteue/beyond0q:11/RP1A.200720.012/G970U1UEU6GUJ3:user/release-keys 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:246)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect
	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:346)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:201)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101)
	at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:64)
	at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:177)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.net.UnknownHostException: Unable to resolve host "[manifest.googlevideo.com](http://manifest.googlevideo.com/)": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at com.android.okhttp.Dns$1.lookup(Dns.java:41)
	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
	at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:192)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:144)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:106)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:400)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:333)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:608)
	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:498)
	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:339)
	... 9 more
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:202)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	... 27 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 11

### Affected device model

Samsung 10e

### Additional information

This started occurring during the same time issue [8029](https://github.com/TeamNewPipe/NewPipe/issues/8029) started happening. I know this because there are 2 routines where I use the background player for extended periods of time:

- In the morning while I cook breakfast (a live video like the one posted here)
- On train rides (various music videos --  not live)

After the update, I was unable to use the background player for extended periods of time and had to just play it via the video player. Typically what happens is after 2-5 minutes the audio playback will freeze. I will interact with the phone which will immediately resume playback and then playback will continue to freeze every 30-60s.

What is particularly weird is that it does not appear to be a buffering issue. As you can see in the video, playback returns after the phone is unlocked. I was not able to capture it, but it also often returns when simply using the volume up/down keys *without* unlocking the phone. Mind you, that my internet speed is 300Mb/s in the above video. For the videos I watched on the train prior to the issue, my connection was significantly slower than this, relying only on data and I still never had this issue.

**Comment by TacoTheDank** [comment]
Seeing as your phone is a Samsung device, have you made sure that it's not just the system killing the app in the background?

See this for info: https://dontkillmyapp.com/samsung#android-11

**Comment by silvaDominic** [comment]
Closing.

Issue was causes by Samsung update turning on battery optimization by default for all apps. This explains why playback would resume on wake/phone interactions.

More info here: https://dontkillmyapp.com/samsung#android-11

**Comment by TacoTheDank** [comment]
I have a Samsung device too (albeit running Android 10), so I know this problem a little too well.

Glad I could help! :)
