### ISSUE TITLE
Crash when opening Newpipe from the notification bar when a video started in the background

### ISSUE THREAD

**Issue by slasherfun** [TeamNewPipe/NewPipe#8058]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

Open a video in YouTube
Open the "share video" menu in YouTube, pick Newpipe, and select the "background player" option
Wait for the video (audio) to start playing in the background
Open Newpipe from Android notification menu

### Expected behavior

Newpipe should open and play the video in the app

### Actual behavior

Newpipe crashes

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ CA
* __Content Language:__ fr-CA
* __App Language:__ fr_CA
* __Service:__ none
* __Version:__ 0.22.1
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.exoplayer2.PlaybackParameters org.schabi.newpipe.player.Player.getPlaybackParameters()' on a null object reference
	at org.schabi.newpipe.player.PlayQueueActivity.onCreateOptionsMenu(PlayQueueActivity.java:106)
	at android.app.Activity.onCreatePanelMenu(Activity.java:4087)
	at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:287)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3084)
	at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
	at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:456)
	at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:57)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7697)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 10 / OxygenOS 10.0.1

### Affected device model

OnePlus 5

**Comment by pattmax00** [comment]
I came here to report this issue, when this is happening, I also am not able to interact with anything else on Android other than the back, home, and open apps buttons, which is resolved by disabling the ability to draw over my screen.

**Comment by seanzzy** [comment]
I've reproduce the bug on my redmi note11 pro with MIUI 12 (Android 11) by doing the procedure you offer.
