### ISSUE TITLE
YouTube video is not being opening with some exception

### ISSUE THREAD

**Issue by bitstuffing** [TeamNewPipe/NewPipe#8112]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.21.13

### Steps to reproduce the bug

1. Open the link
2. The app shows impossible to reproduce video and a retry

### Expected behavior

Video will play

### Actual behavior

Video is not playing

### Screenshots/Screen recordings

<img alt="Screenshot_2022-03-26-16-21-31-23_ee8807d2de22f1831269d80920e33a3b" src="https://user-images.githubusercontent.com/15215960/160246044-307a56fc-7b21-400b-87db-c6690b4304d2.jpg" height=600 />

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=dmW68lzaaqs
* __Content Country:__ ES
* __Content Language:__ es-ES
* __App Language:__ es_ES
* __Service:__ YouTube
* __Version:__ 0.21.13
* __OS:__ Linux OnePlus/OnePlus8Pro_CH/OnePlus8Pro:12/SKQ1.210216.001/Q.202201051928:user/release-keys 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:194)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(Unknown Source:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda6.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12 - ColorOS

### Affected device model

OnePlus8 Pro

### Additional information

The same behaviour with linked videos.

Also I have seen that Youtube Vanced is not longer playing any video so it's possible Youtube have changed the core to get a working video link or metadata video information

**Comment by litetex** [comment]
> I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).

no comment

**Comment by bitstuffing** [comment]
Hi @litetex , sorry if there is no more useful information in my comment, I try to help, but... where is the duplicated issue?

All the reported information was there because I suppose YouTube has changed his algorithm to receive the metadata information

And more information, if it reconforts you, Duff You is working fine, it's a newer Youtube NO-API addon for lastest Kodi, if you are able to test his code and reply the algorithm in NewPipe

**Comment by SameenAhnaf** [comment]
@bitstuffing 0.21.16 is the latest version. Please update your app to that version.

**Comment by bitstuffing** [comment]
> 

Yeah, I've downloaded it, and edited the lastest comment.

Thanks for your work and support.

**Comment by litetex** [comment]
> Hi @litetex , sorry if there is no more useful information in my comment, I try to help, but... where is the duplicated issue?

Duplicate of https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+Could+not+get+any+stream.+See+error+variable+to+get+further+details.+is%3Aclosed (Pick one from this list) 😉
