### ISSUE TITLE
v0.20.8 crash problem

### ISSUE THREAD

**Issue by conradaaron21** [TeamNewPipe/NewPipe#8154]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

v0.20.8

### Steps to reproduce the bug

Nothing works!

## Exception
* _User Action:_ ui error
* _Request:_ App crash, UI failure
* _Content Country:_ TR
* _Content Language:_ tr
* _App Language:_ tr
* _Service:_ none
* _Version:_ 0.20.8
* _OS:_ qnx Android 4.3 - 18
<details><summary><b>Crash log </b></summary><p>

android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://... flg=0x10000000 pkg=com.qnx.internal.qnxinvokeproxy }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1657)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
	at android.app.Activity.startActivityForResult(Activity.java:3456)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
	at android.app.Activity.startActivityForResult(Activity.java:3417)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:662)
	at android.app.Activity.startActivity(Activity.java:3653)
	at android.app.Activity.startActivity(Activity.java:3621)
	at org.schabi.newpipelegacy.util.ShareUtils.openUrlInBrowser(ShareUtils.java:39)
	at org.schabi.newpipelegacy.report.ErrorActivity.lambda$openPrivacyPolicyDialog$6(ErrorActivity.java:279)
	at org.schabi.newpipelegacy.report.ErrorActivity.lambda$openPrivacyPolicyDialog$6$ErrorActivity(ErrorActivity.java)
	at org.schabi.newpipelegacy.report.-$$Lambda$ErrorActivity$G4k4bXzoZQufOIGzBD8GD3omfx0.onClick(lambda)
	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5121)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
	at dalvik.system.NativeStart.main(Native Method)

</details>
<hr>

### Affected Android/Custom ROM version

4.3

### Affected device model

blackberry passport

**Comment by SameenAhnaf** [comment]
> [x] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).

*Sigh*

0.22.1 is the latest version.

**Comment by Nickoriginal** [comment]
NewPipe doesn't support Android 4.3 and lower (you must use [NewPipe Legacy](https://f-droid.org/repo/org.schabi.newpipelegacy_120.apk). @SameenAhnaf or maybe he is using it? (because mentioned by him version matches the latest NewPipe Legacy version). In any case, it can't be fixed due to missing maintainer. Consider closing or moving it to NewPipe Legacy issue tracker.

**Comment by conradaaron21** [comment]
Yeah, I mean NewPipe Legacy. I have to use it. Because my device supports android 4.3 and lower.

**Comment by Nickoriginal** [comment]
It is time for you to close this issue because it applies to a different application - NewPipe Legacy. Please upload it [here](https://github.com/TeamNewPipe/NewPipe-legacy/issues/new?assignees=&labels=bug&template=bug_report.md).

**Comment by opusforlife2** [comment]
See ^.
