### ISSUE TITLE
Subscription csv from Takeout won't load

### ISSUE THREAD

**Issue by darkemporium763** [TeamNewPipe/NewPipe#8172]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

Subscription csv from Google Takeout won't load. It gives some java errors.

### Expected behavior

It is supposed to load my YT subscriptions.

### Actual behavior

It shows the error report page with error logs.

### Screenshots/Screen recordings

<img alt="Screenshot_2022-04-10-16-47-47-489_org schabi newpipe" src="https://user-images.githubusercontent.com/103357593/162610355-144c6da5-2177-4e61-bcd2-5b052a6a0a0d.png" height=600 />

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.22.1
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start service org.schabi.newpipe.local.subscription.services.SubscriptionsImportService@5452207 with Intent { cmp=org.schabi.newpipe/.local.subscription.services.SubscriptionsImportService (has extras) }: java.lang.IllegalArgumentException: Media is read-only
	at android.app.ActivityThread.handleServiceArgs(Unknown Source:146)
	at android.app.ActivityThread.access$2100(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:671)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loopOnce(Unknown Source:176)
	at android.os.Looper.loop(Unknown Source:76)
	at android.app.ActivityThread.main(Unknown Source:153)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:309)
Caused by: java.lang.IllegalArgumentException: Media is read-only
	at android.database.DatabaseUtils.readExceptionFromParcel(Unknown Source:57)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(Unknown Source:14)
	at android.content.ContentProviderProxy.openAssetFile(Unknown Source:42)
	at android.content.ContentResolver.openAssetFileDescriptor(Unknown Source:194)
	at android.content.ContentResolver.openFileDescriptor(Unknown Source:11)
	at android.content.ContentResolver.openFileDescriptor(Unknown Source:1)
	at us.shandian.giga.io.FileStreamSAF.<init>(FileStreamSAF.java:32)
	at org.schabi.newpipe.streams.io.StoredFileHelper.getStream(StoredFileHelper.java:195)
	at org.schabi.newpipe.local.subscription.services.SubscriptionsImportService.onStartCommand(SubscriptionsImportService.java:118)
	at android.app.ActivityThread.handleServiceArgs(Unknown Source:60)
	... 9 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12

### Affected device model

Redmi K30 5G

### Additional information

My ROM is based on xiaomi.eu MIUI 13 Android 12. Device unlocked.

**Comment by opusforlife2** [comment]
>Media is read-only

Try putting it in another folder, like Downloads, or a completely new folder.

**Comment by roerch** [comment]
Same problem here, also Android 12. The rights management is even more strict there. NewPipe only has access to "media" folders. Work-around for me was to copy the .csv file to the 'Movies' folder, then the import went through. However it seems that Android 12 compatibility needs some work.

**Comment by opusforlife2** [comment]
@JeffKineiDOGE It's not a duplicate. Check the error messages. They're different.

**Comment by darkemporium763** [comment]
That was easy. It works. I move it to Documents folder.

Thanks for your help.

More power to this app.

**Comment by opusforlife2** [comment]
xD Thanks for confirming.
