### ISSUE TITLE
Unable to play video on replicant OS (replicant-6.0)

### ISSUE THREAD

**Issue by lerdem** [TeamNewPipe/NewPipe#8181]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

do not see it is working at all

### Steps to reproduce the bug

1. Select any video
2. Press play
3. Wait 10-15 sec(video will not start) and close player
4. Got exception

### Expected behavior

After 2nd step expecting playing video

### Actual behavior

App is chasing

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.22.1
* __OS:__ Linux Android 6.0.1 - 23
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to destroy activity {org.schabi.newpipe/org.schabi.newpipe.MainActivity}: com.google.android.exoplayer2.util.EGLSurfaceTexture$GlException: eglChooseConfig failed: success=true, numConfigs[0]=0, configs[0]=android.opengl.EGLConfig@4b95fc8f
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3865)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3883)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4087)
	at android.app.ActivityThread.-wrap15(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: com.google.android.exoplayer2.util.EGLSurfaceTexture$GlException: eglChooseConfig failed: success=true, numConfigs[0]=0, configs[0]=android.opengl.EGLConfig@4b95fc8f
	at com.google.android.exoplayer2.util.EGLSurfaceTexture.chooseEGLConfig(EGLSurfaceTexture.java:234)
	at com.google.android.exoplayer2.util.EGLSurfaceTexture.init(EGLSurfaceTexture.java:125)
	at com.google.android.exoplayer2.video.DummySurface$DummySurfaceThread.initInternal(DummySurface.java:207)
	at com.google.android.exoplayer2.video.DummySurface$DummySurfaceThread.handleMessage(DummySurface.java:178)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 6.0.1/replicant-6.0

### Affected device model

Galaxy S III (GT-I9300)

### Additional information

Created as detail for #8158 issue.

**Comment by litetex** [comment]
According to the exception it fails to find a GPU renderer or something similar (looks like a OpenGL problem).

So about this OS:
1. At first, Replicant 6.x is based on Android 6.0.1 which is no longer supported
2. If you read https://redmine.replicant.us/projects/replicant/wiki/Graphics it explains everything:
> Replicant doesn't rely on the dedicated graphics processor (GPU) for accelerated graphics rendering. ...
> Until version 6.0 0003, Replicant used libagl. libagl is fast, but caused several issues due to lack of GLES 2.0 support. ...
> As of Replicant 6.0 0004 rc1, llvmpipe is used as the default software renderer. ... Unfortunately, llvmpipe is too slow for certain system components, which may also be true for some apps. Furthermore, certain apps still crash with llvmpipe, although less frequently. Usually the screen stays black if an app does not work with llvmpipe.


It's likely that no ExoPlayer based app works on this OS. You might report the issue to Exoplayer itself or to the OS provider.

Conclusion:
Not sure how you want to watch videos on a 10 year old device with an 7 year old unsupported OS that has hardware  accelerated (GPU) rendering turned off. Even if you can watch a video it will likely have <10 FPS.<br/>IMHO this is just idiotic in the first place - I would compare this with unplugging your PCs graphics card and then complaining about that your display doesn't work anymore...
