### ISSUE TITLE
sound exception, unable to play video

### ISSUE THREAD

**Issue by emilien-g** [TeamNewPipe/NewPipe#8182]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

Hi,
Today a bug started to happen systematically on m'y fairphone 3 on e/os
Every time i start a vidéo, i get this exception and the vidéo doesn't play
I updated to latest version of e/os and the problem still happens

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=1] occurred while playing https://www.youtube.com/watch?v=v2YFii0vJSQ
* __Content Country:__ FR
* __Content Language:__ fr-FR
* __App Language:__ fr_FR
* __Service:__ YouTube
* __Version:__ 0.22.1
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: MediaCodecAudioRenderer error, index=1, format=Format(null, null, null, audio/raw, null, -1, null, [-1, -1, -1.0], [2, 44100]), format_supported=YES
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:555)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed 0 Config(44100, 12, 44100)
	at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:2011)
	at com.google.android.exoplayer2.audio.DefaultAudioSink.buildAudioTrack(DefaultAudioSink.java:844)
	at com.google.android.exoplayer2.audio.DefaultAudioSink.initializeAudioTrack(DefaultAudioSink.java:653)
	at com.google.android.exoplayer2.audio.DefaultAudioSink.handleBuffer(DefaultAudioSink.java:726)
	at com.google.android.exoplayer2.audio.MediaCodecAudioRenderer.processOutputBuffer(MediaCodecAudioRenderer.java:637)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1917)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:843)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:945)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:478)
	... 3 more
	Suppressed: com.google.android.exoplayer2.audio.AudioSink$InitializationException: AudioTrack init failed 0 Config(44100, 12, 44100)
		... 12 more
	Caused by: java.lang.UnsupportedOperationException: Cannot create AudioTrack
		at android.media.AudioTrack$Builder.build(AudioTrack.java:1018)
		at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.createAudioTrackV29(DefaultAudioSink.java:2060)
		at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.createAudioTrack(DefaultAudioSink.java:2038)
		at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:2003)
		... 11 more
Caused by: java.lang.UnsupportedOperationException: Cannot create AudioTrack
	at android.media.AudioTrack$Builder.build(AudioTrack.java:1018)
	at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.createAudioTrackV29(DefaultAudioSink.java:2060)
	at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.createAudioTrack(DefaultAudioSink.java:2038)
	at com.google.android.exoplayer2.audio.DefaultAudioSink$Configuration.buildAudioTrack(DefaultAudioSink.java:2003)
	... 11 more

```
</details>
<hr>

### Affected Android/Custom ROM version

e/os 23

### Affected device model

fairphone 3

**Comment by opusforlife2** [comment]
What's the last version that worked?

**Comment by emilien-g** [comment]
it was 0.21 but finally my sound problem is bigger than that. I reinstalled e/os from scratch and now no sound output is working from any app
looks like a hardware problem that happened suddenly

**Comment by opusforlife2** [comment]
Try installing another OS. If there's still no sound, hardware replacement seems like the way to go.

Leave a comment if it turns out to be a software problem and you're able to solve it, so that other /e/ users who face this issue can see the solution.
