### ISSUE TITLE
Crash on Bandcamp background play

### ISSUE THREAD

**Issue by mamins1376** [TeamNewPipe/NewPipe#8193]
it happened while trying to play something in background from Bandcamp.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.22.1
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
	at androidx.preference.PreferenceManager.getDefaultSharedPreferencesName(PreferenceManager.java:124)
	at androidx.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java:119)
	at org.schabi.newpipe.local.history.HistoryRecordManager.<init>(HistoryRecordManager.java:79)
	at org.schabi.newpipe.util.StreamDialogEntry.lambda$fetchItemInfoIfSparse$19(StreamDialogEntry.java:224)
	at org.schabi.newpipe.util.StreamDialogEntry.$r8$lambda$Tc9oOFdgPZXQSzwoTyHY4uvfJFM(Unknown Source:0)
	at org.schabi.newpipe.util.StreamDialogEntry$$ExternalSyntheticLambda0.accept(Unknown Source:6)
	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>
<hr>

**Comment by litetex** [comment]
Please fill out the template properly (see e.g. https://github.com/TeamNewPipe/NewPipe/issues/new?assignees=&labels=bug&template=bug_report.yml) we can't fix the problem if we don't know how it's reproducible.
