### ISSUE TITLE
Crashing on Attempting to Play an Item from Playlist

### ISSUE THREAD

**Issue by faxotherapy** [TeamNewPipe/NewPipe#8228]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1. Go to Playlist
2. Play an item

### Expected behavior

Should play the item without crashing.

### Actual behavior

Crashing at attempting to play an item from playlist.

### Screenshots/Screen recordings

I wish to mention I've got Internet access.

https://user-images.githubusercontent.com/6538008/163680439-698c7d4d-650a-4d44-b8b7-ee687fbe4039.mp4

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=k9zgbGmHahs
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ YouTube
* __Version:__ 0.22.1
* __OS:__ Linux Android 12 - 32
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
    at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:194)
    at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)
    at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
    at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
    at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(Unknown Source:0)
    at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda6.call(Unknown Source:4)
    at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
    at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
    at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
    at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
    at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
    at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
    at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
    at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
    at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
    at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
    at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15868)
    at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
    at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
    at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
    at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
    at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
    at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
    at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
    at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:920)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12

### Affected device model

Pixel 4a 5G

**Comment by TiA4f8R** [comment]
Read pinned issues.

**Comment by faxotherapy** [comment]
Hi, thx for your prompt reply. I thought the pinned issue was not related to my problem which is in connexion with playlist only. Could you please tell me what do you mean by “template instructions”? Didn't I follow them? 
I have taken the time to fill in all the required details above with posting the log file.
Thank you

**Comment by TiA4f8R** [comment]
> I have taken the time to fill in all the required details above with posting the log file

Yes, you did but you are not following the template instructions. The first checkbox instruction states you are using the latest version, which you can get from the link in it, but that's not true. (0.22.1 is not the latest version, but 0.22.2 is).

So you need to try to reproduce first the bug from the latest version before opening an issue (unless of course if that's a regression from the development branch).

Sorry if I felt rude.

> I thought the pinned issue was not related to my problem which is in connexion with playlist only.

You mean you could not play streams in playlists but individual streams with 0.22.1?

**Comment by faxotherapy** [comment]
Hi, thx for taking the time to reply. In fact, I installed the app from F-Droid, running CalyxOS/Android 12. F-Droid told me the app was up to date. So, I thought the app was up to date. Obviously not. It seems I can no longer rely on F-Droid or Droid-ify to know whether my apps are up to date or not.

**Comment by TiA4f8R** [comment]
I recommend to take a look at our readme, section [Installation and updates](https://github.com/TeamNewPipe/NewPipe#installation-and-updates) to understand better why this happen.
