### ISSUE TITLE
Videos will not load on carrier locked Moto e (2020)

### ISSUE THREAD

**Issue by SuperSpruce** [TeamNewPipe/NewPipe#8237]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.1

### Steps to reproduce the bug

1. Open app
2. Go to any video
3. Wait
4. I get a "sorry, cannot load" message when the video should have loaded

### Expected behavior

The video, along with the buttons below (like, download, etc.) load properly.

### Actual behavior

When the video loads, I get a "sorry cannot load" message

### Screenshots/Screen recordings

<img alt="Screenshot_20220416-163312" src="https://user-images.githubusercontent.com/48099460/163690520-ce1ae95e-8041-4c40-b959-148e0f4c9dfa.png" height=600 />

WiFi is enabled, YouTube official app works as normal.

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=Qskm9MTz2V4
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.22.1
* __OS:__ Linux motorola/ginna_trac/ginna:10/QPG30.82-141/84c8d:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:194)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:64)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(Unknown Source:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda6.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 10, stock I think

### Affected device model

Moto e (2020)

### Additional information

This bug has persisted across several versions, yet the bug does not occur on my unlocked Moto e (2020).

Yes, I have the same phone twice: one unlocked and the other carrier locked to TracFone. This bug only occurs on the locked phone.

I've tried uninstalling and reinstalling the app. No dice.

Sometimes but not always, the comments load before the error message.

**Comment by SameenAhnaf** [comment]
>[x] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).

No, you are not. Please update your app to the latest version 0.22.2

**Comment by SuperSpruce** [comment]
Just did that, and it works, albeit slowly. Previously, I've been having
this bug for months though, so I'm glad it's fixed. 0.22.1 is still the
latest version on F-droid though, where I normally get NewPipe from.
