### ISSUE TITLE
Can't play this video

### ISSUE THREAD

**Issue by the4anoni** [TeamNewPipe/NewPipe#824]
Hi :)
Why i can't play this video ? 
Here is link https://youtu.be/n4u67vFHm6I
On 0.10.2 it says it says that video can't be player
Earlier release crashes (but newest not).

**Comment by theScrabi** [comment]
Good question

**Comment by wb9688** [comment]
No idea, it works with youtube-dl. I'll spend some time looking at it soon.

@theScrabi: Can't I assign this issue to myself or don't I have enough rights for that?

**Comment by theScrabi** [comment]
It seems not. I may have to give you.

**Comment by wb9688** [comment]
@the4anoni: It looks like it works fine on my computer, but it says the age limit is 18, are you sure you've enabled that in the Settings (Content -> View content with age limit)?

![Screenshot](https://user-images.githubusercontent.com/9780201/32653104-ea78e402-c606-11e7-8332-afa69534a97a.png)

**Comment by theScrabi** [comment]
Maybe it depends on the country where its age restricted. Because i have agerestriction disabled, and it works not for me here in germany.

**Comment by codermess** [comment]
For me the video loads but the Next Video section below and the rest of the recommended videos don't load, and an error message pops up.
I get this exception when debugging:

`D/VideoDetailFragment@a783590: setupActionBarHandler() called with: info = [StreamInfo[url="https://www.youtube.com/watch?v=n4u67vFHm6I", name="Cypis - Biała Mewa"]]`

`D/VideoDetailFragment@a783590: showSnackBarError() called with: exception = [[org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get next video]], userAction = [REQUESTED_STREAM], request = [https://www.youtube.com/watch?v=n4u67vFHm6I], errorId = [0]`

Could it be related to non-English characters?

**Comment by EmmanuelMess** [comment]
Opened it twice, the second time it crashed:
```
2019-04-18 19:57:42.193 2189-16952/com.google.android.gms.persistent W/ctxmgr: [AclManager]No 2 for (accnt=account#-517948760#, com.google.android.gms(10013):IndoorOutdoorProducer, vrsn=13280000, 0, 3pPkg = null ,  3pMdlId = null ,  pid = 2189). Was: 3 for 57, account#-517948760#
2019-04-18 19:57:42.970 18161-18161/org.schabi.newpipe.debug E/class org.schabi.newpipe.report.ErrorActivity: org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse json response
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSuggestionExtractor.suggestionList(YoutubeSuggestionExtractor.java:72)
        at org.schabi.newpipe.util.ExtractorHelper.lambda$suggestionsFor$2(ExtractorHelper.java:105)
        at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$kAwiU5Tjeit-NCwHTWhD3V6UHS8.call(Unknown Source:4)
        at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
        at io.reactivex.Single.subscribe(Single.java:3438)
        at io.reactivex.internal.operators.single.SingleToObservable.subscribeActual(SingleToObservable.java:35)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at io.reactivex.internal.operators.observable.ObservableZip$ZipCoordinator.subscribe(ObservableZip.java:110)
        at io.reactivex.internal.operators.observable.ObservableZip.subscribeActual(ObservableZip.java:72)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at io.reactivex.internal.operators.observable.ObservableMaterialize.subscribeActual(ObservableMaterialize.java:28)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at io.reactivex.internal.operators.observable.ObservableSwitchMap$SwitchMapObserver.onNext(ObservableSwitchMap.java:127)
        at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
        at io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver$DelayErrorInnerObserver.onNext(ObservableConcatMap.java:506)
        at io.reactivex.observers.SerializedObserver.onNext(SerializedObserver.java:111)
        at io.reactivex.internal.operators.observable.ObservableDebounceTimed$DebounceTimedObserver.emit(ObservableDebounceTimed.java:143)
        at io.reactivex.internal.operators.observable.ObservableDebounceTimed$DebounceEmitter.run(ObservableDebounceTimed.java:168)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.grack.nanojson.JsonParserException: Unexpected token 'OCTYPE' on line 1, char 1
        at com.grack.nanojson.JsonParser.createParseException(Unknown Source:44)
        at com.grack.nanojson.JsonParser.createHelpfulException(Unknown Source:121)
        at com.grack.nanojson.JsonParser.advanceToken(Unknown Source:54)
        at com.grack.nanojson.JsonParser.parse(Unknown Source:0)
        at com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source:15)
        at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSuggestionExtractor.suggestionList(YoutubeSuggestionExtractor.java:62)
        at org.schabi.newpipe.util.ExtractorHelper.lambda$suggestionsFor$2(ExtractorHelper.java:105) 
        at org.schabi.newpipe.util.-$$Lambda$ExtractorHelper$kAwiU5Tjeit-NCwHTWhD3V6UHS8.call(Unknown Source:4) 
        at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44) 
        at io.reactivex.Single.subscribe(Single.java:3438) 
        at io.reactivex.internal.operators.single.SingleToObservable.subscribeActual(SingleToObservable.java:35) 
        at io.reactivex.Observable.subscribe(Observable.java:12090) 
        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32) 
        at io.reactivex.Observable.subscribe(Observable.java:12090) 
        at io.reactivex.internal.operators.observable.ObservableZip$ZipCoordinator.subscribe(ObservableZip.java:110) 
        at io.reactivex.internal.operators.observable.ObservableZip.subscribeActual(ObservableZip.java:72) 
        at io.reactivex.Observable.subscribe(Observable.java:12090) 
        at io.reactivex.internal.operators.observable.ObservableMaterialize.subscribeActual(ObservableMaterialize.java:28) 
        at io.reactivex.Observable.subscribe(Observable.java:12090) 
        at io.reactivex.internal.operators.observable.ObservableSwitchMap$SwitchMapObserver.onNext(ObservableSwitchMap.java:127) 
        at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52) 
        at io.reactivex.internal.operators.observable.ObservableConcatMap$ConcatMapDelayErrorObserver$DelayErrorInnerObserver.onNext(ObservableConcatMap.java:506) 
        at io.reactivex.observers.SerializedObserver.onNext(SerializedObserver.java:111) 
        at io.reactivex.internal.operators.observable.ObservableDebounceTimed$DebounceTimedObserver.emit(ObservableDebounceTimed.java:143) 
        at io.reactivex.internal.operators.observable.ObservableDebounceTimed$DebounceEmitter.run(ObservableDebounceTimed.java:168) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) 
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
```
