### ISSUE TITLE
Youtube subscriptions import crash

### ISSUE THREAD

**Issue by Betailas** [TeamNewPipe/NewPipe#8267]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.2

### Steps to reproduce the bug

1. Go to Subscription
2. Press Import from youtube
3. select the Subscriptions.csv file from memory
4. Agree with the warning message

### Expected behavior

My personal Youtube subscriptions are available

### Actual behavior

Program closes and crashes and after you turn it again, there's no imported subscriptions

### Affected Android/Custom ROM version

Android 11

### Affected device model

Samsung Galaxy M51

**Comment by dany123** [comment]
I had the same crash when trying to import the .csv file but choosing the full .zip import worked for me. Android 11 on a samsung A8 tablet.

**Comment by azazar** [comment]
It crashed when I was trying to import YouTube subscriptions from CSV

```
java.lang.RuntimeException: Unable to start service org.schabi.newpipe.local.subscription.services.SubscriptionsImportService@b4ce94b with Intent { cmp=org.schabi.newpipe/.local.subscription.services.SubscriptionsImportService (has extras) }: java.lang.IllegalArgumentException: Media is read-only
 at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4500)
 at android.app.ActivityThread.access$2100(ActivityThread.java:261)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2063)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:236)
 at android.app.ActivityThread.main(ActivityThread.java:8051)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
Caused by: java.lang.IllegalArgumentException: Media is read-only
 at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
 at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
 at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:704)
 at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1841)
 at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1656)
 at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1603)
 at us.shandian.giga.io.FileStreamSAF.<init>(FileStreamSAF.java:32)
 at org.schabi.newpipe.streams.io.StoredFileHelper.getStream(StoredFileHelper.java:195)
 at org.schabi.newpipe.local.subscription.services.SubscriptionsImportService.onStartCommand(SubscriptionsImportService.java:118)
 at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4477)
 ... 8 more
```

**Comment by Betailas** [comment]
> I had the same crash when trying to import the .csv file but choosing the full .zip import worked for me. Android 11 on a samsung A8 tablet.

Tried to import the zip file but it refused to import it at all

**Comment by Hammerfest** [comment]
Happening to me as well with zip or .csv

For what its worth its also happening with SkyTube as well

I checked out the CSV file, its formatted as it should be (from what I can find online) so no clue why its failing to import now.

**Comment by replete** [comment]
Android 12, Importing the CSV crases instantly, but importing the `takeout.zip` does work. The messaging in the UI needs updating in light of this.

**Comment by realdomdom** [comment]
I have the same issue, but on Android 7

 ### Checklist 
* [x]  I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
* [x]  I made sure that there are _no existing issues_ - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
* [x]  I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
* [x]  This issue contains only one bug.
* [x]  I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version
0.25.0

### Steps to reproduce the bug
1. Go to 'Subscriptions' > 'Import from' > 'Youtube'
2. Click 'Import file'
3. Select the *.csv file inside the takeout *.zip file from YouTube in the file explorer

### Expected behavior
Subscriptions are imported

### Actual behavior
Newpipe crashes

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/8751735/235346803-f6edb838-e6bc-485f-aa91-8677c4a1efd4.mp4

### Logs
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ DE
* __Content Language:__ de-DE
* __App Language:__ de_DE
* __Service:__ none
* __Version:__ 0.25.0
* __OS:__ Linux Android 7.0 - 24
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start service org.schabi.newpipe.local.subscription.services.SubscriptionsImportService@b729aff with Intent { cmp=org.schabi.newpipe/.local.subscription.services.SubscriptionsImportService (has extras) }: java.lang.IllegalArgumentException: Invalid mode. Only reading "r" supported, but got: "r".
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3550)
	at android.app.ActivityThread.-wrap23(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1685)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
Caused by: java.lang.IllegalArgumentException: Invalid mode. Only reading "r" supported, but got: "r".
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
	at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:621)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1011)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:846)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:800)
	at us.shandian.giga.io.FileStreamSAF.<init>(FileStreamSAF.java:32)
	at org.schabi.newpipe.streams.io.StoredFileHelper.getStream(StoredFileHelper.java:192)
	at org.schabi.newpipe.local.subscription.services.SubscriptionsImportService.onStartCommand(SubscriptionsImportService.java:118)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3522)
	... 8 more

```
</details>
<hr>


### Affected Android/Custom ROM version
Android 7.0 / EMUI 5.1.2

### Affected device model
HUAWEI MediaPad M3 Lite 10 (BAH-W09)

### Additional information
