### ISSUE TITLE
Newpipe on youtube doesnt work with tor

### ISSUE THREAD

**Issue by Unknownoo** [TeamNewPipe/NewPipe#8289]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.2

### Steps to reproduce the bug

1.Connected to tor network.

### Expected behavior

Load youtube feeds and videos

### Actual behavior

Youtube is not working with tor on newpipe. I tried soundcloud with tor and its working. I tried to play a youtube video on a browser with tor and it worked. I even tried to watch a youtube video on newpipe with my original IP and it worked, but when Im turning on tor connection, newpipe doesnt load anything from youtube, even the whats new feed. I tried to fix it by uninstall and reinstall newpipe and orbot,but nothing changed.

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=ma2qDOkvaJo
* __Content Country:__ GR
* __Content Language:__ el
* __App Language:__ el_GR
* __Service:__ YouTube
* __Version:__ 0.22.2
* __OS:__ Linux Android 12 - 32
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not store JavaScript player
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.storePlayerJs(YoutubeStreamExtractor.java:1012)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getStsFromPlayerJs(YoutubeStreamExtractor.java:1080)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:781)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:79)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:74)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:116)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(Unknown Source:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda6.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15868)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: org.schabi.newpipe.extractor.exceptions.ParsingException: Embedded info did not provide YouTube player js url
	at org.schabi.newpipe.extractor.services.youtube.YoutubeJavaScriptExtractor.extractJavaScriptUrl(YoutubeJavaScriptExtractor.java:116)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeJavaScriptExtractor.extractJavaScriptCode(YoutubeJavaScriptExtractor.java:46)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeJavaScriptExtractor.extractJavaScriptCode(YoutubeJavaScriptExtractor.java:65)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.storePlayerJs(YoutubeStreamExtractor.java:1010)
	... 32 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12 / Lineage 19

**Comment by Unknownoo** [comment]
Quick update:
The problem fixed itself somehow.
The case can be closed.

**Comment by tsiflimagas** [comment]
You can close it yourself, you don't have to wait for a member.

**Comment by Unknownoo** [comment]
> You can close it yourself, you don't have to wait for a member.

I dont know how to do it. Im new here. 
However even if I wanted to close it I cant, because the error happened again.

**Comment by ChiefMikeK** [comment]
A possible reason is the tor exit-node's **country** and/or its **ip address** is being blocked by google's bot thinking DDOS/other. 
- Do you get any error?
- Have U tried restarting tor for a new connection exit node estab?

**Comment by Unknownoo** [comment]
> A possible reason is the tor exit-node's **country** and/or its **ip address** is being blocked by google's bot thinking DDOS/other.
> 
> * Do you get any error?
> * While trying browser access were U signed in to Google?
> * Have U tried restarting tor for a new connection exit node estab?

- The error chance is unknown when to occur
- I dont have g account to sign in for privacy concerns
- I tried (when the error happened) to switch countries on orbot but nothing changed

Newpipe now is working, but the error could show up again.
I didnt have this situation before

**Comment by Toasterbirb** [comment]
There is a chance that you just had an exit node in your own country.l It doesn't mean that your IP was leaked necessarily. Tor doesn't choose the exit node depending on your location

I have also sometimes had issues with Newpipe with Tor, but it usually fixes itself after switching the identity. The same issue happens on desktop aswell sometimes with youtube if you aren't using invidious etc. Youtube thinks you are a bot and wants you to do a captcha and Newpipe probably doesn't know how to handle situations like this (show the captcha).

This is mostly just the regular Tor experience.

**Comment by Unknownoo** [comment]
> There is a chance that you just had an exit node in your own country.l It doesn't mean that your IP was leaked necessarily. Tor doesn't choose the exit node depending on your location
> 
> I have also sometimes had issues with Newpipe with Tor, but it usually fixes itself after switching the identity. The same issue happens on desktop aswell sometimes with youtube if you aren't using invidious etc. Youtube thinks you are a bot and wants you to do a captcha and Newpipe probably doesn't know how to handle situations like this (show the captcha).
> 
> This is mostly just the regular Tor experience.

Oh, I understand now.
Thank you!

**Comment by opusforlife2** [comment]
You ticked and later un-ticked an item in the checklist. So just in case it was deliberate: the checklist isn't optional.
