### ISSUE TITLE
Newpipe crashes after exiting fullscreen mode while buffering

### ISSUE THREAD

**Issue by furu-ame** [TeamNewPipe/NewPipe#8293]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.22.2

### Steps to reproduce the bug

1. Open any video with a long playtime. A 2 hour video at 720p **should** work just fine
2. Enter full screen mode
3. Make the video buffer, can be acomplished by skipping to different parts of the video
4. While its buffering, exit full screen mode
5. The crash will occur after atleast 1 attempt of trying to reproduce this error.
Note: This bug doesn't work on all videos. I'm not sure why

### Expected behavior

The video should keep playing

### Actual behavior

Newpipe crashes, resulting an App/UI error

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/84872543/165238349-210bd267-f213-4bf7-81f1-5675b7626a1c.mp4

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.22.2
* __OS:__ Linux samsung/j5x3gjv/j5x3g:7.1.1/NMF26X/J510HXXU3BSD1:user/release-keys 7.1.1 - 25
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to destroy activity {org.schabi.newpipe/org.schabi.newpipe.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.IWindowSession.finishDrawing(android.view.IWindow)' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4670)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4697)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4982)
	at android.app.ActivityThread.-wrap21(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1665)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6816)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.IWindowSession.finishDrawing(android.view.IWindow)' on a null object reference
	at android.view.SurfaceView.updateWindow(SurfaceView.java:696)
	at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:258)
	at android.view.View.dispatchDetachedFromWindow(View.java:16937)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3398)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3398)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3398)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3398)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3398)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3398)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3398)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4936)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4910)
	at android.view.ViewGroup.removeView(ViewGroup.java:4841)
	at androidx.fragment.app.FragmentContainerView.removeView(FragmentContainerView.java:350)
	at androidx.fragment.app.SpecialEffectsController$Operation$State.applyState(SpecialEffectsController.java:452)
	at androidx.fragment.app.SpecialEffectsController$1.run(SpecialEffectsController.java:211)
	at androidx.fragment.app.SpecialEffectsController$Operation.complete(SpecialEffectsController.java:695)
	at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.java:744)
	at androidx.fragment.app.SpecialEffectsController$Operation.cancel(SpecialEffectsController.java:597)
	at androidx.fragment.app.SpecialEffectsController.forceCompleteAllOperations(SpecialEffectsController.java:332)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3132)
	at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:3107)
	at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:334)
	at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:330)
	at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:278)
	at org.schabi.newpipe.MainActivity.onDestroy(MainActivity.java:446)
	at android.app.Activity.performDestroy(Activity.java:7255)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1161)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4657)
	... 10 more

```
</details>
<hr>

### Affected Android/Custom ROM version

OS: Android 7.1.1  Version: Linux samsung/j5x3gjv/j5x3g:7.1.1/NMF26X/J510HXXU3BSD1:user/release-keys 7.1.1 - 25

### Affected device model

Samsung Galaxy J5 2016 (SM-J510H)

### Additional information

I have all animations disabled on my device

**Comment by opusforlife2** [comment]
> I have all animations disabled on my device

Did you try eliminating this as a source of the bug?

**Comment by 20brs** [comment]
I tried to reproduce this bug once more with all animations turned on.
The same crash occurs, so the device animations are not responsible for this

**Comment by fetcheroo** [comment]
I have a similar issue with Samsung Galaxy S3 (GT-I9300) running Android 7.1.2 (LineageOS 14.1); the app version used is 0.24.1 (current latest). The reproduction steps seem to match, although I'll add that in my case going full-screen also causes the video to either be replaced by a black screen or a still frame from the video; the audio continues playing, but trying to seek a different position in the video stops the audio, too.

Another thing is that the logs change based on whether the phone's "Back" key is used to exit the fullscreen mode, or the player's own fullscreen button. Glancing at file comparison it seems like the differences might not be related to the error itself but rather to the way the malfunctioning code is called. The log obtained by using the player's fullscreen button is almost exactly the same as the one posted by OP, except one renamed method and the line numbers being shifted (since it's a different version of the app).

In my case, changing the video format from MPEG-4 to either of the other two formats seems to make the issue disappear.

Not sure if this warrants a separate issue or not, as the behaviour, logs, the major Android version and even hardware manufacturer match. I will attach the logs just in case:
[Log_player_fullscreen_button.txt](https://github.com/TeamNewPipe/NewPipe/files/10475289/Log_player_fullscreen_button.txt)
[Log_phone_Back_key.txt](https://github.com/TeamNewPipe/NewPipe/files/10475291/Log_phone_Back_key.txt)

**Comment by abuturaaab** [comment]
Getting almost similar behavior, when existing from the Fullscreen the app(video playback) crashes every time, I'm on RealmeXT, ancientOS(CR) android 13.

```
{"user_action":"play stream","request":"Player error[type=ERROR_CODE_FAILED_RUNTIME_CHECK] occurred while playing https://www.youtube.com/watch?v=QOhLlvNlI20","content_language":"en-US","content_country":"US","app_language":"en_US","service":"YouTube","package":"org.schabi.newpipe","version":"0.25.0","os":"Linux Android 13 - 33","time":"2023-03-07 12:43","exceptions":["com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loopOnce(Looper.java:201)\n\tat android.os.Looper.loop(Looper.java:288)\n\tat android.os.HandlerThread.run(HandlerThread.java:67)\nCaused by: java.lang.IllegalArgumentException\n\tat android.media.MediaCodec.native_setSurface(Native Method)\n\tat android.media.MediaCodec.setOutputSurface(MediaCodec.java:2234)\n\tat com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter$$ExternalSyntheticApiModelOutline0.m(R8$$SyntheticClass:0)\n\tat com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.setOutputSurface(AsynchronousMediaCodecAdapter.java:262)\n\tat com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:1451)\n\tat com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutput(MediaCodecVideoRenderer.java:646)\n\tat com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:584)\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:1546)\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:1510)\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:1485)\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:521)\n\t... 4 more\n"],"user_comment":""}
```

**Comment by abuturaaab** [comment]
> Getting almost similar behavior, when existing from the Fullscreen the app(video playback) crashes every time, I'm on RealmeXT, ancientOS(CR) android 13.
> 
> Log: https://pastebin.com/DcY8f1tG

My issue wasn't related to the Newpipe, rather my Custom ROM was acting up for the Newpipe (only). I switched back to other ROM, and everything is working as intended.

**Comment by furu-ame** [comment]
I have tested this on the newest version (0.27.4) and the issue still persists. Here's the log:
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.27.4
* __OS:__ Linux samsung/j5x3gjv/j5x3g:7.1.1/NMF26X/J510HXXU3BSD1:user/release-keys 7.1.1 - 25
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to destroy activity {org.schabi.newpipe/org.schabi.newpipe.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.IWindowSession.performDeferredDestroy(android.view.IWindow)' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4670)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4697)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4982)
	at android.app.ActivityThread.-wrap21(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1665)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6816)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.IWindowSession.performDeferredDestroy(android.view.IWindow)' on a null object reference
	at android.view.SurfaceView.updateWindow(SurfaceView.java:698)
	at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:258)
	at android.view.View.dispatchDetachedFromWindow(View.java:16937)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3398)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3398)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3398)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3398)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3398)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3398)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3398)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4936)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4910)
	at android.view.ViewGroup.removeView(ViewGroup.java:4841)
	at androidx.fragment.app.FragmentContainerView.removeView(FragmentContainerView.kt:293)
	at androidx.fragment.app.SpecialEffectsController$Operation$State.applyState(SpecialEffectsController.kt:398)
	at androidx.fragment.app.SpecialEffectsController.enqueue$lambda$4$lambda$2(SpecialEffectsController.kt:147)
	at androidx.fragment.app.SpecialEffectsController.$r8$lambda$TeCmoVW0hctjg0BNHLP6mPbAs5U(SpecialEffectsController.kt:0)
	at androidx.fragment.app.SpecialEffectsController$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
	at androidx.fragment.app.SpecialEffectsController$Operation.complete(SpecialEffectsController.kt:608)
	at androidx.fragment.app.SpecialEffectsController$FragmentStateManagerOperation.complete(SpecialEffectsController.kt:663)
	at androidx.fragment.app.SpecialEffectsController$Operation.cancel(SpecialEffectsController.kt:507)
	at androidx.fragment.app.SpecialEffectsController.forceCompleteAllOperations(SpecialEffectsController.kt:293)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3037)
	at androidx.fragment.app.FragmentManager.dispatchDestroy(FragmentManager.java:2988)
	at androidx.fragment.app.FragmentController.dispatchDestroy(FragmentController.java:346)
	at androidx.fragment.app.FragmentActivity.onDestroy(FragmentActivity.java:258)
	at androidx.appcompat.app.AppCompatActivity.onDestroy(AppCompatActivity.java:283)
	at org.schabi.newpipe.MainActivity.onDestroy(MainActivity.java:451)
	at android.app.Activity.performDestroy(Activity.java:7255)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1161)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4657)
	... 10 more

```
</details>
<hr>

**Comment by furu-ame** [comment]
I have tried to reproduce this error on the Samsung S8+ (Android 9), Samsung A6+ (Android 10) and Samsung S10+ (Android 12). Neither of them had this issue. This appears to affect only Samsung devices running Android 7 (and maybe 8?), based on fetcheroo's previous reply.
