### ISSUE TITLE
ERROR_CODE_PARSING_CONTAINER_MALFORMED (Invalid NAT length) when playing videos

### ISSUE THREAD

**Issue by TheMCNerd2017** [TeamNewPipe/NewPipe#8310]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1. Go to a video that you partially watched
2. Play it normally.
3. Switch to the background player.
4. Switch back to the normal video player.

### Expected behavior

The video should continue to play normally.

### Actual behavior

The video randomly fails to play with a ERROR_CODE_PARSING_CONTAINER_MALFORMED error.

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_PARSING_CONTAINER_MALFORMED] occurred while playing https://www.youtube.com/watch?v=h5uGTLI0z7E
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.23.0
* __OS:__ Linux Android 12 - 32
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:611)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.ParserException: Invalid NAL length
	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readSample(Mp4Extractor.java:621)
	at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:258)
	at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
	at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1042)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

```
</details>
<hr>

### Affected Android/Custom ROM version

GrapheneOS 12

### Affected device model

Pixel 4 XL

### Additional information

The steps I listed is one way to get the error to come up. I've also encountered the error when attempting to play the video normally, play the video in the background, switch from background player to normal player, and switch from normal player to background player.

**Comment by guillp** [comment]
I have exactly the same error here. Updated to 0.23 a few minutes ago, tested the "seamless transition between video and background player", and got that error after a few seconds.

**Comment by lines-of-codes** [comment]
I got the same error too. Though I can't write the information about the error here because I already downgraded back to version 0.22.2 after I've seen the error. But it's pretty much the same thing as the issue description.

Device is Samsung Galaxy A12 (Android 11, One UI Core 3.1, Knox 3.7)

**Comment by TheMCNerd2017** [comment]
After I did more testing, I found out that the issue was coming up for me due to some older cached files not being compatible with 0.23.0 (cached files were from 0.22.2). Clearing the cache fixed the issue on my end.

**Comment by lines-of-codes** [comment]
After the above comment, I tried to do the same thing too, I upgraded to version 0.23.0 again, but this time before playing any video, I tried clearing the cache first, and... it did solve the problem, and now it's running fine as it should be...

**Comment by guillp** [comment]
I confirm that a simple clear cache allows to play the videos affected by this bug! 😊

**Comment by opusforlife2** [comment]
@Stypox Do we not clear the cache upon first start after a version upgrade?

**Comment by Stypox** [comment]
I don't think so

**Comment by opusforlife2** [comment]
Ummm... shouldn't we?

**Comment by Stypox** [comment]
It would definitely make sense

**Comment by ulidtko** [comment]
Got this error without any backgrounding. Clearing app cache helped.

**Comment by ColinTimBarndt** [comment]
I'm having the same issue, but clearing the cache does not resolve it.

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_PARSING_CONTAINER_MALFORMED] occurred while playing https://www.youtube.com/watch?v=pNp4ug5F6To
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.23.0
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:611)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:233)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.ParserException: Invalid NAL length
	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1405)
	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:342)
	at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
	at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1042)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```
</details>
<hr>

**Comment by anantvdb** [comment]
The same issue occurred for me for a single video seemingly randomly.
0.23.0 is the first version I installed, so in my case it is not related to a version upgrade.
Clearing the app cache from system settings (note: not the metadata cache) solved the issue.

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_PARSING_CONTAINER_MALFORMED] occurred while playing https://www.youtube.com/watch?v=LL3lZn2VksQ
* __Content Country:__ US
* __Content Language:__ en
* __App Language:__ en
* __Service:__ YouTube
* __Version:__ 0.23.0
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:611)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:233)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.ParserException: Invalid NAL length
	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1405)
	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:342)
	at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
	at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1042)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```
</details>
<hr>

**Comment by AudricV** [comment]
This issue, which should be YouTube specific, should not happen anymore as we use DASH for YouTube playback since 0.23.1 (even if we have a fallback to progressive sources for the DASH progressive streams that YouTube return). Closing this issue as fixed.
