### ISSUE TITLE
Network errors on live streams (and crashes)

### ISSUE THREAD

**Issue by theycallhermax** [TeamNewPipe/NewPipe#8334]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1. Go to a live stream
There will be network errors.

### Expected behavior

Not supposed to happen.

### Actual behavior

Sadly, it happens.

### Affected Android/Custom ROM version

Android 4.4.4

### Affected device model

Samsung Galaxy Tab E Lite

**Comment by opusforlife2** [comment]
Paste the error report, please.

**Comment by Mwalters75** [comment]
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ CA
* __Content Language:__ en
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.23.0
* __OS:__ Linux Android 4.4.4 - 19
<details><summary><b>Crash log </b></summary><p>
```
java.lang.OutOfMemoryError
	at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:723)
	at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:548)
	at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:872)
	at android.content.res.Resources.loadDrawable(Resources.java:3465)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:614)
	at android.widget.ImageView.<init>(ImageView.java:134)
	at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:74)
	at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:69)
	at androidx.appcompat.app.AppCompatViewInflater.createImageView(AppCompatViewInflater.java:199)
	at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:119)
	at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1563)
	at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1614)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:691)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:762)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:771)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:499)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
	at org.schabi.newpipe.databinding.ChannelHeaderBinding.inflate(ChannelHeaderBinding.java:90)
	at org.schabi.newpipe.fragments.list.channel.ChannelFragment.getListHeaderSupplier(ChannelFragment.java:154)
	at org.schabi.newpipe.fragments.list.BaseListFragment.initViews(BaseListFragment.java:238)
	at org.schabi.newpipe.fragments.list.BaseListInfoFragment.initViews(BaseListInfoFragment.java:51)
	at org.schabi.newpipe.BaseFragment.onViewCreated(BaseFragment.java:67)
	at org.schabi.newpipe.fragments.BaseStateFragment.onViewCreated(BaseStateFragment.java:42)
	at org.schabi.newpipe.fragments.list.channel.ChannelFragment.onViewCreated(ChannelFragment.java:131)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5584)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
	at dalvik.system.NativeStart.main(Native Method)

```

**Comment by ShareASmile** [comment]
> ### Affected Android/Custom ROM version

Android 4.4.4

Closing, since we have dropped support for Kitkat devices a long time ago.
