### ISSUE TITLE
Player error[type=ERROR_CODE_IO_READ_POSITION_OUT_OF_RANGE] occurred

### ISSUE THREAD

**Issue by freezewind** [TeamNewPipe/NewPipe#8364]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1. Playing https://www.youtube.com/watch?v=iO10xF7Wn70
2. Player error[type=ERROR_CODE_IO_READ_POSITION_OUT_OF_RANGE] occurred

### Expected behavior

Play the video without error

### Actual behavior

Error occurred and the video can't play

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_READ_POSITION_OUT_OF_RANGE] occurred while playing https://www.youtube.com/watch?v=iO10xF7Wn70
* __Content Country:__ JP
* __Content Language:__ ja
* __App Language:__ ja
* __Service:__ YouTube
* __Version:__ 0.23.0
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:613)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.upstream.DataSourceException
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:587)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1009)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12

**Comment by litetex** [comment]
``...CacheDataSource...``
Maybe deleting the cache helps?

Might be a duplicate of #8310

**Comment by freezewind** [comment]
Clear cache fix the issue. Thanks.
