### ISSUE TITLE
ERROR_CODE_FAILED_RUNTIME_CHECK comes up when attempting to play a video in the background when another video is almost finished playing

### ISSUE THREAD

**Issue by TheMCNerd2017** [TeamNewPipe/NewPipe#8379]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1. Play a video in the background.
2. When said video is close to finishing (less than 5 to 10 seconds left) start to play another video in the background.

### Expected behavior

The new video plays in the background without any issues.

### Actual behavior

The new video fails to play and a ERROR_CODE_FAILED_RUNTIME_CHECK error comes up.

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_FAILED_RUNTIME_CHECK] occurred while playing https://www.youtube.com/watch?v=ZbwVPuXFDo8
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.23.0
* __OS:__ Linux Android 12 - 32
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:625)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.lang.IllegalArgumentException
	at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:39)
	at com.google.android.exoplayer2.source.BaseMediaSource.prepareSource(BaseMediaSource.java:207)
	at com.google.android.exoplayer2.source.CompositeMediaSource.prepareChildSource(CompositeMediaSource.java:120)
	at com.google.android.exoplayer2.source.MaskingMediaSource.prepareSourceInternal(MaskingMediaSource.java:85)
	at com.google.android.exoplayer2.source.BaseMediaSource.prepareSource(BaseMediaSource.java:214)
	at com.google.android.exoplayer2.source.CompositeMediaSource.prepareChildSource(CompositeMediaSource.java:120)
	at com.google.android.exoplayer2.source.ConcatenatingMediaSource.addMediaSourceInternal(ConcatenatingMediaSource.java:778)
	at com.google.android.exoplayer2.source.ConcatenatingMediaSource.addMediaSourcesInternal(ConcatenatingMediaSource.java:761)
	at com.google.android.exoplayer2.source.ConcatenatingMediaSource.prepareSourceInternal(ConcatenatingMediaSource.java:464)
	at com.google.android.exoplayer2.source.BaseMediaSource.prepareSource(BaseMediaSource.java:214)
	at com.google.android.exoplayer2.source.CompositeMediaSource.prepareChildSource(CompositeMediaSource.java:120)
	at com.google.android.exoplayer2.source.MaskingMediaSource.prepareSourceInternal(MaskingMediaSource.java:85)
	at com.google.android.exoplayer2.source.BaseMediaSource.prepareSource(BaseMediaSource.java:214)
	at com.google.android.exoplayer2.MediaSourceList.prepareChildSource(MediaSourceList.java:446)
	at com.google.android.exoplayer2.MediaSourceList.prepare(MediaSourceList.java:291)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.prepareInternal(ExoPlayerImplInternal.java:704)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:483)
	... 4 more

```
</details>
<hr>

### Affected Android/Custom ROM version

GrapheneOS 12

### Affected device model

Pixel 4 XL

### Additional information

I can consistently reproduce this issue with any video I try. I also recorded this issue happening as well however the video file is too big to upload (Android screen recordings are very large even when the duration is very short).

**Comment by litetex** [comment]
Looks like this is caused by:

https://github.com/google/ExoPlayer/blob/f1b37bc547e7194354fe31e240afa8a8fb0b5c6c/library/core/src/main/java/com/google/android/exoplayer2/source/BaseMediaSource.java#L207 which calls https://developer.android.com/reference/android/os/Looper#myLooper()
> Returns null if the calling thread is not associated with a Looper.

Does the problem occur with the same settings on a stock-android device/emulator?

**Comment by TheMCNerd2017** [comment]
> Looks like this is caused by:
> 
> https://github.com/google/ExoPlayer/blob/f1b37bc547e7194354fe31e240afa8a8fb0b5c6c/library/core/src/main/java/com/google/android/exoplayer2/source/BaseMediaSource.java#L207 which calls https://developer.android.com/reference/android/os/Looper#myLooper()
> 
> > Returns null if the calling thread is not associated with a Looper.
> 
> Does the problem occur with the same settings on a stock-android device/emulator?

I am not sure since I don't have access to a stock Android device and my home internet (768kbps Frontier Communications DSL) is too slow and unreliable to download an emulator image.

**Comment by TheMCNerd2017** [comment]
OK, I just encountered the issue again, this time while trying to play a video in the background while another one was in the middle of playing (not near the end like I was able to consistently reproduce). I'm not sure if I should update the original name and description of the issue, but if I should do so please tell me.

I pasted the error report below, just in case anything from it differs compared to the original one.

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_FAILED_RUNTIME_CHECK] occurred while playing https://www.youtube.com/watch?v=I322_vTkj68
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.23.0
* __OS:__ Linux Android 12 - 32
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:625)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.lang.IllegalArgumentException
	at com.google.android.exoplayer2.util.Assertions.checkArgument(Assertions.java:39)
	at com.google.android.exoplayer2.source.BaseMediaSource.prepareSource(BaseMediaSource.java:207)
	at com.google.android.exoplayer2.source.CompositeMediaSource.prepareChildSource(CompositeMediaSource.java:120)
	at com.google.android.exoplayer2.source.MaskingMediaSource.prepareSourceInternal(MaskingMediaSource.java:85)
	at com.google.android.exoplayer2.source.BaseMediaSource.prepareSource(BaseMediaSource.java:214)
	at com.google.android.exoplayer2.source.CompositeMediaSource.prepareChildSource(CompositeMediaSource.java:120)
	at com.google.android.exoplayer2.source.ConcatenatingMediaSource.addMediaSourceInternal(ConcatenatingMediaSource.java:778)
	at com.google.android.exoplayer2.source.ConcatenatingMediaSource.addMediaSourcesInternal(ConcatenatingMediaSource.java:761)
	at com.google.android.exoplayer2.source.ConcatenatingMediaSource.prepareSourceInternal(ConcatenatingMediaSource.java:464)
	at com.google.android.exoplayer2.source.BaseMediaSource.prepareSource(BaseMediaSource.java:214)
	at com.google.android.exoplayer2.source.CompositeMediaSource.prepareChildSource(CompositeMediaSource.java:120)
	at com.google.android.exoplayer2.source.MaskingMediaSource.prepareSourceInternal(MaskingMediaSource.java:85)
	at com.google.android.exoplayer2.source.BaseMediaSource.prepareSource(BaseMediaSource.java:214)
	at com.google.android.exoplayer2.MediaSourceList.prepareChildSource(MediaSourceList.java:446)
	at com.google.android.exoplayer2.MediaSourceList.prepare(MediaSourceList.java:291)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.prepareInternal(ExoPlayerImplInternal.java:704)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:483)
	... 4 more

```
</details>
<hr>
