### ISSUE TITLE
App errors/crashes when importing subscriptions

### ISSUE THREAD

**Issue by DavidRLTG** [TeamNewPipe/NewPipe#8383]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1. Go to subscriptions
2. Import from YouTube
3. Use the subscriptions zip file
4. App fails to import subscriptions
5. Use extracted subscriptions.csv
6. App crashes

### Expected behavior

I expected my subscriptions to be imported D:

### Actual behavior

App has an error, or crashes.

### Screenshots/Screen recordings

https://ibb.co/wSDGzWj
https://ibb.co/h9THRbw

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.23.0
* __OS:__ Linux Android 12 - 32
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start service org.schabi.newpipe.local.subscription.services.SubscriptionsImportService@1c98d13 with Intent { cmp=org.schabi.newpipe/.local.subscription.services.SubscriptionsImportService (has extras) }: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{995a5b9 32739:org.schabi.newpipe/u0a130} (pid=32739, uid=10130) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4724)
	at android.app.ActivityThread.access$2000(ActivityThread.java:256)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2129)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7877)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{995a5b9 32739:org.schabi.newpipe/u0a130} (pid=32739, uid=10130) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
	at android.os.Parcel.createException(Parcel.java:2409)
	at android.os.Parcel.readException(Parcel.java:2392)
	at android.os.Parcel.readException(Parcel.java:2334)
	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5947)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:7011)
	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:3365)
	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2526)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1844)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1675)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1622)
	at us.shandian.giga.io.FileStreamSAF.<init>(FileStreamSAF.java:32)
	at org.schabi.newpipe.streams.io.StoredFileHelper.getStream(StoredFileHelper.java:195)
	at org.schabi.newpipe.local.subscription.services.SubscriptionsImportService.onStartCommand(SubscriptionsImportService.java:118)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4706)
	... 9 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12L/crDroid/LineageOS 19

### Affected device model

M2012K11AG/Poco F3

**Comment by WhyNotHugo** [comment]
This looks like a duplicate of https://github.com/TeamNewPipe/NewPipe/issues/7411

**Comment by gcallip** [comment]
I concur fully. I get the same issues. OnePlus 6 Android 11.
I've been trying now for almost 3 weeks - get same response each time.

**Comment by DavidRLTG** [comment]
Final Update, I fixed the issue. It was very easy.
Thank you WhyNotHugo, for sending me #7411.
All I had to do was to download a video and set a folder for where videos are downloaded, then import subs. That worked! ^w^ so yeah, thank you all for all your help, And I hope I helped you too. Have a good day lads, thank you all for everything!
