### ISSUE TITLE
newpipe bug report

### ISSUE THREAD

**Issue by ghost** [TeamNewPipe/NewPipe#8392]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

SUBSRIBE TO A CHANNEL

## Exception
* __User Action:__ get subscription
* __Request:__ Get subscription status
* __Content Country:__ IN
* __Content Language:__ en-IN
* __App Language:__ en_IN
* __Service:__ YouTube
* __Version:__ 0.23.0
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalArgumentException: No suitable parent found from the given view. Please provide a valid view.
	at com.google.android.material.snackbar.Snackbar.makeInternal(Snackbar.java:198)
	at com.google.android.material.snackbar.Snackbar.make(Snackbar.java:157)
	at com.google.android.material.snackbar.Snackbar.make(Snackbar.java:262)
	at org.schabi.newpipe.fragments.list.channel.ChannelFragment.showNotifySnackbar(ChannelFragment.java:425)
	at org.schabi.newpipe.fragments.list.channel.ChannelFragment.lambda$monitorSubscription$3(ChannelFragment.java:259)
	at org.schabi.newpipe.fragments.list.channel.ChannelFragment.$r8$lambda$kKnl6ApHfDm8LSrzW7WrxdfY7uM(Unknown Source:0)
	at org.schabi.newpipe.fragments.list.channel.ChannelFragment$$ExternalSyntheticLambda8.accept(Unknown Source:4)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8037)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

```
</details>
<hr>

**Comment by Nqtural** [comment]
Fill out all the feilds; without the "Expected behaviour" and "Actual behaviour" sections, we can not help you.

**Comment by TiA4f8R** [comment]
Also, please fill your device properties too: its OEM, its model, its ROM and its Android version.

**Comment by TacoTheDank** [comment]
Author account no longer exists. Could this be closed, then?
