### ISSUE TITLE
java.lang.IllegalArgumentException: Span count should be at least 1. Provided 0

### ISSUE THREAD

**Issue by VeteranCoder** [TeamNewPipe/NewPipe#8442]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1. Set up split screen between New Pipe and another app while in portrait mode.
2. Switch to landscape using auto rotate mode.
3. Rotate back to portrait.

Important details: i am using a lineage OS GSI on an SM-T510.  It also has MicroG.  Given the DOM error i doubt it is relevant.

### Expected behavior

Smooth transition beteen landscape and portrait

### Actual behavior

The included crash.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.23.0
* __OS:__ Linux Android 12 - 32
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalArgumentException: Span count should be at least 1. Provided 0
	at androidx.recyclerview.widget.GridLayoutManager.setSpanCount(GridLayoutManager.java:829)
	at androidx.recyclerview.widget.GridLayoutManager.<init>(GridLayoutManager.java:86)
	at org.schabi.newpipe.local.BaseLocalListFragment.getGridLayoutManager(BaseLocalListFragment.java:109)
	at org.schabi.newpipe.local.BaseLocalListFragment.initViews(BaseLocalListFragment.java:126)
	at org.schabi.newpipe.local.playlist.LocalPlaylistFragment.initViews(LocalPlaylistFragment.java:142)
	at org.schabi.newpipe.BaseFragment.onViewCreated(BaseFragment.java:67)
	at org.schabi.newpipe.fragments.BaseStateFragment.onViewCreated(BaseStateFragment.java:42)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1471)
	at android.app.Activity.performStart(Activity.java:8079)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3732)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

```
</details>
<hr>

### Affected Android/Custom ROM version

lineage OS 19 GSI.

### Affected device model

samsung tab a 10.1 (2019) SM-T510

### Additional information

Build:  lineage_a64_bvS-userdebug 12 SP2A.220505.002 eng.crossg.20220510.160417 test-keys

**Comment by seanzzy** [comment]
hi, i would like to work on this issue, can I get assigned?

**Comment by litetex** [comment]
@seanzzy I assigned you. Feel free to go on.

**Comment by ShareASmile** [comment]
@VeteranCoder please test the apk from #13803 and comment on PR which includes an attempt to fix your issue.
