### ISSUE TITLE
Unrecoverable Player Error Ocurred

### ISSUE THREAD

**Issue by BrainBlasted** [TeamNewPipe/NewPipe#845]
- [x] I carefully read the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md) and agree to them.
- [x] I checked if the issue/feature exists in the latest version.

Hey, on the latest update from F-Droid, I'm getting the an error that says Unrecoverable Player Error  Occurred when playing any video on NewPipe, and also when trying to background play.

To update, this is not fixed by reinstalling the app.

Another update, it was not fixed by downgrading to 0.10.2 either. If other users can replicate this issue, this may be in response to the fork that showed up on the Play Store a few days ago.
**Android Version:** 6.0.1
**NewPipe Version:** 0.11.0
**Phone Model:** ZTE Zmax Pro (Z981)

**Comment by BrainBlasted** [comment]
Got a relevant looking logcat:
```
7164 11-13 21:34:07.677   544  4569 I OMX-VDEC-1080P: Exit OMX vdec Destructor: fd=-1^M
7165 11-13 21:34:07.677   544  4569 E OMX     : FAILED to allocate omx component 'OMX.qcom.video.decoder.avc' err=InsufficientResources(0x80001000)^M
7166 11-13 21:34:07.677 29746 22038 W ACodec  : Allocating component 'OMX.qcom.video.decoder.avc' failed, try next one.^M
7167 11-13 21:34:07.677 29746 22038 E ACodec  : Unable to instantiate codec 'OMX.qcom.video.decoder.avc' with err 0xfffffff4.^M
7168 11-13 21:34:07.677 29746 22038 E ACodec  : signalError(omxError 0xfffffff4, internalError -12)^M
7169 11-13 21:34:07.687 29746 22037 E MediaCodec: Codec reported err 0xfffffff4, actionCode 0, while in state 1^M
7170 11-13 21:34:07.717 29746 22032 W MediaCodec-JNI: try to release MediaCodec from JMediaCodec::~JMediaCodec()...^M
7171 11-13 21:34:07.717 29746 22032 W MediaCodec-JNI: done releasing MediaCodec from JMediaCodec::~JMediaCodec().^M
7172 11-13 21:34:07.737  1428  1451 D UsageStatsService: User[0] Got usage event for com.android.providers.calendar[1510626846670]: SYSTEM_INTERACTION^M
7173 11-13 21:34:07.747 29746 22032 E ExoPlayerImplInternal: Renderer error.^M
7174 11-13 21:34:07.747 29746 22032 E ExoPlayerImplInternal: com.google.android.exoplayer2.ExoPlaybackException^M
7175 11-13 21:34:07.747 29746 22032 E ExoPlayerImplInternal:         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:395)^M
7176 11-13 21:34:07.747 29746 22032 E ExoPlayerImplInternal:         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:382)^M
7177 11-13 21:34:07.747 29746 22032 E ExoPlayerImplInternal:         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:814)^M
7178 11-13 21:34:07.747 29746 22032 E ExoPlayerImplInternal:         at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:432)^M
7179 11-13 21:34:07.747 29746 22032 E ExoPlayerImplInternal:         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:513)^M
7180 11-13 21:34:07.747 29746 22032 E ExoPlayerImplInternal:         at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:564)^M
7181 11-13 21:34:07.747 29746 22032 E ExoPlayerImplInternal:         at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:340)^M
7182 11-13 21:34:07.747 29746 22032 E ExoPlayerImplInternal:         at android.os.Handler.dispatchMessage(Handler.java:98)^M
7183 11-13 21:34:07.747 29746 22032 E ExoPlayerImplInternal:         at android.os.Looper.loop(Looper.java:171)^M
7184 11-13 21:34:07.747 29746 22032 E ExoPlayerImplInternal:         at android.os.HandlerThread.run(HandlerThread.java:61)^M
7185 11-13 21:34:07.747 29746 22032 E ExoPlayerImplInternal: Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc     , Format(1, null, video/avc, -1, null, [640, 360, -1.0], [-1, -1])^M
7186 11-13 21:34:07.747 29746 22032 E ExoPlayerImplInternal:         ... 9 more^M
7187 11-13 21:34:07.747 29746 22032 E ExoPlayerImplInternal: Caused by: android.media.MediaCodec$CodecException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffff4^M
7188 11-13 21:34:07.747 29746 22032 E ExoPlayerImplInternal:         at android.media.MediaCodec.native_setup(Native Method)^M
7189 11-13 21:34:07.747 29746 22032 E ExoPlayerImplInternal:         at android.media.MediaCodec.<init>(MediaCodec.java:1670)^M
7190 11-13 21:34:07.747 29746 22032 E ExoPlayerImplInternal:         at android.media.MediaCodec.createByCodecName(MediaCodec.java:1651)^M
7191 11-13 21:34:07.747 29746 22032 E ExoPlayerImplInternal:         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:368)^M
7192 11-13 21:34:07.747 29746 22032 E ExoPlayerImplInternal:         ... 8 more^M
7193 11-13 21:34:07.747 22043 22043 W System  : ClassLoader referenced unknown path: /system/priv-app/CalendarProviderZTE/lib/arm64^M
7194 11-13 21:34:07.757 22043 22043 W System  : ClassLoader referenced unknown path: /system/framework/IZTESecurity.jar^M
7195 11-13 21:34:07.757 22043 22043 W System  : ClassLoader referenced unknown path: /system/framework/com.zte.ZTESecurity.jar^M
7196 11-13 21:34:07.787 22043 22043 I CalendarProvider2: Created com.android.providers.calendar.CalendarAlarmManager@2dae6a0(com.android.providers.calendar.CalendarProvider2@9392259)^M
```
Further down...
```
7197 11-13 21:34:07.797 29039 29039 D KP2AAF  : URL=androidapp://org.schabi.newpipe^M
7198 11-13 21:34:07.797 29039 29039 D KP2AAF  : Cancel notif^M
7199 11-13 21:34:07.797 29039 29039 D KP2AAF  : OnAccEvent^M
7200 11-13 21:34:07.797 29039 29039 D KP2AAF  : event: 2048, package = org.schabi.newpipe^M
7201 11-13 21:34:07.797 29039 29039 D KP2AAF  : no com.android.systemui^M
7202 11-13 21:34:07.807 29746 29746 W System.err: com.google.android.exoplayer2.ExoPlaybackException^M
7203 11-13 21:34:07.807 29746 29746 W System.err:    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.throwDecoderInitError(MediaCodecRenderer.java:395)^M
7204 11-13 21:34:07.807 29746 29746 W System.err:    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:382)^M
7205 11-13 21:34:07.807 29746 29746 W System.err:    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:814)^M
7206 11-13 21:34:07.807 29746 29746 W System.err:    at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:432)^M
7207 11-13 21:34:07.807 29746 29746 W System.err:    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:513)^M
7208 11-13 21:34:07.807 29746 29746 W System.err:    at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:564)^M
7209 11-13 21:34:07.807 29746 29746 W System.err:    at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:340)^M
7210 11-13 21:34:07.807 29746 29746 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:98)^M
7211 11-13 21:34:07.807 29746 29746 W System.err:    at android.os.Looper.loop(Looper.java:171)^M
7212 11-13 21:34:07.807 29746 29746 W System.err:    at android.os.HandlerThread.run(HandlerThread.java:61)^M
7213 11-13 21:34:07.807 29746 29746 W System.err: Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1,      null, video/avc, -1, null, [640, 360, -1.0], [-1, -1])^M
7214 11-13 21:34:07.807 29746 29746 W System.err:    ... 9 more^M
7215 11-13 21:34:07.807 29746 29746 W System.err: Caused by: android.media.MediaCodec$CodecException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffff4^M
7216 11-13 21:34:07.807 29746 29746 W System.err:    at android.media.MediaCodec.native_setup(Native Method)^M
7217 11-13 21:34:07.807 29746 29746 W System.err:    at android.media.MediaCodec.<init>(MediaCodec.java:1670)^M
7218 11-13 21:34:07.807 29746 29746 W System.err:    at android.media.MediaCodec.createByCodecName(MediaCodec.java:1651)^M
7219 11-13 21:34:07.807 29746 29746 W System.err:    at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:368)^M
7220 11-13 21:34:07.807 29746 29746 W System.err:    ... 8 more^M
7221 11-13 21:34:07.837  1428 32546 W WindowManager: jiangmin Set focused app to: AppWindowToken{19aca30 token=Token{2d37b73 ActivityRecord{c54ebe2 u0 org.schabi.newpipe/.MainActivity t9488}}} old focus=AppWindo     wToken{7505ecc token=Token{f9e50ff ActivityRecord{48eb01e u0 org.schabi.newpipe/.player.MainVideoPlayer t9488}}} moveFocusNow=true^M
7222 11-13 21:34:07.847 21976 22039 I EventLogChimeraService: Opted in for usage reporting^M
7223 11-13 21:34:07.847 29630  1873 D AlertService: No fired or scheduled alerts^M
```
One more section that stood out
```
7308 11-13 21:34:08.347 29746 29746 I ExoPlayerImpl: Release 2149ba5 [ExoPlayerLib/2.5.1] [urd, Z981, ZTE, 23] [goog.exo.core]^M
7309 11-13 21:34:08.367  1428  4634 I MediaFocusControl:  AudioFocus  abandonAudioFocus() from android.media.AudioManager@4cc11d7org.schabi.newpipe.player.MainVideoPlayer$VideoPlayerImpl@658bdad^M
7310 11-13 21:34:08.387 29746 29746 W MessageQueue: Handler (android.os.Handler) {e61a8e2} sending message to a Handler on a dead thread^M
7311 11-13 21:34:08.387 29746 29746 W MessageQueue: java.lang.IllegalStateException: Handler (android.os.Handler) {e61a8e2} sending message to a Handler on a dead thread^M
7312 11-13 21:34:08.387 29746 29746 W MessageQueue:  at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)^M
7313 11-13 21:34:08.387 29746 29746 W MessageQueue:  at android.os.Handler.enqueueMessage(Handler.java:635)^M
7314 11-13 21:34:08.387 29746 29746 W MessageQueue:  at android.os.Handler.sendMessageAtTime(Handler.java:604)^M
7315 11-13 21:34:08.387 29746 29746 W MessageQueue:  at android.os.Handler.sendMessageDelayed(Handler.java:574)^M
7316 11-13 21:34:08.387 29746 29746 W MessageQueue:  at android.os.Handler.sendEmptyMessageDelayed(Handler.java:538)^M
7317 11-13 21:34:08.387 29746 29746 W MessageQueue:  at android.os.Handler.sendEmptyMessage(Handler.java:519)^M
7318 11-13 21:34:08.387 29746 29746 W MessageQueue:  at com.google.android.exoplayer2.ExoPlayerImplInternal.stop(ExoPlayerImplInternal.java:247)^M
7319 11-13 21:34:08.387 29746 29746 W MessageQueue:  at com.google.android.exoplayer2.ExoPlayerImpl.stop(ExoPlayerImpl.java:262)^M
7320 11-13 21:34:08.387 29746 29746 W MessageQueue:  at com.google.android.exoplayer2.SimpleExoPlayer.stop(SimpleExoPlayer.java:609)^M
7321 11-13 21:34:08.387 29746 29746 W MessageQueue:  at org.schabi.newpipe.player.BasePlayer.destroyPlayer(BasePlayer.java:262)^M
7322 11-13 21:34:08.387 29746 29746 W MessageQueue:  at org.schabi.newpipe.player.BasePlayer.destroy(BasePlayer.java:274)^M
7323 11-13 21:34:08.387 29746 29746 W MessageQueue:  at org.schabi.newpipe.player.VideoPlayer.destroy(VideoPlayer.java:398)^M
7324 11-13 21:34:08.387 29746 29746 W MessageQueue:  at org.schabi.newpipe.player.MainVideoPlayer.onDestroy(MainVideoPlayer.java:132)^M
7325 11-13 21:34:08.387 29746 29746 W MessageQueue:  at android.app.Activity.performDestroy(Activity.java:6456)^M
7326 11-13 21:34:08.387 29746 29746 W MessageQueue:  at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1143)^M
7327 11-13 21:34:08.387 29746 29746 W MessageQueue:  at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3818)^M
7328 11-13 21:34:08.387 29746 29746 W MessageQueue:  at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3849)^M
7329 11-13 21:34:08.387 29746 29746 W MessageQueue:  at android.app.ActivityThread.access$1500(ActivityThread.java:150)^M
7330 11-13 21:34:08.387 29746 29746 W MessageQueue:  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)^M
7331 11-13 21:34:08.387 29746 29746 W MessageQueue:  at android.os.Handler.dispatchMessage(Handler.java:102)^M
7332 11-13 21:34:08.387 29746 29746 W MessageQueue:  at android.os.Looper.loop(Looper.java:171)^M
7333 11-13 21:34:08.387 29746 29746 W MessageQueue:  at android.app.ActivityThread.main(ActivityThread.java:5417)^M
7334 11-13 21:34:08.387 29746 29746 W MessageQueue:  at java.lang.reflect.Method.invoke(Native Method)^M
7335 11-13 21:34:08.387 29746 29746 W MessageQueue:  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)^M
7336 11-13 21:34:08.387 29746 29746 W MessageQueue:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)^M
7337 11-13 21:34:08.387 29746 29746 I ExoPlayerImpl: Release 2149ba5 [ExoPlayerLib/2.5.1] [urd, Z981, ZTE, 23] [goog.exo.core]^M
```

**Comment by BrainBlasted** [comment]
A reboot has fixed the issue for now on 0.10.2. Will see what happens after an upgrade over the next few days.

**Comment by Msuvo0000** [comment]
![Screenshot_2022-08-11-09-19-11-458_com android soundrecorder](https://user-images.githubusercontent.com/111035335/184062182-d81e10de-939d-4bac-8092-8be1e98a1e06.jpg)

**Comment by Msuvo0000** [comment]
No music is playing
