### ISSUE TITLE
Bug report my first big report ever

### ISSUE THREAD

**Issue by 10sp** [TeamNewPipe/NewPipe#8470]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

47677.76868

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ IN
* __Content Language:__ en-IN
* __App Language:__ en_IN
* __Service:__ none
* __Version:__ 0.22.1
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1844)
	at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1884)
	at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:329)
	at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:294)
	at androidx.fragment.app.DialogFragment.show(DialogFragment.java:260)
	at org.schabi.newpipe.RouterActivity.lambda$openDownloadDialog$19(RouterActivity.java:646)
	at org.schabi.newpipe.RouterActivity.$r8$lambda$--0YcizsE0Kz2-_9bdoMW02jdkQ(Unknown Source:0)
	at org.schabi.newpipe.RouterActivity$$ExternalSyntheticLambda14.accept(Unknown Source:4)
	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7864)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

```
</details>
<hr>

### Expected behavior

.

### Screenshots/Screen recordings

.....jxjjfhfududkis
Hdjdjdj....jxjjfhfududkis
Hdjdjdj....jxjjfhfududkis
Hdjdjdj....jxjjfhfududkis
Hdjdjdj....jxjjfhfududkis
Hdjdjdj....jxjjfhfududkis
Hdjdjdj....jxjjfhfududkis
Hdjdjdj....jxjjfhfududkis
Hdjdjdj

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ IN
* __Content Language:__ en-IN
* __App Language:__ en_IN
* __Service:__ none
* __Version:__ 0.22.1
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1844)
	at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1884)
	at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:329)
	at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:294)
	at androidx.fragment.app.DialogFragment.show(DialogFragment.java:260)
	at org.schabi.newpipe.RouterActivity.lambda$openDownloadDialog$19(RouterActivity.java:646)
	at org.schabi.newpipe.RouterActivity.$r8$lambda$--0YcizsE0Kz2-_9bdoMW02jdkQ(Unknown Source:0)
	at org.schabi.newpipe.RouterActivity$$ExternalSyntheticLambda14.accept(Unknown Source:4)
	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7864)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)

```
</details>
<hr>

### Affected Android/Custom ROM version

.....jxjjfhfududkis Hdjdjdj

### Affected device model

.....jxjjfhfududkis Hdjdjdj

### Additional information

....jxjjfhfududkis
Hdjdjdj ....jxjjfhfududkis
Hdjdjdj....jxjjfhfududkis
Hdjdjdj....jxjjfhfududkis
Hdjdjdj....jxjjfhfududkis
Hdjdjdj....jxjjfhfududkis
Hdjdjdj....jxjjfhfududkis
Hdjdjdj....jxjjfhfududkis
Hdjdjdj....jxjjfhfududkis
Hdjdjdj....jxjjfhfududkis
Hdjdjdj....jxjjfhfududkis
Hdjdjdj

**Comment by TiA4f8R** [comment]
Please fill in properly all required details.

**Comment by opusforlife2** [comment]
And do it in a new issue.
