### ISSUE TITLE
App crush

### ISSUE THREAD

**Issue by rajarshikhatua100** [TeamNewPipe/NewPipe#8513]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

I forgot

### Logs

FATAL EXCEPTION: main
Process: org.schabi.newpipe, PID: 18701
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.schabi.newpipe.streams.io.StoredFileHelper.getName()' on a null object reference
	at us.shandian.giga.ui.common.Deleter.next(Deleter.java:91)
	at us.shandian.giga.ui.common.Deleter.$r8$lambda$B-Gi_zHjoCZ_wZjG8qf-dwFZmVE(Unknown Source:0)
	at us.shandian.giga.ui.common.Deleter$$ExternalSyntheticLambda2.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

### Affected Android/Custom ROM version

Android 12

### Affected device model

Samsung galaxy m31

### Additional information

Everything was alright

**Comment by litetex** [comment]
Without a reproduction manual we can't do anything.

Please reopen/create a new issue once you know how to reproduce the bug.
