### ISSUE TITLE
Crash on playing videos

### ISSUE THREAD

**Issue by inaseem** [TeamNewPipe/NewPipe#8560]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

Please follow the attached video

### Expected behavior

Video should play

### Actual behavior

Crashes

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/6770106/176244183-a4649d75-5216-4b20-a433-e13680594a91.mp4

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.23.0
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to create service org.schabi.newpipe.player.MainPlayer: java.lang.NumberFormatException: For input string: "default"
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4662)
	at android.app.ActivityThread.access$1600(ActivityThread.java:301)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2185)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: java.lang.NumberFormatException: For input string: "default"
	at java.lang.Integer.parseInt(Integer.java:615)
	at java.lang.Integer.parseInt(Integer.java:650)
	at org.schabi.newpipe.player.helper.PlayerHelper.getProgressiveLoadIntervalBytes(PlayerHelper.java:434)
	at org.schabi.newpipe.player.helper.PlayerDataSource.<init>(PlayerDataSource.java:42)
	at org.schabi.newpipe.player.Player.<init>(Player.java:433)
	at org.schabi.newpipe.player.MainPlayer.createView(MainPlayer.java:106)
	at org.schabi.newpipe.player.MainPlayer.onCreate(MainPlayer.java:100)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4650)
	... 8 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 11/ one ui core 3.1

### Affected device model

Samsung Galaxy m31s

**Comment by AudricV** [comment]
You imported data from a debug version between 0.22.1 and 0.23.0 (maybe the release candidate of 0.23.0).

Because the default value string ressource name for the `Playback load interval size` preference has been renamed from `progressive_load_interval_default` to `progressive_load_interval_exoplayer_default` and that value is interpreted as number (which cannot be possible, hence the crash), you need to set one of the values in the dialog of the preference (available in `Settings`, `Video and audio`, `Playback load interval size`) (the value which has been set on the release is `64kb`).

As a note for the future: trying to import databases from debug APKs to releases is not guaranteed to have no unexcepted behavior in releases.

Thank you.

**Comment by yaamas** [comment]
@AudricV That is very helpful information. Let me try that.

**Comment by yaamas** [comment]
That was the issue for me. I had jumped on a debug build before when normal builds weren't working and all the normal updates haven't been working since then. Thanks @AudricV , I'm going to add my error here for SEO so that others can find it easily.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.23.2
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to create service org.schabi.newpipe.player.MainPlayer: java.lang.NumberFormatException: For input string: "default"
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4528)
	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2162)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.NumberFormatException: For input string: "default"
	at java.lang.Integer.parseInt(Integer.java:747)
	at java.lang.Integer.parseInt(Integer.java:865)
	at org.schabi.newpipe.player.helper.PlayerHelper.getProgressiveLoadIntervalBytes(PlayerHelper.java:426)
	at org.schabi.newpipe.player.helper.PlayerDataSource.<init>(PlayerDataSource.java:84)
	at org.schabi.newpipe.player.Player.<init>(Player.java:432)
	at org.schabi.newpipe.player.MainPlayer.createView(MainPlayer.java:106)
	at org.schabi.newpipe.player.MainPlayer.onCreate(MainPlayer.java:100)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4515)
	... 9 more

```
</details>
<hr>
