### ISSUE TITLE
Video crashes with java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by finedust** [TeamNewPipe/NewPipe#8562]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

Try to play [this video](https://www.youtube.com/watch?v=z1zuk-jCHas), at time 1h1'59'' crashes.

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_UNSPECIFIED] occurred while playing https://www.youtube.com/watch?v=z1zuk-jCHas
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ YouTube
* __Version:__ 0.23.0
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:617)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected ArrayIndexOutOfBoundsException: src.length=65536 srcPos=-1854894023 dst.length=65536 dstPos=0 length=1854894023
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:433)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ArrayIndexOutOfBoundsException: src.length=65536 srcPos=-1854894023 dst.length=65536 dstPos=0 length=1854894023
	at java.lang.System.arraycopy(System.java:527)
	at com.google.android.exoplayer2.extractor.DefaultExtractorInput.updatePeekBuffer(DefaultExtractorInput.java:264)
	at com.google.android.exoplayer2.extractor.DefaultExtractorInput.skipFromPeekBuffer(DefaultExtractorInput.java:230)
	at com.google.android.exoplayer2.extractor.DefaultExtractorInput.skipFully(DefaultExtractorInput.java:103)
	at com.google.android.exoplayer2.extractor.DefaultExtractorInput.skipFully(DefaultExtractorInput.java:115)
	at com.google.android.exoplayer2.extractor.mkv.DefaultEbmlReader.read(DefaultEbmlReader.java:149)
	at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor.read(MatroskaExtractor.java:510)
	at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
	at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1042)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	... 3 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 10 / crDroid 6.8

### Affected device model

Xiaomi Mi A3

### Additional information

This is not related to firewall or VPN. Other videos are not affected as far as I know.

**Comment by AudricV** [comment]
Cannot reproduce this issue<sup>1</sup>, which seems to be not related to us, but to an error in ExoPlayer internal work. Anyway, force-stopping the app and/or trying to clear the application cache may fix the issue.

<sup>1</sup>By using WEBM or MPEG-4 1080p60 and trying to seek close to the time you wrote (close to a few seconds). What was the format and the resolution you were using? Did you seek exactly to this time or were you just playing the video normally?
