### ISSUE TITLE
NPE while opening video

### ISSUE THREAD

**Issue by zhenyolka** [TeamNewPipe/NewPipe#8570]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.0

### Steps to reproduce the bug

1. Open any video

### Expected behavior

1. See video

### Actual behavior

1. App crashes and show guru meditation error

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ RU
* __Content Language:__ ru-RU
* __App Language:__ ru_RU
* __Service:__ none
* __Version:__ 0.23.0
* __OS:__ Linux Android 12 - 32
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to create service org.schabi.newpipe.player.MainPlayer: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setColorFilter(android.graphics.ColorFilter)' on a null object reference
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4567)
	at android.app.ActivityThread.access$1700(ActivityThread.java:256)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2110)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setColorFilter(android.graphics.ColorFilter)' on a null object reference
	at org.schabi.newpipe.player.Player.initViews(Player.java:488)
	at org.schabi.newpipe.player.Player.setupFromView(Player.java:471)
	at org.schabi.newpipe.player.MainPlayer.createView(MainPlayer.java:107)
	at org.schabi.newpipe.player.MainPlayer.onCreate(MainPlayer.java:100)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4554)
	... 9 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12.1/Corvus vS3.2 Vindicate

### Affected device model

Mi 9 Lite (pyxis)

### Additional information

This bug reproducable only on Corvus. I used same version of NewPipe on CRDroid and all was ok. Maybe its because I built Corvus 2 days ago and it containing latest AOSP changes? Crdroid contained mid-June changes.

**Comment by opusforlife2** [comment]
It's definitely caused by your ROM build, seeing this function in the crash report: `void android.graphics.drawable.Drawable.setColorFilter(android.graphics.ColorFilter)`

Try building it again?
