### ISSUE TITLE
0.23.1 - Exceptions -> timeout, or problem with resolving youtube domain

### ISSUE THREAD

**Issue by pawlosck** [TeamNewPipe/NewPipe#8579]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

23.1

### Steps to reproduce the bug

Just start play any movie.

### Actual behavior

NewPipe throws exceptions and stops playing. After some time (few seconds), movie is resumed, but not always.

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_NETWORK_CONNECTION_TIMEOUT] occurred while playing https://www.youtube.com/watch?v=Nf9XKjemDg0
* __Content Country:__ PL
* __Content Language:__ pl
* __App Language:__ en
* __Service:__ YouTube
* __Version:__ 0.23.1
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:613)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:65)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketTimeoutException: timeout
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.read(YoutubeHttpDataSource.java:502)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.read(DefaultDataSource.java:263)
	at com.google.android.exoplayer2.upstream.TeeDataSource.read(TeeDataSource.java:70)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.read(CacheDataSource.java:622)
	at com.google.android.exoplayer2.upstream.StatsDataSource.read(StatsDataSource.java:92)
	at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromUpstream(DefaultExtractorInput.java:291)
	at com.google.android.exoplayer2.extractor.DefaultExtractorInput.read(DefaultExtractorInput.java:68)
	at com.google.android.exoplayer2.source.SampleDataQueue.sampleData(SampleDataQueue.java:178)
	at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:590)
	at com.google.android.exoplayer2.extractor.TrackOutput$-CC.$default$sampleData(TrackOutput.java:157)
	at com.google.android.exoplayer2.source.SampleQueue.sampleData(Unknown Source:0)
	at com.google.android.exoplayer2.source.chunk.BundledChunkExtractor$BindingTrackOutput.sampleData(BundledChunkExtractor.java:233)
	at com.google.android.exoplayer2.extractor.TrackOutput$-CC.$default$sampleData(TrackOutput.java:157)
	at com.google.android.exoplayer2.source.chunk.BundledChunkExtractor$BindingTrackOutput.sampleData(Unknown Source:0)
	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1444)
	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:342)
	at com.google.android.exoplayer2.source.chunk.BundledChunkExtractor.read(BundledChunkExtractor.java:153)
	at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:127)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.net.SocketTimeoutException: timeout
	at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:221)
	at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:261)
	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
	at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:60)
	at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:602)
	at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:396)
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.readInternal(YoutubeHttpDataSource.java:841)
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.read(YoutubeHttpDataSource.java:500)
	... 21 more
Caused by: java.net.SocketException: socket is closed
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:584)
	at com.android.okhttp.okio.Okio$2.read(Okio.java:141)
	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	... 26 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 9

### Affected device model

Samsung Galaxy s8

### Additional information

It happened, when I installed latest 23.1 version. When I restore previous version (23.0) problem disappear.

NewPipe throws 2 exceptions.
1. timeout
2. problem with resolving youtube domain (movie is playing, so it's strange) -> I saw it one times, so I can't attach to issue

**Comment by AudricV** [comment]
When the issue happens in the player, can you play the same resolution (and if applicable, the audio stream) in an external player?

Does it happens with all qualities?

Also, do you have network issues when downloading the contents in the app and/or with tools such as yt-dlp? Network issues has been reported in it by some users, for which the fallback server provided by YouTube in its streaming URLs seems to work.

**Comment by Symbian9** [comment]
I have similar issue with `v0.23.3` and `v0.24.0-RC3` builds for the last days: most of YouTube videos are failed to load after trying to play it (in video screen, in popup and in background mode).

FTR, I have stable Internet connection, but trying to play almost all videos it appears infinity loading failed in 1-2 minutes with next error:

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_NETWORK_CONNECTION_TIMEOUT] occurred while playing https://www.youtube.com/watch?v=vw_WxslG_A4
* __Content Country:__ US
* __Content Language:__ en
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.23.3
* __OS:__ Linux Android 6.0.1 - 23
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:613)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketTimeoutException: failed to connect to rr2---sn-8ph2xajvh-n8vs.googlevideo.com/85.249.244.45 (port 443) after 8000ms
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:389)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:786)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:599)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.chunk.InitializationChunk.load(InitializationChunk.java:99)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.net.SocketTimeoutException: failed to connect to rr2---sn-8ph2xajvh-n8vs.googlevideo.com/85.249.244.45 (port 443) after 8000ms
	at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
	at libcore.io.IoBridge.connect(IoBridge.java:122)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
	at java.net.Socket.connect(Socket.java:884)
	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:117)
	at com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:438)
	at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:178)
	at com.android.okhttp.Connection.connect(Connection.java:1324)
	at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:1412)
	at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:131)
	at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:481)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:462)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:368)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:476)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:418)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:540)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:385)
	... 10 more

```
</details>
<hr>

**Comment by AudricV** [comment]
@pawlosck @Symbian9 Does increasing connection timeout and read timeout to 30 seconds (for all requests, including the playback ones), and using Cronet for playback improves the issue, or better, fixes it?

Here is a debug APK with these changes: [app-debug-use-cronet-for-playback.zip](https://github.com/TeamNewPipe/NewPipe/files/9641236/app-debug-use-cronet-for-playback.zip)

Note: the source code of these changes is not published yet.

**Comment by pawlosck** [comment]
My problem was solved, when I installed next version after 0.23.1. Currently, I can play any movie without any problems. Sometimes, NewPipe show info about some error, but I can play  movie, so I don't read it and I don't know if this is the same error.

**Comment by opusforlife2** [comment]
Thanks for confirming.

@Symbian9 Please open a new issue.

**Comment by Symbian9** [comment]
> Please open a new issue.

JFTR, I guess my issue related to existed one issue report:

- https://github.com/TeamNewPipe/NewPipe/issues/9010

**Comment by AudricV** [comment]
> JFTR, I guess my issue might be related to existed one issue report

Not at all, please open a new issue, like opusforlife2 said.
