### ISSUE TITLE
Can't resume YouTube videos after not playing for a long time

### ISSUE THREAD

**Issue by timsu92** [TeamNewPipe/NewPipe#8627]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.1

### Steps to reproduce the bug

1. Goto a channel in YouTube
2. Press `background` to play in the background
3. Shuffle the playlist using the notification
4. ...Listen to music...
5. Pause and wait for a long time
6. Play it

### Expected behavior

Continue fluently or try to load the video/audio again just like a click on the video, but start from the current time

### Actual behavior

HTTP 403 and play the next video.
This behavior is new in this new version.
Before, it stucks somewhat like #5730, except I didn't face what that user said:
> 8. Try to go back to previously paused video via History, Playlists tab, etc (problem is here again)

Details below.

### Logs

HTTP error 403 happened after a long time not listening to YouTube (eg. a good night's sleep😴; a nap isn't suffice)
Before updating to 0.23.1, it used to behave somewhat like #5730. 
## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_BAD_HTTP_STATUS] occurred while playing https://www.youtube.com/watch?v=mnvsE7UtFVA
* __Content Country:__ TW
* __Content Language:__ zh-TW
* __App Language:__ zh_TW_#Hant
* __Service:__ YouTube
* __Version:__ 0.23.1
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:613)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:422)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:786)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:599)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:124)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12 stock image

### Affected device model

Samsung Galaxy S21 5G

### Additional information

**In the previous versions, I did things similar to #5730 and I got something similar.**
### Steps to reproduce the bug
1. Goto a YouTube channel and play by pressing `background` to play in the background
2. Shuffle the playlist using the notification
3. Do the same from 2~6
4. The video in the background stucks, with the loading funnel in the notification eternal.
### Workaround:
1. Do NOT resume right away after pause for a long time (However, I've forgotten whether this is a requirement)
5. Switch to last track (since I'm in a playlist)
6. Play. It needs few seconds to start playing, but it always successes.
7. Switch to next track, which is the one I want to continue to listen to
8. Excellent! It continues to play right from the time I paused it after few seconds just like it did in the third point.

**Comment by timsu92** [comment]
Content in "Additional information" -> "Workaround" was wrong. Correct now.

**Comment by timsu92** [comment]
It seems that the workaround I mentioned in the last section of this issue is working in this new version as well

**Comment by nakic** [comment]
Great to see a well written bug report on the exact issue I wanted to report, so that I don't have to write it up: nice work, @timsu92!

The workaround is technically doable, but slow, requires remembering to do the workaround and it's not clear when the workaround is required (how much time has to pass for the link to YT to timeout), so in effect, the workaround should be used almost always, making it impractical.

**Comment by Suncatcher** [comment]
I have the same issue

## Exception
* __User Action:__ play stream
* __Request:__ Player[type=ERROR_CODE_IO_BAD_HTTP_STATUS] occurred while playing https://www.youtube.com/watch?v=djJS79GmsG0
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.27.2
* __OS:__ Linux samsung/a54xue/a54x:14/UP1A.231005.007/A546U1UEU8CXH1:user/release-keys 14 - 34

<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)\n\tat com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loopOnce(Looper.java:230)\n\tat android.os.Looper.loop(Looper.java:319)\n\tat android.os.HandlerThread.run(HandlerThread.java:67)\nCaused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403\n\tat org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:422)\n\tat com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)\n\tat com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)\n\tat com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:796)\n\tat com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:609)\n\tat com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)\n\tat com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:124)\n\tat com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)\n\tat java.lang.Thread.run(Thread.java:1012)\n"],"user_comment":""}

```
</details>

**Comment by dftf-stu** [comment]
Yeah, this is one of the major issues for me in NewPipe -- I'm on the latest 0.28.0 release, and it still has this issue of not being able to resume a video after about 5 or 10 minutes of it being paused, and instead restarts from the beginning, losing my place.

I've just started always swiping the app closed, then going to the hamburger menu, then history, and then tapping it there as a workaround as then it always does pick-up where I last was.

Clearly, a workaround like this really should be necessary though.  Can't NewPipe just skip-back to where a video last was after starting it again?  Surely when a user pauses the video, you only need to save the marker the video is on?
