### ISSUE TITLE
Cannot play any youtube videos

### ISSUE THREAD

**Issue by zolagonano** [TeamNewPipe/NewPipe#8652]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.1

### Steps to reproduce the bug

1. Open any YouTube videos

### Expected behavior

Play the video

### Actual behavior

NewPipe gives an error saying "Sorry, something went wrong"

### Screenshots/Screen recordings

<img alt="screenshot cleaned" src="https://user-images.githubusercontent.com/77786351/179467714-eb515b01-0e35-4ed4-8d90-6bf7bab01489.png" height=600 />

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=iywaBOMvYLI
* __Content Country:__ US
* __Content Language:__ en
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.23.1
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not store JavaScript player
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.storePlayerJs(YoutubeStreamExtractor.java:1001)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.initStsFromPlayerJsIfNeeded(YoutubeStreamExtractor.java:1069)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:763)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:78)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:73)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:118)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(ExtractorHelper.java)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda6.call(R8$$SyntheticClass)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15868)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: org.schabi.newpipe.extractor.exceptions.ParsingException: Embedded info did not provide YouTube player js url
	at org.schabi.newpipe.extractor.services.youtube.YoutubeJavaScriptExtractor.extractJavaScriptUrl(YoutubeJavaScriptExtractor.java:116)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeJavaScriptExtractor.extractJavaScriptCode(YoutubeJavaScriptExtractor.java:46)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeJavaScriptExtractor.extractJavaScriptCode(YoutubeJavaScriptExtractor.java:65)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.storePlayerJs(YoutubeStreamExtractor.java:999)
	... 32 more

```
</details>
<hr>

**Comment by zolagonano** [comment]
Update:  The problem got fixed somehow, probably youtube had changed something and reverted it.

**Comment by PNeigel** [comment]
Similar behavior here, no video works, but my crash log is a little different:

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_TIMEOUT] occurred while playing https://www.youtube.com/watch?v=Ww3ESHE9aps
* __Content Country:__ DE
* __Content Language:__ de-DE
* __App Language:__ de_DE
* __Service:__ YouTube
* __Version:__ 0.23.1
* __OS:__ Linux samsung/d2seea/d2s:12/SP1A.210812.016/N975FXXU8HVE5:user/release-keys 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
	at com.google.android.exoplayer2.ExoPlayerImpl.setVideoOutputInternal(ExoPlayerImpl.java:2489)
	at com.google.android.exoplayer2.ExoPlayerImpl.setVideoSurface(ExoPlayerImpl.java:1246)
	at org.schabi.newpipe.player.playback.SurfaceHolderCallback.surfaceDestroyed(SurfaceHolderCallback.java:53)
	at android.view.SurfaceView.notifySurfaceDestroyed(SurfaceView.java:2186)
	at android.view.SurfaceView.updateSurface(SurfaceView.java:1318)
	at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:419)
	at android.view.View.dispatchWindowVisibilityChanged(View.java:15475)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1637)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1637)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1637)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1637)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1637)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1637)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1637)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1637)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1637)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1637)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1637)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1637)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1637)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1637)
	at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1637)
	at com.android.internal.policy.DecorView.dispatchWindowVisibilityChanged(DecorView.java:4745)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3477)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2911)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10458)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
	at android.view.Choreographer.doFrame(Choreographer.java:797)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: com.google.android.exoplayer2.ExoTimeoutException: Detaching surface timed out.
	at com.google.android.exoplayer2.ExoPlayerImpl.setVideoOutputInternal(ExoPlayerImpl.java:2487)
	... 37 more

```
</details>
<hr>

**Comment by mhmdanas** [comment]
Closing, since the problem was fixed.

@PNeigel your stack trace seems to be the same as the one in https://github.com/TeamNewPipe/NewPipe/issues/8401.
