### ISSUE TITLE
4k and 2k video not playing

### ISSUE THREAD

**Issue by BigDogg99** [TeamNewPipe/NewPipe#8694]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.1

### Steps to reproduce the bug

1. Set default resolution  to best
2. enable show higher resolution
3. play any 2k or 4k video

### Expected behavior

video should play

### Actual behavior

video dont even open instead I get notification

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_DECODING_FAILED] occurred while playing https://www.youtube.com/watch?v=YOSQIUGGdYE
* __Content Country:__ US
* __Content Language:__ en
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.23.1
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(313, null, null, video/x-vnd.on2.vp9, vp9, 11136677, en, [3840, 1920, 30.0], [-1, -1]), format_supported=YES
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:575)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:223)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.qcom.video.decoder.vp9
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1512)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:813)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)
	... 3 more
Caused by: java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
	at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.dequeueOutputBufferIndex(SynchronousMediaCodecAdapter.java:106)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1806)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:792)
	... 5 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 11 / hovoc OS v4.16

### Affected device model

Poco X2

### Additional information

I am facing this issue in only latest update.

**Comment by phillipweinstock** [comment]
I just attempted to recreate it with the pixel 4XL, no dice the video plays perfectly.
So I'll see if I can emulate the Poco X2

**Comment by BigDogg99** [comment]
> I just attempted to recreate it with the pixel 4XL, no dice the video plays perfectly. So I'll see if I can emulate the Poco X2

https://www.youtube.com/watch?v=linlz7-Pnvw try this

**Comment by opusforlife2** [comment]
Works fine here. Try this on another device. The crash log looks suspiciously like your OS/device decoder is failing to play it.

**Comment by AudricV** [comment]
> The crash log looks suspiciously like your OS/device decoder is failing to play it.

Yes, it is.

@BigDogg99 Your screen phone screen resolution is 2400x1080, right? If yes, it seems to be intended to be not able to play resolutions which are higher than the one of your phone screen.

Also you're using a custom ROM, so this may be also the issue too.

According to the stack trace, the format is marked to be supported by your device. Make sure you closed apps that can use video decoders (maybe try to force-stop them). A device has limited media decoder instances which can be used at the same time, and this vary between devices. 

There is nothing we can do about this unfortunately, except trying to use a fallback decoder which may be less performant if there is one available or show more user-friendly messages.

Merging your issue into the one with all `MediaCodecVideoDecoderException` errors, #8016.
