### ISSUE TITLE
why newpipe dont work with 1.1.1.1

### ISSUE THREAD

**Issue by hydrasho** [TeamNewPipe/NewPipe#8753]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [x] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

latest

### Steps to reproduce the bug

hello i use newpipe and i use also the dns 1.1.1.1, why newpipe don't work with this DNS ?

you can install 1.1.1.1 on your playstore for test it or change your dns for 1.1.1.1

I want to clarify that it is only the search function that does not work:
I can deactivate 1.1.1.1 to search, launch a playlist and reactivate it, it works.

**Comment by mhmdanas** [comment]
What do you mean "the search function that does not work"? What happens when you try to search? Do you get an error report? If so, please post it here. A screen recording would also be useful regardless of whether you get an error.

**Comment by michael9dk** [comment]
I have no issues with 1dot1dot1dot1.cloudflare-dns.com on Android 10/11.

Did you install a questionable app to use 1.1.1.1? 
You dont need an app to change the DNS server.

**Comment by SC1040-TS2** [comment]
> I have no issues with 1dot1dot1dot1.cloudflare-dns.com on Android 10/11.
> 
> Did you install a questionable app to use 1.1.1.1? You dont need an app to change the DNS server.

Greetings. There is in fact an official app that Cloudflare provides for the 1.1.1.1 DNS service, found here: https://play.google.com/store/apps/details?id=com.cloudflare.onedotonedotonedotone

It is primarily used to enable the service through rerouting requests through the app, and through the WARP protocol that is enabled through a VPN service triggered by the app.

I once had some initial difficulties using the app, but ended up making it work for a bit settling on just using the manual setup in the router's settings and DNS over TLS. Maybe this user is experiencing similar.

The question is whether the user is attempting to connect through the basic service the app offers, or the WARP service.

**Comment by hydrasho** [comment]
Hello, sorry for the late reply!

- Yes I use the application given by cloudflare but I do not use WARP but only 1.1.1.1.

- Warp actually works unlike app 1.1.1.1
I can make a screen record, because it does not crash

**Comment by hydrasho** [comment]
`## Exception
* User Action: searched
* Request: zen kun
* Content Country: FR
* Content Language: fr-FR
* App Language: fr_FR
* Service: YouTube
* Version: 0.23.2
* OS: Linux OnePlus/Nord_EEA/Nord:12/RKQ1.211119.001/Q.202204221830:user/release-keys 12 - 31
<details><summary><b>Crash log </b></summary><p>

`
java.net.UnknownHostException: Unable to resolve host "www.youtube.com": No address associated with hostname
 at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
 at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
 at java.net.InetAddress.getAllByName(InetAddress.java:1152)
 at okhttp3.Dns$1.lookup(Dns.java:40)
 at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
 at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
 at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
 at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:215)
 at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
 at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
 at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
 at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
 at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
 at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
 at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
 at okhttp3.RealCall.execute(RealCall.java:93)
 at org.schabi.newpipe.DownloaderImpl.execute(DownloaderImpl.java:233)
 at org.schabi.newpipe.extractor.downloader.Downloader.post(Downloader.java:141)
 at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getJsonPostResponse(YoutubeParsingHelper.java:1100)
 at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeSearchExtractor.onFetchPage(YoutubeSearchExtractor.java:95)
 at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)
 at org.schabi.newpipe.extractor.search.SearchInfo.getInfo(SearchInfo.java:36)
 at org.schabi.newpipe.util.ExtractorHelper.lambda$searchFor$0(ExtractorHelper.java:82)
 at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$qyxpuXgomWa-cbONQns-pd7zxm0(Unknown Source:0)
 at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda9.call(Unknown Source:8)
 at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
 at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
 at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
 at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
 at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
 at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
 at java.util.concurrent.FutureTask.run(FutureTask.java:264)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
 at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
 at libcore.io.Linux.android_getaddrinfo(Native Method)
 at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
 at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:222)
 at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
 at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
 ... 42 more

`
</details>
<hr>`

**Comment by hydrasho** [comment]
Wait I'm not very sure of what I'm saying, I have the impression that on my school's wifi it's only 1.1.1.1 that works and not the opposite... I don't understand anything...

**Comment by hydrasho** [comment]
update:
Apparently the problem has surely been solved with the updates
there it was just my school which doesn't support youtube.com url at least i can counter pass with 1.1.1.1...
so I close :)
