### ISSUE TITLE
java.lang.NumberFormatException: For input string: "default"

### ISSUE THREAD

**Issue by tfga** [TeamNewPipe/NewPipe#8812]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

NewPipe_v0.23.2

### Steps to reproduce the bug

Just try to play any video. 

### Expected behavior

Play video. 

### Actual behavior

Crash. 

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.23.2
* __OS:__ Linux motorola/ali_n/ali_n:9/PPS29.55-37-7/445ae:user/release-keys 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to create service org.schabi.newpipe.player.MainPlayer: java.lang.NumberFormatException: For input string: "default"
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3761)
	at android.app.ActivityThread.access$1400(ActivityThread.java:213)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1826)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6923)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
Caused by: java.lang.NumberFormatException: For input string: "default"
	at java.lang.Integer.parseInt(Integer.java:615)
	at java.lang.Integer.parseInt(Integer.java:650)
	at org.schabi.newpipe.player.helper.PlayerHelper.getProgressiveLoadIntervalBytes(PlayerHelper.java:426)
	at org.schabi.newpipe.player.helper.PlayerDataSource.<init>(PlayerDataSource.java:84)
	at org.schabi.newpipe.player.Player.<init>(Player.java:432)
	at org.schabi.newpipe.player.MainPlayer.createView(MainPlayer.java:106)
	at org.schabi.newpipe.player.MainPlayer.onCreate(MainPlayer.java:100)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3749)
	... 8 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 9

### Affected device model

Moto g(6)

**Comment by unmanbearpig** [comment]
I got the same error on Android 12. Crashes on every video I've tried

**Comment by AudricV** [comment]
It seems like the database you use comes from a RC of 0.23.0 version. Look at https://github.com/TeamNewPipe/NewPipe/issues/8560#issuecomment-1169312571 to fix this and please take into consideration the note for the future.

Thank you.
