### ISSUE TITLE
App/UI crashed after clicking any video from suggested list after loading correctly a previous one.

### ISSUE THREAD

**Issue by chianse** [TeamNewPipe/NewPipe#8834]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.2

### Steps to reproduce the bug

1. Select video from main page or any personal list. 
2. Video loads and reproduces correctly. 
3. Select any video from suggested section. 
4. App tries to load new page/video and crashes. 
5. 

### Expected behavior

It'll seem like the app will load the new video, but it will crash and then open again with error report. You'll be able to watch another video after closing and reloading the app.

### Actual behavior

The app quickly shows paige from new selected video, crashes and reloads directly to error report.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.23.2
* __OS:__ Linux Android 7.0 - 24
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start service org.schabi.newpipe.player.MainPlayer@4e13165 with Intent { cmp=org.schabi.newpipe/.player.MainPlayer (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context org.schabi.newpipe.player.Player.getContext()' on a null object reference
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3415)
	at android.app.ActivityThread.-wrap21(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1636)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6272)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context org.schabi.newpipe.player.Player.getContext()' on a null object reference
	at org.schabi.newpipe.player.NotificationUtil.createNotification(NotificationUtil.java:92)
	at org.schabi.newpipe.player.NotificationUtil.createNotificationAndStartForeground(NotificationUtil.java:179)
	at org.schabi.newpipe.player.MainPlayer.onStartCommand(MainPlayer.java:126)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3398)
	... 8 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 7.0

### Affected device model

ZTE Blade A520

**Comment by Mession77** [comment]
Exact same issue here. Running Android 11.

See attached crash:
[crashlog.txt](https://github.com/TeamNewPipe/NewPipe/files/9388729/crashlog.txt)

**Comment by Mession77** [comment]
Same issue in version 0.23.3.

**Comment by opusforlife2** [comment]
Try 0.24.1?
