### ISSUE TITLE
Error — io bad,  player http status

### ISSUE THREAD

**Issue by Grannydontplay** [TeamNewPipe/NewPipe#8843]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.2

### Steps to reproduce the bug

Player error Crash report after playing a few videos on 'Auto-Enqueuing' [yt http issue?].  
Here's Share link (from video where player crashed) https://www.youtube.com/watch?v=IXXxciRUMzE&t=162

Tried above yt video link in NewPipe Legacy ver. 0.20.8; & it gave diff crash report. (How do I add that to my ver. 0.23.2  report? ) 

Tried again in ver. 23.2 & video played without crashing.  

*Unable to submit crash deets via Question format, soz =\ 

### Expected behavior

Expected video playback to continue normally after playing a few yt videos with Auto-Enqueuing selected for. 

### Actual behavior

Player error Crash report after playing a few videos on 'Auto-Enqueuing' [yt http issue?].  
Here's Share link (from video where player crashed) https://www.youtube.com/watch?v=IXXxciRUMzE&t=162

Tried above yt video link in NewPipe Legacy ver. 0.20.8; & it gave diff crash report. (How do I add that to my ver. 0.23.2  report? ) 

Tried again in ver. 23.2 & video played without crashing.  

*Unable to submit crash deets via Question format, soz =\ 

## Exception
* __User Action:__ requested comments
* __Request:__ https://m.youtube.com/watch?v=IXXxciRUMzE
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.20.8
* __OS:__ Linux motorola/minsk_retail/minsk:11/RPC31.Q2-109-16/3d2bb:user/release-keys 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not parse json data for comments
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getPage(YoutubeCommentsExtractor.java:97)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getInitialPage(YoutubeCommentsExtractor.java:52)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:19)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:40)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:25)
	at org.schabi.newpipelegacy.util.ExtractorHelper.lambda$getCommentsInfo$7(ExtractorHelper.java:166)
	at org.schabi.newpipelegacy.util.-$$Lambda$ExtractorHelper$c05hNbPsgDxL7UDIeF-SWkm_CC0.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15753)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:614)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: com.grack.nanojson.JsonParserException: Expected JSON value, got 0 on line 1, char 0
	at com.grack.nanojson.JsonTokener.createParseException(Unknown Source:44)
	at com.grack.nanojson.JsonParser.currentValue(Unknown Source:31)
	at com.grack.nanojson.JsonParser.parse(Unknown Source:4)
	at com.grack.nanojson.JsonParser$JsonParserContext.from(Unknown Source:19)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getPage(YoutubeCommentsExtractor.java:95)
	... 30 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 11

### Affected device model

Motorola G Stylus (2020)

### Additional information

Longtime listener, first time caller… 
Cannot recall if video was playing in Background mode or default, soz! 
Sending in case any info may help with frequent crashes from past week or so.
(If my submission is filled out incorrectly , I can try again on the next crash. Sry but did not find another post that looked OK to add to. Please share post with me if I need to send this in elsewhere in lieu of this current submission. Thanks) 

> Scroll up. Look at the version given in your crash report. It is 0.20.8. We need 0.23.2 there.

——Nm, 23.2 crash-rep is gone since I only clicked 'github' button. It's no trouble to delete OP.

**Comment by opusforlife2** [comment]
Wrong crash report. We need the one from the latest version, not the Legacy app.

**Comment by Grannydontplay** [comment]
> Wrong crash report. We need the one from the latest version, not the Legacy app.

This report is for 23.2 (non-legacy player).
I have a separate crash-rep for Legacy 20.8 player, asking how to add that here to the lastest ver 23.2 crash-rep

**Comment by opusforlife2** [comment]
Scroll up. Look at the version given in your crash report. It is 0.20.8. We need 0.23.2 there.

**Comment by Grannydontplay** [comment]
That is odd as I only clicked Submit via 23.2, did not try same link in Legacy until after I started this issue form. (?‽)

I'm not seeing where to re-submit crash-rep / scroll up unfortunately.  Is it best to delete & try again?

**Comment by opusforlife2** [comment]
If you have the correct 0.23.2 crash report, edit your issue description and replace the old report with the new one.

**Comment by Grannydontplay** [comment]
> Scroll up. Look at the version given in your crash report. It is 0.20.8. We need 0.23.2 there.

——Nm.  23.2 crash-rep is gone since I only hit 'github' button from app. 
 How to cancel this req.??
Didn't see a way under Edit. Thanks for your time.

**Comment by opusforlife2** [comment]
In the future, tap "Copy formatted report" in the Error report screen, and save the crash report in a text file so that it doesn't get lost.
