### ISSUE TITLE
Can't download anything since the last update. Galaxy S21 with FDroid version.

### ISSUE THREAD

**Issue by ETERNALBLUEbullrun** [TeamNewPipe/NewPipe#8846]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.1

### Steps to reproduce the bug

1. Goto any video
2. Click Download
3. Error

### Expected behavior

Download the video.

### Actual behavior

Button to reload, and this error:

## Exception
* __User Action:__ requested stream
* __Request:__ https://www.youtube.com/watch?v=Mo7c6xahV6M
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.23.1
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.stream.StreamInfo$StreamExtractException: Could not get any stream. See error variable to get further details.
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:188)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:82)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:73)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:118)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(Unknown Source:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda6.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15868)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

```
</details>
<hr>

### Affected Android/Custom ROM version

Did system update this week

### Affected device model

Galaxy S21 5G

**Comment by ETERNALBLUEbullrun** [comment]
Is there an update that will address this, or have you decided it is a problem with my device not with NewPipe?

**Comment by opusforlife2** [comment]
The problem is that you haven't followed the template like you were asked to. If you had, your problem would be automatically solved.

**Comment by ETERNALBLUEbullrun** [comment]
I just wasted over an hour painstakingly filling out every single mandatory (even though often irrelevent) piece of information that was demanded to help you devs find problems like this and fix them, and this is the thanks I get?

Well FUCk YOU TOO YOU PIECE OF SHIT, YOU CAN NOT CODE FOR FUCKING SHIT BITCH KILL YOURSELF

**Comment by ETERNALBLUEbullrun** [comment]
I can not believe that rude, abusive, disrespectful, incompetent buffoons such as yourself are getting more respect for worse quality work than me, and that you dare to treat your users so horribly when I bent over backwards to solve error reports that made this one you just closed look like the best, easiest possible to solve bug report ever, which you have just thrown your fat ugly stupid little hands up and ran away crying "OMG not enough info too complicated" like the lazy, worthless retarded piece of shit you are.

**Comment by ouzowtf** [comment]
Looking for a newer version than yours, which is available since 8 days, would be a smarter move than wasting an hour and make yourself an idiot on the internet like a Donald Trump fan. But hey, it's your choice.

**Comment by ChiefMikeK** [comment]
4 best updates try this

- [Add the NewPipe repository to F-Droid](https://newpipe.net/FAQ/tutorials/install-add-fdroid-repo/ )

**Comment by AudricV** [comment]
@ETERNALBLUEbullrun Like others said, if you were smart and you followed properly the template (for which you said you spent one hour), you would noticed that:

> - [x] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).

- you are not using the latest version, which is 0.23.2, which is available on official F-Droid repository since 4 days;

> - [x] I made sure that there are no existing issues - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.

- your issue is a duplicate of #8760.

> Well FUCk YOU TOO YOU PIECE OF SHIT, YOU CAN NOT CODE FOR FUCKING SHIT BITCH KILL YOURSELF

Sorry for you that we are (us and also a part of the community) too smart to find the issue, write fixes, and release a hotfix around one day and that you come more than one week after the fix was released and saying "I can't watch or download YouTube videos, please fix it" without following the issue template properly and searching for duplicates (for which you would found a ton of duplicates!). WE DON'T AND WE NEVER OWE YOU ANYTHING.

You behavior is inacceptable and violates [GitHub's Community Guidelines, section `Maintaining a strong community`, paragraph `Be respectful`](https://docs.github.com/en/site-policy/github-terms/github-community-guidelines#maintaining-a-strong-community).
