### ISSUE TITLE
Get suggestions on search error

### ISSUE THREAD

**Issue by WorkHard4470** [TeamNewPipe/NewPipe#8848]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.2

### Steps to reproduce the bug

Appears to have a problem on search suggestions as threw us a toast notification 
as error message

### Expected behavior

Trying to find suggestions but Suggestion Observer are broken. You will soon try to search content.

### Actual behavior

Please see the details given on that section. This happened if the suggestion observer does not work when you try to search the YouTube content.

### Logs

Get suggestions on search are temporarily broken. Affected version: 0.23.2 (bug fix version)
## Exception
* __User Action:__ get suggestions
* __Request:__ 
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.23.2
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to read from field 'androidx.recyclerview.widget.RecyclerView org.schabi.newpipe.databinding.FragmentSearchBinding.suggestionsList' on a null object reference in method 'void org.schabi.newpipe.fragments.list.search.SearchFragment.handleSuggestions(java.util.List)'
	at org.schabi.newpipe.fragments.list.search.SearchFragment.handleSuggestions(SearchFragment.java:950)
	at org.schabi.newpipe.fragments.list.search.SearchFragment.lambda$initSuggestionObserver$14(SearchFragment.java:791)
	at org.schabi.newpipe.fragments.list.search.SearchFragment.$r8$lambda$HpL953c8k1JPyNfRPyrPNskf55Q(Unknown Source:0)
	at org.schabi.newpipe.fragments.list.search.SearchFragment$$ExternalSyntheticLambda11.accept(Unknown Source:4)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8248)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12

### Affected device model

realme 8 4G

### Additional information

Hoping the developer will fix their only one bug, NOT more bugs in the future public beta versions.

**Comment by WorkHard4470** [comment]
``
