### ISSUE TITLE
Can't resume playing videos when moving from cellular to wifi

### ISSUE THREAD

**Issue by bobdanek** [TeamNewPipe/NewPipe#8863]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.2

### Steps to reproduce the bug

1. Watch a youtube video while out of home wifi range
2. Return home and auto-connect to wifi
3. Video cannot resume from wifi connection

### Expected behavior

Video resumes from wifi connection

### Actual behavior

Newpipe throws errors, cannot resume watching video unless I force-quit the app.

I also get repeated on-screen notifications (they cover up the on-screen keyboard spacebar perfectly) even in other apps, which says "An error occurred, see the notification". This is happening right now as I type this, which is a little frustrating

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_NETWORK_CONNECTION_FAILED] occurred while playing https://www.youtube.com/watch?v=2iuf09zRrBM
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.23.2
* __OS:__ Linux Android 12 - 32
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:613)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.UnknownHostException: Unable to resolve host "rr1---sn-uhvcpax0n5-25xe.googlevideo.com": No address associated with hostname
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:389)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:786)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:599)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.chunk.InitializationChunk.load(InitializationChunk.java:99)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.net.UnknownHostException: Unable to resolve host "rr1---sn-uhvcpax0n5-25xe.googlevideo.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:147)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at com.android.okhttp.Dns$1.lookup(Dns.java:41)
	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
	at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.makeConnection(YoutubeHttpDataSource.java:704)
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.makeConnection(YoutubeHttpDataSource.java:548)
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:383)
	... 10 more
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:136)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:221)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:136)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	... 28 more

```
</details>
<hr>

### Affected Android/Custom ROM version

GrapheneOS SQ3A.220705.004.2022081800

### Affected device model

Pixel 5

### Additional information

When I'm outside relying on cell signal, I'm often switching between video + audio and audio only. Not sure if that's relevant, since the issue only happens when returning home.

The same issue seems to happen in reverse - when I'm playing a video on wifi and I leave wifi range, newpipe doesn't seem to be able to handle the transition between networks.

**Comment by eladkarako** [comment]
<details><summary>that is not unique to NewPipe,  
but it is partially related to it, its infrastructure and recent YouTube changes.</summary>  

connections often drop when switching from WiFi/*G on TCP/IP, that's why most of G00gle products were using QUIC protocol over UDP to mitigate it.  
that aside, you probably feel the effect of YouTube changing their js player signature structure again, 3rd-party players needs to keep updating it, otherwise the download rate is substantially throttled (and NewPipe buffering was always somewhat sluggish).  
yt-dlp has already been updated multiple times in the last few days, and I assume NewPipe (and more importantly https://github.com/polymorphicshade/NewPipe) will follow eventually.
normally you'll get a fast enough (even on 3G) connection to fill the buffers so when the connection would cut out and re-established you won't notice it.  
that's the gist of it.  

the Android library Cronet with its magnificent buffering is too weighty on its own to be included into NewPipe, and its alternative slim referenced-version will require dependency on G00gle-framework installed on the device. so that's why it would probably won't be embedded into NewPipe..
</details>

**Comment by guru-of-sound** [comment]
Bug is also encountered when switching between different wifi access points

**Comment by opusforlife2** [comment]
Can you try toggling "mobile data always active" from "Developer options"?

**Comment by bobdanek** [comment]
Apologies, I missed your response.

Issue occurs regardless of the Mobile Data Always Active setting.

I have a hunch, looking at the last lines of the crash report, that it's due to me moving from LTE with ipv4+ipv6 connectivity, to my home wifi with only ipv4, and it's failing to resolve DNS because it's trying to resolve an AAAA record that no longer resolves.

If I start watching a different video, it works fine, so maybe something that's scoped only to "the currently playing video" is trying to hang onto ipv6 or ipv6 dns resolution
