### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by memz13155n** [TeamNewPipe/NewPipe#8866]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.2

### Steps to reproduce the bug

1. Watch any video
2. Wait for a playback error if it happens by chance

### Expected behavior

To play the video smoothly

### Actual behavior

Crashed and an exception occurred.

### Screenshots/Screen recordings

<img alt="Screenshot_20220823-073409" src="https://user-images.githubusercontent.com/98498676/186160197-f9c5ac8a-7e0d-4419-8733-1f9ddc02df01.png" height=600 />

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_NETWORK_CONNECTION_FAILED] occurred while playing https://www.youtube.com/watch?v=9WujHGP0ojY
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.23.2
* __OS:__ Linux Android 7.1.1 - 25
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:613)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:154)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.UnknownHostException: Unable to resolve host "rr3---sn-4avf-3po6.googlevideo.com": No address associated with hostname
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:389)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:786)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:599)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:124)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.net.UnknownHostException: Unable to resolve host "rr3---sn-4avf-3po6.googlevideo.com": No address associated with hostname
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:125)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74)
	at java.net.InetAddress.getAllByName(InetAddress.java:752)
	at com.android.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:187)
	at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:156)
	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:98)
	at com.android.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:346)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:247)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java)
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.makeConnection(YoutubeHttpDataSource.java:704)
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.makeConnection(YoutubeHttpDataSource.java:548)
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:383)
	... 10 more
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Posix.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:106)
	... 26 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Stock Android 7.1.1

### Affected device model

T-Mobile Revvl Plus  C3701A

### Additional information

Used with Bluetooth device.

**Comment by heinrich-ulbricht** [comment]
Cureently I'm experiencing this 100% when playing in the background. After some seconds the stream just cuts off. This is since 2 or 3 versions ago.

**Comment by MalikTH** [comment]
I've also been experiencing this error ever since 0.23.2 released. It sucks as I have moved away from daily driving services like Spotify to primarily use NewPipe's background playback feature, and this is still a major stability issue.

Android 12 on Galaxy A71 5G, with a Bluetooth device connected.

This also happens with SoundCloud streams. I'll post a log when it happens next there. I've not tested other sources.

**Comment by opusforlife2** [comment]
Try 0.24.1?

**Comment by memz13155n** [comment]
NewPipe 0.24.1 seems to fix it

**Comment by confluence** [comment]
I am using 0.24.1 and I am still experiencing this.

**Comment by opusforlife2** [comment]
Check for dupes and open a new issue.

**Comment by confluence** [comment]
Apologies; I'm no longer 100% sure that I saw the same error code -- the next time this happens I'll save the error output to make sure, and file a new issue.
