### ISSUE TITLE
Sometimes, deleting history will show an error screen.

### ISSUE THREAD

**Issue by orariley70** [TeamNewPipe/NewPipe#8874]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.2

### Steps to reproduce the bug

1. Open history
2. Tap and hold a history entry
3. Tap delete

### Expected behavior

Entry gets deleted

### Actual behavior

Sorry, something went wrong error screen appears.
However the history delete did go through successfully.

## Exception
* __User Action:__ something else
* __Request:__ History Statistics
* __Content Country:__ SG
* __Content Language:__ en-SG
* __App Language:__ en_SG
* __Service:__ none
* __Version:__ 0.23.2
* __OS:__ Linux Android 12 - 32
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Couldn't read row 1237, col 13 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:536)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:78)
	at org.schabi.newpipe.database.history.dao.StreamHistoryDAO_Impl$9.call(StreamHistoryDAO_Impl.java:665)
	at org.schabi.newpipe.database.history.dao.StreamHistoryDAO_Impl$9.call(StreamHistoryDAO_Impl.java:639)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:47)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.onNext(FlowableFlatMapMaybe.java:131)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:402)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:322)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.runEager(ExecutorScheduler.java:287)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:248)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

```
</details>
<hr>

### Affected Android/Custom ROM version

PixelExperience 12L

### Affected device model

Xiaomi Poco X3 Pro

### Additional information

I have no idea what causes this issue and it's hard to reliably reproduce. However it seems to have no effect.
I did merge two NewPipe database from a very old version because the two database is disjointed (i.e. used NewPipe installation 1 from January to March, then NewPipe installation 2 from September to December, which meant I need to merge two databases by hand using a SQL editor.)

**Comment by eclairevoyant** [comment]
Still present in version 4.7.5 and the stack trace is approximately the same.

It's actually very easy to reproduce. Simply close the app from the recent app screen, then open NewPipe again, and the first history entry that you delete will show an error. Subsequent deletions will not show an error until the app is restarted.

**Comment by aardbol** [comment]
Or when deleting somewhere lower in the list. Happens a lot with me.

Log:

```
## Exception
* __User Action:__ something else
* __Request:__ History Statistics
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ <unknown_service>
* __Timestamp:__ 2026-04-10T01:34:06.116+02:00
* __Package:__ org.schabi.newpipe
* __Service:__ <unknown_service>
* __Version:__ 0.28.4
* __OS:__ Linux Android 16 - 36
<details><summary><b>Crash log </b></summary><p>

java.lang.IllegalStateException: Couldn't read row 1214, col 13 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:574)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:78)
	at androidx.room.driver.SupportSQLiteStatement$SupportAndroidSQLiteStatement.getLong(r8-map-id-ce0307bac2c3f16e8dc2f832773b0599f307ee51c82b5550b73911d8a6d3ce37:11)
	at org.schabi.newpipe.database.history.dao.StreamHistoryDAO_Impl$$ExternalSyntheticLambda0.invoke(r8-map-id-ce0307bac2c3f16e8dc2f832773b0599f307ee51c82b5550b73911d8a6d3ce37:433)
	at androidx.room.util.DBUtil__DBUtil_androidKt$performSuspending$lambda$1$$inlined$internalPerform$1.invokeSuspend(r8-map-id-ce0307bac2c3f16e8dc2f832773b0599f307ee51c82b5550b73911d8a6d3ce37:216)
	at androidx.room.util.DBUtil__DBUtil_androidKt$performSuspending$lambda$1$$inlined$internalPerform$1.invoke(r8-map-id-ce0307bac2c3f16e8dc2f832773b0599f307ee51c82b5550b73911d8a6d3ce37:13)
	at androidx.room.driver.SupportSQLiteConnectionPool.useConnection(r8-map-id-ce0307bac2c3f16e8dc2f832773b0599f307ee51c82b5550b73911d8a6d3ce37:24)
	at androidx.room.RoomDatabase.useConnection$room_runtime_release(r8-map-id-ce0307bac2c3f16e8dc2f832773b0599f307ee51c82b5550b73911d8a6d3ce37:7)
	at androidx.room.util.DBUtil__DBUtil_androidKt$performSuspending$$inlined$compatCoroutineExecute$DBUtil__DBUtil_androidKt$1.invokeSuspend(r8-map-id-ce0307bac2c3f16e8dc2f832773b0599f307ee51c82b5550b73911d8a6d3ce37:41)
	at androidx.room.util.DBUtil__DBUtil_androidKt$performSuspending$$inlined$compatCoroutineExecute$DBUtil__DBUtil_androidKt$1.invoke(r8-map-id-ce0307bac2c3f16e8dc2f832773b0599f307ee51c82b5550b73911d8a6d3ce37:13)
	at kotlin.io.TextStreamsKt.startUndspatched(r8-map-id-ce0307bac2c3f16e8dc2f832773b0599f307ee51c82b5550b73911d8a6d3ce37:6)
	at kotlinx.coroutines.JobKt.withContext(Unknown Source:79)
	at androidx.room.util.DBUtil.performSuspending(Unknown Source:166)
	at androidx.room.coroutines.FlowUtil$createFlow$$inlined$map$1$2.emit(r8-map-id-ce0307bac2c3f16e8dc2f832773b0599f307ee51c82b5550b73911d8a6d3ce37:76)
	at kotlinx.coroutines.flow.FlowKt.emitAllImpl$FlowKt__ChannelsKt(Unknown Source:147)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(r8-map-id-ce0307bac2c3f16e8dc2f832773b0599f307ee51c82b5550b73911d8a6d3ce37:12)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(r8-map-id-ce0307bac2c3f16e8dc2f832773b0599f307ee51c82b5550b73911d8a6d3ce37:9)
	at kotlinx.coroutines.DispatchedTask.run(r8-map-id-ce0307bac2c3f16e8dc2f832773b0599f307ee51c82b5550b73911d8a6d3ce37:115)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1154)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:652)
	at java.lang.Thread.run(Thread.java:1563)

```
