### ISSUE TITLE
Pop-up player

### ISSUE THREAD

**Issue by sofsti96** [TeamNewPipe/NewPipe#8884]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.2

### Steps to reproduce the bug

1. Opened a video on YouTube
2. Pressed share
3. Selected newpipr
4. Selected pop-up player 
5.  An error report showed

### Expected behavior

Pop-up player will open and the video continue playing 

### Actual behavior

Show me an error report: sorry that should not have happened 

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.23.2
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/lang/model/SourceVersion;
	at org.mozilla.javascript.JavaMembers.<clinit>(JavaMembers.java:37)
	at org.mozilla.javascript.JavaMembers.lookupClass(JavaMembers.java:769)
	at org.mozilla.javascript.NativeJavaObject.initMembers(NativeJavaObject.java:63)
	at org.mozilla.javascript.NativeJavaObject.<init>(NativeJavaObject.java:53)
	at org.mozilla.javascript.NativeJavaObject.<init>(NativeJavaObject.java:44)
	at org.mozilla.javascript.WrapFactory.wrapAsJavaObject(WrapFactory.java:120)
	at org.mozilla.javascript.WrapFactory.wrap(WrapFactory.java:74)
	at org.mozilla.javascript.Context.javaToJS(Context.java:1720)
	at org.mozilla.javascript.Context.javaToJS(Context.java:1679)
	at org.mozilla.javascript.ScriptRuntime.newCatchScope(ScriptRuntime.java:4119)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:2091)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1053)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:90)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:380)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3868)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:88)
	at org.schabi.newpipe.extractor.utils.JavaScript.run(JavaScript.java:22)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeThrottlingDecrypter.decryptNParam(YoutubeThrottlingDecrypter.java:194)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeThrottlingDecrypter.apply(YoutubeThrottlingDecrypter.java:114)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.tryDecryptUrl(YoutubeStreamExtractor.java:617)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.buildAndAddItagInfoToList(YoutubeStreamExtractor.java:1395)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.lambda$getStreamsFromStreamingDataKey$13(YoutubeStreamExtractor.java:1360)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.$r8$lambda$uz6J0PYZPOMRHm9hVK1D3jkm5_Q(Unknown Source:0)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor$$ExternalSyntheticLambda6.apply(Unknown Source:10)
	at j$.util.stream.g2.accept(SourceFile:4)
	at j$.util.stream.g2.accept(SourceFile:4)
	at j$.util.stream.g2.accept(SourceFile:5)
	at j$.util.Iterator$-CC.$default$forEachRemaining(SourceFile:2)
	at j$.util.Iterator$-EL.forEachRemaining(Unknown Source:10)
	at j$.util.P.forEachRemaining(Unknown Source:24)
	at j$.util.stream.c.b0(SourceFile:4)
	at j$.util.stream.c.n0(SourceFile:2)
	at j$.util.stream.b0.e(Unknown Source:0)
	at j$.util.stream.c.q0(SourceFile:2)
	at j$.util.stream.m2.forEach(SourceFile:3)
	at j$.util.stream.g2.accept(SourceFile:7)
	at j$.util.I.forEachRemaining(Unknown Source:20)
	at j$.util.stream.c.b0(SourceFile:4)
	at j$.util.stream.c.n0(SourceFile:2)
	at j$.util.stream.b0.e(Unknown Source:0)
	at j$.util.stream.c.q0(SourceFile:2)
	at j$.util.stream.m2.forEachOrdered(SourceFile:3)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getItags(YoutubeStreamExtractor.java:1220)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.getAudioStreams(YoutubeStreamExtractor.java:586)
	at org.schabi.newpipe.extractor.stream.StreamInfo.extractStreams(StreamInfo.java:153)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:82)
	at org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:73)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getStreamInfo$3(ExtractorHelper.java:118)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$YTHJjScxCJNO1LTCqs3IKy35iyY(Unknown Source:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda6.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15868)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn.subscribeActual(SingleObserveOn.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4799)
	at org.schabi.newpipe.RouterActivity$FetcherService.handleChoice(RouterActivity.java:792)
	at org.schabi.newpipe.RouterActivity$FetcherService.onHandleIntent(RouterActivity.java:764)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.lang.ClassNotFoundException: javax.lang.model.SourceVersion
	... 75 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12

### Affected device model

Samsung Galaxy S10+

**Comment by trizen** [comment]
Isn't this issue fixed in 0.23.3?
