### ISSUE TITLE
Crashed when tapping-and-holding "PIP" button with video currently playing

### ISSUE THREAD

**Issue by MDP43140** [TeamNewPipe/NewPipe#8887]
### Checklist

- [x] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.3

### Steps to reproduce the bug

1. Open NewPipe.
2. Make a playlist and put a video on it.
3. Open any video, and play it.
4. Go to previously made playlist.
5. Hold "Popup", and toast "Added" appears.
6. Now go back to the video player UI, and rotate your phone (or just click the fullscreen button in bottom-right corner if device rotation is disabled).

### Expected behavior

Not crashing after rotating the phone.

### Actual behavior

Crashed after rotating the phone.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/68391650/187025750-06fb70ab-891e-4553-8d45-633f7c8011dc.mp4

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ ID
* __Content Language:__ id
* __App Language:__ in
* __Service:__ none
* __Version:__ 0.23.3
* __OS:__ Linux samsung/a6ltedx/a6lte:10/QP1A.190711.020/A600GDXU9CUB1:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.CONFIGURATION_CHANGED flg=0x70200010 } in org.schabi.newpipe.player.Player$4@e719fea
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1656)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: java.lang.NullPointerException: Attempt to read from field 'int android.view.ViewGroup$LayoutParams.width' on a null object reference
	at org.schabi.newpipe.player.Player.onBroadcastReceived(Player.java:1314)
	at org.schabi.newpipe.player.Player.-$$Nest$monBroadcastReceived(Unknown Source:0)
	at org.schabi.newpipe.player.Player$4.onReceive(Player.java:1228)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1646)
	... 8 more

```
</details>
<hr>

### Affected Android/Custom ROM version

One UI 2.0 (Android 10)

### Affected device model

Samsung A6

### Additional information

the bug can also be triggered by holding PIP button in the player UI,
And the playlist can be anything as long as it having a video in it

**Comment by AudricV** [comment]
Does it happen on version 0.24.0?

**Comment by MDP43140** [comment]
Looks like its fixed in latest version
