### ISSUE TITLE
Video playback crashes after pausing for a few hours

### ISSUE THREAD

**Issue by akinhet** [TeamNewPipe/NewPipe#8917]
### Checklist

- [x] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.3 (I've noticed the bug before, but I'm not sure in what versions exactly)

### Steps to reproduce the bug

1. Play a video
2. Pause it for about 8 hrs or more (hard to say exactly as most of the time it happend to me when I started the video before going to bed and unpaused it after waking up)
3. Unpause it
4. The video plays for a few seconds
5. The playback crashes
6. The only way to continue to watch the video is to close it and open it again (e.g. from history)

### Expected behavior

The video continues to play normally.

### Actual behavior

The video crashes after a few seconds of playback (after playing all of the buffer?), then after clicking the play button it loads indefinitely.

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_BAD_HTTP_STATUS] occurred while playing https://www.youtube.com/watch?v=opp0MKcNRko
* __Content Country:__ PL
* __Content Language:__ pl-PL
* __App Language:__ pl_PL
* __Service:__ YouTube
* __Version:__ 0.23.3
* __OS:__ Linux Redmi/camellian_eea/camellian:11/RP1A.200720.011/V12.5.4.0.RKSEUOR:user/release-keys 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:613)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:236)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:422)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:786)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:599)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:124)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 11 (MIUI 12.5.5)

### Affected device model

Xiaomi Redmi Note 10 5G

**Comment by akinhet** [comment]
If I had to guess the problem exists because the connection to the server times out and after exhausting the video buffer the player has nothing left to serve, so it tries to contact the server, but because of the timeout the server sends back HTTP 403.

I'm not sure though why the video does not load after the crash.
