### ISSUE TITLE
Some Channels Not Loading

### ISSUE THREAD

**Issue by jhorner6511** [TeamNewPipe/NewPipe#8920]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

23.3

### Steps to reproduce the bug

1. Select random SoundCloud channel
2. Some channels won't load properly.

### Expected behavior

Proper loading and playing of content.

### Actual behavior

Does not load video/content list.

### Screenshots/Screen recordings

![Screenshot_2022-09-01_20-22-59](https://user-images.githubusercontent.com/60300284/188034252-59d3b0a6-572c-4bf8-ae84-761d81fe0245.png)

## Exception
* __User Action:__ requested channel
* __Request:__ Start loading: https://soundcloud.com/h3_music1
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ SoundCloud
* __Version:__ 0.23.3
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ExtractionException: Could not get next page
	at org.schabi.newpipe.extractor.services.soundcloud.extractors.SoundcloudChannelExtractor.getInitialPage(SoundcloudChannelExtractor.java:124)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:21)
	at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:94)
	at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:55)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getChannelInfo$4(ExtractorHelper.java:126)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$BOLWstv98dC8pFAG_uir5gPXYwY(Unknown Source:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda3.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15868)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.io.IOException: Could not get streams from API, HTTP 500
	at org.schabi.newpipe.extractor.services.soundcloud.SoundcloudParsingHelper.getStreamsFromApi(SoundcloudParsingHelper.java:275)
	at org.schabi.newpipe.extractor.services.soundcloud.SoundcloudParsingHelper.getStreamsFromApi(SoundcloudParsingHelper.java:310)
	at org.schabi.newpipe.extractor.services.soundcloud.SoundcloudParsingHelper.getStreamsFromApiMinItems(SoundcloudParsingHelper.java:256)
	at org.schabi.newpipe.extractor.services.soundcloud.extractors.SoundcloudChannelExtractor.getInitialPage(SoundcloudChannelExtractor.java:119)
	... 30 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 10

### Affected device model

TCL Revvl 5G

**Comment by Manishpandey11** [comment]
Hello All ,I would like to work on this issue

**Comment by Manishpandey11** [comment]
can you add me on your slack channel

**Comment by AudricV** [comment]
There is no Slack channel, but an IRC one: you need to join it by yourself (look at the links at the bottom when trying to open a new issue on GitHub).

I am not sure if this issue can be fixed, as unless the 500 HTTP response code is returned instead of appropriate HTTP response codes, this is an issue from SoundCloud servers.

**Comment by opusforlife2** [comment]
> look at the links at the bottom when trying to open a new issue on GitHub

Or our ReadMe.

**Comment by Manishpandey11** [comment]
> 

who is working on that issue(that http issue)
can you please tell me.

**Comment by AudricV** [comment]
Nobody, except you.

**Comment by hubertm600** [comment]
same problem with me!

**Comment by Nico7as** [comment]
Hi, 

I've experienced the same issue, but with Youtube channels, on all of my 3 Android devices.

I'm running NewPipe 0.24 on LineageOS+microG 18.1 or 19.1

I noticed that Youtube recently had a cosmetic overhaul on the PC.
There might be underlying changes preventing NewPipe to properly fetch and display the videos within a channel?

**Comment by neurodiverseEsoteric** [comment]
It's not just soundcloud. No videos are showing for ALL of my channel subscriptions?

**Comment by RobertKillick** [comment]
With youtube I have not had an update for 3 days, no errors though

**Comment by hubertm600** [comment]
I found the problem fixed in version: release/0.24.1

Robert Killick ***@***.***> 於 2022年11月4日週五 下午10:20寫道：

**Comment by neurodiverseEsoteric** [comment]
What release 0.24.1?

**Comment by AudricV** [comment]
Like I said in https://github.com/TeamNewPipe/NewPipe/issues/8920#issuecomment-1279705804, this was an issue from SoundCloud and not from NewPipe or its extractor. I cannot reproduce it myself (the account loads and its tabs load without errors on NewPipe 0.26.1), therefore I am closing this issue.
