### ISSUE TITLE
App/UI crashed

### ISSUE THREAD

**Issue by Red-Luci4** [TeamNewPipe/NewPipe#8935]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.3

### Steps to reproduce the bug

1. Press on the three bar menu
2. Go to settings
3. Go to Content
4. Turn on "Show Age restricted Content"
5. Go back to the Home Page
6. Search for Age Restricted Content
7. Select an Age Restricted Video & Wait till it starts to load

### Expected behavior

It is expected to play the video like any other video.

### Actual behavior

The app abruptly closes.

### Screenshots/Screen recordings

[Bug Demonstration Video](https://mark.nl.tab.digital/s/RF5JgxBm86FsKxG)

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.23.3
* __OS:__ Linux Android 12 - 32
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to create service org.schabi.newpipe.player.MainPlayer: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setColorFilter(android.graphics.ColorFilter)' on a null object reference
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4567)
	at android.app.ActivityThread.access$1700(ActivityThread.java:256)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2110)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setColorFilter(android.graphics.ColorFilter)' on a null object reference
	at org.schabi.newpipe.player.Player.initViews(Player.java:487)
	at org.schabi.newpipe.player.Player.setupFromView(Player.java:470)
	at org.schabi.newpipe.player.MainPlayer.createView(MainPlayer.java:107)
	at org.schabi.newpipe.player.MainPlayer.onCreate(MainPlayer.java:100)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4554)
	... 9 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12 |  Corvus_vS3.2-Vindicate-Vanilla

### Affected device model

Redmi Note 5 Pro (whyred)

### Additional information

1. My phone is completely De-googled (I use micro-G and aurora store)
2. My phone is rooted using Magisk

**Comment by Nuwbertron** [comment]
Happened to me too. No rootkit.

Error:
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.23.3
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7297)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6416)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7519)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

```
</details>
<hr>

**Comment by WorkHard4470** [comment]
Bruh. I'm using the custom ROM via local install using recovery method. Also happened for NewPipe trying to click channels. This is same error.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ PH
* __Content Language:__ en-PH
* __App Language:__ en_PH
* __Service:__ none
* __Version:__ 0.23.3
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
io.reactivex.rxjava3.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.NullPointerException: it.name must not be null
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:718)
	at io.reactivex.rxjava3.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:715)
	at io.reactivex.rxjava3.internal.subscribers.LambdaSubscriber.onError(LambdaSubscriber.java:79)
	at io.reactivex.rxjava3.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:69)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:402)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8248)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)
Caused by: java.lang.NullPointerException: it.name must not be null
	at org.schabi.newpipe.settings.notifications.NotificationModeConfigAdapter.update(NotificationModeConfigAdapter.kt:55)
	at org.schabi.newpipe.settings.notifications.NotificationModeConfigFragment.onViewCreated$lambda-0(NotificationModeConfigFragment.kt:53)
	at org.schabi.newpipe.settings.notifications.NotificationModeConfigFragment.$r8$lambda$5-3HhZFEG6YoGIzMOl4lAsfp44o(Unknown Source:0)
	at org.schabi.newpipe.settings.notifications.NotificationModeConfigFragment$$ExternalSyntheticLambda0.accept(Unknown Source:4)
	at io.reactivex.rxjava3.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65)
	... 11 more

```
</details>
<hr>

**Comment by WorkHard4470** [comment]
This is same error. There is not using Magisk rootkit anymore. This is stock OS or custom stock UI or launcher and tried to load NewPipe channels in notifications. Nothing to do.

**Comment by Red-Luci4** [comment]
I currently updated my OS to Corvus_vS4.0-Leviathan_Venilla and the app now seems to work properly as expected.
