### ISSUE TITLE
Video crash when forwarding or restarting a stoped video

### ISSUE THREAD

**Issue by Benjamin-z** [TeamNewPipe/NewPipe#8941]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.3

### Steps to reproduce the bug

1. Go to a new video
2. Play the video
3. Forward in time
4. The player crash
5. Try to restart the video
6. The player crash

### Expected behavior

I should be able to forward in time or continue a non finished video.

### Actual behavior

Every time I try to move in the video or try to continue a video that is not finished, the player crash with an notification error.

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_DECODING_FAILED] occurred while playing https://www.youtube.com/watch?v=dQw4w9WgXcQ
* __Content Country:__ FR
* __Content Language:__ fr
* __App Language:__ fr
* __Service:__ YouTube
* __Version:__ 0.23.3
* __OS:__ Linux Android 12 - 32
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(136, null, null, video/avc, avc1.4D401F, 958062, null, [1280, 720, 25.0], [-1, -1]), format_supported=YES
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:575)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.qcom.video.decoder.avc
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1512)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:813)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:998)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:499)
	... 4 more
Caused by: android.media.MediaCodec$CodecException: Error 0x80001001

```
</details>
<hr>

### Affected Android/Custom ROM version

Pixel Experience 12.1 based android 12

### Affected device model

Xiaomi Redmi note 10 pro

### Additional information

The bug doesn't happened for audio playback.

**Comment by Benjamin-z** [comment]
Sorry. It seems it was a problem from Pixel Experience as an update to the latest version from 22/08/31 solved the issue
