### ISSUE TITLE
"Share to NewPipe" Error after getting video URL from notification

### ISSUE THREAD

**Issue by MDP43140** [TeamNewPipe/NewPipe#8967]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.3

### Steps to reproduce the bug

1. Make sure NewPipe is set as default for handling youtube.com link (in App Info > Set as default > Open supported URL > In this app).
2. Make sure NewPipe is closed (optionally force-stop if you prefer that way :)
3. Turn off your phone display (just press power once).
4. From other device, send a YouTube URL (In my case, i use KDE Connect "Share to" feature) (your phone might require to connect to internet/WiFi for this).
5. Wait until your phone is ringing a notification or vibrates (if any, else just wait couple seconds).
6. Now open up the phone.
7. Pull down notification.

### Expected behavior

I expect no error shown, especially because the notification isn't even clicked yet.

### Actual behavior

Instead a NewPipe error notification also shows up next to the actual link. Clicking the link won't open NewPipe or showing "Processing video" notification. (see screen recording below).

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/68391650/189919462-6244c57b-6d7d-4053-a257-fa01547ea85c.mp4

## Exception
* __User Action:__ share to newpipe
* __Request:__ Getting service from url: https://m.youtube.com/watch?v=jfKfPfyJRdk
* __Content Country:__ ID
* __Content Language:__ id
* __App Language:__ in
* __Service:__ none
* __Version:__ 0.23.3
* __OS:__ Linux samsung/a6ltedx/a6lte:10/QP1A.190711.020/A600GDXU9CUB1:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Not allowed to start service Intent { cmp=org.polymorphicshade.newpipe/org.schabi.newpipe.RouterActivity$FetcherService (has extras) }: app is in background uid UidRecord{93dfb5 u0a97 TPSL idle procs:1 proclist:1021, seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1688)
	at android.app.ContextImpl.startService(ContextImpl.java:1633)
	at android.content.ContextWrapper.startService(ContextWrapper.java:683)
	at android.content.ContextWrapper.startService(ContextWrapper.java:683)
	at org.schabi.newpipe.RouterActivity.handleChoice(RouterActivity.java:608)
	at org.schabi.newpipe.RouterActivity.onSuccess(RouterActivity.java:309)
	at org.schabi.newpipe.RouterActivity.lambda$handleUrl$1(RouterActivity.java:188)
	at org.schabi.newpipe.RouterActivity.$r8$lambda$pcnx7TUBUevDqo-278LYjZhc5RY(Unknown Source:0)
	at org.schabi.newpipe.RouterActivity$$ExternalSyntheticLambda16.accept(Unknown Source:6)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8167)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 10 (One UI 2.0 Custom ROM)

### Affected device model

Samsung A6

### Additional information
<h6>(this really annoys me especially because i like to watch random videos in newpipe instead of youtube web client to prevent yt algo from giving me clickbait stuff)</h6>

**Comment by lordphariz** [comment]
I have resolved the issues, actually is network probs.

**Comment by opusforlife2** [comment]
> Turn off your phone.

How are you even doing the rest of the steps if your phone is off?

**Comment by MDP43140** [comment]
> > Turn off your phone.
> 
> How are you even doing the rest of the steps if your phone is off?

I mean turn off the phone display not powering off the whole phone, sorry for that

**Comment by opusforlife2** [comment]
Does Newpipe successfully open if you tap a YT link from your device's browser?

**Comment by MDP43140** [comment]
> Does Newpipe successfully open if you tap a YT link from your device's browser? (Given that it is previously closed/force-stopped.)

It worked perfectly fine if i share it on my browser to newpipe, problem only occurs when i get the notifcation

https://user-images.githubusercontent.com/68391650/190942921-24d7ac7e-1cc4-4e7e-bd72-801939be2d50.mp4

###### (btw in the video i use np sb fork, but this also occurs on original newpipe)

**Comment by lordphariz** [comment]
Great to hear from you, your application is best I love it.

**Comment by opusforlife2** [comment]
Then it likely has something to do with app intents. Thanks for the info.
