### ISSUE TITLE
Share from NP to NP download not work 

### ISSUE THREAD

**Issue by leminsc8er** [TeamNewPipe/NewPipe#8980]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

Log

### Steps to reproduce the bug

Looking for workaround to download quickly from lists not work. Because of verry low Internet germany if mobile traffic is emty you have only kb/s...  You cant open videowindow. 
1. Go "Abo" > "All"
2. Press various Video in list with option Share
3. Share Video to NewPipe
4. NewPipe Download Popup come up
5. NewPipe frozen/crash

### Expected behavior

Fix it or stop sahrw i to Share with opopup Info. But it would be nice as Quick download as workaround of #*soon*. 

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ DE
* __Content Language:__ de-DE
* __App Language:__ de_DE
* __Service:__ none
* __Version:__ 0.23.3
* __OS:__ Linux samsung/xcover4seea/xcover4s:11/RP1A.200720.012/G398FNXXUGCVE6:user/release-keys 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1844)
	at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1884)
	at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:329)
	at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:294)
	at androidx.fragment.app.DialogFragment.show(DialogFragment.java:260)
	at org.schabi.newpipe.RouterActivity.lambda$openDownloadDialog$19(RouterActivity.java:682)
	at org.schabi.newpipe.RouterActivity.$r8$lambda$--0YcizsE0Kz2-_9bdoMW02jdkQ(Unknown Source:0)
	at org.schabi.newpipe.RouterActivity$$ExternalSyntheticLambda14.accept(Unknown Source:4)
	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8645)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```
</details>
<hr>

### Additional information

Very slow mobiledtata in germany if your gb-flat emty you have only kb/s for Internet.😤

**Comment by opusforlife2** [comment]
Try with 0.24.1?
