### ISSUE TITLE
Out of Memory when watching sterams

### ISSUE THREAD

**Issue by noskill24** [TeamNewPipe/NewPipe#8992]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.3

### Steps to reproduce the bug

Everytime when i watching stream on Android 4.4.2 I got Out of memory. Memory 1 GB. No other apps are active. In SkyTube I have no problem with the same content.

### Actual behavior

Everytime when i watching stream on Android 4.4.2 I got Out of memory. Memory 1 GB. No other apps are active. In SkyTube I have no problem with the same content.
## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_UNSPECIFIED] occurred while playing https://www.youtube.com/watch?v=IrCFOFsnPr8
* __Content Country:__ RU
* __Content Language:__ ru-RU
* __App Language:__ ru_RU
* __Service:__ YouTube
* __Version:__ 0.23.3
* __OS:__ Linux Android 4.4.2 - 19
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:617)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:149)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: com.google.android.exoplayer2.upstream.Loader$UnexpectedLoaderException: Unexpected OutOfMemoryError: null
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:441)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.OutOfMemoryError
	at com.google.android.exoplayer2.upstream.DefaultAllocator.allocate(DefaultAllocator.java:102)
	at com.google.android.exoplayer2.source.SampleDataQueue.preAppend(SampleDataQueue.java:233)
	at com.google.android.exoplayer2.source.SampleDataQueue.sampleData(SampleDataQueue.java:176)
	at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java:590)
	at com.google.android.exoplayer2.extractor.TrackOutput$-CC.$default$sampleData(TrackOutput.java:157)
	at com.google.android.exoplayer2.source.SampleQueue.sampleData(SampleQueue.java)
	at com.google.android.exoplayer2.source.chunk.BundledChunkExtractor$BindingTrackOutput.sampleData(BundledChunkExtractor.java:233)
	at com.google.android.exoplayer2.extractor.TrackOutput$-CC.$default$sampleData(TrackOutput.java:157)
	at com.google.android.exoplayer2.source.chunk.BundledChunkExtractor$BindingTrackOutput.sampleData(BundledChunkExtractor.java)
	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.readSample(FragmentedMp4Extractor.java:1436)
	at com.google.android.exoplayer2.extractor.mp4.FragmentedMp4Extractor.read(FragmentedMp4Extractor.java:342)
	at com.google.android.exoplayer2.source.chunk.BundledChunkExtractor.read(BundledChunkExtractor.java:153)
	at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:127)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	... 3 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 4.4.2

**Comment by opusforlife2** [comment]
Instead of opening a new issue, you could have updated #8365 with all this information.

**Comment by opusforlife2** [comment]
Right, so, Kitkat support has been dropped from Newpipe. The new version which will come out will not work on your device. So there is no point in opening new Kitkat issues.

The only suggestion I can give you is to watch videos at lower resolutions, like 480p or even 360p.

**Comment by noskill24** [comment]
Over 95% KitKat devices have screens with 720p. KitKat play all youtube formats on 720p very well. SkyTube have special settings for limit maximum resolution and I have no problem there. The problem is that Newpipe always ruining streams at higher resolution. Instead of fixing this issue and let for users limit maximum resolution for Kitkat you simply drop Kitkat support. Nice solution! I would not recommend Newpipe anymore. SkyTube - is now more better, and only one supported all devices where youtube is dropped!

**Comment by tsiflimagas** [comment]
There were many good reasons to drop support for KitKat, and tbh I don't even remember this issue being one of them. At least try to get informed (you could have searched for the related PR and issue) instead of being bitter.

**Comment by opusforlife2** [comment]
> Nice solution! I would not recommend Newpipe anymore. SkyTube - is now more better, and only one supported all devices where youtube is dropped!

Awesome! Your gratefulness about using this _free app_ made by developers' _unpaid voluntary contributions_ in their _own time_ is just shining through.
