### ISSUE TITLE
Newpipe keeps stooping in my new custom rom

### ISSUE THREAD

**Issue by breaking-loss** [TeamNewPipe/NewPipe#8994]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.3

### Steps to reproduce the bug

1. Open newpipe
2. Open a video

### Expected behavior

The video should be loaded

### Actual behavior

The video doesn't load but the comment loads .It closes the app immediately also

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.23.3
* __OS:__ Linux Android 12 - 32
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to create service org.schabi.newpipe.player.MainPlayer: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setColorFilter(android.graphics.ColorFilter)' on a null object reference
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4567)
	at android.app.ActivityThread.access$1700(ActivityThread.java:256)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2110)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:550)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.drawable.Drawable.setColorFilter(android.graphics.ColorFilter)' on a null object reference
	at org.schabi.newpipe.player.Player.initViews(Player.java:487)
	at org.schabi.newpipe.player.Player.setupFromView(Player.java:470)
	at org.schabi.newpipe.player.MainPlayer.createView(MainPlayer.java:107)
	at org.schabi.newpipe.player.MainPlayer.onCreate(MainPlayer.java:100)
	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4554)
	... 9 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Corvus OS S3.2

### Affected device model

Redmi 6 pro

**Comment by MDP43140** [comment]
i think `void android.graphics.drawable.Drawable.setColorFilter(android.graphics.ColorFilter)` in the error log suggests that the custom rom you're using might having a problem related to video/graphics...

**Comment by breaking-loss** [comment]
I didn't format the device .Is it because of that .All other Roms didn't have a problem at all .

**Comment by opusforlife2** [comment]
You know what you have to do to confirm or reject your theory.

**Comment by breaking-loss** [comment]
Wish me luck
