### ISSUE TITLE
No videos are loading anymore

### ISSUE THREAD

**Issue by TAXSET** [TeamNewPipe/NewPipe#9004]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.3

### Steps to reproduce the bug

1. Open any video.

### Expected behavior

Video should start to play after few seconds.

### Actual behavior

Long buffer followed by error in snack bar.

### Affected Android/Custom ROM version

12

### Affected device model

OnePlus Note 2

**Comment by xz-dev** [comment]
I sure I can play normally

**Comment by jakubkovac** [comment]
Same for me on Android 11

**Comment by privacyonly** [comment]
does it load empty 0:02 video?

**Comment by opusforlife2** [comment]
> followed by error in snack bar.

Then please provide the formatted error.

**Comment by Symbian9** [comment]
> Then please provide the formatted error.

Here it is:

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_NETWORK_CONNECTION_TIMEOUT] occurred while playing https://www.youtube.com/watch?v=vw_WxslG_A4
* __Content Country:__ US
* __Content Language:__ en
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.23.3
* __OS:__ Linux Android 6.0.1 - 23
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:641)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:613)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketTimeoutException: failed to connect to rr2---sn-8ph2xajvh-n8vs.googlevideo.com/85.249.244.45 (port 443) after 8000ms
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:389)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:786)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:599)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.chunk.InitializationChunk.load(InitializationChunk.java:99)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.net.SocketTimeoutException: failed to connect to rr2---sn-8ph2xajvh-n8vs.googlevideo.com/85.249.244.45 (port 443) after 8000ms
	at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
	at libcore.io.IoBridge.connect(IoBridge.java:122)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
	at java.net.Socket.connect(Socket.java:884)
	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:117)
	at com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:438)
	at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:178)
	at com.android.okhttp.Connection.connect(Connection.java:1324)
	at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:1412)
	at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:131)
	at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:481)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:462)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:368)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:476)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:418)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:540)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:385)
	... 10 more

```
</details>
<hr>

**Comment by opusforlife2** [comment]
@Symbian9 This is not the sort of error that would show you a snackbar.

**Comment by Symbian9** [comment]
> This is not the sort of error that would show you a snackbar.

@opusforlife2, Is there other related issue to my case reported already?

**Comment by opusforlife2** [comment]
Yep. You can search using your error string to find it easily.
