### ISSUE TITLE
Content unavailable error

### ISSUE THREAD

**Issue by WorkHard4470** [TeamNewPipe/NewPipe#9008]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.3

### Steps to reproduce the bug

1. Go to https://www.youtube.com/channel/UCE2606prvXQc_noEqKxVJXA
2. Wait until loads and content does not load. Looks like it's probably terminated or hacked.

### Expected behavior

Channels with videos are still loaded perfectly.

### Actual behavior

This time this channel called that I'n trying to watch weather-related videos are unavailable—possible termination or hacking. Then there was a error reported by NewPipe.

### Screenshots/Screen recordings

<img alt="Screenshot_2022-09-22-19-43-02-94_ee8807d2de22f1831269d80920e33a3b" src="https://user-images.githubusercontent.com/111160004/191737789-ad0d0daa-1b67-4410-b214-fedae75485dd.jpg" height=600 />

## Exception
* __User Action:__ requested channel
* __Request:__ Start loading: https://www.youtube.com/channel/UCE2606prvXQc_noEqKxVJXA
* __Content Country:__ PH
* __Content Language:__ en-PH
* __App Language:__ en_PH
* __Service:__ YouTube
* __Version:__ 0.23.3
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ContentNotAvailableException: Got error:"INTERNAL": INTERNAL: Request '/VideoFeedsService.GetBrowse' from role 'video-youtube-channels-frontend-page' throttled: Service is overloaded (too-many-retries) go/tr-o.; /VideoFeedsService.GetBrowse RPC failed
=== Source Location Trace: === 
net/rpc/rpc-status.cc:531
video/youtube/discovery/engine/util/make_rpc.h:276

	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeChannelExtractor.onFetchPage(YoutubeChannelExtractor.java:162)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)
	at org.schabi.newpipe.extractor.channel.ChannelInfo.getInfo(ChannelInfo.java:54)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getChannelInfo$4(ExtractorHelper.java:126)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$BOLWstv98dC8pFAG_uir5gPXYwY(Unknown Source:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda3.call(Unknown Source:4)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15868)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12 [Global India ROM, realme UI 3.0]

### Affected device model

realme 8 4G

**Comment by WorkHard4470** [comment]
How do I change labels on my issue?

**Comment by WorkHard4470** [comment]
It appears this is not a bug.

**Comment by WorkHard4470** [comment]
@opusforlife2 we need to add YouTube label and remove Needs Triage.

**Comment by WorkHard4470** [comment]
#8890 should be fixed for their error. This is not a bug.

**Comment by WorkHard4470** [comment]
`is:open remove label:bug`

**Comment by AudricV** [comment]
It seems that your error was an internal YouTube issue, as the channel works fine for me.

Please do not ping specific team members to triage  issues, this will be done by ourselves when we have time to browse the issue tracker.

Labels can be only changed by repository collaborators.

**Comment by ashoklathwal** [comment]
https://wealthquint.com/fix-newpipe-content-unavailable-63068/
