### ISSUE TITLE
Unexpected Player Error

### ISSUE THREAD

**Issue by Harlequin82** [TeamNewPipe/NewPipe#9016]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

23.3

### Steps to reproduce the bug

1. Play any YouTube video.
2. Enter Full Screen.
3. After playing for a bit, double tap to go forward or backwards in the video.
4. Infinite buffering starts.
5. Exiting fullscreen takes a bit longer.
6. A notification shows up: Recovering from Player error.

### Expected behavior

Video should Play and no player error should show up.

### Actual behavior

The recovering from player error shows up, after that no videos can be played until the app is cleared from RAM and opened again. 
This error also seems to happen in only in Fullscreen mode. And it happens only when the video is navigated using the double tapping method, using the video progress bar to go forward and backwards works fine.

### Screenshots/Screen recordings

Here is a screen recording. 

https://user-images.githubusercontent.com/114285003/192091615-8b0d979a-473e-46c0-bedc-39cfcf31d62d.mp4

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_TIMEOUT] occurred while playing https://www.youtube.com/watch?v=uBEL3YVzMwk
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.23.3
* __OS:__ Linux Android 12 - 32
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
	at com.google.android.exoplayer2.ExoPlayerImpl.setVideoOutputInternal(ExoPlayerImpl.java:2489)
	at com.google.android.exoplayer2.ExoPlayerImpl.setVideoSurface(ExoPlayerImpl.java:1246)
	at org.schabi.newpipe.player.playback.SurfaceHolderCallback.surfaceDestroyed(SurfaceHolderCallback.java:53)
	at android.view.SurfaceView.notifySurfaceDestroyed(SurfaceView.java:1981)
	at android.view.SurfaceView.updateSurface(SurfaceView.java:1157)
	at android.view.SurfaceView.setWindowStopped(SurfaceView.java:299)
	at android.view.SurfaceView.surfaceDestroyed(SurfaceView.java:1832)
	at android.view.ViewRootImpl.notifySurfaceDestroyed(ViewRootImpl.java:1986)
	at android.view.ViewRootImpl.setWindowStopped(ViewRootImpl.java:1943)
	at android.view.WindowManagerGlobal.setStoppedState(WindowManagerGlobal.java:662)
	at android.app.Activity.performStop(Activity.java:8281)
	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5215)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5784)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5703)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: com.google.android.exoplayer2.ExoTimeoutException: Detaching surface timed out.
	at com.google.android.exoplayer2.ExoPlayerImpl.setVideoOutputInternal(ExoPlayerImpl.java:2487)
	... 25 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12 / LineageOS 19.1

### Affected device model

Xiaomi Redmi Note 9 [Merlin]

**Comment by Stypox** [comment]
Could you check if this is still reproducible in 0.24.0?

**Comment by Harlequin82** [comment]
> Could you check if this is still reproducible in 0.24.0?

I'm going to fresh install the 24.0 build today and then I'll update here weather the issue is reproducible or not.
