### ISSUE TITLE
Floating window error

### ISSUE THREAD

**Issue by NSTAdventure** [TeamNewPipe/NewPipe#9019]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.23.3

### Steps to reproduce the bug

1. Open newpipe and any video
2. Then try to move the video player few time
3. App crash

### Expected behavior

It shouldn't crash

### Actual behavior

Crashed 

### Logs

-------------------------------------
java.lang.NullPointerException: Attempt to read from field 'com.google.android.material.floatingactionbutton.FloatingActionButton org.schabi.newpipe.databinding.PlayerPopupCloseOverlayBinding.closeButton' on a null object reference
	at org.schabi.newpipe.player.Player.getCloseOverlayButton(Player.java:4651)
	at org.schabi.newpipe.player.event.BasePlayerGestureListener.onScrollInPopup(BasePlayerGestureListener.kt:369)
	at org.schabi.newpipe.player.event.BasePlayerGestureListener.onScroll(BasePlayerGestureListener.kt:285)
	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:686)
	at org.schabi.newpipe.player.event.BasePlayerGestureListener.onTouchInPopup(BasePlayerGestureListener.kt:108)
	at org.schabi.newpipe.player.event.BasePlayerGestureListener.onTouch(BasePlayerGestureListener.kt:82)
	at android.view.View.dispatchTouchEvent(View.java:14134)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3076)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2756)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3082)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2770)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3082)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2770)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3082)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2770)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3082)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2770)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3082)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2770)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3082)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2770)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3082)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2770)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3082)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2770)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3082)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2770)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3082)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2770)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3082)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2770)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3082)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2770)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3082)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2770)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3082)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2770)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:519)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1857)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4121)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:469)
	at android.view.View.dispatchPointerEvent(View.java:14397)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6235)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5984)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5435)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5495)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5454)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5619)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5462)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5676)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5435)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5495)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5454)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5462)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5435)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8309)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8278)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8239)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8434)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:189)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:179)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8385)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:8458)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1090)
	at android.view.Choreographer.doCallbacks(Choreographer.java:913)
	at android.view.Choreographer.doFrame(Choreographer.java:833)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1075)
	at android.os.Handler.handleCallback(Handler.java:899)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:238)
	at android.app.ActivityThread.main(ActivityThread.java:7853)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)

### Affected Android/Custom ROM version

Android 10 Realme UI 1.0

### Affected device model

Realme 5i RMX 2030

### Additional information

1. No i don't have a cat
2. This bug is horsemen of annoyance (bruh)

**Comment by AudricV** [comment]
Is it reproducible with 0.24.0 release candidate?

**Comment by NSTAdventure** [comment]
> Is it reproducible with 0.24.0 release candidate?

I not test yet wait for a moment

**Comment by Stypox** [comment]
Please test now. This should be gone.

**Comment by NSTAdventure** [comment]
> Please test now. This should be gone.

Yes bug is no longer exist on rc release 
Thanks 🙏
