### ISSUE TITLE
the application does not open after importing a backup from animepipe

### ISSUE THREAD

**Issue by Wjxfi** [TeamNewPipe/NewPipe#9029]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [x] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Steps to reproduce the bug

Create a backup from animepipe. paste it into this application

### Expected behavior

Synchronization with backup

### Actual behavior

The application won't open. There is always an error

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Service:__ none
* __Version:__ 0.24.0
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: A migration from 6 to 5 was required but not found. Please provide the necessary Migration path via RoomDatabase.Builder.addMigration(Migration ...) or allow for destructive migrations via one of the RoomDatabase.Builder.fallbackToDestructiveMigration* methods.
	at androidx.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.java:117)
	at androidx.room.RoomOpenHelper.onDowngrade(RoomOpenHelper.java:129)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onDowngrade(FrameworkSQLiteOpenHelper.java:194)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:414)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:151)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:112)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:706)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:483)
	at androidx.room.RoomDatabase.query(RoomDatabase.java:526)
	at androidx.room.util.DBUtil.query(DBUtil.java:86)
	at org.schabi.newpipe.database.playlist.dao.PlaylistRemoteDAO_Impl$6.call(PlaylistRemoteDAO_Impl.java:262)
	at org.schabi.newpipe.database.playlist.dao.PlaylistRemoteDAO_Impl$6.call(PlaylistRemoteDAO_Impl.java:259)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:47)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFlatMapMaybe$FlatMapMaybeSubscriber.onNext(FlowableFlatMapMaybe.java:131)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:402)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:322)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.runEager(ExecutorScheduler.java:287)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:248)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```
</details>
<hr>

### Affected device model

poco x3 pro

**Comment by n-buna404** [comment]
Isn't it unreasonable to assume a backup from a fork will work in newpipe if there is no agreement between dev to maintain cross-comparability?

**Comment by opusforlife2** [comment]
This issue belongs in the fork repo, not here.

**Comment by opusforlife2** [comment]
There is nothing wrong with our app because it is the _upstream_ version. If you create a backup from a fork (which is _downstream_) and it doesn't work with the upstream version, it is the fork that has to change.

Meanwhile, you can clear app data to delete the likely corrupted database caused by the import.
