### ISSUE TITLE
OS not responding error followed by UI crash 

### ISSUE THREAD

**Issue by Jaymn** [TeamNewPipe/NewPipe#9030]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

I have not seen a pattern to this issue consistently.  Best way to try and replicate it is through combination of switching between full screen and not, changing playback speeds (1.0 to 1.75 at .25 intervals), and changing between videos. After a bit, an OS level pop-up shows up showing that the application is not responding, even though it still is.

When I close the playing video afterwards, the app crashes (log has been attached).

I will keep trying to see if I can figure out a pattern and update this ticket accordingly. I'm sorry this does not follow the proper guidelines.

### Logs
```
{"user_action":"ui error",
"request":"ACRA report",
"content_language":"en-CA",
"content_country":"CA",
"app_language":"en_CA",
"service":"none",
"package":"org.schabi.newpipe",
"version":"0.24.0",
"os":"Linux Android 13 - 33",
"time":"2022-09-26 19:02",
"Exceptions":
["android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{515ea4f u0 org.schabi.newpipe/.player.PlayerService}
at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2006)
at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1977)
at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2242)
at android.os.Handler.dispatchMessage(Handler.java:106)\n\tat android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7898)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1915)
at android.app.ContextImpl.startForegroundService(ContextImpl.java:1870)
at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822)
at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822)
at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:931)
at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:703)
at org.schabi.newpipe.fragments.detail.VideoDetailFragment.openMainPlayer(VideoDetailFragment.java:1235)
at org.schabi.newpipe.fragments.detail.VideoDetailFragment.$r8$lambda$7cA0nfOW4EXxLpA03fs92UQohwM(Unknown Source:0)
at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda16.run(Unknown Source:2)
at org.schabi.newpipe.fragments.detail.VideoDetailFragment.replaceQueueIfUserConfirms(VideoDetailFragment.java:2150)
at org.schabi.newpipe.fragments.detail.VideoDetailFragment.openVideoPlayer(VideoDetailFragment.java:1190)
at org.schabi.newpipe.fragments.detail.VideoDetailFragment.openVideoPlayerAutoFullscreen(VideoDetailFragment.java:1203)
at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$runWorker$9(VideoDetailFragment.java:942)
at org.schabi.newpipe.fragments.detail.VideoDetailFragment.$r8$lambda$U48iIKXy1FeNEKzrs0mKI60q5_s(Unknown Source:0)
at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda12.accept(Unknown Source:8)
at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
... 6 more
```
### Affected Android/Custom ROM version

Android version 13

### Affected device model

Pixel 4a

**Comment by OfficialDyray** [comment]
I am experiencing a similar issue. 
Device: Pixel 4a with GrapheneOS

It will be actively playing video when the not responding message pops up. If I click wait, it will pop back up in a few seconds.

**Comment by itsme24082004** [comment]
Same issue on redmi

**Comment by opusforlife2** [comment]
Try on 0.24.1?

**Comment by Jaymn** [comment]
@opusforlife2  unfortunately yes. I tried it out for a day or two, but the issue still persisted. Ended up going back to version 0.23.3 for the time being.

**Comment by pmontgo33** [comment]
Same issue on Pixel 6 running Android 13

**Comment by Jaymn** [comment]
@Coderdude112 that sounds about right. Although for me, I've noticed that it happens after completing the first video, and starting the second one. About a minute in the error message pops up. I tried doing the steps you mentioned above, but nadda yet.
