### ISSUE TITLE
Frequently app refuses to playback videos and soundcloud audio

### ISSUE THREAD

**Issue by OfficialMuffin** [TeamNewPipe/NewPipe#9033]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. On latest version, try playing any video or soundcloud audio
2. App should return error and refuse to play

### Expected behavior

Videos and soundcloud audio play without issues.

### Actual behavior

App returns error and refuses to play any video and soundcloud audio

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_PARSING_CONTAINER_MALFORMED] occurred while playing https://soundcloud.com/bluemuffincreations/dangerous-encounter
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ SoundCloud
* __Version:__ 0.24.0
* __OS:__ Linux samsung/c1seea/c1s:12/SP1A.210812.016/N980FXXU4FVGA:user/release-keys 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:632)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:602)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.ParserException: Cannot find sync byte. Most likely not a Transport Stream.
	at com.google.android.exoplayer2.extractor.ts.TsExtractor.findEndOfFirstTsPacketInBuffer(TsExtractor.java:460)
	at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:327)
	at com.google.android.exoplayer2.source.hls.BundledHlsMediaChunkExtractor.read(BundledHlsMediaChunkExtractor.java:67)
	at com.google.android.exoplayer2.source.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:473)
	at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:437)
	at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:394)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12

### Affected device model

Samsung Galaxy Note20

**Comment by AudricV** [comment]
Did you try to clear the application cache? This may be an issue coming from the cache data unsupported or incomplete for the new ExoPlayer version shipped with 0.24.0 (version 2.18.1 vs version 2.17.1 on the 0.23.3 version of the app).

**Comment by OfficialMuffin** [comment]
Thanks, I'll try it and report any findings after

**Comment by OfficialMuffin** [comment]
Opened the app and tried again. Seems to be working normally now. I'll reopen this issue if the error comes back. Closing
