### ISSUE TITLE
Crash when touching on (some) comment

### ISSUE THREAD

**Issue by devlearner** [TeamNewPipe/NewPipe#9052]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. Load a video
2. Switch to Comments tab
3. Touch / long press the text of some comment

### Expected behavior

Comment text copied to clipboard

### Actual behavior

Crashes with a cast exception `android.text.SpannedString cannot be cast to android.text.Spannable` in `CommentTextOnTouchListener`

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.24.0
* __OS:__ Linux Android 8.0.0 - 26
<details><summary><b>Crash log </b></summary><p>

```
java.lang.ClassCastException: android.text.SpannedString cannot be cast to android.text.Spannable
	at org.schabi.newpipe.util.CommentTextOnTouchListener.onTouch(CommentTextOnTouchListener.java:29)
	at android.view.View.dispatchTouchEvent(View.java:12536)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2786)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2786)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2786)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2786)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2786)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2786)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2786)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2786)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2786)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2786)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2786)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2786)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2786)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3159)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2786)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:601)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3384)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:563)
	at android.view.View.dispatchPointerEvent(View.java:12788)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5675)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5470)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4963)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5016)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4982)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5119)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4990)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5176)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4963)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5016)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4982)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4990)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4963)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7742)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7682)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7643)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7853)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:197)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:325)
	at android.os.Looper.loop(Looper.java:142)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 8.0

### Affected device model

Samsung Galaxy C9 Pro

### Additional information

Can't pinpoint the exact comment texts that trigger the exception.  But higher chances it will throw for comments with emojis.  Possibly related to the fact that the text I pressed on contain newer Unicode standard emojis (like 🥰) beyond that the native Android supports (Android 8.0 in my case).

**Comment by janTaja** [comment]
I have the same problem, also on an Android 8 Galaxy phone (mine is a3 2017). An example crashing comment is the pinned one in this video: https://www.youtube.com/watch?v=_Nm6OWFleis

**Comment by Marcos6226** [comment]
Can confirm. Mine's happens on almost all videos with a considerable sum of comments. But there is a specific video that it happens all the time. [Link to the video](https://www.youtube.com/watch?v=oCWhytwQ1As) 

Here is the log:
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ CA
* __Content Language:__ en
* __App Language:__ pt_BR
* __Service:__ none
* __Version:__ 0.24.0
* __OS:__ Linux Android 5.1.1 - 22
<details><summary><b>Crash log </b></summary><p>

```
java.lang.ClassCastException: android.text.SpannedString cannot be cast to android.text.Spannable
	at org.schabi.newpipe.util.CommentTextOnTouchListener.onTouch(CommentTextOnTouchListener.java:29)
	at android.view.View.dispatchTouchEvent(View.java:9181)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2308)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2308)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2308)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2308)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2308)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2308)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2308)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2308)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2308)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2308)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2308)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2308)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2308)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2308)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2743)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1836)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3043)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2704)
	at android.view.View.dispatchPointerEvent(View.java:9397)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5082)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4899)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4356)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4409)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4375)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4501)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4383)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4558)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4356)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4409)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4375)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4383)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4356)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6979)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6852)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6823)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7069)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:143)
	at android.os.Looper.loop(Looper.java:130)
	at android.app.ActivityThread.main(ActivityThread.java:7007)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

```
</details>
<hr>

**Comment by tsiflimagas** [comment]
For anyone experiencing this issue, try out the debug build from https://github.com/TeamNewPipe/NewPipe/pull/9065.

**Comment by TobiGr** [comment]
I am unable to reproduce the original issue in the emulator. @devlearner @janTaja  does #9065 fix the crash ?

**Comment by janTaja** [comment]
@TobiGr it does for me (at least i haven't had any crashes scrolling through comments, and that used to happen a lot with the release version)

**Comment by devlearner** [comment]
yep, now I feel the peace of mind not having to watch out where my finger lies when scrolling through the comments ;-)
