### ISSUE TITLE
Pressing 'pause' button on headphones while no video is currently playing will crash NewPipe

### ISSUE THREAD

**Issue by spitemim** [TeamNewPipe/NewPipe#9095]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. Connect any kind of headphones, that have a physical 'pause' button, to the device
2. Ensure that no video is currently playing
3. Press the 'pause' button on the connected headphones
4. Wait for a few seconds

### Expected behavior

The pause button on your headphones should not have any effect on the app when there is no video playing.

### Actual behavior

After a few seconds, the app crashes. This happens regardless of whether the user interacts with the application before or after the button is pressed. The application functions normally in the period of time between pressing the button and the app crashing. I've tested this with bluetooth and wired headphones. I've also tested this when opening the app after a force stop, or after watching a video and then closing it. The bug persists in all cases.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/69088069/194779104-0af3296d-b64d-4403-a6e1-ada3c5af3777.mp4

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.24.0
* __OS:__ Linux Android 12 - 32
<details><summary><b>Crash log </b></summary><p>

```
android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{69897de u0 org.schabi.newpipe/.player.PlayerService}
	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:1966)
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1937)
	at android.app.ActivityThread.access$2700(ActivityThread.java:257)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2191)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7876)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:48)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1898)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1853)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:781)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:781)
	at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:931)
	at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:703)
	at androidx.media.session.MediaButtonReceiver.onReceive(MediaButtonReceiver.java:115)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4376)
	at android.app.ActivityThread.access$1600(ActivityThread.java:257)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2103)
	... 9 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12 / GrapheneOS (build number SP2A.220505.008.2022090700)

### Affected device model

Pixel 3a XL

**Comment by opusforlife2** [comment]
It used to just cause a blank Newpipe notification to appear because it is the last used media app. Since 0.24.0 it causes a crash instead.

**Comment by DominikNovosel** [comment]
Any idea when will this be fixed? Or, I guess more importantly, how?

**Comment by opusforlife2** [comment]
Nope, I'm not a dev.

**Comment by SentientCoffee** [comment]
Getting the same error on version 0.25.0, especially annoying when my car tries to autoplay any media and NewPipe crashes.
***
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ CA
* __Content Language:__ en-CA
* __App Language:__ en_CA
* __Service:__ none
* __Version:__ 0.25.0
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{d37f1f6 u0 org.schabi.newpipe/.player.PlayerService}
	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2006)
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1977)
	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2242)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7879)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1936)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1891)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822)
	at androidx.core.content.ContextCompat$Api26Impl$$ExternalSyntheticApiModelOutline0.m(R8$$SyntheticClass:0)
	at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:931)
	at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:703)
	at androidx.media.session.MediaButtonReceiver.onReceive(MediaButtonReceiver.java:115)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4307)
	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2154)
	... 9 more

```
</details>
<hr>
