### ISSUE TITLE
App crashes when scrolling playlist screen after watching video in fullscreen

### ISSUE THREAD

**Issue by AlertSubject** [TeamNewPipe/NewPipe#9107]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. Open a playlist (I added a tab for all my playlist in the main page)
2. scroll down until the title bar of playlist is no longer visible
3. Watch video in landscape mode
4. exit landscape mode watching
5. minimize player
6. There will now be a slightly transparent banner in the top of the playlist screen. (See Screenshot)
7. Scroll up the playlist
8. newpipe crashes

Note that this only seems to happen when the video was played in full screen landscape mode
The issue does not occur when the playlists name + the play all buttons etc are still visible
The crash can be prevented by exiting the playlist instead of scrolling (Transparent title bar no longer present upon entering playlist again)
Same applies for entering the channel details page and then backing out into the playlist again 
(Seems like every change in what screen is displayed removes the transparent banner)

### Expected behavior

The playlist view should scroll up

### Actual behavior

app crashes 

### Screenshots/Screen recordings

![IMG_20221011_133243](https://user-images.githubusercontent.com/72819077/195079271-b53bc630-81a8-4f36-a053-251898ead674.jpg)

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ DE
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.24.0
* __OS:__ Linux OnePlus/OnePlus9Pro_EEA/OnePlus9Pro:12/RKQ1.211119.001/R.GDPR.202205311640:user/release-keys 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: ViewHolder views must not be attached when created. Ensure that you are not passing 'true' to the attachToRoot parameter of LayoutInflater.inflate(..., boolean attachToRoot)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7297)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6416)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12 + OxygenOS12

### Affected device model

OnePlus 9 Pro

### Additional information

Animation speed is set to .5

**Comment by AlertSubject** [comment]
Hi, could you please link the original issue as I wasn't able to find it when searching for "crash + Playlist"?
Thanks

**Comment by tsiflimagas** [comment]
#4475
