### ISSUE TITLE
Switching thumbnail setting crash

### ISSUE THREAD

**Issue by NSTAdventure** [TeamNewPipe/NewPipe#9110]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. Open newpipe go to setting content
2. Try to switch (toggle) the show thumbnail setting
3. App crash even setting work

### Expected behavior

No crash 

### Actual behavior

Crash

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ ID
* __Content Language:__ id
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.24.0
* __OS:__ Linux realme/RMX2030/RMX2030:10/QKQ1.200209.002/1605146661:user/release-keys 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Picasso instance already shut down. Cannot submit new requests.
	at com.squareup.picasso.RequestCreator.<init>(RequestCreator.java:76)
	at com.squareup.picasso.Picasso.load(Picasso.java:309)
	at com.squareup.picasso.Picasso.load(Picasso.java:334)
	at org.schabi.newpipe.util.PicassoHelper.loadImageDefault(PicassoHelper.java:193)
	at org.schabi.newpipe.util.PicassoHelper.loadImageDefault(PicassoHelper.java:181)
	at org.schabi.newpipe.util.PicassoHelper.loadAvatar(PicassoHelper.java:99)
	at org.schabi.newpipe.local.subscription.item.ChannelItem.bind(ChannelItem.kt:42)
	at com.xwray.groupie.Item.bind(Item.java:63)
	at com.xwray.groupie.Item.bind(Item.java:49)
	at com.xwray.groupie.GroupAdapter.onBindViewHolder(GroupAdapter.java:233)
	at com.xwray.groupie.GroupAdapter.onBindViewHolder(GroupAdapter.java:20)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7337)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6194)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6460)
	at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
	at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
	at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
	at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
	at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
	at android.os.Handler.handleCallback(Handler.java:899)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:238)
	at android.app.ActivityThread.main(ActivityThread.java:7853)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:984)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 10 Realme UI 1.0

### Affected device model

RMX 2030

### Additional information

1. I don't have cats.
2. Happen on both official and fork

**Comment by ShareASmile** [comment]
Closing as not reproducible, we have moved our app's image loading library from Picasso to Coil in #13272.
