### ISSUE TITLE
Full-screen crash on some videos

### ISSUE THREAD

**Issue by digr8wanka** [TeamNewPipe/NewPipe#9112]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. Go to [https://www.youtube.com/watch?v=OuY5arXWpks](https://www.youtube.com/watch?v=OuY5arXWpks)
2. Rotate phone or switch to full-screen
3. Watch the video crash and smash your phone (Not a very smart thing to do and I won't be responsible for any damage you cause by doing so)

### Expected behavior

I expected to be able to enjoy the video in full-screen.

### Actual behavior

The app crashed when switching to full-screen. Portrait mode works fine, but because the video isn't full-screen I can't see sh*t.

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_DECODING_FAILED] occurred while playing https://www.youtube.com/watch?v=OuY5arXWpks
* __Content Country:__ US
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ YouTube
* __Version:__ 0.24.0
* __OS:__ Linux Android 7.0 - 24
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(299, null, null, video/avc, avc1.64002A, 5339123, null, [1920, 1080, 60.0], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:566)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:156)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: OMX.IMG.MSVDX.Decoder.AVC
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1590)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:813)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
	... 3 more
Caused by: java.lang.IllegalStateException
	at android.media.MediaCodec.releaseOutputBuffer(Native Method)
	at android.media.MediaCodec.releaseOutputBuffer(MediaCodec.java:2701)
	at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.releaseOutputBuffer(SynchronousMediaCodecAdapter.java:161)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.renderOutputBufferV21(MediaCodecVideoRenderer.java:1325)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.processOutputBuffer(MediaCodecVideoRenderer.java:1090)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1894)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:792)
	... 5 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 7.0

### Affected device model

Huawei Honor 8

**Comment by SC1040-TS2** [comment]
Greetings. After encountering a similar degree of instability when I updated ot, it became clear that even when using the NewPipe Upstream Repository, the app was failing to properly migrate to 0.24.0 from 0.23.x.

The following process can be used to mitigate some of it:
1. In the existing 0.24.0 installation, Export a subscription backup. Do not export settings.
2. Once the export is completed, completely purge all data in the NewPipe app and in its App Info>Storage section.
3. Uninstall NewPipe.
4. Go back to F-Droid, and reinstall NewPipe 0.24.0.
5. Once successful there, Import your subscriptions backup, and reconfigure your settings manually.

That should mitigate most of the jank for now. When the app was initially pushed, something about the update process was malformed.

Let me know if this seems to help.
