### ISSUE TITLE
App crash when pressing back while the Ui is frozen trying to start a video.

### ISSUE THREAD

**Issue by amynbe** [TeamNewPipe/NewPipe#9132]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

App crash when pressing back while the Ui is frozen trying to start a video.

I should mention no video is able to on my phone, for an unknown reason.

* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.24.0
* __OS:__ Linux Android 12 - 31

### Logs

```
java.lang.IndexOutOfBoundsException
	at android.view.ViewGroup.removeFromArray(ViewGroup.java:6234)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:6422)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:6384)
	at android.view.ViewGroup.removeView(ViewGroup.java:6315)
	at org.schabi.newpipe.player.ui.MainPlayerUi.removeViewFromParent(MainPlayerUi.java:204)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda31.accept(Unknown Source:2)
	at j$.util.Optional.ifPresent(Unknown Source:4)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.removeVideoPlayerView(VideoDetailFragment.java:1345)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.hideMainPlayerOnLoadingNewStream(VideoDetailFragment.java:1252)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.setupFromHistoryItem(VideoDetailFragment.java:805)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.onBackPressed(VideoDetailFragment.java:798)
	at org.schabi.newpipe.MainActivity.onBackPressed(MainActivity.java:566)
	at android.app.Activity.onKeyUp(Activity.java:3905)
	at android.view.KeyEvent.dispatch(KeyEvent.java:3688)
	at android.app.Activity.dispatchKeyEvent(Activity.java:4230)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:124)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:86)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:142)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:599)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3089)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:822)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:7722)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7545)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6922)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6979)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6945)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7143)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6953)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7200)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6926)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6979)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6945)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6953)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6926)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6979)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6945)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7176)
	at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:7363)
	at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3399)
	at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2960)
	at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2951)
	at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3376)
	at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:186)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```

### Affected device model

Galaxy S10+

### Additional information

n/a

**Comment by amynbe** [comment]
Never happened again
