### ISSUE TITLE
Newpipe crashes while scrolling through comment list

### ISSUE THREAD

**Issue by hype11** [TeamNewPipe/NewPipe#9140]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

Goto to a video with a huge comment list and scroll down, read some and scroll further. 

### Expected behavior

Newpipe is not crashing and I can read all comments

### Actual behavior

Newpipe is crashing and restarting itsself automatical and show crash log

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ DE
* __Content Language:__ de-DE
* __App Language:__ de_DE
* __Service:__ none
* __Version:__ 0.24.0
* __OS:__ Linux samsung/gtaxlwifixx/gtaxlwifi:8.1.0/M1AJQ/T580XXU4CSA1:user/release-keys 8.1.0 - 27
<details><summary><b>Crash log </b></summary><p>

```
java.lang.ClassCastException: android.text.SpannedString cannot be cast to android.text.Spannable
	at org.schabi.newpipe.util.CommentTextOnTouchListener.onTouch(CommentTextOnTouchListener.java:29)
	at android.view.View.dispatchTouchEvent(View.java:12628)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3172)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3172)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3172)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3172)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3172)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3172)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3172)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3172)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3172)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3172)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3172)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3172)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3172)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3172)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3172)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:615)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1879)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3441)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:577)
	at android.view.View.dispatchPointerEvent(View.java:12880)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5863)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5658)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5151)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5204)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5170)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5307)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5178)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5364)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5151)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5204)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5170)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5178)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5151)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7981)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7921)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7882)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8092)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:198)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:325)
	at android.os.Looper.loop(Looper.java:142)
	at android.app.ActivityThread.main(ActivityThread.java:7000)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 8.1.0

### Affected device model

Samsung Tab A SM-T 580

**Comment by hype11** [comment]
for imformation: bug is just fixed: #9052
