### ISSUE TITLE
App initial start UI error

### ISSUE THREAD

**Issue by killerrook** [TeamNewPipe/NewPipe#9146]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. Install new pipe
2. import a save file
3. Clear data
4. Open the app

### Expected behavior

No error should occur

### Actual behavior

Ui error

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.24.0
* __OS:__ Linux OPPO/CPH1861/CPH1861:9/PPR1.180610.011/1587903909:user/release-keys 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.schabi.newpipe/org.schabi.newpipe.MainActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: androidx.fragment.app.FragmentManagerState
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3175)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3312)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:113)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:71)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2038)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:226)
	at android.app.ActivityThread.main(ActivityThread.java:7178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
Caused by: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: androidx.fragment.app.FragmentManagerState
	at android.os.Parcel.readParcelableCreator(Parcel.java:2855)
	at android.os.Parcel.readParcelable(Parcel.java:2781)
	at android.os.Parcel.readValue(Parcel.java:2684)
	at android.os.Parcel.readArrayMapInternal(Parcel.java:3053)
	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
	at android.os.BaseBundle.unparcel(BaseBundle.java:232)
	at android.os.Bundle.getParcelable(Bundle.java:940)
	at androidx.fragment.app.FragmentManager.attachController(FragmentManager.java:2583)
	at androidx.fragment.app.FragmentController.attachHost(FragmentController.java:116)
	at androidx.fragment.app.FragmentActivity.lambda$init$1(FragmentActivity.java:128)
	at androidx.fragment.app.FragmentActivity.$r8$lambda$QtiQ2ZI3e38UkO1_xuJ8vE_JZj4(Unknown Source:0)
	at androidx.fragment.app.FragmentActivity$$ExternalSyntheticLambda0.onContextAvailable(Unknown Source:2)
	at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:322)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:249)
	at org.schabi.newpipe.MainActivity.onCreate(MainActivity.java:136)
	at android.app.Activity.performCreate(Activity.java:7383)
	at android.app.Activity.performCreate(Activity.java:7374)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3155)
	... 11 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Color OS v6.0(android 9)

### Affected device model

Oppo Realme 1 CPH1861

**Comment by opusforlife2** [comment]
Try force-stopping the app before/after clearing data.
