### ISSUE TITLE
Long press->download button crash bug

### ISSUE THREAD

**Issue by killerrook** [TeamNewPipe/NewPipe#9154]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1.export data using settings>content>export data
2. Clear data and import data 
3. Long press on any video in What's new feed
4. Select download option

Note: Recently there have been a lot of issues related to storage permission. Since new pipe doesn't ask for read write permission for files on initial setup it causes issues with downloads and other features. A possible fix would be to prompt the request for storage access permission when the app is initially launched for first time or after clearing data.

### Expected behavior

The player should ask for storage permission and Download confirmation dialogue box appears

### Actual behavior

App crashes

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.24.0
* __OS:__ Linux OPPO/CPH1861/CPH1861:9/PPR1.180610.011/1587903909:user/release-keys 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List org.schabi.newpipe.util.StreamItemAdapter.getAll()' on a null object reference
	at org.schabi.newpipe.download.DownloadDialog.onViewCreated(DownloadDialog.java:286)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3019)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:226)
	at android.app.ActivityThread.main(ActivityThread.java:7178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

```
</details>
<hr>

### Affected Android/Custom ROM version

Color OS v6.0(android 9)

### Affected device model

Oppo Realme 1 CPH1861

### Additional information

Consistent and easily verifiable by reproduction. After repeating 3-4 times the player asks for storage permission and then issue disappears.

**Comment by Stypox** [comment]
Thanks for reporting! This should be fixed by https://github.com/TeamNewPipe/NewPipe/pull/10912
