### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by arfanmrafeek** [TeamNewPipe/NewPipe#9160]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

While playing a video, I seek it from beginning of the video. 

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_TIMEOUT] occurred while playing https://www.youtube.com/watch?v=_l1iUngU6pQ
* __Content Country:__ IN
* __Content Language:__ ml
* __App Language:__ en_GB
* __Service:__ YouTube
* __Version:__ 0.24.0
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
	at com.google.android.exoplayer2.ExoPlayerImpl.setVideoOutputInternal(ExoPlayerImpl.java:2491)
	at com.google.android.exoplayer2.ExoPlayerImpl.clearVideoSurface(ExoPlayerImpl.java:1242)
	at org.schabi.newpipe.player.ui.VideoPlayerUi$$ExternalSyntheticLambda15.accept(Unknown Source:2)
	at j$.util.Optional.ifPresent(Unknown Source:4)
	at org.schabi.newpipe.player.ui.VideoPlayerUi.clearVideoSurface(VideoPlayerUi.java:1559)
	at org.schabi.newpipe.player.ui.VideoPlayerUi.destroyPlayer(VideoPlayerUi.java:381)
	at org.schabi.newpipe.player.ui.MainPlayerUi.destroyPlayer(MainPlayerUi.java:222)
	at org.schabi.newpipe.player.Player$$ExternalSyntheticLambda22.accept(Unknown Source:2)
	at j$.util.Iterator$-CC.$default$forEachRemaining(SourceFile:2)
	at j$.util.Iterator$-EL.forEachRemaining(Unknown Source:10)
	at j$.util.O.forEachRemaining(Unknown Source:24)
	at j$.util.stream.i2.forEachOrdered(Unknown Source:10)
	at org.schabi.newpipe.player.ui.PlayerUiList.call(PlayerUiList.java:88)
	at org.schabi.newpipe.player.Player.destroyPlayer(Player.java:549)
	at org.schabi.newpipe.player.Player.destroy(Player.java:579)
	at org.schabi.newpipe.player.PlayerService.cleanup(PlayerService.java:119)
	at org.schabi.newpipe.player.PlayerService.onDestroy(PlayerService.java:114)
	at org.schabi.newpipe.player.PlayerService.onTaskRemoved(PlayerService.java:104)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4801)
	at android.app.ActivityThread.access$2200(ActivityThread.java:277)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8306)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)
Caused by: com.google.android.exoplayer2.ExoTimeoutException: Detaching surface timed out.
	at com.google.android.exoplayer2.ExoPlayerImpl.setVideoOutputInternal(ExoPlayerImpl.java:2489)
	... 27 more

```
</details>
<hr>

**Comment by opusforlife2** [comment]
Please provide more info and a proper title.

**Comment by arfanmrafeek** [comment]
It occurs once, So, I'm closing this...
