### ISSUE TITLE
App crash on startup

### ISSUE THREAD

**Issue by 5t0rmr1d3r** [TeamNewPipe/NewPipe#9163]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

Just tried to start the app again, the day before it worked on that version like a charm. No other updates (e.g. for OS) habe been installed. 

### Expected behavior

A normal starting and working app... 

### Actual behavior

App appears for a blink and vanishes instantly. Then after about a minute the crash report appears. 

### Logs

[Aicp Crashlog](https://haste.aicp-rom.com/dosulowuna) 

time: 1666281849726
msg: java.lang.IllegalArgumentException: Remote stack trace:
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.enforceValidJobRequest(JobSchedulerService.java:2569)
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:2631)
	at android.app.job.IJobScheduler$Stub.onTransact(IJobScheduler.java:153)
	at android.os.Binder.execTransactInternal(Binder.java:1154)
	at android.os.Binder.execTransact(Binder.java:1123)

stacktrace: java.lang.IllegalArgumentException: No such service ComponentInfo{org.schabi.newpipe/org.acra.sender.JobSenderService}
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2377)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.os.Parcel.readException(Parcel.java:2282)
	at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:308)
	at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:47)
	at org.acra.scheduler.DefaultSenderScheduler.scheduleReportSending(DefaultSenderScheduler.kt:52)
	at org.acra.scheduler.SchedulerStarter.scheduleReports(SchedulerStarter.kt:49)
	at org.acra.startup.StartupProcessorExecutor.processReports$lambda-5$lambda-4(StartupProcessorExecutor.kt:56)
	at org.acra.startup.StartupProcessorExecutor.$r8$lambda$o2NE53IEwtcT_aLpWXA2a4JC9OE(Unknown Source:0)
	at org.acra.startup.StartupProcessorExecutor$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:923)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.enforceValidJobRequest(JobSchedulerService.java:2569)
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:2631)
	at android.app.job.IJobScheduler$Stub.onTransact(IJobScheduler.java:153)
	at android.os.Binder.execTransactInternal(Binder.java:1154)
	at android.os.Binder.execTransact(Binder.java:1123)

### Affected Android/Custom ROM version

Android 11 / AICP 16.1

### Affected device model

ONEPLUS A6003

**Comment by opusforlife2** [comment]
Looks like an issue with the update check. Try opening the app after turning off internet.

**Comment by 5t0rmr1d3r** [comment]
When the phone is in flight mode the issue still exists.

[https://haste.aicp-rom.com/dosulowuna](https://haste.aicp-rom.com/dosulowuna)

That's the log that appears after the try...

**Comment by opusforlife2** [comment]
If you have root, can you take a backup of the app and then uninstall and reinstall it? If not, can you just try using an RC from [here]()https://github.com/TeamNewPipe/NewPipe/issues/8890#issue-1353049930 without importing any databases or changing any settings?

**Comment by 5t0rmr1d3r** [comment]
After an backup with titanium I Uninstaller it.
Freshly installed it startet again.
I then installed the backup of the app data and the following newpipe error screen appeard:

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ DE
* __Content Language:__ de
* __App Language:__ de_DE
* __Service:__ none
* __Version:__ 0.24.0
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalArgumentException: No such service ComponentInfo{org.schabi.newpipe/org.acra.sender.JobSenderService}
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2377)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.os.Parcel.readException(Parcel.java:2282)
	at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:308)
	at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:47)
	at org.acra.scheduler.DefaultSenderScheduler.scheduleReportSending(DefaultSenderScheduler.kt:52)
	at org.acra.scheduler.SchedulerStarter.scheduleReports(SchedulerStarter.kt:49)
	at org.acra.startup.StartupProcessorExecutor.processReports$lambda-5$lambda-4(StartupProcessorExecutor.kt:56)
	at org.acra.startup.StartupProcessorExecutor.$r8$lambda$o2NE53IEwtcT_aLpWXA2a4JC9OE(Unknown Source:0)
	at org.acra.startup.StartupProcessorExecutor$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:923)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.enforceValidJobRequest(JobSchedulerService.java:2569)
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:2631)
	at android.app.job.IJobScheduler$Stub.onTransact(IJobScheduler.java:153)
	at android.os.Binder.execTransactInternal(Binder.java:1154)
	at android.os.Binder.execTransact(Binder.java:1123)


```
</details>
<hr>

Then this error:

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ DE
* __Content Language:__ de
* __App Language:__ de_DE
* __Service:__ none
* __Version:__ 0.24.0
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalArgumentException: No such service ComponentInfo{org.schabi.newpipe/org.acra.sender.JobSenderService}
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2377)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.os.Parcel.readException(Parcel.java:2282)
	at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:308)
	at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:47)
	at org.acra.scheduler.DefaultSenderScheduler.scheduleReportSending(DefaultSenderScheduler.kt:52)
	at org.acra.scheduler.SchedulerStarter.scheduleReports(SchedulerStarter.kt:49)
	at org.acra.startup.StartupProcessorExecutor.processReports$lambda-5$lambda-4(StartupProcessorExecutor.kt:56)
	at org.acra.startup.StartupProcessorExecutor.$r8$lambda$o2NE53IEwtcT_aLpWXA2a4JC9OE(Unknown Source:0)
	at org.acra.startup.StartupProcessorExecutor$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:923)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.enforceValidJobRequest(JobSchedulerService.java:2569)
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:2631)
	at android.app.job.IJobScheduler$Stub.onTransact(IJobScheduler.java:153)
	at android.os.Binder.execTransactInternal(Binder.java:1154)
	at android.os.Binder.execTransact(Binder.java:1123)


```
</details>
<hr>
Then another:
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ DE
* __Content Language:__ de
* __App Language:__ de_DE
* __Service:__ none
* __Version:__ 0.24.0
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalArgumentException: No such service ComponentInfo{org.schabi.newpipe/org.acra.sender.JobSenderService}
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2377)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.os.Parcel.readException(Parcel.java:2282)
	at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:308)
	at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:47)
	at org.acra.scheduler.DefaultSenderScheduler.scheduleReportSending(DefaultSenderScheduler.kt:52)
	at org.acra.scheduler.SchedulerStarter.scheduleReports(SchedulerStarter.kt:49)
	at org.acra.startup.StartupProcessorExecutor.processReports$lambda-5$lambda-4(StartupProcessorExecutor.kt:56)
	at org.acra.startup.StartupProcessorExecutor.$r8$lambda$o2NE53IEwtcT_aLpWXA2a4JC9OE(Unknown Source:0)
	at org.acra.startup.StartupProcessorExecutor$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at java.lang.Thread.run(Thread.java:923)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.enforceValidJobRequest(JobSchedulerService.java:2569)
	at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:2631)
	at android.app.job.IJobScheduler$Stub.onTransact(IJobScheduler.java:153)
	at android.os.Binder.execTransactInternal(Binder.java:1154)
	at android.os.Binder.execTransact(Binder.java:1123)


```
</details>
<hr>

Then this one:

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ DE
* __Content Language:__ de
* __App Language:__ de_DE
* __Service:__ none
* __Version:__ 0.24.0
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{8dbcc07 u0 org.schabi.newpipe/.player.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2006)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7661)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

```
</details>
<hr>

Then the ui of newpipe appeared

**Comment by 5t0rmr1d3r** [comment]
Situation isn't there anymore. And can be marked as solved.
There is not yet a 0.26.0 RC in your fdroid repo, so I haven't tested that.

*Von: *opusforlife2 ***@***.***>
*An: *TeamNewPipe/NewPipe ***@***.***>
*Kopie: *Uwe Schanbacher ***@***.***>; Mention ***@***.***>
*Datum: *22.10.2023 22:11:24
*Betreff: *Re: [TeamNewPipe/NewPipe] App crash on startup (Issue #9163)
