### ISSUE TITLE
Occurred while selecting next video

### ISSUE THREAD

**Issue by Charan-ravi** [TeamNewPipe/NewPipe#9165]
https://user-images.githubusercontent.com/52713551/197202174-cc90b0be-2d54-493f-aec3-a7df1d2f1e33.mp4

### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. Played a video (Ryan Reynolds speech will leave you speechless)
2. When selecting the next video(Robert Downey Jr speech from suggestions), after hitting the play button the app seems to be crashed 

### Expected behavior

1. Play the selected video 

### Actual behavior

I have attached the logs 

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_DECODER_INIT_FAILED] occurred while playing https://www.youtube.com/watch?v=vEEvoH-45Yc
* __Content Country:__ IN
* __Content Language:__ en-IN
* __App Language:__ en_IN
* __Service:__ YouTube
* __Version:__ 0.24.0
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(315, null, null, video/x-vnd.on2.vp9, vp9, 27029497, en, [3840, 2160, 60.0], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:566)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: c2.qti.vp9.decoder, Format(315, null, null, video/x-vnd.on2.vp9, vp9, 27029497, en, [3840, 2160, 60.0], [-1, -1])
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1030)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:546)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1450)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:877)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:963)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:779)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
	... 4 more
Caused by: android.media.MediaCodec$CodecException: start failed
	at android.media.MediaCodec.native_start(Native Method)
	at android.media.MediaCodec.start(MediaCodec.java:2284)
	at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.initialize(AsynchronousMediaCodecAdapter.java:160)
	at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.access$100(AsynchronousMediaCodecAdapter.java:50)
	at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter$Factory.createAdapter(AsynchronousMediaCodecAdapter.java:103)
	at com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:108)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1108)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1019)
	... 11 more

```
</details>
<hr>

### Affected device model

Nothing phone 1

**Comment by opusforlife2** [comment]
> format_supported=NO_EXCEEDS_CAPABILITIES

Your device can't play this stream. Try lower resolutions/different format.

@AudricV Is there any way to detect this and automatically lower the resolution to a safe option, like 1080p?

**Comment by Charan-ravi** [comment]
After a restart it works fine at 1080 60fps setting.

**Comment by Charan-ravi** [comment]
Oh but my device does have support to play 4k videos also it doesn't show 4k in the quality now 

https://user-images.githubusercontent.com/52713551/197348056-a85095b7-0a95-4a24-afe9-346b06d193d6.mp4

**Comment by opusforlife2** [comment]
>also it doesn't show 4k in the quality now

In video and audio settings, there will be a toggle to show higher resolutions.

**Comment by Charan-ravi** [comment]
I have attached the debug info below even in YouTube the max resolution is 1080 so how it is possible that I can find the same video at 4k here.
PS: I thought this might be needed.
{
  "ns": "yt",
  "el": "detailpage",
  "cpn": "e_CLO91arevQafT_",
  "ver": 2,
  "cmt": "0",
  "fmt": "399",
  "fs": "0",
  "rt": "65.529",
  "euri": "",
  "lact": 2,
  "cl": "481927134",
  "mos": 0,
  "state": "804",
  "volume": 100,
  "cbrand": "nothing",
  "cbr": "Chrome Mobile",
  "cbrver": "106.0.0.0",
  "c": "MWEB",
  "cver": "2.20221020.06.00",
  "cplayer": "UNIPLAYER",
  "cmodel": "a063",
  "cos": "Android",
  "cosver": "12",
  "cplatform": "MOBILE",
  "hl": "en_US",
  "cr": "IN",
  "len": "485.141",
  "fexp": "23983296,24001373,24002022,24002025,24004644,24007246,24080738,24113425,24135310,24169501,24211858,24248385,24255165,24279628,24280768,24285874,24289901,24290131,24290289,24292955,24295233,24298640,24394105,24396235,24396436,24397192,24399521,24404215,39322399",
  "afmt": "251",
  "muted": "0",
  "conn": "3",
  "docid": "7vBb4-E-4Qc",
  "ei": "lg9UY-zhDfqVg8UPl7aRqAg",
  "plid": "AAXroWrYSOptzRYy",
  "of": "ImWPqp0UsHeFS14sIVnNKg",
  "vm": "CAEQARgEOjJBTGV0MXV6U3Jxam9XNldYVHdCX00zSDBmTEhwU3JuTnBlc1FRSFN2OUNyMFNvblVQd2JXQVBta0tESk1BN3dveUNrV0E3WDdDY1FIa1R4QUw2OVladklmanpsNVd6eUs5OGlxckozYTEtbkRzNWg4amRQUjBGdXVFbHJFYVExc1lKNlFITjYwUEFFaAE",
  "vct": "0.000",
  "vd": "485.141",
  "vpl": "",
  "vbu": "0.000-15.001",
  "vpa": "1",
  "vsk": "0",
  "ven": "0",
  "vpr": "1",
  "vrs": "4",
  "vns": "2",
  "vec": "null",
  "vemsg": "",
  "vvol": "1",
  "vdom": "1",
  "vsrc": "1",
  "vw": "412",
  "vh": "232",
  "lct": "0.000",
  "lsk": false,
  "lmf": true,
  "lbw": "1369273.199",
  "lhd": "0.070",
  "lst": "0.000",
  "laa": "itag_251_type_3_seg_1_range_168523-250817_time_10.0-15.1_off_0_len_82295",
  "lva": "itag_399_type_3_seg_5_range_3073586-3300894_time_20.8-23.4_off_109500_len_227309_end_1",
  "lar": "itag_251_type_3_seg_2_range_328446-479063_time_20.0-30.0_off_0_len_150618_end_1",
  "lvr": "itag_399_type_3_seg_5_range_2964086-3300894_time_19.6-23.4_off_0_len_336809_end_1",
  "laq": "228246",
  "lvq": "0",
  "lab": "0.000-15.001",
  "lvb": "0.000-23.390",
  "ismb": 2400000,
  "relative_loudness": "-2.380",
  "optimal_format": "1080p60",
  "user_qual": 1080,
  "release_version": "youtube.player.web_20221018_01_RC00",
  "debug_videoId": "7vBb4-E-4Qc",
  "0sz": "false",
  "op": "",
  "yof": "false",
  "dis": "",
  "gpu": "Adreno_(TM)_642L",
  "debug_playbackQuality": "hd1080",
  "debug_date": "Sat Oct 22 2022 21:16:32 GMT+0530 (India Standard Time)"
}

**Comment by opusforlife2** [comment]
> "fmt": "399",

That's AV1. So it might not have been the resolution, but the codec which is unsupported.

**Comment by Charan-ravi** [comment]
There are other videos which are supported at 2160p. So I think the crash bug was a one time event and might not reoccur.

**Comment by opusforlife2** [comment]
It was just pointed out to me that this second report is not from the same video/app. You posted a different one that has nothing to do with your original error.

The format you got for the original issue in the description is 315, which is VP9 4K. There are other videos you can check using this format. My guess is none of them will work.

**Comment by Charan-ravi** [comment]
Unable to play the video
Copied the formatted report
## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_DECODER_INIT_FAILED] occurred while playing https://www.youtube.com/watch?v=V1vaJnl4G3A
* __Content Country:__ IN
* __Content Language:__ en-IN
* __App Language:__ en_IN
* __Service:__ YouTube
* __Version:__ 0.24.0
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(315, null, null, video/x-vnd.on2.vp9, vp9, 17066708, en, [3840, 1920, 50.0], [-1, -1]), format_supported=NO_EXCEEDS_CAPABILITIES
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:566)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: c2.qti.vp9.decoder, Format(315, null, null, video/x-vnd.on2.vp9, vp9, 17066708, en, [3840, 1920, 50.0], [-1, -1])
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1030)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:546)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1450)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:877)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:963)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:779)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
	... 4 more
Caused by: android.media.MediaCodec$CodecException: start failed
	at android.media.MediaCodec.native_start(Native Method)
	at android.media.MediaCodec.start(MediaCodec.java:2284)
	at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.initialize(AsynchronousMediaCodecAdapter.java:160)
	at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.access$100(AsynchronousMediaCodecAdapter.java:50)
	at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter$Factory.createAdapter(AsynchronousMediaCodecAdapter.java:103)
	at com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:108)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1108)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1019)
	... 11 more

```
</details>
<hr>

**Comment by opusforlife2** [comment]
Yes, that's the same format, see? So your device can't decode VP9 4K. Use a different resolution/format combo that works for you.
