### ISSUE TITLE
ERROR_CODE_DECODER_INIT_FAILED appearing when trying to watch any video

### ISSUE THREAD

**Issue by olgak0096** [TeamNewPipe/NewPipe#9215]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

I was trying to use NewPipe to watch 1) https://www.youtube.com/watch?v=2ZbiAfNCo0E
2) https://www.youtube.com/watch?v=eAjhxj7TIoA
in both cases I got the same error. I attach below the message I've gotten. I had to use YouTube ReVanced app instead.

### Expected behavior

I want to play those and others videos.

### Actual behavior

It crashes. It loads the video but when clicked play button it crushes and throws an exception.

### Screenshots/Screen recordings

![0003](https://user-images.githubusercontent.com/56155203/198161845-8fbb615d-c098-45ba-852e-2493a71fb35f.jpg)
![0002](https://user-images.githubusercontent.com/56155203/198161849-b5f5dbf1-35c2-4d1e-ade0-ce10813d1352.jpg)
<img alt="0001" src="https://user-images.githubusercontent.com/56155203/198161850-a3a48517-41bd-45c2-88dd-62a9316732e1.jpg" height=600 />

## Exception
* _User Action:_ play stream
* _Request:_ Player error[type=ERROR_CODE_DECODER_INIT_FAILED] occurred while playing [https://www.youtube.com/watch?v=eAjhxj7TIoA](https://www.youtube.com/watch?v=eAjhxj7TIoA&fbclid=IwAR1tQ3frNYg9BZpwcbpx5JsMYkwZU0Pqwwv_4eEOqGUqjzksoIjGXI8kD9U)
* _Content Country:_ PL
* _Content Language:_ pl-PL
* _App Language:_ pl_PL
* _Service:_ YouTube
* _Version:_ 0.24.0
* _OS:_ Linux samsung/j5y17ltexx/j5y17lte:9/PPR1.180610.011/J530FXXU6CSK9:user/release-keys 9 - 28
<details><summary><b>Crash log </b></summary><p>

com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(135, null, null, video/avc, avc1.4D401F, 1164036, null, [852, 480, 30.0], [-1, -1]), format_supported=YES
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:566)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:216)
	at android.os.HandlerThread.run(HandlerThread.java:65)
Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.Exynos.avc.dec, Format(135, null, null, video/avc, avc1.4D401F, 1164036, null, [852, 480, 30.0], [-1, -1])
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1030)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:546)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1450)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:877)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:963)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:779)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
	... 3 more
Caused by: android.media.MediaCodec$CodecException: Error 0xffffec77
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:1960)
	at android.media.MediaCodec.configure(MediaCodec.java:1889)
	at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter$Factory.createAdapter(SynchronousMediaCodecAdapter.java:51)
	at com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:110)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1108)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1019)
	... 10 more

</details>
<hr>

### Affected Android/Custom ROM version

Android 9 Pie

### Affected device model

Samsung Galaxy J5 (2017)

**Comment by olgak0096** [comment]
Well, the original app works. But I feel it's a problem with my hardware as it's still there. So I'll leave my phone to Samsung help center and tell them there's a problem. So that they will be able to  update codeks. But please be sure that if anyone has the same problem NewPipe will be able to deal with this.
![image](https://user-images.githubusercontent.com/56155203/198767636-2e961a24-4078-40ef-a6af-aca4f9a6ec00.png)

**Comment by olgak96-art** [comment]
However now I tried to play it in NewPipe and it works. I also saw two others videos that I wanted to watch a few hours ago and then it didn't work. I don't see the error now. Thank you.
