### ISSUE TITLE
App Crash when importing subscriptions.csv

### ISSUE THREAD

**Issue by NX-Mirco-Centrone** [TeamNewPipe/NewPipe#9219]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. Importing a subscription.scv file

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ IT
* __Content Language:__ it-IT
* __App Language:__ it_IT
* __Service:__ none
* __Version:__ 0.24.0
* __OS:__ Linux motorola/nairo_retaile/nairo:11/RPN31.Q4U-39-27-8/9deb9:user/release-keys 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start service org.schabi.newpipe.local.subscription.services.SubscriptionsImportService@1ceee83 with Intent { cmp=org.schabi.newpipe/.local.subscription.services.SubscriptionsImportService (has extras) }: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{1f97243 31160:org.schabi.newpipe/u0a316} (pid=31160, uid=10316) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4406)
	at android.app.ActivityThread.access$1800(ActivityThread.java:250)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2000)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:250)
	at android.app.ActivityThread.main(ActivityThread.java:7755)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{1f97243 31160:org.schabi.newpipe/u0a316} (pid=31160, uid=10316) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.os.Parcel.readException(Parcel.java:2282)
	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5988)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:6904)
	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2964)
	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2481)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1800)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1631)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1578)
	at us.shandian.giga.io.FileStreamSAF.<init>(FileStreamSAF.java:32)
	at org.schabi.newpipe.streams.io.StoredFileHelper.getStream(StoredFileHelper.java:192)
	at org.schabi.newpipe.local.subscription.services.SubscriptionsImportService.onStartCommand(SubscriptionsImportService.java:118)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4388)
	... 8 more

```
</details>
<hr>

**Comment by tsiflimagas** [comment]
Have you disabled or removed the system's Files app (com.android.documentsui)?

**Comment by NX-Mirco-Centrone** [comment]
@tsiflimagas there is no app running or installed with that particular name.
there is however a "com.google.android.overlay.modules.documentsui"
