### ISSUE TITLE
newpipe 0.24.0 crash

### ISSUE THREAD

**Issue by Domiuns** [TeamNewPipe/NewPipe#9222]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

open the app
open a video
see a long comment and expand it
click again on the expanded comment to make it collapsed
the app crashes

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ IT
* __Content Language:__ it-IT
* __App Language:__ it_IT
* __Service:__ none
* __Version:__ 0.24.0
* __OS:__ Linux Android 7.0 - 24
<details><summary><b>Crash log </b></summary><p>

```
java.lang.ClassCastException: android.text.SpannedString cannot be cast to android.text.Spannable
	at org.schabi.newpipe.util.CommentTextOnTouchListener.onTouch(CommentTextOnTouchListener.java:29)
	at android.view.View.dispatchTouchEvent(View.java:10101)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2782)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2361)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:435)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1836)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3072)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:397)
	at android.view.View.dispatchPointerEvent(View.java:10341)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4928)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4787)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4293)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4346)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4312)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4459)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4320)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4516)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4293)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4346)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4312)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4320)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4293)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6817)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6791)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6734)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6989)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:328)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:6361)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 7.0

### Affected device model

sony xperia

**Comment by tsiflimagas** [comment]
Duplicate of #9052. Fixed in #9065.
