### ISSUE TITLE
Soundcloud doesn't load any songs

### ISSUE THREAD

**Issue by mamRobles** [TeamNewPipe/NewPipe#9227]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. Open any song
2. Try to reproduce it

### Expected behavior

The song plays

### Actual behavior

It doesn't play the song and blames it on the network.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/114167756/198367329-e0a39436-04db-47fb-8b83-429c212a1e6f.mp4

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_PARSING_CONTAINER_MALFORMED] occurred while playing https://soundcloud.com/raowoul/from-y-to-y-len
* __Content Country:__ ES
* __Content Language:__ es-ES
* __App Language:__ es_ES
* __Service:__ SoundCloud
* __Version:__ 0.24.0
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:632)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:602)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.ParserException: Cannot find sync byte. Most likely not a Transport Stream.
	at com.google.android.exoplayer2.extractor.ts.TsExtractor.findEndOfFirstTsPacketInBuffer(TsExtractor.java:460)
	at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:327)
	at com.google.android.exoplayer2.source.hls.BundledHlsMediaChunkExtractor.read(BundledHlsMediaChunkExtractor.java:67)
	at com.google.android.exoplayer2.source.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:473)
	at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:437)
	at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:394)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12

### Affected device model

Samsung galaxy s10

**Comment by opusforlife2** [comment]
All these songs are working. Try a different network.

**Comment by marmrobles** [comment]
Really weird, with wifi works just fine but when I use mobile data it crashes without further explanation. On the Souncloud page it works with both, not sure of what is going on.

**Comment by bbbbnny** [comment]
Have the same issue but on a Pixel 3a. Works on wifi but not on data.

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_PARSING_CONTAINER_MALFORMED] occurred while playing https://soundcloud.com/ssaliva/close2me-ss-stretchd_ascent-edit
* __Content Country:__ AU
* __Content Language:__ en-AU
* __App Language:__ en_AU
* __Service:__ SoundCloud
* __Version:__ 0.24.0
* __OS:__ Linux Android 12 - 32
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:632)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:602)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.ParserException: Cannot find sync byte. Most likely not a Transport Stream.
	at com.google.android.exoplayer2.extractor.ts.TsExtractor.findEndOfFirstTsPacketInBuffer(TsExtractor.java:460)
	at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:327)
	at com.google.android.exoplayer2.source.hls.BundledHlsMediaChunkExtractor.read(BundledHlsMediaChunkExtractor.java:67)
	at com.google.android.exoplayer2.source.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:473)
	at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:437)
	at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:394)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```
</details>
<hr>

Sorry if i shouldnt comment on closed issues or have wrong formatting.

**Comment by ShareASmile** [comment]
if no other issue is open about this specific issue, then this should be re-opened.

**Comment by selurvedu** [comment]
Same here.

**Comment by szc126** [comment]
The same issue happens when a Wi-Fi network has been designated as metered.

**Comment by val9299** [comment]
Reading here it was an issue with mobile data y tried to change "Limit resolution when using mobile data" to "no limit" and it worked for me. I can play SoundCloud now. This setting can be found in Settings -> Video and audio. It's one of the first settings in the list.

**Comment by vomindoraan** [comment]
I am still having this issue on v0.25.0. SoundCloud streams work fine over Wi-Fi, but error out when trying to play over mobile data. Changing the aforementioned _Limit resolution_ setting to _No limit_ allows streams to play, but this feels more like a workaround than a proper solution. Ideally, I would like to be able to keep the setting on 480p for YouTube videos, while at the same time being able to stream audio from SoundCloud unimpeded.
