### ISSUE TITLE
An error is thrown every time a video completes playing in full-screen mode

### ISSUE THREAD

**Issue by rohandebsarkar** [TeamNewPipe/NewPipe#9254]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

1. Play any video.
2. Wait for it to complete playing.
3. An error toast message is shown.
4. The following error is encountered.

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_FAILED_RUNTIME_CHECK] occurred while playing https://www.youtube.com/watch?v=CqkhjL3WvWQ
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.24.0
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
 at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.lang.IllegalArgumentException
 at android.media.MediaCodec.native_setSurface(Native Method)
 at android.media.MediaCodec.setOutputSurface(MediaCodec.java:2233)
 at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.setOutputSurface(AsynchronousMediaCodecAdapter.java:262)
 at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:1451)
 at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutput(MediaCodecVideoRenderer.java:646)
 at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:584)
 at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:1546)
 at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:1510)
 at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:1485)
 at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:521)
 ... 4 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 13 / Custom ROM

### Affected device model

Redmi Note 7

**Comment by opusforlife2** [comment]
First, try using a completely blank installation of the app (make sure you take a database backup before clearing app data). If the bug is still there, try on a different device/ROM.

**Comment by Melarok** [comment]
I have the same problem since switching to A13 on my Poco F3.
In my instance I also get the error if I rotate my phone during playback.

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_FAILED_RUNTIME_CHECK] occurred while playing https://www.youtube.com/watch?v=rm8lvwdUzFs
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ YouTube
* __Version:__ 0.24.0
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.lang.IllegalArgumentException
	at android.media.MediaCodec.native_setSurface(Native Method)
	at android.media.MediaCodec.setOutputSurface(MediaCodec.java:2233)
	at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.setOutputSurface(AsynchronousMediaCodecAdapter.java:262)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:1451)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutput(MediaCodecVideoRenderer.java:646)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:584)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:1546)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:1510)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:1485)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:521)
	... 4 more

```
</details>
<hr>

**Comment by rohandebsarkar** [comment]
I noticed this also happens when pressing the back button or home button when the player is in full screen mode. Also, if I try to get out of the full screen mode using the icon in the bottom left corner.

**Comment by opusforlife2** [comment]
@Melarok Custom ROM or stock OS?

**Comment by Melarok** [comment]
@opusforlife2 Custom (CrDroid with microG to be specific)

**Comment by tsiflimagas** [comment]
Oh, so I can now confirm it's a crDroid source issue. Yesterday I installed an update and started getting this error everytime I start the popup player, or coming back from fullscreen, and maybe in more cases.

**Comment by opusforlife2** [comment]
Please leave a comment in case this turns out not to be a crDroid bug.

**Comment by danielzgtg** [comment]
Is there a link to this on the crDroid bug tracker?

**Comment by Terminator-J** [comment]
It's something in our frameworks/av/ 13.0 branch currently, beyond what's in LineageOS (upon which we ware based).
If I roll that project back to match lineage-20.0, the bug disappears.
I'm working my way through a `git bisect` now; I'll keep the crDroid bug tracker updated & probably PR for a revert in the next day or so.

**Comment by Terminator-J** [comment]
It's resolved.
https://github.com/crdroidandroid/issue_tracker/issues/35
We'd been including a commit in framework/av/ from AOSP gerrit from a Xiaomi contributor that ended up getting abandoned.
Dropping it resolved the bug.
