### ISSUE TITLE
Using auto-rotation while a video is loading crashes the app consistently.

### ISSUE THREAD

**Issue by syboxez** [TeamNewPipe/NewPipe#9277]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.0

### Steps to reproduce the bug

May be related to #8152

To reproduce, queue up two or more videos, then at the end of one video, right before the next one starts playing, use auto-rotate. The beginning orientation does not matter, but portrait to landscape or vice versa.

### Expected behavior

I expect roration as normal

### Actual behavior

App crashes

### Affected Android/Custom ROM version

LineageOS 17.1 through 20

### Affected device model

OnePlus 6, Pixel 3a, Nexus 6P

**Comment by FinnHuelsbusch** [comment]
I also have problems when rotating my OnePlus Nord while there is more than one video in the queue. 
I am happy to provide further information or logs if needed but may need instructions on how to extract the information (non rooted device) 

Kind regards, 
Finn

**Comment by somos61** [comment]
alike as #9329 issue
in my case even no need in queue. Using internal player, just rotate screen while playing video and it fails with error message (like on screenshot in mentioned)

**Comment by opusforlife2** [comment]
Check with the latest version.

**Comment by FinnHuelsbusch** [comment]
The bug is also present in 0.24.1. Though I have not tried a build from dev.

**Comment by somos61** [comment]
as for me in my post above it's about v 0.24.1, still there

**Comment by seniorm0ment** [comment]
Have encountered this issue for a few months, however it is not only during loading. It is also during playback for me. Sometimes I can rotate fine, othertimes when rotating it just crashes with no error.
Very aggravating.

Latest Newpipe, Pixel 6 Pro GrapheneOS

**Comment by FinnHuelsbusch** [comment]
Sometimes I get the following crash report: ## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ DE
* __Content Language:__ de-DE
* __App Language:__ de_DE
* __Service:__ none
* __Version:__ 0.24.1
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
android.app.ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{ea1cc0a u0 org.schabi.newpipe/.player.PlayerService}
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2054)
	at android.app.ActivityThread.access$2800(ActivityThread.java:254)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2279)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

```
</details>
<hr>


Which seams to be related to #9030.

**Comment by ykuksenko** [comment]
Also seeing crashes on rotation but during playback without any message. `Newpipe 0.25.1`, `pixel 4a`, `GrapheneOS`.

**Comment by johnstonesnow** [comment]
Ditto, random crashes whether multiple videos queued or not. Lose entire queue each time. Would love it if it could be fixed
