### ISSUE TITLE
Error, Can't play videos on full screen

### ISSUE THREAD

**Issue by 307jose** [TeamNewPipe/NewPipe#9329]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1

### Steps to reproduce the bug

1.- Open NewPipe and reproduce any video
2.- The video plays without any error, but if you turn the cell phone to enter full-screen mode the error happens.

### Expected behavior

The video plays without any error if you turn the cell phone to enter full-screen mode.

### Actual behavior

The video plays with error if you turn the cell phone to enter full-screen mode.

### Screenshots/Screen recordings

![Screenshot_20221107-011618](https://user-images.githubusercontent.com/108562987/200247778-a55d8f31-5a99-42fb-a1f2-9b895418e47c.png)

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_FAILED_RUNTIME_CHECK] occurred while playing https://www.youtube.com/watch?v=22mEBhcdR1M
* __Content Country:__ MX
* __Content Language:__ es-MX
* __App Language:__ es_MX
* __Service:__ YouTube
* __Version:__ 0.24.1
* __OS:__ Linux Android 6.0 - 23
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:207)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: java.lang.IllegalArgumentException
	at android.media.MediaCodec.native_setSurface(Native Method)
	at android.media.MediaCodec.setOutputSurface(MediaCodec.java:1810)
	at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter$$ExternalSyntheticApiModelOutline0.m(R8$$SyntheticClass)
	at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.setOutputSurface(SynchronousMediaCodecAdapter.java:189)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:1451)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutput(MediaCodecVideoRenderer.java:646)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:584)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:1546)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:1510)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:1485)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:521)
	... 3 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Linux Android 6.0 - 23

### Affected device model

Alcatel Shine (5080A)

**Comment by somos61** [comment]
Confirm, rotating screen to landscape while playing video fails with error. Also trying to go to fullscreen from popup fails.
Android 7.0

**Comment by stevep99** [comment]
Confirmed here too, with an Android 6.0 device. 
All videos crash when played in full screen landscape mode. Works OK as portrait or popup.

**Comment by rubbernglue** [comment]
I have this exact same problem, still I have not tried 0.24.1 yet though because you still confirms the problem hanging on from 0.24.0. I use this mainly on my Philips Android TV and if I try to make it full screen in any way the app crashes.
Imagewise it works well on 0.23.3, however other issues have emerged with that version.

**Comment by mart-hill** [comment]
I can confirm that on the Philips 50PUS8546 AndroidTV, updated - since NewPipe 0.24 version, it's impossible to play anything on full screen (by selecting that square on the bottom right corner). I can only view the content in half-screen, squeezed.

**Comment by somos61** [comment]
i have made my video of error:
https://user-images.githubusercontent.com/117638248/201401712-2820aa78-7e09-4d6f-be54-89d636dec61d.mp4

log is nearly the same:
`## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_FAILED_RUNTIME_CHECK] occurred while playing https://www.youtube.com/watch?v=En4OxhdgYo4
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.24.1
* __OS:__ Linux Android 7.0 - 24
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:203)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: java.lang.IllegalArgumentException
	at android.media.MediaCodec.native_setSurface(Native Method)
	at android.media.MediaCodec.setOutputSurface(MediaCodec.java:1914)
	at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter$$ExternalSyntheticApiModelOutline0.m(R8$$SyntheticClass)
	at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter.setOutputSurface(SynchronousMediaCodecAdapter.java:189)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:1451)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutput(MediaCodecVideoRenderer.java:646)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:584)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:1546)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:1510)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:1485)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:521)
	... 3 more`

**Comment by somos61** [comment]
As well the problem persists for:
- going to fullscreen from popup
https://user-images.githubusercontent.com/117638248/201402696-4ecac421-7ef7-4094-95e1-870f87b3c1b9.mp4

- going to background from mini/popup
https://user-images.githubusercontent.com/117638248/201402922-56bdbe27-0f27-47a0-9d48-2e4c1b55a744.mp4

Crash logs is the same as above

**Comment by mart-hill** [comment]
I'll have to check, if I'm able to pick up the crash log from the program on this dreary AndroidTV - this OS sucks more and more with every iteration (I can't even open HTTP/HTTPS links in it). :)
This crash occurs no matter the video format I choose, be it WebM 2160p, or MP4 (probably AVC codec) 1080p. I hope it's not dependent on SoC, in my case (probably) MT5887 with Mali-G51 M4 GPU.

**Comment by opusforlife2** [comment]
Could you guys try https://github.com/TeamNewPipe/NewPipe/issues/9396#issuecomment-1312950357?

**Comment by somos61** [comment]
> Could you guys try [#9396 (comment)](https://github.com/TeamNewPipe/NewPipe/issues/9396#issuecomment-1312950357)?

Seems like in my case clearing app data/cache, whatever, is not working. Tried also fresh install, still there. As well the problem persists the same for app-debug channel tabs variant of NewPipe at #9182

**Comment by mart-hill** [comment]
Thanks a lot!
For now I'll wait patiently - the normal YT app is practically unusable on AndroidTV OS (ads destroyed the comfort of using it completely), and it's not possible to enable HTTPS filtering anymore with AdGuard on this OS. It's not even opening HTTPS links in standard browser (at least on Philips 50PUS8546). NewPipe is the one of the rarest gems out there. 🥇

**Comment by sstraightea** [comment]
I'm having a similar issue on Android 13.

The error occurs when rotating the view (for me it crashes when rotating from fullscreen to normal) or changing the resolution of the playback. Sometimes it happens when a video ends as well, and in a few cases also just randomly during playback. 

My crash log is the following:

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_FAILED_RUNTIME_CHECK] occurred while playing https://www.youtube.com/watch?v=wdBGCI0_wfg
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ YouTube
* __Version:__ 0.24.1
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.lang.IllegalArgumentException
	at android.media.MediaCodec.native_setSurface(Native Method)
	at android.media.MediaCodec.setOutputSurface(MediaCodec.java:2233)
	at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter$$ExternalSyntheticApiModelOutline0.m(Unknown Source:0)
	at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.setOutputSurface(AsynchronousMediaCodecAdapter.java:262)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:1451)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutput(MediaCodecVideoRenderer.java:646)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:584)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:1546)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:1510)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:1485)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:521)
	... 4 more

```
</details>
<hr>

**Comment by disconnect5852** [comment]
Same here: xiaomi TV stick, android TV 11, cant play full screen. If i try, after that nothing will play, even if not full screen. Restart of the tv stick is needed to try again

**Comment by g1t3m** [comment]
[ Crash on Rotation (and startup initially) #216 ]
(https://github.com/polymorphicshade/NewPipe/issues/216) 
    Search for a video (likely optional)
    Click on a video
    Rotate the screen quickly while the video is buffering or click the fullscreen icon on the video
Expected: Video plays in landscape mode
Actual: App crashes and resets to initial Newpipe screen.

The above issue occurs even in the normal release of NewPipe.

The crash occurred with the "start main player in full screen" setting turned off and my phone's auto rotate setting turned off.

Phone: Google Pixel 6 Pro
OS: GrapheneOS, Android 13
Newpipe Version: 0.24.1
App Fork: Sponsorblock

I can attest to this issue of Newpipe crashing whenever I expand the video to fullscreen when pressing the fullscreen button. It doesn't happen on all videos, but once in a while.
