### ISSUE TITLE
App crashes trying to close popup via red "X" at the bottom

### ISSUE THREAD

**Issue by somos61** [TeamNewPipe/NewPipe#9378]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

v0.24.1

### Steps to reproduce the bug

1. Start play in popup
2. Touch and hold popup
3. When red "X" circle appears at the bottom, drag popup on it to close

### Expected behavior

Expected popup window closed

### Actual behavior

App goes to crash log page with error

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/117638248/201408701-53363737-691a-448e-a4c3-3aec0231006b.mp4

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.24.1
* __OS:__ Linux Android 7.0 - 24
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalArgumentException: View=android.widget.FrameLayout{5e80b13 V.E...... ......ID 0,0-720,1232} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:499)
	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:406)
	at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:124)
	at org.schabi.newpipe.player.ui.PopupPlayerUi$1.end(PopupPlayerUi.java:383)
	at org.schabi.newpipe.player.ui.PopupPlayerUi$1.onAnimationEnd(PopupPlayerUi.java:379)
	at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1142)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1149)
	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1309)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
	at android.animation.AnimationHandler.-wrap2(AnimationHandler.java)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:905)
	at android.view.Choreographer.doCallbacks(Choreographer.java:709)
	at android.view.Choreographer.doFrame(Choreographer.java:641)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:893)
	at android.os.Handler.handleCallback(Handler.java:836)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6269)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 7.0

### Affected device model

Gionee A1

**Comment by somos61** [comment]
Seem like this problem relates to fullscreen crash issue described here #9023
Working debug fixes also this issue with crash on close via red X circle
Closed
