### ISSUE TITLE
Fails to play video

### ISSUE THREAD

**Issue by 0Karakurt0** [TeamNewPipe/NewPipe#9379]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1

### Steps to reproduce the bug

1. Set Default video format (probably does not matter)
2. Open link https://www.youtube.com/watch?v=ZSEF1ugUof0
3. Wait for it to load (takes slightly longer than usual)
4. Observe ~3 seconds of black screen.

### Expected behavior

To be able to watch a video

### Actual behavior

~3 seconds of black screen are displayed, after which queue is cleared.

Video and audio still can be downloaded, although it takes really long time to draw download options dialogue

Issue does not affect all videos, but is not limited to a video provided.

Issue can be cleared by app restart

## Exception
* __User Action:__ play stream
* __Request:__ Loading failed for [Pipeline Caverns - Threat Theme (Rain World)]: https://www.youtube.com/watch?v=ZSEF1ugUof0
* __Content Country:__ UA
* __Content Language:__ uk-UA
* __App Language:__ uk_UA
* __Service:__ YouTube
* __Version:__ 0.24.1
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.player.mediasource.FailedMediaSource$MediaSourceResolutionException: Unable to resolve source from stream info. URL: https://www.youtube.com/watch?v=ZSEF1ugUof0, audio count: 3, video count: 12, 2
	at org.schabi.newpipe.player.playback.MediaSourceManager.lambda$getLoadedMediaSource$3(MediaSourceManager.java:439)
	at org.schabi.newpipe.player.playback.MediaSourceManager.$r8$lambda$GiL2pCn9PgSZNVk872SsYVyH27I(Unknown Source:0)
	at org.schabi.newpipe.player.playback.MediaSourceManager$$ExternalSyntheticLambda4.apply(Unknown Source:6)
	at io.reactivex.rxjava3.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:58)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnError$DoOnError.onSuccess(SingleDoOnError.java:52)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.onSuccess(SingleSubscribeOn.java:68)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle$ToSingleMaybeSubscriber.onSuccess(MaybeToSingle.java:83)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onNext(FlowableElementAtMaybe.java:80)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:136)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15868)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4813)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```
</details>
<hr>

### Affected Android/Custom ROM version

DoT OS 5.2.1

### Affected device model

Mi 9t

### Additional information

I am using Sponsor Block fork, but I am not sure that it is related. I will duplicate issue there.

**Comment by opusforlife2** [comment]
> but I am not sure that it is related

First make sure, so that you don't create extra work for maintainers of both projects?

**Comment by 0Karakurt0** [comment]
Can't reproduce it anymore

**Comment by 0Karakurt0** [comment]
New findings: it resets on restart and affects smaller channels in the first place. Catched the fail 3 times on [this channel](https://www.youtube.com/channel/UC4nFHK8e3q8paWYzGEFXT_w) already.

**Comment by opusforlife2** [comment]
Fiddle with it a little to see what the best steps are to reliably reproduce it?

**Comment by 0Karakurt0** [comment]
It really seems random. But it does not affect upstream built, at least not that I could catch it.

My current guess is that it is somewhat related to video struggling to load on slow connection, but this time I'm definitely not limited by internet

**Comment by AudricV** [comment]
This is likely an issue with the generation of a DASH manifest for a YouTube OTF stream. If you get this by any chance again, could you collect logs using ADB's logcat? The error should be also logged on release builds, as you can see [here](https://github.com/TeamNewPipe/NewPipe/blob/aad5e26f31d52566a0b74b73d3aaa531a4695d7a/app/src/main/java/org/schabi/newpipe/player/resolver/PlaybackResolver.java#L455-456).

**Comment by 0Karakurt0** [comment]
I think [I have got the log](http://0x0.st/o5_5.txt) , but I am definitely not the one to make sense of it.

how:

- Met another video with same symptoms
- `adb shell`
- `pgrep newpipe`
- `logcat --pid 30050 > logfile`
- *switched from Termux, re-tried video a couple of times*
- ^C

**Comment by 0Karakurt0** [comment]
Met it on completely different video, and yet caught another one in a row on the same channel as above. Decided to check.
And that somewhy fixed one before that...

Only thing connecting all cases is that they are all somewhat small channels. ~200 views on both videos I just mentioned.

**Comment by 0Karakurt0** [comment]
Turning off "Skipping sponsors" or addind to a whitelist fid not help

**Comment by AudricV** [comment]
Unfortunately, the log doesn't give anything useful, except the same stack trace and other stacktraces not related to app components, but AndroidX/JetPack ones used in the app.

What is the quality and the format you try to play when you get the error?

**Comment by 0Karakurt0** [comment]
> What is the quality and the format you try to play when you get the error

The defaults, as menu renders only after the error. I use 720p and WebM, but switching to mpeg did not help.

**Comment by 0Karakurt0** [comment]
I don't have hardware for Android Studio (what a funny thing to say...), but I will give it a try on dev build

**Comment by 0Karakurt0** [comment]
Ah, wait, there is no pre-built dev version, is it?

**Comment by AudricV** [comment]
There are built debug versions from the dev branch, see https://github.com/TeamNewPipe/NewPipe/actions/workflows/ci.yml?query=branch%3Adev.

**Comment by 0Karakurt0** [comment]
Haven't had time to get a dev version (and also didn't found it at the time), but this time my issue happened mid-video.
