### ISSUE TITLE
unable to launch fullscreen

### ISSUE THREAD

**Issue by sjamali25** [TeamNewPipe/NewPipe#9396]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.2.41

### Steps to reproduce the bug

1. Open any video
2. Tap fullscreen
3. Wait for loading screen (forever)
4. Press Back Button

### Expected behavior

play the video in fullscreen

### Actual behavior

loading video infinitely in fullscreen
pressing back crashs app

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.24.1
* __OS:__ Linux Android 6.0.1 - 23
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke interface method 'void android.view.IWindowSession.performDeferredDestroy(android.view.IWindow)' on a null object reference
	at android.view.SurfaceView.updateWindow(SurfaceView.java:616)
	at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:239)
	at android.view.View.dispatchDetachedFromWindow(View.java:14561)
	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3063)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4603)
	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4576)
	at android.view.ViewGroup.removeView(ViewGroup.java:4507)
	at org.schabi.newpipe.player.ui.MainPlayerUi.removeViewFromParent(MainPlayerUi.java:208)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$tryAddVideoPlayerView$18(VideoDetailFragment.java:1340)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.$r8$lambda$ZzjLKhR2Gonsds2l69UGxn_Rrzc(VideoDetailFragment.java)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda37.accept(R8$$SyntheticClass)
	at j$.util.Optional.ifPresent(SourceFile)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$tryAddVideoPlayerView$19(VideoDetailFragment.java:1336)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.$r8$lambda$LHqsaPsx9z979dNc2_7Xw3h43AY(VideoDetailFragment.java)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda36.run(R8$$SyntheticClass)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 6.0.1

### Affected device model

Samesung galaxy note 2

### Additional information

only can play video in mini player
when i try to open any video in fullscreen it keeps loading infinitely
and if i go back from fullscreen it crashes the app

**Comment by sjamali25** [comment]
i cleared app data and imported database (from app settings) without importing settings
it worked

**Comment by mart-hill** [comment]
> i cleared app data and imported database (from app settings) without importing settings it worked

AndroidTV 11 doesn't even allow saving a backup, nor a read file access, so it's a no-go.
