### ISSUE TITLE
Unrecoverable player error while switching between audio and video 

### ISSUE THREAD

**Issue by killerrook** [TeamNewPipe/NewPipe#9412]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1

### Steps to reproduce the bug

1. Start playing any video in background
2. Try to switch from audio to video 
3. See unrecoverable error occurred toast with following error report.

Note: this doesn't happens all the time but once you switch between audio and video 2-3times it occurs every time. Notheless pretty inconsistent.

Note2:The issue only occurs if you are trying to switch from audio to video.

### Expected behavior

Player should successfully switch between video and audio 

### Actual behavior

Unrecoverable player error occurs

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_DECODER_INIT_FAILED] occurred while playing https://www.youtube.com/watch?v=tuLCbyu-Fpo
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.24.1
* __OS:__ Linux OPPO/CPH1861/CPH1861:9/PPR1.180610.011/1587903909:user/release-keys 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(null, null, null, audio/raw, null, -1, null, [-1, -1, -1.0], [2, 44100]), format_supported=NO
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:566)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:226)
	at android.os.HandlerThread.run(HandlerThread.java:65)
Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.google.raw.decoder, Format(null, null, null, audio/raw, null, -1, null, [-1, -1, -1.0], [2, 44100])
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1030)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecOrBypass(MediaCodecRenderer.java:546)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1450)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:877)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.readSourceOmittingSampleData(MediaCodecRenderer.java:963)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:779)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
	... 3 more
Caused by: android.media.MediaCodec$CodecException: Error 0x80001001
	at android.media.MediaCodec.native_configure(Native Method)
	at android.media.MediaCodec.configure(MediaCodec.java:1960)
	at android.media.MediaCodec.configure(MediaCodec.java:1889)
	at com.google.android.exoplayer2.mediacodec.SynchronousMediaCodecAdapter$Factory.createAdapter(SynchronousMediaCodecAdapter.java:51)
	at com.google.android.exoplayer2.mediacodec.DefaultMediaCodecAdapterFactory.createAdapter(DefaultMediaCodecAdapterFactory.java:110)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:1108)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodecWithFallback(MediaCodecRenderer.java:1019)
	... 10 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Color OS v6.0(android 9) Non rooted

### Affected device model

Oppo Realme 1 CPH1861

### Additional information

Already tried clearing cache but no luck.

**Comment by av01d1ngx4** [comment]
The error message indicates that a video codec was not properly initialized during viewing. It appears that the decoder "`OMX.google.raw.decoder`" did not correctly initialize.

This could be due to a number of factors, such as an unsupported video file, a problem with the device's hardware or software, or a problem with the ExoPlayer library itself.

**Comment by ShareASmile** [comment]
@killerrook , Would you try to reproduce it in latest version 0.26.1 ?
