### ISSUE TITLE
App crushing as soon as I press play on a video 

### ISSUE THREAD

**Issue by Achilles96** [TeamNewPipe/NewPipe#9490]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

On the latest one,  it's version 1 I believe 

### Steps to reproduce the bug

Just press any video 

### Expected behavior

Play the video 

### Actual behavior

The app crashes 

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 1
* __OS:__ Linux samsung/gta4lwifieea/gta4lwifi:12/SP1A.210812.016/T500XXU3CVG4:user/release-keys 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalArgumentException: com.newpipe.protube: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:382)
	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:673)
	at android.app.PendingIntent.getBroadcast(PendingIntent.java:660)
	at org.schabi.newpipe.player.notification.NotificationUtil.createNotification(NotificationUtil.java:123)
	at org.schabi.newpipe.player.notification.NotificationUtil.createNotificationAndStartForeground(NotificationUtil.java:170)
	at org.schabi.newpipe.player.notification.NotificationPlayerUi.initPlayer(NotificationPlayerUi.java:32)
	at org.schabi.newpipe.player.Player$$ExternalSyntheticLambda23.accept(Unknown Source:2)
	at j$.util.Iterator$-CC.$default$forEachRemaining(SourceFile:2)
	at j$.util.Iterator$-EL.forEachRemaining(Unknown Source:10)
	at j$.util.Y.forEachRemaining(Unknown Source:24)
	at j$.util.stream.l2.forEachOrdered(Unknown Source:10)
	at org.schabi.newpipe.player.ui.PlayerUiList.call(PlayerUiList.java:88)
	at org.schabi.newpipe.player.Player.initPlayer(Player.java:522)
	at org.schabi.newpipe.player.Player.initPlayback(Player.java:487)
	at org.schabi.newpipe.player.Player.lambda$handleIntent$2(Player.java:425)
	at org.schabi.newpipe.player.Player.$r8$lambda$1PcYbMVI_TTEfmKKifNTvbiXL8A(Unknown Source:0)
	at org.schabi.newpipe.player.Player$$ExternalSyntheticLambda0.run(Unknown Source:16)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeCallbackObserver.onComplete(MaybeCallbackObserver.java:93)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeObserveOn$ObserveOnMaybeObserver.run(MaybeObserveOn.java:105)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android  12

### Affected device model

Samsung tab a7

**Comment by AudricV** [comment]
> com.newpipe.protube

Uninstall this app immediately. You are using a fake NewPipe clone. Use instead **the official one, which you can find with the sources listed on [the README of the repository](https://github.com/TeamNewPipe/NewPipe#installation-and-updates)**.

More info about our official sources on this Reddit post: https://teddit.net/r/NewPipe/comments/xzx997/reminder_only_download_newpipe_from_official/

(By the way, the issue is related to targeting Android 12 or above and due to `PendingIntent` flags, as you can see in the stacktrace. It is already fixed for us, as we added these flags recently and we are not targeting this version yet).
