### ISSUE TITLE
Crash while opening another Video while Playing a Video

### ISSUE THREAD

**Issue by materialred** [TeamNewPipe/NewPipe#9509]
### Checklist

- [x] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1

### Steps to reproduce the bug

1. Play any Video in full screen
2. Open another video

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ DE
* __Content Language:__ de-DE
* __App Language:__ de_DE
* __Service:__ none
* __Version:__ 0.24.1
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start service org.schabi.newpipe.player.PlayerService@d56236 with Intent { cmp=org.schabi.newpipe/.player.PlayerService (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.schabi.newpipe.player.Player.handleIntent(android.content.Intent)' on a null object reference
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4703)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2181)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.schabi.newpipe.player.Player.handleIntent(android.content.Intent)' on a null object reference
	at org.schabi.newpipe.player.PlayerService.onStartCommand(PlayerService.java:76)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4685)
	... 9 more

```
</details>
<hr>

### Affected Android/Custom ROM version

crDroid 9 (Android 13)

### Affected device model

Samsung Galaxy A20E

### Additional information

Phone must be in Landscape

**Comment by opusforlife2** [comment]
Does this happen on a different ROM/OS?

**Comment by materialred** [comment]
It only happens in crDroid.

**Comment by opusforlife2** [comment]
Then it is a crDroid bug. Follow their changelog or bug tracker to see if it's been fixed or reported already. Otherwise, you could consider reporting this yourself.

**Comment by materialred** [comment]
Thankyou
