### ISSUE TITLE
Play a video in a popup when the network is off, then the app will be not responding

### ISSUE THREAD

**Issue by Kobayashi-996** [TeamNewPipe/NewPipe#9529]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1 and 0.23.3

### Steps to reproduce the bug

1. Open the app and go to the main page "Trending"
2. After the page finishes loading, **turn off the network of the phone (for example, open flight mode)**
3. Long Click one video
4. Click "Start playing in a popup", the video would keep loading and soon the app isn't responding

### Expected behavior

For example hint network error.

### Actual behavior

The app isn't responding.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/120108516/206873802-3331e803-835a-4261-8784-da526b2cd4f1.mp4

### Logs

ANR in org.schabi.newpipe
    PID: 26591
    Reason: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{96e480e u0 org.schabi.newpipe/.player.PlayerService}

### Affected Android/Custom ROM version

Android 9.0

### Affected device model

Google Pixel 2

### Additional information

If I click "X" instead of waiting when the video is loading without network, the app would immediately crash and then get this:

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.24.1
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{1a62810 u0 org.schabi.newpipe/.player.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1737)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```
</details>
<hr>

**Comment by AudricV** [comment]
They still have the same origin though. Could you look at https://github.com/TeamNewPipe/NewPipe/issues/9358#issuecomment-1722546621 and test the debug APK linked to see if the issue is fixed? Thanks in advance.

**Comment by Kobayashi-996** [comment]
I have tried the app in the link and found that the app not crash any more in the aforementioned situation. I think the issue is fixed. Thank you very much!
