### ISSUE TITLE
Crash when long click on "Popup" 

### ISSUE THREAD

**Issue by pratyaksh1610** [TeamNewPipe/NewPipe#9556]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1

### Steps to reproduce the bug

1. Open any channel.
2. Long press on "Popup" below "Subscribe".
3. App crashes.

### Expected behavior

App should not crash.

### Actual behavior

App crashes.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/76740999/208230652-f8404bb9-1c18-4d25-a470-824295e8e7b4.mp4

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.24.1
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start service org.schabi.newpipe.player.PlayerService@aadfb27 with Intent { cmp=org.schabi.newpipe.debug/org.schabi.newpipe.player.PlayerService (has extras) }: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@f0c3896 -- permission denied for window type 2038
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4344)
	at android.app.ActivityThread.access$1800(ActivityThread.java:237)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1951)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@f0c3896 -- permission denied for window type 2038
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1092)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:409)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:109)
	at org.schabi.newpipe.player.ui.PopupPlayerUi.initPopup(PopupPlayerUi.java:129)
	at org.schabi.newpipe.player.ui.PopupPlayerUi.setupAfterIntent(PopupPlayerUi.java:99)
	at org.schabi.newpipe.player.Player$$ExternalSyntheticLambda28.accept(Unknown Source:2)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1390)
	at java.util.stream.ReferencePipeline$Head.forEachOrdered(ReferencePipeline.java:614)
	at org.schabi.newpipe.player.ui.PlayerUiList.call(PlayerUiList.java:88)
	at org.schabi.newpipe.player.Player.handleIntent(Player.java:443)
	at org.schabi.newpipe.player.PlayerService.onStartCommand(PlayerService.java:76)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4326)
	... 8 more

```
</details>
<hr>

**Comment by opusforlife2** [comment]
Have you given it the display over other apps permission?

**Comment by pratyaksh1610** [comment]
@opusforlife2 If we only `click` on popup then it asks for permission , but if we `long click` it crashes if no permission is given already, so if the user by mistake `long presses` then it would crash.
So, I think on `long click` we must ask for permission if not given.
