### ISSUE TITLE
NullPointerException when enqueueing from sparse feed

### ISSUE THREAD

**Issue by ktprograms** [TeamNewPipe/NewPipe#9609]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1

### Steps to reproduce the bug

In a subscription feed with "fast loading" enabled (where feed items from YouTube are "sparse"), have some videos playing, then enqueue one or more sparse items.
This only happens sometimes, and I'm not sure what causes it to happen/not happen sometimes.

### Expected behavior

No crash

### Actual behavior

Crash

(sorry about these short answers, what else is expected from a NullPointerException?)

## Exception
* _User Action:_ ui error
* _Request:_ ACRA report
* _Content Country:_ GB
* _Content Language:_ en-GB
* _App Language:_ en_GB
* _Service:_ none
* _Version:_ 0.24.1
* _OS:_ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
	at android.widget.Toast.makeText(Toast.java:892)
	at org.schabi.newpipe.util.NavigationHelper.enqueueOnPlayer(NavigationHelper.java:186)
	at org.schabi.newpipe.util.NavigationHelper.enqueueOnPlayer(NavigationHelper.java:200)
	at org.schabi.newpipe.info_list.dialog.StreamDialogDefaultEntry.lambda$static$2(StreamDialogDefaultEntry.java:54)
	at org.schabi.newpipe.info_list.dialog.StreamDialogDefaultEntry.$r8$lambda$HrNW3ftQD3NQNetYZjrz1JDwzD4(Unknown Source:0)
	at org.schabi.newpipe.info_list.dialog.StreamDialogDefaultEntry$$ExternalSyntheticLambda15.accept(Unknown Source:4)
	at org.schabi.newpipe.util.SparseItemUtil.lambda$fetchItemInfoIfSparse$0(SparseItemUtil.java:60)
	at org.schabi.newpipe.util.SparseItemUtil.$r8$lambda$rd2kSpgtBScfiwrztd_5JrCbEyQ(Unknown Source:0)
	at org.schabi.newpipe.util.SparseItemUtil$$ExternalSyntheticLambda2.accept(Unknown Source:4)
	at org.schabi.newpipe.util.SparseItemUtil.lambda$fetchStreamInfoAndSaveToDatabase$4(SparseItemUtil.java:121)
	at org.schabi.newpipe.util.SparseItemUtil.$r8$lambda$cfmnXoy0qdCzt8EeO-smvalxWsM(Unknown Source:0)
	at org.schabi.newpipe.util.SparseItemUtil$$ExternalSyntheticLambda0.accept(Unknown Source:6)
	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

</details>
<hr>

### Affected Android/Custom ROM version

Android 12 (Samsung OneUI 4.1)

### Affected device model

Samsung Galaxy A23

**Comment by ktprograms** [comment]
I did some looking based on the crash log, it seems to be because at `StreamDialogDefaultEntry.java:53`, `fragment.requireContext()` isn't null so it successfully fetches, but then somehow in the callback at line 54 `fragment.getContext()` is null.

**Comment by whistlingwoods** [comment]
Steps to reproduce are some clearer as documented with steps in this issue 
https://github.com/MaintainTeam/LastPipeBender/issues/11 , but as OP says it is a hit and a miss.
