### ISSUE TITLE
Resolution Dropdown Open + Rotate = Crash

### ISSUE THREAD

**Issue by Tex2002ans** [TeamNewPipe/NewPipe#9643]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1

### Steps to reproduce the bug

0) Open a video.

1) Press Play (then optionally pause).

2) Click on the resolution dropdown.

(Act as if you are choosing 1080p, 720p, etc.)

3) With resolution dropdown open:

- Rotate the screen.

Crash.

(This crashes both going from portrait -> landscape + landscape -> portrait.)

### Expected behavior

Not crash.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.24.1
* __OS:__ Linux Android 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalArgumentException: View=android.widget.PopupWindow$PopupDecorView{6241ddc V.E...... R.....ID 0,0-515,756} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:556)
	at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:445)
	at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:118)
	at android.widget.PopupWindow.update(PopupWindow.java:2210)
	at android.widget.PopupWindow.update(PopupWindow.java:2331)
	at android.widget.PopupWindow.alignToAnchor(PopupWindow.java:2501)
	at android.widget.PopupWindow.access$000(PopupWindow.java:106)
	at android.widget.PopupWindow$1.onViewAttachedToWindow(PopupWindow.java:240)
	at android.view.View.dispatchAttachedToWindow(View.java:20637)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3521)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3521)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3521)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3521)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3521)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5303)
	at android.view.ViewGroup.addView(ViewGroup.java:5089)
	at android.view.ViewGroup.addView(ViewGroup.java:5029)
	at android.view.ViewGroup.addView(ViewGroup.java:5001)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$tryAddVideoPlayerView$18(VideoDetailFragment.java:1341)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.$r8$lambda$ZzjLKhR2Gonsds2l69UGxn_Rrzc(Unknown Source:0)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda37.accept(Unknown Source:4)
	at j$.util.Optional.ifPresent(Unknown Source:4)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$tryAddVideoPlayerView$19(VideoDetailFragment.java:1336)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.$r8$lambda$LHqsaPsx9z979dNc2_7Xw3h43AY(Unknown Source:0)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda36.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8068)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 11 / OxygenOS 11.1.2.2

### Affected device model

OnePlus 6T

**Comment by seniorm0ment** [comment]
I have had issues for the past few months. 
Rotating while a video is playing causes the app to crash. I have not noticed anything as far as resolution changes go. But this is a very aggravating bug and it also doesn't save position of the video.

**Comment by GfEW** [comment]
I can confirm this still crashes in 26.1, and add to it that the crash also gets triggered with the menu to choose subtitle language rather than resolution.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ DE
* __Content Language:__ de-
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.26.1
* __OS:__ Linux Android 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalArgumentException: View=android.widget.PopupWindow$PopupDecorView{8a9026c V.E...... R.....I. 0,0-643,288} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:485)
	at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:380)
	at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:101)
	at android.widget.PopupWindow.update(PopupWindow.java:2064)
	at android.widget.PopupWindow.update(PopupWindow.java:2185)
	at android.widget.PopupWindow.alignToAnchor(PopupWindow.java:2355)
	at android.widget.PopupWindow.access$000(PopupWindow.java:106)
	at android.widget.PopupWindow$1.onViewAttachedToWindow(PopupWindow.java:220)
	at android.view.View.dispatchAttachedToWindow(View.java:18376)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3484)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3484)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3484)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3484)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3484)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3484)
	at android.view.ViewGroup.addViewInner(ViewGroup.java:5157)
	at android.view.ViewGroup.addView(ViewGroup.java:4945)
	at android.view.ViewGroup.addView(ViewGroup.java:4885)
	at android.view.ViewGroup.addView(ViewGroup.java:4858)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$tryAddVideoPlayerView$41(VideoDetailFragment.java:1244)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.$r8$lambda$s-YSZ_fvw5kK3nBMjl4uKoby47w(VideoDetailFragment.java:0)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda66.accept(R8$$SyntheticClass:0)
	at j$.util.Optional.ifPresent(Unknown Source:4)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.lambda$tryAddVideoPlayerView$42(VideoDetailFragment.java:1239)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment.$r8$lambda$S8n3OzU8HWJ8m_WwgX_142JT8Zo(VideoDetailFragment.java:0)
	at org.schabi.newpipe.fragments.detail.VideoDetailFragment$$ExternalSyntheticLambda57.run(R8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6826)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```
</details>
<hr>

**Comment by ItsHarper** [comment]
I got this error when I tapped the resolution selection button on the external display of a Razr 2024 running Android 15.
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Timestamp:__ 2025-04-26T08:28:54.007-05:00
* __Package:__ org.schabi.newpipe
* __Service:__ none
* __Version:__ 0.27.6
* __OS:__ Linux Android 15 - 35
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalArgumentException: View=android.widget.PopupWindow$PopupDecorView{ffcd113 V.E...... R.....I. 0,0-0,0} not attached to window manager
	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:626)
	at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:518)
	at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:172)
	at android.widget.PopupWindow.update(PopupWindow.java:2246)
	at android.widget.PopupWindow.update(PopupWindow.java:2371)
	at android.widget.PopupWindow.update(PopupWindow.java:2472)
	at android.widget.PopupWindow.update(PopupWindow.java:2421)
	at androidx.appcompat.widget.AppCompatPopupWindow.update(AppCompatPopupWindow.java:86)
	at androidx.appcompat.widget.ListPopupWindow.show(ListPopupWindow.java:709)
	at androidx.appcompat.view.menu.StandardMenuPopup.tryShow(StandardMenuPopup.java:201)
	at androidx.appcompat.view.menu.StandardMenuPopup.show(StandardMenuPopup.java:208)
	at androidx.appcompat.view.menu.MenuPopupHelper.showPopup(MenuPopupHelper.java:299)
	at androidx.appcompat.view.menu.MenuPopupHelper.tryShow(MenuPopupHelper.java:185)
	at androidx.appcompat.view.menu.MenuPopupHelper.show(MenuPopupHelper.java:147)
	at androidx.appcompat.widget.PopupMenu.show(PopupMenu.java:238)
	at org.schabi.newpipe.player.ui.VideoPlayerUi.onQualityClicked(VideoPlayerUi.java:1242)
	at org.schabi.newpipe.player.ui.VideoPlayerUi.$r8$lambda$kmQ-gHSpRlP8IHhy0K6BjAzObEA(VideoPlayerUi.java:0)
	at org.schabi.newpipe.player.ui.VideoPlayerUi$$ExternalSyntheticLambda10.run(R8$$SyntheticClass:0)
	at org.schabi.newpipe.player.ui.VideoPlayerUi.lambda$makeOnClickListener$27(VideoPlayerUi.java:1442)
	at org.schabi.newpipe.player.ui.VideoPlayerUi.$r8$lambda$sLz84DjfIdKegRqDuEqocysGYyg(VideoPlayerUi.java:0)
	at org.schabi.newpipe.player.ui.VideoPlayerUi$$ExternalSyntheticLambda43.onClick(R8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:8053)
	at android.view.View.performClickInternal(View.java:8030)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31429)
	at android.os.Handler.handleCallback(Handler.java:1001)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loopOnce(Looper.java:268)
	at android.os.Looper.loop(Looper.java:384)
	at android.app.ActivityThread.main(ActivityThread.java:8970)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:907)

```
</details>
<hr>
