### ISSUE TITLE
Crashing to desktop: Android 10/11, Samsung Galaxy S20FE

### ISSUE THREAD

**Issue by b1k3rdude** [TeamNewPipe/NewPipe#9652]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1

### Steps to reproduce the bug

1. open the app..
2. watch any video..
3.  New pipe will either crash while watching that video or while watching the next video

 Best way to try and replicate it is changing between videos. After a bit, an OS level pop-up shows up showing that the application is not responding, even though it still is.
 
 I have cleared the cache, same behavour.

### Screenshots/Screen recordings

![Screenshot_20230109-153552_NewPipe](https://user-images.githubusercontent.com/12858109/211347241-818d1702-dec8-4434-9725-bbdc329ad534.jpg)

### Logs

Newpipe crash 2

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.24.1
* __OS:__ Linux samsung/r8qxeea/r8q:11/RP1A.200720.012/G781BXXU4CUH5:user/release-keys 11 - 30
<details><summary><b>Crash log </b></summary><p>

```
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{44e02ec u0 org.schabi.newpipe/.player.PlayerService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2258)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 10/11 ProjectX_5g V3/4 rom.

### Affected device model

Samsung S20FE

### Additional information

I have had the same bug on Android 10 and 11.

**Comment by b1k3rdude** [comment]
@opusforlife2

thank you for looking into this.
