### ISSUE TITLE
[Nightly] Crash on Importing Database

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/NewPipe#9692]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.2 (nightly 30)

### Steps to reproduce the bug

1. Export db in NewPipe 0.24.1
2. Open NewPipe nightly and open a video / the video detail fragment
3. minimize player and Import db in current nightly

### Expected behavior

No crash

### Actual behavior

NewPipe finished the import and crashes afterwards.

### Logs

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
 at org.schabi.newpipe.local.feed.FeedFragment.onCreate$lambda-0(FeedFragment.kt:125)
 at org.schabi.newpipe.local.feed.FeedFragment.$r8$lambda$SVZC3B9xz0HrRxuxOiEkSYdQHMY(Unknown Source:0)
 at org.schabi.newpipe.local.feed.FeedFragment$$ExternalSyntheticLambda13.onSharedPreferenceChanged(Unknown Source:2)
 at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:629)
 at android.app.SharedPreferencesImpl$EditorImpl.commit(SharedPreferencesImpl.java:617)
 at org.schabi.newpipe.settings.ContentSettingsManager.loadSharedPreferences(ContentSettingsManager.kt:102)
 at org.schabi.newpipe.settings.ContentSettingsFragment.lambda$importDatabase$6$org-schabi-newpipe-settings-ContentSettingsFragment(ContentSettingsFragment.java:235)
 at org.schabi.newpipe.settings.ContentSettingsFragment$$ExternalSyntheticLambda3.onClick(Unknown Source:4)
 at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at ...
```

**Comment by Stypox** [comment]
<img width="484" alt="image" src="https://user-images.githubusercontent.com/36421898/212749058-4e2d5f69-19db-4e77-b6e7-4e21a0e17cea.png">
Here's the problem...
