### ISSUE TITLE
Issue: App crashes and stop the video on rotation while playing the video.

### ISSUE THREAD

**Issue by giwrgosmant** [TeamNewPipe/NewPipe#9705]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1

### Steps to reproduce the bug

1. Play one video.
2. Rotate your phone horizontally.
3. Rotate your phone again vertically.
4. The app crashes and it stops the video.

### Expected behavior

To rotate without an error and without stopping the video.

### Actual behavior

It crashes and it stops the video.

### Screenshots/Screen recordings

I don't remember from which version it started to happen, it been here for a while.
You can check the video I recorded at [MEGA Cloud](https://mega.nz/file/6lsTnbQY#wTWf8ntgEFIW9fcM9BkFW8LeoPCUZFu300GUI0ojpwY).

### Logs
[Logs - NewPipe - Rotation Issue.txt](https://github.com/TeamNewPipe/NewPipe/files/10461072/Logs.-.NewPipe.-.Rotation.Issue.txt)
 Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_FAILED_RUNTIME_CHECK] occurred while playing https://www.youtube.com/watch?v=jvpGKLJAvs0
* __Content Country:__ GR
* __Content Language:__ el-GR
* __App Language:__ el_GR
* __Service:__ YouTube
* __Version:__ 0.24.1
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.lang.IllegalArgumentException
	at android.media.MediaCodec.native_setSurface(Native Method)
	at android.media.MediaCodec.setOutputSurface(MediaCodec.java:2234)
	at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter$$ExternalSyntheticApiModelOutline0.m(Unknown Source:0)
	at com.google.android.exoplayer2.mediacodec.AsynchronousMediaCodecAdapter.setOutputSurface(AsynchronousMediaCodecAdapter.java:262)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutputSurfaceV23(MediaCodecVideoRenderer.java:1451)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.setOutput(MediaCodecVideoRenderer.java:646)
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.handleMessage(MediaCodecVideoRenderer.java:584)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.deliverMessage(ExoPlayerImplInternal.java:1546)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageToTarget(ExoPlayerImplInternal.java:1510)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.sendMessageInternal(ExoPlayerImplInternal.java:1485)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:521)
	... 4 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Androi 13 / crDroid 9.1 ROM

### Affected device model

POCO F1

**Comment by AudricV** [comment]
> Issue: App crashes and stop the video on rotation while playing the video.

Issue: you didn't follow the template instructions. 

Please search (better, with different keywords?) for duplicates, especially pinned posts, the next time you want to open an issue. Thank you.

**Comment by giwrgosmant** [comment]
> > Issue: App crashes and stop the video on rotation while playing the video.
> 
> Issue: you didn't follow the template instructions. 
> 
> Please search (better, with different keywords?) for duplicates, especially pinned posts, the next time you want to open an issue. Thank you.

First of all I would appreciate if you reply could be less with irony and provide much more information, I guess with the link of the duplicate? Since I think I help a lot of with translation of the app to my native language by spent much time and I just opened this issue since it's been a while without fix after couple of updates.

I searched the words "rotation" and "rotate " since this is what I encounter. I don't have time to do maths and matches with different words to find if this issue exist, and if exist you should change the title of the issue to be better recognizable.

The pinned post you mentioned, describe an issue with "Fullscreen" and "Android TV". This is not what I encounter. My issue is after I exit fullscreen with rotation.
Other issues I found was "while loading video" or "if other video is on queue" and other things.

Thanks.

**Comment by giwrgosmant** [comment]
@AudricV so you will point me the link of duplicate please to check it out?

**Comment by Symbian9** [comment]
Might be duplicate of https://github.com/TeamNewPipe/NewPipe/issues/9277
