### ISSUE TITLE
The app crashes when i go to download (I download it through F-Droid)

### ISSUE THREAD

**Issue by davidadarme** [TeamNewPipe/NewPipe#9714]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1

### Steps to reproduce the bug

1. I open youtube of revanced
2. I select the download option of the newpipe client
3. Sometimes the download details appear
4. when the download list appears it allows me to click on download but it doesn't
5. I go to the download section and there is nothing being downloaded

### Expected behavior

Download the files and show them in the download section

### Actual behavior

It does not download but the empty file is stored in the download folder

### Screenshots/Screen recordings

![Screenshot_20230122-113739_NewPipe](https://user-images.githubusercontent.com/114038362/213927897-dfb601bb-5dfb-44e0-bf10-d31f58e56cdf.jpg)
![Screenshot_20230122-113731_NewPipe](https://user-images.githubusercontent.com/114038362/213927900-e4d25dae-7540-4200-a8a6-1fb98ff5dc4a.jpg)

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.24.1
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to resume activity {org.schabi.newpipe/org.schabi.newpipe.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=554497543, result=-1, data=Intent { dat=content://com.android.externalstorage.documents/document/primary:Download/NewPipe/Avicii - Wake Me Up (Official Video).mp4 flg=0x43 }} to activity {org.schabi.newpipe/org.schabi.newpipe.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'us.shandian.giga.service.MissionState us.shandian.giga.service.DownloadManager.checkForExistingMission(org.schabi.newpipe.streams.io.StoredFileHelper)' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5230)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5269)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=554497543, result=-1, data=Intent { dat=content://com.android.externalstorage.documents/document/primary:Download/NewPipe/Avicii - Wake Me Up (Official Video).mp4 flg=0x43 }} to activity {org.schabi.newpipe/org.schabi.newpipe.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'us.shandian.giga.service.MissionState us.shandian.giga.service.DownloadManager.checkForExistingMission(org.schabi.newpipe.streams.io.StoredFileHelper)' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5864)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5197)
	... 13 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'us.shandian.giga.service.MissionState us.shandian.giga.service.DownloadManager.checkForExistingMission(org.schabi.newpipe.streams.io.StoredFileHelper)' on a null object reference
	at org.schabi.newpipe.download.DownloadDialog.checkSelectedDownload(DownloadDialog.java:803)
	at org.schabi.newpipe.download.DownloadDialog.requestDownloadSaveAsResult(DownloadDialog.java:479)
	at org.schabi.newpipe.download.DownloadDialog.$r8$lambda$vU8dKInqtm1tI_Y5_Z_v3TI7Yd8(Unknown Source:0)
	at org.schabi.newpipe.download.DownloadDialog$$ExternalSyntheticLambda0.onActivityResult(Unknown Source:4)
	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:418)
	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:375)
	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:777)
	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:140)
	at android.app.Activity.dispatchActivityResult(Activity.java:8659)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5857)
	... 14 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 11

### Affected device model

Samsung A21s

### Additional information

disable the developer option to disable all activities and privacy options

**Comment by davidadarme** [comment]
Yeah, but even I share the link to newpipe from original youtube and it doesn't work. Also, I tried downloading a video directly from newpipe and it didn't work
