### ISSUE TITLE
YouTube videos not loading due to timeout on Android 5

### ISSUE THREAD

**Issue by krlvm** [TeamNewPipe/NewPipe#9760]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

at least since version 0.23.0

### Steps to reproduce the bug

Open any YouTube video

### Expected behavior

Video itself, comments, related items and details should be loaded

### Actual behavior

Nothing is loading, after a long time there is a report about an error when loading comments due to a timeout

### Screenshots/Screen recordings

![Screenshot](https://user-images.githubusercontent.com/51774833/217748535-9e42250a-247c-4f76-b6db-e10d61398039.png)

## Exception
* __User Action:__ requested comments
* __Request:__ Start loading: https://www.youtube.com/watch?v=[...]
* __Service:__ YouTube
* __Version:__ 0.25.0
* __OS:__ Linux Android 5.1 - 22
<details><summary><b>Crash log </b></summary><p>

```
java.net.SocketTimeoutException: timeout
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:675)
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:684)
	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:143)
	at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:96)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at org.schabi.newpipe.DownloaderImpl.execute(DownloaderImpl.java:163)
	at org.schabi.newpipe.extractor.downloader.Downloader.post(Downloader.java:143)
	at org.schabi.newpipe.extractor.downloader.Downloader.postWithContentType(Downloader.java:175)
	at org.schabi.newpipe.extractor.downloader.Downloader.postWithContentTypeJson(Downloader.java:217)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getJsonPostResponse(YoutubeParsingHelper.java:1185)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.onFetchPage(YoutubeCommentsExtractor.java:264)
	at org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:39)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:29)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getCommentsInfo$7(ExtractorHelper.java:159)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$60N_-UL7E5eaxFaFO1bZZmnfwM8(ExtractorHelper.java:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda9.call(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5375)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15917)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5375)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 5.1

### Affected device model

stock AOSP firmware

### Additional information

- everything works with other supported services
- everything works fine on other Android devices (Android 7-11) connected to the same WiFi network
- clearing app data doesn't help

**Comment by krlvm** [comment]
I suspect that the problem is with the certificate - everything works with mitmproxy.

I copied all the system certificates from my Android 10 device, but it didn't help.

**Comment by krlvm** [comment]
I've managed to fix it by installing _GTS Root 1_ and _GTS CA 1C3_ certificates manually, maybe they should be included in NewPipe

Yes, it does not work on Android 7 either indeed, but fails with different error (NewPipe also was failing to play video with this error on Android 5 after certificate installation): 
```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not store JavaScript player
Caused by: org.schabi.newpipe.extractor.exceptions.ParsingException: Embedded info did not provide YouTube player js url
```

**Comment by krlvm** [comment]
GTS certificates are not included in certificate store by default and I don't have them on my Android 8+ devices on which NewPipe works normally, _GlobalSign Root CA (GlobalSign nv-sa, the one that was issued in 1998, expires in 2028)_ is the root CA for _GTS Root R1_, which is root CA for _GTS CA 1C3_, so I don't think that installing the latter was necessary. GlobalSign certificate was installed on my Android 5 device though - it is installed on all Android devices.

If I disable GlobalSign certificate on Android 10, NewPipe keeps working.

Now I've removed both certificates from Android 5 device and NewPipe still working for some reason - someone needs to confirm or deny the connection of certificates with this problem.

**Comment by ale5000-git** [comment]
I have tried on stock Lollipop (Android 5) and LineageOS Nougat (Android 7) and the latest version works perfectly, so probably the issue is in your phone or in your network (LAN firewall, Pi-hole, etc.).

**Comment by krlvm** [comment]
I don't think I have network issues - as I've said previously, everything works perfectly on the same network but on Android >= 8.

Interesting indeed

**Comment by ale5000-git** [comment]
Have you tried to factory reset the devices with problems?
Maybe it is just some corruption.

**Comment by krlvm** [comment]
I'm pretty sure that's not how it works

**Comment by krlvm** [comment]
There's no other ROMs for my device :(

Seems like the issue is resolved after copying certificates from Android 10
