### ISSUE TITLE
Tapping/clicking on an empty comment crashes the app

### ISSUE THREAD

**Issue by zachintolinux** [TeamNewPipe/NewPipe#9774]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.0

### Steps to reproduce the bug

1.  Search for the video "Tesla can't build a car" by "Louis Rossmann: RANDOM LIVE"
2. Tap/click on the empty comment
3. App should crash
4. Open the app and repeat steps 1-2
5. The error report should appear

### Expected behavior

I expected the empty comment to have full text after expanding said comment.

### Actual behavior

As I mentioned before, the app crashes when I tap on the empty comment in that video.

### Screenshots/Screen recordings

<img alt="Screenshot_20230209-130010" src="https://user-images.githubusercontent.com/63529936/217938677-70ed9b33-36e0-4468-9b04-1e40bbbe25ef.png" width=270 />

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.25.0
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
java.lang.StringIndexOutOfBoundsException: length=0; index=-1
	at java.lang.String.charAt(Native Method)
	at org.schabi.newpipe.info_list.holder.CommentsMiniInfoItemHolder.toggleEllipsize(CommentsMiniInfoItemHolder.java:255)
	at org.schabi.newpipe.info_list.holder.CommentsMiniInfoItemHolder.lambda$updateFromItem$1(CommentsMiniInfoItemHolder.java:145)
	at org.schabi.newpipe.info_list.holder.CommentsMiniInfoItemHolder.$r8$lambda$0fvlfbx4UGcHQ9bF6ke9G9oLHSM(CommentsMiniInfoItemHolder.java:0)
	at org.schabi.newpipe.info_list.holder.CommentsMiniInfoItemHolder$$ExternalSyntheticLambda1.onClick(R8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:7506)
	at android.view.View.performClickInternal(View.java:7483)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29341)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7879)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 13/GrapheneOS

### Affected device model

Google Pixel 6a

### Additional information

DISCLAIMER: This is the first time I've encountered an issue like this.

Keep that in mind as this could be either a one-time occurrence or one of many randomized occurrences across multiple videos.

**Comment by janTasija** [comment]
the comment text missing also seems to be being fixed, they got broken because they have hashtags

https://github.com/TeamNewPipe/NewPipeExtractor/pull/1021

**Comment by AudricV** [comment]
> the comment text missing also seems to have been fixed in the extractor?

In fact, the fix doesn't really fix the issue, but I found how to really fix this.

Anyway, that's outside the scope of this issue: see TeamNewPipe/NewPipeExtractor#1019.
