### ISSUE TITLE
Crash when exporting database

### ISSUE THREAD

**Issue by MaxsimLionel** [TeamNewPipe/NewPipe#9826]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.0

### Steps to reproduce the bug

1. Tap Export Database

## Exception
* __User Action:__ ui error
* __Request:__ Exporting database
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.25.0
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: database is not initialized
	at org.schabi.newpipe.NewPipeDatabase.checkpoint(NewPipeDatabase.java:51)
	at org.schabi.newpipe.settings.ContentSettingsFragment.exportDatabase(ContentSettingsFragment.java:193)
	at org.schabi.newpipe.settings.ContentSettingsFragment.requestExportPathResult(ContentSettingsFragment.java:166)
	at org.schabi.newpipe.settings.ContentSettingsFragment.$r8$lambda$8bBkxkdGnhK6YvPK6sE5N6ky1yA(ContentSettingsFragment.java:0)
	at org.schabi.newpipe.settings.ContentSettingsFragment$$ExternalSyntheticLambda1.onActivityResult(R8$$SyntheticClass:0)
	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:418)
	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:375)
	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:777)
	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:140)
	at android.app.Activity.dispatchActivityResult(Activity.java:8675)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5323)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5369)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7879)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```
</details>
<hr>

### Affected Android/Custom ROM version

Linux Android 13 Graphene Latest

### Affected device model

Pixel 4a

**Comment by av01d1ngx4** [comment]
You may want to try uninstalling and reinstalling the app to see if that resolves the issue.

**Comment by Stypox** [comment]
A user said via email:

> I have the assumption that no exported backup can be exported to the same smartphones (my wife has the same) and then import the settings on the other smartphone. Then a mistake seems to happen.
Maybe that will help you at Newpipe?
