### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by CypherpunkSamurai** [TeamNewPipe/NewPipe#9828]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.0

### Steps to reproduce the bug

1. Go to documentation page
2. Follow docs
3. Implement a service
4. Kiosk null pointer. Not working
5. Spend 2 hours trying to debug
6. Turns out documentation is outdated

### Expected behavior

App works. Happy

### Actual behavior

Kiosk Null pointer.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ IN
* __Content Language:__ en-IN
* __App Language:__ en_IN
* __Service:__ none
* __Version:__ 0.25.0
* __OS:__ Linux Android 7.1.1 - 25
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.schabi.newpipe.debug/org.schabi.newpipe.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2676)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2737)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1488)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6160)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:929)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:819)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.hashCode()' on a null object reference
	at org.schabi.newpipe.util.KioskTranslator.getTranslatedKioskName(KioskTranslator.java:32)
	at org.schabi.newpipe.settings.tabs.Tab$DefaultKioskTab.getTabName(Tab.java:493)
	at org.schabi.newpipe.fragments.MainFragment.updateTitleForTab(MainFragment.java:190)
	at org.schabi.newpipe.fragments.MainFragment.onTabSelected(MainFragment.java:198)
	at com.google.android.material.tabs.TabLayout.dispatchTabSelected(TabLayout.java:1905)
	at com.google.android.material.tabs.TabLayout.selectTab(TabLayout.java:1898)
	at com.google.android.material.tabs.TabLayout.selectTab(TabLayout.java:1858)
	at com.google.android.material.tabs.TabLayout.populateFromPagerAdapter(TabLayout.java:1585)
	at com.google.android.material.tabs.TabLayout.setPagerAdapter(TabLayout.java:1569)
	at com.google.android.material.tabs.TabLayout$AdapterChangeListener.onAdapterChanged(TabLayout.java:3496)
	at androidx.viewpager.widget.ViewPager.setAdapter(ViewPager.java:549)
	at org.schabi.newpipe.fragments.MainFragment.setupTabs(MainFragment.java:170)
	at org.schabi.newpipe.fragments.MainFragment.initViews(MainFragment.java:93)
	at org.schabi.newpipe.BaseFragment.onViewCreated(BaseFragment.java:67)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3019)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1758)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2849)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2784)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:262)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:478)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:248)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1254)
	at android.app.Activity.performStart(Activity.java:6820)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2639)
	... 9 more

```
</details>
<hr>

**Comment by Stypox** [comment]
@CypherpunkSamurai could you explain what was missing from the documentation, so that it can be added? Also, if you want to open a PR on the documentation repo please do so: since you know exactly what was missing you would be able to write things faster  than me.

**Comment by CypherpunkSamurai** [comment]
Hi @Stypox 👋🏼,

Actually it's bit of a confusion, I tried several ways to implement a service without a Kiosk, yet none of them work. Which leads me to believe kiosk is now not optional.

It that the Kiosk handler is not optional anymore as [mentioned](https://teamnewpipe.github.io/documentation/03_Implement_a_service/) in the documentation.

I tried building a application with a empty Kiosk that would return a null list, relevant by the parent class function. But I'm receiving null pointer errors.

Please confirm if this is true

**Comment by Stypox** [comment]
Apparently a default kiosk is required, since in NewPipe there is a [`DefaultKioskTab`](https://github.com/TeamNewPipe/NewPipe/blob/d33229a3b862f1e53e1c9b6da9fd7216238695a7/app/src/main/java/org/schabi/newpipe/settings/tabs/Tab.java#L483) which obviously needs to access some kiosk. Adding an `if (kioskId == null) { return "" }` [here](https://github.com/TeamNewPipe/NewPipe/blob/d33229a3b862f1e53e1c9b6da9fd7216238695a7/app/src/main/java/org/schabi/newpipe/util/KioskTranslator.java#L32) would at least fix the app crash, though.

> a null list

Btw, usually it is not good practice to return a null list: just return an empty list instead. [This other code](https://github.com/TeamNewPipe/NewPipe/blob/d33229a3b862f1e53e1c9b6da9fd7216238695a7/app/src/main/java/org/schabi/newpipe/MainActivity.java#L224) would work just fine with an empty list.

**Comment by CypherpunkSamurai** [comment]
Alright, this looks like a small change, I'll try to fix this issue and hopefully add a PR

**Comment by CypherpunkSamurai** [comment]
> Adding an if (kioskId == null) { return "" } [here](https://github.com/TeamNewPipe/NewPipe/blob/d33229a3b862f1e53e1c9b6da9fd7216238695a7/app/src/main/java/org/schabi/newpipe/util/KioskTranslator.java#L32) would at least fix the app crash, though.

Ok. I tried this and the build crashes:
```gradle
FAILURE: Build completed with 2 failures.
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:runCheckstyle'.
> A failure occurred while executing org.gradle.api.plugins.quality.internal.CheckstyleAction
   > Unable to process files: [/buddy/newpipe-testing/NewPipe/app/src/test/java/org/schabi/newpipe/settings/tabs/TabsJsonHelperTest.java, /buddy/newpipe-testing/NewPipe/app/src/test/java/org/schabi/newpipe/settings/tabs/TabTest.java, /buddy/newpipe-testing/NewPipe/app/src/test/java/org/schabi/newpipe/error/ErrorActivityTest.java, /buddy/newpipe-testing/NewPipe/app/src/test/java/org/schabi/newpipe/player/playqueue/PlayQueueTest.java, /buddy/newpipe-testing/NewPipe/app/src/test/java/org/schabi/newpipe/player/playqueue/PlayQueueItemTest.java, /buddy/newpipe-testing/NewPipe/app/src/test/java/org/schabi/newpipe/util/QuadraticSliderStrategyTest.java, /buddy/newpipe-testing/NewPipe/app/src/test/java/org/schabi/newpipe/util/external_communication/TimestampExtractorTest.java, /buddy/newpipe-testing/NewPipe/app/src/test/java/org/schabi/newpipe/util/ListHelperTest.java, /buddy/newpipe-testing/NewPipe/app/src/test/java/org/schabi/newpipe/local/subscription/services/ImportExportJsonHelperTest.java, ...
```

**Comment by CypherpunkSamurai** [comment]
or a
```java
    case (null):
                return "";
```

works too :P

**Comment by CypherpunkSamurai** [comment]
@Stypox I have a question, offtopic. How can I provide referer to the url stream from StreamExtractor?

**Comment by Stypox** [comment]
I am not sure I understand what you mean

**Comment by CypherpunkSamurai** [comment]
How can I use "referer" header when the player plays from the http url?

**Comment by Stypox** [comment]
Oh ok, now it's clear. Since in [`Stream`](https://github.com/TeamNewPipe/NewPipeExtractor/blob/dev/extractor/src/main/java/org/schabi/newpipe/extractor/stream/Stream.java) there is no field that could hold headers to be used by clients (e.g. inside NewPipe), you would first need to add a `headers` field to that class, and then modify NewPipe so that is uses the field.
