### ISSUE TITLE
No internet connection error message should disappear automatically

### ISSUE THREAD

**Issue by almustaness** [TeamNewPipe/NewPipe#9831]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25

### Steps to reproduce the bug

1. Keep a video playing on the background.
2. Disconnect the internet and you will get error on the notifications. 

### Expected behavior

The notification error should disappear when internet connection is back. 

### Actual behavior

The notification error is displayed and you should remove it manually

**Comment by guyfawkes69** [comment]
I'm also getting this on my OnePlus phone

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_NETWORK_CONNECTION_TIMEOUT] occurred while playing https://www.youtube.com/watch?v=waRMnFgxbHQ
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.24.1
* __OS:__ Linux OnePlus/OnePlus8TMO/OnePlus8TMO:12/RKQ1.211119.001/Q.202211042112:user/release-keys 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:632)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:604)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: java.net.SocketTimeoutException: failed to connect to rr2---sn-qxoedn7k.googlevideo.com/74.125.159.199 (port 443) from /192.168.1.4 (port 48940) after 8000ms: isConnected failed: ETIMEDOUT (Connection timed out)
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:389)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:786)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:599)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.chunk.ContainerMediaChunk.load(ContainerMediaChunk.java:124)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.net.SocketTimeoutException: failed to connect to rr2---sn-qxoedn7k.googlevideo.com/74.125.159.199 (port 443) from /192.168.1.4 (port 48940) after 8000ms: isConnected failed: ETIMEDOUT (Connection timed out)
	at libcore.io.IoBridge.isConnected(IoBridge.java:343)
	at libcore.io.IoBridge.connectErrno(IoBridge.java:237)
	at libcore.io.IoBridge.connect(IoBridge.java:179)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
	at java.net.Socket.connect(Socket.java:646)
	at com.android.okhttp.internal.Platform.connectSocket(Platform.java:182)
	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:145)
	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.makeConnection(YoutubeHttpDataSource.java:704)
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.makeConnection(YoutubeHttpDataSource.java:548)
	at org.schabi.newpipe.player.datasource.YoutubeHttpDataSource.open(YoutubeHttpDataSource.java:383)
	... 10 more
Caused by: android.system.ErrnoException: isConnected failed: ETIMEDOUT (Connection timed out)
	at libcore.io.IoBridge.isConnected(IoBridge.java:334)
	... 33 more

```
</details>
<hr>

**Comment by u7484052** [comment]
Hi, I'm a uni student looking to gain more experience working on open-source projects. Is there any chance this issue could be assigned to me so that I could have a go at it?

**Comment by SupremeSkriptKiddie** [comment]
Yeah that's fine w me I'm a uni student too :) the app works fine the error
persists but I am using the app right now.

**Comment by u7484052** [comment]
Yeah cool, the issue seems like more of a feature than a bug but I'll implement some form of looping check anyways as it will likely be a welcome addition. Also, are you using some form of emulator to run the program or a physical device? I was planning on using android studio but also have access to an old android device if you reckon it would be better.

**Comment by SupremeSkriptKiddie** [comment]
No emulator and the error pops up Everytime. The only way that I can get
the videos to play uninterrupted while it pops up is to have the phone
locked

**Comment by SupremeSkriptKiddie** [comment]
Cool feature

**Comment by u7484052** [comment]
Yep sounds good. Also, unrelated to this issue, I am trying to build and run the app using Android Studio Giraffe, I'm using jdk 17.0.2 and for some reason when trying to run the app I get the following issue:

Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':app:debugCompileClasspath'.

There are quite a few outdated dependencies in the build file but I'm assuming they are all outdated for a reason so I don't want to change them. Any help would be much appreciated so that I can tackle another bug instead.

**Comment by SupremeSkriptKiddie** [comment]
I'm not sure what help I could give you but I recently haven't been able to
get thru more than a few seconds of a any video before the error coming and
stopping the video. I can keep restarting them but can't watch anything so
I just been using Odyssee. If you want to move on to a different bug then
go ahead but I've tried redownloading the app from fdroid and doesn't help

**Comment by u7484052** [comment]
My bad, my question wasn't related to this issue in particular and was just a general question that I was hoping that @opusforlife2  would be able to help me with.
