### ISSUE TITLE
crash on suggest

### ISSUE THREAD

**Issue by starenka** [TeamNewPipe/NewPipe#9857]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.0

### Steps to reproduce the bug

search

## Exception
* __User Action:__ get suggestions
* __Request:__ italia squisita aglio olio
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.25.0
* __OS:__ Linux samsung/beyond0lteeea/beyond0:12/SP1A.210812.016/G970FXXUGHVJ5:user/release-keys 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to read from field 'androidx.recyclerview.widget.RecyclerView org.schabi.newpipe.databinding.FragmentSearchBinding.suggestionsList' on a null object reference
	at org.schabi.newpipe.fragments.list.search.SearchFragment.lambda$handleSuggestions$23(SearchFragment.java:944)
	at org.schabi.newpipe.fragments.list.search.SearchFragment.$r8$lambda$EfAlcDqpqGgTnDxlaHMRg6m2ELs(SearchFragment.java:0)
	at org.schabi.newpipe.fragments.list.search.SearchFragment$$ExternalSyntheticLambda21.run(R8$$SyntheticClass:0)
	at androidx.recyclerview.widget.AsyncListDiffer.onCurrentListChanged(AsyncListDiffer.java:379)
	at androidx.recyclerview.widget.AsyncListDiffer.submitList(AsyncListDiffer.java:284)
	at androidx.recyclerview.widget.ListAdapter.submitList(ListAdapter.java:146)
	at org.schabi.newpipe.fragments.list.search.SearchFragment.handleSuggestions(SearchFragment.java:943)
	at org.schabi.newpipe.fragments.list.search.SearchFragment.lambda$initSuggestionObserver$14(SearchFragment.java:784)
	at org.schabi.newpipe.fragments.list.search.SearchFragment.$r8$lambda$HpL953c8k1JPyNfRPyrPNskf55Q(SearchFragment.java:0)
	at org.schabi.newpipe.fragments.list.search.SearchFragment$$ExternalSyntheticLambda14.accept(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:202)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:256)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8751)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

```
</details>
<hr>

**Comment by av01d1ngx4** [comment]
There is something wrong with `RecyclerView`
