### ISSUE TITLE
Opening video quality menu crashes on Quest

### ISSUE THREAD

**Issue by DevanWolf** [TeamNewPipe/NewPipe#9862]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.24.1

### Steps to reproduce the bug

1. Play any video
2. Open the video quality/resolution setting menu (e.g. 720p)

### Expected behavior

The quality list menu is supposed to show up as if it were viewing on other devices (phone/tablet).

### Actual behavior

App crash

### Logs

Opening video resolution menu on Quest crashes app
## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.24.1
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log</b></summary><p>

```
android.view.WindowManager$BadTokenException: Unable to add window -- token android.view.ViewRootImpl$W@5e5b01d is not valid; is your activity running?
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:941)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:387)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:95)
	at android.widget.PopupWindow.invokePopup(PopupWindow.java:1577)
	at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1424)
	at androidx.appcompat.widget.AppCompatPopupWindow.showAsDropDown(AppCompatPopupWindow.java:77)
	at androidx.core.widget.PopupWindowCompat$Api19Impl.showAsDropDown(PopupWindowCompat.java:247)
	at androidx.core.widget.PopupWindowCompat.showAsDropDown(PopupWindowCompat.java:71)
	at androidx.appcompat.widget.ListPopupWindow.show(ListPopupWindow.java:757)
	at androidx.appcompat.view.menu.CascadingMenuPopup.showMenu(CascadingMenuPopup.java:487)
	at androidx.appcompat.view.menu.CascadingMenuPopup.show(CascadingMenuPopup.java:266)
	at androidx.appcompat.view.menu.MenuPopupHelper.showPopup(MenuPopupHelper.java:299)
	at androidx.appcompat.view.menu.MenuPopupHelper.tryShow(MenuPopupHelper.java:185)
	at androidx.appcompat.view.menu.MenuPopupHelper.show(MenuPopupHelper.java:147)
	at androidx.appcompat.widget.PopupMenu.show(PopupMenu.java:238)
	at org.schabi.newpipe.player.ui.VideoPlayerUi.onQualityClicked(VideoPlayerUi.java:1165)
	at org.schabi.newpipe.player.ui.VideoPlayerUi.onClick(VideoPlayerUi.java:1369)
	at org.schabi.newpipe.player.ui.MainPlayerUi.onClick(MainPlayerUi.java:863)
	at android.view.View.performClick(View.java:7259)
	at android.view.View.performClickInternal(View.java:7236)
	at android.view.View.access$3600(View.java:801)
	at android.view.View$PerformClick.run(View.java:27892)
	at android.os.Handler.handleCallback(Handler.java:886)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7436)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 10 / Meta Quest Platform

### Affected device model

Meta Quest 2

### Additional information

Device is an HMD

**Comment by DevanWolf** [comment]
Same problem on that latest version, even the caption menu does it.

**Comment by av01d1ngx4** [comment]
This error notice indicates that an attempt was made to add a new window to the currently running activity, but the activity may have been terminated or was not operating when the window was added. 

This error can occur in a variety of situations, including attempting to display a dialog or a popup window after the activity has been destroyed, or attempting to display a popup window from a background thread.

**Comment by DevanWolf** [comment]
Bug is still present in the latest version (v0.27.0)

**Comment by DevanWolf** [comment]
I did (assuming it's the same log).

**Comment by DevanWolf** [comment]
> > Update your description to state the correct version.
> 
> ^
> 
> Also, replace that old crash report with one from the latest version, just so we can be sure the log is the same.

Bug is still present in 0.27.2
