### ISSUE TITLE
Could not parse website 

### ISSUE THREAD

**Issue by Lariea** [TeamNewPipe/NewPipe#9888]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.0

### Steps to reproduce the bug

Open newpipe, go to saved playlists, click play all

## Exception
* __User Action:__ requested comments
* __Request:__ Start loading: https://www.youtube.com/watch?v=Bs5QGN-zhwM
* __Content Country:__ AU
* __Content Language:__ en-AU
* __App Language:__ en_AU
* __Service:__ YouTube
* __Version:__ 0.25.0
* __OS:__ Linux Android 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get comment text
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsInfoItemExtractor.getCommentText(YoutubeCommentsInfoItemExtractor.java:194)
	at org.schabi.newpipe.extractor.comments.CommentsInfoItemsCollector.extract(CommentsInfoItemsCollector.java:29)
	at org.schabi.newpipe.extractor.comments.CommentsInfoItemsCollector.commit(CommentsInfoItemsCollector.java:110)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor$$ExternalSyntheticLambda3.accept(R8$$SyntheticClass:0)
	at j$.util.stream.V.accept(Unknown Source:2)
	at j$.util.stream.e2.accept(SourceFile:0)
	at j$.util.stream.e2.accept(SourceFile:0)
	at j$.util.stream.e2.accept(SourceFile:0)
	at j$.util.a.forEachRemaining(SourceFile:0)
	at j$.util.stream.c.Z(SourceFile:0)
	at j$.util.stream.c.t0(Unknown Source:10)
	at j$.util.stream.W.v(SourceFile:0)
	at j$.util.stream.c.w0(SourceFile:0)
	at j$.util.stream.m2.forEach(SourceFile:0)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.collectCommentsFrom(YoutubeCommentsExtractor.java:248)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.extractComments(YoutubeCommentsExtractor.java:191)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getInitialPage(YoutubeCommentsExtractor.java:58)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:21)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:48)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:29)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getCommentsInfo$7(ExtractorHelper.java:159)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$60N_-UL7E5eaxFaFO1bZZmnfwM8(ExtractorHelper.java:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda9.call(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5375)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15917)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5375)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: org.schabi.newpipe.extractor.exceptions.ParsingException: canonicalBaseUrl is null and browseId is not a channel ("{browseId=FEhashtag, params=6gUNCglzaW1zNGV2ZXIYAQ%3D%3D}")
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getUrlFromNavigationEndpoint(YoutubeParsingHelper.java:896)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getTextFromObject(YoutubeParsingHelper.java:949)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsInfoItemExtractor.getCommentText(YoutubeCommentsInfoItemExtractor.java:187)
	... 46 more

```
</details>
<hr>

**Comment by AudricV** [comment]
This issue has been already fixed and the fix will be shipped in 0.25.1.
