### ISSUE TITLE
Error when loading some video comment (and crash when expanding the pinned one)

### ISSUE THREAD

**Issue by mfranceschi** [TeamNewPipe/NewPipe#9912]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.0

### Steps to reproduce the bug

1. Open the video  https://youtu.be/thIQaUljNoE

An error is shown at the bottom "Désolé, quelque chose s'est mal passé"

2. Go to the comments tab 

The pinned comment is shown empty (see screenshot).

3. Expand the pinned comment

Crash 

### Screenshots/Screen recordings

https://postimg.cc/cg01jyLr

## Exception
* __User Action:__ requested comments
* __Request:__ Start loading: https://www.youtube.com/watch?v=thIQaUljNoE
* __Content Country:__ FR
* __Content Language:__ fr-
* __App Language:__ fr_FR
* __Service:__ YouTube
* __Version:__ 0.25.0
* __OS:__ Linux samsung/beyond0lteeea/beyond0:12/SP1A.210812.016/G970FXXUGHVJ5:user/release-keys 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
org.schabi.newpipe.extractor.exceptions.ParsingException: Could not get comment text
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsInfoItemExtractor.getCommentText(YoutubeCommentsInfoItemExtractor.java:194)
	at org.schabi.newpipe.extractor.comments.CommentsInfoItemsCollector.extract(CommentsInfoItemsCollector.java:29)
	at org.schabi.newpipe.extractor.comments.CommentsInfoItemsCollector.commit(CommentsInfoItemsCollector.java:110)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor$$ExternalSyntheticLambda3.accept(R8$$SyntheticClass:0)
	at j$.util.stream.V.accept(Unknown Source:2)
	at j$.util.stream.e2.accept(SourceFile:0)
	at j$.util.stream.e2.accept(SourceFile:0)
	at j$.util.stream.e2.accept(SourceFile:0)
	at j$.util.a.forEachRemaining(SourceFile:0)
	at j$.util.stream.c.Z(SourceFile:0)
	at j$.util.stream.c.t0(Unknown Source:10)
	at j$.util.stream.W.v(SourceFile:0)
	at j$.util.stream.c.w0(SourceFile:0)
	at j$.util.stream.m2.forEach(SourceFile:0)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.collectCommentsFrom(YoutubeCommentsExtractor.java:248)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.extractComments(YoutubeCommentsExtractor.java:191)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsExtractor.getInitialPage(YoutubeCommentsExtractor.java:58)
	at org.schabi.newpipe.extractor.utils.ExtractorHelper.getItemsPageOrLogError(ExtractorHelper.java:21)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:48)
	at org.schabi.newpipe.extractor.comments.CommentsInfo.getInfo(CommentsInfo.java:29)
	at org.schabi.newpipe.util.ExtractorHelper.lambda$getCommentsInfo$7(ExtractorHelper.java:159)
	at org.schabi.newpipe.util.ExtractorHelper.$r8$lambda$60N_-UL7E5eaxFaFO1bZZmnfwM8(ExtractorHelper.java:0)
	at org.schabi.newpipe.util.ExtractorHelper$$ExternalSyntheticLambda9.call(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:43)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromSingle.subscribeActual(MaybeFromSingle.java:41)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5375)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.drain(MaybeConcatArray.java:153)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray$ConcatMaybeObserver.request(MaybeConcatArray.java:78)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe$ElementAtSubscriber.onSubscribe(FlowableElementAtMaybe.java:66)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeConcatArray.subscribeActual(MaybeConcatArray.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15917)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableElementAtMaybe.subscribeActual(FlowableElementAtMaybe.java:36)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5375)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeToSingle.subscribeActual(MaybeToSingle.java:46)
	at io.reactivex.rxjava3.core.Single.subscribe(Single.java:4855)
	at io.reactivex.rxjava3.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: org.schabi.newpipe.extractor.exceptions.ParsingException: canonicalBaseUrl is null and browseId is not a channel ("{browseId=FEhashtag, params=6gUGCgJhZBgB}")
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getUrlFromNavigationEndpoint(YoutubeParsingHelper.java:896)
	at org.schabi.newpipe.extractor.services.youtube.YoutubeParsingHelper.getTextFromObject(YoutubeParsingHelper.java:949)
	at org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeCommentsInfoItemExtractor.getCommentText(YoutubeCommentsInfoItemExtractor.java:187)
	... 46 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 12

### Affected device model

Samsung Galaxy S10e

**Comment by mfranceschi** [comment]
In what way did I ignore the template?

**Comment by Frivolous2** [comment]
Happens to me as well. 

https://m.youtube.com/watch?v=1GY3HTZE5R0

https://user-images.githubusercontent.com/57101103/225280980-f8080943-6e4c-4872-a0a3-98a565e60aaf.mp4


## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ BG
* __Content Language:__ en-
* __App Language:__ en
* __Service:__ none
* __Version:__ 0.25.0
* __OS:__ Linux samsung/a52sxqeea/a52sxq:13/TP1A.220624.014/A528BXXU1DWA4:user/release-keys 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
java.lang.StringIndexOutOfBoundsException: length=0; index=-1
	at java.lang.String.charAt(Native Method)
	at org.schabi.newpipe.info_list.holder.CommentsMiniInfoItemHolder.toggleEllipsize(CommentsMiniInfoItemHolder.java:255)
	at org.schabi.newpipe.info_list.holder.CommentsMiniInfoItemHolder.lambda$updateFromItem$1(CommentsMiniInfoItemHolder.java:145)
	at org.schabi.newpipe.info_list.holder.CommentsMiniInfoItemHolder.$r8$lambda$0fvlfbx4UGcHQ9bF6ke9G9oLHSM(CommentsMiniInfoItemHolder.java:0)
	at org.schabi.newpipe.info_list.holder.CommentsMiniInfoItemHolder$$ExternalSyntheticLambda1.onClick(R8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:7881)
	at android.view.View.performClickInternal(View.java:7858)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30863)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```
</details>
<hr>

**Comment by mfranceschi** [comment]
- not pointing at the original one, since this is a duplicate (and I've searched for another similar thread without success)
- closing the issue straight away without any message
- reporting the person below me as spam
Is not a way to encourage bug reports.
