### ISSUE TITLE
Regular crashes playing Soundcloud playlists

### ISSUE THREAD

**Issue by ChemoCosmo** [TeamNewPipe/NewPipe#9925]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.0

### Steps to reproduce the bug

1. Start Playlist, for example https://soundcloud.com/user-428882203/sets/grim-dark-warhammer-40k-40000
2. Wait a couple of songs
3. Music stops
4. Look at Error message

### Expected behavior

Playlist should be played without interruptions and errors

### Actual behavior

NewPipe throws an error playing Soundcloud playlists. Observed with at least 3 different playlists. NewPipe plays multiple songs until it suddenly stops after one song and shows an error notification. This happens constantly after 10-30 minutes. 

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_BAD_HTTP_STATUS] occurred while playing https://soundcloud.com/graham-plowman/for-the-emperor-warhammer-40k
* __Content Country:__ DE
* __Content Language:__ de-DE
* __App Language:__ de_DE
* __Service:__ SoundCloud
* __Version:__ 0.25.0
* __OS:__ Linux Android 10 - 29
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:632)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:604)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:404)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:258)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:786)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:599)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1005)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 10 - e/OS 1.5q

### Affected device model

Fairphone 3

**Comment by av01d1ngx4** [comment]
Your internet connection could be the root of the problem. I attempted to replicate your issue, but nothing occurred.

**Comment by ChemoCosmo** [comment]
I'll try with mobile data (instead of wifi) next and let you know if the issue doesn't occur anymore.

**Comment by ChemoCosmo** [comment]
Problem also occurs with mobile data, which is usually very reliable.

`InvalidResponseCodeException: Response code: 403` doesn't really sound like a timed out connection to me.

I will update my OS in the next days. Maybe that does the trick...

**Comment by ChemoCosmo** [comment]
Came back to tell, that an update to Android 11 did not fix the issue.

**Comment by davidasunmo** [comment]
This is a bug I've also been experiencing for a while, also getting basically the exact same stack trace too. Idk if I get it for YT videos as I mostly have soundcloud in my playlists, but it happens multiple times a day.

**Comment by ChemoCosmo** [comment]
In that case it would be nice if Newpipe would just resume the playlist in case one song is not accessible.

**Comment by simonai1254** [comment]
For me this issue occurs as well, regardless if on WiFi or mobile data, multiple times a day. I mostly listen in the background, not sure if it happens in the normal mode as often/at all. 

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_IO_BAD_HTTP_STATUS] occurred while playing https://soundcloud.com/samfeldt/sam-feldt-x-lucas-steve-feat-wulf-summer-on-you-1
* __Content Country:__ GB
* __Content Language:__ en-GB
* __App Language:__ en_GB
* __Service:__ SoundCloud
* __Version:__ 0.27.0
* __OS:__ Linux samsung/p3sxxx/p3s:14/UP1A.231005.007/G998BXXUAGXDA:user/release-keys 14 - 34
*  __Device:__ Samsung Galaxy S21 Ultra / One UI 6.1 - Android 14
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Source error
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:616)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 403
	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:413)
	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:263)
	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:52)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:796)
	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:609)
	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
	at com.google.android.exoplayer2.source.hls.HlsMediaChunk.prepareExtraction(HlsMediaChunk.java:495)
	at com.google.android.exoplayer2.source.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:468)
	at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:437)
	at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:394)
	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

```
</details>
<hr>

> Newpipe does skip to the next song in the queue. 
This is correct, but to some degree annoying, especially since going back to the song before and continuing where it crashed usually works fine.

**Comment by absurdlylongusername** [comment]
Noting this here for better visibility: https://github.com/TeamNewPipe/NewPipe/pull/12418 most likely fixes this
