### ISSUE TITLE
Cannot Play Videos

### ISSUE THREAD

**Issue by U8avY** [TeamNewPipe/NewPipe#9931]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.0

### Steps to reproduce the bug

Tried to play any video through the app, whether on WiFi or mobile data.

### Expected behavior

Video should play

### Actual behavior

Video only shows its thumbnail and presents the bug notification.

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_DECODING_FAILED] occurred while playing https://www.youtube.com/watch?v=t7gxKdRda_Y
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.25.0
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: MediaCodecVideoRenderer error, index=0, format=Format(299, null, null, video/avc, avc1.64002A, 6618203, null, [1920, 1080, 50.0], [-1, -1]), format_supported=YES
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:566)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.video.MediaCodecVideoDecoderException: Decoder failed: c2.exynos.h264.decoder
	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.createDecoderException(MediaCodecVideoRenderer.java:1590)
	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:813)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:989)
	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:490)
	... 4 more
Caused by: android.media.MediaCodec$CodecException: Error 0xe

```
</details>
<hr>

### Affected Android/Custom ROM version

CalyxOS v4.7.1

### Affected device model

Pixel 6 Pro

**Comment by av01d1ngx4** [comment]
Same issue on  [https://github.com/TeamNewPipe/NewPipe/issues/9929]()

**Comment by av01d1ngx4** [comment]
Bug was also reported to Calyx OS which [affected some pixel phones]()https://gitlab.com/CalyxOS/calyxos/-/issues/1541.

**Comment by av01d1ngx4** [comment]
Calyx OS is underway for fixing the bug. Refer to this [link](https://gitlab.com/CalyxOS/calyxos/-/issues/1541)
