### ISSUE TITLE
When I try to download it from the icon below the playing video 

### ISSUE THREAD

**Issue by Maybach86** [TeamNewPipe/NewPipe#9949]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

2,25

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.25.0
* __OS:__ Linux OnePlus/GN2200/OP515AL1:12/RKQ1.211119.001/c150d4_16c64_3c542:user/release-keys 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalArgumentException: Illegal group reference: group index is missing
	at java.util.regex.Matcher.appendEvaluated(Matcher.java:774)
	at java.util.regex.Matcher.appendReplacement(Matcher.java:717)
	at java.util.regex.Matcher.replaceAll(Matcher.java:843)
	at java.lang.String.replaceAll(String.java:2752)
	at org.schabi.newpipe.util.FilenameUtils.createFilename(FilenameUtils.java:67)
	at org.schabi.newpipe.util.FilenameUtils.createFilename(FilenameUtils.java:54)
	at org.schabi.newpipe.download.DownloadDialog.onViewCreated(DownloadDialog.java:286)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3019)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:349)
	at android.app.ActivityThread.main(ActivityThread.java:8241)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

```
</details>
<hr>

### Expected behavior

Start downloading the song.

### Actual behavior

Send me to screen that says this.....## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.25.0
* __OS:__ Linux OnePlus/GN2200/OP515AL1:12/RKQ1.211119.001/c150d4_16c64_3c542:user/release-keys 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalArgumentException: Illegal group reference: group index is missing
	at java.util.regex.Matcher.appendEvaluated(Matcher.java:774)
	at java.util.regex.Matcher.appendReplacement(Matcher.java:717)
	at java.util.regex.Matcher.replaceAll(Matcher.java:843)
	at java.lang.String.replaceAll(String.java:2752)
	at org.schabi.newpipe.util.FilenameUtils.createFilename(FilenameUtils.java:67)
	at org.schabi.newpipe.util.FilenameUtils.createFilename(FilenameUtils.java:54)
	at org.schabi.newpipe.download.DownloadDialog.onViewCreated(DownloadDialog.java:286)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3019)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:349)
	at android.app.ActivityThread.main(ActivityThread.java:8241)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

```
</details>
<hr>

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.25.0
* __OS:__ Linux OnePlus/GN2200/OP515AL1:12/RKQ1.211119.001/c150d4_16c64_3c542:user/release-keys 12 - 31
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalArgumentException: Illegal group reference: group index is missing
	at java.util.regex.Matcher.appendEvaluated(Matcher.java:774)
	at java.util.regex.Matcher.appendReplacement(Matcher.java:717)
	at java.util.regex.Matcher.replaceAll(Matcher.java:843)
	at java.lang.String.replaceAll(String.java:2752)
	at org.schabi.newpipe.util.FilenameUtils.createFilename(FilenameUtils.java:67)
	at org.schabi.newpipe.util.FilenameUtils.createFilename(FilenameUtils.java:54)
	at org.schabi.newpipe.download.DownloadDialog.onViewCreated(DownloadDialog.java:286)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3019)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:349)
	at android.app.ActivityThread.main(ActivityThread.java:8241)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

```
</details>
<hr>

**Comment by av01d1ngx4** [comment]
@Maybach86 Did you enabled Newpipe to access "Files and media" on App permissions (on your phone settings)?
