### ISSUE TITLE
[Bug] Unable to Playback YouTube Videos

### ISSUE THREAD

**Issue by moriel5** [TeamNewPipe/NewPipe#9953]
Device: Razer Phone 2
ROM: Stock (Android 9)
App Version: 0.25.0
Service: Youtube

While I do not know when this may have begub, as due to lack of time and poor networking conditions I usually download the videos and later watch them offline, I can confirm that it is currently impossible to playback any YouTube videos on NewPipe 0.25.0, at least in my region.

Report from a current example:

## Exception
* __User Action:__ play stream
* __Request:__ Player error[type=ERROR_CODE_TIMEOUT] occurred while playing https://www.youtube.com/watch?v=KHvuXZB4-Ow
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ YouTube
* __Version:__ 0.25.0
* __OS:__ Linux razer/cheryl2/aura:9/P-MR2-RC001-RZR-190914/3123:user/release-keys 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
com.google.android.exoplayer2.ExoPlaybackException: Unexpected runtime error
	at com.google.android.exoplayer2.ExoPlayerImpl.setVideoOutputInternal(Unknown Source:108)
	at com.google.android.exoplayer2.ExoPlayerImpl.clearVideoSurface(Unknown Source:7)
	at org.schabi.newpipe.player.ui.VideoPlayerUi$$ExternalSyntheticLambda15.accept(Unknown Source:2)
	at j$.util.Optional.ifPresent(Unknown Source:4)
	at org.schabi.newpipe.player.ui.VideoPlayerUi.clearVideoSurface(Unknown Source:46)
	at org.schabi.newpipe.player.ui.VideoPlayerUi.destroyPlayer(Unknown Source:3)
	at org.schabi.newpipe.player.ui.MainPlayerUi.destroyPlayer(Unknown Source:0)
	at org.schabi.newpipe.player.Player$$ExternalSyntheticLambda26.accept(Unknown Source:2)
	at j$.util.a.forEachRemaining(Unknown Source:19)
	at j$.util.stream.j2.forEachOrdered(Unknown Source:10)
	at org.schabi.newpipe.player.ui.PlayerUiList.call(Unknown Source:6)
	at org.schabi.newpipe.player.Player.destroyPlayer(Unknown Source:18)
	at org.schabi.newpipe.player.Player.destroy(Unknown Source:20)
	at org.schabi.newpipe.player.PlayerService.cleanup(Unknown Source:4)
	at org.schabi.newpipe.player.PlayerService.onDestroy(Unknown Source:11)
	at android.app.ActivityThread.handleStopService(ActivityThread.java:3735)
	at android.app.ActivityThread.access$1700(ActivityThread.java:200)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1693)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6735)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: com.google.android.exoplayer2.ExoTimeoutException: Detaching surface timed out.
	at com.google.android.exoplayer2.ExoPlayerImpl.setVideoOutputInternal(Unknown Source:103)
	... 23 more

```
</details>
<hr>

If this is not an issue with NewPipe or YouTube changing their website code, but merely due to my networking conditions (since I see a timeout cited the reason), feel free to mark this as invalid.

**Comment by moriel5** [comment]
Both, however this can be closed as invalid, since while I have no idea what was the cause, it looks to be something system-side, and unrelated to either NewPipe or anything regarding networking, since it affected all video playback in all apps (I saw this with VLC as well).

Rebooting the device has resolved this.
