### ISSUE TITLE
Lost all history, subscriptions and data

### ISSUE THREAD

**Issue by RustyCobalt36** [TeamNewPipe/NewPipe#9954]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.0

### Steps to reproduce the bug

Reload subscription page, error occurs

## Exception
* __User Action:__ requested feed
* __Request:__ Loading feed
* __Content Country:__ US
* __Content Language:__ en-US
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.25.0
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
java.lang.IllegalStateException: Cannot perform this operation because there is no current transaction.
	at android.database.sqlite.SQLiteSession.throwIfNoTransaction(SQLiteSession.java:917)
	at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:400)
	at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:755)
	at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.endTransaction(FrameworkSQLiteDatabase.java:94)
	at androidx.room.RoomDatabase.internalEndTransaction(RoomDatabase.java:594)
	at androidx.room.RoomDatabase.endTransaction(RoomDatabase.java:584)
	at org.schabi.newpipe.database.feed.dao.FeedDAO_Impl.unlinkStreamsOlderThan(FeedDAO_Impl.java:242)
	at org.schabi.newpipe.local.feed.FeedDatabaseManager.removeOrphansOrOlderStreams(FeedDatabaseManager.kt:113)
	at org.schabi.newpipe.local.feed.FeedDatabaseManager.removeOrphansOrOlderStreams$default(FeedDatabaseManager.kt:112)
	at org.schabi.newpipe.local.feed.service.FeedLoadManager.postProcessFeed$lambda-11(FeedLoadManager.kt:179)
	at org.schabi.newpipe.local.feed.service.FeedLoadManager.$r8$lambda$IW8gNMLA_0SrYIHw54GavLkWKsI(FeedLoadManager.kt:0)
	at org.schabi.newpipe.local.feed.service.FeedLoadManager$$ExternalSyntheticLambda11.run(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableFromRunnable.subscribeActual(CompletableFromRunnable.java:35)
	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2859)
	at io.reactivex.rxjava3.internal.operators.completable.CompletablePeek.subscribeActual(CompletablePeek.java:51)
	at io.reactivex.rxjava3.core.Completable.subscribe(Completable.java:2859)
	at io.reactivex.rxjava3.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
	at io.reactivex.rxjava3.core.Scheduler$DisposeTask.run(Scheduler.java:644)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 13/ calyx os

### Affected device model

Pixel 3a

**Comment by RustyCobalt36** [comment]
This is highly reproducible,
Occurs at every reload of "what's new"/subscription feed reload.
All data is wiped
