### ISSUE TITLE
Connecting to Car via bluetooth causes crash

### ISSUE THREAD

**Issue by TheRedSpy15** [TeamNewPipe/NewPipe#9993]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/TeamNewPipe/NewPipe/releases/latest).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/TeamNewPipe/NewPipe/issues) or [closed](https://github.com/TeamNewPipe/NewPipe/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have read the [FAQ](https://newpipe.net/FAQ/) and my problem isn't listed.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.
- [X] I have read and understood the [contribution guidelines](https://github.com/TeamNewPipe/NewPipe/blob/dev/.github/CONTRIBUTING.md).

### Affected version

0.25.0

### Steps to reproduce the bug

1. Don't have newpipe open in recent apps.
2. Connect to cars stereo via bluetooth.
3. Newpipe crash reporter shows up.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ en-
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.25.0
* __OS:__ Linux samsung/b0qsqw/b0q:13/TP1A.220624.014/S908USQU2CWAI:user/release-keys 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{5c6708d u0 org.schabi.newpipe/.player.PlayerService}
	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2245)
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2216)
	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2508)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1988)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1933)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:839)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:839)
	at androidx.core.content.ContextCompat$Api26Impl$$ExternalSyntheticApiModelOutline0.m(R8$$SyntheticClass:0)
	at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:931)
	at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:703)
	at androidx.media.session.MediaButtonReceiver.onReceive(MediaButtonReceiver.java:115)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4894)
	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2420)
	... 7 more

```
</details>
<hr>

### Affected Android/Custom ROM version

Android 13

### Affected device model

Samsung galaxy s22+

### Additional information

I don't use android auto. Just regular old bluetooth

**Comment by marmotton** [comment]
Same happens here, with a Sony SRS-XB33 bluetooth speaker.

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ US
* __Content Language:__ fr-
* __App Language:__ en_US
* __Service:__ none
* __Version:__ 0.25.1
* __OS:__ Linux Android 13 - 33
<details><summary><b>Crash log </b></summary><p>

```
android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{63d34b4 u0 org.schabi.newpipe/.player.PlayerService}
	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2001)
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1975)
	at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2237)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: android.app.StackTrace: Last startServiceCommon() call for this service was made here
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1915)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1870)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:822)
	at androidx.core.content.ContextCompat$Api26Impl$$ExternalSyntheticApiModelOutline0.m(R8$$SyntheticClass:0)
	at androidx.core.content.ContextCompat$Api26Impl.startForegroundService(ContextCompat.java:931)
	at androidx.core.content.ContextCompat.startForegroundService(ContextCompat.java:703)
	at androidx.media.session.MediaButtonReceiver.onReceive(MediaButtonReceiver.java:115)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:4303)
	at android.app.ActivityThread.-$$Nest$mhandleReceiver(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2149)
	... 7 more

```
</details>
<hr>

**Comment by kt368** [comment]
Same happens here.
Volkswagen RNS510, Android 13, Pixel 7.
Newpipe version 0.25.1.

**Comment by AaronWright3** [comment]
Same here. Happens whether the app is already running or not.
2021 Hyundai Ioniq plug-in hybrid, Android 13, Samsung Galaxy A32 5G.
Newpipe version 0.25.1

**Comment by jeremiah-k** [comment]
Every time I leave in my car I have to disable NewPipe. Force closing doesn't help. After rebooting it crashes again, even if I don't open the app.

Newpipe 0.25.1
2015 Subaru Legacy
Pixel 4a 5G Android 13

**Comment by DstroyerOfWorlds** [comment]
Same issues as above here. It's quite annoying as the error report prevents Spotify from auto-playing, even with a Routine set to open Spotify and play music where I last left off when I connect to my car.

Newpipe 0.25.1
2015 Toyota Camry
Samsung Galaxy S22 Ultra (Android 13)

**Comment by DstroyerOfWorlds** [comment]
> This is likely happening because Newpipe was the last used media app on your device. Try to see if you get this crash, by ensuring another media app was the last one played before you do step 2.

I can confirm that this is not the case in my experience. I can make sure the app is closed, force stopped, and not the last used/played media app but it'll still crash, at least for me.

**Comment by timonoj** [comment]
Thank god, i thought i was going crazy. Happens to me when i use navigation and my Bluetooth headset on the motorbike.

**Comment by timonoj** [comment]
Which version is this fixed on? It just happened again yesterday.
